<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory Barnes">

<title>Answering questions with data - 6&nbsp; t-tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-Nonparametric.html" rel="next">
<link href="./05-Hypothesis_Testing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 6&nbsp; t-tests">
<meta property="og:description" content="">
<meta property="og:image" content="06-ttests_files/figure-html/fig-7-z-vs-t-linear-log-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 6&nbsp; t-tests">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-ttests.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics? Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-MoreFactorialDesigns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#intro" id="toc-intro" class="nav-link active" data-scroll-target="#intro"><span class="header-section-number">6.1</span> Intro</a></li>
  <li><a href="#from-mean-sd-to-signal-over-noise" id="toc-from-mean-sd-to-signal-over-noise" class="nav-link" data-scroll-target="#from-mean-sd-to-signal-over-noise"><span class="header-section-number">6.2</span> From mean &amp; SD to “signal over noise”</a></li>
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test"><span class="header-section-number">6.3</span> One-sample t-test</a>
  <ul class="collapse">
  <li><a href="#comparing-z-and-t" id="toc-comparing-z-and-t" class="nav-link" data-scroll-target="#comparing-z-and-t"><span class="header-section-number">6.3.1</span> Comparing <span class="math inline">\(z\)</span> and <span class="math inline">\(t\)</span></a></li>
  <li><a href="#what-t-represents" id="toc-what-t-represents" class="nav-link" data-scroll-target="#what-t-represents"><span class="header-section-number">6.3.2</span> What t represents</a></li>
  <li><a href="#calculating-t-from-data" id="toc-calculating-t-from-data" class="nav-link" data-scroll-target="#calculating-t-from-data"><span class="header-section-number">6.3.3</span> Calculating t from data</a></li>
  <li><a href="#assumptions-and-what-to-do-when-they-dont-hold" id="toc-assumptions-and-what-to-do-when-they-dont-hold" class="nav-link" data-scroll-target="#assumptions-and-what-to-do-when-they-dont-hold"><span class="header-section-number">6.3.4</span> Assumptions, and what to do when they don’t hold</a></li>
  <li><a href="#how-does-t-behave" id="toc-how-does-t-behave" class="nav-link" data-scroll-target="#how-does-t-behave"><span class="header-section-number">6.3.5</span> How does t behave?</a></li>
  <li><a href="#interpreting-t" id="toc-interpreting-t" class="nav-link" data-scroll-target="#interpreting-t"><span class="header-section-number">6.3.6</span> Interpreting <span class="math inline">\(t\)</span></a></li>
  <li><a href="#getting-the-p-values-for-t-values" id="toc-getting-the-p-values-for-t-values" class="nav-link" data-scroll-target="#getting-the-p-values-for-t-values"><span class="header-section-number">6.3.7</span> Getting the p-values for <span class="math inline">\(t\)</span>-values</a></li>
  <li><a href="#one-tailed-vs.-two-tailed-applied" id="toc-one-tailed-vs.-two-tailed-applied" class="nav-link" data-scroll-target="#one-tailed-vs.-two-tailed-applied"><span class="header-section-number">6.3.8</span> One-tailed vs.&nbsp;two-tailed, applied</a></li>
  <li><a href="#which-one-should-you-use" id="toc-which-one-should-you-use" class="nav-link" data-scroll-target="#which-one-should-you-use"><span class="header-section-number">6.3.9</span> Which one should you use?</a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom"><span class="header-section-number">6.3.10</span> Degrees of freedom</a></li>
  </ul></li>
  <li><a href="#paired-t-beforeafter-or-matched" id="toc-paired-t-beforeafter-or-matched" class="nav-link" data-scroll-target="#paired-t-beforeafter-or-matched"><span class="header-section-number">6.4</span> Paired t: before/after or matched</a>
  <ul class="collapse">
  <li><a href="#calculate-t" id="toc-calculate-t" class="nav-link" data-scroll-target="#calculate-t"><span class="header-section-number">6.4.1</span> Calculate t</a></li>
  <li><a href="#scaling-to-the-full-sample" id="toc-scaling-to-the-full-sample" class="nav-link" data-scroll-target="#scaling-to-the-full-sample"><span class="header-section-number">6.4.2</span> Scaling to the full sample</a></li>
  </ul></li>
  <li><a href="#two-independent-groups" id="toc-two-independent-groups" class="nav-link" data-scroll-target="#two-independent-groups"><span class="header-section-number">6.5</span> Two independent groups</a></li>
  <li><a href="#simulating-data-for-t-tests" id="toc-simulating-data-for-t-tests" class="nav-link" data-scroll-target="#simulating-data-for-t-tests"><span class="header-section-number">6.6</span> Simulating data for t-tests</a>
  <ul class="collapse">
  <li><a href="#simulating-a-one-sample-t-test" id="toc-simulating-a-one-sample-t-test" class="nav-link" data-scroll-target="#simulating-a-one-sample-t-test"><span class="header-section-number">6.6.1</span> Simulating a one-sample t-test</a></li>
  <li><a href="#simulating-a-paired-samples-t-test" id="toc-simulating-a-paired-samples-t-test" class="nav-link" data-scroll-target="#simulating-a-paired-samples-t-test"><span class="header-section-number">6.6.2</span> Simulating a paired samples t-test</a></li>
  <li><a href="#simulating-an-independent-samples-t-test" id="toc-simulating-an-independent-samples-t-test" class="nav-link" data-scroll-target="#simulating-an-independent-samples-t-test"><span class="header-section-number">6.6.3</span> Simulating an independent samples t-test</a></li>
  </ul></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"><span class="header-section-number">6.7</span> Videos</a>
  <ul class="collapse">
  <li><a href="#one-or-two-tailed-tests" id="toc-one-or-two-tailed-tests" class="nav-link" data-scroll-target="#one-or-two-tailed-tests"><span class="header-section-number">6.7.1</span> One or Two tailed tests</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/06-ttests.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 27, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="intro" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="intro"><span class="header-section-number">6.1</span> Intro</h2>
<p>In the early 1900s, William Sealy Gosset joined <strong>Guinness</strong>, then the world’s largest brewery. Guinness hired scientifically trained brewers and gave them latitude to pursue research that improved the product. As production scaled, quality control mattered: a pint should taste the same in Dublin as in Detroit. Until then, hop quality was judged mostly by appearance and smell, which was unreliable. Chemical assays could measure ingredients, but the core problem was statistical. Inference relied on the normal (Z) distribution, which works well when samples are large enough for a normal approximation. In practice, Guinness could not destroy large volumes of beer or ingredients just to test them.</p>
<p>Gosset set out to quantify the extra uncertainty introduced by <strong>small</strong> samples. How much wider is the error around an estimate when <span class="math inline">\(n=10\)</span> instead of <span class="math inline">\(n=1000\)</span>? He derived a new sampling distribution that accounts for small-sample variability, now known as the <strong>Student’s (t) distribution</strong>. Because Guinness restricted external publications, he published the 1908 paper under the pseudonym <strong>“Student”</strong> <span class="citation" data-cites="Student1908">(<a href="#ref-Student1908" role="doc-biblioref">Student 1908</a>)</span>. That is why we still say <strong>Student’s</strong> <span class="math inline">\(t\)</span>-test. The core idea you will use today is the same: measure a signal, scale it by its standard error, and compare the resulting <span class="math inline">\(t\)</span> to the appropriate <span class="math inline">\(t\)</span> distribution for your <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
<p><strong>Why this matters.</strong> We often compare a sample mean to a reference (drinking-water standard, historical average) or compare two conditions (before/after, site A vs site B). A t-test asks whether the observed difference is larger than you would expect from sampling variation alone, given your <span class="math inline">\(n\)</span> and variability.</p>
<p><strong>Three common t-tests you will use.</strong></p>
<ol type="1">
<li><strong>One-sample t-test.</strong> Compare a sample mean to a target (<span class="math inline">\(\mu_0\)</span>).</li>
<li><strong>Paired t-test.</strong> Compare before/after (or matched) measurements on the same units by running a one-sample t on the <em>differences</em>.</li>
<li><strong>Independent-samples t-test (also called two-sample t-test)</strong> Compare means from two groups measured on different units. Use Welch’s test by default when variances differ.</li>
</ol>
<p><strong>What you will report.</strong></p>
<p>Always report:</p>
<ul>
<li>the effect size (mean difference)</li>
<li>a 95% CI, the test statistic with df</li>
<li>and the <span class="math inline">\(p\)</span>-value.</li>
</ul>
<p>Example: “Mean change was (-0.42) units (95% CI [-0.73,-0.11] ;t(11)=-2.92; p=0.014).”</p>
</section>
<section id="from-mean-sd-to-signal-over-noise" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="from-mean-sd-to-signal-over-noise"><span class="header-section-number">6.2</span> From mean &amp; SD to “signal over noise”</h2>
<p>A mean tells you where the center is; the SD tells you how spread out the data are. A mean of 50 could be very representative (if SD is tiny) or nearly meaningless (if SD is huge). You need both.</p>
<p>A simple way to combine them is a ratio:</p>
<p><span class="math display">\[
\frac{\text{mean}}{\text{SD}}
\]</span></p>
<ul>
<li><p>Big numerator, small denominator → big ratio (more confidence that the mean reflects the data).</p></li>
<li><p>Small numerator or big denominator → small ratio (less confidence).</p></li>
</ul>
<p>For instance, mean = 50 with SD = 1 gives 50; mean = 50 with SD = 100 gives 0.5. Same mean, very different stories.</p>
<p>This “signal over noise” pattern shows up everywhere in inference. In general,</p>
<p><span class="math display">\[
\text{statistic}=\frac{\text{effect}}{\text{error}}.
\]</span></p>
<p>For <span class="math inline">\(t\)</span>-tests, we won’t actually use SD in the denominator, we use the <strong>standard error</strong> <span class="math inline">\(SE\)</span>, which is the SD of the sample mean. But the logic is the same: measure a signal, scale it by its uncertainty, and see whether the resulting ratio is unusually large or small under the right <span class="math inline">\(t\)</span> distribution.</p>
<p><span class="math display">\[
t = \frac{\text{effect}}{\text{standard error}} = \frac{\bar{X} - \mu_0}{s / \sqrt{n}}
\]</span></p>
<p>We now turn that ratio into a test statistic for a <em>single mean</em>.</p>
</section>
<section id="one-sample-t-test" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="one-sample-t-test"><span class="header-section-number">6.3</span> One-sample t-test</h2>
<p>Use a one-sample <span class="math inline">\(t\)</span> when you want to test whether a sample mean differs from a reference value (<span class="math inline">\(\mu_0\)</span>). The question: is the observed difference bigger than you’d expect from sampling variability, given <span class="math inline">\(n\)</span> and your sample SD <span class="math inline">\(s\)</span>?</p>
<p><span class="math display">\[
t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}, \qquad df = n-1
\]</span></p>
<p>After calculating <span class="math inline">\(t\)</span> from our data, we compare the observed <span class="math inline">\(t\)</span> to a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-1\)</span> degrees of freedom to get a <span class="math inline">\(p\)</span>-value and a decision at <span class="math inline">\(\alpha\)</span>.</p>
<section id="comparing-z-and-t" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="comparing-z-and-t"><span class="header-section-number">6.3.1</span> Comparing <span class="math inline">\(z\)</span> and <span class="math inline">\(t\)</span></h3>
<p>When the population SD is known (or we have a large enough sample to assume convergence), the ratio is called <span class="math inline">\(z\)</span>; when it’s estimated from the data, it’s <span class="math inline">\(t\)</span>.</p>
<p>Under a known population SD (<span class="math inline">\(\sigma\)</span>), the standardized mean uses the <span class="math inline">\(z\)</span> statistic: <span class="math display">\[
z = \frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}
\]</span></p>
<p>When <span class="math inline">\(\sigma\)</span> is <strong>unknown</strong> (the usual case), we estimate it with the sample SD (<span class="math inline">\(s\)</span>) and use the <span class="math inline">\(t\)</span> statistic: <span class="math display">\[
t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}, \qquad df = n-1
\]</span></p>
<p>Because <span class="math inline">\(s\)</span> varies from sample to sample, the <span class="math inline">\(t\)</span> distribution has <strong>heavier tails</strong> than the standard normal. As <span class="math inline">\(n\)</span> grows, <span class="math inline">\(s\)</span> stabilizes and <span class="math inline">\(t\)</span> <strong>converges</strong> to <span class="math inline">\(z\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7-z-vs-t-linear-log" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7-z-vs-t-linear-log-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.1: Normal (<span class="math inline">\(z\)</span>) vs <span class="math inline">\(t\)</span> distributions: on a linear scale (top), tail differences look small; on a log scale (bottom), the heavy tails of small-<span class="math inline">\(n\)</span> <span class="math inline">\(t\)</span> are clear.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>When is</strong> <span class="math inline">\(z\)</span> appropriate? If the population SD <span class="math inline">\(\sigma\)</span> is known <em>and</em> the sampling distribution of the mean is (approximately) normal, use <span class="math inline">\(z\)</span>. In practice, <span class="math inline">\(\sigma\)</span> is rarely known, so we use <span class="math inline">\(t\)</span> with <span class="math inline">\(s\)</span> and <span class="math inline">\(df=n-1\)</span>.</p>
</div>
</div>
<p><strong>Rule of thumb.</strong> For two-tailed tests at <span class="math inline">\(\alpha=0.05\)</span>:</p>
<ul>
<li><span class="math inline">\(z\)</span> uses critical values <span class="math inline">\(\pm 1.96\)</span>.</li>
<li><span class="math inline">\(t\)</span> is a bit wider for small <span class="math inline">\(n\)</span> (e.g., <span class="math inline">\(df=9 \Rightarrow \pm 2.262\)</span>; <span class="math inline">\(df=29 \Rightarrow \pm 2.045\)</span>), and approaches <span class="math inline">\(\pm 1.96\)</span> as <span class="math inline">\(n\)</span> increases.</li>
</ul>
</section>
<section id="what-t-represents" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="what-t-represents"><span class="header-section-number">6.3.2</span> What t represents</h3>
<p>Either way, the ratio asks the same question: how far is the mean from the reference in SE units?</p>
<p><span class="math inline">\(t\)</span> expresses how far a sample mean is from the hypothesized mean, in <strong>standard error units</strong> (signal over noise):</p>
<p><span class="math display">\[
t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}
\]</span></p>
<p><span class="math inline">\(t\)</span> can be positive or negative depending on direction. Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(t \sim t_{(df=n-1)}\)</span>.<br>
<strong>Rule of thumb:</strong> at <span class="math inline">\(\alpha=.05\)</span> two-tailed, <span class="math inline">\(|t|\gtrsim 2\)</span> is uncommon when <span class="math inline">\(df\approx 20\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Remember, <span class="math inline">\(s/\sqrt{n}\)</span> is the <strong>standard error (SE)</strong>—the standard deviation of the sampling distribution of the mean.</p>
</div>
</div>
<p>Let’s see how <span class="math inline">\(t\)</span> values behave when samples really come from the null hypothesis. Under the null hypothesis, <span class="math inline">\(t\)</span> follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(df = n-1\)</span>.<br>
Large <span class="math inline">\(|t|\)</span> values are rare; with <span class="math inline">\(df \approx 20\)</span>, <span class="math inline">\(|t| \gtrsim 2\)</span> is uncommon at <span class="math inline">\(\alpha = .05\)</span> (two-tailed).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7t-sim" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7t-sim-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.2: Histogram of 1,000 simulated <span class="math inline">\(t\)</span> values (<span class="math inline">\(n=10\)</span>) drawn from a population with <span class="math inline">\(\mu_0=0\)</span>. Most <span class="math inline">\(t\)</span>s cluster near 0; large positive or negative values are rare.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Takeaway:</strong> <span class="math inline">\(t\)</span> measures how far the sample mean is from the null expectation, scaled by its uncertainty. It behaves predictably under <span class="math inline">\(H_0\)</span>, allowing us to decide whether a difference is likely due to chance.</p>
</section>
<section id="calculating-t-from-data" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="calculating-t-from-data"><span class="header-section-number">6.3.3</span> Calculating t from data</h3>
<p>Let’s calculate a one-sample <span class="math inline">\(t\)</span> statistic step by step using a short example. Ten students each took a 5-question true/false quiz (50% expected by chance). Their scores (percent correct) are:</p>
<p><strong>Scores</strong>: 50, 70, 60, 40, 80, 30, 90, 60, 70, 60</p>
<p>By hand, the standard error of the mean is the sample SD divided by the square root of <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[
\text{SEM} = \frac{s}{\sqrt{n}} = \frac{17.92}{\sqrt{10}} = 5.67
\]</span></p>
<p>And <span class="math inline">\(t\)</span> is the difference between the sample mean (61) and the reference value (50, chance level), divided by that SEM:</p>
<p><span class="math display">\[
t = \frac{\bar{X}-\mu_0}{SEM} = \frac{61-50}{5.67} = 1.94
\]</span></p>
<p>We can confirm this with a single R command, <code>t.test(scores, mu = 50)</code>:</p>
<p><strong>Results:</strong> <span class="math inline">\(t(9)=1.94\)</span>, <span class="math inline">\(p=0.0842\)</span>; mean <span class="math inline">\(=61\)</span> (95% CI [48.18, 73.82]).</p>
<p><strong>Interpretation:</strong> The mean (61%) is above chance (50%), but the difference is not statistically significant at <span class="math inline">\(\alpha=.05\)</span>.</p>
<p><strong>Assumptions check:</strong> Observations are independent, and with <span class="math inline">\(n=10\)</span> the data are approximately normal, sufficient for a one-sample <span class="math inline">\(t\)</span>-test.</p>
</section>
<section id="assumptions-and-what-to-do-when-they-dont-hold" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="assumptions-and-what-to-do-when-they-dont-hold"><span class="header-section-number">6.3.4</span> Assumptions, and what to do when they don’t hold</h3>
<p>Every test in this book rests on assumptions. Assumptions are conditions that need to be roughly true for the math behind the test to be trustworthy. There are two different kinds of assumptions.</p>
<p><strong>The universal assumption.</strong> Every single test we cover in this class (one-sample <span class="math inline">\(t\)</span>, paired <span class="math inline">\(t\)</span>, independent <span class="math inline">\(t\)</span>, ANOVA, regression) assumes your observations are <strong>independent</strong> and came from a <strong>sound study design</strong> (a fair sample, not one that systematically favors certain values). This assumption is so constant that from here on, we won’t re-list it test by test. Keep it in the back of your mind, but if an exam or homework question asks you to “list the assumptions of this test,” this isn’t the answer they’re looking for.</p>
<p><strong>Test-specific assumptions.</strong> These come from how a particular test’s math actually works, and they differ test to test. For the one-sample and paired <span class="math inline">\(t\)</span>-tests, the specific assumption is <strong>approximate normality</strong> of the outcome itself (one-sample) or of the difference scores (paired). Why does this matter? The <span class="math inline">\(t\)</span>-distribution we’ve been using to get <span class="math inline">\(p\)</span>-values is <em>derived</em> assuming the sampling distribution of the mean is normal. If your data are badly skewed and your sample is small, that derivation is on shaky ground, and the <span class="math inline">\(p\)</span>-value it hands you may not mean what it claims to mean.</p>
<p><strong>How worried should you be?</strong> It depends enormously on <span class="math inline">\(n\)</span>. With a large sample, the Central Limit Theorem does a lot of the work for you. The sampling distribution of the mean tends toward normal even when individual observations are skewed, so the <span class="math inline">\(t\)</span>-test is fairly <strong>robust</strong> to non-normality once <span class="math inline">\(n\)</span> is reasonably large. A lot of environmental data, particularly field data, instead is from <strong>small samples that are also skewed</strong>. Examples include a handful of expensive water samples, a short list of monitoring wells, five plots you had time to visit before the storm rolled in. Small <span class="math inline">\(n\)</span> and non-normality reinforcing each other is when a <span class="math inline">\(t\)</span>-test’s answer becomes questionable.</p>
<p><strong>What to do about it.</strong> First, look at your data. A histogram or a QQ-plot will usually tell you whether “approximately normal” is a reasonable description or a stretch. You can also run a formal normality test, the <strong>Shapiro-Wilk test</strong> (<code>shapiro.test()</code> in R), which tests <span class="math inline">\(H_0\)</span>: the data came from a normal distribution. Treat it as one more piece of evidence rather than a strict gate though: with a small sample, exactly when a violation matters most, it has low power and will often say “no problem” even when there is one. If your data look like a stretch and your sample is small, you have another option: a <strong>nonparametric test</strong> that doesn’t lean on the normality assumption at all. You’ll meet these nonparametric alternatives in the next chapter, once we’ve covered all three t-test forms below.</p>
</section>
<section id="how-does-t-behave" class="level3" data-number="6.3.5">
<h3 data-number="6.3.5" class="anchored" data-anchor-id="how-does-t-behave"><span class="header-section-number">6.3.5</span> How does t behave?</h3>
<p>Under the null hypothesis (<span class="math inline">\(H_0\)</span> true), <span class="math inline">\(t\)</span> follows a <em>t</em> distribution with degrees of freedom <span class="math inline">\(df = n - 1\)</span>. Large <span class="math inline">\(|t|\)</span> values are rare; extreme sample means are unlikely if <span class="math inline">\(H_0\)</span> is true.</p>
<p>For moderate sample sizes (<span class="math inline">\(df \approx 20\)</span>), a simple rule of thumb is:</p>
<blockquote class="blockquote">
<p>In a two-tailed test at <span class="math inline">\(\alpha = .05\)</span>, <span class="math inline">\(|t| \gtrsim 2\)</span> is uncommon.</p>
</blockquote>
<p>This means values of <span class="math inline">\(t\)</span> beyond roughly <span class="math inline">\(-2\)</span> or <span class="math inline">\(+2\)</span> occur less than 5% of the time under the null. That’s the foundation of the decision rule for <span class="math inline">\(t\)</span> tests: if your observed <span class="math inline">\(t\)</span> lies in those rare tails, you reject <span class="math inline">\(H_0\)</span>.</p>
<p>Remember, if we obtained a single <span class="math inline">\(t\)</span> from one sample we collected, we could consult the chance window in <a href="#fig-7-t-rejection">Figure&nbsp;<span class="quarto-unresolved-ref">fig-7-t-rejection</span></a> below to find out whether the <span class="math inline">\(t\)</span> we obtained from the sample was likely or unlikely to occur by chance.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7-t-rejection" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7-t-rejection-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.3: Two-tailed rejection regions at <span class="math inline">\(\alpha=.05\)</span> for <span class="math inline">\(t_{(df=9)}\)</span>. Shaded tails mark unlikely values under <span class="math inline">\(H_0\)</span>.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpreting-t" class="level3" data-number="6.3.6">
<h3 data-number="6.3.6" class="anchored" data-anchor-id="interpreting-t"><span class="header-section-number">6.3.6</span> Interpreting <span class="math inline">\(t\)</span></h3>
<p>We’re asking whether our sample could plausibly have come from the null distribution: the distribution of <span class="math inline">\(t\)</span>-values we’d see across many samples of size 10, if the true mean were exactly 50 (chance level). <a href="#fig-7tnull">Figure&nbsp;<span class="quarto-unresolved-ref">fig-7tnull</span></a> shows what that distribution looks like, at <span class="math inline">\(df=9\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7tnull" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7tnull-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.4: A distribution of <span class="math inline">\(t\)</span>-values that can occur by chance alone, when there is no difference between the sample and a population</figcaption>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(t\)</span> is most likely to land near zero, which makes sense: this is the distribution of <em>no</em> differences, so most of the time chance alone won’t push it far from 0. Because the distribution is symmetric, a <span class="math inline">\(t\)</span>-value from the null distribution is just as likely to be positive as negative.</p>
<p>That symmetry gives us a few basic probabilities for free:</p>
<ol type="1">
<li><span class="math inline">\(t\)</span> is always zero, positive, or negative, so <span class="math inline">\(p(t=0 \text{ or } t&gt;0 \text{ or } t&lt;0) = 1\)</span>.</li>
<li><span class="math inline">\(p(t \geq 0) = .5\)</span>: half of all <span class="math inline">\(t\)</span>-values are zero or greater.</li>
<li><span class="math inline">\(p(t \leq 0) = .5\)</span>: half are zero or smaller.</li>
</ol>
<p>We can get more precise than a 50/50 split. <a href="#fig-7percentregions">Figure&nbsp;<span class="quarto-unresolved-ref">fig-7percentregions</span></a> divides the same distribution into ten regions, each containing 10% of the distribution. Notice the regions get wider out in the tails: since most <span class="math inline">\(t\)</span>-values cluster near 0, it takes a wider interval out there to capture the same 10%.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7percentregions" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7percentregions-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.5: Splitting the t distribution up into regions each containing 10% of the <span class="math inline">\(t\)</span>-values. The width between the bars narrows as they approach the center of the distribution, where there are more <span class="math inline">\(t\)</span>-values.</figcaption>
</figure>
</div>
</div>
</div>
<p>For example:</p>
<ol type="1">
<li><span class="math inline">\(t \leq -1.38\)</span>: <span class="math inline">\(p = 10\%\)</span></li>
<li><span class="math inline">\(-1.38 \leq t \leq -0.88\)</span>: <span class="math inline">\(p = 10\%\)</span></li>
<li><span class="math inline">\(-0.88 \leq t \leq -0.54\)</span>: <span class="math inline">\(p = 10\%\)</span></li>
<li><span class="math inline">\(t \geq 1.38\)</span>: <span class="math inline">\(p = 10\%\)</span></li>
</ol>
<p>Each range captures the same 10% of the distribution, even though the ranges themselves are different widths.</p>
</section>
<section id="getting-the-p-values-for-t-values" class="level3" data-number="6.3.7">
<h3 data-number="6.3.7" class="anchored" data-anchor-id="getting-the-p-values-for-t-values"><span class="header-section-number">6.3.7</span> Getting the p-values for <span class="math inline">\(t\)</span>-values</h3>
<p>Where do values like these actually come from? Older textbooks put a table in the back of the book; this one doesn’t need one, because software gives you exact <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span> values directly. R, Excel, and <a href="http://www.socscistatistics.com/pvalues/tdistribution.aspx">online calculators</a> all work; you’ll get hands-on practice with this in lab, both with software and by simulation.</p>
<p>Software does need a couple of things from you to compute a <span class="math inline">\(p\)</span>-value correctly: the degrees of freedom, and whether the test is one-tailed or two-tailed. We haven’t covered either yet, so that’s next, starting with one-tailed tests, then two-tailed, then degrees of freedom.</p>
</section>
<section id="one-tailed-vs.-two-tailed-applied" class="level3" data-number="6.3.8">
<h3 data-number="6.3.8" class="anchored" data-anchor-id="one-tailed-vs.-two-tailed-applied"><span class="header-section-number">6.3.8</span> One-tailed vs.&nbsp;two-tailed, applied</h3>
<p>Chapter 5 introduced the concept: a two-tailed test asks whether <span class="math inline">\(\mu\)</span> differs from <span class="math inline">\(\mu_0\)</span> in either direction, while a one-tailed test commits to one direction in advance, and is only justified when your theory already rules out the other direction. Here’s how that choice plays out mechanically for a <span class="math inline">\(t\)</span>-test: it changes the critical value, and therefore the <span class="math inline">\(p\)</span>-value, for the exact same data.</p>
<p>For our quiz-score example (<span class="math inline">\(df=9\)</span>), a one-tailed test only needs to clear 5% of the distribution on one side. A two-tailed test has to clear 2.5% on each side, which pushes the critical value farther out:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7critT" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7critT-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.6: One-tailed critical value at df=9: t-values of 1.83 or greater occur 5% of the time.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7twotailedt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7twotailedt-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.7: Two-tailed critical values at df=9: t-values beyond ±2.26 occur 5% of the time total, 2.5% in each tail.</figcaption>
</figure>
</div>
</div>
</div>
<p>Applied to our actual result, <span class="math inline">\(t(9) = 1.94\)</span>: the one-tailed <span class="math inline">\(p\)</span> is .042, the two-tailed <span class="math inline">\(p\)</span> is .084, exactly double, since a two-tailed test counts the matching extreme region on both sides instead of just one. Here the choice actually changes the decision: one-tailed, this result is significant at <span class="math inline">\(\alpha=.05\)</span>; two-tailed, it isn’t. That’s exactly why a one-tailed test has to be justified by your theory <em>before</em> you see the data, not chosen afterward because it gives the answer you wanted.</p>
</section>
<section id="which-one-should-you-use" class="level3" data-number="6.3.9">
<h3 data-number="6.3.9" class="anchored" data-anchor-id="which-one-should-you-use"><span class="header-section-number">6.3.9</span> Which one should you use?</h3>
<p>Use a one-tailed test only when your theory already rules out the opposite direction; default to two-tailed otherwise (Chapter 5’s rule). There’s a second reason two-tailed is the safer default: a one-tailed critical value is always closer to 0 than a two-tailed one, so routinely running one-tailed tests inflates your long-run Type I error rate above your stated <span class="math inline">\(\alpha\)</span> (recall from Chapter 5: a Type I error means rejecting <span class="math inline">\(H_0\)</span> when it’s actually true). That’s why most researchers default to two-tailed tests even when they do have a directional prediction, and why it’s worth being able to justify your choice rather than picking whichever gives the smaller <span class="math inline">\(p\)</span>-value.</p>
</section>
<section id="degrees-of-freedom" class="level3" data-number="6.3.10">
<h3 data-number="6.3.10" class="anchored" data-anchor-id="degrees-of-freedom"><span class="header-section-number">6.3.10</span> Degrees of freedom</h3>
<p>You’ve probably noticed a number in parentheses every time we report a <span class="math inline">\(t\)</span>-test, like <span class="math inline">\(t(9) = 1.94\)</span>. That’s the degrees of freedom, and it’s worth understanding what it means, not just where to find it.</p>
<p>For one-sample and paired <span class="math inline">\(t\)</span>-tests, <span class="math inline">\(df = n-1\)</span>. In our quiz example, <span class="math inline">\(n=10\)</span> students, so <span class="math inline">\(df=9\)</span>.</p>
<p>Degrees of freedom is both a concept and a correction. The concept: once you’ve estimated something from your data, like the mean, that estimate constrains how many of the numbers are still free to vary. Consider three numbers with a mean of 2: pick the first two freely, say 51 and <span class="math inline">\(-3\)</span>, and the third number is no longer free. It has to be <span class="math inline">\(-42\)</span> for the mean to come out to 2. Two of the three numbers had freedom; the third didn’t. That’s <span class="math inline">\(df=n-1=2\)</span> for three numbers.</p>
<p>The same logic applies to the sample standard deviation. Computing it requires the sample mean first, which uses up one degree of freedom, exactly why the sample SD divides by <span class="math inline">\(n-1\)</span> rather than <span class="math inline">\(n\)</span> (Chapter 1).</p>
<section id="simulating-how-degrees-of-freedom-affects-the-t-distribution" class="level4" data-number="6.3.10.1">
<h4 data-number="6.3.10.1" class="anchored" data-anchor-id="simulating-how-degrees-of-freedom-affects-the-t-distribution"><span class="header-section-number">6.3.10.1</span> Simulating how degrees of freedom affects the <span class="math inline">\(t\)</span> distribution</h4>
<p>We can see the effect of degrees of freedom directly by simulating the <span class="math inline">\(t\)</span> distribution at two different sample sizes. <a href="#fig-7dft">Figure&nbsp;<span class="quarto-unresolved-ref">fig-7dft</span></a> compares <span class="math inline">\(df=9\)</span> (our quiz-score example) to <span class="math inline">\(df=100\)</span> (a much larger sample).</p>
<div class="cell" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-7dft" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7dft-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.8: The width of the t distribution shrinks as sample size and degrees of freedom (from 9 to 100) increases.</figcaption>
</figure>
</div>
</div>
</div>
<p>As degrees of freedom increase, the <span class="math inline">\(t\)</span> distribution gets taller in the middle and narrower in the tails, converging toward the standard normal. That’s the same pattern from “Comparing <span class="math inline">\(z\)</span> and <span class="math inline">\(t\)</span>” earlier: with more data, the sample SD becomes a more reliable estimate of the population SD, so <span class="math inline">\(t\)</span> behaves more like <span class="math inline">\(z\)</span>.</p>
<p>Why <span class="math inline">\(n-1\)</span> and not <span class="math inline">\(n\)</span>? Because <span class="math inline">\(t\)</span> uses the sample SD to estimate the standard error, and that SD calculation already spent one degree of freedom estimating the mean, so the <span class="math inline">\(t\)</span>-distribution is built assuming <span class="math inline">\(n-1\)</span> from the start.</p>
</section>
</section>
</section>
<section id="paired-t-beforeafter-or-matched" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="paired-t-beforeafter-or-matched"><span class="header-section-number">6.4</span> Paired t: before/after or matched</h2>
<p>When the <strong>same units</strong> are measured twice (before/after, matched pairs), the question is whether they <strong>changed</strong>. The natural data unit is the <strong>within-unit difference</strong>.</p>
<p><strong>Design in this worked example.</strong> Ecologists measured <strong>soil moisture (%)</strong> at 20 paired field plots before and after wetland restoration. Each plot was measured twice — once during the dry season before restoration work began, and again one year later. We care whether restoration <strong>increased</strong> soil moisture, which would support plant reestablishment and carbon sequestration.</p>
<p><strong>Define differences and their meaning.</strong> Choose an order and stick to it:</p>
<ul>
<li><span class="math inline">\(d_i = \text{After}_i - \text{Before}_i\)</span></li>
<li><span class="math inline">\(d_i&gt;0\)</span>: plot had <strong>more</strong> soil moisture after restoration (increase)</li>
<li><span class="math inline">\(d_i&lt;0\)</span>: plot had <strong>less</strong> soil moisture after restoration (decrease)</li>
</ul>
<p>This subtraction <strong>cancels between-plot variability</strong> (some plots are naturally wetter than others) and focuses on <strong>within-plot change</strong>.</p>
<p><strong>Test on differences (paired (t)).</strong> Compute one difference per plot, then run a <strong>one-sample</strong> <span class="math inline">\(t\)</span> against 0:</p>
<p><span class="math display">\[
\bar d=\frac{1}{n}\sum_{i=1}^n d_i, \quad
s_d=\text{SD}(d_1,\ldots,d_n), \quad
t = \frac{\bar d - 0}{s_d/\sqrt{n}}, \quad df=n-1.
\]</span></p>
<p>The <strong>sign of <span class="math inline">\(t\)</span></strong> matches <span class="math inline">\(\bar d\)</span> and your difference direction.</p>
<p><strong>Mini walk-through (first 5 plots).</strong> Using the first five plots, <span class="math inline">\(\bar d = 2.8\)</span> and <span class="math inline">\(s_d = 3.42\)</span>. Then <span class="math display">\[
t=\frac{2.8}{3.42/\sqrt{5}} \approx 1.83,\qquad df=4,
\]</span> which (two-tailed) is <strong>not</strong> significant. That’s expected with <span class="math inline">\(n=5\)</span>.</p>
<p><strong>Full sample effect.</strong> With all 20 plots, <span class="math inline">\(\bar d\)</span> is similar but <span class="math inline">\(s_d/\sqrt{n}\)</span> gets smaller, so <span class="math inline">\(t\)</span> increases and the result becomes significant. This is the payoff of pairing: more power from the same number of plots.</p>
<p><strong>What to report.</strong> <span class="math inline">\(\bar d\)</span> (the mean change), a 95% CI, <span class="math inline">\(t(df)\)</span>, and <span class="math inline">\(p\)</span>. Optionally add a standardized effect (Cohen’s <span class="math inline">\(d=\bar d/s_d\)</span>).</p>
<p><strong>R pointers (you’ll do this in lab).</strong></p>
<ul>
<li>Compute differences: <code>d &lt;- after - before</code></li>
<li>Paired <span class="math inline">\(t\)</span>: <code>t.test(d, mu = 0)</code> or <code>t.test(after, before, paired = TRUE)</code></li>
<li>CI for <span class="math inline">\(\bar d\)</span>: from the <code>t.test</code> output</li>
</ul>
<section id="calculate-t" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="calculate-t"><span class="header-section-number">6.4.1</span> Calculate t</h3>
<p>How do we calculate <span class="math inline">\(t\)</span> for a paired-samples <span class="math inline">\(t\)</span>-test? We use the exact same one-sample <span class="math inline">\(t\)</span>-test formula from the previous section, just applied to the difference scores instead of raw scores. The paired-samples <span class="math inline">\(t\)</span>-test is really just a variation on the one-sample <span class="math inline">\(t\)</span>-test: there’s still only one group of numbers involved, the differences.</p>
<p>Let’s find <span class="math inline">\(t\)</span> for the mean difference scores:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">plot</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Before</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">After</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">differences</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff_from_mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Squared_differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">0.2</td>
<td style="text-align: left;">0.0400000000000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">26</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">3.2</td>
<td style="text-align: left;">10.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">-5.8</td>
<td style="text-align: left;">33.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">102</td>
<td style="text-align: left;">116</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">46.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">20.4</td>
<td style="text-align: left;">23.2</td>
<td style="text-align: left;">2.8</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">9.36</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">sd</td>
<td style="text-align: left;">3.421</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">SEM</td>
<td style="text-align: left;">1.53</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">t</td>
<td style="text-align: left;">1.83006535947712</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>If we did this test using R, we would obtain almost the same numbers (there is a little bit of rounding in the table).</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Paired t-test on 5 restoration plots</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0.141</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Our t-test results are: t(4) = 1.83, p = .141.</p>
<p>The sign of <span class="math inline">\(t\)</span> matches the sign of the mean difference (ours was <span class="math inline">\(+2.8\)</span> percentage points), so soil moisture increased on average, exactly what <span class="math inline">\(\bar d\)</span> already told us directly. Getting a <span class="math inline">\(p\)</span>-value from this <span class="math inline">\(t\)</span>, and choosing one-tailed vs.&nbsp;two-tailed, works exactly like it did for the one-sample case (see the One-sample <span class="math inline">\(t\)</span>-test section above). Two-tailed, <span class="math inline">\(p=.141\)</span>: not significant, this five-plot sample is too small to rule out chance.</p>
</section>
<section id="scaling-to-the-full-sample" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="scaling-to-the-full-sample"><span class="header-section-number">6.4.2</span> Scaling to the full sample</h3>
<p>The five plots above are a subset of the full restoration study, which measured all <strong>20</strong> paired plots. With only <span class="math inline">\(n=5\)</span>, <span class="math inline">\(t(4)=1.83\)</span> wasn’t enough to distinguish the observed increase from chance (<span class="math inline">\(p=.141\)</span>). Here’s what changes with the full sample.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Paired t-test on all 20 restoration plots</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">0.022</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>At <span class="math inline">\(n=20\)</span>, <span class="math inline">\(t(19) = 2.5\)</span>, <span class="math inline">\(p = 0.022\)</span>: significant. The mean difference (1.9 percentage points) is in the same range as what the 5-plot subset already suggested; what changed is the standard error, which shrank enough with the larger sample to rule out chance. This is the payoff of pairing: same design, more plots, more power to detect a real effect.</p>
</section>
</section>
<section id="two-independent-groups" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="two-independent-groups"><span class="header-section-number">6.5</span> Two independent groups</h2>
<p>The independent-samples <span class="math inline">\(t\)</span>-test is the third and last design in this chapter. The logic is the same as the one-sample and paired cases: a mean difference divided by an estimate of its variability. What changes is the research design.</p>
<p>Use an independent-samples <span class="math inline">\(t\)</span>-test for a <strong>between-subjects</strong> design: different people or units in each condition, each measured once. With two groups of 10, that’s 20 people total, none of them paired. Without repeated measures on the same unit, there’s no meaningful way to subtract scores between conditions the way the paired <span class="math inline">\(t\)</span>-test does.</p>
<p>The numerator works the same way it always has: the mean difference between groups. The denominator is where independent groups differ from the paired case, since now we need a single estimate of variability built from two separate samples instead of one.</p>
<p>A natural first guess is to average the two groups’ standard errors:</p>
<p><span class="math display">\[
t = \frac{\bar{A}-\bar{B}}{\left(\dfrac{SEM_A+SEM_B}{2}\right)}
\]</span></p>
<p>That average, however, is a biased estimator of the variability under the null. Instead, the independent-samples <span class="math inline">\(t\)</span>-test <strong>pools</strong> the two groups’ variances, weighted by their degrees of freedom, into a single estimate for the denominator:</p>
<p><span class="math display">\[
t = \frac{\bar{X}_A-\bar{X}_B}{s_p\sqrt{\dfrac{1}{n_A}+\dfrac{1}{n_B}}}
\]</span></p>
<p>where the pooled standard deviation <span class="math inline">\(s_p\)</span> is (note <span class="math inline">\(s_A^2\)</span> and <span class="math inline">\(s_B^2\)</span> here are variances, not standard deviations):</p>
<p><span class="math display">\[
s_p = \sqrt{\frac{(n_A-1)s_A^2 + (n_B-1)s_B^2}{n_A+n_B-2}}
\]</span></p>
<p>The example below computes <span class="math inline">\(t\)</span> for two small groups by following that formula step by step in R, then checks it against <code>t.test()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="do">## By "hand" using R</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">9</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>mean_difference <span class="ot">&lt;-</span> <span class="fu">mean</span>(a)<span class="sc">-</span><span class="fu">mean</span>(b) <span class="co"># compute mean difference</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>variance_a <span class="ot">&lt;-</span> <span class="fu">var</span>(a) <span class="co"># compute variance for A</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>variance_b <span class="ot">&lt;-</span> <span class="fu">var</span>(b) <span class="co"># compute variance for B</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute top part and bottom part of sp formula</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>sp_numerator <span class="ot">&lt;-</span> (<span class="dv">4</span><span class="sc">*</span>variance_a <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span> variance_b) </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>sp_denominator <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">+</span><span class="dv">5-2</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sp_numerator<span class="sc">/</span>sp_denominator) <span class="co"># compute sp</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># compute t following the formula</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> mean_difference <span class="sc">/</span> ( sp <span class="sc">*</span> <span class="fu">sqrt</span>( (<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>) <span class="sc">+</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>) ) )</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>t <span class="co"># print results</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -2.017991</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># using the R function t.test</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a,b, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Two Sample t-test</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; data:  a and b</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t = -2.018, df = 8, p-value = 0.0783</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; alternative hypothesis: true difference in means is not equal to 0</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  -5.5710785  0.3710785</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample estimates:</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; mean of x mean of y </span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       3.0       5.6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulating-data-for-t-tests" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="simulating-data-for-t-tests"><span class="header-section-number">6.6</span> Simulating data for t-tests</h2>
<p>An “advanced” topic for <span class="math inline">\(t\)</span>-tests is the idea of using R to conduct simulations for <span class="math inline">\(t\)</span>-tests.</p>
<p>If you recall, <span class="math inline">\(t\)</span> is a property of a sample. We calculate <span class="math inline">\(t\)</span> from our sample. The <span class="math inline">\(t\)</span> distribution is the hypothetical behavior of our sample. That is, if we had taken thousands upon thousands of samples, and calculated <span class="math inline">\(t\)</span> for each one, and then looked at the distribution of those <span class="math inline">\(t\)</span>’s, we would have the sampling distribution of <span class="math inline">\(t\)</span>!</p>
<p>It can be very useful to get in the habit of using R to simulate data under certain conditions, to see how your sample data, and things like <span class="math inline">\(t\)</span> behave. Why is this useful? It mainly prepares you with some intuitions about how sampling error (random chance) can influence your results, given specific parameters of your design, such as sample-size, the size of the mean difference you expect to find in your data, and the amount of variation you might find. These methods can be used formally to conduct power-analyses. Or more informally for data sense.</p>
<section id="simulating-a-one-sample-t-test" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="simulating-a-one-sample-t-test"><span class="header-section-number">6.6.1</span> Simulating a one-sample t-test</h3>
<p>Here are the steps you might follow to simulate data for a one sample <span class="math inline">\(t\)</span>-test.</p>
<ol type="1">
<li><p>Make some assumptions about what your sample (that you might be planning to collect) might look like. For example, you might be planning to collect 30 subjects worth of data. The scores of those data points might come from a normal distribution (mean = 50, sd = 10).</p></li>
<li><p>sample simulated numbers from the distribution, then conduct a <span class="math inline">\(t\)</span>-test on the simulated numbers. Save the statistics you want (such as <span class="math inline">\(t\)</span>s and <span class="math inline">\(p\)</span>s), and then see how things behave.</p></li>
</ol>
<p>Let’s do this a couple different times. First, let’s simulate samples with N = 30, taken from a normal (mean= 50, sd = 25). We’ll do a simulation with 1000 simulations. For each simulation, we will compare the sample mean with a population mean of 50. There should be no difference on average here. <a href="#fig-7nullt">Figure&nbsp;<span class="quarto-unresolved-ref">fig-7nullt</span></a> is the null distribution that we are simulating.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7nullt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7nullt-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.9: The distribution of <span class="math inline">\(t\)</span>-values under the null. These are the <span class="math inline">\(t\)</span> values that are produced by chance alone.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7flatp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7flatp-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.10: The distribution of <span class="math inline">\(p\)</span>-values that are observed is flat under the null.</figcaption>
</figure>
</div>
</div>
</div>
<p>The simulated <span class="math inline">\(t\)</span> distribution looks like a <span class="math inline">\(t\)</span> distribution should, and it shows us how often we get <span class="math inline">\(t\)</span> values of particular sizes. The <span class="math inline">\(p\)</span>-distribution is flat under the null, which we are simulating here. This means you have the same chance of getting a <span class="math inline">\(t\)</span> with a p-value between 0 and 0.05 as you would of getting one between .90 and .95. Those ranges are both ranges of 5%, so there are an equal amount of <span class="math inline">\(t\)</span> values in them by definition.</p>
<p>You can write the same simulation more compactly with <code>replicate()</code> instead of a <code>for</code> loop; it produces the same two distributions above:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>simulated_ts <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">t.test</span>(<span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">50</span>, <span class="dv">25</span>), <span class="at">mu =</span> <span class="dv">50</span>)<span class="sc">$</span>statistic)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>simulated_ps <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">t.test</span>(<span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">50</span>, <span class="dv">25</span>), <span class="at">mu =</span> <span class="dv">50</span>)<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulating-a-paired-samples-t-test" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="simulating-a-paired-samples-t-test"><span class="header-section-number">6.6.2</span> Simulating a paired samples t-test</h3>
<p>The code below is set up to sample 10 scores for condition A and B from the same normal distribution. The simulation is conducted 1000 times, and the <span class="math inline">\(t\)</span>s and <span class="math inline">\(p\)</span>s are saved and plotted for each.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simts1000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7simts1000-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.11: 1000 simulated ts from the null distribution</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simps1000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7simps1000-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.12: 1000 simulated ps from the null distribution</figcaption>
</figure>
</div>
</div>
</div>
<p>According to the simulation, when there are no differences between the conditions, and the samples are being pulled from the very same distribution, you get these two distributions for <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span>. These again show how the null distribution of no differences behaves.</p>
<p>For any of these simulations, if you rejected the null-hypothesis (that your difference was only due to chance), you would be making a type I error. If you set your alpha criteria to <span class="math inline">\(\alpha = .05\)</span>, we can ask how many type I errors were made in these 1000 simulations. The answer is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 51</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.051</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We happened to make 51 type I errors. The expectation over the long run is a 5% type I error rate (if your alpha is .05).</p>
<p>What happens if there actually is a difference in the simulated data, let’s set one condition to have a larger mean than the other:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">13</span>,<span class="dv">5</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simtrueps" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7simtrueps-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.13: 1000 ps when there is a true difference</figcaption>
</figure>
</div>
</div>
</div>
<p>Now you can see that the <span class="math inline">\(p\)</span>-value distribution is skewed to the left. This is because when there is a true effect, you will get p-values that are less than .05 more often. Or, rather, you get larger <span class="math inline">\(t\)</span> values than you normally would if there were no differences.</p>
<p>In this case, we wouldn’t be making a type I error if we rejected the null when p was smaller than .05. How many times would we do that out of our 1000 experiments?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 216</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.216</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We happened to get 216 simulations where p was less than .05, that’s only 0.216 of experiments. If you were the researcher, would you want to run an experiment that would be successful only 0.216 of the time? Probably not, that’s the case for designing a better experiment.</p>
<p>How would you run a better simulated experiment? Well, you could increase <span class="math inline">\(n\)</span>, the number of subjects in the experiment. Let’s increase <span class="math inline">\(n\)</span> from 10 to 100, and see what happens to the number of “significant” simulated experiments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>,<span class="dv">13</span>,<span class="dv">5</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<pre><code>#&gt; [1] 990
#&gt; [1] 0.99</code></pre>
<div class="cell-output-display">
<div id="fig-7simpsB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7simpsB-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.14: 1000 ps for n =100, when there is a true effect</figcaption>
</figure>
</div>
</div>
</div>
<p>Now almost all of the experiments show a <span class="math inline">\(p\)</span>-value of less than .05 (using a two-tailed test, the default in R). You can use this simulation process to determine how many subjects you need to reliably detect your effect.</p>
</section>
<section id="simulating-an-independent-samples-t-test" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="simulating-an-independent-samples-t-test"><span class="header-section-number">6.6.3</span> Simulating an independent samples t-test</h3>
<p>The setup is the same, you just change what goes into <code>t.test()</code>. Here’s the null case, assuming no difference between two independent groups of <span class="math inline">\(n=10\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  group_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  group_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(group_A, group_B, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<pre><code>#&gt; [1] 51
#&gt; [1] 0.051</code></pre>
<div class="cell-output-display">
<div id="fig-7simpsC" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-7simpsC-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6.15: 1000 ps for the independent-samples null, n=10 per group</figcaption>
</figure>
</div>
</div>
</div>
<p>Same story as before: about 5% of these simulated experiments come out “significant” by chance alone. And the same two levers we saw for the paired test still apply here, giving <code>group_A</code> and <code>group_B</code> different means will pull power up, and so will increasing <span class="math inline">\(n\)</span>. Try editing the code above to see it for yourself.</p>
</section>
</section>
<section id="videos" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="videos"><span class="header-section-number">6.7</span> Videos</h2>
<section id="one-or-two-tailed-tests" class="level3" data-number="6.7.1">
<h3 data-number="6.7.1" class="anchored" data-anchor-id="one-or-two-tailed-tests"><span class="header-section-number">6.7.1</span> One or Two tailed tests</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/PuoGsguuY30" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
<div id="ref-Student1908" class="csl-entry" role="listitem">
Student, A. 1908. <span>“The Probable Error of a Mean.”</span> <em>Biometrika</em> 6: 1–2.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-Hypothesis_Testing.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-Nonparametric.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>