<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>Answering questions with data - 12&nbsp; Analysis of Covariance (ANCOVA)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-MoreFactorialDesigns.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 12&nbsp; Analysis of Covariance (ANCOVA)">
<meta property="og:description" content="">
<meta property="og:image" content="12-ANCOVA_files/figure-html/unnamed-chunk-4-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 12&nbsp; Analysis of Covariance (ANCOVA)">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-ANCOVA.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics? Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-MoreFactorialDesigns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ANCOVA.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#moving-beyond-regression-and-anova-to-ancova" id="toc-moving-beyond-regression-and-anova-to-ancova" class="nav-link active" data-scroll-target="#moving-beyond-regression-and-anova-to-ancova"><span class="header-section-number">12.1</span> Moving Beyond Regression and ANOVA to ANCOVA</a>
  <ul class="collapse">
  <li><a href="#conceptual-background-for-ancova" id="toc-conceptual-background-for-ancova" class="nav-link" data-scroll-target="#conceptual-background-for-ancova"><span class="header-section-number">12.1.1</span> Conceptual Background for ANCOVA</a></li>
  <li><a href="#terminology-in-lms" id="toc-terminology-in-lms" class="nav-link" data-scroll-target="#terminology-in-lms"><span class="header-section-number">12.1.2</span> Terminology in LMs</a></li>
  </ul></li>
  <li><a href="#what-ancova-is" id="toc-what-ancova-is" class="nav-link" data-scroll-target="#what-ancova-is"><span class="header-section-number">12.2</span> What ANCOVA Is</a>
  <ul class="collapse">
  <li><a href="#the-null-hypothesis-in-ancova" id="toc-the-null-hypothesis-in-ancova" class="nav-link" data-scroll-target="#the-null-hypothesis-in-ancova"><span class="header-section-number">12.2.1</span> The Null Hypothesis in ANCOVA</a></li>
  <li><a href="#conducting-the-test" id="toc-conducting-the-test" class="nav-link" data-scroll-target="#conducting-the-test"><span class="header-section-number">12.2.2</span> Conducting the Test</a></li>
  </ul></li>
  <li><a href="#full-ancova-example" id="toc-full-ancova-example" class="nav-link" data-scroll-target="#full-ancova-example"><span class="header-section-number">12.3</span> Full ANCOVA Example</a>
  <ul class="collapse">
  <li><a href="#question" id="toc-question" class="nav-link" data-scroll-target="#question"><span class="header-section-number">12.3.1</span> Question</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model"><span class="header-section-number">12.3.2</span> Model</a></li>
  <li><a href="#why-were-running-the-ancova" id="toc-why-were-running-the-ancova" class="nav-link" data-scroll-target="#why-were-running-the-ancova"><span class="header-section-number">12.3.3</span> Why We’re Running the ANCOVA</a></li>
  <li><a href="#null-and-alternative-hypotheses-in-our-example-ancova" id="toc-null-and-alternative-hypotheses-in-our-example-ancova" class="nav-link" data-scroll-target="#null-and-alternative-hypotheses-in-our-example-ancova"><span class="header-section-number">12.3.4</span> Null and Alternative Hypotheses in our example ANCOVA</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">12.3.5</span> Analysis</a></li>
  <li><a href="#results-of-the-ancova-model" id="toc-results-of-the-ancova-model" class="nav-link" data-scroll-target="#results-of-the-ancova-model"><span class="header-section-number">12.3.6</span> Results of the ANCOVA Model</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">12.4</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/12-ANCOVA.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 21, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<p><strong>ANCOVA</strong> uses the same linear model ideas from regression, with one continuous covariate and one categorical factor. We first test whether groups have different <strong>slopes</strong> with respect to the covariate, then, only if slopes are parallel, we test whether groups differ in <strong>adjusted means</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Going deeper.</strong> T-tests, ANOVA, regression, and ANCOVA are all special cases of one underlying framework, the <strong>general linear model</strong>. Seeing that unification — and the indicator (dummy) variable mechanics that make it work — is genuinely useful, but it’s a level of abstraction that belongs in a second statistics course, not a first one. If you want to go there, see the out-of-sequence chapter <em>“The Linear Model Framework: Dummy Variables and Interactions”</em> in this book’s repository.</p>
</div>
</div>
<section id="moving-beyond-regression-and-anova-to-ancova" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="moving-beyond-regression-and-anova-to-ancova"><span class="header-section-number">12.1</span> Moving Beyond Regression and ANOVA to ANCOVA</h2>
<p>As we’ve explored statistical modeling, we’ve understood the power of both regression and ANOVA. Now, let’s merge them. ANCOVA allows us to examine relationships across different categories.</p>
<p>Consider these questions that may arise in environmental research:</p>
<ul>
<li><p>Are dbh (Diameter at Breast Height) and height related similarly for tulip poplars and oaks?</p></li>
<li><p>Are biomass and BTUs (British Thermal Units) related similarly for corn stover and Miscanthus?</p></li>
<li><p>Does the exposure to PFAS correlate with the lifetime incidence of cancer uniformly across low- and high-income American populations?</p></li>
</ul>
<p>This specific subsection of general linear models is known as <strong>Analysis of Covariance – ANCOVA</strong>. ANCOVA is a linear model with one continuous covariate and one categorical factor; it tests group differences <strong>after</strong> adjusting for the covariate and, first, whether slopes differ across groups.</p>
<section id="conceptual-background-for-ancova" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="conceptual-background-for-ancova"><span class="header-section-number">12.1.1</span> Conceptual Background for ANCOVA</h3>
<p>At its core, ANCOVA checks whether groups share the same line, or whether each group needs its own slope and intercept. That’s exactly what the interaction test below is doing — so keep the picture of “one shared line vs.&nbsp;two separate lines” in mind as we go.</p>
</section>
<section id="terminology-in-lms" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="terminology-in-lms"><span class="header-section-number">12.1.2</span> Terminology in LMs</h3>
<p>A few key terms help clarify how variables play different roles in linear models:</p>
<ul>
<li><p><strong>Fixed factor:</strong> A categorical variable with specific, intentional levels chosen by the researcher.</p>
<p><em>Example:</em> comparing plant growth across seasons (spring, summer, autumn, winter). Each season is a fixed, predefined category of interest.</p></li>
<li><p><strong>Random factor:</strong> A categorical variable whose levels represent a random sample from a larger population.</p>
<p><em>Example:</em> if tree plots are randomly selected from many possible sites, “plot” is a random factor because it reflects sampling variation rather than a treatment.</p></li>
<li><p><strong>Covariate:</strong> A continuous variable that changes alongside the response variable and helps explain part of its variation.</p>
<p>In environmental studies, common covariates include temperature, rainfall, soil moisture, or pollution concentration—factors that may influence the outcome but are not the main treatment of interest.</p>
<p>The purpose of including a covariate is to <strong>adjust for its influence</strong>, allowing a clearer test of the categorical effects once that continuous background variation is accounted for.</p></li>
</ul>
</section>
</section>
<section id="what-ancova-is" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="what-ancova-is"><span class="header-section-number">12.2</span> What ANCOVA Is</h2>
<p><strong>Analysis of Covariance (ANCOVA)</strong> extends ANOVA by adding a continuous predictor. It fits a linear model with both a categorical factor and a covariate, allowing us to compare groups <strong>and</strong> account for how the response changes with the continuous variable.</p>
<p>The covariate may or may not be the main factor of interest. Sometimes we adjust for it, and sometimes we want to see whether its relationship with the response differs across groups.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Two reasons people reach for ANCOVA.</strong> If you look this test up elsewhere, you’ll often see it introduced differently than we’re introducing it here — worth knowing both versions exist:</p>
<ul>
<li><strong>The classic motivation (covariate as a nuisance):</strong> you want to compare groups, but you know a continuous variable is quietly influencing the outcome and could confound the comparison if you ignore it. You add the covariate to <em>control for</em> it, so the group comparison is fairer. Most “which test should I use” flowcharts are built around this version, which is why ANCOVA usually doesn’t get its own branch on them — it’s treated as an add-on decision, not a starting point.</li>
<li><strong>The version we’re emphasizing (covariate as the question):</strong> you actually want to know whether a continuous relationship — like a trend over time — looks different across groups. Here the interaction <em>is</em> the finding, not a nuisance to control away. This is closer to how ANCOVA gets used in a lot of real environmental research (including, often, your own project), which is why this course leads with it.</li>
</ul>
<p>Both are the same test, mechanically. The difference is which term you actually came to interpret.</p>
</div>
</div>
<p>For ANCOVA, you need:</p>
<ol type="1">
<li>A continuous dependent variable (the main effect you’re studying)</li>
<li>At least one continuous independent variable (covariate)</li>
<li>At least one categorical independent variable (which can be either a fixed or random factor)</li>
</ol>
<section id="the-null-hypothesis-in-ancova" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="the-null-hypothesis-in-ancova"><span class="header-section-number">12.2.1</span> The Null Hypothesis in ANCOVA</h3>
<p><strong>Why this matters.</strong> ANCOVA asks two questions in order. First, do groups have the <strong>same slope</strong> for the covariate–response relation. Only if slopes are the same do we ask whether groups differ in <strong>adjusted means</strong> after controlling for the covariate.</p>
<p><strong>Model.</strong> For one covariate (x) and a two-level group indicator <span class="math inline">\(g\in{0,1}\)</span>,</p>
<p><span class="math inline">\(y=\beta_0+\beta_1 x+\beta_2 g+\beta_3(x\times g)+\varepsilon .\)</span></p>
<p><strong>Step 1: Slopes equal across groups?</strong> This tests whether the covariate effect is the same in each group.</p>
<ul>
<li>Null: <span class="math inline">\(H_{0,\text{int}}:\beta_3=0\)</span> (parallel lines, same slope)</li>
<li>Alternative: <span class="math inline">\(H_{A,\text{int}}:\beta_3\neq 0\)</span> (non-parallel lines, different slopes)</li>
</ul>
<p><strong>Interpretation if rejected.</strong> Report the two fitted lines and describe how the slope differs by group. Do not test adjusted means, because the idea of a single adjusted mean per group assumes parallel slopes.</p>
<p><strong>Step 2: Adjusted means equal?</strong> <em>(only if Step 1 retained parallel slopes)</em> Fit the model without the interaction,</p>
<p><span class="math inline">\(y=\beta_0+\beta_1 x+\beta_2 g+\varepsilon .\)</span></p>
<ul>
<li>Null: <span class="math inline">\(H_{0,\text{group}}:\beta_2=0\)</span> (no difference in adjusted means)</li>
<li>Alternative: <span class="math inline">\(H_{A,\text{group}}:\beta_2\neq 0\)</span></li>
</ul>
<p><strong>What the parameters mean.</strong></p>
<ul>
<li><span class="math inline">\(\beta_1\)</span>: common slope of <span class="math inline">\(y\)</span> on <span class="math inline">\(x\)</span> when slopes are parallel.</li>
<li><span class="math inline">\(\beta_2\)</span>: difference in group means <strong>after</strong> adjusting for <span class="math inline">\(x\)</span> (tested only when <span class="math inline">\(\beta_3=0\)</span>).</li>
<li><span class="math inline">\(\beta_3\)</span>: difference in slopes between groups.</li>
</ul>
<p><strong>Intercepts and centering.</strong> Intercepts are evaluated at <span class="math inline">\(x=0\)</span>. Compare intercepts only if you center the covariate, for example <span class="math inline">\(\tilde x=x-\bar x\)</span>, so that the intercepts represent group means at the average covariate value.</p>
<p><strong>What to report.</strong></p>
<ul>
<li>If <span class="math inline">\(x\times g\)</span> is significant: “The effect of <span class="math inline">\(x\)</span> differs by group,” then provide the two line equations and a figure with separate fitted lines.</li>
<li>If <span class="math inline">\(x\times g\)</span> is not significant: report the common slope <span class="math inline">\(\beta_1\)</span> and the adjusted group difference <span class="math inline">\(\beta_2\)</span>, with a figure showing parallel lines.</li>
</ul>
<p><strong>Common pitfalls.</strong></p>
<ul>
<li>Interpreting main effects when the interaction is significant.</li>
<li>Comparing raw intercepts when <span class="math inline">\(x\)</span> is not centered.</li>
<li>Treating adjusted means as meaningful when slopes are not parallel.</li>
</ul>
</section>
<section id="conducting-the-test" class="level3" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="conducting-the-test"><span class="header-section-number">12.2.2</span> Conducting the Test</h3>
<p>When we run an ANCOVA, the output includes an <strong>omnibus F-test</strong>—a single test of whether there are any differences in the adjusted group means after accounting for the covariate.</p>
<p>If this test is <strong>significant</strong>, we reject the overall null hypothesis that all adjusted means are equal.</p>
<p><strong>What happens next:</strong> A significant omnibus test tells us that at least one group differs, but it doesn’t tell us <em>which</em> groups differ or <em>why</em>.</p>
<p>To interpret the result, we must <strong>decompose the omnibus effect</strong> into its components:</p>
<ol type="1">
<li><p><strong>Interaction (slope difference):</strong> Are the slopes of the covariate–response relationship the same across groups?</p></li>
<li><p><strong>Adjusted means (intercept difference):</strong> If the slopes are equal, do the groups still differ in their adjusted means?</p></li>
</ol>
<p>This two-step logic—testing slope equality first, then adjusted means—is central to ANCOVA and parallels how we follow a significant ANOVA with post-hoc comparisons.</p>
<p><strong>Interpreting the Findings:</strong></p>
<p>Rejecting the omnibus null indicates that the categorical factor affects the dependent variable <em>after controlling for the covariate</em>.</p>
<p>However, as always, statistical significance does not guarantee ecological or practical importance. The results should be interpreted in light of the study’s design, measurement precision, and the size of the observed effects.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>ANCOVA ASSUMPTIONS</strong></p>
<ul>
<li>Linearity within each group (covariate–response relation is linear).</li>
<li><strong>Homogeneity of slopes</strong> (test via interaction).</li>
<li>Independent observations.</li>
<li>Approximately normal residuals and similar variances across groups.</li>
<li>Covariate measured without substantial error and not affected by treatment</li>
</ul>
</div>
</div>
</section>
</section>
<section id="full-ancova-example" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="full-ancova-example"><span class="header-section-number">12.3</span> Full ANCOVA Example</h2>
<section id="question" class="level3" data-number="12.3.1">
<h3 data-number="12.3.1" class="anchored" data-anchor-id="question"><span class="header-section-number">12.3.1</span> Question</h3>
<p>Imagine we’re environmental scientists studying the impact of <strong>air pollution</strong> (a continuous variable) on <strong>bird species density</strong> (our dependent variable).</p>
<p>We want to know whether this relationship differs between <strong>urban</strong> and <strong>rural</strong> areas (our categorical variable).</p>
<p>For this purpose, we’ve created a synthetic dataset to model the scenario.</p>
</section>
<section id="model" class="level3" data-number="12.3.2">
<h3 data-number="12.3.2" class="anchored" data-anchor-id="model"><span class="header-section-number">12.3.2</span> Model</h3>
<p>We’ll fit an ANCOVA model to test whether location type influences bird density <strong>after accounting for</strong> air pollution.</p>
<p>The categorical variable (urban vs.&nbsp;rural) is represented as a dummy variable, and air pollution enters as a covariate.</p>
<ul>
<li><strong>Dataset Overview:</strong> 200 observations of bird density across urban and rural sites, each with a measured level of air pollution.</li>
</ul>
</section>
<section id="why-were-running-the-ancova" class="level3" data-number="12.3.3">
<h3 data-number="12.3.3" class="anchored" data-anchor-id="why-were-running-the-ancova"><span class="header-section-number">12.3.3</span> Why We’re Running the ANCOVA</h3>
<ul>
<li><p><strong>Research Question:</strong> Does the effect of air pollution on bird density differ between urban and rural areas?</p></li>
<li><p><strong>Expectation:</strong> Air pollution will have a stronger negative effect in urban areas than in rural areas.</p></li>
</ul>
</section>
<section id="null-and-alternative-hypotheses-in-our-example-ancova" class="level3" data-number="12.3.4">
<h3 data-number="12.3.4" class="anchored" data-anchor-id="null-and-alternative-hypotheses-in-our-example-ancova"><span class="header-section-number">12.3.4</span> Null and Alternative Hypotheses in our example ANCOVA</h3>
<ol start="0" type="1">
<li><p><strong>Omnibus (adjusted means) hypothesis</strong> After adjusting for air pollution, do urban and rural sites differ in mean bird density?</p>
<p><span class="math inline">\(H_{0}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p><span class="math inline">\(H_{A}: \mu_{\text{Urban, adj}} \neq \mu_{\text{Rural, adj}}\)</span></p>
<p>Here, <span class="math inline">\(\mu_{\text{Urban, adj}}\)</span> and <span class="math inline">\(\mu_{\text{Rural, adj}}\)</span> are the <em>adjusted</em> group means once the covariate (air pollution) is accounted for.</p></li>
<li><p><strong>Slope (interaction) hypothesis</strong></p>
<p>Does air pollution affect bird density in the same way across urban and rural sites?</p>
<p><span class="math inline">\(H_{0,1}: \beta_{\text{interaction}} = 0\)</span></p>
<p><span class="math inline">\(H_{A,1}: \beta_{\text{interaction}} \neq 0\)</span></p>
<p>A significant interaction means the slopes differ, and air pollution’s relationship with bird density depends on area type.</p></li>
<li><p><strong>Intercept (baseline difference) hypothesis</strong></p>
<p>If slopes are parallel (interaction not significant), do the adjusted means differ?</p>
<p><span class="math inline">\(H_{0,2}: \beta_{0,\text{Urban}} = \beta_{0,\text{Rural}}\)</span></p>
<p><span class="math inline">\(H_{A,2}: \beta_{0,\text{Urban}} \neq \beta_{0,\text{Rural}}\)</span></p>
<p>Rejecting <span class="math inline">\(H_{0,2}\)</span> indicates an inherent group difference in bird density that is independent of pollution.</p></li>
</ol>
</section>
<section id="analysis" class="level3" data-number="12.3.5">
<h3 data-number="12.3.5" class="anchored" data-anchor-id="analysis"><span class="header-section-number">12.3.5</span> Analysis</h3>
<p>Before we look at the model results, it’s always good practice to <strong>look at the data first</strong>.</p>
<p>Visual inspection helps us check for broad patterns and see whether the model output later “makes sense.”</p>
<p>Let’s start with the response variable—<strong>bird density</strong>. This will give us a quick visual sense of whether urban and rural areas differ in their average values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot for bird density by area type</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(AreaType, BirdDensity)) <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>(<span class="at">base_size=</span><span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bird Density by Area Type"</span>, <span class="at">x =</span> <span class="st">"Area Type"</span>, <span class="at">y =</span> <span class="st">"Bird Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-ANCOVA_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" style="width:75.0%"></p>
</div>
</div>
<p>At first glance, bird density appears <strong>higher in rural areas</strong> than in urban ones, consistent with what we might expect ecologically.</p>
<p>Next, check the <strong>covariate</strong>, air pollution.</p>
<p>If the covariate differs sharply between groups, ANCOVA will “adjust” for that difference.</p>
<p>If it doesn’t, group comparisons will look more like a simple ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(AreaType, AirPollution)) <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>(<span class="at">base_size=</span><span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Air Pollution by Area Type"</span>, <span class="at">x =</span> <span class="st">"Area Type"</span>, <span class="at">y =</span> <span class="st">"Air Pollution"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="12-ANCOVA_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" style="width:75.0%"></p>
</div>
</div>
<p>Air pollution looks fairly similar between urban and rural sites—there’s no obvious systematic difference.</p>
<p>This isn’t diagnostic, but it helps us <strong>anticipate what the model might show</strong>: we may find that group differences in bird density aren’t explained by pollution alone.</p>
</section>
<section id="results-of-the-ancova-model" class="level3" data-number="12.3.6">
<h3 data-number="12.3.6" class="anchored" data-anchor-id="results-of-the-ancova-model"><span class="header-section-number">12.3.6</span> Results of the ANCOVA Model</h3>
<p>Now that we’ve explored the data visually, we can test our hypotheses formally using ANCOVA.</p>
<p><strong>Step 1: Fit the ANCOVA model</strong>.</p>
<p><code>ancova &lt;- aov(BirdDensity ~ AirPollution * AreaType, data = data)</code></p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>ANCOVA Table</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">meansq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AirPollution</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.7690</td>
</tr>
<tr class="even">
<td style="text-align: left;">AreaType</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1687.99</td>
<td style="text-align: right;">1687.99</td>
<td style="text-align: right;">24.79</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AirPollution:AreaType</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">291.26</td>
<td style="text-align: right;">291.26</td>
<td style="text-align: right;">4.28</td>
<td style="text-align: right;">0.0399</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">13347.09</td>
<td style="text-align: right;">68.10</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Step 2: Interpret each term in light of the hypotheses</strong></p>
<p><strong>0. Omnibus (adjusted means)</strong> :</p>
<p><span class="math inline">\(H_{0}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p>The overall ANCOVA test examines whether adjusted means differ between groups after accounting for the covariate.</p>
<p>Because we included an interaction term, this omnibus test is <strong>decomposed</strong> into two parts:</p>
<ul>
<li><p>the <strong>interaction</strong> (slope difference), and</p></li>
<li><p>the <strong>main effects</strong> (covariate and group).</p></li>
</ul>
<p>So we interpret the omnibus test through these individual terms rather than as a separate <span class="math inline">\(p\)</span>-value.</p>
<p><strong>1. Interaction (slope difference)</strong>:</p>
<p><span class="math inline">\(H_{0,1}: \beta_{\text{interaction}} = 0\)</span></p>
<p>The interaction between air pollution and area type is <strong>significant</strong> (<span class="math inline">\(p = 0.0399\)</span>).</p>
<p>Reject <span class="math inline">\(H_{0,1}\)</span> → our slopes are not parallel. Air pollution’s relationship with bird density depends on area type.</p>
<p><strong>2. Covariate (main effect of Air Pollution)</strong></p>
<p>Although not a formal ANCOVA hypothesis, this term tests whether air pollution predicts bird density <em>on average</em>, across both groups.</p>
<p>It is <strong>not significant</strong> (<span class="math inline">\(p = 0.7690\)</span>), so air pollution alone does not explain much variation.</p>
<p><strong>3. Group (main effect of Area Type)</strong> – <span class="math inline">\(H_{0,2}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p>Area type is <strong>significant</strong> (<span class="math inline">\(p &lt; 0.001\)</span>), suggesting lower average bird density in urban areas.</p>
<p>However, because the interaction is significant, this group difference changes with air pollution level, so it should be interpreted conditionally, not as a single overall difference.</p>
<p>Reject <span class="math inline">\(H_{0,2}\)</span> with caution.</p>
<p><strong>Step 3: Examine regression coefficients</strong></p>
<p>We can also fit the same model using <code>lm()</code> to view the <strong>regression coefficients</strong> directly.</p>
<p>This shows how each term contributes to predicting bird density and corresponds to the hypothesis tests we just discussed.</p>
<p><code>ancova_lm &lt;- lm(BirdDensity ~ AirPollution * AreaType, data = data)</code></p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Linear Model Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">31.546</td>
<td style="text-align: right;">2.286</td>
<td style="text-align: right;">13.80</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution</td>
<td style="text-align: right;">-0.043</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">-1.75</td>
<td style="text-align: right;">0.0816</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AreaTypeUrban</td>
<td style="text-align: right;">-11.577</td>
<td style="text-align: right;">3.022</td>
<td style="text-align: right;">-3.83</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution:AreaTypeUrban</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">2.07</td>
<td style="text-align: right;">0.0399</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>R automatically converts the categorical <code>AreaType</code> variable into a 0/1 indicator behind the scenes — it picks one level (here, “Rural,” alphabetically first) as the <strong>reference</strong>, and every coefficient involving <code>AreaType</code> is interpreted relative to that reference. That’s why you see a coefficient called <code>AreaTypeUrban</code> but no separate <code>AreaTypeRural</code> term.</p>
<p>These coefficients give the <em>direction</em> and <em>magnitude</em> of each effect:</p>
<ul>
<li><strong>(Intercept):</strong> estimated mean bird density for rural sites (the reference group) when air pollution is zero.</li>
<li><strong>AirPollution:</strong> slope of the relationship between pollution and bird density in rural sites.</li>
<li><strong>AreaTypeUrban:</strong> difference in intercept between urban and rural areas.</li>
<li><strong>AirPollution:AreaTypeUrban:</strong> difference in slope between urban and rural areas (the interaction).</li>
</ul>
<p><strong>Step 4: Visualize the interaction</strong></p>
<p>As always, plotting helps confirm what the model tells us.</p>
<p>A scatter plot with fitted regression lines lets us see how air pollution relates to bird density for each area type.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="12-ANCOVA_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" style="width:75.0%"></p>
</div>
</div>
<p>Here, the slopes differ by area type, illustrating the <strong>significant interaction</strong> we detected statistically.</p>
<p>You’ll also notice quite a bit of scatter around each line, which makes sense—our overall <span class="math inline">\(R^2\)</span> is only <strong>0.116</strong>.</p>
<p>Remember, <span class="math inline">\(R^2\)</span> represents the <strong>proportion of variance in bird density explained by the model</strong>.</p>
<p>So, about <strong>12% of the variation</strong> in bird density is explained by air pollution, area type, and their interaction.</p>
<p>The remaining 88% reflects other factors, measurement noise, or natural ecological variability not captured by this simple model.</p>
<p><strong>Step 5: Centering the covariate</strong></p>
<p>Interpreting intercepts at <span class="math inline">\(x = 0\)</span> can be misleading when “zero pollution” isn’t meaningful.</p>
<p>By centering the covariate (subtracting its mean), we make the intercept represent <strong>average bird density at mean air pollution</strong> instead.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Centered ANCOVA Model Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">27.814</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution_c</td>
<td style="text-align: right;">-0.043</td>
<td style="text-align: right;">0.0816</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AreaTypeUrban</td>
<td style="text-align: right;">-5.810</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution_c:AreaTypeUrban</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.0399</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>This re-centering doesn’t change the slopes or <span class="math inline">\(p\)</span>-values—it just shifts the intercepts, making them easier to interpret.</p>
<p><strong>Interpreting the Centered Model</strong></p>
<p>Centering does <strong>not</strong> change the slopes or their <span class="math inline">\(p\)</span>-values.</p>
<p>Notice that the coefficients for <code>AirPollution_c</code> (–0.04) and <code>AirPollution_c:AreaTypeUrban</code> (+0.07) are <strong>identical</strong> to the slopes we estimated before centering.</p>
<p>Only the <strong>intercept</strong> and the <strong>AreaTypeUrban</strong> (group difference) term have changed — they are now interpreted at the <em>mean pollution level</em> instead of pollution = 0.</p>
<ul>
<li><p><strong>Intercept (27.8):</strong> Predicted bird density for <strong>rural sites</strong> at <em>average air pollution</em>.</p></li>
<li><p><strong>AreaTypeUrban (–5.8):</strong> Urban sites have, on average, <strong>about 6 fewer birds</strong> than rural sites <em>at the same mean pollution level</em>.</p></li>
<li><p><strong>AirPollution_c (–0.04):</strong> Slope for rural sites — bird density decreases slightly as pollution increases.</p></li>
<li><p><strong>Interaction (+0.07):</strong> Difference in slopes between groups. The urban slope = –0.04 + 0.07 ≈ <strong>+0.03</strong>, meaning bird density increases slightly with pollution in urban areas.</p></li>
</ul>
<p><strong>Step 6: Summarize and Interpret</strong></p>
<p>The significant interaction shows that <strong>air pollution’s effect on bird density depends on area type</strong>: in rural sites, bird density decreases slightly as pollution rises, while in urban sites, it increases slightly.</p>
<p>Because the interaction is significant, we focus on these <strong>different slopes</strong>, not on adjusted mean differences.</p>
<p>If the interaction had <strong>not</strong> been significant, we would instead drop the interaction term and interpret the <strong>parallel slopes model</strong>, comparing adjusted means between groups.</p>
<p>Our results sentences might look something like this:</p>
<p>Results from the ANCOVA indicated that air pollution’s effect on bird density depended on area type, <em>F</em>(1, 196) = 4.28, <em>p</em> = .0399. Bird density declined with increasing pollution in rural sites but showed a slight increase in urban sites. These findings suggest that <strong>urbanization modifies the pollution–bird density relationship</strong> and may point toward the need for area-specific conservation strategies.</p>
<p><strong>Key takeaways</strong></p>
<ol type="1">
<li>Always <strong>check for interaction first</strong></li>
<li>If interaction is <strong>significant</strong>, interpret slope differences.</li>
<li>If not, <strong>fit the reduced model</strong> (no interaction) and compare adjusted means.</li>
<li>Center covariates when the intercept needs to represent a meaningful point.</li>
</ol>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">12.4</span> Chapter Summary</h2>
<p>In this chapter, we introduced <strong>ANCOVA</strong> as an extension of ANOVA that includes continuous covariates. We began by framing ANOVA within the linear modeling framework, showing how ANCOVA builds on it by combining categorical and continuous predictors. Using examples such as bird density across urban and rural environments, we developed and tested null and alternative hypotheses step by step. The main advantage of ANCOVA is its ability to adjust for continuous variables, allowing clearer interpretation of group effects.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./11-MoreFactorialDesigns.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>