# _quarto-pdf.yml
# to run: quarto render --profile pdf

project:
  output-dir: pdf

format:
  pdf:
    documentclass: scrreprt
    fig-format: pdf         # ensure vector figs for LaTeX
    number-sections: true
    toc: true
    lof: true
    lot: false
    output-file: "Answering-questions-with-data.pdf"
    latex-auto-install: true

execute:
  freeze: false             # don't reuse HTML-frozen outputs for PDF
  cache: false              # avoid cross-format cache reuse
  echo: false
  warning: false
  message: false