project:
  type: book
  output-dir: docs

book:
  title: "Answering questions with data"
  source: https://crumplab.com/statistics/
  license: CC BY-SA
  cover-image: imgs/TextbookCover.png
  original-author:
    - "Matthew J. C. Crump"
    - "Danielle J. Navarro"
    - "Jeffrey Suzuki"
  author:
    - name:
        given: Mallory
        family: Barnes
        literal: Mallory Barnes
      affiliations:
        - name: Indiana University Bloomington
          department: Paul H. O'Neill School of Public and Environmental Affairs
          address: 107 S. Indiana Avenue
          city: Bloomington
          region: IN
          postal-code: 47405
          url: https://www.indiana.edu/
      url: https://oneill.indiana.edu/faculty-research/directory/profiles/faculty/full-time/barnes-mallory.html
      email: malbarn@iu.edu
      orcid: 0000-0001-8528-6981
  original-date: "2018-09-01"
  date: last-modified
  abstract: "A free textbook teaching introductory statistics for undergraduates in psychology, including a lab manual, and course website. Licensed on CC BY SA 4.0"
  chapters:
    - index.qmd
    - 01-Science_Data.qmd
    - 02-Describing_Data.qmd
    - 03-Correlation.qmd
    - 04-SamplesPopulations.qmd
    - 05-Foundation_Inference.qmd
    - 06-ttests.qmd
    - 07-ANOVA.qmd
    - 08-RMANOVA.qmd
    - 09-FactorialANOVA.qmd
    - 10-MixedANOVA.qmd
    - 11-Simulation.qmd
    - 12-Thinking.qmd
    - 13-Gifs.qmd
    - references.qmd
  # site-url:
  repo-url: https://github.com/malloryb/statistics_E538
  repo-branch: master
  repo-actions: [edit]
  # google-analytics:
  open-graph: true
  twitter-card:
    site: "@mallory_barnes"
    description: "A free textbook teaching introductory statistics for undergraduates in psychology, including a lab manual, and course website. Licensed on CC BY SA 4.0"
    card-style: "summary"
    image: imgs/TextbookCover.png

bibliography: [StatisticsTextbook.bib]

format:
  html:
    theme: cosmo
    date-modified: last-modified
    license: CC BY-SA
    copyright: Mallory Barnes
  pdf:
    documentclass: scrreprt

editor: visual
