# Preface {.unnumbered}

First Draft (version 0.0 = August 14th, 2023) Last Compiled: `r Sys.Date()`

Welcome to the first edition of this unique Open Educational Resource (OER) textbook, specifically adapted to the needs of Environmental Science students enrolled in the SPEA E-538 statistics course at Indiana University (IU). 

As you delve into this text, you will notice that it is built on the foundation of a comprehensive textbook, originally conceived to teach introductory statistics to undergraduate Psychology students. The masterminds behind this initial project were Matthew Crump and his colleagues. As part of IU's Course Materials Fellowship Program (CMFP), I, Mallory Barnes, have taken the helm to transform the original material into a specialized tool for Environmental Science education.

This adaptation effort was largely supported by IU's CMFP, an initiative designed to incentivize the discovery, implementation, and creation of cost-effective course materials. The goal of this program is to promote the adoption of OERs—openly accessible and customizable learning materials that aim to make education more equitable and accessible.

**Online Textbook**:<https://malloryb.github.io/statistics_E538/>

**Citation for original textbook**: Crump, M. J. C., Navarro, D. J., & Suzuki, J. (2019, June 5). Answering Questions with Data (Textbook): Introductory Statistics for Psychology Students. https://doi.org/10.17605/OSF.IO/JZE52

All resources are released under a creative commons licence [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Click the link to read more about the license, or read more below in the license section.

### Acknowledgements

I would like to extend my gratitude to the numerous contributors of the original textbook who have made this adaptation possible. I am indebted to the expertise and vision of Matthew Crump, Alla Chavarga, Anjali Krishnan, Jeffrey Suzuki, and Stephen Volz, who created an exceptional foundation upon which this project was built.

My heartfelt thanks go to the CMFP at IU and all the educators and administrators who have supported this project throughout its development. I would like to extend a special acknowledgement to Sarah Hare, the Bloomington lead for the CMFP program, and Adam Mazel, a digital publishing librarian at IU. Their guidance, expertise, and unwavering support have been instrumental to this project's fruition, and their contributions to the advancement of affordable and accessible education are truly commendable.

### CC BY-SA 4.0 license

This license means that you are free to:

-   Share: copy and redistribute the material in any medium or format
-   Adapt: remix, transform, and build upon the material for any purpose, even commercially.

The licensor cannot revoke these freedoms as long as you follow the license terms.

Under the following terms:

-   Attribution: You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
-   ShareAlike: If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
-   No additional restrictions: You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

## Copying the textbook

This textbook was written in R-Studio, using R Markdown, and compiled into a web-book format using the bookdown package. In general, I thank the larger R community for all of the amazing tools they made, and for making those tools open, so that I could use them to make this thing.

All of the source code for compiling the book is available from the GitHub repository for the original textbook:

<https://github.com/CrumpLab/statistics>

and my github repository: 

<https://github.com/malloryb/statistics_E538>

In principle, anybody could fork or otherwise download the E-538 textbook, or the original textbook, which is what I did. Load the Rproj file in R-studio, and then compile the entire book. Then, the individual .rmd files for each chapter could be edited for content and style to better suit your needs.

If you want to contribute to this version of the textbook, you could make pull requests on GitHub, or discuss issues and request on the issues tab.

### The vision behind this textbook

The goal of this textbook is twofold. First, it aims to make complex statistical concepts accessible and digestible for students in Environmental Science. Second, it hopes to promote the usage of open-source tools like R, recognizing their value in today's data-driven world.



