<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>1&nbsp; Measuring and Describing Data – Answering questions with data</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02-Correlation.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="1&nbsp; Measuring and Describing Data – Answering questions with data">
<meta property="og:description" content="Adapted to environmental science by Mallory Barnes. Portions adapted from Chapters 1 and 2 in Navarro, D. J. “Learning Statistics with R.” https://compcogscisydney.org/learning-statistics-with-r/">
<meta property="og:image" content="01-Data_Description_files/figure-html/fig-1nominal-landcover-1.png">
<meta property="og:site_name" content="Answering questions with data">
<meta property="og:image:alt" content="Four colored map tiles labeled forest, grassland, wetland, and urban. An arrow points to a fifth, muddy sage-green tile labeled average, annotated as corresponding to no land cover class.">
<meta name="twitter:title" content="1&nbsp; Measuring and Describing Data – Answering questions with data">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-Data_Description.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-role-of-statistics-in-environmental-science" id="toc-the-role-of-statistics-in-environmental-science" class="nav-link active" data-scroll-target="#the-role-of-statistics-in-environmental-science"><span class="header-section-number">1.1</span> The Role of Statistics in Environmental Science</a>
  <ul class="collapse">
  <li><a href="#why-numbers-matter" id="toc-why-numbers-matter" class="nav-link" data-scroll-target="#why-numbers-matter"><span class="header-section-number">1.1.1</span> Why Numbers Matter</a></li>
  </ul></li>
  <li><a href="#introduction-to-measurements" id="toc-introduction-to-measurements" class="nav-link" data-scroll-target="#introduction-to-measurements"><span class="header-section-number">1.2</span> Introduction to measurements</a></li>
  <li><a href="#scales-of-measurement" id="toc-scales-of-measurement" class="nav-link" data-scroll-target="#scales-of-measurement"><span class="header-section-number">1.3</span> Scales of measurement</a>
  <ul class="collapse">
  <li><a href="#nominal-scale" id="toc-nominal-scale" class="nav-link" data-scroll-target="#nominal-scale"><span class="header-section-number">1.3.1</span> Nominal scale</a></li>
  <li><a href="#ordinal-scale" id="toc-ordinal-scale" class="nav-link" data-scroll-target="#ordinal-scale"><span class="header-section-number">1.3.2</span> Ordinal scale</a></li>
  <li><a href="#interval-scale" id="toc-interval-scale" class="nav-link" data-scroll-target="#interval-scale"><span class="header-section-number">1.3.3</span> Interval scale</a></li>
  <li><a href="#ratio-scale" id="toc-ratio-scale" class="nav-link" data-scroll-target="#ratio-scale"><span class="header-section-number">1.3.4</span> Ratio scale</a></li>
  <li><a href="#continuous-versus-discrete-variables" id="toc-continuous-versus-discrete-variables" class="nav-link" data-scroll-target="#continuous-versus-discrete-variables"><span class="header-section-number">1.3.5</span> Continuous versus discrete variables</a></li>
  <li><a href="#a-note-on-real-data" id="toc-a-note-on-real-data" class="nav-link" data-scroll-target="#a-note-on-real-data"><span class="header-section-number">1.3.6</span> A note on real data</a></li>
  </ul></li>
  <li><a href="#the-role-of-variables-predictors-and-outcomes" id="toc-the-role-of-variables-predictors-and-outcomes" class="nav-link" data-scroll-target="#the-role-of-variables-predictors-and-outcomes"><span class="header-section-number">1.4</span> The role of variables: predictors and outcomes</a></li>
  <li><a href="#experimental-and-non-experimental-research" id="toc-experimental-and-non-experimental-research" class="nav-link" data-scroll-target="#experimental-and-non-experimental-research"><span class="header-section-number">1.5</span> Experimental and non-experimental research</a></li>
  <li><a href="#from-measurement-to-description" id="toc-from-measurement-to-description" class="nav-link" data-scroll-target="#from-measurement-to-description"><span class="header-section-number">1.6</span> From measurement to description</a></li>
  <li><a href="#looking-at-the-data" id="toc-looking-at-the-data" class="nav-link" data-scroll-target="#looking-at-the-data"><span class="header-section-number">1.7</span> Looking at the data</a>
  <ul class="collapse">
  <li><a href="#scatter-of-raw-values" id="toc-scatter-of-raw-values" class="nav-link" data-scroll-target="#scatter-of-raw-values"><span class="header-section-number">1.7.1</span> Scatter of raw values</a></li>
  <li><a href="#histograms" id="toc-histograms" class="nav-link" data-scroll-target="#histograms"><span class="header-section-number">1.7.2</span> Histograms</a></li>
  </ul></li>
  <li><a href="#important-ideas-distribution-central-tendency-and-variance" id="toc-important-ideas-distribution-central-tendency-and-variance" class="nav-link" data-scroll-target="#important-ideas-distribution-central-tendency-and-variance"><span class="header-section-number">1.8</span> Important Ideas: Distribution, Central Tendency, and Variance</a></li>
  <li><a href="#measures-of-central-tendency-sameness" id="toc-measures-of-central-tendency-sameness" class="nav-link" data-scroll-target="#measures-of-central-tendency-sameness"><span class="header-section-number">1.9</span> Measures of Central Tendency (Sameness)</a>
  <ul class="collapse">
  <li><a href="#mode" id="toc-mode" class="nav-link" data-scroll-target="#mode"><span class="header-section-number">1.9.1</span> Mode</a></li>
  <li><a href="#median" id="toc-median" class="nav-link" data-scroll-target="#median"><span class="header-section-number">1.9.2</span> Median</a></li>
  <li><a href="#mean" id="toc-mean" class="nav-link" data-scroll-target="#mean"><span class="header-section-number">1.9.3</span> Mean</a></li>
  <li><a href="#what-does-the-mean-mean" id="toc-what-does-the-mean-mean" class="nav-link" data-scroll-target="#what-does-the-mean-mean"><span class="header-section-number">1.9.4</span> What does the mean mean?</a></li>
  <li><a href="#comparing-the-mean-median-and-mode" id="toc-comparing-the-mean-median-and-mode" class="nav-link" data-scroll-target="#comparing-the-mean-median-and-mode"><span class="header-section-number">1.9.5</span> Comparing the mean, median, and mode</a></li>
  </ul></li>
  <li><a href="#measures-of-variation-differentness" id="toc-measures-of-variation-differentness" class="nav-link" data-scroll-target="#measures-of-variation-differentness"><span class="header-section-number">1.10</span> Measures of Variation (Different<em>ness</em>)</a>
  <ul class="collapse">
  <li><a href="#the-range" id="toc-the-range" class="nav-link" data-scroll-target="#the-range"><span class="header-section-number">1.10.1</span> The Range</a></li>
  <li><a href="#difference-scores" id="toc-difference-scores" class="nav-link" data-scroll-target="#difference-scores"><span class="header-section-number">1.10.2</span> Difference Scores</a></li>
  <li><a href="#the-variance" id="toc-the-variance" class="nav-link" data-scroll-target="#the-variance"><span class="header-section-number">1.10.3</span> The Variance</a></li>
  <li><a href="#the-standard-deviation" id="toc-the-standard-deviation" class="nav-link" data-scroll-target="#the-standard-deviation"><span class="header-section-number">1.10.4</span> The Standard Deviation</a></li>
  <li><a href="#sample-versus-population-a-note-on-n---1" id="toc-sample-versus-population-a-note-on-n---1" class="nav-link" data-scroll-target="#sample-versus-population-a-note-on-n---1"><span class="header-section-number">1.10.5</span> Sample versus population: a note on <span class="math inline">\(n - 1\)</span></a></li>
  <li><a href="#mean-absolute-deviation" id="toc-mean-absolute-deviation" class="nav-link" data-scroll-target="#mean-absolute-deviation"><span class="header-section-number">1.10.6</span> Mean Absolute Deviation</a></li>
  </ul></li>
  <li><a href="#remember-to-look-at-your-data" id="toc-remember-to-look-at-your-data" class="nav-link" data-scroll-target="#remember-to-look-at-your-data"><span class="header-section-number">1.11</span> Remember to look at your data</a>
  <ul class="collapse">
  <li><a href="#anscombes-quartet" id="toc-anscombes-quartet" class="nav-link" data-scroll-target="#anscombes-quartet"><span class="header-section-number">1.11.1</span> Anscombe’s Quartet</a></li>
  <li><a href="#datasaurus-dozen" id="toc-datasaurus-dozen" class="nav-link" data-scroll-target="#datasaurus-dozen"><span class="header-section-number">1.11.2</span> Datasaurus Dozen</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">1.12</span> Chapter Summary</a></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"><span class="header-section-number">1.13</span> Videos</a>
  <ul class="collapse">
  <li><a href="#terms-of-statistics" id="toc-terms-of-statistics" class="nav-link" data-scroll-target="#terms-of-statistics"><span class="header-section-number">1.13.1</span> Terms of Statistics</a></li>
  <li><a href="#measures-of-center-mode" id="toc-measures-of-center-mode" class="nav-link" data-scroll-target="#measures-of-center-mode"><span class="header-section-number">1.13.2</span> Measures of center: Mode</a></li>
  <li><a href="#measures-of-center-median-and-mean" id="toc-measures-of-center-median-and-mean" class="nav-link" data-scroll-target="#measures-of-center-median-and-mean"><span class="header-section-number">1.13.3</span> Measures of center: Median and Mean</a></li>
  <li><a href="#standard-deviation-part-i" id="toc-standard-deviation-part-i" class="nav-link" data-scroll-target="#standard-deviation-part-i"><span class="header-section-number">1.13.4</span> Standard deviation part I</a></li>
  <li><a href="#standard-deviation-part-ii" id="toc-standard-deviation-part-ii" class="nav-link" data-scroll-target="#standard-deviation-part-ii"><span class="header-section-number">1.13.5</span> Standard deviation part II</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/01-Data_Description.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 28, 2026</p>
    </div>
  </div>
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Chapter notes</div>
    Adapted to environmental science by Mallory Barnes. Portions adapted from Chapters 1 and 2 in Navarro, D. J. “Learning Statistics with R.” <a href="https://compcogscisydney.org/learning-statistics-with-r/" class="uri">https://compcogscisydney.org/learning-statistics-with-r/</a>
  </div>
</div>


</header>


<blockquote class="blockquote">
<p><em>To call in statisticians after the experiment is done may be no more than asking them to perform a post-mortem examination: They may be able to say what the experiment died of.</em> – Sir Ronald Fisher</p>
</blockquote>
<section id="the-role-of-statistics-in-environmental-science" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="the-role-of-statistics-in-environmental-science"><span class="header-section-number">1.1</span> The Role of Statistics in Environmental Science</h2>
<p>Environmental questions are almost always questions about change. Is this stream warming? Are these bees declining? Did the restoration work? What makes them hard is that the systems involved never sit still to begin with. Streams warm and cool over a single day, bee counts swing with the weather, and vegetation recovers in fits and starts. Something is always changing, so finding a real effect means separating it from all the change that would have happened anyway.</p>
<p>That is the problem statistics exists to solve. It gives you a way to say how much of what you observed is the thing you were looking for, how much is ordinary variation, and how much confidence you should have in telling the two apart. Every environmental claim you will read, make, or have to defend rests on that distinction, whether or not the person making it says so out loud.</p>
<section id="why-numbers-matter" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="why-numbers-matter"><span class="header-section-number">1.1.1</span> Why Numbers Matter</h3>
<p>Common sense is useful, but it is prone to bias. When we already believe something to be true, we are more likely to interpret new evidence as supporting it, even if it does not. This tendency can lead us astray.</p>
<p>For example, if you’re convinced that industrial farming is the main driver of bee declines, you might see every new drop in bee abundance as confirmation of that belief. Maybe you’re right, but maybe disease or weather are stronger contributors. Statistics gives us tools to test these ideas systematically. It helps us separate patterns from noise, avoid being misled by our own expectations, and draw conclusions that are more likely to hold up under scrutiny. It’s not magic, but it makes our conclusions far more reliable.</p>
<p>Another challenge is that the same data can tell very different stories depending on how they are aggregated. <strong>Simpson’s paradox</strong> occurs when a trend seen in combined data reverses after you split the data into meaningful groups.</p>
<p>Here’s a recent example. During the COVID-19 pandemic, early data showed that Italy’s overall case fatality rate was higher than China’s. But, once researchers <em>disaggregated by age group,</em> the trend flipped: within every age group, the fatality rate was actually higher in China. The apparent contradiction was explained by differences in the age distribution of cases <span class="citation" data-cites="vonkügelgen2021">(<a href="#ref-vonkügelgen2021" role="doc-biblioref"><span class="nocase">von Kügelgen et al.</span> 2021</a>)</span>.</p>
<p>Using case fatality rate (CFR), here are some illustrative numbers (made up for teaching).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-simpson-covid-overall" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simpson-covid-overall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-simpson-covid-overall-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simpson-covid-overall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Crude case fatality rates. Italy appears to have a higher fatality rate than China when all cases are combined.
</figcaption>
</figure>
</div>
</div>
</div>
<p>At face value, Italy looks worse. But what happens when we stratify by age group? Because age strongly affects COVID fatality, splitting cases into 10-year bands reveals a different picture. When we do, China’s fatality rate is higher in every band.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-simpson-by-age-group" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simpson-by-age-group-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-simpson-by-age-group-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simpson-by-age-group-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: Fatality rates by age group (same made-up numbers). Within each age band, China’s CFR exceeds Italy’s.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Why the reversal? Italy’s population skews older while China’s skews younger, and baseline risk rises steeply with age. It is not that people in China fared better, it is that Italy had a greater proportion of older people getting sick, which pulls Italy’s overall average up and China’s down. Aggregating without adjusting for age hid the within-group pattern entirely. That is the disciplined check statistics offers: the answer can reverse once you ask the data a more specific question.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-age-distributions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-age-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-age-distributions-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-age-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: Case age distribution by country. Italy’s cases are older on average; China’s are younger.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Sheer volume is the other reason. Satellites measure surface temperature, field stations log rainfall, and sensors track air quality, so a single study can generate thousands of rows. Meanwhile river flow changes by the hour, forests grow unevenly, and human activity layers on more variability still. Statistics is how we compress all of that into something we can reason about, and how we ask whether an apparent change is real or just the fluctuation we would expect anyway.</p>
<p>It would be reasonable to ask why you need to learn this yourself rather than handing the analysis to someone who already knows it. Three reasons:</p>
<ol type="1">
<li><p><strong>Design and analysis go together.</strong> A good study starts long before you run a statistical test. If you want to study how fertilizer affects crop yields, your sampling plan and your analysis are inseparable. Poor design, like measuring only in unusually wet fields, can’t be rescued by sophisticated analysis.</p></li>
<li><p><strong>Understanding the Science:</strong> Scientific papers on climate change, biodiversity, or pollution are built on statistical results. To interpret them, you need to know what the numbers mean.</p></li>
<li><p><strong>Practicality:</strong> Hiring a specialist for every question isn’t realistic. A working knowledge of statistics makes you more self-sufficient, whether you end up working as a scientist, an environmental manager, or a decision-maker who has to evaluate someone else’s analysis.</p></li>
</ol>
<blockquote class="blockquote">
<p><em>“We are drowning in information, but we are starved for knowledge”</em></p>
<p>– Various authors, original probably John Naisbitt</p>
</blockquote>
<p>Finally, none of this is only for researchers, or only for environmental science. Weather forecasts, air quality alerts, and wildlife population trends are all communicated through numbers, and so are the statistical claims that turn up in news coverage, policy debates, and podcasts. Once you can recognize the difference between a correlation and a cause, or spot a claim resting on a sample too small to support it, you start noticing those moves everywhere. A basic knowledge of statistics is what lets you tell whether the numbers support the claim being made, or whether someone is stretching them. In that sense, it is part of being an informed citizen in a data-saturated world.</p>
</section>
</section>
<section id="introduction-to-measurements" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="introduction-to-measurements"><span class="header-section-number">1.2</span> Introduction to measurements</h2>
<p>Every dataset begins with measurement: assigning numbers, labels, or categories to aspects of the world so they can be recorded and analyzed. Science often deals with broad ideas that need to be pinned down before they can be studied. For example, <em>soil health</em> or <em>forest change</em> are meaningful, but vague. To analyze them, we have to decide exactly what we mean and how to capture it. That process is called <strong>operationalization</strong>: turning a general concept into something measurable.</p>
<p>Before moving on, let’s clarify how operationalization fits with three related terms:</p>
<ul>
<li><strong>Operationalization</strong>: the step where you define exactly how a broad idea will be captured with a measure</li>
<li><strong>Measure</strong>: the tool or method used to make observations</li>
<li><strong>Variable</strong>: the actual values you record once the measure is applied. Variables are the actual data that end up in our dataset.</li>
</ul>
<p><strong>Example:</strong></p>
<ul>
<li>Concept of interest: <em>Soil health</em>
<ul>
<li><strong>Operationalization:</strong> concentration of organic carbon in the top 30 cm</li>
<li><strong>Measure:</strong> laboratory analysis of soil samples</li>
<li><strong>Variable:</strong> recorded carbon concentration values for each plot</li>
</ul></li>
</ul>
<p><em>Soil health</em> is the idea we care about, but you cannot go outside and measure an idea. Organic carbon is a defensible stand-in, since healthy soils generally store more of it, but soil health also involves compaction, pH, microbial activity, and how well the soil holds water. So the first decision is which facet will stand in for the whole:</p>
<ul>
<li><strong>Which facet?</strong> ☐ pH ☐ compaction ☑ <strong><em>organic carbon</em></strong> ☐ microbial activity ☐ water-holding capacity</li>
</ul>
<p>Choosing carbon means the other facets go unmeasured. And the choice is not finished, it has only narrowed. How deep will you sample? Thirty centimeters is conventional, but 10 cm or a full meter would give different answers:</p>
<ul>
<li><strong>Sampling depth?</strong> ☐ 10 cm ☑ <strong><em>30 cm</em></strong> ☐ 1 m</li>
</ul>
<p>Then come a dozen more, each one a place where another reasonable person might go the other way:</p>
<ul>
<li><strong>Which carbon counts?</strong> ☑ <strong><em>organic</em></strong> ☐ carbonate minerals ☐ total</li>
<li><strong>How many cores per plot?</strong> ☐ 1 ☐ 3 ☑ <strong><em>6</em></strong> ☐ 9</li>
<li><strong>Where in the plot?</strong> ☐ wherever is easiest ☑ <strong><em>stratified random</em></strong> ☐ along a fixed transect</li>
<li><strong>When in the season?</strong> ☐ spring ☑ <strong><em>after harvest</em></strong> ☐ same calendar date each year</li>
</ul>
<p>Every checked box narrows what “soil health” now means in your dataset, and every unchecked box is a part of soil health your data can no longer speak to. Another researcher could work down the same list, check different boxes, report a different number, and both of you would be right, because you measured different things and gave them the same name.</p>
<p>Operationalization is rarely straightforward, and there is no single correct way to do it. The best choice depends on the question you are asking and how the data will be used. In many fields, scientists have developed common practices, but every project still requires case-by-case judgment. Even so, some principles of good operationalization apply across studies: be precise about what you mean, how you will measure it, and what values are possible.</p>
</section>
<section id="scales-of-measurement" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="scales-of-measurement"><span class="header-section-number">1.3</span> Scales of measurement</h2>
<p>As the previous section indicates, the outcome of a measurement is called a <strong>variable</strong>. Not all variables are the same type, and knowing the type matters because it determines which statistical tools make sense. The four classic scales are <strong>nominal, ordinal, interval,</strong> and <strong>ratio</strong>.</p>
<section id="nominal-scale" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="nominal-scale"><span class="header-section-number">1.3.1</span> Nominal scale</h3>
<p>A <strong>nominal scale</strong> variable (also referred to as a <strong>categorical</strong> variable) is one in which the values are just names. They do not have an inherent order, and it makes no sense to average them.</p>
<p><em>Example:</em> land cover class. A pixel on a satellite map might be classified as forest, grassland, wetland, or urban. None of those is “greater” than another, they cannot be put in a meaningful order, and there is no such thing as an average land cover.</p>
<p>It is worth being precise about <em>why</em>, because the arithmetic itself does not fail. Map classes are drawn in colors, and colors have numeric codes, so a computer will happily average forest, grassland, wetland, and urban and hand you a result. <a href="#fig-1nominal-landcover" class="quarto-xref">Figure&nbsp;<span>1.4</span></a> shows what comes back.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1nominal-landcover" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four colored map tiles labeled forest, grassland, wetland, and urban. An arrow points to a fifth, muddy sage-green tile labeled average, annotated as corresponding to no land cover class.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1nominal-landcover-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-1nominal-landcover-1.png" class="img-fluid figure-img" style="width:88.0%" alt="Four colored map tiles labeled forest, grassland, wetland, and urban. An arrow points to a fifth, muddy sage-green tile labeled average, annotated as corresponding to no land cover class.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1nominal-landcover-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.4: Averaging the color codes of four land cover classes returns a color, but not a land cover class. Nothing on the map is that color.
</figcaption>
</figure>
</div>
</div>
</div>
<p>You get a color back. Nothing on the map is that color, and more importantly there is no class it could represent, because forest and urban have no midpoint. That is what makes a variable nominal: the values are <strong>labels, not quantities</strong>, so arithmetic on them runs perfectly well and tells you nothing. Land cover is unusual in even having numbers attached that <em>could</em> be averaged, and only because someone chose colors for a map. Most nominal variables, like species identity or watershed name, have nothing there to average in the first place.</p>
</section>
<section id="ordinal-scale" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="ordinal-scale"><span class="header-section-number">1.3.2</span> Ordinal scale</h3>
<p><strong>Ordinal scale</strong> variables have a meaningful order, but the spacing between values is not defined mathematically. You can rank the values, but you can’t assume equal steps between them, nor calculate a meaningful average.</p>
<p><em>Example:</em> finishing position in a competition. First place comes before second, and second before third, but the ranks themselves tell you nothing about how far apart the competitors actually were.</p>
<p>An Olympic weightlifting meet makes this concrete, because the thing being ranked is a weight, so we can see both scales at once. <a href="#fig-1ordinal-lifting" class="quarto-xref">Figure&nbsp;<span>1.5</span></a> shows a podium alongside the weights the three athletes actually lifted.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1ordinal-lifting" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A three-step podium with athletes holding bronze, silver, and gold medals, the steps evenly spaced. Dotted guides drop from each athlete to a horizontal kilogram scale below, where third place sits at 71 kg and second and third sit close together at 100 and 102 kg. Brackets label the gaps as 29 kg apart and 2 kg apart.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1ordinal-lifting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-1ordinal-lifting-1.png" class="img-fluid figure-img" style="width:92.0%" alt="A three-step podium with athletes holding bronze, silver, and gold medals, the steps evenly spaced. Dotted guides drop from each athlete to a horizontal kilogram scale below, where third place sits at 71 kg and second and third sit close together at 100 and 102 kg. Brackets label the gaps as 29 kg apart and 2 kg apart.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1ordinal-lifting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.5: The same three athletes shown two ways. On the podium the steps are one place apart and one place apart again. On the scale below, the weights they lifted are 29 kg and 2 kg apart.
</figcaption>
</figure>
</div>
</div>
</div>
<p>On the podium, second place looks exactly as far from first as it does from third. On the scale below, second place is nearly tied with first and nowhere near third. That is the cost of ranking: it keeps the order and throws away the distances. Notice also that a single event gives us both kinds of variable. The finishing place is ordinal, the weight lifted is ratio, and only one of them can be averaged.</p>
</section>
<section id="interval-scale" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="interval-scale"><span class="header-section-number">1.3.3</span> Interval scale</h3>
<p>Interval variables have equal intervals between values, so differences are meaningful. However, zero is arbitrary, so multiplication and division are not valid.</p>
<p><em>Example:</em> temperature in degrees Celsius. A difference of 3<span class="math inline">\(^\circ\)</span> means the same regardless of whether it is 7 → 10 or 15 → 18. But 0<span class="math inline">\(^\circ\)</span>C does not mean “no temperature.” That zero is defined by the freezing point of water, which is a useful convention rather than a fact about heat. So you can say today is 3<span class="math inline">\(^\circ\)</span> warmer than yesterday, but you cannot say 20<span class="math inline">\(^\circ\)</span>C is “twice as hot” as 10<span class="math inline">\(^\circ\)</span>C.</p>
<p><em>Alternate example:</em> calendar years. The ten years from 1990 to 2000 are the same length as the ten years from 2010 to 2020, so differences work fine. But year 0 is a convention we agreed on, not the beginning of time, and other calendars put their zero somewhere else and are equally correct. That is why the year 2000 is not “twice as late” as the year 1000.</p>
</section>
<section id="ratio-scale" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="ratio-scale"><span class="header-section-number">1.3.4</span> Ratio scale</h3>
<p>Ratio scale variables have all the properties of interval variables, plus a true zero, meaning zero really does indicate none of the thing. That is what makes multiplication and division valid.</p>
<p><em>Example:</em> age in years. Zero means no age at all, and someone who is 20 really is twice as old as someone who is 10. Differences (20 – 10 = 10 years) and ratios (20 ÷ 10 = 2) are both meaningful.</p>
<p>Temperature makes an unusually clean comparison here, because the same physical quantity can be recorded on either kind of scale depending on where you put the zero. <a href="#fig-1temp-scales" class="quarto-xref">Figure&nbsp;<span>1.6</span></a> shows both.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1temp-scales" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two vertical temperature scales side by side spanning the same physical range. On the Celsius scale, zero sits near the top with a shaded region of negative temperatures extending far below it. On the Kelvin scale, zero sits at the very bottom, with an arrow noting that nothing colder exists.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1temp-scales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-1temp-scales-1.png" class="img-fluid figure-img" style="width:78.0%" alt="Two vertical temperature scales side by side spanning the same physical range. On the Celsius scale, zero sits near the top with a shaded region of negative temperatures extending far below it. On the Kelvin scale, zero sits at the very bottom, with an arrow noting that nothing colder exists.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1temp-scales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.6: The same physical range of temperatures on two scales. Both rails cover identical ground; only the placement of zero differs. Celsius anchors its zero to the freezing point of water, Kelvin to the absence of thermal energy.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The consequence is easy to check. Going from 10<span class="math inline">\(^\circ\)</span>C to 20<span class="math inline">\(^\circ\)</span>C doubles the Celsius number, so it is tempting to call it twice as hot. On the Kelvin scale those same two temperatures are 283 K and 293 K, an increase of about 3.5%. The physical change is small; the doubling was an artifact of where Celsius happens to put its zero. Kelvin, with a true zero, gives ratios you can trust: 200 K really does carry twice the thermal energy of 100 K.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 23%">
<col style="width: 27%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">can rank</th>
<th style="text-align: center;">can subtract/add</th>
<th style="text-align: center;">can multiply/divide</th>
<th>example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nominal</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td>land cover class</td>
</tr>
<tr class="even">
<td>ordinal</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td>finishing place</td>
</tr>
<tr class="odd">
<td>interval</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;"></td>
<td>temperature (°C)</td>
</tr>
<tr class="even">
<td>ratio</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;">x</td>
<td>age</td>
</tr>
</tbody>
</table>
</section>
<section id="continuous-versus-discrete-variables" class="level3" data-number="1.3.5">
<h3 data-number="1.3.5" class="anchored" data-anchor-id="continuous-versus-discrete-variables"><span class="header-section-number">1.3.5</span> Continuous versus discrete variables</h3>
<p>Another useful distinction is whether a variable can take on values in between others.</p>
<ul>
<li><p>A <strong>continuous variable</strong> can, in principle, take on any value within a range. For example, consider height. If you are 72 inches tall and your friend Cameron is 71 inches tall, Alan could be 71.4 inches and David 71.49 inches. Because we can always imagine a new value in between two others, height is continuous.</p></li>
<li><p>A <strong>discrete variable</strong> is, in effect, a variable that isn’t continuous. Discrete variables have separate, distinct values with nothing in between. Nominal variables are always discrete: there is no land cover class that falls “between” wetland and urban in the same way that 71.4 falls between 71 and 72. Ordinal variables are also discrete: although second place falls between first and third, nothing can logically fall between first and second.</p></li>
</ul>
<p>Interval and ratio variables can be either. Height (a ratio variable) is continuous. But the number of people living in a household (a ratio variable) is discrete: you cannot have 4.2 people. Temperature in degrees Celsius (an interval variable) is also continuous. But the year you started college (an interval variable) is discrete: there is no year between 2022 and 2023.</p>
<p>The table below shows how the scales of measurement relate to this distinction. Cells with an “x” mark what is possible.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">continuous</th>
<th style="text-align: center;">discrete</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nominal</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
</tr>
<tr class="even">
<td>ordinal</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">x</td>
</tr>
<tr class="odd">
<td>interval</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;">x</td>
</tr>
<tr class="even">
<td>ratio</td>
<td style="text-align: center;">x</td>
<td style="text-align: center;">x</td>
</tr>
</tbody>
</table>
</section>
<section id="a-note-on-real-data" class="level3" data-number="1.3.6">
<h3 data-number="1.3.6" class="anchored" data-anchor-id="a-note-on-real-data"><span class="header-section-number">1.3.6</span> A note on real data</h3>
<p>These categories are guides, not hard rules. For example, survey responses on a 1–5 “strongly disagree” to “strongly agree” scale are technically <strong>ordinal</strong>, but researchers often treat them as “quasi-interval” because the spacing is assumed to be roughly equal.</p>
</section>
</section>
<section id="the-role-of-variables-predictors-and-outcomes" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="the-role-of-variables-predictors-and-outcomes"><span class="header-section-number">1.4</span> The role of variables: predictors and outcomes</h2>
<p>One last piece of terminology before we leave variables behind. In most studies we have many variables, but when we analyze them, we usually split them into two roles: the <strong>thing we’re trying to explain</strong> and the <strong>thing doing the explaining</strong>. To keep it straight, we use <span class="math inline">\(Y\)</span> for the variable being explained, and a <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, etc. for the variables used to explain it.</p>
<p>Traditionally, <span class="math inline">\(X\)</span> is called the <strong>indepdendent variable (IV)</strong> and <span class="math inline">\(Y\)</span> is the <strong>dependent variable (DV).</strong> The logic is that if there’s a relationship, <span class="math inline">\(Y\)</span> depends on <span class="math inline">\(X\)</span>. These terms can be clunky and can be confusing because: (a) IVs are rarely actually “independent of everything else” and (b) if there’s no relationship, then the DV doesn’t actually “depend” on the IV at all.</p>
<p>Two alternative vocabularies are often clearer. In experiments, IVs are <strong>manipulations</strong> and DVs are <strong>measurements</strong>. When we are using <span class="math inline">\(X\)</span> to predict <span class="math inline">\(Y\)</span> rather than manipulating anything, the pair is <strong>predictor</strong> and <strong>outcome</strong>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 30%">
<col style="width: 18%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">role of the variable</th>
<th style="text-align: left;">classical name</th>
<th style="text-align: left;">in experiments</th>
<th style="text-align: left;">in prediction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">“to be explained” (<span class="math inline">\(Y\)</span>)</td>
<td style="text-align: left;">dependent variable (DV)</td>
<td style="text-align: left;">measurement</td>
<td style="text-align: left;">outcome</td>
</tr>
<tr class="even">
<td style="text-align: left;">“to do the explaining” (<span class="math inline">\(X\)</span>)</td>
<td style="text-align: left;">independent variable (IV)</td>
<td style="text-align: left;">manipulation</td>
<td style="text-align: left;">predictor</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Which terms this course uses.</strong> You should recognize all three pairs, since all three appear in the literature. This book uses <strong>IV and DV</strong> when comparing groups (<span class="math inline">\(t\)</span>-tests, ANOVA) and <strong>predictor and outcome</strong> for regression, where nothing is manipulated and “independent variable” would mislead. A later chapter switching vocabulary is following the convention of the method, not introducing a new idea.</p>
</div>
</div>
</section>
<section id="experimental-and-non-experimental-research" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="experimental-and-non-experimental-research"><span class="header-section-number">1.5</span> Experimental and non-experimental research</h2>
<p>A central distinction in research is between experimental and non-experimental studies. What matters here is the degree of control the researcher has.</p>
<p>In <strong>experimental research</strong>, the researcher deliberately manipulates something (the predictor/IV) and measures its effect on outcomes (the outcome/DV). The goal is to isolate causal effects. To avoid the problem of “something else” influencing the outcome, researchers try to hold other factors constant. In practice, it’s almost impossible to identify <em>everything</em> that might matter, much less keep it constant. The standard solution is <strong>randomization</strong>. Randomization doesn’t eliminate confounds, but it makes them less likely to systematically bias results.</p>
<p>For instance, suppose we wanted to know if smoking causes lung cancer. Observing smokers and non-smokers can only get us so far, because those groups differ in many ways besides smoking, like occupation, income, and diet. A true experiment would require randomly assigning people to smoke or not. You can see how that would be deeply unethical. The same problem comes up in medicine: we know surprisingly little about how certain drugs or exposures affect pregnant people, precisely because we cannot ethically assign them to risky conditions.</p>
<p>In <strong>environmental science</strong> the limitation is usually not ethics but feasibility. There is no control planet to set aside as a baseline, and nobody can dial precipitation or temperature up and down. So the field leans heavily on <strong>non-experimental research</strong>, which mostly takes three forms.</p>
<p><strong>Quasi-experiments</strong> compare conditions the researcher did not create. You cannot control what a factory discharges into a river, but you can compare reaches above and below the outfall and use statistical tools to account for the confounding variables you could not hold constant.</p>
<p><strong>Time series</strong> follow one system over a long stretch, which matters because many environmental processes unfold across decades or centuries. Tracking global temperature or sea level takes years of consistent measurement, and statistics is what separates the trend from the natural year-to-year noise.</p>
<p><strong>Case studies</strong> go deep on a single event or place: the aftermath of a wildfire, the ecology of a threatened habitat, the consequences of a policy. One case is tied to its context, but a well-designed one can still expose a mechanism that travels. A drought in one forest can reveal how water potential and transpiration respond to stress, which helps anticipate what other forests will do.</p>
</section>
<section id="from-measurement-to-description" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="from-measurement-to-description"><span class="header-section-number">1.6</span> From measurement to description</h2>
<p>The first half of this chapter was about what data <em>are</em>: how a broad concept gets operationalized into a variable, what scale that variable lives on, and what kind of study produced it. The rest of the chapter is about what to do with a dataset once you have one.</p>
<blockquote class="blockquote">
<p>Far better an approximate answer to the right question, which is often vague, than an exact answer to the wrong question, which can always be made precise.<br>
John W. Tukey</p>
</blockquote>
<p>Statistics often begins with the problem of <strong>too much data</strong>. Rainfall at hundreds of stations, thousands of tree measurements in a forest survey, millions of satellite pixels: looking at raw numbers alone is overwhelming and uninformative. We need tools to compress, summarize, and visualize, and those tools are <strong>descriptive statistics</strong>.</p>
<p>There is more than one useful way to describe a dataset, and which one you reach for depends on the pattern you are trying to reveal. Every method in this half of the chapter was invented for that reason.</p>
</section>
<section id="looking-at-the-data" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="looking-at-the-data"><span class="header-section-number">1.7</span> Looking at the data</h2>
<p>Everything up to now has been about where numbers come from. From here on we work with a real dataset, so the tools have something concrete to act on.</p>
<p>R ships with <code>airquality</code>, a record of daily air quality measurements taken in New York from May through September of 1973. Each row is one day, with ozone concentration (parts per billion), solar radiation, wind speed, and maximum temperature.</p>
<div class="cell">
<div id="tbl-1airquality-head" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1airquality-head-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.1: The first six days of the airquality dataset.
</figcaption>
<div aria-describedby="tbl-1airquality-head-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Ozone</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Solar.R</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Wind</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Temp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Month</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">41</td>
<td style="text-align: right;">190</td>
<td style="text-align: right;">7.4</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">36</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">8.0</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">12.6</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">313</td>
<td style="text-align: right;">11.5</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">14.3</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">28</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">14.9</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Look at the <code>NA</code> entries. Ozone and solar radiation were not recorded every day, and real environmental datasets almost always have gaps like this. That has an immediate practical consequence:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(airquality<span class="sc">$</span>Ozone)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] NA</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>R returns <code>NA</code> rather than a number, because it has no way of knowing what the missing days would have been. You have to tell it explicitly to set those days aside:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(airquality<span class="sc">$</span>Ozone, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 42.12931</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>That <code>na.rm = TRUE</code> will follow you through the rest of the course. Now, to the data itself.</p>
<section id="scatter-of-raw-values" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="scatter-of-raw-values"><span class="header-section-number">1.7.1</span> Scatter of raw values</h3>
<p><strong>Plot every value.</strong> Before summarizing anything, it is worth simply looking at all of it.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1tempPlot" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatter plot with day number on the horizontal axis and daily maximum temperature on the vertical axis. Temperatures rise from the high 50s and 60s in May to the 80s and 90s in midsummer, then fall again by September.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1tempPlot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-1tempPlot-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Scatter plot with day number on the horizontal axis and daily maximum temperature on the vertical axis. Temperatures rise from the high 50s and 60s in May to the 80s and 90s in midsummer, then fall again by September.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1tempPlot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.7: Daily maximum temperature at a New York station, May through September 1973.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-1tempPlot" class="quarto-xref">Figure&nbsp;<span>1.7</span></a> shows all 153 daily temperatures at once, with day number across the bottom and that day’s maximum temperature up the side. Already this tells us more than a table of 153 numbers would: there is a clear seasonal arc, cooler in May, warmest through July and August, cooling again by September.</p>
<p>But notice what the plot does <em>not</em> answer well. If you want to know whether most days were warm or cool, you end up squinting at a cloud of dots, because the seasonal ordering gets in the way. For that we need a different view, a <strong>histogram</strong>.</p>
</section>
<section id="histograms" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="histograms"><span class="header-section-number">1.7.2</span> Histograms</h3>
<p>A histogram summarizes data by grouping values into bins rather than showing each point separately. It throws away the day-to-day ordering on purpose, and in exchange it shows you the shape of the data.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1tempHist" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of daily maximum temperatures. Bars rise toward a peak around 80 degrees, with fewer days in the high 50s and low 60s and fewer above 90.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1tempHist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-1tempHist-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Histogram of daily maximum temperatures. Bars rise toward a peak around 80 degrees, with fewer days in the high 50s and low 60s and fewer above 90.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1tempHist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.8: A histogram of the same daily temperatures.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each bar counts the days falling in a temperature range, and the pattern is now easy to read: most days land in the 70s and 80s, with a tail of cooler days near 56°F and relatively few above 90°F.</p>
<p><strong>Bin width is a choice you make.</strong> Wide bins look smooth but hide detail; narrow bins show more variation but can dissolve into noise. <a href="#fig-1manyhistbin" class="quarto-xref">Figure&nbsp;<span>1.9</span></a> compares the same temperatures at four bin widths.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1manyhistbin" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four histograms of daily maximum temperature using 5, 10, 20, and 50 bins. The five-bin version is blocky, the fifty-bin version is jagged and sparse, and the middle two show the shape most clearly.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1manyhistbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-1manyhistbin-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Four histograms of daily maximum temperature using 5, 10, 20, and 50 bins. The five-bin version is blocky, the fifty-bin version is jagged and sparse, and the middle two show the shape most clearly.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1manyhistbin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.9: Four histograms of the same temperature data using different numbers of bins.
</figcaption>
</figure>
</div>
</div>
</div>
<p>All four show the same general shape, but the extremes are unhelpful. Five bins is so coarse that the peak becomes one wide block; fifty spreads 153 days so thinly that bars jump around at random. The middle two are the ones you would actually use. A histogram trades away the individual values and the day-to-day ordering, and in exchange it shows you the shape of the data, but only if you pick a sensible bin width.</p>
</section>
</section>
<section id="important-ideas-distribution-central-tendency-and-variance" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="important-ideas-distribution-central-tendency-and-variance"><span class="header-section-number">1.8</span> Important Ideas: Distribution, Central Tendency, and Variance</h2>
<p>Three terms will keep coming up: <strong>distribution, central tendency, and variance.</strong> Their everyday meanings aren’t far from the statistical ones.</p>
<ul>
<li><p><strong>Distribution</strong>: how values are spread across their range. A histogram is one way of showing a distribution. The shape of the distribution tells us where values are concentrated, where they’re rare, and how far the extremes reach. Later we’ll see that distributions don’t just describe data, we also use them to <strong>generate theoretical data</strong>, which is the basis for sampling distributions and tools like <em>t</em>-tests.</p></li>
<li><p><strong>Central tendency</strong> is about <em>sameness</em>: where values cluster. In the temperature histogram, most days sit in the high 70s and low 80s, so we say the data have a central tendency around 80°F. Central tendency doesn’t mean “everything is the same”, just that many values gather in a common area. Some datasets even have more than one cluster, and therefore more than one central tendency.</p></li>
<li><p><strong>Variance</strong> is about <em>differentness</em>: how spread out the values are. If every day had been 78°F, variance would be zero. Instead the days run from 56°F to 97°F, so there is real variance to describe. In practice, variance is a family of measures we use to quantify differences, and we’ll introduce those next.</p></li>
</ul>
</section>
<section id="measures-of-central-tendency-sameness" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="measures-of-central-tendency-sameness"><span class="header-section-number">1.9</span> Measures of Central Tendency (Sameness)</h2>
<p>Plots and histograms show where values fall, but lack precision. We can summarize data with a single number representing its “center” - these <strong>measures of central tendency</strong> show what values are generally like.</p>
<section id="mode" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="mode"><span class="header-section-number">1.9.1</span> Mode</h3>
<p>The <strong>mode</strong> is the most frequently occurring value: count how often each value appears, and whichever wins is the mode. In <code>1 1 1 2 3 4 5 6</code> the mode is 1, since it appears three times.</p>
<p>Ties are allowed. In <code>1 1 1 2 2 2 3 4 5 6</code> both 1 and 2 appear three times, so the data have two modes.</p>
<p><strong>The mode does not always land where you would call the center.</strong> In <code>1 1 2 3 4 5 6 7 8 9</code> the mode is 1, but nearly every value is larger. It is most useful when a dataset has genuinely repeating values, and like any tool it needs to suit the data you have.</p>
</section>
<section id="median" class="level3" data-number="1.9.2">
<h3 data-number="1.9.2" class="anchored" data-anchor-id="median"><span class="header-section-number">1.9.2</span> Median</h3>
<p>The <strong>median</strong> is the exact middle of the data once they are ordered from smallest to largest. For example:</p>
<blockquote class="blockquote">
<p>1 5 4 3 6 7 9</p>
</blockquote>
<p>Before we can compute the median, we need to order the numbers from smallest to largest. Ordered:</p>
<blockquote class="blockquote">
<p>1 3 4 <strong>5</strong> 6 7 9</p>
</blockquote>
<p>The median is 5, with three numbers on each side.</p>
<p>With an even count there is no single middle value, so the median is the midpoint of the two central numbers. In <code>1 2 3 4 5 6</code> that is halfway between 3 and 4, or 3.5.</p>
<p><strong>The median holds still when extreme values do not.</strong> Consider <code>1 2 3 4 4 4 5 6 6 6 7 7 1000</code>. Most values are modest and one is wildly out of line, yet the median is still 5, sitting right where the bulk of the data is. That value of 1000 is an <strong>outlier</strong>, a value much farther out than the rest. Outliers can drag the mean a long way while leaving the median untouched, and how to handle them is a question we return to later in the course.</p>
</section>
<section id="mean" class="level3" data-number="1.9.3">
<h3 data-number="1.9.3" class="anchored" data-anchor-id="mean"><span class="header-section-number">1.9.3</span> Mean</h3>
<p>The <strong>mean</strong>, also called the average, is the sum of a set of numbers divided by how many numbers there are.</p>
<p><span class="math display">\[Mean = \bar{X} = \frac{\sum_{i=1}^{n} x_{i}}{N}\]</span></p>
<p>The <span class="math inline">\(\sum\)</span> symbol is <strong>sigma</strong>, and it means “sum these up.” The <span class="math inline">\(x_{i}\)</span> are the individual numbers, <span class="math inline">\(i\)</span> runs from the first to the last, <span class="math inline">\(N\)</span> is how many there are, and <span class="math inline">\(\bar{X}\)</span> is the mean. In plainer terms, it is the sum of your numbers divided by the count of your numbers.</p>
<p>For the five numbers 3, 7, 9, 2, and 6, that gives</p>
<p><span class="math display">\[\bar{X} = \frac{3+7+9+2+6}{5} = \frac{27}{5} = 5.4\]</span></p>
<p>Whether the mean is a <em>good</em> summary, as with the mode, depends on the data.</p>
</section>
<section id="what-does-the-mean-mean" class="level3" data-number="1.9.4">
<h3 data-number="1.9.4" class="anchored" data-anchor-id="what-does-the-mean-mean"><span class="header-section-number">1.9.4</span> What does the mean mean?</h3>
<p>Knowing how to calculate a mean is not the same as knowing what it represents. The formula divides a sum by a count, but what does that operation actually <em>do</em>?</p>
<p>Think about plain division. When we compute <span class="math inline">\(\frac{12}{3} = 4\)</span>, we are splitting 12 into three equal parts of 4 each. Division equalizes the numerator into identical pieces.</p>
<p>The same logic applies to the mean. Suppose you add up every daily temperature across the whole summer into one large total. If that total were redistributed equally across all the days, each day would get the same value. That value is the mean. Individual days were originally warmer or cooler, but the mean is the balance point created by spreading the total evenly.</p>
<p>This is why the mean is more than just arithmetic. It is the one number that can replace every observation so that, when all those replacements are added together, you get back the original total.</p>
<p>That is what makes the mean unique. It is the only single value that can replace every observation and still leave the total unchanged.</p>
</section>
<section id="comparing-the-mean-median-and-mode" class="level3" data-number="1.9.5">
<h3 data-number="1.9.5" class="anchored" data-anchor-id="comparing-the-mean-median-and-mode"><span class="header-section-number">1.9.5</span> Comparing the mean, median, and mode</h3>
<p>So far we have three summaries of the “middle” of a dataset. It is worth seeing what happens when they disagree, because the disagreement itself is informative.</p>
<p>Temperature was a well-behaved variable: its mean (77.9°F) and median (79°F) sit almost on top of each other, which is what you expect when a distribution is roughly symmetric. Ozone is a different story.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1meanmedian" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of daily ozone concentration. Most days fall below 50 parts per billion, with a long thin tail extending past 150. Three thick vertical lines mark the mode at 23 ppb in green, the median at 31.5 ppb in blue, and the mean at 42.1 ppb in red, in that left-to-right order.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1meanmedian-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-1meanmedian-1.png" class="img-fluid figure-img" style="width:92.0%" alt="Histogram of daily ozone concentration. Most days fall below 50 parts per billion, with a long thin tail extending past 150. Three thick vertical lines mark the mode at 23 ppb in green, the median at 31.5 ppb in blue, and the mean at 42.1 ppb in red, in that left-to-right order.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1meanmedian-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.10: Daily ozone concentration with all three measures of central tendency marked. They fall in the order mode, median, mean, which is the standard signature of a right-skewed distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>All three land in different places, and the order they fall in is not an accident. For a right-skewed distribution you will nearly always find <strong>mode &lt; median &lt; mean</strong>, which is exactly what <a href="#fig-1meanmedian" class="quarto-xref">Figure&nbsp;<span>1.10</span></a> shows: the mode at 23 ppb, the median at 31.5 ppb, and the mean at 42.1 ppb.</p>
<p>They differ because each one is sensitive to something different.</p>
<ul>
<li>The <strong>mean</strong> uses every value, so it feels the full weight of those bad-air days out past 150 ppb. Add one extreme day and the mean moves.</li>
<li>The <strong>median</strong> only cares about which value sits in the middle. Those same extreme days push it over by one position at most, so it stays down where the bulk of the days actually are.</li>
<li>The <strong>mode</strong> ignores position entirely and reports whichever value occurred most often. It answers a genuinely different question: not “what is the center” but “what happened most”.</li>
</ul>
<p>Neither the mean nor the median is wrong here. They answer different questions. If you want to know what a typical day looked like, the median is the better guide. If you care about the total ozone burden across the summer, the mean is the number that relates to that total.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>When the mode gets fragile.</strong> Ozone is a continuous measurement, so exact repeats are largely an accident of rounding. The value 23 ppb occurs 6 times out of 116 days, barely more often than several neighbors. Round differently and the mode moves. It is at its best for categorical variables, where “most common land cover class” is exactly the question, and for values that genuinely repeat.</p>
</div>
</div>
</section>
</section>
<section id="measures-of-variation-differentness" class="level2" data-number="1.10">
<h2 data-number="1.10" class="anchored" data-anchor-id="measures-of-variation-differentness"><span class="header-section-number">1.10</span> Measures of Variation (Different<em>ness</em>)</h2>
<p>Central tendency tells us what values have in common. Measures of <strong>variation</strong> tell us how they differ. Any dataset with more than one value will show some variation, and summarizing that spread is as important as finding the center.</p>
<section id="the-range" class="level3" data-number="1.10.1">
<h3 data-number="1.10.1" class="anchored" data-anchor-id="the-range"><span class="header-section-number">1.10.1</span> The Range</h3>
<p>Consider these 10 ordered numbers:</p>
<blockquote class="blockquote">
<p>1 3 4 5 5 6 7 8 9 24</p>
</blockquote>
<p>The smallest is 1, the largest is 24. Together they define the <strong>range</strong>. The range quickly shows the boundaries of the data and can flag possible outliers. For instance, if you expected values between 1 and 7 but found one at 340,500, you’d know something unusual happened and might investigate.</p>
</section>
<section id="difference-scores" class="level3" data-number="1.10.2">
<h3 data-number="1.10.2" class="anchored" data-anchor-id="difference-scores"><span class="header-section-number">1.10.2</span> Difference Scores</h3>
<p>It would be nice to summarize the amount of different<em>ness</em> in the data. Think about these 10 ordered numbers:</p>
<blockquote class="blockquote">
<p>1 3 4 5 5 6 7 8 9 24</p>
</blockquote>
<p>One idea is to compare every number to every other number. It works, but it scales badly: 10 numbers give 100 pairwise differences, and 500 numbers would give 250,000. If all the values were identical every difference would be 0 and the lack of variation would be obvious, but with real data we just get a large pile of differences. The natural way to summarize a pile of numbers is the one we just learned, so let’s take their <strong>average</strong>.</p>
<p>Let’s try it on a set small enough to see all at once:</p>
<blockquote class="blockquote">
<p>1 2 3</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean of these nine difference scores is:</p>
<p><span class="math inline">\(\text{mean of difference scores} = \frac{0+1+2-1+0+1-2-1+0}{9} = \frac{0}{9} = 0\)</span></p>
<p>This will always happen: the positives and negatives cancel. So the mean of raw difference scores is not a useful measure of variation.</p>
<p>Notice also that the matrix is redundant: the diagonal is always zero, and values above and below the diagonal are the same except for sign.</p>
<p>These problems motivate why we compute <strong>variance</strong> and <strong>standard deviation</strong>. They solve the cancellation issue and give us a practical summary of spread.</p>
</section>
<section id="the-variance" class="level3" data-number="1.10.3">
<h3 data-number="1.10.3" class="anchored" data-anchor-id="the-variance"><span class="header-section-number">1.10.3</span> The Variance</h3>
<p>We have used the words variability, variation, and variance a lot, and they all point at the same idea: numbers differ. The word <em>variance</em> does double duty, though. Loosely it means that general idea. Precisely it names a specific statistic, the <strong>mean of the squared deviations from the mean</strong>.</p>
<p>To calculate it, subtract the mean from each score to get its <strong>difference score</strong>, square those differences, then average them. Squaring is the trick that stops positive and negative deviations from cancelling. In short:</p>
<p><span class="math inline">\(variance = \frac{\text{Sum of squared difference scores}}{\text{Number of Scores}}\)</span></p>
<p>A little further on we’ll distinguish between dividing by <span class="math inline">\(N\)</span> (when you have the entire population) and <span class="math inline">\(n-1\)</span> (when you only have a sample, which is almost always the case). For now, just use <span class="math inline">\(N\)</span>.</p>
<section id="deviations-from-the-mean" class="level4" data-number="1.10.3.1">
<h4 data-number="1.10.3.1" class="anchored" data-anchor-id="deviations-from-the-mean"><span class="header-section-number">1.10.3.1</span> Deviations from the mean</h4>
<p>Earlier we compared every number to every other number, which got unmanageable fast. The simpler approach is to compare each score to the mean instead: find the mean, then subtract it from every score. What comes back tells us both how well the mean represents the data and how much spread there is around it.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference_from_Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean here is <span class="math inline">\(\frac{1+6+4+2+6+8}{6} = \frac{27}{6} = 4.5\)</span>. The third column just repeats it on every row, which looks redundant but makes the earlier point concrete: six copies of 4.5 add back to the original total of 27. The fourth column is the <strong>deviation from the mean</strong>, <span class="math inline">\(X_{i}-\bar{X}\)</span>, so the score of 1 sits 3.5 below and the score of 6 sits 1.5 above.</p>
<p><strong>And now the problem.</strong> Those deviations sum to zero. The positives and negatives cancel exactly, which would suggest there is no variation at all, and that is obviously false. Squaring will fix it, but first it is worth seeing <em>why</em> the cancellation happens.</p>
</section>
<section id="mean-as-the-balancing-point" class="level4" data-number="1.10.3.2">
<h4 data-number="1.10.3.2" class="anchored" data-anchor-id="mean-as-the-balancing-point"><span class="header-section-number">1.10.3.2</span> Mean as the Balancing Point</h4>
<p>The mean is the balancing point of the data. Imagine laying a ruler across your finger. The place where it balances is the point where the weight on each side is equal. Data works the same way: if we treat each value like a weight, the mean is where the total “mass” to the left and right cancel out.</p>
<p>This balancing property explains why the deviations always sum to zero. The values below the mean contribute negative deviations, the values above contribute positive ones, and together they cancel:</p>
<p><span class="math inline">\(-x + x = 0\)</span></p>
<p>To see this more concretely, consider the numbers</p>
<p><span class="math inline">\(X = (1,2,6,7,9)\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-number-line" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Horizontal number line with dots at 1, 2, 6, 7, and 9, each labeled above.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-number-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-number-line-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Horizontal number line with dots at 1, 2, 6, 7, and 9, each labeled above.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-number-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.11: Values on a number line.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now imagine the number line as a teeter-totter. Only when the fulcrum is placed at 5 does the board balance:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mean-balance-panels" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three panels with a horizontal number line and a triangular fulcrum; the board tilts left/right when the fulcrum is not at the mean, and is level at the mean.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mean-balance-panels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-mean-balance-panels-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Three panels with a horizontal number line and a triangular fulcrum; the board tilts left/right when the fulcrum is not at the mean, and is level at the mean.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean-balance-panels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.12: Mean as the unique balancing point. Only at the mean do signed deviations cancel.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Formally, this means the signed distances from the mean always cancel out:</p>
<p><span class="math inline">\((1−5)+(2−5)+(6−5)+(7−5)+(9−5)=0\)</span></p>
<p>This makes the mean unique. It is the <strong>only value</strong> for which the sum of deviations equals zero:</p>
<p><span class="math inline">\(\sum_{i=1}^{n}x_{{i}-a} = 0 \quad \Rightarrow \quad a = \bar{x}\)</span></p>
<p>The mean is not just a “typical” value, it is the one point where the data balance. And that balancing property is exactly why the raw deviations always sum to zero. To summarize variation, we need a way around this problem.</p>
</section>
<section id="the-squared-deviations" class="level4" data-number="1.10.3.3">
<h4 data-number="1.10.3.3" class="anchored" data-anchor-id="the-squared-deviations"><span class="header-section-number">1.10.3.3</span> The squared deviations</h4>
<p>The standard trick is to square the deviations. Since <span class="math inline">\(2^2 = 4\)</span> and <span class="math inline">\((-2)^2 = 4\)</span>, squaring turns every negative into a positive, so the deviations can no longer cancel. We call these <strong>squared deviations</strong>. Here is the same table with a column for them:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference_from_Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Squared_Deviations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-3.5</td>
<td style="text-align: left;">12.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-0.5</td>
<td style="text-align: left;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-2.5</td>
<td style="text-align: left;">6.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">3.5</td>
<td style="text-align: left;">12.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">35.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">5.91666666666667</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The first score of 1 sits 3.5 below the mean, so its deviation is <span class="math inline">\(-3.5\)</span> and its squared deviation is <span class="math inline">\((-3.5)^2 = 12.25\)</span>. Now that nothing is negative we can add them up, and that total is the <strong>sum of squares (SS)</strong>. You will meet this quantity again in the ANOVA chapter, but there is nothing more to it than the sum of those squared deviations.</p>
</section>
<section id="finally-the-variance" class="level4" data-number="1.10.3.4">
<h4 data-number="1.10.3.4" class="anchored" data-anchor-id="finally-the-variance"><span class="header-section-number">1.10.3.4</span> Finally, the variance</h4>
<p>We have already computed the variance, one step at a time, without naming it. The goal was a single number summarizing spread, but deviations give us as many numbers as we have data points, so we want their <em>average</em>. Sum the squared deviations, divide by how many there are, and that is <strong>the variance</strong>:</p>
<p><span class="math display">\[variance = \frac{SS}{N}\]</span></p>
<p>For our data it comes to 5.916. On its own that number is hard to interpret, because squaring the deviations put it on a <em>squared</em> scale, so it is no longer in the same units as the data. The fix is to take the square root, <span class="math inline">\(\sqrt{5.916} \approx 2.43\)</span>.</p>
</section>
</section>
<section id="the-standard-deviation" class="level3" data-number="1.10.4">
<h3 data-number="1.10.4" class="anchored" data-anchor-id="the-standard-deviation"><span class="header-section-number">1.10.4</span> The Standard Deviation</h3>
<p>That square root is the <strong>standard deviation (SD)</strong>, so we had already computed it a step earlier without naming it:</p>
<p><span class="math display">\[\text{standard deviation} = \sqrt{Variance} = \sqrt{\frac{SS}{N}} = \sqrt{\frac{\sum_{i}^{n}(x_{i}-\bar{x})^2}{N}}\]</span></p>
<p>The square root “unsquares” the variance, putting the measure of spread back on the original scale of the data. Here is the table one more time:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference_from_Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Squared_Deviations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-3.5</td>
<td style="text-align: left;">12.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-0.5</td>
<td style="text-align: left;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-2.5</td>
<td style="text-align: left;">6.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">3.5</td>
<td style="text-align: left;">12.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">35.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">5.91666666666667</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Our standard deviation, <span class="math inline">\(\sqrt{5.916} \approx 2.43\)</span>, makes far more sense than the variance did. A variance of 5.916 feels too large for this data because it is on the squared scale, but an SD of 2.43 lines up with the actual deviations, since most scores fall within about 2.4 of the mean of 4.5.</p>
<p><strong>That is what makes the SD so useful.</strong> Told only that a dataset has a mean of 4.5 and an SD of 2.4, you already have a picture of it: values cluster around 4.5, not exactly at it, with a typical spread of two to three units either way. It gives you the <em>typical deviation</em> from the mean while staying in the original units.</p>
</section>
<section id="sample-versus-population-a-note-on-n---1" class="level3" data-number="1.10.5">
<h3 data-number="1.10.5" class="anchored" data-anchor-id="sample-versus-population-a-note-on-n---1"><span class="header-section-number">1.10.5</span> Sample versus population: a note on <span class="math inline">\(n - 1\)</span></h3>
<p>One detail we glossed over: is <span class="math inline">\(N\)</span> the size of the whole population, or just the size of our sample? For the mean it does not matter. The sample mean <span class="math inline">\(\bar{x}\)</span> is <strong>unbiased</strong>, meaning that averaged across many samples it lands right on the true population mean.</p>
<p>The standard deviation is not so well behaved. A sample standard deviation computed by dividing by <span class="math inline">\(N\)</span> comes out systematically <strong>too small</strong>. The reason is that <span class="math inline">\(\bar{x}\)</span> is calculated <em>from</em> the same points used to measure spread, which pulls those points artificially close to it, so the distances we are averaging are shorter than they should be.</p>
<p>The fix is to divide by <span class="math inline">\(n-1\)</span> instead of <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[s_{n-1}^2 = \frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2\]</span></p>
<p>This is what R’s <code>sd()</code> function already does, and it is what “the sample standard deviation” means unless you are told otherwise. Chapter 3 returns to this and shows the bias directly with a simulation, once we have the vocabulary of populations, samples, and estimation to explain <em>why</em> the correction is the right size.</p>
</section>
<section id="mean-absolute-deviation" class="level3" data-number="1.10.6">
<h3 data-number="1.10.6" class="anchored" data-anchor-id="mean-absolute-deviation"><span class="header-section-number">1.10.6</span> Mean Absolute Deviation</h3>
<p>So far we’ve handled the “differences cancel out” problem by squaring deviations. But there’s another simple option: take the <strong>absolute value</strong> of each deviation from the mean. That way, every difference becomes positive, and when we add them up we don’t end up at zero.</p>
<p>Here’s what that looks like for our data:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference_from_Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Absolute_Deviations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-3.5</td>
<td style="text-align: left;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-0.5</td>
<td style="text-align: left;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-2.5</td>
<td style="text-align: left;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">3.5</td>
<td style="text-align: left;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">2.16666666666667</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The last column shows absolute deviations. If we take their mean, we get the mean absolute deviation (MAD). Notice this acts a lot like the standard deviation: it’s the average size of a deviation from the mean, only without squaring. Both approaches, squaring and taking absolute values, solve the same problem in slightly different ways. Squaring is more common because it leads to nice mathematical properties (like in regression and ANOVA), but the MAD can be more intuitive to interpret.</p>
</section>
</section>
<section id="remember-to-look-at-your-data" class="level2" data-number="1.11">
<h2 data-number="1.11" class="anchored" data-anchor-id="remember-to-look-at-your-data"><span class="header-section-number">1.11</span> Remember to look at your data</h2>
<p>Descriptive statistics are useful, but they are also compressed summaries. They reduce a dataset to a few numbers, which means they always lose detail. That’s fine if the summary captures the important features, but sometimes it doesn’t.</p>
<p>The safest habit is to <strong>always combine descriptive statistics with graphs</strong>. Compute the summaries, then plot the data, and check that the two tell the same story. We just did this with ozone: the gap between the mean and the median said “skewed,” and the histogram confirmed it.</p>
<p>When the numbers and the graph disagree, believe the graph. A summary can only report what it was designed to measure, while a plot shows you everything, including whatever you failed to anticipate. The next two examples show just how badly summaries can mislead when you skip that step.</p>
<section id="anscombes-quartet" class="level3" data-number="1.11.1">
<h3 data-number="1.11.1" class="anchored" data-anchor-id="anscombes-quartet"><span class="header-section-number">1.11.1</span> Anscombe’s Quartet</h3>
<p>Francis Anscombe (<span class="citation" data-cites="Anscombe1973">Anscombe (<a href="#ref-Anscombe1973" role="doc-biblioref">1973</a>)</span>) made this point with a famous example, now called <em>Anscombe’s Quartet</em>. Each panel in Figure <a href="#fig-anscombe" class="quarto-xref">Figure&nbsp;<span>1.13</span></a> shows pairs of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> values as a scatterplot.</p>
<p>Visually, the four panels are very different: one looks linear, one curved, one is mostly linear except for an outlier, and one forms a near-vertical line except for one point.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-anscombe" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Anscombe's Quartet, a set of four scatter plots each with a different pattern, despite having identical descriptive statistics. This illustrates the importance of graphing data to understand underlying relationships beyond basic statistical measures">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anscombe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01-Data_Description_files/figure-html/fig-anscombe-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Anscombe's Quartet, a set of four scatter plots each with a different pattern, despite having identical descriptive statistics. This illustrates the importance of graphing data to understand underlying relationships beyond basic statistical measures">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anscombe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.13: Anscombe’s Quartet
</figcaption>
</figure>
</div>
</div>
</div>
<p>Yet if we summarize each quartet with just its descriptive statistics:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">quartet</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_x</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">var_x</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_y</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">var_y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7.500909</td>
<td style="text-align: right;">4.127269</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7.500909</td>
<td style="text-align: right;">4.127629</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7.500000</td>
<td style="text-align: right;">4.122620</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7.500909</td>
<td style="text-align: right;">4.123249</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>All four datasets have the <strong>exact same descriptive statistics</strong>:</p>
<p>same mean and variance for <span class="math inline">\(x\)</span></p>
<p>same mean and variance for <span class="math inline">\(y\)</span></p>
<p>same correlation between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span></p>
<p>Yet the scatterplots could not look more different.</p>
</section>
<section id="datasaurus-dozen" class="level3" data-number="1.11.2">
<h3 data-number="1.11.2" class="anchored" data-anchor-id="datasaurus-dozen"><span class="header-section-number">1.11.2</span> Datasaurus Dozen</h3>
<p>The <a href="https://www.autodeskresearch.com/publications/samestats">Datasaurus Dozen</a> <span class="citation" data-cites="matejka2017same">(<a href="#ref-matejka2017same" role="doc-biblioref">Matejka and Fitzmaurice 2017</a>)</span> takes Anscombe’s point further: 13 datasets with nearly identical means, variances, and correlations, but when plotted, the points form shapes like a star, a circle, or even a dinosaur. A reminder that your numbers might look like a dinosaur if you don’t plot them.</p>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="1.12">
<h2 data-number="1.12" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">1.12</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> Every analysis later in this course assumes you already have numbers that mean something and a sense of what they look like. This chapter covers both halves of that: where data come from, and how to describe them once you have them.</p>
<p>On measurement and study design:</p>
<ul>
<li><p><strong>Why statistics matters.</strong> It will not answer every scientific question, but it provides a disciplined way to separate signal from bias, and to avoid being fooled by aggregated data, as Simpson’s paradox shows.</p></li>
<li><p><strong>Operationalization and measurement.</strong> Turning a broad concept like <em>soil health</em> into something recordable is a decision you have to make and justify, not something the data hands you.</p></li>
<li><p><strong>Scales of measurement.</strong> Nominal, ordinal, interval, and ratio, plus the continuous-versus-discrete distinction. These determine which statistical tools are available to you, which is why we return to them all semester.</p></li>
<li><p><strong>Predictors and outcomes.</strong> The roles variables play in an analysis, and the several vocabularies used to describe them.</p></li>
<li><p><strong>Experimental and non-experimental research.</strong> Environmental science rarely permits full experimental control, so the field leans on quasi-experiments, long-term time series, and case studies.</p></li>
</ul>
<p>On describing data:</p>
<ul>
<li><p><strong>Plot first.</strong> Scatter plots and histograms show the shape of a distribution, and bin width is a choice that changes what you see.</p></li>
<li><p><strong>Central tendency.</strong> The mode, median, and mean each summarize the “middle” differently, and they diverge when data are skewed.</p></li>
<li><p><strong>Variation.</strong> The range, then deviations from the mean, then squared deviations, the sum of squares, the variance, and finally the standard deviation, which returns the measure of spread to the original units.</p></li>
<li><p><strong>Always look at the graph.</strong> Anscombe’s Quartet and the Datasaurus Dozen make the point that identical summary statistics can describe radically different data.</p></li>
</ul>
<hr>
</section>
<section id="videos" class="level2" data-number="1.13">
<h2 data-number="1.13" class="anchored" data-anchor-id="videos"><span class="header-section-number">1.13</span> Videos</h2>
<section id="terms-of-statistics" class="level3" data-number="1.13.1">
<h3 data-number="1.13.1" class="anchored" data-anchor-id="terms-of-statistics"><span class="header-section-number">1.13.1</span> Terms of Statistics</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/HgtnpOtk350" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="measures-of-center-mode" class="level3" data-number="1.13.2">
<h3 data-number="1.13.2" class="anchored" data-anchor-id="measures-of-center-mode"><span class="header-section-number">1.13.2</span> Measures of center: Mode</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/hQ2p-QQpGso" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="measures-of-center-median-and-mean" class="level3" data-number="1.13.3">
<h3 data-number="1.13.3" class="anchored" data-anchor-id="measures-of-center-median-and-mean"><span class="header-section-number">1.13.3</span> Measures of center: Median and Mean</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/BopmCXCjq08" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="standard-deviation-part-i" class="level3" data-number="1.13.4">
<h3 data-number="1.13.4" class="anchored" data-anchor-id="standard-deviation-part-i"><span class="header-section-number">1.13.4</span> Standard deviation part I</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/8Yguf93s5dI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="standard-deviation-part-ii" class="level3" data-number="1.13.5">
<h3 data-number="1.13.5" class="anchored" data-anchor-id="standard-deviation-part-ii"><span class="header-section-number">1.13.5</span> Standard deviation part II</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/KodmsOXScBc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Anscombe1973" class="csl-entry" role="listitem">
Anscombe, F. J. 1973. <span>“Graphs in Statistical Analysis.”</span> <em>American Statistician</em> 27: 17–21.
</div>
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
<div id="ref-matejka2017same" class="csl-entry" role="listitem">
Matejka, Justin, and George Fitzmaurice. 2017. <span>“Same Stats, Different Graphs: Generating Datasets with Varied Appearance and Identical Statistics Through Simulated Annealing.”</span> <em>Proceedings of the 2017 <span>CHI</span> Conference on Human Factors in Computing Systems</em>, 1290–94. <a href="https://doi.org/10.1145/3025453.3025912">https://doi.org/10.1145/3025453.3025912</a>.
</div>
<div id="ref-vonkügelgen2021" class="csl-entry" role="listitem">
<span class="nocase">von Kügelgen, Julius, Luigi Gresele, and Bernhard Schölkopf</span>. 2021. <span>“Simpson’s Paradox in COVID-19 Case Fatality Rates: A Mediation Analysis of Age-Related Causal Effects.”</span> <em>IEEE Transactions on Artificial Intelligence</em> 2 (1): 18–27. <a href="https://doi.org/10.1109/TAI.2021.3073088">https://doi.org/10.1109/TAI.2021.3073088</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Preface">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02-Correlation.html" class="pagination-link" aria-label="Correlation">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/01-Data_Description.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>