<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>2&nbsp; Correlation – Statistics for Environmental Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-SamplesPopulations.html" rel="next">
<link href="./01-Data_Description.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="2&nbsp; Correlation – Statistics for Environmental Science">
<meta property="og:description" content="">
<meta property="og:image" content="02-Correlation_files/figure-html/fig-2scatter1-1.png">
<meta property="og:site_name" content="Statistics for Environmental Science">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-Correlation.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for Environmental Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inference and Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Errors, Power, and Effect Size</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-data-look-like-when-one-thing-changes-another" id="toc-what-data-look-like-when-one-thing-changes-another" class="nav-link active" data-scroll-target="#what-data-look-like-when-one-thing-changes-another"><span class="header-section-number">2.1</span> What data look like when one thing changes another</a>
  <ul class="collapse">
  <li><a href="#more-chocolate-more-happiness" id="toc-more-chocolate-more-happiness" class="nav-link" data-scroll-target="#more-chocolate-more-happiness"><span class="header-section-number">2.1.1</span> More Chocolate = More Happiness?</a></li>
  <li><a href="#scatter-plots" id="toc-scatter-plots" class="nav-link" data-scroll-target="#scatter-plots"><span class="header-section-number">2.1.2</span> Scatter plots</a></li>
  <li><a href="#positive-negative-and-no-correlation" id="toc-positive-negative-and-no-correlation" class="nav-link" data-scroll-target="#positive-negative-and-no-correlation"><span class="header-section-number">2.1.3</span> Positive, Negative, and No-Correlation</a></li>
  </ul></li>
  <li><a href="#how-much-does-one-variable-vary" id="toc-how-much-does-one-variable-vary" class="nav-link" data-scroll-target="#how-much-does-one-variable-vary"><span class="header-section-number">2.2</span> How much does one variable vary?</a>
  <ul class="collapse">
  <li><a href="#difference-scores" id="toc-difference-scores" class="nav-link" data-scroll-target="#difference-scores"><span class="header-section-number">2.2.1</span> Difference Scores</a></li>
  <li><a href="#the-variance" id="toc-the-variance" class="nav-link" data-scroll-target="#the-variance"><span class="header-section-number">2.2.2</span> The Variance</a></li>
  <li><a href="#the-standard-deviation" id="toc-the-standard-deviation" class="nav-link" data-scroll-target="#the-standard-deviation"><span class="header-section-number">2.2.3</span> The Standard Deviation</a></li>
  <li><a href="#mean-absolute-deviation" id="toc-mean-absolute-deviation" class="nav-link" data-scroll-target="#mean-absolute-deviation"><span class="header-section-number">2.2.4</span> Mean Absolute Deviation</a></li>
  </ul></li>
  <li><a href="#covariance" id="toc-covariance" class="nav-link" data-scroll-target="#covariance"><span class="header-section-number">2.3</span> Covariance</a>
  <ul class="collapse">
  <li><a href="#turning-the-numbers-into-a-measure-of-covariance" id="toc-turning-the-numbers-into-a-measure-of-covariance" class="nav-link" data-scroll-target="#turning-the-numbers-into-a-measure-of-covariance"><span class="header-section-number">2.3.1</span> Turning the numbers into a measure of Covariance</a></li>
  <li><a href="#covariance-the-measure" id="toc-covariance-the-measure" class="nav-link" data-scroll-target="#covariance-the-measure"><span class="header-section-number">2.3.2</span> Covariance, the measure</a></li>
  <li><a href="#pearsons-r" id="toc-pearsons-r" class="nav-link" data-scroll-target="#pearsons-r"><span class="header-section-number">2.3.3</span> Pearson’s r</a></li>
  </ul></li>
  <li><a href="#regression-a-mini-intro" id="toc-regression-a-mini-intro" class="nav-link" data-scroll-target="#regression-a-mini-intro"><span class="header-section-number">2.4</span> Regression: A mini intro</a>
  <ul class="collapse">
  <li><a href="#the-best-fit-line" id="toc-the-best-fit-line" class="nav-link" data-scroll-target="#the-best-fit-line"><span class="header-section-number">2.4.1</span> The best fit line</a></li>
  <li><a href="#computing-the-best-fit-line" id="toc-computing-the-best-fit-line" class="nav-link" data-scroll-target="#computing-the-best-fit-line"><span class="header-section-number">2.4.2</span> Computing the best fit line</a></li>
  </ul></li>
  <li><a href="#interpreting-correlations-why-caution-is-warranted" id="toc-interpreting-correlations-why-caution-is-warranted" class="nav-link" data-scroll-target="#interpreting-correlations-why-caution-is-warranted"><span class="header-section-number">2.5</span> Interpreting Correlations: why caution is warranted</a>
  <ul class="collapse">
  <li><a href="#spurious-correlation-chance-alone-can-look-convincing" id="toc-spurious-correlation-chance-alone-can-look-convincing" class="nav-link" data-scroll-target="#spurious-correlation-chance-alone-can-look-convincing"><span class="header-section-number">2.5.1</span> Spurious correlation: chance alone can look convincing</a></li>
  <li><a href="#sample-size-and-stability" id="toc-sample-size-and-stability" class="nav-link" data-scroll-target="#sample-size-and-stability"><span class="header-section-number">2.5.2</span> Sample size and stability</a></li>
  <li><a href="#nonlinearity-when-r-misses-real-relationships" id="toc-nonlinearity-when-r-misses-real-relationships" class="nav-link" data-scroll-target="#nonlinearity-when-r-misses-real-relationships"><span class="header-section-number">2.5.3</span> Nonlinearity: when r misses real relationships</a></li>
  <li><a href="#anscombes-quartet-same-statistics-different-data" id="toc-anscombes-quartet-same-statistics-different-data" class="nav-link" data-scroll-target="#anscombes-quartet-same-statistics-different-data"><span class="header-section-number">2.5.4</span> Anscombe’s Quartet: same statistics, different data</a></li>
  <li><a href="#confounding-variables-third-variable-problem" id="toc-confounding-variables-third-variable-problem" class="nav-link" data-scroll-target="#confounding-variables-third-variable-problem"><span class="header-section-number">2.5.5</span> Confounding variables (third-variable problem)</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">2.6</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/02-Correlation.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="Correlation" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">August 26, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><em>Correlation does not equal causation.</em></p>
<p>Every Statistics Instructor Ever</p>
</blockquote>
<p>In the last chapter, we worked with data that felt overwhelming at first. We used plots and histograms to make the data visible, and descriptive statistics to summarize their central tendency and variability.</p>
<p>We learned those tools because we want to use data to answer questions. That theme runs through this course. As you read each section, keep asking yourself: how does this concept help me answer questions with data?</p>
<p>In Chapter 1, we described a season of daily air quality measurements. The data were just numbers, but they already raised useful questions. How spread out were the ozone readings? Did most days cluster near the middle, or were there clusters of especially clean and especially polluted days?</p>
<p>We also saw that numbers are imperfect stand-ins for the thing we actually care about. Ozone concentration at one station is one way of capturing air quality, and it may not capture the whole idea, but it is meaningful enough to work with.</p>
<p>Every one of those questions was about <strong>one variable at a time</strong>. That is the limit we run into now. Describing a single variable well tells you nothing about whether it changes along with anything else, and most interesting questions are about exactly that. Does ozone rise on hotter days? Do wetter winters produce taller trees?</p>
<p>Answering those questions means moving from description to explanation. Rather than asking only how much of something we observed, we start asking what it changes along with, which is the core of correlation analysis.</p>
<section id="what-data-look-like-when-one-thing-changes-another" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="what-data-look-like-when-one-thing-changes-another"><span class="header-section-number">2.1</span> What data look like when one thing changes another</h2>
<p>To use data for explanation, we need tools for recognizing when two things move together. Sometimes that reflects a real cause-and-effect relationship, and sometimes it doesn’t. The challenge is learning to tell the difference. In this chapter we’ll build intuition for what data look like when two variables are unrelated, when they move together, and when the pattern might mislead us.</p>
<section id="more-chocolate-more-happiness" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="more-chocolate-more-happiness"><span class="header-section-number">2.1.1</span> More Chocolate = More Happiness?</h3>
<p>Suppose a person’s chocolate supply has a causal influence on their happiness: more chocolate means more happiness, less chocolate means less. Because happiness is also caused by plenty of other things in a person’s life, we’d expect the relationship between chocolate and happiness to be real but imperfect, not a perfect one-to-one match.</p>
<p>Our first step is to collect some imaginary data from 100 people. We walk around and ask the first 100 people we meet to answer two questions:</p>
<ol type="1">
<li>how much chocolate do you have? and</li>
<li>how happy are you?</li>
</ol>
<p>For convenience, both the scales will go from 0 to 100. For the chocolate scale, 0 means no chocolate, 100 means lifetime supply of chocolate. Any other number is somewhere in between. For the happiness scale, 0 means no happiness, 100 means all of the happiness, and in between means some amount in between.</p>
<p>Here is some sample data from the first 10 imaginary subjects.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">subject</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">chocolate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">happiness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We asked each subject two questions so there are two scores for each subject, one for their chocolate supply, and one for their level of happiness. You might already notice some relationships between amount of chocolate and level of happiness in the table. To make those relationships even more clear, let’s plot all of the data in a graph.</p>
</section>
<section id="scatter-plots" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="scatter-plots"><span class="header-section-number">2.1.2</span> Scatter plots</h3>
<p>When you have two measurements worth of data, you can always turn them into dots and plot them in a scatter plot. A scatter plot has a horizontal x-axis, and a vertical y-axis. You get to choose which measurement goes on which axis. Let’s put chocolate supply on the x-axis, and happiness level on the y-axis. <a href="#fig-2scatter1" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> shows 100 dots. Each dot is for one subject and represents both their happiness level and their chocolate supply.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2scatter1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2scatter1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2scatter1-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2scatter1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Imaginary data showing a positive correlation between amount of chocolate and amount happiness
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each dot has two coordinates, an x-coordinate for chocolate, and a y-coordinate for happiness. Looking at the <strong>scatter plot</strong>, we can see that the dots show a pattern. People with less chocolate tend to report lower happiness, while those with more chocolate tend to report higher happiness. It looks like the more chocolate you have the happier you will be, and vice-versa. This kind of relationship is called a <strong>positive correlation</strong>.</p>
</section>
<section id="positive-negative-and-no-correlation" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="positive-negative-and-no-correlation"><span class="header-section-number">2.1.3</span> Positive, Negative, and No-Correlation</h3>
<p>Two other patterns are worth seeing: a reversed relationship, where more chocolate means less happiness, and no relationship at all, where chocolate supply has nothing to do with happiness. <a href="#fig-2posnegrand" class="quarto-xref">Figure&nbsp;<span>2.2</span></a> shows all three side by side:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2posnegrand" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2posnegrand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2posnegrand-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2posnegrand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Three scatterplots showing negative, positive, and zero correlation
</figcaption>
</figure>
</div>
</div>
</div>
<p>The first panel shows a <strong>negative correlation</strong>: happiness goes down as chocolate supply increases, more of X means less of Y. The second panel shows a <strong>positive correlation</strong>: happiness goes up as chocolate supply increases, more of X means more of Y. The third panel shows <strong>no correlation</strong>: there’s no obvious relationship between chocolate supply and happiness, changes in X don’t relate to changes in Y.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Tip: Always plot first">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip: Always plot first
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the scatter shows a U-shape or other curve, a single straight-line correlation will mislead. Fit a curved model (e.g., add a quadratic term) or transform variables instead of reporting <em>r</em> alone.</p>
</div>
</div>
<p>We’ve already covered how to generate descriptive statistics for individual variables through means, standard deviations, etc. But to summarize how two variables move together in a single descriptive statistic, we need a new one: Pearson’s <span class="math inline">\(r\)</span>. The path there starts with understanding covariance.</p>
</section>
</section>
<section id="how-much-does-one-variable-vary" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="how-much-does-one-variable-vary"><span class="header-section-number">2.2</span> How much does one variable vary?</h2>
<p>Before we can measure how two variables move <em>together</em>, we need a number for how much a single variable moves at all. That turns out to be the same machinery, used twice, so we build it once here and then extend it on the next page.</p>
<section id="difference-scores" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="difference-scores"><span class="header-section-number">2.2.1</span> Difference Scores</h3>
<p>It would be nice to summarize the amount of different<em>ness</em> in the data. Think about these 10 ordered numbers:</p>
<blockquote class="blockquote">
<p>1 3 4 5 5 6 7 8 9 24</p>
</blockquote>
<p>One idea is to compare every number to every other number. It works, but it scales badly: 10 numbers give 100 pairwise differences, and 500 numbers would give 250,000. If all the values were identical every difference would be 0 and the lack of variation would be obvious, but with real data we just get a large pile of differences. The natural way to summarize a pile of numbers is the one we just learned, so let’s take their <strong>average</strong>.</p>
<p>Let’s try it on a set small enough to see all at once:</p>
<blockquote class="blockquote">
<p>1 2 3</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean of these nine difference scores is:</p>
<p><span class="math inline">\(\text{mean of difference scores} = \frac{0+1+2-1+0+1-2-1+0}{9} = \frac{0}{9} = 0\)</span></p>
<p>This will always happen: the positives and negatives cancel. So the mean of raw difference scores is not a useful measure of variation.</p>
<p>Notice also that the matrix is redundant: the diagonal is always zero, and values above and below the diagonal are the same except for sign.</p>
<p>These problems motivate why we compute <strong>variance</strong> and <strong>standard deviation</strong>. They solve the cancellation issue and give us a practical summary of spread.</p>
</section>
<section id="the-variance" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="the-variance"><span class="header-section-number">2.2.2</span> The Variance</h3>
<p>We have used the words variability, variation, and variance a lot, and they all point at the same idea: numbers differ. The word <em>variance</em> does double duty, though. Loosely it means that general idea. Precisely it names a specific statistic, the <strong>mean of the squared deviations from the mean</strong>.</p>
<p>To calculate it, subtract the mean from each score to get its <strong>difference score</strong>, square those differences, then average them. Squaring is the trick that stops positive and negative deviations from cancelling. In short:</p>
<p><span class="math inline">\(variance = \frac{\text{Sum of squared difference scores}}{\text{Number of Scores}}\)</span></p>
<p>A little further on we’ll distinguish between dividing by <span class="math inline">\(N\)</span> (when you have the entire population) and <span class="math inline">\(n-1\)</span> (when you only have a sample, which is almost always the case). For now, just use <span class="math inline">\(N\)</span>.</p>
<p><strong>Deviations from the mean.</strong></p>
<p>Earlier we compared every number to every other number, which got unmanageable fast. The simpler approach is to compare each score to the mean instead: find the mean, then subtract it from every score. What comes back tells us both how well the mean represents the data and how much spread there is around it.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference_from_Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean here is <span class="math inline">\(\frac{1+6+4+2+6+8}{6} = \frac{27}{6} = 4.5\)</span>. The third column just repeats it on every row, which looks redundant but makes the earlier point concrete: six copies of 4.5 add back to the original total of 27. The fourth column is the <strong>deviation from the mean</strong>, <span class="math inline">\(X_{i}-\bar{x}\)</span>, so the score of 1 sits 3.5 below and the score of 6 sits 1.5 above.</p>
<p><strong>And now the problem.</strong> Those deviations sum to zero. The positives and negatives cancel exactly, which would suggest there is no variation at all, and that is obviously false. Squaring will fix it, but first it is worth seeing <em>why</em> the cancellation happens.</p>
<p><strong>Mean as the Balancing Point.</strong></p>
<p>The mean is the balancing point of the data. Imagine laying a ruler across your finger. The place where it balances is the point where the weight on each side is equal. Data works the same way: if we treat each value like a weight, the mean is where the total “mass” to the left and right cancel out.</p>
<p>This balancing property explains why the deviations always sum to zero. The values below the mean contribute negative deviations, the values above contribute positive ones, and together they cancel:</p>
<p><span class="math inline">\(-x + x = 0\)</span></p>
<p>To see this more concretely, consider the numbers</p>
<p><span class="math inline">\(X = (1,2,6,7,9)\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-number-line" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Horizontal number line with dots at 1, 2, 6, 7, and 9, each labeled above.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-number-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-number-line-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Horizontal number line with dots at 1, 2, 6, 7, and 9, each labeled above.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-number-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Values on a number line.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now imagine the number line as a teeter-totter. Only when the fulcrum is placed at 5 does the board balance:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mean-balance-panels" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three panels with a horizontal number line and a triangular fulcrum; the board tilts left/right when the fulcrum is not at the mean, and is level at the mean.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mean-balance-panels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-mean-balance-panels-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Three panels with a horizontal number line and a triangular fulcrum; the board tilts left/right when the fulcrum is not at the mean, and is level at the mean.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean-balance-panels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Mean as the unique balancing point. Only at the mean do signed deviations cancel.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Formally, this means the signed distances from the mean always cancel out:</p>
<p><span class="math inline">\((1−5)+(2−5)+(6−5)+(7−5)+(9−5)=0\)</span></p>
<p>This makes the mean unique. It is the <strong>only value</strong> for which the sum of deviations equals zero:</p>
<p><span class="math inline">\(\sum_{i=1}^{n}(x_{i}-a) = 0 \quad \Rightarrow \quad a = \bar{x}\)</span></p>
<p>The mean is not just a “typical” value, it is the one point where the data balance. And that balancing property is exactly why the raw deviations always sum to zero. To summarize variation, we need a way around this problem.</p>
<p><strong>The squared deviations.</strong></p>
<p>The standard trick is to square the deviations. Since <span class="math inline">\(2^2 = 4\)</span> and <span class="math inline">\((-2)^2 = 4\)</span>, squaring turns every negative into a positive, so the deviations can no longer cancel. We call these <strong>squared deviations</strong>. Here is the same table with a column for them:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference_from_Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Squared_Deviations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-3.5</td>
<td style="text-align: left;">12.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-0.5</td>
<td style="text-align: left;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-2.5</td>
<td style="text-align: left;">6.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">3.5</td>
<td style="text-align: left;">12.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">35.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">5.91666666666667</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The first score of 1 sits 3.5 below the mean, so its deviation is <span class="math inline">\(-3.5\)</span> and its squared deviation is <span class="math inline">\((-3.5)^2 = 12.25\)</span>. Now that nothing is negative we can add them up, and that total is the <strong>sum of squares (SS)</strong>. You will meet this quantity again in the ANOVA chapter, but there is nothing more to it than the sum of those squared deviations.</p>
<p><strong>Finally, the variance.</strong></p>
<p>We have already computed the variance, one step at a time, without naming it. The goal was a single number summarizing spread, but deviations give us as many numbers as we have data points, so we want their <em>average</em>. Sum the squared deviations, divide by how many there are, and that is <strong>the variance</strong>:</p>
<p><span class="math display">\[variance = \frac{SS}{N}\]</span></p>
<p>For our data it comes to 5.916. On its own that number is hard to interpret, because squaring the deviations put it on a <em>squared</em> scale, so it is no longer in the same units as the data. The fix is to take the square root, <span class="math inline">\(\sqrt{5.916} \approx 2.43\)</span>.</p>
</section>
<section id="the-standard-deviation" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="the-standard-deviation"><span class="header-section-number">2.2.3</span> The Standard Deviation</h3>
<p>That square root is the <strong>standard deviation (SD)</strong>, so we had already computed it a step earlier without naming it:</p>
<p><span class="math display">\[\text{standard deviation} = \sqrt{Variance} = \sqrt{\frac{SS}{N}} = \sqrt{\frac{\sum_{i}^{n}(x_{i}-\bar{x})^2}{N}}\]</span></p>
<p>The square root “unsquares” the variance, putting the measure of spread back on the original scale of the data. Here is the table one more time:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference_from_Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Squared_Deviations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-3.5</td>
<td style="text-align: left;">12.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-0.5</td>
<td style="text-align: left;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-2.5</td>
<td style="text-align: left;">6.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">2.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">3.5</td>
<td style="text-align: left;">12.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">35.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">5.91666666666667</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Our standard deviation, <span class="math inline">\(\sqrt{5.916} \approx 2.43\)</span>, makes far more sense than the variance did. A variance of 5.916 feels too large for this data because it is on the squared scale, but an SD of 2.43 lines up with the actual deviations, since most scores fall within about 2.4 of the mean of 4.5.</p>
<p><strong>That is what makes the SD so useful.</strong> Told only that a dataset has a mean of 4.5 and an SD of 2.4, you already have a picture of it: values cluster around 4.5, not exactly at it, with a typical spread of two to three units either way. It gives you the <em>typical deviation</em> from the mean while staying in the original units.</p>
</section>
<section id="mean-absolute-deviation" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4" class="anchored" data-anchor-id="mean-absolute-deviation"><span class="header-section-number">2.2.4</span> Mean Absolute Deviation</h3>
<p>So far we’ve handled the “differences cancel out” problem by squaring deviations. But there’s another simple option: take the <strong>absolute value</strong> of each deviation from the mean. That way, every difference becomes positive, and when we add them up we don’t end up at zero.</p>
<p>Here’s what that looks like for our data:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference_from_Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Absolute_Deviations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-3.5</td>
<td style="text-align: left;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-0.5</td>
<td style="text-align: left;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">-2.5</td>
<td style="text-align: left;">2.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">1.5</td>
<td style="text-align: left;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">3.5</td>
<td style="text-align: left;">3.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">4.5</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">2.16666666666667</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The last column shows absolute deviations. If we take their mean, we get the mean absolute deviation (MAD). Notice this acts a lot like the standard deviation: it’s the average size of a deviation from the mean, only without squaring. Both approaches, squaring and taking absolute values, solve the same problem in slightly different ways. Squaring is more common because it leads to nice mathematical properties (like in regression and ANOVA), but the MAD can be more intuitive to interpret.</p>
</section>
</section>
<section id="covariance" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="covariance"><span class="header-section-number">2.3</span> Covariance</h2>
<p>We now have a number for how one variable varies. <strong>Covariance</strong> is the same idea for two: it tells us whether being above the mean on <span class="math inline">\(X\)</span> tends to come with being above the mean on <span class="math inline">\(Y\)</span> (positive), below the mean on <span class="math inline">\(Y\)</span> (negative), or neither (near zero).</p>
<p>In our chocolate–happiness example, the scatter plot suggested that higher chocolate tends to come with higher happiness. That means the deviations from each mean often have the same sign, so their products are mostly positive: evidence of <em>positive</em> covariance. Put simply, the two variables <strong>vary together</strong>.</p>
<p>Covariance is important because it underlies correlation, regression, and many other statistical tools. It can feel abstract at first, so keep the core idea in mind: look at how each variable’s deviations from its mean behave together.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note: Covariance intuition">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: Covariance intuition
</div>
</div>
<div class="callout-body-container callout-body">
<p>Think of a three-legged race. When partners move forward together, their steps align (positive covariance). When one moves forward as the other moves back, their steps oppose (negative covariance). If their steps are uncoordinated, there’s no consistent pattern (covariance near zero).</p>
</div>
</div>
<section id="turning-the-numbers-into-a-measure-of-covariance" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="turning-the-numbers-into-a-measure-of-covariance"><span class="header-section-number">2.3.1</span> Turning the numbers into a measure of Covariance</h3>
<p>To turn “chocolate and happiness vary together” into an actual number, we need a way to measure that relationship directly. Consider our chocolate and happiness scores.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">subject</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">chocolate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">happiness</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Chocolate_X_Happiness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">42</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">236</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.7</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">23.6</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We’ve added a new column called <code>Chocolate_X_Happiness</code>, which is simply each person’s chocolate score multiplied by their happiness score. Why multiply? Because the products reveal how the two values move together.</p>
<ul>
<li>Small × small → small product</li>
<li>Large × large → large product</li>
<li>Small × large → product in between</li>
</ul>
<p>Now extend this idea from pairs to the whole dataset. If chocolate and happiness rise together (both above average at the same time), the summed products will be large. If one tends to rise while the other falls, the summed products will shrink. This is the basic logic behind <strong>covariance</strong>.</p>
<p>Suppose we have two variables, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> go up together (both small at the same time, both large at the same time), their products will also be large when summed across the dataset. If one goes up while the other goes down (large pairs with small), the summed products will be much smaller.</p>
<p>Here are two tables to illustrate:</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-bordered caption-top table-sm table-striped small">
<caption>Aligned: sum = 385</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">X</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Y</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">XY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">64</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">81</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">385</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-bordered caption-top table-sm table-striped small">
<caption>Reversed: sum = 220</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">A</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">B</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">220</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p><span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are perfectly aligned: <span class="math inline">\(1\)</span> with <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span> with <span class="math inline">\(2\)</span>, up to <span class="math inline">\(10\)</span> with <span class="math inline">\(10\)</span>. Their products add up to <strong>385</strong>, the <em>largest</em> possible sum.</p>
<p><span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are perfectly reversed: <span class="math inline">\(1\)</span> with <span class="math inline">\(10\)</span>, <span class="math inline">\(2\)</span> with <span class="math inline">\(9\)</span>, and so on. Their products add up to <strong>220</strong>, the <em>smallest</em> possible sum.</p>
<p>Any other pairing of 1–10 with 1–10 will fall between these two extremes. <a href="#fig-2simsum" class="quarto-xref">Figure&nbsp;<span>2.5</span></a> shows the sums of products from 1000 random pairings. Every result falls between 220 (perfect negative alignment) and 385 (perfect positive alignment).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2simsum" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2simsum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2simsum-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2simsum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.5: Simulated sums of products showing the kinds of values that can be produced by randomly ordering the numbers in X and Y.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <strong>sum of the products</strong> tells us about the direction of the relationship:</p>
<ul>
<li>Close to 385 → strong positive relationship.</li>
<li>Close to 220 → strong negative relationship.</li>
<li>Near the middle → little or no relationship.</li>
</ul>
<p>This is the foundation of <em>covariance</em>: products of paired values reveal whether two variables rise together, fall together, or move in opposite directions.</p>
</section>
<section id="covariance-the-measure" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="covariance-the-measure"><span class="header-section-number">2.3.2</span> Covariance, the measure</h3>
<p>Earlier we saw that multiplying values from two variables can highlight how they vary together: large-with-large and small-with-small pairs push the product up, while mixed pairs keep it lower. That intuition is useful, but in statistics we define <strong>covariance</strong> more precisely.</p>
<p>Instead of multiplying raw values of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, we multiply their <em>deviations from the mean</em>. This centers each variable, so the product reflects how the two variables co-vary around their averages:</p>
<p><span class="math inline">\(cov(X,Y) = \frac{\sum_{i}^{n}(x_{i}-\bar{x})(y_{i}-\bar{Y})}{N}\)</span></p>
<p>In practice, the steps are straightforward: subtract the mean of <span class="math inline">\(X\)</span> from each <span class="math inline">\(x_i\)</span>, subtract the mean of <span class="math inline">\(Y\)</span> from each <span class="math inline">\(y_i\)</span>, multiply the deviations, and then average those products. A positive covariance means the two variables tend to move together (above or below their means at the same time). A negative covariance means they move in opposite directions. A covariance near zero suggests no consistent relationship.</p>
<p>The following table shows this process:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">subject</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">chocolate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">happiness</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">C_d</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">H_d</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Cd_x_Hd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">-3.7</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">11.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">-2.7</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">8.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-1.7</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">3.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-1.7</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">3.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">0.3</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-0.7</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">-0.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">2.3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">3.3</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">0.3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">0.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">4.3</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">17.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">48</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.7</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">4.8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Deviations from the mean for chocolate (column <code>C_d</code>), deviations from the mean for happiness (column <code>H_d</code>), and their products. The mean of those products (in the bottom right corner of the table) is the official <strong>covariance</strong>.</p>
<p>One note before moving on. The formula above divides by <span class="math inline">\(N\)</span>, which is the population version, and that is what the table computes. R’s <code>cov()</code> and <code>sd()</code> divide by <span class="math inline">\(n-1\)</span> instead, for the same reason the sample standard deviation did earlier in this chapter. The two differ only by a factor of <span class="math inline">\(n/(n-1)\)</span>, and that factor cancels completely in Pearson’s <span class="math inline">\(r\)</span> below, so <span class="math inline">\(r\)</span> comes out identical either way. If you compute the covariance itself in R, though, expect a slightly larger number than the one in this table.</p>
<p>Covariance is a powerful idea, but it has a major drawback: its magnitude is hard to interpret. Just as variance is tied to squared units, covariance is tied to the scales of both variables, so a covariance of 3.22 isn’t inherently “large” or “small” the way a correlation is. All we can read directly from it is the sign, not the strength. To compare strength across variables with different units or scales, we need to normalize covariance, which leads to Pearson’s <span class="math inline">\(r\)</span>.</p>
</section>
<section id="pearsons-r" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="pearsons-r"><span class="header-section-number">2.3.3</span> Pearson’s r</h3>
<p>We often want a relationship measure that is <strong>directional</strong>, <strong>unitless</strong>, and <strong>bounded</strong>. <strong>Pearson’s</strong> <span class="math inline">\(r\)</span> does exactly this by rescaling covariance to lie between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>:</p>
<ul>
<li><span class="math inline">\(r=1\)</span>: perfect positive linear relationship</li>
<li><span class="math inline">\(r=0\)</span>: no linear relationship</li>
<li><span class="math inline">\(r=-1\)</span>: perfect negative linear relationship</li>
</ul>
<p>Values closer to <span class="math inline">\(\pm1\)</span> indicate stronger linear association; values near <span class="math inline">\(0\)</span> indicate weak or no linear association.</p>
<p>Let’s take a look at a formula for Pearson’s <span class="math inline">\(r\)</span>:</p>
<p><span class="math inline">\(r = \frac{cov(X,Y)}{\sigma_{X}\sigma_{Y}} = \frac{cov(X,Y)}{SD_{X}SD_{Y}}\)</span></p>
<p>Here, <span class="math inline">\(\sigma\)</span> is the standard deviation (SD), so <span class="math inline">\(r\)</span> is the covariance of X and Y divided by the product of their standard deviations. Dividing by the standard deviations <strong>normalizes</strong> the covariance, constraining <span class="math inline">\(r\)</span> to fall between -1 and 1, which makes correlation values comparable across variables measured in different units or on different scales.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note: Computing *r*">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: Computing <em>r</em>
</div>
</div>
<div class="callout-body-container callout-body">
<p>You’ll see several algebraically equivalent formulas for Pearson’s <em>r</em>, some easier for hand calculation, others more compact. They all produce the same result. In practice, you’ll compute <span class="math inline">\(r\)</span> with software, so the priority here is understanding what <span class="math inline">\(r\)</span> means and how to interpret it. Working through one example by hand still helps: it shows where <span class="math inline">\(r\)</span> actually comes from, which is why lecture walks through a full hand calculation before you run it in R during lab.</p>
</div>
</div>
<p>To confirm <span class="math inline">\(r\)</span> really does stay between -1 and 1, <a href="#fig-2onethousandr" class="quarto-xref">Figure&nbsp;<span>2.6</span></a> shows a simulation: we randomly ordered the numbers 1 to 10 for both an X measure and a Y measure, computed Pearson’s <span class="math inline">\(r\)</span> between them, and repeated the process 1000 times. Every dot falls between -1 and 1.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2onethousandr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2onethousandr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2onethousandr-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2onethousandr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.6: A simulation of correlations. Each dot is the r-value between an X and Y variable that each contain the numbers 1 to 10 in random orders.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="regression-a-mini-intro" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="regression-a-mini-intro"><span class="header-section-number">2.4</span> Regression: A mini intro</h2>
<p>This section adds one more piece to our understanding of correlation: <strong>linear regression</strong>, at an introductory level.</p>
<p><a href="#fig-2regression" class="quarto-xref">Figure&nbsp;<span>2.7</span></a> shows the same three scatter plots as before, now with a fitted line added to each.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2regression-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.7: Three scatterplots showing negative, positive, and a random correlation (where the r-value is expected to be 0), along with the best fit regression line
</figcaption>
</figure>
</div>
</div>
</div>
<section id="the-best-fit-line" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="the-best-fit-line"><span class="header-section-number">2.4.1</span> The best fit line</h3>
<p>Notice the red lines in these panels. Each is a <strong>best fit</strong> line: the single straight line that best summarizes the overall pattern of dots.</p>
<p>With one variable, we use the mean to describe central tendency in one dimension. With two variables plotted together, we need a two-dimensional equivalent. A line serves that purpose, capturing the average relationship across the cloud of points.</p>
<p>Many lines could be drawn through a scatter of points, but most would miss the pattern. The best fit line is the one with the least error, defined precisely below.</p>
<p><a href="#fig-2regressionResiduals" class="quarto-xref">Figure&nbsp;<span>2.8</span></a> shows what that error looks like: a line runs through the dots, and short vertical lines drop from each dot to the line. These are <strong>residuals</strong>, the vertical differences between the observed data and the fitted line, showing how far off the line’s prediction is for each point. Since not all dots fall exactly on the line, some error is inevitable; the best-fit line is the one that minimizes it overall.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2regressionResiduals" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2regressionResiduals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2regressionResiduals-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2regressionResiduals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.8: Black dots are the data, white dots are the values the regression line predicts, and the red lines are the errors between them. R code for residual visualization adapted from Simon Jackson: <a href="https://drsimonj.svbtle.com/visualising-residuals" class="uri">https://drsimonj.svbtle.com/visualising-residuals</a>
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-2regressionResiduals" class="quarto-xref">Figure&nbsp;<span>2.8</span></a> shows a scatter plot of two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Each black dot represents observed data; the blue line is the regression line, and the white dots show its predicted values. The red lines are <strong>residuals</strong>: they drop vertically from each observed value to its predicted value on the line, showing how far the prediction differs from what was actually observed.</p>
<p>The regression line is chosen to minimize the total size of these residuals. In practice, we compute the <strong>sum of squared deviations</strong>: square each residual, then add them together. The blue line produces the smallest possible total squared error; any other line would yield a larger one.</p>
<p><a href="#fig-2regressionGIF" class="quarto-xref">Figure&nbsp;<span>2.9</span></a> animates this directly, comparing the best fit line (blue) to other possible lines (black) as the black line moves up and down. The red lines show the error between the black line and the data points at each position, and the shaded grey area shrinks to its minimum exactly when the black line reaches the best fit line, then expands again as it moves away.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2regressionGIF" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2regressionGIF-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imgs/gifs/regression-1.gif" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2regressionGIF-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.9: The black line moves through alternative positions while the blue best-fit line stays put. Red lines show each point’s error, and the shaded grey area is their total, which shrinks to a minimum exactly at the best-fit line.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Whenever the black line does not overlap with the blue line, it fits the data less well: the blue regression line is the one that minimizes the overall error, not too high, not too low, but the line with the least total deviation.</p>
<p><a href="#fig-2minimizeSS" class="quarto-xref">Figure&nbsp;<span>2.10</span></a> makes that error concrete: for each position of the black line, we square the length of every red line from the animation above and add them up, giving the total sum of squared deviations at that position. The dots start high on the left, swoop down to a minimum in the middle, and rise again on the right. That minimum point is the best fit regression line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2minimizeSS" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2minimizeSS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2minimizeSS-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2minimizeSS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.10: A plot of the sum of the squared deviations for different lines moving up and down, through the best fit line. The best fit line occurs at the position that minimizes the sum of the squared deviations.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This graph shows how the total error behaves as the line’s y-intercept moves up and down: the error rises whether we shift the line down (0 to -5) or up (0 to +5), and is smallest right in the middle, at the original best fit line.</p>
</section>
<section id="computing-the-best-fit-line" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="computing-the-best-fit-line"><span class="header-section-number">2.4.2</span> Computing the best fit line</h3>
<p>How do we find the line that minimizes the sum of squared deviations? In principle, you could try many possible lines and compare their errors, but that’s not efficient. Instead, we use formulas (or, more realistically, software) to identify the line with the smallest total error.</p>
<p>Next we’ll look at the formulas for calculating the slope and intercept of a regression line, and work through one example by hand. Many statistical formulas were designed to simplify hand calculations before computers were common. Today we rely on software, but working through examples by hand helps illustrate the logic behind the formulas.</p>
<p>Here are two formulas we can use to calculate the slope and the intercept, straight from the data. We won’t go into why these formulas do what they do. These ones are for “easy” calculation.</p>
<p><span class="math inline">\(intercept = b = \frac{\sum{y}\sum{x^2}-\sum{x}\sum{xy}}{n\sum{x^2}-(\sum{x})^2}\)</span></p>
<p><span class="math inline">\(slope = m = \frac{n\sum{xy}-\sum{x}\sum{y}}{n\sum{x^2}-(\sum{x})^2}\)</span></p>
<p>In these formulas, the <span class="math inline">\(x\)</span> and the <span class="math inline">\(y\)</span> refer to the individual scores. Here’s a table showing you how everything fits together.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">x</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">y</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">x_squared</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">y_squared</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">xy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">81</td>
<td style="text-align: left;">72</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">34</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">200</td>
<td style="text-align: left;">275</td>
<td style="text-align: left;">231</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table has 7 pairs of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> scores, plus columns for <span class="math inline">\(x^2\)</span>, <span class="math inline">\(y^2\)</span>, and <span class="math inline">\(xy\)</span> (each <span class="math inline">\(x\)</span> score times its matching <span class="math inline">\(y\)</span> score), with column sums at the bottom. These sums are everything the formulas need. Here’s what they look like with numbers plugged in:</p>
<p><span class="math inline">\(intercept = b = \frac{\sum{y}\sum{x^2}-\sum{x}\sum{xy}}{n\sum{x^2}-(\sum{x})^2} = \frac{39 * 200 - 34*231}{7*200-34^2} = -.221\)</span></p>
<p><span class="math inline">\(slope = m = \frac{n\sum{xy}-\sum{x}\sum{y}}{n\sum{x^2}-(\sum{x})^2} = \frac{7*231-34*39}{7*200-34^2} = 1.19\)</span></p>
<p>To check the work, plot the scores and draw a line through them with slope = 1.19 and y-intercept = -.221. As shown in <a href="#fig-2corwithLine" class="quarto-xref">Figure&nbsp;<span>2.11</span></a>, the line runs through the middle of the dots, as it should.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2corwithLine" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2corwithLine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2corwithLine-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2corwithLine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.11: An example regression line going through a few data points in a scatterplot.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="interpreting-correlations-why-caution-is-warranted" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="interpreting-correlations-why-caution-is-warranted"><span class="header-section-number">2.5</span> Interpreting Correlations: why caution is warranted</h2>
<p>You’ve heard the warning that <strong>correlation does not equal causation</strong>. Interpreting correlations requires care, because the same number can arise from very different situations: random chance, confounding influences, or nonlinear patterns. In this section, we’ll look at why correlations can be unreliable and how to recognize their limits.</p>
<section id="spurious-correlation-chance-alone-can-look-convincing" class="level3" data-number="2.5.1">
<h3 data-number="2.5.1" class="anchored" data-anchor-id="spurious-correlation-chance-alone-can-look-convincing"><span class="header-section-number">2.5.1</span> Spurious correlation: chance alone can look convincing</h3>
<p>Correlations can be produced by random chance. You can find a positive or negative correlation between two measures that have nothing to do with one another, and you will, often enough that it matters. Unrelated measures produce these <strong>spurious</strong> correlations by chance alone.</p>
<p>Let’s demonstrate how correlations can appear by chance when there is no causal connection between two measures. Imagine two independent participants, one at the North Pole and one at the South Pole. Each has a lottery machine containing balls numbered 1 through 10. With replacement, each participant randomly draws 10 balls and records the numbers. Because the draws occur independently and half a world apart, there is no possible causal link between the two sets of numbers. The outcomes are determined by chance alone.</p>
<p>Here is what the numbers on each ball could look like for each participant:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Ball</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">North_pole</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">South_pole</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In this one case, if we computed Pearson’s <span class="math inline">\(r\)</span>, we would find that <span class="math inline">\(r =\)</span> -0.2. But, we already know that this value does not tell us anything about the relationship between the balls chosen in the north and south pole. We know that relationship should be completely random, because that is how we set up the game.</p>
<p>The better question is what random chance alone can do: if we ran this game thousands of times, each time drawing new balls and computing the correlation, the <span class="math inline">\(r\)</span> value would fluctuate across the whole range. Looking at the shape of that fluctuation tells us what kinds of correlations chance can produce.</p>
<p><strong>Monte-carlo: what chance produces.</strong></p>
<p>We can use a computer to repeat the lottery game as many times as we like. This process, repeated random sampling to explore possible outcomes, is called a <strong>Monte Carlo simulation</strong>.</p>
<p>Running the game 1,000 times, each time generating 10 random numbers for both the North Pole and South Pole participants and computing the correlation between them, gives 1,000 different values of Pearson’s <span class="math inline">\(r\)</span>, each produced under conditions where we know no real relationship exists.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2anotherthousand" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2anotherthousand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2anotherthousand-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2anotherthousand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.12: Another figure showing a range of r-values that can be obtained by chance.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-2anotherthousand" class="quarto-xref">Figure&nbsp;<span>2.12</span></a> shows the outcome. Each dot is one simulated correlation. All of them fall between –1 and 1, but the values scatter widely: sometimes strongly positive, sometimes strongly negative, often near zero. The point is that <strong>chance alone can generate correlations of any size</strong>. Finding a correlation in your data does not by itself guarantee a meaningful relationship.</p>
<p>To visualize this process more concretely, we can animate a single run. In <a href="#fig-2randcor10gif" class="quarto-xref">Figure&nbsp;<span>2.13</span></a>, each frame shows two sets of 10 random values plotted against each other, along with the fitted regression line. Because the data are random, we expect no consistent pattern. Yet across repetitions, the line slopes upward, then downward, then occasionally flat. This is what spurious correlation looks like, and how quickly random samples can mimic a real pattern.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2randcor10gif" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2randcor10gif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imgs/gifs/corUnifn10-1.gif" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2randcor10gif-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.13: Completely random data points drawn from a uniform distribution with a small sample size of 10. The red trend line twirls around sometimes showing large correlations that are produced by chance
</figcaption>
</figure>
</div>
</div>
</div>
<p>This leaves us with a real problem: <strong>how do we know whether the correlation we observed is meaningful or just chance?</strong> One way forward is to look at the whole distribution of outcomes chance produces, rather than at a single outcome. By simulating 1,000 random correlations and plotting them in a histogram, we can see which values occur frequently and which are rare.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2histrandcor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2histrandcor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2histrandcor-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2histrandcor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.14: A histogram showing the frequency distribution of r-values for completely random values between an X and Y variable (sample-size=10). A full range of r-values can be obtained by chance alone. Larger r-values are less common than smaller r-values
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-2histrandcor" class="quarto-xref">Figure&nbsp;<span>2.14</span></a> shows that most chance correlations cluster near zero. Moderate correlations (around <span class="math inline">\(\pm 0.5\)</span>) occur less frequently, and near-perfect correlations (<span class="math inline">\(\pm 0.95\)</span>) are almost absent. This distribution defines a “window of chance.” When we compute a correlation in real data, we can ask: is our observed <span class="math inline">\(r\)</span> consistent with what chance alone could plausibly generate?</p>
<p>For example, if you observed <span class="math inline">\(r=0.1\)</span>, the histogram shows that such values are common in random data, so chance could easily explain it. An observed <span class="math inline">\(r=0.5\)</span> is less common but still possible by chance. An observed <span class="math inline">\(r=0.95\)</span>, however, falls outside what chance typically produces, suggesting that something more systematic is driving the relationship.</p>
</section>
<section id="sample-size-and-stability" class="level3" data-number="2.5.2">
<h3 data-number="2.5.2" class="anchored" data-anchor-id="sample-size-and-stability"><span class="header-section-number">2.5.2</span> Sample size and stability</h3>
<p>So far, our lottery game has used 10 draws per participant. With such small samples, chance produces a wide range of correlations: sometimes strongly positive, sometimes strongly negative. But what happens if we increase the sample size?</p>
<p>We can repeat the simulation under four conditions: each participant draws 10, 50, 100, or 1000 numbers. In each case, we run 1000 simulations and record the correlation values.</p>
<p><a href="#fig-2corrandN" class="quarto-xref">Figure&nbsp;<span>2.15</span></a> shows the resulting four histograms of Pearson <span class="math inline">\(r\)</span> values.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2corrandN" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2corrandN-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2corrandN-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2corrandN-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.15: Distributions of r-values between completely random X and Y variables, at four sample sizes. The distributions narrow as sample size grows.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The pattern is clear:</p>
<ul>
<li>With <strong>n=10</strong>, correlations spread widely across the range –1 to 1. Chance alone frequently produces values that would look “strong” in real data.</li>
<li>With <strong>n=50 or 100</strong>, the spread narrows, but moderate correlations still appear.</li>
<li>With <strong>n=1000</strong>, almost all simulated correlations fall close to zero.</li>
</ul>
<p>The takeaway is that <strong>larger samples reduce the influence of chance</strong>. Small samples are highly unstable, making it difficult to distinguish signal from noise. As sample size increases, the distribution of chance correlations collapses toward zero, so observing a large <span class="math inline">\(r\)</span> becomes far less likely under randomness alone.</p>
<p>This illustrates why researchers place so much emphasis on collecting sufficient data. With too few observations, even strong-looking correlations may be spurious. With larger samples, a correlation of the same size is much harder to attribute to chance, and therefore more likely to reflect a real underlying relationship.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Tip: Sample size">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip: Sample size
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bigger <em>n</em> narrows the “window of chance.” If you expect a modest linear effect (e.g., |r| ≈ 0.2–0.3), plan for larger samples so random swings are less likely to mimic or mask the effect.</p>
</div>
</div>
<p><strong>Visualizing the effect of sample size.</strong></p>
<p>Animations make it easier to see how sample size influences the stability of correlation estimates. When the sample is very small, chance variation can create apparent patterns in any direction. As the sample size increases, those chance fluctuations diminish.</p>
<p><strong>When there is no true correlation</strong></p>
<p>In <a href="#fig-2corRandfour" class="quarto-xref">Figure&nbsp;<span>2.16</span></a>, each panel shows two random variables sampled with no real relationship. The panels differ only in sample size: 10, 50, 100, or 1000 observations. Each frame of the animation re-samples the data, plots them, and fits a line.</p>
<p>With <span class="math inline">\(n=10\)</span>, the line swings dramatically from positive to negative slopes. At <span class="math inline">\(n=50\)</span> and <span class="math inline">\(n=100\)</span>, the line still shifts but is more restrained. At <span class="math inline">\(n=1000\)</span>, the line is consistently flat, as expected when no correlation exists.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2corRandfour" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2corRandfour-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imgs/gifs/corUnifFourNs-1.gif" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2corRandfour-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.16: Animation of how correlation behaves for completely random X and Y variables as a function of sample size. The best fit line is not very stable for small sample-sizes, but becomes more reliably flat as sample-size increases.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The line from the sample with 1000 observations is the most reliable. It stays nearly flat across repetitions, as we would expect when no true correlation exists. The line from a sample of only 10 observations swings wildly. Claims about correlation are only as trustworthy as the sample size behind them.</p>
<p><strong>When there is a true correlation</strong></p>
<p>In <a href="#fig-2realcorFour" class="quarto-xref">Figure&nbsp;<span>2.17</span></a>, the simulation is repeated with a real positive correlation built into the data. Again, we vary the sample size from 10 to 1000.</p>
<p>With <span class="math inline">\(n=10\)</span>, the regression line jumps around and occasionally even points downward, despite the underlying positive relationship. As the sample size grows, the line becomes more stable and consistently reflects the true positive slope. Sampling error still introduces some noise, but with larger samples the real correlation is much easier to detect.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2realcorFour" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2realcorFour-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imgs/gifs/corRealgif-1.gif" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2realcorFour-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.17: How correlation behaves as a function of sample-size when there is a true correlation between X and Y variables.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Even when a real positive correlation exists, a small sample might miss it, or even suggest the opposite, simply due to chance. Because we usually only have one sample, we can never know for certain whether we were “lucky” or “unlucky.” The best protection is to collect more data.</p>
</section>
<section id="nonlinearity-when-r-misses-real-relationships" class="level3" data-number="2.5.3">
<h3 data-number="2.5.3" class="anchored" data-anchor-id="nonlinearity-when-r-misses-real-relationships"><span class="header-section-number">2.5.3</span> Nonlinearity: when r misses real relationships</h3>
<p>Consider a snake plant. Like most plants, it needs water to stay alive, but also needs <em>the right amount</em> of water. Imagine we grow 1000 snake plants, each receiving a different amount of water per day, ranging from <em>no water</em> to <em>extreme overwatering</em> (say 1000 teaspoons a day), and measure their weekly growth. Water is clearly causally related to plant growth, so we’d expect to see a correlation.</p>
<p>Plants given no water at all will eventually die, showing little or no weekly growth. With only a few teaspoons per day, plants may survive but grow only modestly. In a scatter plot, those cases would appear near the bottom left (low water, low growth) and rise upward as water increases. Growth continues to improve until a threshold is reached, beyond which excess water harms the plants. Severely overwatered plants also fail to grow and eventually die, just as those given no water do.</p>
<p>The scatter plot would form an inverted U or V: as water increases, growth rises to a peak and then declines with overwatering. A relationship like this can produce a Pearson’s <span class="math inline">\(r\)</span> close to zero, even though water clearly affects growth. <a href="#fig-2snakeplant" class="quarto-xref">Figure&nbsp;<span>2.18</span></a> illustrates this pattern.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2snakeplant" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2snakeplant-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-2snakeplant-1.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2snakeplant-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.18: Illustration of a possible relationship between amount of water and snake plant growth. Growth goes up with water, but eventually goes back down as too much water makes snake plants die.
</figcaption>
</figure>
</div>
</div>
</div>
<p>There is clearly a relationship between watering and snake plant growth. But, the correlation isn’t in one direction. As a result, when we compute the correlation in terms of Pearson’s r, we get a value very close to zero, suggesting no relationship.</p>
<div class="cell">
<pre><code>#&gt; [1] 0.009793996</code></pre>
</div>
<p>What this really means is there is no relationship that can be described by a <em>single straight line</em>. When we need lines or curves going in more than one direction, we have a nonlinear relationship.</p>
<p>This example shows why correlations can be tricky to interpret. Water is clearly necessary for plant growth, yet the overall correlation can be misleading. The first half of the data suggests a positive relationship, the second half a negative one, and the full dataset little or none. Even with a real causal link, a single correlation coefficient may fail to capture it. This is one reason plotting matters: if you see an upside-down U in the scatter, correlation is probably not the right analysis for your data.</p>
</section>
<section id="anscombes-quartet-same-statistics-different-data" class="level3" data-number="2.5.4">
<h3 data-number="2.5.4" class="anchored" data-anchor-id="anscombes-quartet-same-statistics-different-data"><span class="header-section-number">2.5.4</span> Anscombe’s Quartet: same statistics, different data</h3>
<p>Everything so far has compressed a relationship into a number: a covariance, an <span class="math inline">\(r\)</span>, a slope. Those numbers are summaries, and summaries lose things. The most famous demonstration of how much they can lose is a set of four datasets built to share almost every statistic you would think to compute.</p>
<p>Francis Anscombe (<span class="citation" data-cites="Anscombe1973">Anscombe (<a href="references.html#ref-Anscombe1973" role="doc-biblioref">1973</a>)</span>) made this point with a famous example, now called <em>Anscombe’s Quartet</em>. Each panel in <a href="#fig-anscombe" class="quarto-xref">Figure&nbsp;<span>2.19</span></a> shows pairs of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> values as a scatterplot.</p>
<p>Visually, the four panels are very different: one looks linear, one curved, one is mostly linear except for an outlier, and one forms a near-vertical line except for one point.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-anscombe" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Anscombe's Quartet, a set of four scatter plots each with a different pattern, despite having identical descriptive statistics. This illustrates the importance of graphing data to understand underlying relationships beyond basic statistical measures">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anscombe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-Correlation_files/figure-html/fig-anscombe-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Anscombe's Quartet, a set of four scatter plots each with a different pattern, despite having identical descriptive statistics. This illustrates the importance of graphing data to understand underlying relationships beyond basic statistical measures">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anscombe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.19: Anscombe’s Quartet
</figcaption>
</figure>
</div>
</div>
</div>
<p>Yet if we summarize each quartet with just its descriptive statistics:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">quartet</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_x</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">var_x</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_y</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">var_y</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">cor_xy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">4.13</td>
<td style="text-align: right;">0.82</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">4.13</td>
<td style="text-align: right;">0.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">4.12</td>
<td style="text-align: right;">0.82</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">4.12</td>
<td style="text-align: right;">0.82</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Rounded to two decimals, all four datasets have the <strong>same descriptive statistics</strong>:</p>
<ul>
<li><p>same mean and variance for <span class="math inline">\(x\)</span></p></li>
<li><p>same mean and variance for <span class="math inline">\(y\)</span></p></li>
<li><p>same correlation between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span></p></li>
</ul>
<p>Yet the scatterplots could not look more different. (Anscombe constructed the four sets to agree to two decimal places, so they differ very slightly beyond that. Carry more decimals and the variances of <span class="math inline">\(y\)</span> separate in the third one.)</p>
</section>
<section id="confounding-variables-third-variable-problem" class="level3" data-number="2.5.5">
<h3 data-number="2.5.5" class="anchored" data-anchor-id="confounding-variables-third-variable-problem"><span class="header-section-number">2.5.5</span> Confounding variables (third-variable problem)</h3>
<p>Correlations can arise because of a third variable: something not directly measured that influences both variables of interest. Returning to the snake plant example: imagine we measure water and plant growth, but ignore sunlight. If plants in sunnier windows both receive more water and grow faster, we might attribute the effect to water alone, when in fact sunlight is doing much of the work.</p>
<p>The same issue appears in human data. Suppose we find that income and happiness are positively correlated. Money itself might be the cause, but other factors, such as housing quality, healthcare access, or social opportunities, may be the true drivers, correlated with income and independently influencing happiness.</p>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">2.6</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> Correlation is how we quantify whether two variables move together. It’s essential for describing patterns (e.g., temperature and canopy cover, chocolate and happiness) and for deciding whether a relationship is worth modeling or acting on.</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>Scatter first, always.</strong> A scatter plot shows direction (up, down, none), form (straight vs curved), and outliers. If the pattern is curved, don’t stop at <em>r</em>: fit a suitable model (e.g., add a quadratic term) or transform a variable instead.</li>
<li><strong>Covariance → correlation.</strong> Covariance measures whether deviations from each mean tend to align. Pearson’s <em>r</em> rescales covariance by the standard deviations so the result is unitless and bounded ([-1, 1]).</li>
<li><strong>Interpreting <em>r</em>.</strong> Sign indicates direction; magnitude indicates strength of a <em>linear</em> relationship. <em>r</em> near 0 can still hide a strong <em>nonlinear</em> pattern.</li>
<li><strong>Regression link.</strong> The best-fit line summarizes the average relationship; residuals are the vertical gaps between data and the line. The line is chosen to minimize the <strong>sum of squared residuals</strong>.</li>
<li><strong>Chance alone can manufacture a correlation.</strong> Small samples can produce large |<em>r</em>| by accident, and larger samples shrink the “chance window” toward 0. Always report <em>r</em> alongside its sample size (<em>n</em>) and, when possible, a confidence interval. If a result hinges on a small sample, say so and treat the conclusion as tentative.</li>
<li><strong>Nonlinearity hides real effects.</strong> Curved relationships (e.g., too little or too much water harming plant growth) can yield <em>r</em> ≈ 0 even when the underlying effect is strong.</li>
<li><strong>Confounding.</strong> A third variable can create or inflate a correlation (e.g., sunlight affecting both watering patterns and plant growth). This is why the honest phrasing is “associated with,” not “caused by.”</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Anscombe1973" class="csl-entry" role="listitem">
Anscombe, F. J. 1973. <span>“Graphs in Statistical Analysis.”</span> <em>American Statistician</em> 27: 17–21.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-Data_Description.html" class="pagination-link" aria-label="Measuring and Describing Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-SamplesPopulations.html" class="pagination-link" aria-label="Probability and Distributions">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/02-Correlation.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>