<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>Answering questions with data - 3&nbsp; Correlation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-SamplesPopulations.html" rel="next">
<link href="./02-Describing_Data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 3&nbsp; Correlation">
<meta property="og:description" content="">
<meta property="og:image" content="03-Correlation_files/figure-html/fig-3scatter1-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 3&nbsp; Correlation">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-Correlation.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-MixedANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Libraries (top)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#if-something-caused-something-else-to-change-what-would-that-look-like" id="toc-if-something-caused-something-else-to-change-what-would-that-look-like" class="nav-link active" data-scroll-target="#if-something-caused-something-else-to-change-what-would-that-look-like"><span class="header-section-number">3.1</span> If something caused something else to change, what would that look like?</a>
  <ul class="collapse">
  <li><a href="#more-chocolate-more-happiness" id="toc-more-chocolate-more-happiness" class="nav-link" data-scroll-target="#more-chocolate-more-happiness"><span class="header-section-number">3.1.1</span> More Chocolate = More Happiness?</a></li>
  <li><a href="#scatter-plots" id="toc-scatter-plots" class="nav-link" data-scroll-target="#scatter-plots"><span class="header-section-number">3.1.2</span> Scatter plots</a></li>
  <li><a href="#positive-negative-and-no-correlation" id="toc-positive-negative-and-no-correlation" class="nav-link" data-scroll-target="#positive-negative-and-no-correlation"><span class="header-section-number">3.1.3</span> Positive, Negative, and No-Correlation</a></li>
  </ul></li>
  <li><a href="#covariance" id="toc-covariance" class="nav-link" data-scroll-target="#covariance"><span class="header-section-number">3.2</span> Covariance</a>
  <ul class="collapse">
  <li><a href="#turning-the-numbers-into-a-measure-of-covariance" id="toc-turning-the-numbers-into-a-measure-of-covariance" class="nav-link" data-scroll-target="#turning-the-numbers-into-a-measure-of-covariance"><span class="header-section-number">3.2.1</span> Turning the numbers into a measure of Covariance</a></li>
  <li><a href="#covariance-the-measure" id="toc-covariance-the-measure" class="nav-link" data-scroll-target="#covariance-the-measure"><span class="header-section-number">3.2.2</span> Covariance, the measure</a></li>
  <li><a href="#pearsons-r" id="toc-pearsons-r" class="nav-link" data-scroll-target="#pearsons-r"><span class="header-section-number">3.2.3</span> Pearson’s r</a></li>
  </ul></li>
  <li><a href="#regression-a-mini-intro" id="toc-regression-a-mini-intro" class="nav-link" data-scroll-target="#regression-a-mini-intro"><span class="header-section-number">3.3</span> Regression: A mini intro</a>
  <ul class="collapse">
  <li><a href="#the-best-fit-line" id="toc-the-best-fit-line" class="nav-link" data-scroll-target="#the-best-fit-line"><span class="header-section-number">3.3.1</span> The best fit line</a></li>
  <li><a href="#computing-the-best-fit-line" id="toc-computing-the-best-fit-line" class="nav-link" data-scroll-target="#computing-the-best-fit-line"><span class="header-section-number">3.3.2</span> Computing the best fit line</a></li>
  </ul></li>
  <li><a href="#interpreting-correlations-why-caution-is-warranted" id="toc-interpreting-correlations-why-caution-is-warranted" class="nav-link" data-scroll-target="#interpreting-correlations-why-caution-is-warranted"><span class="header-section-number">3.4</span> Interpreting Correlations: why caution is warranted</a>
  <ul class="collapse">
  <li><a href="#spurious-correlation-chance-alone-can-look-convincing" id="toc-spurious-correlation-chance-alone-can-look-convincing" class="nav-link" data-scroll-target="#spurious-correlation-chance-alone-can-look-convincing"><span class="header-section-number">3.4.1</span> Spurious correlation: chance alone can look convincing</a></li>
  <li><a href="#sample-size-and-stability" id="toc-sample-size-and-stability" class="nav-link" data-scroll-target="#sample-size-and-stability"><span class="header-section-number">3.4.2</span> Sample size and stability</a></li>
  <li><a href="#nonlinearity-when-r-misses-real-relationships" id="toc-nonlinearity-when-r-misses-real-relationships" class="nav-link" data-scroll-target="#nonlinearity-when-r-misses-real-relationships"><span class="header-section-number">3.4.3</span> Nonlinearity: when r misses real relationships</a></li>
  <li><a href="#confounding-variables-third-variable-problem" id="toc-confounding-variables-third-variable-problem" class="nav-link" data-scroll-target="#confounding-variables-third-variable-problem"><span class="header-section-number">3.4.4</span> Confounding variables (third-variable problem)</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">3.5</span> Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/03-Correlation.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="Correlation" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 14, 2025</p>
    </div>
  </div>
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>Correlation does not equal causation .*<br>
– Every Statistics Instructor Ever</p>
</blockquote>
<p>In the last chapter, we worked with data that felt overwhelming at first. We used plots and histograms to make the data visible, and descriptive statistics to summarize their central tendency and variability.</p>
<p>The reason we learned those tools is simple: we want to use data to answer questions. That theme runs through this course. As you read each section, keep asking yourself: how does this concept help me answer questions with data?</p>
<p>In Chapter 2, we imagined collecting self-reports of happiness from a group of people. The data were just numbers, but they already raised useful questions. How spread out are people’s happiness ratings? Do most people cluster near the middle, or are there groups of especially happy or unhappy individuals?</p>
<p>We also saw that numbers are imperfect reflections of experience. A rating from 0 to 100 is just one way of measuring happiness. It may not capture the full construct, but for now we will treat it as meaningful enough to work with.</p>
<p>This sets up the next step: moving from description to explanation. Rather than just asking how much happiness people report, we might ask what predicts differences in happiness? For example, does happiness vary with weather, income, or education? With social connections or cultural factors? Or with something lighter, like access to chocolate? Questions like these push us beyond describing data toward identifying relationships — the core of correlation analysis.</p>
<section id="if-something-caused-something-else-to-change-what-would-that-look-like" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="if-something-caused-something-else-to-change-what-would-that-look-like"><span class="header-section-number">3.1</span> If something caused something else to change, what would that look like?</h2>
<p>To use data for explanation, we need tools for recognizing when two things move together. Sometimes that reflects a real cause-and-effect relationship, and sometimes it doesn’t. The challenge is learning to tell the difference. In this chapter we’ll build intuition for what data look like when two variables are unrelated, when they move together, and when the pattern might mislead us.</p>
<section id="more-chocolate-more-happiness" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="more-chocolate-more-happiness"><span class="header-section-number">3.1.1</span> More Chocolate = More Happiness?</h3>
<p>Let’s imagine that a person’s supply of chocolate has a causal influence on their level of happiness. Let’s further imagine that the more chocolate you have the more happy you will be, and the less chocolate you have, the less happy you will be. Finally, because we suspect happiness is caused by lots of other things in a person’s life, we anticipate that the relationship between chocolate supply and happiness won’t be perfect. What do these assumptions mean for how the data should look?</p>
<p>Our first step is to collect some imaginary data from 100 people. We walk around and ask the first 100 people we meet to answer two questions:</p>
<ol type="1">
<li>how much chocolate do you have? and</li>
<li>how happy are you?</li>
</ol>
<p>For convenience, both the scales will go from 0 to 100. For the chocolate scale, 0 means no chocolate, 100 means lifetime supply of chocolate. Any other number is somewhere in between. For the happiness scale, 0 means no happiness, 100 means all of the happiness, and in between means some amount in between.</p>
<p>Here is some sample data from the first 10 imaginary subjects.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">subject</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">chocolate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">happiness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>We asked each subject two questions so there are two scores for each subject, one for their chocolate supply, and one for their level of happiness. You might already notice some relationships between amount of chocolate and level of happiness in the table. To make those relationships even more clear, let’s plot all of the data in a graph.</p>
</section>
<section id="scatter-plots" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="scatter-plots"><span class="header-section-number">3.1.2</span> Scatter plots</h3>
<p>When you have two measurements worth of data, you can always turn them into dots and plot them in a scatter plot. A scatter plot has a horizontal x-axis, and a vertical y-axis. You get to choose which measurement goes on which axis. Let’s put chocolate supply on the x-axis, and happiness level on the y-axis. <a href="#fig-3scatter1">Figure&nbsp;<span>3.1</span></a> shows 100 dots. Each dot is for one subject and represents both their happiness level and their chocolate supply.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3scatter1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3scatter1-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.1: Imaginary data showing a positive correlation between amount of chocolate and amount happiness</figcaption>
</figure>
</div>
</div>
</div>
<p>Each dot has two coordinates, an x-coordinate for chocolate, and a y-coordinate for happiness. Looking at the <strong>scatter plot</strong>, we can see that the dots show a pattern. People with less chocolate tend to report lower happiness, while those with more chocolate tend to report higher happiness. It looks like the more chocolate you have the happier you will be, and vice-versa. This kind of relationship is called a <strong>positive correlation</strong>.</p>
</section>
<section id="positive-negative-and-no-correlation" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="positive-negative-and-no-correlation"><span class="header-section-number">3.1.3</span> Positive, Negative, and No-Correlation</h3>
<p>Let’s imagine some more data. What do you imagine the scatter plot would look like if the relationship was reversed, and larger chocolate supplies decreased happiness? Or, what if there’s no relationship, and the amount of chocolate that you have doesn’t do anything to your happiness? take a look at <a href="#fig-3posnegrand">Figure&nbsp;<span>3.2</span></a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3posnegrand" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3posnegrand-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.2: Three scatterplots showing negative, positive, and zero correlation</figcaption>
</figure>
</div>
</div>
</div>
<p>The first panel shows a <strong>negative correlation</strong>. Happiness goes down as chocolate supply increases. Negative correlation occurs when one thing goes up and the other thing goes down; or, when more of X is less of Y, and vice-versa. The second panel shows a <strong>positive correlation</strong>. Happiness goes up as chocolate as chocolate supply increases. Positive correlation occurs when both things go up together, and go down together: more of X is more of Y, and vice-versa. The third panel shows <strong>no correlation</strong>. Here, there doesn’t appear to be any obvious relationship between chocolate supply and happiness.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Always plot first.</strong> If the scatter shows a U-shape or other curve, a single straight-line correlation will mislead. Fit a curved model (e.g., add a quadratic term) or transform variables instead of reporting <em>r</em> alone.</p>
</div>
</div>
<p>Zero correlation occurs when one thing is not related in any way to another things: changes in X do not relate to any changes in Y, and vice-versa.</p>
<p>You’ve examined your scatter plots, and now you might be wondering how to quantify what you see. We’ve already covered how to generate descriptive statistics for individual variables through means, standard deviations, etc. But what if you want to summarize how two variables move together in a single descriptive statistic? The path to that statistic (Pearson’s r) starts with understanding covariance.</p>
</section>
</section>
<section id="covariance" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="covariance"><span class="header-section-number">3.2</span> Covariance</h2>
<p>Let’s revisit <strong>variance</strong>. For one variable, variance summarizes how much values differ from their mean. <strong>Covariance</strong> extends this to two variables: it tells us whether being above the mean on <span class="math inline">\(X\)</span> tends to come with being above the mean on <span class="math inline">\(Y\)</span> (positive), below the mean on <span class="math inline">\(Y\)</span> (negative), or neither (near zero).</p>
<p>In our chocolate–happiness example, the scatter plot suggested that higher chocolate tends to come with higher happiness. That means the deviations from each mean often have the same sign, so their products are mostly positive: evidence of <em>positive</em> covariance. Put simply, the two variables <strong>vary together</strong>.</p>
<p>Covariance is important because it underlies correlation, regression, and many other statistical tools. It can feel abstract at first. Keep the core idea in mind: look at how each variable’s deviations from its mean behave together. If both are above or below their means at the same time, the covariance is positive. If one is above while the other is below, it’s negative. If there’s no consistent pairing, the covariance is near zero. With practice, this way of thinking becomes intuitive.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Covariance intuition.</strong> Think of a three-legged race. When partners move forward together, their steps align (positive covariance). When one moves forward as the other moves back, their steps oppose (negative covariance). If their steps are uncoordinated, there’s no consistent pattern (covariance near zero).</p>
</div>
</div>
<section id="turning-the-numbers-into-a-measure-of-covariance" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="turning-the-numbers-into-a-measure-of-covariance"><span class="header-section-number">3.2.1</span> Turning the numbers into a measure of Covariance</h3>
<p>If Covariance is just another word for correlation or relationship between two measures,then, we need some way to measure that. Consider our chocolate and happiness scores.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">subject</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">chocolate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">happiness</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Chocolate_X_Happiness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">35</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">63</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">42</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">44</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">218</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">21.8</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>We’ve added a new column called <code>Chocolate_X_Happiness</code>, which is simply each person’s chocolate score multiplied by their happiness score. Why multiply? Because the products reveal how the two values move together.</p>
<ul>
<li>Small × small → small product</li>
<li>Large × large → large product</li>
<li>Small × large → product in between</li>
</ul>
<p>Now extend this idea from pairs to the whole dataset. If chocolate and happiness rise together (both above average at the same time), the summed products will be large. If one tends to rise while the other falls, the summed products will shrink. This is the basic logic behind <strong>covariance</strong>.</p>
<p>Suppose we have two variables, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> go up together (both small at the same time, both large at the same time), their products will also be large when summed across the dataset. If one goes up while the other goes down (large pairs with small), the summed products will be much smaller.</p>
<p>Here’s are two tables to illustrate:</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-bordered table-sm table-striped small" data-quarto-postprocess="true">
<caption>Aligned: sum = 385</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">X</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Y</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">XY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">64</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">81</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">385</td>
</tr>
</tbody>
</table>


</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-bordered table-sm table-striped small" data-quarto-postprocess="true">
<caption>Reversed: sum = 220</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">A</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">B</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">220</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</div>
<p><span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are perfectly aligned: <span class="math inline">\(1\)</span> with <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span> with <span class="math inline">\(2\)</span>, up to <span class="math inline">\(10\)</span> with <span class="math inline">\(10\)</span>. Their products add up to <strong>385</strong>, the <em>largest</em> possible sum.</p>
<p><span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are perfectly reversed: <span class="math inline">\(1\)</span> with <span class="math inline">\(10\)</span>, <span class="math inline">\(2\)</span> with <span class="math inline">\(9\)</span>, and so on. Their products add up to <strong>220</strong>, the <em>smallest</em> possible sum.</p>
<p>Any other pairing of 1–10 with 1–10 will fall between these two extremes. <a href="#fig-3simsum">Figure&nbsp;<span>3.3</span></a> shows the sums of products from 1000 random pairings. Every result falls between 220 (perfect negative alignment) and 385 (perfect positive alignment).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3simsum" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3simsum-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.3: Simulated sums of products showing the kinds of values than can be produced by randomly ordering the numbers in X and Y.</figcaption>
</figure>
</div>
</div>
</div>
<p>So what does this mean? The <strong>sum of the products</strong> tells us about the direction of the relationship:</p>
<ul>
<li>Close to 385 → strong positive relationship.</li>
<li>Close to 220 → strong negative relationship.</li>
<li>Near the middle → little or no relationship.</li>
</ul>
<p>This is the foundation of <em>covariance</em>: products of paired values reveal whether two variables rise together, fall together, or move in opposite directions.</p>
<p><strong>Takeaway:</strong></p>
<ul>
<li>Positive correlation → large values in <span class="math inline">\(X\)</span> pair with large values in <span class="math inline">\(Y\)</span> → sum of products near the maximum.</li>
<li>Negative correlation → large values in <span class="math inline">\(X\)</span> pair with small values in <span class="math inline">\(Y\)</span> → sum near the minimum.</li>
<li>No correlation → pairings are random → sum lands in the middle.</li>
</ul>
</section>
<section id="covariance-the-measure" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="covariance-the-measure"><span class="header-section-number">3.2.2</span> Covariance, the measure</h3>
<p>Earlier we saw that multiplying values from two variables can highlight how they vary together: large-with-large and small-with-small pairs push the product up, while mixed pairs keep it lower. That intuition is useful, but in statistics we define <strong>covariance</strong> more precisely.</p>
<p>Instead of multiplying raw values of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, we multiply their <em>deviations from the mean</em>. This centers each variable, so the product reflects how the two variables co-vary around their averages:</p>
<p><span class="math inline">\(cov(X,Y) = \frac{\sum_{i}^{n}(x_{i}-\bar{X})(y_{i}-\bar{Y})}{N}\)</span></p>
<p>In practice, the steps are straightforward: subtract the mean of <span class="math inline">\(X\)</span> from each <span class="math inline">\(x_i\)</span>, subtract the mean of <span class="math inline">\(Y\)</span> from each <span class="math inline">\(y_i\)</span>, multiply the deviations, and then average those products. A positive covariance means the two variables tend to move together (above or below their means at the same time). A negative covariance means they move in opposite directions. A covariance near zero suggests no consistent relationship.</p>
<p>The following table shows this process:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">subject</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">chocolate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">happiness</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">C_d</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">H_d</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Cd_x_Hd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">-3.4</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">10.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-2.4</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-2.4</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">-0.4</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">-1.4</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">-0.4</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">2.6</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">2.6</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">2.6</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">2.6</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">44</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">42</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">4.4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">4.2</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Deviations from the mean for chocolate (column <code>C_d</code>), deviations from the mean for happiness (column <code>H_d</code>), and their products. The mean of those products (in the bottom right corner of the table) is the official <strong>covariance</strong>.</p>
<p>Covariance is a powerful idea, but it has a major drawback: its magnitude is hard to interpret. Just as variance is tied to squared units, covariance is tied to the scales of both variables. Is our covariance of 3.22 large? What if it’s 100? The raw number doesn’t tell us. All we can tell is its sign (positive or negative), not its size, which means we can’t say how strong the correlation is. To compare strength across variables with different units or scales, we need to normalize covariance, which leads to Pearson’s <span class="math inline">\(r\)</span>.</p>
</section>
<section id="pearsons-r" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="pearsons-r"><span class="header-section-number">3.2.3</span> Pearson’s r</h3>
<p>We often want a relationship measure that is <strong>directional</strong>, <strong>unitless</strong>, and <strong>bounded</strong>. <strong>Pearson’s</strong> <span class="math inline">\(r\)</span> does exactly this by rescaling covariance to lie between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>:</p>
<ul>
<li><span class="math inline">\(r=1\)</span>: perfect positive linear relationship</li>
<li><span class="math inline">\(r=0\)</span>: no linear relationship</li>
<li><span class="math inline">\(r=-1\)</span>: perfect negative linear relationship</li>
</ul>
<p>Values closer to <span class="math inline">\(\pm1\)</span> indicate stronger linear association; values near <span class="math inline">\(0\)</span> indicate weak or no linear association.</p>
<p>Let’s take a look at a formula for Pearson’s <span class="math inline">\(r\)</span>:</p>
<p><span class="math inline">\(r = \frac{cov(X,Y)}{\sigma_{X}\sigma_{Y}} = \frac{cov(X,Y)}{SD_{X}SD_{Y}}\)</span></p>
<p>In this forumal we see the symbol <span class="math inline">\(\sigma\)</span>, which indicates the standard deviation (SD). In words, <span class="math inline">\(r\)</span> is the Covariance of X and Y divided by the product of their standard deviations. Dividing by the standard deviations <strong>normalizes</strong> the Covariance, constraining <span class="math inline">\(r\)</span> to fall between between -1 to 1. This makes correlation values comparable across variables measured in different units or on different scales.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Computing <em>r</em>.</strong> You’ll see algebraically equivalent formulas for Pearson’s <em>r</em>. They produce the same result; we’ll typically rely on software and focus on interpretation.</p>
</div>
</div>
<div class="{callout-note}">
<p>There are several equivalent formulas for computing Pearson’s <span class="math inline">\(r\)</span>. Some are written to simplify hand calculations, others are more compact algebraically. They all yield the same result. Since we rely on software for calculations, our focus will be on what <span class="math inline">\(r\)</span> means and how to interpret it, rather than practicing manual computation. You’ll see how to run the calculation in R during lab.</p>
</div>
<p>Does Pearson’s <span class="math inline">\(r\)</span> really stay between -1 and 1 no matter what? It’s true, take a look at the following simulation. Here I randomly ordered the numbers 1 to 10 for an X measure, and did the same for a Y measure. Then, I computed Pearson’s <span class="math inline">\(r\)</span>, and repeated this process 1000 times. As you can see from <a href="#fig-3onethousandr">Figure&nbsp;<span>3.4</span></a> all of the dots are between -1 and 1.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3onethousandr" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3onethousandr-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.4: A simulation of of correlations. Each dot represents the r-value for the correlation between an X and Y variable that each contain the numbers 1 to 10 in random orders. The figure illustrates that many r-values can be obtained by this random process</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="regression-a-mini-intro" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="regression-a-mini-intro"><span class="header-section-number">3.3</span> Regression: A mini intro</h2>
<p>We’re going to spend the next little bit adding one more thing to our understanding of correlation. It’s called <strong>linear regression</strong>. Just an introduction to the basic concepts.</p>
<p>First, let’s look at a linear regression. This way we can see what we’re trying to learn about. <a href="#fig-3regression">Figure&nbsp;<span>3.5</span></a> shows the same scatter plots as before with something new: lines!</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3regression" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3regression-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.5: Three scatterplots showing negative, positive, and a random correlation (where the r-value is expected to be 0), along with the best fit regression line</figcaption>
</figure>
</div>
</div>
</div>
<section id="the-best-fit-line" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="the-best-fit-line"><span class="header-section-number">3.3.1</span> The best fit line</h3>
<p>Notice the blue lines in these panels. Each is a <strong>best fit</strong> line: the single straight line that best summarizes the overall pattern of dots.</p>
<p>With one variable, we use hte mean to describe central tendency in one dimension. With two variables plotted together, we need a two-dimensional equivalent. A line serves that purpose, capturing the average relationship across the could of points.</p>
<p>Of course, many possible lines could be drawn. Most would miss the pattern. The useful lines would go through the data following the general shape of the dots. Which one is the best? How can we find out, and what do we mean by that? In short, the best fit line is the one that has the least error.</p>
<p>Check out this plot: a line runs through the dots, and short vertical lines drop from each dot to the line. These are <strong>residuals</strong>:the vertical differences between the observed data and the fitted line. Residuals show the error, or how far off the line’s prediction is for each point. Since not all dots fall exactly on the line, some error is inevitable. The best-fit line is the one that minimizes these errors overall.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3regressionResiduals" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3regressionResiduals-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.6: Black dots represent data points. The blue line is the best fit regression line. The white dots are repesent the predicted location of each black dot. The red lines show the error between each black dot and the regression line. The blue line is the best fit line because it minimizes the error shown by the red lines.R code for residual visualziation adapted from Simon Jackson: <a href="https://drsimonj.svbtle.com/visualising-residuals" class="uri">https://drsimonj.svbtle.com/visualising-residuals</a></figcaption>
</figure>
</div>
</div>
</div>
<p>There’s a lot going on in <a href="#fig-3regressionResiduals">Figure&nbsp;<span>3.6</span></a>. his is a scatter plot of two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Each black dot represents the observed data. The blue line is the regression line, and the white dots show the predicted values from that line. The red lines are <strong>residuals</strong>: they drop vertically from each observed value to its predicted value on the line. Because most of the black dots are not exactly on the line, each residual shows how far the prediction differs from the observed value.</p>
<p>The key point is that the regression line is chosen to minimize the total size of these residuals. In practice, we compute the <strong>sum of squared deviations</strong>: squaring each residual, then adding them together. The blue line is the one that produces the smallest possible total squared error. Any other line would yield a larger total error.</p>
<p><a href="#fig-3regressionGIF">Figure&nbsp;<span>3.7</span></a> is an animation to see this in action. The animations compares the best fit line in blue, to some other possible lines in black. The black line moves up and down. The red lines show the error between the black line and the data points. As the black line moves toward the best fit line, the total error, depicted visually by the grey area shrinks to its minimum value. The total error expands as the black line moves away from the best fit line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3regressionGIF" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/regression-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.7: The blue line is the best fit regression line explaining the co-variation among the black dots. The black line moves up and down showing alternative lines that could be drawn. The red lines show the amount of error between each data point and the black line. The total amount of error is depicted by the shaded grey area. The size of the grey area expands as the black line moves away from the best fit line, and shrinks to a minimum as the black line moves toward the best fit line.</figcaption>
</figure>
</div>
</div>
</div>
<p>Whenever the black line does not overlap with the blue line, it fits the data less well. The blue regression line is the one that minimizes the overall error — not too high, not too low, but the line with the least total deviation.</p>
<p><a href="#fig-3minimizeSS">Figure&nbsp;<span>3.8</span></a> shows how the sum of squared deviations (the sum of the squared lengths of the red lines) behaves as we move the line up and down. What’s going on here is that we are computing a measure of the total error as the black line moves through the best fit line. This represents the sum of the squared deviations. In other words, we square the length of each red line from the above animation, then we add up all of the squared red lines, and get the total error (the total sum of the squared deviations). The graph below shows what the total error looks like as the black line approaches then moves away from the best fit line. Notice, the dots in this graph start high on the left side, then they swoop down to a minimum at the bottom middle of the graph. When they reach their minimum point, we have found a line that minimizes the total error. This is the best fit regression line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3minimizeSS" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3minimizeSS-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.8: A plot of the sum of the squared deviations for different lines moving up and down, through the best fit line. The best fit line occurs at the position that minimizes the sum of the squared deviations.</figcaption>
</figure>
</div>
</div>
</div>
<p>OK, so we haven’t talked about the y-intercept yet. But, what this graph shows us is how the total error behaves as we move the line up and down. The y-intercept here is the thing we change that makes our line move up and down. As you can see the dots go up when we move the line down from 0 to -5, and the dots go up when we move the line up from 0 to +5. The best line, that minimizes the error occurs right in the middle, when we don’t move the blue regression line at all.</p>
</section>
<section id="computing-the-best-fit-line" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="computing-the-best-fit-line"><span class="header-section-number">3.3.2</span> Computing the best fit line</h3>
<p>How do we find the line that minimizes the sum of squared deviations? In principle, you could try many possible lines and compare their errors, but that’s not efficient. Instead, we use formulas (or, more realistically, software) to identify the line with the smallest total error.</p>
<p>Next we’ll look at the formulas for calculating the slope and intercept of a regression line, and work through one example by hand. Many statistical formulas were designed to simplify hand calculations before computers were common. Today we rely on software, but working through examples by hand helps illustrate the logic behind the formulas.</p>
<p>Here are two formulas we can use to calculate the slope and the intercept, straight from the data. We won’t go into why these formulas do what they do. These ones are for “easy” calculation.</p>
<p><span class="math inline">\(intercept = b = \frac{\sum{y}\sum{x^2}-\sum{x}\sum{xy}}{n\sum{x^2}-(\sum{x})^2}\)</span></p>
<p><span class="math inline">\(slope = m = \frac{n\sum{xy}-\sum{x}\sum{y}}{n\sum{x^2}-(\sum{x})^2}\)</span></p>
<p>In these formulas, the <span class="math inline">\(x\)</span> and the <span class="math inline">\(y\)</span> refer to the individual scores. Here’s a table showing you how everything fits together.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">x</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">y</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">x_squared</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">y_squared</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">xy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">81</td>
<td style="text-align: left;">72</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">34</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">200</td>
<td style="text-align: left;">275</td>
<td style="text-align: left;">231</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>We see 7 sets of scores for the x and y variable. We calculated <span class="math inline">\(x^2\)</span> by squaring each value of x, and putting it in a column. We calculated <span class="math inline">\(y^2\)</span> by squaring each value of y, and putting it in a column. Then we calculated <span class="math inline">\(xy\)</span>, by multiplying each <span class="math inline">\(x\)</span> score with each <span class="math inline">\(y\)</span> score, and put that in a column. Then we added all the columns up, and put the sums at the bottom. These are all the number we need for the formulas to find the best fit line. Here’s what the formulas look like when we put numbers in them:</p>
<p><span class="math inline">\(intercept = b = \frac{\sum{y}\sum{x^2}-\sum{x}\sum{xy}}{n\sum{x^2}-(\sum{x})^2} = \frac{39 * 200 - 34*231}{7*200-34^2} = -.221\)</span></p>
<p><span class="math inline">\(slope = m = \frac{n\sum{xy}-\sum{x}\sum{y}}{n\sum{x^2}-(\sum{x})^2} = \frac{7*231-34*39}{7*275-34^2} = 1.19\)</span></p>
<p>Great, now we can check our work, let’s plot the scores in a scatter plot and draw a line through it with slope = 1.19, and a y-intercept of -.221. As shown in <a href="#fig-3corwithLine">Figure&nbsp;<span>3.9</span></a>, the line should go through the middle of the dots.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3corwithLine" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3corwithLine-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.9: An example regression line with confidence bands going through a few data points in a scatterplot</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="interpreting-correlations-why-caution-is-warranted" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="interpreting-correlations-why-caution-is-warranted"><span class="header-section-number">3.4</span> Interpreting Correlations: why caution is warranted</h2>
<p>You’ve heard the warning: <strong>correlation does not equal causation</strong>. But what does a correlation really tell us, and what can it mislead us about? Interpreting correlations requires care, because the same number can arise from very different situations: random chance, confounding influences, or nonlinear patterns. In this section, we’ll look at why correlations can be unreliable and how to recognize their limits.</p>
<section id="spurious-correlation-chance-alone-can-look-convincing" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="spurious-correlation-chance-alone-can-look-convincing"><span class="header-section-number">3.4.1</span> Spurious correlation: chance alone can look convincing</h3>
<p>Another very important aspect of correlations is the fact that they can be produced by random chance. This means that you can find a positive or negative correlation between two measures, even when they have absolutely nothing to do with one another. You might have hoped to find zero correlation when two measures are totally unrelated to each other. Although this certainly happens, unrelated measures can accidentally produce <strong>spurious</strong> correlations, just by chance alone.</p>
<p>Let’s demonstrate how correlations can appear by chance when there is no causal connection between two measures. Imagine two independent participants, one at the North Pole and one at the South Pole. Each has a lottery machine containing balls numbered 1 through 10. With replacement, each participant randomly draws 10 balls and records the numbers. Because the draws occur independently and half a world apart, there is no possible causal link between the two sets of numbers. The outcomes are determined by chance alone.</p>
<p>Here is what the numbers on each ball could look like for each participant:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Ball</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">North_pole</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">South_pole</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>In this one case, if we computed Pearson’s <span class="math inline">\(r\)</span>, we would find that <span class="math inline">\(r =\)</span> -0.1318786. But, we already know that this value does not tell us anything about the relationship between the balls chosen in the north and south pole. We know that relationship should be completely random, because that is how we set up the game.</p>
<p>The better question here is to ask what can random chance do? For example, if we ran our game over and over again thousands of times, each time choosing new balls, and each time computing the correlation, what would we find?First, we will find fluctuation. The r value will sometimes be positive, sometimes be negative, sometimes be big and sometimes be small. Second, we will see what the fluctuation looks like. This will give us a window into the kinds of correlations that chance alone can produce. Let’s see what happens.</p>
<section id="monte-carlo-what-chance-produces" class="level4" data-number="3.4.1.1">
<h4 data-number="3.4.1.1" class="anchored" data-anchor-id="monte-carlo-what-chance-produces"><span class="header-section-number">3.4.1.1</span> Monte-carlo: what chance produces</h4>
<p>We can use a computer to repeat the lottery game as many times as we like. This process, repeated random sampling to explore possible outcomes, is called a <strong>Monte Carlo simulation</strong>.</p>
<p>I’ve coded a loop to run the game 1,000 times. Each time, both the North Pole and South Pole participants generate 10 random numbers. We then compute the correlation between their two sets. The result is 1,000 different values of Pearson’s <span class="math inline">\(r\)</span>, each produced under conditions where we know no real relationship exists.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3anotherthousand" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3anotherthousand-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.10: Another figure showing a range of r-values that can be obtained by chance.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-3anotherthousand">Figure&nbsp;<span>3.10</span></a> shows the outcome. Each dot is one simulated correlation. All of them fall between –1 and 1, but the values scatter widely: sometimes strongly positive, sometimes strongly negative, often near zero. The point is that <strong>chance alone can generate correlations of any size</strong>. Finding a correlation in your data does not by itself guarantee a meaningful relationship.</p>
<p>To visualize this process more concretely, we can animate a single run. In <a href="#fig-3randcor10gif">Figure&nbsp;<span>3.11</span></a>, each frame shows two sets of 10 random values plotted against each other, along with the fitted regression line. Because the data are random, we expect no consistent pattern. Yet across repetitions, the line sometimes slopes upward, sometimes downward, and occasionally appears flat. This is what spurious correlation looks like.</p>
<p>The animation makes clear how quickly random samples can mimic each of these patterns.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3randcor10gif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/corUnifn10-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.11: Completely random data points drawn from a uniform distribution with a small sampl-size of 10. The blue line twirls around sometimes showing large correlations that are produced by chance</figcaption>
</figure>
</div>
</div>
</div>
<p>You might find this unsettling: if two random variables with no relationship can still produce correlations, how can we trust any correlation at all? This raises a key question: <strong>how do we know whether the correlation we observed is meaningful or just chance?</strong> One way forward is to look not at a single outcome, but at the distribution of outcomes produced by chance. By simulating 1,000 random correlations and plotting them in a histogram, we can see which values occur frequently and which are rare.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3histrandcor" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3histrandcor-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.12: A histogram showing the frequency distribution of r-values for completely random values between an X and Y variable (sample-size=10). A rull range of r-values can be obtained by chance alone. Larger r-values are less common than smaller r-values</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-3histrandcor">Figure&nbsp;<span>3.12</span></a> shows that most chance correlations cluster near zero. Moderate correlations (around <span class="math inline">\(\pm 0.5\)</span>) occur less frequently, and near-perfect correlations (<span class="math inline">\(\pm 0.95\)</span>) are almost absent. This distribution defines a “window of chance.” When we compute a correlation in real data, we can ask: is our observed <span class="math inline">\(r\)</span> consistent with what chance alone could plausibly generate?</p>
<p>or example, if you observed <span class="math inline">\(r=0.1\)</span>, the histogram shows that such values are common in random data, so chance could easily explain it. An observed <span class="math inline">\(r=0.5\)</span> is less common but still possible by chance. An observed <span class="math inline">\(r=0.95\)</span>, however, falls outside what chance typically produces, suggesting that something more systematic is driving the relationship.</p>
</section>
</section>
<section id="sample-size-and-stability" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="sample-size-and-stability"><span class="header-section-number">3.4.2</span> Sample size and stability</h3>
<p>So far, our lottery game has used 10 draws per participant. With such small samples, chance produces a wide range of correlations: sometimes strongly positive, sometimes strongly negative. But what happens if we increase the sample size?</p>
<p>We can repeat the simulation under four conditions: each participant draws 10, 50, 100, or 1000 numbers. In each case, we run 1000 simulations and record the correlation values.</p>
<p><a href="#fig-3corrandN">Figure&nbsp;<span>3.13</span></a> shows the resulting four histograms of Pearson <span class="math inline">\(r\)</span> values.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3corrandN" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3corrandN-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.13: Four histograms showing the frequency distributions of r-values between completely random X and Y variables as a function of sample-size. The width of the distributions shrink as sample-size increases. Smaller sample-sizes are more likely to produce a wider range of r-values by chance. Larger sample-sizes always produce a narrow range of small r-values</figcaption>
</figure>
</div>
</div>
</div>
<p>The pattern is clear:</p>
<ul>
<li>With <strong>n=10</strong>, correlations spread widely across the range –1 to 1. Chance alone frequently produces values that would look “strong” in real data.</li>
<li>With <strong>n=50 or 100</strong>, the spread narrows, but moderate correlations still appear.</li>
<li>With <strong>n=1000</strong>, almost all simulated correlations fall close to zero.</li>
</ul>
<p>The takeaway is that <strong>larger samples reduce the influence of chance</strong>. Small samples are highly unstable, making it difficult to distinguish signal from noise. As sample size increases, the distribution of chance correlations collapses toward zero, so observing a large <span class="math inline">\(r\)</span> becomes far less likely under randomness alone.</p>
<p>This illustrates why researchers place so much emphasis on collecting sufficient data. With too few observations, even strong-looking correlations may be spurious. With larger samples, a correlation of the same size is much harder to attribute to chance, and therefore more likely to reflect a real underlying relationship.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Experimental design tip: sample size.</strong> Bigger <em>n</em> narrows the “window of chance.” If you expect a modest linear effect (e.g., |r| ≈ 0.2–0.3), plan for larger samples so random swings are less likely to mimic or mask the effect.</p>
</div>
</div>
<section id="visualizing-the-effect-of-sample-size" class="level4" data-number="3.4.2.1">
<h4 data-number="3.4.2.1" class="anchored" data-anchor-id="visualizing-the-effect-of-sample-size"><span class="header-section-number">3.4.2.1</span> Visualizing the effect of sample size</h4>
<p>Animations make it easier to see how sample size influences the stability of correlation estimates. When the sample is very small, chance variation can create apparent patterns in any direction. As the sample size increases, those chance fluctuations diminish.</p>
<p><strong>When there is no true correlation</strong></p>
<p>In <a href="#fig-3corRandfour">Figure&nbsp;<span>3.14</span></a>, each panel shows two random variables sampled with no real relationship. The panels differ only in sample size: 10, 50, 100, or 1000 observations. Each frame of the animation re-samples the data, plots them, and fits a line.</p>
<p>With <span class="math inline">\(n=10\)</span>, the line swings dramatically from positive to negative slopes. At <span class="math inline">\(n=50\)</span> and <span class="math inline">\(n=100\)</span>, the line still shifts but is more restrained. At <span class="math inline">\(n=1000\)</span>, the line is consistently flat, as expected when no correlation exists.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3corRandfour" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/corUnifFourNs-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.14: Animation of how correlation behaves for completely random X and Y variables as a function of sample size. The best fit line is not very stable for small sample-sizes, but becomes more reliably flat as sample-size increases.</figcaption>
</figure>
</div>
</div>
</div>
<p>Which line should you trust? The line from the sample with 1000 observations is the most reliable. It stays nearly flat across repetitions, as we would expect when no true correlation exists. The line from a sample of only 10 observations swings wildly, sometimes positive, sometimes negative. The lesson is straightforward: claims about correlation are only as trustworthy as the sample size behind them. Small samples can produce misleading patterns by chance, while large samples rarely do.</p>
<p>We can also repeat this simulation with data drawn from a normal distribution rather than a uniform one. The result is the same: small samples fluctuate dramatically, but with large samples the estimated correlation stays close to zero. <a href="#fig-3normCorfour">Figure&nbsp;<span>3.15</span></a> illustrates this.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3normCorfour" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/corNormFourNs-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.15: Animation of correlation for random values sampled from a normal distribution, rather than a uniform distribution.</figcaption>
</figure>
</div>
</div>
</div>
<p>What do things look like when there actually is a correlation between variables?</p>
<p><strong>When there is a true correlation</strong></p>
<p>In <a href="#fig-3realcorFour">Figure&nbsp;<span>3.16</span></a>, the simulation is repeated with a real positive correlation built into the data. Again, we vary the sample size from 10 to 1000.</p>
<p>With <span class="math inline">\(n=10\)</span>, the regression line jumps around and occasionally even points downward, despite the underlying positive relationship. As the sample size grows, the line becomes more stable and consistently reflects the true positive slope. Sampling error still introduces some noise, but with larger samples the real correlation is much easier to detect.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3realcorFour" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/corRealgif-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.16: How correlation behaves as a function of sample-size when there is a true correlation between X and Y variables.</figcaption>
</figure>
</div>
</div>
</div>
<p>Both the histograms and the animations show that <strong>small samples make correlations unreliable, while larger samples are more likely to reveal the true pattern</strong>. Even when a real positive correlation exists, a small sample might miss it, or even suggest the opposite, simply due to chance. Because we usually only have one sample, we can never know for certain whether we were “lucky” or “unlucky.” The best protection is to collect more data: larger samples reduce the influence of chance and make genuine relationships easier to detect.</p>
</section>
</section>
<section id="nonlinearity-when-r-misses-real-relationships" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="nonlinearity-when-r-misses-real-relationships"><span class="header-section-number">3.4.3</span> Nonlinearity: when r misses real relationships</h3>
<p>Consider, a snake plant. Like most plants, snake plants need water to stay alive. But, they also need <em>the right amount</em> of water. Imagine we grow 1000 snake plants, each receiving a different amount of water per day. The amount of water ranges from <em>no water</em> to <em>extreme overwatering</em> (say 1000 teaspoons of water per day). We then measure weekly snake plant growth. Water is clearly causally related to plant growth, so we expect to see a correlation.</p>
<p>What would the scatter plot look like?</p>
<p>Plants given no water at all will eventually die, showing little or no weekly growth. With only a few teaspoons per day, plants may survive but grow only modestly. In a scatter plot, those cases would appear near the bottom left (low water, low growth) and rise upward as water increases. Growth continues to improve until a threshold is reached—beyond that point, excess water harms the plants. Severely overwatered plants also fail to grow and eventually die, just as those given no water do.</p>
<p>The scatter plot would form an inverted U or V: as water increases, growth rises to a peak and then declines with overwatering. A relationship like this can produce a Pearson’s <span class="math inline">\(r\)</span> close to zero, even though water clearly affects growth. <a href="#fig-3snakeplant">Figure&nbsp;<span>3.17</span></a> illustrates this pattern.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3snakeplant" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="03-Correlation_files/figure-html/fig-3snakeplant-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3.17: Illustration of a possible relationship between amount of water and snake plant growth. Growth goes up with water, but eventually goes back down as too much water makes snake plants die.</figcaption>
</figure>
</div>
</div>
</div>
<p>There is clearly a relationship between watering and snake plant growth. But, the correlation isn’t in one direction. As a result, when we compute the correlation in terms of Pearson’s r, we get a value very close to zero, suggesting no relationship.</p>
<div class="cell">
<pre><code>#&gt; [1] -0.02108469</code></pre>
</div>
<p>What this really means is there is no relationship that can be described by a <em>single straight line</em>. When we need lines or curves going in more than one direction, we have a nonlinear relationship.</p>
<p>This example shows why correlations can be tricky to interpret. Water is clearly necessary for plant growth, yet the overall correlation can be misleading. The first half of the data suggests a positive relationship, the second half a negative one, and the full dataset little or none. Even with a real causal link, a single correlation coefficient may fail to capture it.</p>
<blockquote class="blockquote">
<p>Pro Tip: This is one reason why plotting your data is so important. If you see an upside U shape pattern, then a correlation analysis is probably not the best analysis for your data.</p>
</blockquote>
</section>
<section id="confounding-variables-third-variable-problem" class="level3" data-number="3.4.4">
<h3 data-number="3.4.4" class="anchored" data-anchor-id="confounding-variables-third-variable-problem"><span class="header-section-number">3.4.4</span> Confounding variables (third-variable problem)</h3>
<p>Correlations can arise because of a third variable—something not directly measured that influences both variables of interest. Returning to the snake plant example: imagine we measure water and plant growth, but ignore sunlight. If plants in sunnier windows both receive more water and grow faster, we might attribute the effect to water alone, when in fact sunlight is doing much of the work.</p>
<p>The same issue appears in human data. Suppose we find that income and happiness are positively correlated. Is money itself the cause? Possibly, but other factors – such as housing quality, healthcare access, or social opportunities – may be the true drivers. Income is correlated with these factors, which in turn influence happiness.</p>
</section>
</section>
<section id="summary" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="summary"><span class="header-section-number">3.5</span> Summary</h2>
<p><strong>Why it matters.</strong> Correlation is how we quantify whether two variables move together. It’s essential for describing patterns (e.g., temperature and canopy cover, chocolate and happiness) and for deciding whether a relationship is worth modeling or acting on.</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>Scatter first, always.</strong> A scatter plot shows direction (up, down, none), form (straight vs curved), and outliers.</li>
<li><strong>Covariance → correlation.</strong> Covariance measures whether deviations from each mean tend to align. Pearson’s <em>r</em> rescales covariance by the standard deviations so the result is unitless and bounded ([-1, 1]).</li>
<li><strong>Interpreting <em>r</em>.</strong> Sign indicates direction; magnitude indicates strength of a <em>linear</em> relationship. <em>r</em> near 0 can still hide a strong <em>nonlinear</em> pattern.</li>
<li><strong>Regression link.</strong> The best-fit line summarizes the average relationship; residuals are the vertical gaps between data and the line. The line is chosen to minimize the <strong>sum of squared residuals</strong>.</li>
</ul>
<p><strong>Common pitfalls</strong></p>
<ul>
<li><strong>Chance (spurious) correlations.</strong> Small samples can produce large |<em>r</em>| by accident. Larger samples shrink the “chance window” toward 0.</li>
<li><strong>Nonlinearity.</strong> Curved relationships (e.g., too little or too much water harming plant growth) can yield <em>r</em> ≈ 0 despite a real effect.</li>
<li><strong>Confounding.</strong> A third variable can create or inflate a correlation (e.g., sunlight affecting both watering patterns and plant growth).</li>
</ul>
<p><strong>Practice checklist</strong></p>
<ol type="1">
<li>Plot the scatter; look for linearness, curvature, and outliers.<br>
</li>
<li>Report <em>r</em> with <strong>sample size</strong> (<em>n</em>) and, when possible, a <strong>confidence interval</strong>.</li>
<li>Avoid causal language—say “associated with,” not “caused by.”<br>
</li>
<li>If the pattern is curved, don’t stop at <em>r</em>; fit a suitable model (e.g., add a quadratic term) or transform.<br>
</li>
<li>If results hinge on a small sample, say so and treat conclusions as tentative.</li>
</ol>
<p><strong>Takeaway.</strong> Correlation is a precise way to summarize linear association, but it’s only as trustworthy as your plot, your sample size, and your awareness of curvature and confounding. Plot first, quantify carefully, and interpret cautiously.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-Describing_Data.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-SamplesPopulations.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>