<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>Answering questions with data - 4&nbsp; Foundations for inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-Hypothesis_Testing.html" rel="next">
<link href="./03-SamplesPopulations.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 4&nbsp; Foundations for inference">
<meta property="og:description" content="">
<meta property="og:image" content="04-Foundation_Inference_files/figure-html/fig-5unifagain-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 4&nbsp; Foundations for inference">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-Foundation_Inference.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#brief-review-of-experiments" id="toc-brief-review-of-experiments" class="nav-link active" data-scroll-target="#brief-review-of-experiments"><span class="header-section-number">4.1</span> Brief review of Experiments</a></li>
  <li><a href="#the-data-came-from-a-distribution" id="toc-the-data-came-from-a-distribution" class="nav-link" data-scroll-target="#the-data-came-from-a-distribution"><span class="header-section-number">4.2</span> The data came from a distribution</a>
  <ul class="collapse">
  <li><a href="#uniform-distribution" id="toc-uniform-distribution" class="nav-link" data-scroll-target="#uniform-distribution"><span class="header-section-number">4.2.1</span> Uniform distribution</a></li>
  <li><a href="#not-all-samples-are-the-same-they-are-usually-quite-different" id="toc-not-all-samples-are-the-same-they-are-usually-quite-different" class="nav-link" data-scroll-target="#not-all-samples-are-the-same-they-are-usually-quite-different"><span class="header-section-number">4.2.2</span> Not all samples are the same, they are usually quite different</a></li>
  <li><a href="#large-samples-are-more-like-the-distribution-they-came-from" id="toc-large-samples-are-more-like-the-distribution-they-came-from" class="nav-link" data-scroll-target="#large-samples-are-more-like-the-distribution-they-came-from"><span class="header-section-number">4.2.3</span> Large samples are more like the distribution they came from</a></li>
  </ul></li>
  <li><a href="#is-there-a-difference" id="toc-is-there-a-difference" class="nav-link" data-scroll-target="#is-there-a-difference"><span class="header-section-number">4.3</span> Is there a difference?</a>
  <ul class="collapse">
  <li><a href="#chance-can-produce-differences" id="toc-chance-can-produce-differences" class="nav-link" data-scroll-target="#chance-can-produce-differences"><span class="header-section-number">4.3.1</span> Chance can produce differences</a></li>
  <li><a href="#differences-due-to-chance-can-be-simulated" id="toc-differences-due-to-chance-can-be-simulated" class="nav-link" data-scroll-target="#differences-due-to-chance-can-be-simulated"><span class="header-section-number">4.3.2</span> Differences due to chance can be simulated</a></li>
  </ul></li>
  <li><a href="#chance-makes-some-differences-more-likely-than-others" id="toc-chance-makes-some-differences-more-likely-than-others" class="nav-link" data-scroll-target="#chance-makes-some-differences-more-likely-than-others"><span class="header-section-number">4.4</span> Chance makes some differences more likely than others</a></li>
  <li><a href="#simulation-based-inference" id="toc-simulation-based-inference" class="nav-link" data-scroll-target="#simulation-based-inference"><span class="header-section-number">4.5</span> Simulation-Based Inference</a>
  <ul class="collapse">
  <li><a href="#intuitive-methods" id="toc-intuitive-methods" class="nav-link" data-scroll-target="#intuitive-methods"><span class="header-section-number">4.5.1</span> Intuitive methods</a></li>
  <li><a href="#part-1-frequency-based-intuition-about-occurrence" id="toc-part-1-frequency-based-intuition-about-occurrence" class="nav-link" data-scroll-target="#part-1-frequency-based-intuition-about-occurrence"><span class="header-section-number">4.5.2</span> Part 1: Frequency-based intuition about occurrence</a></li>
  <li><a href="#part-2-judgment-and-decision-making" id="toc-part-2-judgment-and-decision-making" class="nav-link" data-scroll-target="#part-2-judgment-and-decision-making"><span class="header-section-number">4.5.3</span> Part 2: Judgment and Decision-making</a></li>
  <li><a href="#part-3-study-design-and-sensitivity" id="toc-part-3-study-design-and-sensitivity" class="nav-link" data-scroll-target="#part-3-study-design-and-sensitivity"><span class="header-section-number">4.5.4</span> Part 3: Study Design and Sensitivity</a></li>
  <li><a href="#summary-of-simulation-based-inference" id="toc-summary-of-simulation-based-inference" class="nav-link" data-scroll-target="#summary-of-simulation-based-inference"><span class="header-section-number">4.5.5</span> Summary of Simulation-Based Inference</a></li>
  </ul></li>
  <li><a href="#the-randomization-test-permutation-test" id="toc-the-randomization-test-permutation-test" class="nav-link" data-scroll-target="#the-randomization-test-permutation-test"><span class="header-section-number">4.6</span> The randomization test (permutation test)</a>
  <ul class="collapse">
  <li><a href="#pretend-example-does-distance-from-a-highway-affect-no₂-levels" id="toc-pretend-example-does-distance-from-a-highway-affect-no₂-levels" class="nav-link" data-scroll-target="#pretend-example-does-distance-from-a-highway-affect-no₂-levels"><span class="header-section-number">4.6.1</span> Pretend example: does distance from a highway affect NO₂ levels?</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">4.7</span> Chapter Summary</a></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"><span class="header-section-number">4.8</span> Videos</a>
  <ul class="collapse">
  <li><a href="#null-and-alternate-hypotheses" id="toc-null-and-alternate-hypotheses" class="nav-link" data-scroll-target="#null-and-alternate-hypotheses"><span class="header-section-number">4.8.1</span> Null and Alternate Hypotheses</a></li>
  <li><a href="#types-of-errors" id="toc-types-of-errors" class="nav-link" data-scroll-target="#types-of-errors"><span class="header-section-number">4.8.2</span> Types of Errors</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/04-Foundation_Inference.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 29, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>Data and data sets are not objective; they are creations of human design. We give numbers their voice, draw inferences from them, and define their meaning through our interpretations.<br>
Katie Crawford</p>
</blockquote>
<p><strong>Inferential statistics</strong> is the branch of statistics concerned with drawing conclusions about populations or causal relationships from sample data. It provides the tools to answer questions like: did our manipulation actually cause a change, or could the pattern we observed have arisen by random chance alone?</p>
<p>This chapter builds the conceptual foundations for inference using simulation, no formulas yet. The goal is to make the underlying logic explicit and visible before it gets formalized in later chapters.</p>
<section id="brief-review-of-experiments" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="brief-review-of-experiments"><span class="header-section-number">4.1</span> Brief review of Experiments</h2>
<p>A controlled experiment is a structured method of data collection designed to support inferences about causality. Experiments involve deliberately manipulating one condition while holding others constant, then measuring the response.</p>
<p>Every experiment has two core components: the <strong>independent variable</strong>, the condition under experimental control, and the <strong>dependent variable</strong>, what is measured.</p>
<p>For example, a researcher studying the effects of wastewater discharge on stream health might compare dissolved oxygen (DO) levels at sites downstream of a discharge point against levels at unaffected reference sites, expecting DO to be lower downstream if the discharge is having an effect (wastewater typically consumes oxygen as it decomposes). Distance from discharge (affected vs.&nbsp;reference) is the independent variable; DO is the dependent variable.</p>
<p>Causal forces produce detectable change. If the discharge is truly reducing dissolved oxygen, then measurements from affected sites should differ systematically from measurements at reference sites. The experiment is designed to detect that change.</p>
<p>The central question becomes: how do we know if a measured difference between conditions reflects a real causal effect? Data always contain variability: measurements fluctuate even when nothing has changed. To decide whether a difference is real, we need tools that can distinguish meaningful change from background noise.</p>
</section>
<section id="the-data-came-from-a-distribution" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="the-data-came-from-a-distribution"><span class="header-section-number">4.2</span> The data came from a distribution</h2>
<p>Understanding where data come from is foundational to inference. This section returns to sampling and distributions, but now to ask what they reveal about the process that generated our data, not just to describe them.</p>
<p>A <strong>distribution</strong> specifies what numbers are likely to occur and how often. It sets the constraints on what we can expect to see when we take measurements.</p>
<section id="uniform-distribution" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="uniform-distribution"><span class="header-section-number">4.2.1</span> Uniform distribution</h3>
<p>As a reminder from last chapter, <a href="#fig-5unifagain">Figure&nbsp;<span>4.1</span></a> shows that the shape of a uniform distribution is completely flat.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5unifagain" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5unifagain-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.1: Uniform distribution showing that the numbers from 1 to 10 have an equal probability of being sampled</figcaption>
</figure>
</div>
</div>
</div>
<p>The y-axis shows probability (0 to 1) and the x-axis shows the values 1 through 10. The flat horizontal line indicates that every value from 1 to 10 has an equal probability of occurring: 1/10 = 0.1. This is the defining property of a uniform distribution: no value is more likely than any other.</p>
<p>Think of the uniform distribution as a number-generating process. If it generates numbers repeatedly, it produces each value with equal frequency: roughly 10% 1s, 10% 2s, and so on. Let’s sample 100 numbers from this distribution.</p>
<p>We used the uniform distribution to generate these numbers. Formally, this is called <strong>sampling</strong> from a <strong>distribution</strong>. Drawing a subset of observations from a larger process or population is sampling; if you could observe every possible value the process could produce, you would have the <strong>population</strong>. We will return to the distinction between samples and populations throughout the course.</p>
<p>Because we used the uniform distribution to create these numbers, we already know where they came from. But suppose someone handed you this same list without telling you its source: could you tell, just by looking, that it came from a uniform distribution? You’d check whether all the numbers occur with roughly equal frequency, since that’s what a uniform distribution predicts: if each number had the same chance of occurring, each should show up roughly the same number of times.</p>
<p>Putting the sample of 100 numbers into a histogram makes the counts easy to compare. If all values from 1 to 10 occur with equal frequency, each individual number should occur about 10 times. <a href="#fig-5histunif">Figure&nbsp;<span>4.2</span></a> shows the histogram:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5histunif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5histunif-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.2: Histogram of 100 numbers randomly sampled from the uniform distribution containing the integers from 1 to 10</figcaption>
</figure>
</div>
</div>
</div>
<p>As the histogram shows, not all numbers occurred exactly 10 times. The bars vary in height even though all values had equal probability. This is an illustration of <strong>sampling variability</strong>: random samples do not perfectly reproduce the distribution they came from. The discrepancy between what we observe and what the distribution predicts is called <strong>sampling error</strong>.</p>
</section>
<section id="not-all-samples-are-the-same-they-are-usually-quite-different" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="not-all-samples-are-the-same-they-are-usually-quite-different"><span class="header-section-number">4.2.2</span> Not all samples are the same, they are usually quite different</h3>
<p>Let’s look at sampling error more closely. We will sample 20 numbers from the uniform distribution. We should expect that each number between 1 and 10 occurs about two times each. As before, this expectation can be visualized in a histogram. To get a better sense of sampling error, let’s repeat the above process ten times. <a href="#fig-5manysamples">Figure&nbsp;<span>4.3</span></a> has 10 histograms, each showing what 10 different samples of twenty numbers looks like:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5manysamples" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5manysamples-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.3: Histograms for 10 different samples from the uniform distribution. Each sample contains 20 numbers. The histograms all look quite different. The differences between the samples are due to sampling error or random chance.</figcaption>
</figure>
</div>
</div>
</div>
<p>You might notice right away that none of the histograms are the same. Even though we are randomly taking 20 numbers from the very same uniform distribution, each sample of 20 numbers comes out different. That’s our sampling variability.</p>
<p><a href="#fig-5expectedUnif">Figure&nbsp;<span>4.4</span></a> shows an animated version of the process of repeatedly choosing 20 new random numbers and plotting a histogram. The horizontal line shows the flat-line shape of the uniform distribution. The line crosses the y-axis at 2; and, we expect that each number (from 1 to 10) should occur about 2 times each in a sample of 20. However, each sample bounces around quite a bit, due to random chance.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5expectedUnif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/sampleUnifExpected-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.4: Animated histograms of repeated samples of 20 from a uniform distribution. The black line marks the expected count of 2 per number; the bars rarely match it.</figcaption>
</figure>
</div>
</div>
</div>
<p>Small samples show high variability because random chance can produce very uneven counts even when every value is equally likely. This variability is sampling error, and it makes it harder to identify the true distribution from a single sample.</p>
</section>
<section id="large-samples-are-more-like-the-distribution-they-came-from" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="large-samples-are-more-like-the-distribution-they-came-from"><span class="header-section-number">4.2.3</span> Large samples are more like the distribution they came from</h3>
<p>Let’s refresh the question. Which of the two samples in <a href="#fig-5whichone">Figure&nbsp;<span>4.5</span></a> do you think came from a uniform distribution?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5whichone" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5whichone-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.5: Which of these two samples came from a uniform distribution?</figcaption>
</figure>
</div>
</div>
</div>
<p>Trick question. Both samples came from the uniform distribution, yet neither histogram looks flat. Sampling error can obscure the true shape of a distribution, even with a sample of this size.</p>
<p>Increasing the <strong>sample size</strong> makes it easier to see whether a sample came from a uniform distribution. We’ll often use the letter <code>n</code> for sample size: the number of observations in a sample.</p>
<p>Increasing each sample from 20 to 100 observations, and again creating 10 samples drawn from the same uniform distribution, we’d now expect each number from 1 to 10 to occur about 10 times per sample. The histograms are shown in <a href="#fig-5unifsamp100">Figure&nbsp;<span>4.6</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5unifsamp100" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5unifsamp100-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.6: Histograms for different samples from a uniform distribution. N = 100 for each sample.</figcaption>
</figure>
</div>
</div>
</div>
<p>Again, most of these histograms don’t look very flat: the bars still vary up and down instead of sitting exactly at 10 each. Sampling error is still there, and it always will be, at any sample size.</p>
<p>Increasing <span class="math inline">\(N\)</span> from 100 to 1000 observations per sample, we’d now expect every number to appear about 100 times each.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5unifsamp1000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5unifsamp1000-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.7: Histograms for different samples from a uniform distribution. N = 1000 for each sample.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-5unifsamp1000">Figure&nbsp;<span>4.7</span></a> shows the histograms starting to flatten out. The bars are still not perfectly at 100, because there is still sampling error, but a flat-looking histogram from a large sample gives more confidence that the numbers came from a uniform distribution.</p>
<p>Pushing sample size further, to 100,000 observations per sample, we’d expect each number to occur about 10,000 times each.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5sampunifALOT" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5sampunifALOT-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.8: Histograms for different samples from a uniform distribution. N = 100,000 for each sample.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-5sampunifALOT">Figure&nbsp;<span>4.8</span></a> shows the histograms for each sample starting to look the same. With 100,000 observations each, chance has enough opportunity to distribute the numbers evenly, so the bars all land very close to 10,000, right where they should be for a uniform distribution.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Key pattern.</strong> The pattern behind a sample will tend to stabilize as sample size increases. Small samples show a wider variety of patterns because of sampling error (chance).</p>
</div>
</div>
<p>Before returning to experiments, one more comparison, and this time it isn’t a trick question: in <a href="#fig-5whichoneB">Figure&nbsp;<span>4.9</span></a>, one of the two 20-observation samples really did come from a different distribution than the other.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5whichoneB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5whichoneB-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.9: Which of these samples came from a uniform distribution?</figcaption>
</figure>
</div>
</div>
</div>
<p>If you’re not confident in the answer, that’s because <strong>sampling error</strong> (randomness) is obscuring the histograms, even though the two samples really do come from different distributions this time.</p>
<p>Here’s the same question again, this time with 1,000 observations per sample. Which histogram in <a href="#fig-5whichoneC">Figure&nbsp;<span>4.10</span></a> do you think came from a uniform distribution, and which did not?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5whichoneC" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5whichoneC-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.10: Which of these samples came from a uniform distribution?</figcaption>
</figure>
</div>
</div>
</div>
<p>Now that we have increased N, we can see the pattern in each sample becomes more obvious. Distribution 1 has bars near 100, not perfectly flat, but it resembles a uniform distribution. Distribution 2 is not flat looking at all.</p>
<p>By comparing the two histograms, we’ve already performed a basic statistical inference: Distribution 2 did not come from a uniform distribution. This is the same logic underlying the formal tests covered in later chapters: arrange the data to make the source distribution visible, then judge whether the observed pattern is consistent with a hypothesized one.</p>
<!--
## Playing with distributions

talk about a few different distribution. Embed shiny app

SHINY APP here

-->
</section>
</section>
<section id="is-there-a-difference" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="is-there-a-difference"><span class="header-section-number">4.3</span> Is there a difference?</h2>
<p>Back to experiments. We want to know if an independent variable (our manipulation) causes a change in a dependent variable (measurement); if it does, we should see differences in the measurement as a function of the manipulation.</p>
<p>Some manipulations produce effects too large and consistent to need any statistics at all:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Light switch experiment.</strong> Flip the switch up (condition 1) and the light goes on (measurement). Flip it down (condition 2) and the light goes off (measurement). The light changes as a direct function of the switch position, every time. When an effect is this large and this consistent, there’s no ambiguity: you don’t need a statistical test to tell you the manipulation is working.</p>
</div>
</div>
<p>Most environmental effects aren’t like the light switch. They’re a real signal buried in noisy, variable measurements, which is exactly the kind of case inference is built for.</p>
<section id="chance-can-produce-differences" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="chance-can-produce-differences"><span class="header-section-number">4.3.1</span> Chance can produce differences</h3>
<p>Random chance can produce apparent differences between groups even when no real difference exists. We have already seen this with sampling: two samples from the same distribution come out differently. The same principle applies when we compare group means. This is a fundamental problem for inference.</p>
<p>To make this concrete, consider a scenario where we expect to find no real difference. A researcher surveys 10 bat hibernacula for white-nose syndrome, a fungal disease that has killed millions of North American bats. At each site they capture 20 bats and count how many show visible signs of infection. All 10 sites are drawn from the same population: no treatment, no environmental gradient, no systematic difference between them, so the true infection rate is identical everywhere. The sites are arbitrarily divided into two groups of 5 (Group A and Group B). Even though there is no real difference, we might still observe a difference in the mean number of infected bats simply because of sampling error.</p>
<p>Here is data from one run of this scenario:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Infected bats (of 20)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">7</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>This is a long-format table. Each row is one site. The first column shows the group assignment, and the second shows how many of the 20 captured bats were infected. Did Group A have more infected bats on average than Group B?</p>
<p>It is easier to see the comparison in a bar graph (<a href="#fig-5gumballA">Figure&nbsp;<span>4.11</span></a>), which shows the mean count for each group.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5gumballA" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5gumballA-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.11: Mean number of infected bats per site for two groups drawn from the same population. Note the zoomed y-axis, which does not start at 0.</figcaption>
</figure>
</div>
</div>
</div>
<p>The bars are not the same height: Group A and Group B have different mean counts. But both groups were drawn from the very same population of sites, so this isn’t a real difference in infection risk, it’s sampling error.</p>
<p>This is the core inference problem: differences appear even when nothing real caused them. <strong>How can we tell whether an observed difference is real or just the result of chance?</strong></p>
</section>
<section id="differences-due-to-chance-can-be-simulated" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="differences-due-to-chance-can-be-simulated"><span class="header-section-number">4.3.2</span> Differences due to chance can be simulated</h3>
<p>Chapter 2 showed that chance alone can produce spurious correlations. The same is true for group means: we can characterize exactly what chance is capable of producing in a comparison of group means. Once we know what chance typically does, and what it cannot do, we have a basis for judging whether our observed difference falls within or outside its range.</p>
<p>The first step is to replicate the sampling scenario many times. <a href="#fig-5gumballsims">Figure&nbsp;<span>4.12</span></a> shows bar graphs of the mean infected count for Group A and Group B across 10 replications of the same survey: all 10 sites sampled from the same population, split 5+5, and means computed.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5gumballsims" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5gumballsims-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.12: Ten replications of surveying 10 hibernacula and splitting them arbitrarily into two groups of 5. Every difference here is chance alone.</figcaption>
</figure>
</div>
</div>
</div>
<p>These 10 replications show that chance produces different mean differences each time. Sometimes Group A is higher, sometimes Group B is higher, sometimes the means are nearly equal. All of this variation arises from sampling error alone: there is no real difference in the population.</p>
</section>
</section>
<section id="chance-makes-some-differences-more-likely-than-others" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="chance-makes-some-differences-more-likely-than-others"><span class="header-section-number">4.4</span> Chance makes some differences more likely than others</h2>
<p>We have seen that chance can produce group mean differences. But we still need to characterize what chance usually does and what it rarely does. If we can establish the range of differences that chance produces, we can build a window: differences inside the window could plausibly have arisen by chance; differences outside the window could not.</p>
<p>We summarize each replication as a single <strong>difference score</strong>: the mean count for Group A minus the mean count for Group B. <a href="#fig-5gumballdiffs">Figure&nbsp;<span>4.13</span></a> shows those difference scores for the 10 replications above.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5gumballdiffs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5gumballdiffs-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.13: Difference in mean infected count between Group A and Group B across 10 replications. The true difference is zero, but sampling error produces non-zero differences each time.</figcaption>
</figure>
</div>
</div>
</div>
<p>A bar at zero means the two groups had the same mean count in that replication. Positive values indicate Group A was higher; negative values indicate Group B was higher. The signs of the differences would flip if we reversed the subtraction order.</p>
<p>The differences in these 10 replications mostly fall in a narrow range. To better characterize what chance can do, we run 100 replications. The results are shown in <a href="#fig-5manydiffs">Figure&nbsp;<span>4.14</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5manydiffs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5manydiffs-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.14: Difference in mean infected count between Group A and Group B across 100 replications. There are many possible differences that chance can produce, but the y-axis shows the range is bounded.</figcaption>
</figure>
</div>
</div>
</div>
<p>The x-axis just indexes the 100 replications; the information is on the y-axis. Many different difference sizes occur, but the range is bounded: the bars stay within a limited band around zero, and differences several times larger never show up. This begins to define the window of what chance can produce.</p>
<p>To get a clearer picture, we now run 10,000 replications and plot the distribution of difference scores as a histogram. This gives a precise view of which differences happen often and which are extremely rare.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5histdiffgumball" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5histdiffgumball-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.15: Histogram of mean count differences between Group A and Group B over 10,000 replications. All differences arise from chance alone. The most frequent difference is near zero; larger differences occur less often. Chance cannot produce everything.</figcaption>
</figure>
</div>
</div>
</div>
<p>This histogram is the <strong>chance window</strong> for this study design. It shows that chance most often produces a difference near zero, the tallest bar in the center. Larger differences in either direction occur less and less frequently. The distribution has a clear boundary: extreme differences are possible but very rare.</p>
<p>We can use this window to evaluate any observed difference. If a study found a difference of 1 infected bat between two groups, that falls well inside the chance window: differences of that size occur frequently by random sampling alone. If the study found a difference of 6 bats, that would fall far outside the window; chance produced a difference that large 0 times out of 10,000. When an observed result almost never happens by chance, we have grounds to conclude that something other than chance produced it.</p>
</section>
<section id="simulation-based-inference" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="simulation-based-inference"><span class="header-section-number">4.5</span> Simulation-Based Inference</h2>
<p>Most of the inference done throughout the rest of this course comes down to one question: did chance produce the difference in the data? In an experiment, we want to know if our manipulation caused a difference in our measurement. But everything we measure has natural variability, so we’ll always find <em>some</em> difference between conditions, whether the manipulation matters or not. What we want to know is whether that difference could plausibly have been produced by chance alone. If chance is a very unlikely explanation, we infer that something about the manipulation, not chance, produced the difference.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Beyond ruling out chance.</strong> Statistics is not only about determining whether chance could have produced a pattern in the observed data. The same tools we are talking about here can be generalized to ask whether any kind of distribution could have produced the differences. This allows comparisons between different models of the data, to see which one was the most likely, rather than just rejecting the unlikely ones (e.g., chance). But, we’ll leave those advanced topics for another textbook.</p>
</div>
</div>
<p>The simulation-based approach here answers that question the same way every formal test in later chapters does. The advantage of starting with simulation is that every step is visible before any formulas are introduced.</p>
<section id="intuitive-methods" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="intuitive-methods"><span class="header-section-number">4.5.1</span> Intuitive methods</h3>
<p>The approach in this section uses only simple arithmetic operations that you already understand to build a tool for inference. Specifically, we will use:</p>
<ol type="1">
<li>Sampling numbers randomly from a distribution</li>
<li>Adding and subtracting</li>
<li>Division, to find the mean</li>
<li>Counting</li>
<li>Graphing and drawing lines</li>
<li>No formulas</li>
</ol>
</section>
<section id="part-1-frequency-based-intuition-about-occurrence" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="part-1-frequency-based-intuition-about-occurrence"><span class="header-section-number">4.5.2</span> Part 1: Frequency-based intuition about occurrence</h3>
<p><strong>Question</strong>: How many times does something need to happen for it to happen “a lot”? How rare does something need to be before you stop worrying about it?</p>
<p>Environmental scientists already have a working vocabulary for this: the <strong>100-year flood</strong>. A “100-year flood” doesn’t mean floods that size happen once a century on a schedule; it means that in any given year, there’s about a 1-in-100 chance of a flood that severe. Would you build a house in that floodplain? Many people do, and often regret it, because a 1% annual chance still adds up over a 30-year mortgage (roughly a 26% chance of at least one such flood in that span). A location with a 1-in-10,000 annual flood risk is very different: over the same 30 years, the cumulative chance is under 0.3%. Same underlying logic, wildly different practical decisions.</p>
<p>That’s the intuition we need going forward: <strong>rare events still happen, but how rare something is changes what you’re willing to conclude from seeing it.</strong> Later in this chapter, we’ll use 1-in-10,000 as our own working definition of “rare enough to call surprising.”</p>
</section>
<section id="part-2-judgment-and-decision-making" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="part-2-judgment-and-decision-making"><span class="header-section-number">4.5.3</span> Part 2: Judgment and Decision-making</h3>
<p>We already have everything we need to make this concrete: the bat simulation above gave us 10,000 mean differences that chance alone can produce when there is no real difference between groups. That histogram (<a href="#fig-5histdiffgumball">Figure&nbsp;<span>4.15</span></a>) <em>is</em> our reference distribution. Now we use it to make a decision.</p>
<p>Let’s draw some lines on that same histogram and label two kinds of regions:</p>
<ol type="1">
<li><strong>Region of chance.</strong> Chance did it. Chance could have done it.</li>
<li><strong>Region of not chance.</strong> Chance didn’t do it. Chance couldn’t have done it.</li>
</ol>
<p>The boundaries are the minimum and maximum values chance actually produced across the 10,000 replications. <a href="#fig-5simdecision">Figure&nbsp;<span>4.16</span></a> shows this applied to our count differences.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5simdecision" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5simdecision-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.16: Decision boundaries applied to the histogram of mean count differences from <a href="#fig-5histdiffgumball">Figure&nbsp;<span>4.15</span></a>. Green marks differences chance never produced in 10,000 replications; red marks the range chance did produce; grey marks a zone chance produced only rarely.</figcaption>
</figure>
</div>
</div>
</div>
<p>Here’s how the decision works. A difference beyond the green boundary (roughly -5.2 to 4.8 bats, from our 10,000 simulated replications) never happened by chance in this simulation, so observing something out there would give real grounds to suspect it wasn’t just sampling error. A difference well inside the red zone, close to 0, is exactly what chance produces routinely: no grounds for suspicion.</p>
<p>The grey bands are the honest part: differences near the edge of what chance can do, but not quite past it. Chance <em>could</em> produce something in the grey zone, it’s technically still inside the red window, but it does so rarely. That’s not a clean yes/no; it’s a “probably not chance, but I can’t rule it out,” and how you handle that ambiguity is a judgment call, not a fact. More conservative researchers shrink the grey zone (fewer false alarms, more missed real effects); more permissive researchers expand it (the reverse trade-off). Chapter 5 formalizes this trade-off with a standard convention (<span class="math inline">\(\alpha = .05\)</span>) so that researchers aren’t each inventing their own boundary from scratch.</p>
<section id="making-decisions-and-being-wrong" class="level4" data-number="4.5.3.1">
<h4 data-number="4.5.3.1" class="anchored" data-anchor-id="making-decisions-and-being-wrong"><span class="header-section-number">4.5.3.1</span> Making decisions and being wrong</h4>
<p>No matter how you plan to make decisions about your data, you will always be prone to making some mistakes. You might call one finding real, when in fact it was caused by chance. This is called a <strong>type I</strong> error, or a false positive. You might ignore one finding, calling it chance, when in fact it wasn’t chance (even though it was in the window). This is called a <strong>type II</strong> error, or a false negative.</p>
<p>How you make decisions influences how often you make errors over time. A researcher who only accepts results as real when they fall in the strict “no chance” zone will make few type I errors, but will also make more type II errors, missing real effects that the decision criterion happened to call chance. A researcher who accepts results in the grey zone as real will make more type I errors but fewer type II errors. Using cutoff regions for decision-making forces this trade-off. The Bayesian view sidesteps it somewhat: rather than a binary real/not-real decision, it treats confidence as continuous, updated by each new experiment, which avoids committing to a fixed trade-off between the two error types.</p>
<p>There’s also a way to reduce both error types, and increase confidence in your results, before you even run the experiment: designing the study well in the first place.</p>
</section>
</section>
<section id="part-3-study-design-and-sensitivity" class="level3" data-number="4.5.4">
<h3 data-number="4.5.4" class="anchored" data-anchor-id="part-3-study-design-and-sensitivity"><span class="header-section-number">4.5.4</span> Part 3: Study Design and Sensitivity</h3>
<p>Study design directly controls how sensitive an analysis is. It’s often possible, and important, to choose a design that can actually detect the size of effect you care about.</p>
<p>Two forces govern whether a study can detect a real effect: the size of the effect, and the amount of noise in the data. The main design choice under your control is sample size, which determines how much that noise obscures the signal.</p>
<p>Recall what happens to the sampling distribution of the mean as sample size increases: it narrows. The same is true for the distribution of mean differences. As <span class="math inline">\(n\)</span> increases, the range of differences that chance alone produces shrinks. This means that with enough sites or plots, even a small real effect can be reliably distinguished from noise, while with too few, even a fairly large real effect can get lost in it.</p>
<p>Let’s return to the hibernacula scenario, but now vary the number of sites surveyed per group: 5 (what we started with), 10, 20, and 40.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5sampleDistNormal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5sampleDistNormal-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.17: The width of the chance window for mean count differences shrinks as the number of sites per group increases.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-5minmax" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;4.1: Smallest and largest mean count differences produced by chance, by sites per group.</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Sites per group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Smallest</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Largest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">-5.40</td>
<td style="text-align: right;">5.20</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">-3.20</td>
<td style="text-align: right;">3.90</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20</td>
<td style="text-align: right;">-2.95</td>
<td style="text-align: right;">2.55</td>
</tr>
<tr class="even">
<td style="text-align: right;">40</td>
<td style="text-align: right;">-1.80</td>
<td style="text-align: right;">1.75</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>The pattern is clear: the chance window is wide with only 5 sites per group and narrows steadily as sites are added. Consider what this means for a real study. Suppose a treatment applied inside the hibernacula is expected to reduce infections by about 2 bats per site. With only 5 sites per group, that effect size sits well inside the chance window in the table above, so a real 2-bat effect could easily be mistaken for sampling noise, or a sampling-noise result could be mistaken for a real effect. With 40 sites per group, the same 2-bat difference sits outside the window chance can produce, and you could detect it with real confidence.</p>
<p><strong>The design of a study determines the size of effect it can reliably detect.</strong> Sample size is the main lever, but not the only one: taking repeated measurements at each site (reducing measurement noise) and choosing conditions with a genuinely strong contrast both help too. This idea, how sensitive a given design is to a real effect of a given size, has a name, <strong>statistical power</strong>, which Chapter 5 develops formally alongside the standard <span class="math inline">\(\alpha = .05\)</span> convention.</p>
</section>
<section id="summary-of-simulation-based-inference" class="level3" data-number="4.5.5">
<h3 data-number="4.5.5" class="anchored" data-anchor-id="summary-of-simulation-based-inference"><span class="header-section-number">4.5.5</span> Summary of Simulation-Based Inference</h3>
<p>We built the core logic of inference using nothing but sampling, arithmetic, and histograms: simulate what chance alone can produce, compare an observed result to that simulated distribution, and use where it falls to judge whether chance is a plausible explanation. The comparison isn’t perfectly clean. There’s a grey zone near the edges where judgment has to do the work, and the width of the chance window itself depends on how much data you collect.</p>
</section>
</section>
<section id="the-randomization-test-permutation-test" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="the-randomization-test-permutation-test"><span class="header-section-number">4.6</span> The randomization test (permutation test)</h2>
<p>This is the first formal inferential statistic in this textbook. Everything so far has built the intuition; now we formalize it into a <strong>randomization test</strong>, which uses random chance to judge whether an experimental finding was likely due to chance or not. The ideas behind it are exactly the ideas already developed in this chapter, now assembled and given a name.</p>
<p>When you run an experiment and collect data, you find out what happened that one time. Because you ran it only once, you don’t find out what <strong>could have happened</strong>. The randomization test gives you that missing half, so you can compare <strong>what did happen</strong> in your experiment against it.</p>
<section id="pretend-example-does-distance-from-a-highway-affect-no₂-levels" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="pretend-example-does-distance-from-a-highway-affect-no₂-levels"><span class="header-section-number">4.6.1</span> Pretend example: does distance from a highway affect NO₂ levels?</h3>
<p>Let’s say you are monitoring nitrogen dioxide (NO₂) concentrations at air quality sites near a major highway. You assign 20 monitoring sites to a “near” group (within 50 m of the highway) and 20 different sites to a “far” group (500 m or more from the highway). If highway traffic is a meaningful source of NO₂, then the near group should have higher concentrations on average than the far group.</p>
<p>Let’s say the data looked like this:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near_ppb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far_ppb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">41</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">41</td>
<td style="text-align: left;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">59</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">33</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">41</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">22</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">52</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">957</td>
<td style="text-align: left;">456</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">47.85</td>
<td style="text-align: left;">22.8</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>So, did the near-highway sites have higher NO₂ than the far sites? The mean for near sites was 47.85 ppb, and for far sites was 22.8 ppb. Just looking at the means, it looks like proximity to the highway matters.</p>
<p>But could this just be chance? Maybe the near sites happened to be in a windier or more industrialized area, so their higher readings reflect those conditions rather than the highway itself, or maybe the difference arose simply from random sampling variation. That’s a legitimate concern worth taking seriously. We already know how the data came out; what we want to know is how they <em>could have</em> come out, across all the possibilities.</p>
<p>The data would have come out a bit different if some sites from the near group had been placed in the far group, and vice versa. There are many ways the 40 sites could have been assigned to two groups, and the group means would come out differently depending on the assignment.</p>
<p>It’s not practical to run the experiment every possible way, that would take too long, but we can estimate how those experiments might have turned out using simulation.</p>
<p>We take all 40 NO₂ readings from both groups, pool them together, then randomly assign 20 to a “near” group and 20 to a “far” group, as if the original assignment had been done differently. We compute the new group means and their difference, and repeat this process many times to build up a picture of what the difference could have been under random assignment.</p>
<section id="doing-the-randomization" class="level4" data-number="4.6.1.1">
<h4 data-number="4.6.1.1" class="anchored" data-anchor-id="doing-the-randomization"><span class="header-section-number">4.6.1.1</span> Doing the randomization</h4>
<p>Before we do that, let’s show how the randomization part works. We’ll use fewer numbers to make the process easier to look at. Here are the first 5 NO₂ readings from each group.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near_ppb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far_ppb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">41</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">259</td>
<td style="text-align: left;">106</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">51.8</td>
<td style="text-align: left;">21.2</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Things could have turned out differently if some of the near-highway sites had been placed in the far group instead, and vice versa. Here’s how we can do some random switching using R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>all_readings      <span class="ot">&lt;-</span> <span class="fu">c</span>(near[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>], far[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>randomize_scores  <span class="ot">&lt;-</span> <span class="fu">sample</span>(all_readings)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>new_near          <span class="ot">&lt;-</span> randomize_scores[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>new_far           <span class="ot">&lt;-</span> randomize_scores[<span class="dv">6</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(new_near)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 58 41 63 16 12</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(new_far)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 60 27 28 23 37</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have taken the first 5 readings from each group and put them all into a variable called <code>all_readings</code>. Then we use the <code>sample</code> function in R to shuffle the readings. Finally, we take the first 5 readings from the shuffled numbers and put them into <code>new_near</code>, and the last five into <code>new_far</code>.</p>
<p>Repeating this a couple of times and putting the results in a table shows the group means shifting each time the sites are shuffled around:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near_ppb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far_ppb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near3</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">41</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">58</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">41</td>
<td style="text-align: left;">23</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">23</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">37</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">259</td>
<td style="text-align: left;">106</td>
<td style="text-align: left;">188</td>
<td style="text-align: left;">177</td>
<td style="text-align: left;">190</td>
<td style="text-align: left;">175</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">51.8</td>
<td style="text-align: left;">21.2</td>
<td style="text-align: left;">37.6</td>
<td style="text-align: left;">35.4</td>
<td style="text-align: left;">38</td>
<td style="text-align: left;">35</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="simulating-the-mean-differences-across-the-different-randomizations" class="level4" data-number="4.6.1.2">
<h4 data-number="4.6.1.2" class="anchored" data-anchor-id="simulating-the-mean-differences-across-the-different-randomizations"><span class="header-section-number">4.6.1.2</span> Simulating the mean differences across the different randomizations</h4>
<p>In our pretend study we found that the mean NO₂ for near-highway sites was 47.85 ppb, and for far sites was 22.8 ppb. The mean difference (near − far) was 25.05 ppb. This is a pretty big difference. This is <strong>what did happen</strong>. But, <strong>what could have happened</strong>? If we tried out all the possible ways to assign 40 sites to two groups, what does the distribution of the possible mean differences look like? Let’s find out. This is what the randomization test is all about.</p>
<p>When we do our randomization test we will measure the mean difference in NO₂ between the near and far groups. Every time we randomize we will save the mean difference.</p>
<p><a href="#fig-5randtest">Figure&nbsp;<span>4.18</span></a> animates what’s happening in a randomization test, using data from a different fake study (we’ll return to the NO₂ example after). The purple dots show the original mean of each group (lower-exposure vs.&nbsp;higher-exposure sites); since one sits below the other, we want to know whether chance could produce a difference that size. The light green and red dots are the individual readings from each of 10 sites per group, the raw data the purple means are built from. As the animation randomizes, those readings shuffle between groups, and the moving yellow dots show the resulting new group means after each shuffle. The spread of the yellow dots shows the range of differences chance alone could produce.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5randtest" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/randomizationTest-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.18: Animation of a randomization test. Purple dots are the original condition means, yellow dots the means after each reshuffle, and blue and red dots track how individual scores move.</figcaption>
</figure>
</div>
</div>
</div>
<p>We are engaging in some visual statistical inference. By looking at the range of motion of the yellow dots, we are watching what kind of differences chance can produce. In this animation, the purple dots, representing the original difference, are generally outside of the range of chance. The yellow dots don’t move past the purple dots, as a result chance is an unlikely explanation of the difference.</p>
<p>If the purple dots were inside the range of the yellow dots, we would know that chance is capable of producing the difference we observed, and that it does so fairly often. As a result, we should not conclude the manipulation caused the difference, because it could have easily occurred by chance.</p>
<p>Let’s return to the NO₂ example. After we randomize our readings many times and compute the new means and mean differences, we will have loads of mean differences to look at, which we can plot in a histogram. The histogram gives a picture of <strong>what could have happened</strong>. Then, we can compare <strong>what did happen</strong> with <strong>what could have happened</strong>.</p>
<p>Here’s the histogram of the mean differences from the randomization test. For this simulation, we randomized the results from the original study 10,000 times. This is what could have happened. The blue line in <a href="#fig-5randhist">Figure&nbsp;<span>4.19</span></a> shows where the observed difference lies on the x-axis.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5randhist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5randhist-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.19: A histogram of simulated mean differences in NO₂ (ppb) for a randomization test. The blue vertical line marks the observed difference from our study.</figcaption>
</figure>
</div>
</div>
</div>
<p>This histogram is another window of chance: the mean differences that could have occurred if the 40 sites had been assigned to the near and far groups differently. The differences range from negative to positive, symmetric around a most-frequent value of 0, and grow less frequent the larger they get in either direction. The blue line, <strong>the observed difference</strong> from our study, sits well out to the right, outside the histogram entirely.</p>
<p>So could the observed difference have been caused by chance? Probably not. It is rare under chance alone, which makes it more consistent with a real effect of highway proximity on NO₂.</p>
<p><strong>Important:</strong> <strong>what could have happened</strong> always means what could have happened <strong>by chance</strong>. That comparison is the whole test.</p>
<p>Now suppose we’d gotten a much smaller mean difference when we first ran the study. New lines (blue and red) represent smaller differences we might have found instead.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5randquestion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-Foundation_Inference_files/figure-html/fig-5randquestion-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.20: Would you expect a mean difference represented by the blue line to occur more or less often by chance compared to the mean difference represented by the red line?</figcaption>
</figure>
</div>
</div>
</div>
<p>Look at the blue line in <a href="#fig-5randquestion">Figure&nbsp;<span>4.20</span></a>, a mean difference of 10 ppb. It sits inside the chance window: differences that size do happen sometimes by chance. You might lean toward “probably not chance” since it’s near the edge, but with some real skepticism. The red line, a difference of +5 ppb, sits well inside the chance window, and differences that size happen fairly often, so it would take more evidence before concluding highway proximity was driving it.</p>
</section>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">4.7</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> This chapter is the conceptual hinge of the course. Every formal test that follows is a shortcut for what we did here by hand: work out what chance alone could produce, then check whether your result sits inside that range.</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>The question inference actually asks.</strong> Not “is there a difference,” but “where did this difference come from?” Chance alone produces differences between groups all the time, so the real question is whether chance is a sufficient explanation for yours.</li>
<li><strong>Simulate what chance can do.</strong> Randomly reshuffling your data breaks any real relationship while keeping everything else intact. Doing that many times builds a picture of the differences chance alone can generate for a dataset your size.</li>
<li><strong>Then compare.</strong> If your observed difference sits comfortably inside that chance window, chance remains a plausible explanation. If it sits far outside, chance becomes hard to defend as the whole story.</li>
<li><strong>The grey zone is real.</strong> Results near the edge of the chance window are genuinely ambiguous, and where you draw the line is a judgment call rather than a fact. The next chapter adopts a convention (<span class="math inline">\(\alpha = .05\)</span>) so researchers aren’t each inventing their own boundary.</li>
<li><strong>Design determines what you can detect.</strong> Sample size is the main lever, but repeated measurements and a stronger contrast between conditions matter too. A study can fail to find a real effect simply because it was never built to see one.</li>
<li><strong>The picture becomes a number.</strong> From here on we replace the histogram with a single summary, the probability that chance could have produced your result. That number is the <span class="math inline">\(p\)</span>-value, and the next few chapters build toward it.</li>
</ul>
</section>
<section id="videos" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="videos"><span class="header-section-number">4.8</span> Videos</h2>
<section id="null-and-alternate-hypotheses" class="level3" data-number="4.8.1">
<h3 data-number="4.8.1" class="anchored" data-anchor-id="null-and-alternate-hypotheses"><span class="header-section-number">4.8.1</span> Null and Alternate Hypotheses</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/gJ38qX0ihPc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="types-of-errors" class="level3" data-number="4.8.2">
<h3 data-number="4.8.2" class="anchored" data-anchor-id="types-of-errors"><span class="header-section-number">4.8.2</span> Types of Errors</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/zhhDCFPzlkw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-SamplesPopulations.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-Hypothesis_Testing.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>