<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>Answering questions with data - 4&nbsp; Probability and Distributions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-Foundation_Inference.html" rel="next">
<link href="./03-Correlation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 4&nbsp; Probability and Distributions">
<meta property="og:description" content="">
<meta property="og:image" content="04-SamplesPopulations_files/figure-html/fig-icecream-prob-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 4&nbsp; Probability and Distributions">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-SamplesPopulations.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Run this:</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Run this:</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-RMANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Allow HTML inside a PDF build (prevents early abort).</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-MixedANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Thinking about answering questions with data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-Gifs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">GIFs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#from-description-to-inference" id="toc-from-description-to-inference" class="nav-link active" data-scroll-target="#from-description-to-inference"><span class="header-section-number">4.1</span> From description to inference</a></li>
  <li><a href="#probability-vs.-statistics" id="toc-probability-vs.-statistics" class="nav-link" data-scroll-target="#probability-vs.-statistics"><span class="header-section-number">4.2</span> Probability vs.&nbsp;Statistics</a></li>
  <li><a href="#what-does-probability-mean" id="toc-what-does-probability-mean" class="nav-link" data-scroll-target="#what-does-probability-mean"><span class="header-section-number">4.3</span> What does probability mean?</a></li>
  <li><a href="#basic-probability-theory" id="toc-basic-probability-theory" class="nav-link" data-scroll-target="#basic-probability-theory"><span class="header-section-number">4.4</span> Basic probability theory</a></li>
  <li><a href="#rules-of-probability" id="toc-rules-of-probability" class="nav-link" data-scroll-target="#rules-of-probability"><span class="header-section-number">4.5</span> Rules of Probability</a>
  <ul class="collapse">
  <li><a href="#not-a" id="toc-not-a" class="nav-link" data-scroll-target="#not-a"><span class="header-section-number">4.5.1</span> <strong>Not</strong> <span class="math inline">\(A\)</span></a></li>
  <li><a href="#a-and-b" id="toc-a-and-b" class="nav-link" data-scroll-target="#a-and-b"><span class="header-section-number">4.5.2</span> <span class="math inline">\(A\)</span> <strong>and</strong> <span class="math inline">\(B\)</span></a></li>
  <li><a href="#a-or-b" id="toc-a-or-b" class="nav-link" data-scroll-target="#a-or-b"><span class="header-section-number">4.5.3</span> <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span></a></li>
  <li><a href="#a-cup-b-textchocolate-vanilla-strawberry-rocky-road" id="toc-a-cup-b-textchocolate-vanilla-strawberry-rocky-road" class="nav-link" data-scroll-target="#a-cup-b-textchocolate-vanilla-strawberry-rocky-road"><span class="header-section-number">4.5.4</span> <span class="math inline">\(A \cup B = (\text{chocolate, vanilla, strawberry, rocky road})\)</span></a></li>
  </ul></li>
  <li><a href="#probaiblity-distributions" id="toc-probaiblity-distributions" class="nav-link" data-scroll-target="#probaiblity-distributions"><span class="header-section-number">4.6</span> Probaiblity Distributions</a>
  <ul class="collapse">
  <li><a href="#the-binomial-distribution" id="toc-the-binomial-distribution" class="nav-link" data-scroll-target="#the-binomial-distribution"><span class="header-section-number">4.6.1</span> The binomial distribution</a></li>
  </ul></li>
  <li><a href="#the-normal-distribution" id="toc-the-normal-distribution" class="nav-link" data-scroll-target="#the-normal-distribution"><span class="header-section-number">4.7</span> The normal distribution</a></li>
  <li><a href="#summary-of-probability" id="toc-summary-of-probability" class="nav-link" data-scroll-target="#summary-of-probability"><span class="header-section-number">4.8</span> Summary of Probability</a></li>
  <li><a href="#samples-populations-and-sampling" id="toc-samples-populations-and-sampling" class="nav-link" data-scroll-target="#samples-populations-and-sampling"><span class="header-section-number">4.9</span> Samples, populations and sampling</a>
  <ul class="collapse">
  <li><a href="#defining-a-population" id="toc-defining-a-population" class="nav-link" data-scroll-target="#defining-a-population"><span class="header-section-number">4.9.1</span> Defining a population</a></li>
  <li><a href="#simple-random-samples" id="toc-simple-random-samples" class="nav-link" data-scroll-target="#simple-random-samples"><span class="header-section-number">4.9.2</span> Simple random samples</a></li>
  <li><a href="#most-samples-are-not-simple-random-samples" id="toc-most-samples-are-not-simple-random-samples" class="nav-link" data-scroll-target="#most-samples-are-not-simple-random-samples"><span class="header-section-number">4.9.3</span> Most samples are not simple random samples</a></li>
  <li><a href="#how-much-does-it-matter-if-you-dont-have-a-simple-random-sample" id="toc-how-much-does-it-matter-if-you-dont-have-a-simple-random-sample" class="nav-link" data-scroll-target="#how-much-does-it-matter-if-you-dont-have-a-simple-random-sample"><span class="header-section-number">4.9.4</span> How much does it matter if you don’t have a simple random sample?</a></li>
  <li><a href="#population-parameters-and-sample-statistics" id="toc-population-parameters-and-sample-statistics" class="nav-link" data-scroll-target="#population-parameters-and-sample-statistics"><span class="header-section-number">4.9.5</span> Population parameters and sample statistics</a></li>
  </ul></li>
  <li><a href="#the-law-of-large-numbers" id="toc-the-law-of-large-numbers" class="nav-link" data-scroll-target="#the-law-of-large-numbers"><span class="header-section-number">4.10</span> The law of large numbers</a></li>
  <li><a href="#sampling-distributions-and-the-central-limit-theorem" id="toc-sampling-distributions-and-the-central-limit-theorem" class="nav-link" data-scroll-target="#sampling-distributions-and-the-central-limit-theorem"><span class="header-section-number">4.11</span> Sampling distributions and the central limit theorem</a>
  <ul class="collapse">
  <li><a href="#sampling-distribution-of-the-sample-means" id="toc-sampling-distribution-of-the-sample-means" class="nav-link" data-scroll-target="#sampling-distribution-of-the-sample-means"><span class="header-section-number">4.11.1</span> Sampling distribution of the sample means</a></li>
  <li><a href="#seeing-the-pieces" id="toc-seeing-the-pieces" class="nav-link" data-scroll-target="#seeing-the-pieces"><span class="header-section-number">4.11.2</span> Seeing the pieces</a></li>
  <li><a href="#sampling-distributions-exist-for-any-sample-statistic" id="toc-sampling-distributions-exist-for-any-sample-statistic" class="nav-link" data-scroll-target="#sampling-distributions-exist-for-any-sample-statistic"><span class="header-section-number">4.11.3</span> Sampling distributions exist for any sample statistic!</a></li>
  </ul></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem"><span class="header-section-number">4.12</span> The central limit theorem</a></li>
  <li><a href="#z-scores" id="toc-z-scores" class="nav-link" data-scroll-target="#z-scores"><span class="header-section-number">4.13</span> z-scores</a>
  <ul class="collapse">
  <li><a href="#idea-behind-z-scores" id="toc-idea-behind-z-scores" class="nav-link" data-scroll-target="#idea-behind-z-scores"><span class="header-section-number">4.13.1</span> Idea behind z-scores</a></li>
  <li><a href="#calculating-z-scores" id="toc-calculating-z-scores" class="nav-link" data-scroll-target="#calculating-z-scores"><span class="header-section-number">4.13.2</span> Calculating z-scores</a></li>
  </ul></li>
  <li><a href="#estimating-population-parameters" id="toc-estimating-population-parameters" class="nav-link" data-scroll-target="#estimating-population-parameters"><span class="header-section-number">4.14</span> Estimating population parameters</a>
  <ul class="collapse">
  <li><a href="#concrete-population-parameters" id="toc-concrete-population-parameters" class="nav-link" data-scroll-target="#concrete-population-parameters"><span class="header-section-number">4.14.1</span> Concrete population parameters</a></li>
  <li><a href="#abstract-population-parameters" id="toc-abstract-population-parameters" class="nav-link" data-scroll-target="#abstract-population-parameters"><span class="header-section-number">4.14.2</span> Abstract population parameters</a></li>
  <li><a href="#experiments-and-population-parameters" id="toc-experiments-and-population-parameters" class="nav-link" data-scroll-target="#experiments-and-population-parameters"><span class="header-section-number">4.14.3</span> Experiments and Population parameters</a></li>
  <li><a href="#interim-summary" id="toc-interim-summary" class="nav-link" data-scroll-target="#interim-summary"><span class="header-section-number">4.14.4</span> Interim summary</a></li>
  <li><a href="#estimating-the-population-mean" id="toc-estimating-the-population-mean" class="nav-link" data-scroll-target="#estimating-the-population-mean"><span class="header-section-number">4.14.5</span> Estimating the population mean</a></li>
  <li><a href="#estimating-the-population-standard-deviation" id="toc-estimating-the-population-standard-deviation" class="nav-link" data-scroll-target="#estimating-the-population-standard-deviation"><span class="header-section-number">4.14.6</span> Estimating the population standard deviation</a></li>
  </ul></li>
  <li><a href="#estimating-a-confidence-interval" id="toc-estimating-a-confidence-interval" class="nav-link" data-scroll-target="#estimating-a-confidence-interval"><span class="header-section-number">4.15</span> Estimating a confidence interval</a>
  <ul class="collapse">
  <li><a href="#a-slight-mistake-in-the-formula" id="toc-a-slight-mistake-in-the-formula" class="nav-link" data-scroll-target="#a-slight-mistake-in-the-formula"><span class="header-section-number">4.15.1</span> A slight mistake in the formula</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.16</span> Summary</a></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"><span class="header-section-number">4.17</span> Videos</a>
  <ul class="collapse">
  <li><a href="#introduction-to-probability" id="toc-introduction-to-probability" class="nav-link" data-scroll-target="#introduction-to-probability"><span class="header-section-number">4.17.1</span> Introduction to Probability</a></li>
  <li><a href="#chebychevs-theorem" id="toc-chebychevs-theorem" class="nav-link" data-scroll-target="#chebychevs-theorem"><span class="header-section-number">4.17.2</span> Chebychev’s Theorem</a></li>
  <li><a href="#z-scores-1" id="toc-z-scores-1" class="nav-link" data-scroll-target="#z-scores-1"><span class="header-section-number">4.17.3</span> Z-scores</a></li>
  <li><a href="#normal-distribution-i" id="toc-normal-distribution-i" class="nav-link" data-scroll-target="#normal-distribution-i"><span class="header-section-number">4.17.4</span> Normal Distribution I</a></li>
  <li><a href="#normal-distribution-ii" id="toc-normal-distribution-ii" class="nav-link" data-scroll-target="#normal-distribution-ii"><span class="header-section-number">4.17.5</span> Normal Distribution II</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/04-SamplesPopulations.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 12, 2025</p>
    </div>
  </div>
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>I have studied many languages-French, Spanish and a little Italian, but no one told me that Statistics was a foreign language. – Charmaine J. Forde</p>
</blockquote>
<section id="from-description-to-inference" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="from-description-to-inference"><span class="header-section-number">4.1</span> From description to inference</h2>
<p>Up to this point, we’ve focused on experimental design and descriptive statistics: how to collect data and how to summarize it with graphs and averages. But statistics is more than description. Its power is in inference, using limited data to say something about a broader population. Inference relies on two foundations: probability theory and the behavior of samples from distributions.</p>
</section>
<section id="probability-vs.-statistics" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="probability-vs.-statistics"><span class="header-section-number">4.2</span> Probability vs.&nbsp;Statistics</h2>
<p>Probability and statistics are closely related but not the same.</p>
<p><strong>Probability</strong> starts with a known model of the world and asks: what kinds of data are likely?</p>
<ul>
<li>Example: What is the chance of flipping 10 heads in a row with a fair coin?</li>
<li>Example: What is the chance of drawing five hearts from a shuffled deck?</li>
</ul>
<p>Here, the <strong>model is known</strong> (fair coin, fair deck). Data are imagined.</p>
<p><strong>Statistics</strong> starts with data and asks: what model of the world generated these data?</p>
<ul>
<li>Example: If a coin comes up heads 10 times in a row, is it fair?</li>
<li>Example: If five cards in a row are hearts, was the deck shuffled?</li>
</ul>
<p>Here, the <strong>data are known</strong>. The model is what we want to learn about.</p>
<p><strong>Takeaway:</strong></p>
<ul>
<li><p>Probability works from model → data. Statistics works from data → model.</p></li>
<li><p>Because inference depends on probability, we start this chapter with probability foundations.</p></li>
</ul>
</section>
<section id="what-does-probability-mean" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="what-does-probability-mean"><span class="header-section-number">4.3</span> What does probability mean?</h2>
<p>Statisticians agree on the rules of probability but not always on what the word itself means. In everyday life we’re comfortable saying something is “likely” or “unlikely,” but the formal meaning varies.</p>
<p>Imagine a soccer game between Arsenal and West Ham. You say Arsenal has an 80% chance of winning. That could mean:</p>
<ol type="1">
<li><p>Long-run frequency: if the teams played many times, Arsenal would win ~8 out of 10.</p></li>
<li><p>Betting odds: you’d only take a wager if payoffs reflected an 80/20 split.</p></li>
<li><p>Subjective belief: your confidence in Arsenal is four times stronger than in West Ham.</p></li>
</ol>
<p>All three interpretations follow the same rules but reflect different philosophies.</p>
<p>For our purposes, the math works the same either way. In this course we’ll use the <strong>frequentist</strong> view, so you can think of probability as the long-run proportion of times an event would occur if you could repeat the process many times (that’s #1 above).</p>
</section>
<section id="basic-probability-theory" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="basic-probability-theory"><span class="header-section-number">4.4</span> Basic probability theory</h2>
<p>At the core of probability theory is the idea of a distribution: a set of possible outcomes and their probabilities.</p>
<p>Suppose we track which ice cream flavor a customer chooses: chocolate, vanilla, or strawberry. Each choice is an <em>elementary event</em>, and the set of all possible events is the <em>sample space</em>, <span class="math inline">\(S\)</span>:</p>
<p><span class="math inline">\(S = {\text{chocolate}, \text{vanilla}, \text{strawberry}}\)</span></p>
<p>If we record how often each flavor is chosen, we might estimate the following probabilities:</p>
<p>Flavor Probability:</p>
<ul>
<li><p>Chocolate <span class="math inline">\(P(\text{chocolate})=0.5\)</span></p></li>
<li><p>Vanilla <span class="math inline">\(P(\text{vanilla})=0.3\)</span></p></li>
<li><p>Strawberry <span class="math inline">\(P(\text{strawberry})=0.2\)</span></p></li>
</ul>
<p>These probabilities form a distribution. Each value lies between 0 and 1, and together they sum to 1.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-icecream-prob" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-icecream-prob-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.1: A simple probability distribution: the probabilities for three flavors must add to 1.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Non-elementary events</strong></p>
<p>We can also define events that group multiple outcomes.</p>
<p>For example, let <span class="math inline">\(A=\)</span> “not chocolate.” Then:</p>
<p><span class="math display">\[P(A) = P(vanilla) + P(strawberry)  = 0.5\]</span></p>
</section>
<section id="rules-of-probability" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="rules-of-probability"><span class="header-section-number">4.5</span> Rules of Probability</h2>
<p>Some basic rules follow from this framework. Let’s consider a sample space <span class="math inline">\(X\)</span> that consists of elementary events <span class="math inline">\(x\)</span>, and two non-elementary events, which we’ll call <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>.</p>
<p>Here are our rules:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">English</th>
<th style="text-align: left;">Notation</th>
<th style="text-align: left;">Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">not A</td>
<td style="text-align: left;"><span class="math inline">\(\neg A\)</span></td>
<td style="text-align: left;"><span class="math inline">\(P(\neg A) = 1 - P(A)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">A and B</td>
<td style="text-align: left;"><span class="math inline">\(A \cap B\)</span></td>
<td style="text-align: left;"><span class="math inline">\(P(A \cap B) = P(A\mid B)\,P(B) = P(B\mid A)\,P(A)\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">A or B</td>
<td style="text-align: left;"><span class="math inline">\(A \cup B\)</span></td>
<td style="text-align: left;"><span class="math inline">\(P(A \cup B) = P(A) + P(B) - P(A \cap B)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">A given B</td>
<td style="text-align: left;"><span class="math inline">\(A \mid B\)</span></td>
<td style="text-align: left;"><span class="math inline">\(P(A \mid B) = \dfrac{P(A \cap B)}{P(B)}\)</span></td>
</tr>
</tbody>
</table>
<p>These rules look abstract at first, but they are just formal ways of describing common-sense situations. Let’s work through them step by step with our ice cream example. We’ll assign probabilities to each flavor and then show how the rules play out with real numbers. That way, the notation is always tied to something you can picture.</p>
<p>Let’s add a fourth flavor and assign some probabilities:</p>
<p><strong>Flavor Probability:</strong> - Chocolate <span class="math inline">\(P(\text{chocolate})=0.4\)</span></p>
<ul>
<li><p>Vanilla <span class="math inline">\(P(\text{vanilla})=0.3\)</span></p></li>
<li><p>Strawberry <span class="math inline">\(P(\text{strawberry})=0.2\)</span></p></li>
<li><p>Rocky Road <span class="math inline">\(P(\text{rocky road})=0.1\)</span></p></li>
</ul>
<p>Notice these add to 1, as they must.</p>
<p>Now let’s revisit the rules with actual numbers. We’ll have two non-elementary events, <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, defined as:<br>
</p>
<p><span class="math inline">\(A = (\text{chocolate, vanilla, strawberry})\)</span></p>
<p><span class="math inline">\(B = (\text{chocolate, rocky road})\)</span></p>
<section id="not-a" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="not-a"><span class="header-section-number">4.5.1</span> <strong>Not</strong> <span class="math inline">\(A\)</span></h3>
<p><span class="math inline">\(A = (\text{chocolate, vanilla, strawberry})\)</span></p>
<p><span class="math inline">\(P(A) = 0.4 + 0.3 + 0.2 = 0.9\)</span></p>
<p>So, <span class="math inline">\(P(\neg A) = 1 - P(A) = 1 - 0.9 = 0.1\)</span></p>
<p><em>Explanation</em>: This adds up logically. The chance of <em>not</em> choosing chocolate, vanilla, or strawberry is equal to the chance of Rocky Road.</p>
</section>
<section id="a-and-b" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="a-and-b"><span class="header-section-number">4.5.2</span> <span class="math inline">\(A\)</span> <strong>and</strong> <span class="math inline">\(B\)</span></h3>
<p><em>Explanation</em>: The only overlap between <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> is chocolate: $A B = ()</p>
<p>So <span class="math inline">\(P(A \cap B) = 0.4\)</span></p>
</section>
<section id="a-or-b" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="a-or-b"><span class="header-section-number">4.5.3</span> <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span></h3>
</section>
<section id="a-cup-b-textchocolate-vanilla-strawberry-rocky-road" class="level3" data-number="4.5.4">
<h3 data-number="4.5.4" class="anchored" data-anchor-id="a-cup-b-textchocolate-vanilla-strawberry-rocky-road"><span class="header-section-number">4.5.4</span> <span class="math inline">\(A \cup B = (\text{chocolate, vanilla, strawberry, rocky road})\)</span></h3>
<p>In words, this emans, what’s the probability of choosing a flavor that’s in A or a flavor in B. Since our entire sample space is only 4 flavors, this is our whole sample space, so <span class="math inline">\(P(A \cup B)\)</span> = 1</p>
<p><strong>Conditional probability</strong></p>
<p>Suppose we want <span class="math inline">\(P(B|A)\)</span>: the probability of choosing <span class="math inline">\(B\)</span> (chocolate or rocky road) given that we already know the choice was from <span class="math inline">\(A\)</span> (chocolate, vanilla, strawberry). We know <span class="math inline">\(P(A \cap B)\)</span> and <span class="math inline">\(P(A)\)</span> from above.</p>
<p>By the rule, <span class="math inline">\(P(B|A) = \frac{P(A \cap B)}{P(A)} = \frac{0.4}{0.9} \approx 0.44\)</span></p>
<p><em>In words</em>: if you know someone picked from the “<span class="math inline">\(A\)</span> group” flavors, there’s about a 44% chance they chose chocolate (the only overlapping flavor).</p>
</section>
</section>
<section id="probaiblity-distributions" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="probaiblity-distributions"><span class="header-section-number">4.6</span> Probaiblity Distributions</h2>
<p>A <strong>probability distribution</strong> is a rule that assigns probabilities to all possible outcomes of a random variable. Many distributions exist, but this book mostly uses five: Binomial, Normal, <span class="math inline">\(t\)</span>, χ² (“chi-square”), and <span class="math inline">\(F\)</span>. We’ll focus on Binomial and Normal here; the others appear when we do inference.</p>
<p>For continuous distributions like the normal, probabilities work differently than in the discrete case. You cannot ask for the probability of one exact value (e.g., <span class="math inline">\(P(X = 23)\)</span>), because the answer is essentially zero. Instead, we calculate the probability of being in a <strong>range</strong>, such as <span class="math inline">\(22.5 \leq X \leq 23.5\)</span>.</p>
<p>This is why the <span class="math inline">\(y\)</span>-axis of a normal curve is labelled <strong>probability density</strong>. The height of the curve at a point, <span class="math inline">\(p(x)\)</span>, is not itself a probability. Instead, probabilities come from the <strong>area under the curve</strong> between two values. For example, about 68% of values from a standard normal fall between −1 and 1, because the area between −1 and 1 is 0.68.</p>
<p>In R, functions like <code>dnorm()</code> return the density (the curve’s height), while <code>pnorm()</code> and <code>qnorm()</code> work with cumulative probabilities and quantiles, which are usually more useful for applied problems.</p>
<section id="the-binomial-distribution" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="the-binomial-distribution"><span class="header-section-number">4.6.1</span> The binomial distribution</h3>
<p>The binomial distribution models the number of “successes” in a fixed number of independent trials.</p>
<ul>
<li>A trial is a single attempt with two possible outcomes (success or failure).</li>
<li>The success probability is the chance of success on any one trial, usually written as <span class="math inline">\(\theta\)</span>.</li>
<li>The size parameter <span class="math inline">\(N\)</span> is the number of trials.</li>
<li>The random variable <span class="math inline">\(X\)</span> is the number of successes observed in those <span class="math inline">\(N\)</span> trials.</li>
</ul>
<p>We write this as:</p>
<p><span class="math inline">\(X \sim \text{Binomial}(N, \theta)\)</span></p>
<p>For example, if you flip a fair coin 20 times (<span class="math inline">\(N=20\)</span>, <span class="math inline">\(\theta=0.5\)</span>), the binomial distribution tells you the probability of getting 0 heads, 1 head, 2 heads … all the way up to 20 heads. The bars of the distribution in <a href="#fig-binom">Figure&nbsp;<span>4.2</span></a> show the probability of each outcome, and the total always sums to 1.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-binom" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-binom-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.2: Binomial probabilities for X ~ Binomial(N = 20, θ = 0.5). Bars show P(X = x).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Two common queries</strong></p>
<ol type="1">
<li>To find the <em>exact probability</em> of getting 4 heads: <span class="math inline">\(P(X=4)\)</span></li>
</ol>
<div class="cell">
<pre><code>#&gt; [1] 0.004620552</code></pre>
</div>
<p>The probability is about <span class="math inline">\(0.5%\)</span>.</p>
<ol start="2" type="1">
<li>Find the <em>cumulative probability</em>. We specify a particular quantile q , and we get the probability of obtaining an outcome smaller than or equal to q.</li>
</ol>
<p>For <span class="math inline">\(P(X \le 4)\)</span>:</p>
<div class="cell">
<pre><code>#&gt; [1] 0.005908966</code></pre>
</div>
<p>The probability is about <span class="math inline">\(0.6%\)</span></p>
<p>The probability is slightly higher here, becuase it also includes hte probability we could get 3, 2, or 1 heads as well.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>R’s distribution helpers (for every distribution)</p>
<pre><code>•   d* = exact probability (PMF/PDF)
•   p* = cumulative probability P(X \le q)
•   q* = quantile (inverse of p*)
•   r* = random draws</code></pre>
<p>For binomial: dbinom, pbinom, qbinom, rbinom. For discrete distributions, some percentiles don’t exist exactly; qbinom returns the smallest x with P(X x) p.</p>
</div>
</div>
</section>
</section>
<section id="the-normal-distribution" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="the-normal-distribution"><span class="header-section-number">4.7</span> The normal distribution</h2>
<p>The normal distribution describes variables that can take on a wide range of values, clustered around a central point. The normal distribution is our most important distribution. It’s also sometimes called a Gaussian distribution or a bell curve.</p>
<ul>
<li>The mean <span class="math inline">\(\mu\)</span> is the center of the distribution.</li>
<li>The standard deviation <span class="math inline">\(\sigma\)</span> measures spread: how tightly or widely values are clustered around the mean.</li>
<li>The random variable <span class="math inline">\(X\)</span> represents the outcome, which can be any real number.</li>
</ul>
<p>We write this as:</p>
<p><span class="math inline">\(X \sim \text{Normal}(\mu, \sigma)\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-normal-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.3: Standard normal PDF (μ = 0, σ = 1). For continuous variables, probabilities are <em>areas</em> under the curve.</figcaption>
</figure>
</div>
</div>
</div>
<p>Changing <span class="math inline">\(\mu\)</span> shifts the curve left/right; changing <span class="math inline">\(\sigma\)</span> widens/narrows it (area always = 1).</p>
<p><strong>68–95–99.7 rule:</strong> - ~68% within 1σ, - ~95% within 2σ, - ~99.7% within 3σ.</p>
<p><strong>Important</strong>: In this distribution, our probability is the <em>area</em> (not height). For continuous distributions P(X = x) = 0; we compute <span class="math inline">\(P(a \le X \le b)\)</span> as the area under the curve between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. See <a href="#fig-normal-area">Figure&nbsp;<span>4.4</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-area" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-normal-area-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.4: Shaded area shows P(−1 ≤ X ≤ 1) ≈ 0.68 for X ~ Normal(0,1).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Two common queries</strong></p>
<ol type="1">
<li><pre><code>What is the probability that x is exactly, less than, or greater than, a given value? For example:</code></pre></li>
</ol>
<p><span class="math inline">\(P(X \le 1.64)\)</span> for <span class="math inline">\(X \sim \text{Normal}(0,1)\)</span></p>
<div class="cell">
<pre><code>#&gt; [1] 0.9494974</code></pre>
</div>
<p>In a normal distribution with a mean of 0 and standard deviation of 1, the probability the value is less than or equal to 1.64 is about 95%.</p>
<ol start="2" type="1">
<li>What value correspondds to the xx-th percentile in a given normal distribution?</li>
</ol>
<p>For example, what value corresponds to the 97.5th percentile?</p>
<div class="cell">
<pre><code>#&gt; [1] 1.959964</code></pre>
</div>
<p>Takeaway: For continuous variables, use areas (via pnorm/qnorm), not bar heights.</p>
<p>For example, suppose exam scores in a class are centered around 70 (<span class="math inline">\(\mu = 70\)</span>) with a standard deviation of 10 (<span class="math inline">\(\sigma = 10\)</span>). The normal distribution tells you how likely it is to see a score near 70, or further away (like 50 or 90). You can also find the score that correspnods to the 80th percentile, say.</p>
<p>Unlike the binomial, the normal distribution is continuous, any real number is possible, and probabilities are represented by the area under the smooth bell-shaped curve.</p>
</section>
<section id="summary-of-probability" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="summary-of-probability"><span class="header-section-number">4.8</span> Summary of Probability</h2>
<p>Summary: Probability</p>
<p>In this section we introduced the building blocks of probability, with an emphasis on the parts most relevant for statistics.</p>
<ul>
<li><p>What probability means: We use the frequentist view—probability as the long-run proportion of times an event occurs.</p></li>
<li><p>Distributions: A probability distribution assigns probabilities to all possible outcomes of a random variable. For discrete variables (like coin flips), probabilities are attached to each outcome; for continuous variables (like exam scores), probabilities come from areas under a curve.</p></li>
<li><p>Rules of probability: Complements, intersections (and), unions (or), and conditional probabilities all follow from the basic distribution framework.</p></li>
<li><p>Key distributions:</p>
<ul>
<li>Binomial—counts successes across <span class="math inline">\(N\)</span> independent trials.</li>
<li>Normal—describes continuous outcomes centered at a mean, with spread determined by the standard deviation.</li>
<li>Others (<span class="math inline">\(t\)</span>, <span class="math inline">\(\chi^2\)</span>, <span class="math inline">\(F\)</span>) appear later when we turn to inference.</li>
</ul></li>
</ul>
<p><strong>Takeaway</strong>: probability provides the language and tools that make statistical inference possible. Once we understand how outcomes behave under these distributions, we can ask questions about samples, uncertainty, and whether results are surprising enough to change what we believe about the world.</p>
</section>
<section id="samples-populations-and-sampling" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="samples-populations-and-sampling"><span class="header-section-number">4.9</span> Samples, populations and sampling</h2>
<p>Remember, the role of descriptive statistics is to concisely summarize what we <strong>do</strong> know. In contrast, the purpose of inferential statistics is to “learn what we do not know from what we do”. What kinds of things would we like to learn about? And how do we learn them? These are the questions that lie at the heart of inferential statistics, and they are traditionally divided into two “big ideas”: estimation and hypothesis testing. The goal in this chapter is to introduce the first of these big ideas, estimation theory, but we’ll talk about sampling theory first because estimation theory doesn’t make sense until you understand sampling. So, this chapter divides into sampling theory, and how to make use of sampling theory to discuss how statisticians think about estimation. We have already done lots of sampling, so you are already familiar with some of the big ideas.</p>
<p><strong>Sampling theory</strong> plays a huge role in specifying the assumptions upon which your statistical inferences rely. And in order to talk about “making inferences” the way statisticians think about it, we need to be a bit more explicit about what it is that we’re drawing inferences <strong>from</strong> (the sample) and what it is that we’re drawing inferences <strong>about</strong> (the population).</p>
<p>In almost every situation of interest, what we have available to us as researchers is a <strong>sample</strong> of data. We might have run experiment with some number of participants; a polling company might have phoned some number of people to ask questions about voting intentions; etc. Regardless: the data set available to us is finite, and incomplete. We can’t possibly get every person in the world to do our experiment; a polling company doesn’t have the time or the money to ring up every voter in the country etc. In our earlier discussion of descriptive statistics, this sample was the only thing we were interested in. Our only goal was to find ways of describing, summarizing and graphing that sample. This is about to change.</p>
<section id="defining-a-population" class="level3" data-number="4.9.1">
<h3 data-number="4.9.1" class="anchored" data-anchor-id="defining-a-population"><span class="header-section-number">4.9.1</span> Defining a population</h3>
<p>A sample is a concrete thing. You can open up a data file, and there’s the data from your sample. A <strong>population</strong>, on the other hand, is a more abstract idea. It refers to the set of all possible people, or all possible observations, that you want to draw conclusions about, and is generally <strong>much</strong> bigger than the sample. In an ideal world, the researcher would begin the study with a clear idea of what the population of interest is, since the process of designing a study and testing hypotheses about the data that it produces does depend on the population about which you want to make statements. However, that doesn’t always happen in practice: usually the researcher has a fairly vague idea of what the population is and designs the study as best he/she can on that basis.</p>
<p>Sometimes it’s easy to state the population of interest. For instance, in the “polling company” example, the population consisted of all voters enrolled at the a time of the study – millions of people. The sample was a set of 1000 people who all belong to that population. In most situations the situation is much less simple. In a typical a psychological experiment, determining the population of interest is a bit more complicated. Suppose I run an experiment using 100 undergraduate students as my participants. My goal, as a cognitive scientist, is to try to learn something about how the mind works. So, which of the following would count as “the population”:</p>
<ul>
<li><p>All of the undergraduate psychology students at the University of Adelaide?</p></li>
<li><p>Undergraduate psychology students in general, anywhere in the world?</p></li>
<li><p>Australians currently living?</p></li>
<li><p>Australians of similar ages to my sample?</p></li>
<li><p>Anyone currently alive?</p></li>
<li><p>Any human being, past, present or future?</p></li>
<li><p>Any biological organism with a sufficient degree of intelligence operating in a terrestrial environment?</p></li>
<li><p>Any intelligent being?</p></li>
</ul>
<p>Each of these defines a real group of mind-possessing entities, all of which might be of interest to me as a cognitive scientist, and it’s not at all clear which one ought to be the true population of interest.</p>
</section>
<section id="simple-random-samples" class="level3" data-number="4.9.2">
<h3 data-number="4.9.2" class="anchored" data-anchor-id="simple-random-samples"><span class="header-section-number">4.9.2</span> Simple random samples</h3>
<p>Irrespective of how we define the population, the critical point is that the sample is a subset of the population, and our goal is to use our knowledge of the sample to draw inferences about the properties of the population. The relationship between the two depends on the <strong>procedure</strong> by which the sample was selected. This procedure is referred to as a <strong>sampling method</strong>, and it is important to understand why it matters.</p>
<p>To keep things simple, imagine we have a bag containing 10 chips. Each chip has a unique letter printed on it, so we can distinguish between the 10 chips. The chips come in two colors, black and white.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-srs1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/navarro_img/estimation/srs1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.5: Simple random sampling without replacement from a finite population</figcaption>
</figure>
</div>
</div>
</div>
<p>This set of chips is the population of interest, and it is depicted graphically on the left of <a href="#fig-srs1">Figure&nbsp;<span>4.5</span></a>.</p>
<p>As you can see from looking at the picture, there are 4 black chips and 6 white chips, but of course in real life we wouldn’t know that unless we looked in the bag. Now imagine you run the following “experiment”: you shake up the bag, close your eyes, and pull out 4 chips without putting any of them back into the bag. First out comes the <span class="math inline">\(a\)</span> chip (black), then the <span class="math inline">\(c\)</span> chip (white), then <span class="math inline">\(j\)</span> (white) and then finally <span class="math inline">\(b\)</span> (black). If you wanted, you could then put all the chips back in the bag and repeat the experiment, as depicted on the right hand side of <a href="#fig-srs1">Figure&nbsp;<span>4.5</span></a>. Each time you get different results, but the procedure is identical in each case. The fact that the same procedure can lead to different results each time, we refer to it as a <strong>random</strong> process. However, because we shook the bag before pulling any chips out, it seems reasonable to think that every chip has the same chance of being selected. A procedure in which every member of the population has the same chance of being selected is called a <strong>simple random sample</strong>. The fact that we did <strong>not</strong> put the chips back in the bag after pulling them out means that you can’t observe the same thing twice, and in such cases the observations are said to have been sampled <strong>without replacement</strong>.</p>
<p>To help make sure you understand the importance of the sampling procedure, consider an alternative way in which the experiment could have been run. Suppose that my 5-year old son had opened the bag, and decided to pull out four black chips without putting any of them back in the bag. This <strong>biased</strong> sampling scheme is depicted in <a href="#fig-brs">Figure&nbsp;<span>4.6</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-brs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/navarro_img/estimation/brs.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.6: Biased sampling without replacement from a finite populations.</figcaption>
</figure>
</div>
</div>
</div>
<p>Now consider the evidentiary value of seeing 4 black chips and 0 white chips. Clearly, it depends on the sampling scheme, does it not? If you know that the sampling scheme is biased to select only black chips, then a sample that consists of only black chips doesn’t tell you very much about the population! For this reason, statisticians really like it when a data set can be considered a simple random sample, because it makes the data analysis <strong>much</strong> easier.</p>
<p>A third procedure is worth mentioning. This time around we close our eyes, shake the bag, and pull out a chip. This time, however, we record the observation and then put the chip back in the bag. Again we close our eyes, shake the bag, and pull out a chip. We then repeat this procedure until we have 4 chips. Data sets generated in this way are still simple random samples, but because we put the chips back in the bag immediately after drawing them it is referred to as a sample <strong>with replacement</strong>. The difference between this situation and the first one is that it is possible to observe the same population member multiple times, as illustrated in <a href="#fig-srs2">Figure&nbsp;<span>4.7</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-srs2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/navarro_img/estimation/srs2.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.7: Simple random sampling with replacement from a finite population.</figcaption>
</figure>
</div>
</div>
</div>
<p>Most psychology experiments tend to be sampling without replacement, because the same person is not allowed to participate in the experiment twice. However, most statistical theory is based on the assumption that the data arise from a simple random sample <strong>with</strong> replacement. In real life, this very rarely matters. If the population of interest is large (e.g., has more than 10 entities!) the difference between sampling with- and without- replacement is too small to be concerned with. The difference between simple random samples and biased samples, on the other hand, is not such an easy thing to dismiss.</p>
</section>
<section id="most-samples-are-not-simple-random-samples" class="level3" data-number="4.9.3">
<h3 data-number="4.9.3" class="anchored" data-anchor-id="most-samples-are-not-simple-random-samples"><span class="header-section-number">4.9.3</span> Most samples are not simple random samples</h3>
<p>As you can see from looking at the list of possible populations that I showed above, it is almost impossible to obtain a simple random sample from most populations of interest. When I run experiments, I’d consider it a minor miracle if my participants turned out to be a random sampling of the undergraduate psychology students at Adelaide university, even though this is by far the narrowest population that I might want to generalize to. A thorough discussion of other types of sampling schemes is beyond the scope of this book, but to give you a sense of what’s out there I’ll list a few of the more important ones:</p>
<ul>
<li><p><strong>Stratified sampling</strong>. Suppose your population is (or can be) divided into several different sub-populations, or <strong>strata</strong>. Perhaps you’re running a study at several different sites, for example. Instead of trying to sample randomly from the population as a whole, you instead try to collect a separate random sample from each of the strata. Stratified sampling is sometimes easier to do than simple random sampling, especially when the population is already divided into the distinct strata. It can also be more efficient that simple random sampling, especially when some of the sub-populations are rare. For instance, when studying schizophrenia it would be much better to divide the population into two strata (schizophrenic and not-schizophrenic), and then sample an equal number of people from each group. If you selected people randomly, you would get so few schizophrenic people in the sample that your study would be useless. This specific kind of of stratified sampling is referred to as <strong>oversampling</strong> because it makes a deliberate attempt to over-represent rare groups.</p></li>
<li><p><strong>Snowball sampling</strong> is a technique that is especially useful when sampling from a “hidden” or hard to access population, and is especially common in social sciences. For instance, suppose the researchers want to conduct an opinion poll among transgender people. The research team might only have contact details for a few trans folks, so the survey starts by asking them to participate (stage 1). At the end of the survey, the participants are asked to provide contact details for other people who might want to participate. In stage 2, those new contacts are surveyed. The process continues until the researchers have sufficient data. The big advantage to snowball sampling is that it gets you data in situations that might otherwise be impossible to get any. On the statistical side, the main disadvantage is that the sample is highly non-random, and non-random in ways that are difficult to address. On the real life side, the disadvantage is that the procedure can be unethical if not handled well, because hidden populations are often hidden for a reason. I chose transgender people as an example here to highlight this: if you weren’t careful you might end up outing people who don’t want to be outed (very, very bad form), and even if you don’t make that mistake it can still be intrusive to use people’s social networks to study them. It’s certainly very hard to get people’s informed consent <strong>before</strong> contacting them, yet in many cases the simple act of contacting them and saying “hey we want to study you” can be hurtful. Social networks are complex things, and just because you can use them to get data doesn’t always mean you should.</p></li>
<li><p><strong>Convenience sampling</strong> is more or less what it sounds like. The samples are chosen in a way that is convenient to the researcher, and not selected at random from the population of interest. Snowball sampling is one type of convenience sampling, but there are many others. A common example in psychology are studies that rely on undergraduate psychology students. These samples are generally non-random in two respects: firstly, reliance on undergraduate psychology students automatically means that your data are restricted to a single sub-population. Secondly, the students usually get to pick which studies they participate in, so the sample is a self selected subset of psychology students not a randomly selected subset. In real life, most studies are convenience samples of one form or another. This is sometimes a severe limitation, but not always.</p></li>
</ul>
</section>
<section id="how-much-does-it-matter-if-you-dont-have-a-simple-random-sample" class="level3" data-number="4.9.4">
<h3 data-number="4.9.4" class="anchored" data-anchor-id="how-much-does-it-matter-if-you-dont-have-a-simple-random-sample"><span class="header-section-number">4.9.4</span> How much does it matter if you don’t have a simple random sample?</h3>
<p>Okay, so real world data collection tends not to involve nice simple random samples. Does that matter? A little thought should make it clear to you that it <strong>can</strong> matter if your data are not a simple random sample: just think about the difference between <a href="#fig-srs1">Figure&nbsp;<span>4.5</span></a> and <a href="#fig-brs">Figure&nbsp;<span>4.6</span></a>. However, it’s not quite as bad as it sounds. Some types of biased samples are entirely unproblematic. For instance, when using a stratified sampling technique you actually <strong>know</strong> what the bias is because you created it deliberately, often to <strong>increase</strong> the effectiveness of your study, and there are statistical techniques that you can use to adjust for the biases you’ve introduced (not covered in this book!). So in those situations it’s not a problem.</p>
<p>More generally though, it’s important to remember that random sampling is a means to an end, not the end in itself. Let’s assume you’ve relied on a convenience sample, and as such you can assume it’s biased. A bias in your sampling method is only a problem if it causes you to draw the wrong conclusions. When viewed from that perspective, I’d argue that we don’t need the sample to be randomly generated in <strong>every</strong> respect: we only need it to be random with respect to the psychologically-relevant phenomenon of interest. Suppose I’m doing a study looking at working memory capacity. In study 1, I actually have the ability to sample randomly from all human beings currently alive, with one exception: I can only sample people born on a Monday. In study 2, I am able to sample randomly from the Australian population. I want to generalize my results to the population of all living humans. Which study is better? The answer, obviously, is study 1. Why? Because we have no reason to think that being “born on a Monday” has any interesting relationship to working memory capacity. In contrast, I can think of several reasons why “being Australian” might matter. Australia is a wealthy, industrialized country with a very well-developed education system. People growing up in that system will have had life experiences much more similar to the experiences of the people who designed the tests for working memory capacity. This shared experience might easily translate into similar beliefs about how to “take a test”, a shared assumption about how psychological experimentation works, and so on. These things might actually matter. For instance, “test taking” style might have taught the Australian participants how to direct their attention exclusively on fairly abstract test materials relative to people that haven’t grown up in a similar environment; leading to a misleading picture of what working memory capacity is.</p>
<p>There are two points hidden in this discussion. Firstly, when designing your own studies, it’s important to think about what population you care about, and try hard to sample in a way that is appropriate to that population. In practice, you’re usually forced to put up with a “sample of convenience” (e.g., psychology lecturers sample psychology students because that’s the least expensive way to collect data, and our coffers aren’t exactly overflowing with gold), but if so you should at least spend some time thinking about what the dangers of this practice might be.</p>
<p>Secondly, if you’re going to criticize someone else’s study because they’ve used a sample of convenience rather than laboriously sampling randomly from the entire human population, at least have the courtesy to offer a specific theory as to <strong>how</strong> this might have distorted the results. Remember, everyone in science is aware of this issue, and does what they can to alleviate it. Merely pointing out that “the study only included people from group BLAH” is entirely unhelpful, and borders on being insulting to the researchers, who are aware of the issue. They just don’t happen to be in possession of the infinite supply of time and money required to construct the perfect sample. In short, if you want to offer a responsible critique of the sampling process, then be <strong>helpful</strong>. Rehashing the blindingly obvious truisms that I’ve been rambling on about in this section isn’t helpful.</p>
</section>
<section id="population-parameters-and-sample-statistics" class="level3" data-number="4.9.5">
<h3 data-number="4.9.5" class="anchored" data-anchor-id="population-parameters-and-sample-statistics"><span class="header-section-number">4.9.5</span> Population parameters and sample statistics</h3>
<p>Okay. Setting aside the thorny methodological issues associated with obtaining a random sample, let’s consider a slightly different issue. Up to this point we have been talking about populations the way a scientist might. To a psychologist, a population might be a group of people. To an ecologist, a population might be a group of bears. In most cases the populations that scientists care about are concrete things that actually exist in the real world.</p>
<p>Statisticians, however, are a funny lot. On the one hand, they <strong>are</strong> interested in real world data and real science in the same way that scientists are. On the other hand, they also operate in the realm of pure abstraction in the way that mathematicians do. As a consequence, statistical theory tends to be a bit abstract in how a population is defined. In much the same way that psychological researchers operationalize our abstract theoretical ideas in terms of concrete measurements, statisticians operationalize the concept of a “population” in terms of mathematical objects that they know how to work with. You’ve already come across these objects they’re called probability distributions (remember, the place where data comes from).</p>
<p>The idea is quite simple. Let’s say we’re talking about IQ scores. To a psychologist, the population of interest is a group of actual humans who have IQ scores. A statistician “simplifies” this by operationally defining the population as the probability distribution depicted in <a href="#fig-IQdist">Figure&nbsp;<span>4.8</span></a> <span class="math inline">\(a\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-IQdist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/figures/navIQ.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.8: The population distribution of IQ scores (panel a) and two samples drawn randomly from it. In panel b we have a sample of 100 observations, and panel c we have a sample of 10,000 observations.</figcaption>
</figure>
</div>
</div>
</div>
<p>IQ tests are designed so that the average IQ is 100, the standard deviation of IQ scores is 15, and the distribution of IQ scores is normal. These values are referred to as the <strong>population parameters</strong> because they are characteristics of the entire population. That is, we say that the population mean <span class="math inline">\(\mu\)</span> is 100, and the population standard deviation <span class="math inline">\(\sigma\)</span> is 15.</p>
<p>Now suppose we collect some data. We select 100 people at random and administer an IQ test, giving a simple random sample from the population. The sample would consist of a collection of numbers like this:</p>
<p><code>106 101 98 80 74 ... 107 72 100</code></p>
<p>Each of these IQ scores is sampled from a normal distribution with mean 100 and standard deviation 15. So if I plot a histogram of the sample, I get something like the one shown in <a href="#fig-IQdist">Figure&nbsp;<span>4.8</span></a> <span class="math inline">\(b\)</span>. As you can see, the histogram is <strong>roughly</strong> the right shape, but it’s a very crude approximation to the true population distribution shown in <a href="#fig-IQdist">Figure&nbsp;<span>4.8</span></a> <span class="math inline">\(a\)</span>. The mean of the sample is fairly close to the population mean 100 but not identical. In this case, it turns out that the people in the sample have a mean IQ of 98.5, and the standard deviation of their IQ scores is 15.9. These <strong>sample statistics</strong> are properties of the data set, and although they are fairly similar to the true population values, they are not the same. <strong>In general, sample statistics are the things you can calculate from your data set, and the population parameters are the things you want to learn about.</strong> Later on in this chapter we’ll talk about how you can estimate population parameters using your sample statistics and how to work out how confident you are in your estimates but before we get to that there’s a few more ideas in sampling theory that you need to know about.</p>
</section>
</section>
<section id="the-law-of-large-numbers" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="the-law-of-large-numbers"><span class="header-section-number">4.10</span> The law of large numbers</h2>
<p>We just looked at the results of one fictitious IQ experiment with a sample size of <span class="math inline">\(N=100\)</span>. The results were somewhat encouraging: the true population mean is 100, and the sample mean of 98.5 is a pretty reasonable approximation to it. In many scientific studies that level of precision is perfectly acceptable, but in other situations you need to be a lot more precise. If we want our sample statistics to be much closer to the population parameters, what can we do about it?</p>
<p>The obvious answer is to collect more data. Suppose that we ran a much larger experiment, this time measuring the IQ’s of 10,000 people. We can simulate the results of this experiment using R, using the <strong>rnorm()</strong> function, which generates random numbers sampled from a normal distribution. For an experiment with a sample size of <strong>n = 10000</strong>, and a population with <strong>mean = 100</strong> and <strong>sd = 15</strong>, R produces our fake IQ data using these commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>IQ <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">10000</span>, <span class="at">mean=</span><span class="dv">100</span>, <span class="at">sd=</span><span class="dv">15</span>) <span class="co">#generate IQ scores</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>IQ <span class="ot">&lt;-</span> <span class="fu">round</span>(IQ) <span class="co"># make round numbers</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cool, we just generated 10,000 fake IQ scores. Where did they go? Well, they went into the variable IQ on my computer. You can do the same on your computer too by copying the above code. 10,000 numbers is too many numbers to look at. We can look at the first 100 like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(IQ[<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>])</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   [1] 115  79  90  89 112 108  96 101  87  71  93  86  93 103  93 101  81  91</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [19]  77 103 104  92  86  97  79  95 126  89  99  84 112 108  92  78 109 113</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [37] 109  86  88 116 102  87 108  96  99  90  85  95  92 110 121  77  89 106</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [55]  98  77 116 126 103 104 113  89 118  85 111  95 118  92  94  87 105 101</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [73]  96 114 105  78  90  83 107  83  92 115  96  85 117  97  60  97  92 121</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [91] 118 109 125  71 111  84 124  95  90 102</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can compute the mean IQ using the command <strong>mean(IQ)</strong> and the standard deviation using the command <strong>sd(IQ)</strong>, and draw a histogram using <strong>hist()</strong>. The histogram of this much larger sample is shown in Figure @ref(fig:IQdist)c.&nbsp;Even a moment’s inspections makes clear that the larger sample is a much better approximation to the true population distribution than the smaller one. This is reflected in the sample statistics: the mean IQ for the larger sample turns out to be 99.9, and the standard deviation is 15.1. These values are now very close to the true population.</p>
<p>I feel a bit silly saying this, but the thing I want you to take away from this is that large samples generally give you better information. I feel silly saying it because it’s so bloody obvious that it shouldn’t need to be said. In fact, it’s such an obvious point that when Jacob Bernoulli – one of the founders of probability theory – formalized this idea back in 1713, he was kind of a jerk about it. Here’s how he described the fact that we all share this intuition:</p>
<blockquote class="blockquote">
<p><strong>For even the most stupid of men, by some instinct of nature, by himself and without any instruction (which is a remarkable thing), is convinced that the more observations have been made, the less danger there is of wandering from one’s goal</strong> (see Stigler, 1986, p65).</p>
</blockquote>
<p>Okay, so the passage comes across as a bit condescending (not to mention sexist), but his main point is correct: it really does feel obvious that more data will give you better answers. The question is, why is this so? Not surprisingly, this intuition that we all share turns out to be correct, and statisticians refer to it as the <strong>law of large numbers</strong>. The law of large numbers is a mathematical law that applies to many different sample statistics, but the simplest way to think about it is as a law about averages. The sample mean is the most obvious example of a statistic that relies on averaging (because that’s what the mean is… an average), so let’s look at that. <strong>When applied to the sample mean, what the law of large numbers states is that as the sample gets larger, the sample mean tends to get closer to the true population mean.</strong> Or, to say it a little bit more precisely, as the sample size “approaches” infinity (written as <span class="math inline">\(N \rightarrow \infty\)</span>) the sample mean approaches the population mean (<span class="math inline">\(\bar{X} \rightarrow \mu\)</span>).</p>
<p>I don’t intend to subject you to a proof that the law of large numbers is true, but it’s one of the most important tools for statistical theory. The law of large numbers is the thing we can use to justify our belief that collecting more and more data will eventually lead us to the truth. For any particular data set, the sample statistics that we calculate from it will be wrong, but the law of large numbers tells us that if we keep collecting more data those sample statistics will tend to get closer and closer to the true population parameters.</p>
</section>
<section id="sampling-distributions-and-the-central-limit-theorem" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="sampling-distributions-and-the-central-limit-theorem"><span class="header-section-number">4.11</span> Sampling distributions and the central limit theorem</h2>
<p>The law of large numbers is a very powerful tool, but it’s not going to be good enough to answer all our questions. Among other things, all it gives us is a “long run guarantee”. In the long run, if we were somehow able to collect an infinite amount of data, then the law of large numbers guarantees that our sample statistics will be correct. But as John Maynard Keynes famously argued in economics, a long run guarantee is of little use in real life:</p>
<blockquote class="blockquote">
<p>[**The] long run is a misleading guide to current affairs. In the long run we are all dead. Economists set themselves too easy, too useless a task, if in tempestuous seasons they can only tell us, that when the storm is long past, the ocean is flat again.** <span class="citation" data-cites="Keynes1923">Keynes (<a href="references.html#ref-Keynes1923" role="doc-biblioref">1923, 80</a>)</span></p>
</blockquote>
<p>As in economics, so too in psychology and statistics. It is not enough to know that we will <strong>eventually</strong> arrive at the right answer when calculating the sample mean. Knowing that an infinitely large data set will tell me the exact value of the population mean is cold comfort when my <strong>actual</strong> data set has a sample size of <span class="math inline">\(N=100\)</span>. In real life, then, we must know something about the behavior of the sample mean when it is calculated from a more modest data set!</p>
<section id="sampling-distribution-of-the-sample-means" class="level3" data-number="4.11.1">
<h3 data-number="4.11.1" class="anchored" data-anchor-id="sampling-distribution-of-the-sample-means"><span class="header-section-number">4.11.1</span> Sampling distribution of the sample means</h3>
<p>“Oh no, what is the sample distribution of the sample means? Is that even allowed in English?”. Yes, unfortunately, this is allowed. The <strong>sampling distribution of the sample means</strong> is the next most important thing you will need to understand. IT IS SO IMPORTANT THAT IT IS NECESSARY TO USE ALL CAPS. It is only confusing at first because it’s long and uses sampling and sample in the same phrase.</p>
<p>Don’t worry, we’ve been prepping you for this. You know what a distribution is right? It’s where numbers comes from. It makes some numbers occur more or less frequently, or the same as other numbers. You know what a sample is right? It’s the numbers we take from a distribution. So, what could the sampling distribution of the sample means refer to?</p>
<p>First, what do you think the sample means refers to? Well, if you took a sample of numbers, you would have a bunch of numbers…then, you could compute the mean of those numbers. The sample mean is the mean of the numbers in the sample. That is all. So, what is this distribution you speak of? Well, what if you took a bunch of samples, put one here, put one there, put some other ones other places. You have a lot of different samples of numbers. You could compute the mean for each them. Then you would have a bunch of means. What do those means look like? Well, if you put them in a histogram, you could find out. If you did that, you would be looking at (roughly) a distribution, AKA <strong>the sampling distribution of the sample means</strong>.</p>
<p>“I’m following along sort of, why would I want to do this instead of watching Netflix…”. Because, the sampling distribution of the sample means gives you another window into chance. A very useful one that you can control, just like your remote control, by pressing the right design buttons.</p>
</section>
<section id="seeing-the-pieces" class="level3" data-number="4.11.2">
<h3 data-number="4.11.2" class="anchored" data-anchor-id="seeing-the-pieces"><span class="header-section-number">4.11.2</span> Seeing the pieces</h3>
<p>To make a sampling distribution of the sample means, we just need the following:</p>
<ol type="1">
<li>A distribution to take numbers from</li>
<li>A bunch of different samples from the distribution</li>
<li>The means of each of the samples</li>
<li>Get all of the sample means, and plot them in a histogram</li>
</ol>
<hr>
<p>Question for yourself: What do you think the sampling distribution of the sample means will look like? Will it tend to look the shape of the distribution that the samples came from? Or not? Good question, think about it.</p>
<hr>
<p>Let’s do those four things. We will sample numbers from the uniform distribution. <a href="#fig-4Unif">Figure&nbsp;<span>4.9</span></a> shows the uniform distribution for sampling the set of integers from 1 to 10:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4Unif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-4Unif-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.9: A uniform distribution illustrating the probabilites of sampling the numbers 1 to 10. In a uniform distribution, all numbers have an equal probability of being sampled, so the line is flat indicating all numbers have the same probability</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-4sample20unif">Figure&nbsp;<span>4.10</span></a> animates the process of taking a bunch of samples from the uniform distribution. We will set our sample-size to 20. It’s easier to see how the sample mean behaves in a movie. Each histogram shows a new sample. The red line shows where the mean of the sample is. The samples are all very different from each other, but the red line doesn’t move around very much, it always stays near the middle. However, the red line does move around a little bit, and this variance is what we call the sampling distribution of the sample mean.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4sample20unif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/sampleHistUnif-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.10: Animiation showing histograms for different samples of size 20 from the uniform distribution. The red line shows the mean of each sample.</figcaption>
</figure>
</div>
</div>
</div>
<p>OK, what have we got here? We have an animation of 10 different samples. Each sample has 20 observations and these are summarized in each of histograms that show up in the animation. Each histogram has a red line. The red line shows you where the mean of each sample is located. So, we have found the sample means for the 10 different samples from a uniform distribution.</p>
<p>First question. Are the sample means all the same? The answer is no. They are all kind of similar to each other though, they are all around five plus or minus a few numbers. This is interesting. Although all of our samples look pretty different from one another, the means of our samples look more similar than different.</p>
<p>Second question. What should we do with the means of our samples? Well, how about we collect them them all, and then plot a histogram of them. This would allow us to see what the distribution of the sample means looks like. The next histogram is just this. Except, rather than taking 10 samples, we will take 10,000 samples. For each of them we will compute the means. So, we will have 10,000 means. <a href="#fig-4unifmany">Figure&nbsp;<span>4.11</span></a> shows the histogram of the sample means:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4unifmany" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-4unifmany-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.11: A histogram showing the sample means for 10,000 samples, each size 20, from the uniform distribution of numbers from 1 to 10. The expected mean is 5.5, and the histogram is centered on 5.5. The mean of each sample is not always 5.5 because of sampling error or chance</figcaption>
</figure>
</div>
</div>
</div>
<p>“Wait what? This doesn’t look right. I thought we were taking samples from a uniform distribution. Uniform distributions are flat. THIS DOES NOT LOOK LIKE A FLAT DISTRIBTUION, WHAT IS GOING ON, AAAAAGGGHH.”. We feel your pain.</p>
<p>Remember, we are looking at the distribution of sample means. It is indeed true that the distribution of sample means does not look the same as the distribution we took the samples from. Our distribution of sample means goes up and down. In fact, this will almost always be the case for distributions of sample means. This fact is called the <strong>central limit theorem</strong>, which we talk about later.</p>
<p>For now, let’s talk about about what’s happening. Remember, we have been sampling numbers between the range 1 to 10. We are supposed to get each number with roughly equal frequency, because we are sampling from a uniform distribution. So, let’s say we took a sample of 10 numbers, and happened to get one of each from 1 to 10.</p>
<p><code>1 2 3 4 5 6 7 8 9 10</code></p>
<p>What is the mean of those numbers? Well, its 1+2+3+4+5+6+7+8+9+10 = 55 / 10 = 5.5. Imagine if we took a bigger sample, say of 20 numbers, and again we got exactly 2 of each number. What would the mean be? It would be (1+2+3+4+5+6+7+8+9+10)*2 = 110 / 20 = 5.5. Still 5.5. You can see here, that the mean value of our uniform distribution is 5.5. Now that we know this, we might expect that most of our samples will have a mean near this number. We already know that every sample won’t be perfect, and it won’t have exactly an equal amount of every number. So, we will expect the mean of our samples to vary a little bit. The histogram that we made shows the variation. Not surprisingly, the numbers vary around the value 5.5.</p>
</section>
<section id="sampling-distributions-exist-for-any-sample-statistic" class="level3" data-number="4.11.3">
<h3 data-number="4.11.3" class="anchored" data-anchor-id="sampling-distributions-exist-for-any-sample-statistic"><span class="header-section-number">4.11.3</span> Sampling distributions exist for any sample statistic!</h3>
<p>One thing to keep in mind when thinking about sampling distributions is that <strong>any</strong> sample statistic you might care to calculate has a sampling distribution. For example, suppose that each time you sampled some numbers from an experiment you wrote down the largest number in the experiment. Doing this over and over again would give you a very different sampling distribution, namely the <strong>sampling distribution of the maximum</strong>. You could calculate the smallest number, or the mode, or the median, of the variance, or the standard deviation, or anything else from your sample. Then, you could repeat many times, and produce the sampling distribution of those statistics. Neat!</p>
<p>Just for fun here are some different sampling distributions for different statistics. We will take a normal distribution with mean = 100, and standard deviation =20. Then, we’ll take lots of samples with n = 50 (50 observations per sample). We’ll save all of the sample statistics, then plot their histograms in <a href="#fig-4samplestats">Figure&nbsp;<span>4.12</span></a>. Let’s do it:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4samplestats" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-4samplestats-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.12: Each panel shows a histogram of a different sampling statistic</figcaption>
</figure>
</div>
</div>
</div>
<p>We just computed 4 different sampling distributions, for the mean, standard deviation, maximum value, and the median. If you just look quickly at these histograms you might think they all basically look the same. Hold up now. It’s very important to look at the x-axes. They are different. For example, the sample mean goes from about 90 to 110, whereas the standard deviation goes from 15 to 25.</p>
<p>These sampling distributions are super important, and worth thinking about. What should you think about? Well, here’s a clue. These distributions are telling you what to expect from your sample. Critically, they are telling you what you should expect from a sample, when you take one from the specific distribution that we used (normal distribution with mean =100 and SD = 20). What have we learned. We’ve learned a tonne. We’ve learned that we can expect our sample to have a mean somewhere between 90 and 108ish. Notice, the sample means are never more extreme. We’ve learned that our sample will usually have some variance, and that the the standard deviation will be somewhere between 15 and 25 (never much more extreme than that). We can see that sometime we get some big numbers, say between 120 and 180, but not much bigger than that. And, we can see that the median is pretty similar to the mean. If you ever took a sample of 50 numbers, and your descriptive statistics were inside these windows, then perhaps they came from this kind of normal distribution. If your sample statistics are very different, then your sample probably did not come this distribution. By using simulation, we can find out what samples look like when they come from distributions, and we can use this information to make inferences about whether our sample came from particular distributions.</p>
</section>
</section>
<section id="the-central-limit-theorem" class="level2" data-number="4.12">
<h2 data-number="4.12" class="anchored" data-anchor-id="the-central-limit-theorem"><span class="header-section-number">4.12</span> The central limit theorem</h2>
<p>OK, so now you’ve seen lots of sampling distributions, and you know what the sampling distribution of the mean is. Here, we’ll focus on <strong>how the sampling distribution of the mean changes as a function of sample size.</strong></p>
<p>Intuitively, you already know part of the answer: if you only have a few observations, the sample mean is likely to be quite inaccurate (you’ve already seen it bounce around): if you replicate a small experiment and recalculate the mean you’ll get a very different answer. In other words, the sampling distribution is quite wide. If you replicate a large experiment and recalculate the sample mean you’ll probably get the same answer you got last time, so the sampling distribution will be very narrow.</p>
<p>Let’s give ourselves a nice movie to see everything in action. We’re going to sample numbers from a normal distribution. <a href="#fig-4samplingmean">Figure&nbsp;<span>4.13</span></a> has four panels, each panel represents a different sample size (n), including sample-sizes of 10, 50, 100, and 1000. The red line shows the shape of the normal distribution. The grey bars show a histogram of each of the samples that we take. The red line shows the mean of an individual sample (the middle of the grey bars). As you can see, the red line moves around a lot, especially when the sample size is small (10).</p>
<p>The new bits are the blue bars and the blue lines. The blue bars represent the sampling distribution of the sample mean. For example, in the panel for sample-size 10, we see a bunch of blue bars. This is a histogram of 10 sample means, taken from 10 samples of size 10. In the 50 panel, we see a histogram of 50 sample means, taken from 50 samples of size 50, and so on. The blue line in each panel is the mean of the sample means (“aaagh, it’s a mean of means”, yes it is).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4samplingmean" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/sampleDistNormal-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.13: Animation of samples (grey histogram shows frequency counts of data in each sample), and the sampling distribution of the mean (histogram of the sampling means for many samples). Each sample is taken from the normal distribution shown in red. The moving red line is the mean of an individual sample. The blue line is the mean of the blue histogram, which represents the sampling distribution of the mean for many samples</figcaption>
</figure>
</div>
</div>
</div>
<p>What should you notice? Notice that the range of the blue bars shrinks as sample size increases. The sampling distribution of the mean is quite wide when the sample-size is 10, it narrows as sample-size increases to 50 and 100, and it’s just one bar, right in the middle when sample-size goes to 1000. What we are seeing is that the mean of the sampling distribution approaches the mean of the population as sample-size increases.</p>
<p>So, the sampling distribution of the mean is another distribution, and it has some variance. It varies more when sample-size is small, and varies less when sample-size is large. We can quantify this effect by calculating the standard deviation of the sampling distribution, which is referred to as the <strong>standard error</strong>. The standard error of a statistic is often denoted SE, and since we’re usually interested in the standard error of the sample <strong>mean</strong>, we often use the acronym SEM. As you can see just by looking at the movie, as the sample size <span class="math inline">\(N\)</span> increases, the SEM decreases.</p>
<p>Okay, so that’s one part of the story. However, there’s something we’ve been glossing over a little bit. We’ve seen it already, but it’s worth looking at it one more time. Here’s the thing: <strong>no matter what shape your population distribution is</strong>, as <span class="math inline">\(N\)</span> increases the sampling distribution of the mean starts to look more like a normal distribution. This is the central limit theorem.</p>
<p>To see the central limit theorem in action, we are going to look at some histograms of sample means from different kinds of distributions. It is very important to recognize that you are looking at distributions of sample means, not distributions of individual samples.</p>
<p>Here we go, <a href="#fig-4sampledistmeannorm">Figure&nbsp;<span>4.14</span></a> shows sampling from a normal distribution. The red line is the normal distribution where each sample is drawn from. The mean for each sample of numbers is computed, and the distribution of sample means is shown by the blue bars. Note that the shape of red line and the blue bars are similar, they both look like a normal distribution.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4sampledistmeannorm" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-4sampledistmeannorm-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.14: Comparison of two normal distributions, and histograms for the sampling distribution of the mean for different samples-sizes. The range of sampling distribution of the mean shrinks as sample-size increases</figcaption>
</figure>
</div>
</div>
</div>
<p>Let’s do it again. This time we will sample from a flat uniform distribution shown by the red line. However, <a href="#fig-4samplemeanunif">Figure&nbsp;<span>4.15</span></a> shows the distribution of sample means represented by the blue bars is not flat, it looks like a normal distribution.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4samplemeanunif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-4samplemeanunif-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.15: Illustration that the shape of the sampling distribution of the mean is normal, even when the samples come from a non-normal (uniform in this case) distribution</figcaption>
</figure>
</div>
</div>
</div>
<p>One more time with an exponential distribution (shown in red) where smaller numbers are more likely to be sampled than larger numbers. Even though way more of the numbers in a given sample will be smaller than larger, according to <a href="#fig-4samplemeanExp">Figure&nbsp;<span>4.16</span></a> the sampling distribution of the mean does not look the red line. Instead, the sampling distribution of the mean looks like a bell-shaped normal curve. This is the central limit theorem in action.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4samplemeanExp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-4samplemeanExp-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.16: Illustration that the shape of the sampling distribution of the mean is normal, even when the samples come from an exponential distribution</figcaption>
</figure>
</div>
</div>
</div>
<p>On the basis of these figures, it seems like we have evidence for all of the following claims about the sampling distribution of the mean:</p>
<ul>
<li><p>The mean of the sampling distribution is the same as the mean of the population</p></li>
<li><p>The standard deviation of the sampling distribution (i.e., the standard error) gets smaller as the sample size increases</p></li>
<li><p>The shape of the sampling distribution becomes normal as the sample size increases</p></li>
</ul>
<p>As it happens, not only are all of these statements true, there is a very famous theorem in statistics that proves all three of them, known as the <strong>central limit theorem</strong>. Among other things, the central limit theorem tells us that if the population distribution has mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>, then the sampling distribution of the mean also has mean <span class="math inline">\(\mu\)</span>, and the standard error of the mean is <span class="math display">\[\mbox{SEM} = \frac{\sigma}{ \sqrt{N} }\]</span> Because we divide the population standard deviation <span class="math inline">\(\sigma\)</span> by the square root of the sample size <span class="math inline">\(N\)</span>, the SEM gets smaller as the sample size increases. It also tells us that the shape of the sampling distribution becomes normal.</p>
<p>This result is useful for all sorts of things. It tells us why large experiments are more reliable than small ones, and because it gives us an explicit formula for the standard error it tells us <strong>how much</strong> more reliable a large experiment is. It tells us why the normal distribution is, well, <strong>normal</strong>. In real experiments, many of the things that we want to measure are actually averages of lots of different quantities (e.g., arguably, “general” intelligence as measured by IQ is an average of a large number of “specific” skills and abilities), and when that happens, the averaged quantity should follow a normal distribution. Because of this mathematical law, the normal distribution pops up over and over again in real data.</p>
</section>
<section id="z-scores" class="level2" data-number="4.13">
<h2 data-number="4.13" class="anchored" data-anchor-id="z-scores"><span class="header-section-number">4.13</span> z-scores</h2>
<p>We are now in a position to combine some of things we’ve been talking about in this chapter, and introduce you to a new tool, <strong>z-scores</strong>. It turns out we won’t use <strong>z-scores</strong> very much in this textbook. However, you can’t take a class on statistics and not learn about <strong>z-scores</strong>.</p>
<p>We are going to look at a normal distribution in <a href="#fig-4normalSDspercents">Figure&nbsp;<span>4.17</span></a>, and draw lines through the distribution at 0, +/- 1, +/-2, and +/- 3 standard deviations from the mean:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4normalSDspercents" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-4normalSDspercents-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.17: A normal distribution. Each line represents a standard deviation from the mean. The labels show the proportions of scores that fall between each bar.</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure shows a normal distribution with mean = 0, and standard deviation = 1. We’ve drawn lines at each of the standard deviations: -3, -2, -1, 0, 1, 2, and 3. We also show some numbers in the labels, in between each line. These numbers are proportions. For example, we see the proportion is .341 for scores that fall between the range 0 and 1. Scores between 0 and 1 occur 34.1% of the time. Scores in between -1 and 1, occur 68.2% of the time, that’s more than half of the scores. Scores between 1 and occur about 13.6% of the time, and scores between 2 and 3 occur even less, only 2.1% of the time.</p>
<p>Normal distributions always have these properties, even when they have different means and standard deviations. For example, take a look at the normal distribution in <a href="#fig-4normalSDspercentsB">Figure&nbsp;<span>4.18</span></a> that has a mean = 100, and standard deviation = 25.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4normalSDspercentsB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="04-SamplesPopulations_files/figure-html/fig-4normalSDspercentsB-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.18: A normal distribution. Each line represents a standard deviation from the mean. The labels show the proportions of scores that fall between each bar.</figcaption>
</figure>
</div>
</div>
</div>
<p>Now we are looking at a normal distribution with mean = 100 and standard deviation = 25. Notice that the region between 100 and 125 contains 34.1% of the scores. This region is 1 standard deviation away from the mean (the standard deviation is 25, the mean is 100, so 25 is one whole standard deviation away from 100). As you can see, the very same proportions occur between each of the standard deviations, as they did when our standard deviation was set to 1 (with a mean of 0).</p>
<section id="idea-behind-z-scores" class="level3" data-number="4.13.1">
<h3 data-number="4.13.1" class="anchored" data-anchor-id="idea-behind-z-scores"><span class="header-section-number">4.13.1</span> Idea behind z-scores</h3>
<p>Sometimes it can be convenient to transform your original scores into different scores that are easier to work with. For example, if you have a bunch of proportions, like .3, .5, .6, .7, you might want to turn them into percentages like 30%, 50%, 60%, and 70%. To do that you multiply the proportions by a constant of 100. If you want to turn percentages back into proportions, you divide by a constant of 100. This kind of transformation just changes the scale of the numbers from between 0-1, and between 0-100. Otherwise, the pattern in the numbers stays the same.</p>
<p>The idea behind z-scores is a similar kind of transformation. The idea is to express each raw score in terms of it’s standard deviation. For example, if I told you I got a 75% on test, you wouldn’t know how well I did compared to the rest of the class. But, if I told you that I scored 2 standard deviations above the mean, you’d know I did quite well compared to the rest of the class, because you know that most scores (if they are distributed normally) fall below 2 standard deviations of the mean.</p>
<p>We also know, now thanks to the central limit theorem, that many of our measures, such as sample means, will be distributed normally. So, it can often be desirable to express the raw scores in terms of their standard deviations.</p>
<p>Let’s see how this looks in a table without showing you any formulas. We will look at some scores that come from a normal distribution with mean = 100, and standard deviation = 25. We will list some raw scores, along with the z-scores</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">raw</th>
<th style="text-align: right;">z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: right;">-3</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
<td style="text-align: right;">-2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">75</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="even">
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">125</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">150</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">175</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Remember, the mean is 100, and the standard deviation is 25. How many standard deviations away from the mean is a score of 100? The answer is 0, it’s right on the mean. You can see the z-score for 100, is 0. How many standard deviations is 125 away from the mean? Well the standard deviation is 25, 125 is one whole 25 away from 100, that’s a total of 1 standard deviation, so the z-score for 125 is 1. The z-score for 150 is 2, because 150 is two 25s away from 100. The z-score for 50 is -2, because 50 is two 25s away from 100 in the opposite direction. All we are doing here is re-expressing the raw scores in terms of how many standard deviations they are from the mean. Remember, the mean is always right on target, so the center of the z-score distribution is always 0.</p>
</section>
<section id="calculating-z-scores" class="level3" data-number="4.13.2">
<h3 data-number="4.13.2" class="anchored" data-anchor-id="calculating-z-scores"><span class="header-section-number">4.13.2</span> Calculating z-scores</h3>
<p>To calculate z-scores all you have to do is figure out how many standard deviations from the mean each number is. Let’s say the mean is 100, and the standard deviation is 25. You have a score of 97. How many standard deviations from the mean is 97?</p>
<p>First compute the difference between the score and the mean:</p>
<p><span class="math inline">\(97-100 = -3\)</span></p>
<p>Alright, we have a total difference of -3. How many standard deviations does -3 represent if 1 standard deviation is 25? Clearly -3 is much smaller than 25, so it’s going to be much less than 1. To figure it out, just divide -3 by the standard deviation.</p>
<p><span class="math inline">\(\frac{-3}{25} = -.12\)</span></p>
<p>Our z-score for 97 is -.12.</p>
<p>Here’s the general formula:</p>
<p><span class="math inline">\(z = \frac{\text{raw score} - \text{mean}}{\text{standard deviation}}\)</span></p>
<p>So, for example if we had these 10 scores from a normal distribution with mean = 100, and standard deviation =25</p>
<div class="cell">
<pre><code>#&gt;  [1] 121.36  48.69  91.69  46.76 114.57 116.07 133.11  78.14 104.95  73.26</code></pre>
</div>
<p>The z-scores would be:</p>
<div class="cell">
<pre><code>#&gt;  [1]  0.8544 -2.0524 -0.3324 -2.1296  0.5828  0.6428  1.3244 -0.8744  0.1980
#&gt; [10] -1.0696</code></pre>
</div>
<p>Once you have the z-scores, you could use them as another way to describe your data. For example, now just by looking at a score you know if it is likely or unlikely to occur, because you know how the area under the normal curve works. z-scores between -1 and 1 happen pretty often, scores greater than 1 or -1 still happen fairly often, but not as often. And, scores bigger than 2 or -2 don’t happen very often. This is a convenient thing to do if you want to look at your numbers and get a general sense of how often they happen.</p>
<p>Usually you do not know the mean or the standard deviation of the population that you are drawing your sample scores from. So, you could use the mean and standard deviation of your sample as an estimate, and then use those to calculate z-scores.</p>
<p>Finally, z-scores are also called <strong>standardized scores</strong>, because each raw score is described in terms of it’s standard deviation. This may well be the last time we talk about z-scores in this book. You might wonder why we even bothered telling you about them. First, it’s worth knowing they are a thing. Second, they become important as your statistical prowess becomes more advanced. Third, some statistical concepts, like correlation, can be re-written in terms of z-scores, and this illuminates aspects of those statistics. Finally, they are super useful when you are dealing with a normal distribution that has a known mean and standard deviation.</p>
</section>
</section>
<section id="estimating-population-parameters" class="level2" data-number="4.14">
<h2 data-number="4.14" class="anchored" data-anchor-id="estimating-population-parameters"><span class="header-section-number">4.14</span> Estimating population parameters</h2>
<p>Let’s pause for a moment to get our bearings. We’re about to go into the topic of <strong>estimation</strong>. What is that, and why should you care? First, population parameters are things about a distribution. For example, distributions have means. The mean is a parameter of the distribution. The standard deviation of a distribution is a parameter. Anything that can describe a distribution is a potential parameter.</p>
<p>OK fine, who cares? This I think, is a really good question. There are some good concrete reasons to care. And there are some great abstract reasons to care. Unfortunately, most of the time in research, it’s the abstract reasons that matter most, and these can be the most difficult to get your head around.</p>
<section id="concrete-population-parameters" class="level3" data-number="4.14.1">
<h3 data-number="4.14.1" class="anchored" data-anchor-id="concrete-population-parameters"><span class="header-section-number">4.14.1</span> Concrete population parameters</h3>
<p>First some concrete reasons. There are real populations out there, and sometimes you want to know the parameters of them. For example, if you are a shoe company, you would want to know about the population parameters of feet size. As a first pass, you would want to know the mean and standard deviation of the population. If your company knew this, and other companies did not, your company would do better (assuming all shoes are made equal). Why would your company do better, and how could it use the parameters? Here’s one good reason. As a shoe company you want to meet demand with the right amount of supply. If you make too many big or small shoes, and there aren’t enough people to buy them, then you’re making extra shoes that don’t sell. If you don’t make enough of the most popular sizes, you’ll be leaving money on the table. Right? Yes. So, what would be an optimal thing to do? Perhaps, you would make different amounts of shoes in each size, corresponding to how the demand for each shoe size. You would know something about the demand by figuring out the frequency of each size in the population. You would need to know the population parameters to do this.</p>
<p>Fortunately, it’s pretty easy to get the population parameters without measuring the entire population. Who has time to measure every-bodies feet? Nobody, that’s who. Instead, you would just need to randomly pick a bunch of people, measure their feet, and then measure the parameters of the sample. If you take a big enough sample, we have learned that the sample mean gives a very good estimate of the population mean. We will learn shortly that a version of the standard deviation of the sample also gives a good estimate of the standard deviation of the population. Perhaps shoe-sizes have a slightly different shape than a normal distribution. Here too, if you collect a big enough sample, the shape of the distribution of the sample will be a good estimate of the shape of the populations. All of these are good reasons to care about estimating population parameters. But, do you run a shoe company? Probably not.</p>
</section>
<section id="abstract-population-parameters" class="level3" data-number="4.14.2">
<h3 data-number="4.14.2" class="anchored" data-anchor-id="abstract-population-parameters"><span class="header-section-number">4.14.2</span> Abstract population parameters</h3>
<p>Even when we think we are talking about something concrete in Psychology, it often gets abstract right away. Instead of measuring the population of feet-sizes, how about the population of human happiness. We all think we know what happiness is, everyone has more or less of it, there are a bunch of people, so there must be a population of happiness right? Perhaps, but it’s not very concrete. The first problem is figuring out how to measure happiness. Let’s use a questionnaire. Consider these questions:</p>
<blockquote class="blockquote">
<p>How happy are you right now on a scale from 1 to 7? How happy are you in general on a scale from 1 to 7? How happy are you in the mornings on a scale from 1 to 7? How happy are you in the afternoons on a scale from 1 to 7?</p>
</blockquote>
<ol type="1">
<li>= very unhappy</li>
<li>= unhappy</li>
<li>= sort of unhappy</li>
<li>= in the middle</li>
<li>= sort of happy</li>
<li>= happy</li>
<li>= very happy</li>
</ol>
<p>Forget about asking these questions to everybody in the world. Let’s just ask them to lots of people (our sample). What do you think would happen? Well, obviously people would give all sorts of answers right. We could tally up the answers and plot them in a histogram. This would show us a distribution of happiness scores from our sample. “Great, fantastic!”, you say. Yes, fine and dandy.</p>
<p>So, on the one hand we could say lots of things about the people in our sample. We could say exactly who says they are happy and who says they aren’t, after all they just told us!</p>
<p>But, what can we say about the larger population? Can we use the parameters of our sample (e.g., mean, standard deviation, shape etc.) to estimate something about a larger population. Can we infer how happy everybody else is, just from our sample? HOLD THE PHONE.</p>
<section id="complications-with-inference" class="level4" data-number="4.14.2.1">
<h4 data-number="4.14.2.1" class="anchored" data-anchor-id="complications-with-inference"><span class="header-section-number">4.14.2.1</span> Complications with inference</h4>
<p>Before listing a bunch of complications, let me tell you what I think we can do with our sample. Provided it is big enough, our sample parameters will be a pretty good estimate of what another sample would look like. Because of the following discussion, this is often all we can say. But, that’s OK, as you see throughout this book, we can work with that!</p>
<p><strong>Problem 1: Multiple populations</strong>: If you looked at a large sample of questionnaire data you will find evidence of multiple distributions inside your sample. People answer questions differently. Some people are very cautious and not very extreme. Their answers will tend to be distributed about the middle of the scale, mostly 3s, 4s, and 5s. Some people are very bi-modal, they are very happy and very unhappy, depending on time of day. These people’s answers will be mostly 1s and 2s, and 6s and 7s, and those numbers look like they come from a completely different distribution. Some people are entirely happy or entirely unhappy. Again, these two “populations” of people’s numbers look like two different distributions, one with mostly 6s and 7s, and one with mostly 1s and 2s. Other people will be more random, and their scores will look like a uniform distribution. So, is there a single population with parameters that we can estimate from our sample? Probably not. Could be a mixture of lots of populations with different distributions.</p>
<p><strong>Problem 2: What do these questions measure?</strong>: If the whole point of doing the questionnaire is to estimate the population’s happiness, we really need wonder if the sample measurements actually tell us anything about happiness in the first place. Some questions: Are people accurate in saying how happy they are? Does the measure of happiness depend on the scale, for example, would the results be different if we used 0-100, or -100 to +100, or no numbers? Does the measure of happiness depend on the wording in the question? Does a measure like this one tell us everything we want to know about happiness (probably not), what is it missing (who knows? probably lots). In short, nobody knows if these kinds of questions measure what we want them to measure. We just hope that they do. Instead, we have a very good idea of the kinds of things that they actually measure. It’s really quite obvious, and staring you in the face. Questionnaire measurements measure how people answer questionnaires. In other words, how people behave and answer questions when they are given a questionnaire. This might also measure something about happiness, when the question has to do about happiness. But, it turns out people are remarkably consistent in how they answer questions, even when the questions are total nonsense, or have no questions at all (just numbers to choose!) <span class="citation" data-cites="maul_rethinking_2017">Maul (<a href="references.html#ref-maul_rethinking_2017" role="doc-biblioref">2017</a>)</span>.</p>
<p>The take home complications here are that we can collect samples, but in Psychology, we often don’t have a good idea of the populations that might be linked to these samples. There might be lots of populations, or the populations could be different depending on who you ask. Finally, the “population” might not be the one you want it to be.</p>
</section>
</section>
<section id="experiments-and-population-parameters" class="level3" data-number="4.14.3">
<h3 data-number="4.14.3" class="anchored" data-anchor-id="experiments-and-population-parameters"><span class="header-section-number">4.14.3</span> Experiments and Population parameters</h3>
<p>OK, so we don’t own a shoe company, and we can’t really identify the population of interest in Psychology, can’t we just skip this section on estimation? After all, the “population” is just too weird and abstract and useless and contentious. HOLD THE PHONE AGAIN!</p>
<p>It turns out we can apply the things we have been learning to solve lots of important problems in research. These allow us to answer questions with the data that we collect. Parameter estimation is one of these tools. We just need to be a little bit more creative, and a little bit more abstract to use the tools.</p>
<p>Here is what we know already. The numbers that we measure come from somewhere, we have called this place “distributions”. Distributions control how the numbers arrive. Some numbers happen more than others depending on the distribution. We assume, even if we don’t know what the distribution is, or what it means, that the numbers came from one. Second, when get some numbers, we call it a sample. This entire chapter so far has taught you one thing. When your sample is big, it resembles the distribution it came from. And, when your sample is big, it will resemble very closely what another big sample of the same thing will look like. We can use this knowledge!</p>
<p>Very often as Psychologists what we want to know is what causes what. We want to know if X causes something to change in Y. Does eating chocolate make you happier? Does studying improve your grades? There a bazillions of these kinds of questions. And, we want answers to them.</p>
<p>I’ve been trying to be mostly concrete so far in this textbook, that’s why we talk about silly things like chocolate and happiness, at least they are concrete. Let’s give a go at being abstract. We can do it.</p>
<p>So, we want to know if X causes Y to change. What is X? What is Y? X is something you change, something you manipulate, the independent variable. Y is something you measure. So, we will be taking samples from Y. “Oh I get it, we’ll take samples from Y, then we can use the sample parameters to estimate the population parameters of Y!” NO, not really, but yes sort of. We will take sample from Y, that is something we absolutely do. In fact, that is really all we ever do, which is why talking about the population of Y is kind of meaningless. We’re more interested in our samples of Y, and how they behave.</p>
<p>So, what would happen if we removed X from the universe altogether, and then took a big sample of Y. We’ll pretend Y measures something in a Psychology experiment. So, we know right away that Y is variable. When we take a big sample, it will have a distribution (because Y is variable). So, we can do things like measure the mean of Y, and measure the standard deviation of Y, and anything else we want to know about Y. Fine. What would happen if we replicated this measurement. That is, we just take another random sample of Y, just as big as the first. What should happen is that our first sample should look a lot like our second example. After all, we didn’t do anything to Y, we just took two big samples twice. Both of our samples will be a little bit different (due to sampling error), but they’ll be mostly the same. The bigger our samples, the more they will look the same, especially when we don’t do anything to cause them to be different. In other words, we can use the parameters of one sample to estimate the parameters of a second sample, because they will tend to be the same, especially when they are large.</p>
<p>We are now ready for step two. You want to know if X changes Y. What do you do? You make X go up and take a big sample of Y then look at it. You make X go down, then take a second big sample of Y and look at it. Next, you compare the two samples of Y. If X does nothing then what should you find? We already discussed that in the previous paragraph. If X does nothing, then both of your big samples of Y should be pretty similar. However, if X does something to Y, then one of your big samples of Y will be different from the other. You will have changed something about Y. Maybe X makes the mean of Y change. Or maybe X makes the variation in Y change. Or, maybe X makes the whole shape of the distribution change. If we find any big changes that can’t be explained by sampling error, then we can conclude that something about X caused a change in Y! We could use this approach to learn about what causes what!</p>
<p>The very important idea is still about estimation, just not population parameter estimation exactly. We know that when we take samples they naturally vary. So, when we estimate a parameter of a sample, like the mean, we know we are off by some amount. When we find that two samples are different, we need to find out if the size of the difference is consistent with what sampling error can produce, or if the difference is bigger than that. If the difference is bigger, then we can be confident that sampling error didn’t produce the difference. So, we can confidently infer that something else (like an X) did cause the difference. This bit of abstract thinking is what most of the rest of the textbook is about. Determining whether there is a difference caused by your manipulation. There’s more to the story, there always is. We can get more specific than just, is there a difference, but for introductory purposes, we will focus on the finding of differences as a foundational concept.</p>
</section>
<section id="interim-summary" class="level3" data-number="4.14.4">
<h3 data-number="4.14.4" class="anchored" data-anchor-id="interim-summary"><span class="header-section-number">4.14.4</span> Interim summary</h3>
<p>We’ve talked about estimation without doing any estimation, so in the next section we will do some estimating of the mean and of the standard deviation. Formally, we talk about this as using a sample to estimate a parameter of the population. Feel free to think of the “population” in different ways. It could be concrete population, like the distribution of feet-sizes. Or, it could be something more abstract, like the parameter estimate of what samples usually look like when they come from a distribution.</p>
</section>
<section id="estimating-the-population-mean" class="level3" data-number="4.14.5">
<h3 data-number="4.14.5" class="anchored" data-anchor-id="estimating-the-population-mean"><span class="header-section-number">4.14.5</span> Estimating the population mean</h3>
<p>Suppose we go to Brooklyn and 100 of the locals are kind enough to sit through an IQ test. The average IQ score among these people turns out to be <span class="math inline">\(\bar{X}=98.5\)</span>. So what is the true mean IQ for the entire population of Brooklyn? Obviously, we don’t know the answer to that question. It could be <span class="math inline">\(97.2\)</span>, but if could also be <span class="math inline">\(103.5\)</span>. Our sampling isn’t exhaustive so we cannot give a definitive answer. Nevertheless if forced to give a “best guess” I’d have to say <span class="math inline">\(98.5\)</span>. That’s the essence of statistical estimation: giving a best guess. We’re using the sample mean as the best guess of the population mean.</p>
<p>In this example, estimating the unknown population parameter is straightforward. I calculate the sample mean, and I use that as my <strong>estimate of the population mean</strong>. It’s pretty simple, and in the next section we’ll explain the statistical justification for this intuitive answer. However, for the moment let’s make sure you recognize that the sample statistic and the estimate of the population parameter are conceptually different things. A sample statistic is a description of your data, whereas the estimate is a guess about the population. With that in mind, statisticians often use different notation to refer to them. For instance, if true population mean is denoted <span class="math inline">\(\mu\)</span>, then we would use <span class="math inline">\(\hat\mu\)</span> to refer to our estimate of the population mean. In contrast, the sample mean is denoted <span class="math inline">\(\bar{X}\)</span> or sometimes <span class="math inline">\(m\)</span>. However, in simple random samples, the estimate of the population mean is identical to the sample mean: if I observe a sample mean of <span class="math inline">\(\bar{X} = 98.5\)</span>, then my estimate of the population mean is also <span class="math inline">\(\hat\mu = 98.5\)</span>. To help keep the notation clear, here’s a handy table:</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>What is it?</th>
<th>Do we know what it is?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\bar{X}\)</span></td>
<td>Sample mean</td>
<td>Yes, calculated from the raw data</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu\)</span></td>
<td>True population mean</td>
<td>Almost never known for sure</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat{\mu}\)</span></td>
<td>Estimate of the population mean</td>
<td>Yes, identical to the sample mean</td>
</tr>
</tbody>
</table>
</section>
<section id="estimating-the-population-standard-deviation" class="level3" data-number="4.14.6">
<h3 data-number="4.14.6" class="anchored" data-anchor-id="estimating-the-population-standard-deviation"><span class="header-section-number">4.14.6</span> Estimating the population standard deviation</h3>
<p>So far, estimation seems pretty simple, and you might be wondering why I forced you to read through all that stuff about sampling theory. In the case of the mean, our estimate of the population parameter (i.e.&nbsp;<span class="math inline">\(\hat\mu\)</span>) turned out to identical to the corresponding sample statistic (i.e.&nbsp;<span class="math inline">\(\bar{X}\)</span>). However, that’s not always true. To see this, let’s have a think about how to construct an <strong>estimate of the population standard deviation</strong>, which we’ll denote <span class="math inline">\(\hat\sigma\)</span>. What shall we use as our estimate in this case? Your first thought might be that we could do the same thing we did when estimating the mean, and just use the sample statistic as our estimate. That’s almost the right thing to do, but not quite.</p>
<p>Here’s why. Suppose I have a sample that contains a single observation. For this example, it helps to consider a sample where you have no intuitions at all about what the true population values might be, so let’s use something completely fictitious. Suppose the observation in question measures the <strong>cromulence</strong> of my shoes. It turns out that my shoes have a cromulence of 20. So here’s my sample:</p>
<p><code>20</code></p>
<p>This is a perfectly legitimate sample, even if it does have a sample size of <span class="math inline">\(N=1\)</span>. It has a sample mean of 20, and because every observation in this sample is equal to the sample mean (obviously!) it has a sample standard deviation of 0. As a description of the <strong>sample</strong> this seems quite right: the sample contains a single observation and therefore there is no variation observed within the sample. A sample standard deviation of <span class="math inline">\(s = 0\)</span> is the right answer here. But as an estimate of the <strong>population</strong> standard deviation, it feels completely insane, right? Admittedly, you and I don’t know anything at all about what “cromulence” is, but we know something about data: the only reason that we don’t see any variability in the <strong>sample</strong> is that the sample is too small to display any variation! So, if you have a sample size of <span class="math inline">\(N=1\)</span>, it <strong>feels</strong> like the right answer is just to say “no idea at all”.</p>
<p>Notice that you <strong>don’t</strong> have the same intuition when it comes to the sample mean and the population mean. If forced to make a best guess about the population mean, it doesn’t feel completely insane to guess that the population mean is 20. Sure, you probably wouldn’t feel very confident in that guess, because you have only the one observation to work with, but it’s still the best guess you can make.</p>
<p>Let’s extend this example a little. Suppose I now make a second observation. My data set now has <span class="math inline">\(N=2\)</span> observations of the cromulence of shoes, and the complete sample now looks like this:</p>
<p><code>20, 22</code></p>
<p>This time around, our sample is <strong>just</strong> large enough for us to be able to observe some variability: two observations is the bare minimum number needed for any variability to be observed! For our new data set, the sample mean is <span class="math inline">\(\bar{X}=21\)</span>, and the sample standard deviation is <span class="math inline">\(s=1\)</span>. What intuitions do we have about the population? Again, as far as the population mean goes, the best guess we can possibly make is the sample mean: if forced to guess, we’d probably guess that the population mean cromulence is 21. What about the standard deviation? This is a little more complicated. The sample standard deviation is only based on two observations, and if you’re at all like me you probably have the intuition that, with only two observations, we haven’t given the population “enough of a chance” to reveal its true variability to us. It’s not just that we suspect that the estimate is <strong>wrong</strong>: after all, with only two observations we expect it to be wrong to some degree. The worry is that the error is <strong>systematic</strong>.</p>
<p>If the error is systematic, that means it is <strong>biased</strong>. For example, imagine if the sample mean was always smaller than the population mean. If this was true (it’s not), then we couldn’t use the sample mean as an estimator. It would be biased, we’d be using the wrong number.</p>
<p>It turns out the sample standard deviation is a <strong>biased estimator</strong> of the population standard deviation. We can sort of anticipate this by what we’ve been discussing. When the sample size is 1, the standard deviation is 0, which is obviously to small. When the sample size is 2, the standard deviation becomes a number bigger than 0, but because we only have two sample, we suspect it might still be too small. Turns out this intuition is correct.</p>
<p>It would be nice to demonstrate this somehow. There are in fact mathematical proofs that confirm this intuition, but unless you have the right mathematical background they don’t help very much. Instead, what I’ll do is use R to simulate the results of some experiments. With that in mind, let’s return to our IQ studies. Suppose the true population mean IQ is 100 and the standard deviation is 15. I can use the <strong>rnorm()</strong> function to generate the the results of an experiment in which I measure <span class="math inline">\(N=2\)</span> IQ scores, and calculate the sample standard deviation. If I do this over and over again, and plot a histogram of these sample standard deviations, what I have is the <strong>sampling distribution of the standard deviation</strong>. I’ve plotted this distribution in <a href="#fig-sampdistsd">Figure&nbsp;<span>4.19</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sampdistsd" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/navarro_img/estimation/sampdistsd.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.19: The sampling distribution of the sample standard deviation for a two IQ scores experiment. The true population standard deviation is 15 (dashed line), but as you can see from the histogram, the vast majority of experiments will produce a much smaller sample standard deviation than this. On average, this experiment would produce a sample standard deviation of only 8.5, well below the true value! In other words, the sample standard deviation is a biased estimate of the population standard deviation.</figcaption>
</figure>
</div>
</div>
</div>
<p>Even though the true population standard deviation is 15, the average of the <strong>sample</strong> standard deviations is only 8.5. Notice that this is a very different from when we were plotting sampling distributions of the sample mean, those were always centered around the mean of the population.</p>
<p>Now let’s extend the simulation. Instead of restricting ourselves to the situation where we have a sample size of <span class="math inline">\(N=2\)</span>, let’s repeat the exercise for sample sizes from 1 to 10. If we plot the average sample mean and average sample standard deviation as a function of sample size, you get the following results.</p>
<p>@fig-estimatorbiasA shows the sample mean as a function of sample size. Notice it’s a flat line. The sample mean doesn’t underestimate or overestimate the population mean. It is an unbiased estimate!</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-estimatorbiasA" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/navarro_img/estimation/biasMean-eps-converted-to.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.20: An illustration of the fact that the sample mean is an unbiased estimator of the population mean.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-estimatorbiasB">Figure&nbsp;<span>4.21</span></a> shows the sample standard deviation as a function of sample size. Notice it is not a flat line. The sample standard deviation systematically underestimates the population standard deviation!</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-estimatorbiasB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/navarro_img/estimation/biasSD-eps-converted-to.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4.21: An illustration of the fact that the the sample standard deviation is a biased estimator of the population standard deviation.</figcaption>
</figure>
</div>
</div>
</div>
<p>In other words, if we want to make a “best guess” (<span class="math inline">\(\hat\sigma\)</span>, our estimate of the population standard deviation) about the value of the population standard deviation <span class="math inline">\(\sigma\)</span>, we should make sure our guess is a little bit larger than the sample standard deviation <span class="math inline">\(s\)</span>.</p>
<p>The fix to this systematic bias turns out to be very simple. Here’s how it works. Before tackling the standard deviation, let’s look at the variance. If you recall from the second chapter, the sample variance is defined to be the average of the squared deviations from the sample mean. That is: <span class="math display">\[s^2 = \frac{1}{N} \sum_{i=1}^N (X_i - \bar{X})^2\]</span> The sample variance <span class="math inline">\(s^2\)</span> is a biased estimator of the population variance <span class="math inline">\(\sigma^2\)</span>. But as it turns out, we only need to make a tiny tweak to transform this into an unbiased estimator. All we have to do is divide by <span class="math inline">\(N-1\)</span> rather than by <span class="math inline">\(N\)</span>. If we do that, we obtain the following formula: <span class="math display">\[\hat\sigma^2 = \frac{1}{N-1} \sum_{i=1}^N (X_i - \bar{X})^2\]</span> This is an unbiased estimator of the population variance <span class="math inline">\(\sigma\)</span>.</p>
<p>A similar story applies for the standard deviation. If we divide by <span class="math inline">\(N-1\)</span> rather than <span class="math inline">\(N\)</span>, our estimate of the population standard deviation becomes: <span class="math display">\[\hat\sigma = \sqrt{\frac{1}{N-1} \sum_{i=1}^N (X_i - \bar{X})^2}\]</span>.</p>
<p>It is worth pointing out that software programs make assumptions <strong>for you</strong>, about which variance and standard deviation <strong>you</strong> are computing. Some programs automatically divide by <span class="math inline">\(N-1\)</span>, some do not. You need to check to figure out what they are doing. Don’t let the software tell you what to do. Software is for you telling it what to do.</p>
<p>One final point: in practice, a lot of people tend to refer to <span class="math inline">\(\hat{\sigma}\)</span> (i.e., the formula where we divide by <span class="math inline">\(N-1\)</span>) as the <strong>sample</strong> standard deviation. Technically, this is incorrect: the <strong>sample</strong> standard deviation should be equal to <span class="math inline">\(s\)</span> (i.e., the formula where we divide by <span class="math inline">\(N\)</span>). These aren’t the same thing, either conceptually or numerically. One is a property of the sample, the other is an estimated characteristic of the population. However, in almost every real life application, what we actually care about is the estimate of the population parameter, and so people always report <span class="math inline">\(\hat\sigma\)</span> rather than <span class="math inline">\(s\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note, whether you should divide by N or N-1 also depends on your philosophy about what you are doing. For example, if you don’t think that what you are doing is estimating a population parameter, then why would you divide by N-1? Also, when N is large, it doesn’t matter too much. The difference between a big N, and a big N-1, is just -1.</p>
</div>
</div>
<p>This is the right number to report, of course, it’s that people tend to get a little bit imprecise about terminology when they write it up, because “sample standard deviation” is shorter than “estimated population standard deviation”. It’s no big deal, and in practice I do the same thing everyone else does. Nevertheless, I think it’s important to keep the two <strong>concepts</strong> separate: it’s never a good idea to confuse “known properties of your sample” with “guesses about the population from which it came”. The moment you start thinking that <span class="math inline">\(s\)</span> and <span class="math inline">\(\hat\sigma\)</span> are the same thing, you start doing exactly that.</p>
<p>To finish this section off, here’s another couple of tables to help keep things clear:</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 33%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>What is it?</th>
<th>Do we know what it is?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(s^2\)</span></td>
<td>Sample variance</td>
<td>Yes, calculated from the raw data</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma^2\)</span></td>
<td>Population variance</td>
<td>Almost never known for sure</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat{\sigma}^2\)</span></td>
<td>Estimate of the population variance</td>
<td>Yes, but not the same as the sample variance</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="estimating-a-confidence-interval" class="level2" data-number="4.15">
<h2 data-number="4.15" class="anchored" data-anchor-id="estimating-a-confidence-interval"><span class="header-section-number">4.15</span> Estimating a confidence interval</h2>
<blockquote class="blockquote">
<p>Statistics means never having to say you’re certain – Unknown origin</p>
</blockquote>
<p>Up to this point in this chapter, we’ve outlined the basics of sampling theory which statisticians rely on to make guesses about population parameters on the basis of a sample of data. As this discussion illustrates, one of the reasons we need all this sampling theory is that every data set leaves us with some of uncertainty, so our estimates are never going to be perfectly accurate. The thing that has been missing from this discussion is an attempt to <strong>quantify</strong> the amount of uncertainty in our estimate. It’s not enough to be able guess that the mean IQ of undergraduate psychology students is 115 (yes, I just made that number up). We also want to be able to say something that expresses the degree of certainty that we have in our guess. For example, it would be nice to be able to say that there is a 95% chance that the true mean lies between 109 and 121. The name for this is a <strong>confidence interval</strong> for the mean.</p>
<p>Armed with an understanding of sampling distributions, constructing a confidence interval for the mean is actually pretty easy. Here’s how it works. Suppose the true population mean is <span class="math inline">\(\mu\)</span> and the standard deviation is <span class="math inline">\(\sigma\)</span>. I’ve just finished running my study that has <span class="math inline">\(N\)</span> participants, and the mean IQ among those participants is <span class="math inline">\(\bar{X}\)</span>. We know from our discussion of the central limit theorem that the sampling distribution of the mean is approximately normal. We also know from our discussion of the normal distribution that there is a 95% chance that a normally-distributed quantity will fall within two standard deviations of the true mean. To be more precise, we can use the <strong>qnorm()</strong> function to compute the 2.5th and 97.5th percentiles of the normal distribution</p>
<blockquote class="blockquote">
<p>qnorm( p = c(.025, .975) ) [1] -1.959964 1.959964</p>
</blockquote>
<p>Okay, so I lied earlier on. The more correct answer is that a 95% chance that a normally-distributed quantity will fall within 1.96 standard deviations of the true mean.</p>
<p>Next, recall that the standard deviation of the sampling distribution is referred to as the standard error, and the standard error of the mean is written as SEM. When we put all these pieces together, we learn that there is a 95% probability that the sample mean <span class="math inline">\(\bar{X}\)</span> that we have actually observed lies within 1.96 standard errors of the population mean. Oof, that is a lot of mathy talk there. We’ll clear it up, don’t worry.</p>
<p>Mathematically, we write this as: <span class="math display">\[\mu - \left( 1.96 \times \mbox{SEM} \right) \ \leq \  \bar{X}\  \leq \  \mu + \left( 1.96 \times \mbox{SEM} \right)\]</span> where the SEM is equal to <span class="math inline">\(\sigma / \sqrt{N}\)</span>, and we can be 95% confident that this is true.</p>
<p>However, that’s not answering the question that we’re actually interested in. The equation above tells us what we should expect about the sample mean, given that we know what the population parameters are. What we <strong>want</strong> is to have this work the other way around: we want to know what we should believe about the population parameters, given that we have observed a particular sample. However, it’s not too difficult to do this. Using a little high school algebra, a sneaky way to rewrite our equation is like this: <span class="math display">\[\bar{X} -  \left( 1.96 \times \mbox{SEM} \right) \ \leq \ \mu  \ \leq  \ \bar{X} +  \left( 1.96 \times \mbox{SEM}\right)\]</span> What this is telling is is that the range of values has a 95% probability of containing the population mean <span class="math inline">\(\mu\)</span>. We refer to this range as a <strong>95% confidence interval</strong>, denoted <span class="math inline">\(\mbox{CI}_{95}\)</span>. In short, as long as <span class="math inline">\(N\)</span> is sufficiently large – large enough for us to believe that the sampling distribution of the mean is normal – then we can write this as our formula for the 95% confidence interval: <span class="math display">\[\mbox{CI}_{95} = \bar{X} \pm \left( 1.96 \times \frac{\sigma}{\sqrt{N}} \right)\]</span> Of course, there’s nothing special about the number 1.96: it just happens to be the multiplier you need to use if you want a 95% confidence interval. If I’d wanted a 70% confidence interval, I could have used the <strong>qnorm()</strong> function to calculate the 15th and 85th quantiles:</p>
<blockquote class="blockquote">
<p>qnorm( p = c(.15, .85) ) [1] -1.036433 1.036433</p>
</blockquote>
<p>and so the formula for <span class="math inline">\(\mbox{CI}_{70}\)</span> would be the same as the formula for <span class="math inline">\(\mbox{CI}_{95}\)</span> except that we’d use 1.04 as our magic number rather than 1.96.</p>
<section id="a-slight-mistake-in-the-formula" class="level3" data-number="4.15.1">
<h3 data-number="4.15.1" class="anchored" data-anchor-id="a-slight-mistake-in-the-formula"><span class="header-section-number">4.15.1</span> A slight mistake in the formula</h3>
<p>As usual, I lied. The formula that I’ve given above for the 95% confidence interval is approximately correct, but I glossed over an important detail in the discussion. Notice my formula requires you to use the standard error of the mean, SEM, which in turn requires you to use the true population standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<p>Yet, before we stressed the fact that we don’t actually <strong>know</strong> the true population parameters. Because we don’t know the true value of <span class="math inline">\(\sigma\)</span>, we have to use an estimate of the population standard deviation <span class="math inline">\(\hat{\sigma}\)</span> instead. This is pretty straightforward to do, but this has the consequence that we need to use the quantiles of the <span class="math inline">\(t\)</span>-distribution rather than the normal distribution to calculate our magic number; and the answer depends on the sample size. Plus, we haven’t really talked about the <span class="math inline">\(t\)</span> distribution yet.</p>
<p>When we use the <span class="math inline">\(t\)</span> distribution instead of the normal distribution, we get bigger numbers, indicating that we have more uncertainty. And why do we have that extra uncertainty? Well, because our estimate of the population standard deviation <span class="math inline">\(\hat\sigma\)</span> might be wrong! If it’s wrong, it implies that we’re a bit less sure about what our sampling distribution of the mean actually looks like… and this uncertainty ends up getting reflected in a wider confidence interval.</p>
</section>
</section>
<section id="summary" class="level2" data-number="4.16">
<h2 data-number="4.16" class="anchored" data-anchor-id="summary"><span class="header-section-number">4.16</span> Summary</h2>
<p>In this chapter I’ve covered two main topics. The first half of the chapter talks about sampling theory, and the second half talks about how we can use sampling theory to construct estimates of the population parameters. The section breakdown looks like this:</p>
<ul>
<li><p>Basic ideas about samples, sampling and populations</p></li>
<li><p>Statistical theory of sampling: the law of large numbers, sampling distributions and the central limit theorem.</p></li>
<li><p>Estimating means and standard deviations</p></li>
<li><p>confidence intervals</p></li>
</ul>
<p>As always, there’s a lot of topics related to sampling and estimation that aren’t covered in this chapter, but for an introductory psychology class this is fairly comprehensive I think. For most applied researchers you won’t need much more theory than this. One big question that I haven’t touched on in this chapter is what you do when you don’t have a simple random sample. There is a lot of statistical theory you can draw on to handle this situation, but it’s well beyond the scope of this book.</p>
</section>
<section id="videos" class="level2" data-number="4.17">
<h2 data-number="4.17" class="anchored" data-anchor-id="videos"><span class="header-section-number">4.17</span> Videos</h2>
<section id="introduction-to-probability" class="level3" data-number="4.17.1">
<h3 data-number="4.17.1" class="anchored" data-anchor-id="introduction-to-probability"><span class="header-section-number">4.17.1</span> Introduction to Probability</h3>
<p>Jeff has several more videos on probability that you can view on his <a href="https://www.youtube.com/playlist?list=PLKXdxQAT3tCvuex_E1ZnQYaw897ELUSaI">statistics playlist</a>.</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/RoalMn9VHZg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="chebychevs-theorem" class="level3" data-number="4.17.2">
<h3 data-number="4.17.2" class="anchored" data-anchor-id="chebychevs-theorem"><span class="header-section-number">4.17.2</span> Chebychev’s Theorem</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/4RtwqCFt1IU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="z-scores-1" class="level3" data-number="4.17.3">
<h3 data-number="4.17.3" class="anchored" data-anchor-id="z-scores-1"><span class="header-section-number">4.17.3</span> Z-scores</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/dQVO0KAxFaU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="normal-distribution-i" class="level3" data-number="4.17.4">
<h3 data-number="4.17.4" class="anchored" data-anchor-id="normal-distribution-i"><span class="header-section-number">4.17.4</span> Normal Distribution I</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/FPJDF9fGwwE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="normal-distribution-ii" class="level3" data-number="4.17.5">
<h3 data-number="4.17.5" class="anchored" data-anchor-id="normal-distribution-ii"><span class="header-section-number">4.17.5</span> Normal Distribution II</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/mPdnF-GVuCo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
<div id="ref-Keynes1923" class="csl-entry" role="listitem">
Keynes, John Maynard. 1923. <em>A Tract on Monetary Reform</em>. <span>London</span>: <span>Macmillan and Company</span>.
</div>
<div id="ref-maul_rethinking_2017" class="csl-entry" role="listitem">
Maul, Andrew. 2017. <span>“Rethinking <span>Traditional Methods</span> of <span>Survey Validation</span>.”</span> <em>Measurement: Interdisciplinary Research and Perspectives</em> 15 (2): 51–69. <a href="https://doi.org/10.1080/15366367.2017.1348108">https://doi.org/10.1080/15366367.2017.1348108</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-Correlation.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-Foundation_Inference.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>