<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew J. C. Crump">
<meta name="author" content="Mallory L. Barnes">

<title>Answering questions with data - 5&nbsp; Foundations for inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-Hypothesis_Testing.html" rel="next">
<link href="./04-SamplesPopulations.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 5&nbsp; Foundations for inference">
<meta property="og:description" content="">
<meta property="og:image" content="05-Foundation_Inference_files/figure-html/fig-5unifagain-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 5&nbsp; Foundations for inference">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-Foundation_Inference.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-MixedANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#brief-review-of-experiments" id="toc-brief-review-of-experiments" class="nav-link active" data-scroll-target="#brief-review-of-experiments"><span class="header-section-number">5.1</span> Brief review of Experiments</a></li>
  <li><a href="#the-data-came-from-a-distribution" id="toc-the-data-came-from-a-distribution" class="nav-link" data-scroll-target="#the-data-came-from-a-distribution"><span class="header-section-number">5.2</span> The data came from a distribution</a>
  <ul class="collapse">
  <li><a href="#uniform-distribution" id="toc-uniform-distribution" class="nav-link" data-scroll-target="#uniform-distribution"><span class="header-section-number">5.2.1</span> Uniform distribution</a></li>
  <li><a href="#not-all-samples-are-the-same-they-are-usually-quite-different" id="toc-not-all-samples-are-the-same-they-are-usually-quite-different" class="nav-link" data-scroll-target="#not-all-samples-are-the-same-they-are-usually-quite-different"><span class="header-section-number">5.2.2</span> Not all samples are the same, they are usually quite different</a></li>
  <li><a href="#large-samples-are-more-like-the-distribution-they-came-from" id="toc-large-samples-are-more-like-the-distribution-they-came-from" class="nav-link" data-scroll-target="#large-samples-are-more-like-the-distribution-they-came-from"><span class="header-section-number">5.2.3</span> Large samples are more like the distribution they came from</a></li>
  </ul></li>
  <li><a href="#is-there-a-difference" id="toc-is-there-a-difference" class="nav-link" data-scroll-target="#is-there-a-difference"><span class="header-section-number">5.3</span> Is there a difference?</a>
  <ul class="collapse">
  <li><a href="#chance-can-produce-differences" id="toc-chance-can-produce-differences" class="nav-link" data-scroll-target="#chance-can-produce-differences"><span class="header-section-number">5.3.1</span> Chance can produce differences</a></li>
  <li><a href="#differences-due-to-chance-can-be-simulated" id="toc-differences-due-to-chance-can-be-simulated" class="nav-link" data-scroll-target="#differences-due-to-chance-can-be-simulated"><span class="header-section-number">5.3.2</span> Differences due to chance can be simulated</a></li>
  </ul></li>
  <li><a href="#chance-makes-some-differences-more-likely-than-others" id="toc-chance-makes-some-differences-more-likely-than-others" class="nav-link" data-scroll-target="#chance-makes-some-differences-more-likely-than-others"><span class="header-section-number">5.4</span> Chance makes some differences more likely than others</a></li>
  <li><a href="#simulation-based-inference" id="toc-simulation-based-inference" class="nav-link" data-scroll-target="#simulation-based-inference"><span class="header-section-number">5.5</span> Simulation-Based Inference</a>
  <ul class="collapse">
  <li><a href="#intuitive-methods" id="toc-intuitive-methods" class="nav-link" data-scroll-target="#intuitive-methods"><span class="header-section-number">5.5.1</span> Intuitive methods</a></li>
  <li><a href="#part-1-frequency-based-intuition-about-occurrence" id="toc-part-1-frequency-based-intuition-about-occurrence" class="nav-link" data-scroll-target="#part-1-frequency-based-intuition-about-occurrence"><span class="header-section-number">5.5.2</span> Part 1: Frequency based intuition about occurrence</a></li>
  <li><a href="#part-2-simulating-chance" id="toc-part-2-simulating-chance" class="nav-link" data-scroll-target="#part-2-simulating-chance"><span class="header-section-number">5.5.3</span> Part 2: Simulating chance</a></li>
  <li><a href="#part-3-judgment-and-decision-making" id="toc-part-3-judgment-and-decision-making" class="nav-link" data-scroll-target="#part-3-judgment-and-decision-making"><span class="header-section-number">5.5.4</span> Part 3: Judgment and Decision-making</a></li>
  <li><a href="#part-4-experiment-design" id="toc-part-4-experiment-design" class="nav-link" data-scroll-target="#part-4-experiment-design"><span class="header-section-number">5.5.5</span> Part 4: Experiment Design</a></li>
  <li><a href="#part-5-i-have-the-power" id="toc-part-5-i-have-the-power" class="nav-link" data-scroll-target="#part-5-i-have-the-power"><span class="header-section-number">5.5.6</span> Part 5: I have the power</a></li>
  <li><a href="#summary-of-simulation-based-inference" id="toc-summary-of-simulation-based-inference" class="nav-link" data-scroll-target="#summary-of-simulation-based-inference"><span class="header-section-number">5.5.7</span> Summary of Simulation-Based Inference</a></li>
  </ul></li>
  <li><a href="#the-randomization-test-permutation-test" id="toc-the-randomization-test-permutation-test" class="nav-link" data-scroll-target="#the-randomization-test-permutation-test"><span class="header-section-number">5.6</span> The randomization test (permutation test)</a>
  <ul class="collapse">
  <li><a href="#pretend-example-does-distance-from-a-highway-affect-no₂-levels" id="toc-pretend-example-does-distance-from-a-highway-affect-no₂-levels" class="nav-link" data-scroll-target="#pretend-example-does-distance-from-a-highway-affect-no₂-levels"><span class="header-section-number">5.6.1</span> Pretend example: does distance from a highway affect NO₂ levels?</a></li>
  <li><a href="#take-homes-so-far" id="toc-take-homes-so-far" class="nav-link" data-scroll-target="#take-homes-so-far"><span class="header-section-number">5.6.2</span> Take homes so far</a></li>
  </ul></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"><span class="header-section-number">5.7</span> Videos</a>
  <ul class="collapse">
  <li><a href="#null-and-alternate-hypotheses" id="toc-null-and-alternate-hypotheses" class="nav-link" data-scroll-target="#null-and-alternate-hypotheses"><span class="header-section-number">5.7.1</span> Null and Alternate Hypotheses</a></li>
  <li><a href="#types-of-errors" id="toc-types-of-errors" class="nav-link" data-scroll-target="#types-of-errors"><span class="header-section-number">5.7.2</span> Types of Errors</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/05-Foundation_Inference.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Matthew J. C. Crump </p>
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 6, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>Data and data sets are not objective; they are creations of human design. We give numbers their voice, draw inferences from them, and define their meaning through our interpretations. —Katie Crawford</p>
</blockquote>
<p><strong>Inferential statistics</strong> is the branch of statistics concerned with drawing conclusions about populations or causal relationships from sample data. It provides the tools to answer questions like: did our manipulation actually cause a change, or could the pattern we observed have arisen by random chance alone?</p>
<p>This chapter builds the conceptual foundations for inference using simulation — no formulas yet. The goal is to make the underlying logic explicit and visible before it gets formalized in later chapters.</p>
<section id="brief-review-of-experiments" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="brief-review-of-experiments"><span class="header-section-number">5.1</span> Brief review of Experiments</h2>
<p>A controlled experiment is a structured method of data collection designed to support inferences about causality. In environmental science, experiments involve deliberately manipulating one condition while holding others constant, then measuring the response.</p>
<p>Every experiment has two core components. The <strong>independent variable</strong> is the condition under experimental control — the manipulation. The <strong>dependent variable</strong> is what is measured. For example, a researcher studying the effects of wastewater discharge on stream health might compare dissolved oxygen levels at sites downstream of a discharge point against levels at unaffected reference sites. Distance from discharge (affected vs.&nbsp;reference) is the independent variable; dissolved oxygen is the dependent variable.</p>
<p>Causal forces produce detectable change. If the discharge is genuinely reducing dissolved oxygen, then measurements from affected sites should differ systematically from measurements at reference sites. The experiment is designed to detect that change.</p>
<p>The central question becomes: how do we know if a measured difference between conditions reflects a real causal effect? The short answer is that data always contain variability — measurements fluctuate even when nothing has changed. To decide whether a difference is real, we need tools that can distinguish meaningful change from background noise.</p>
</section>
<section id="the-data-came-from-a-distribution" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="the-data-came-from-a-distribution"><span class="header-section-number">5.2</span> The data came from a distribution</h2>
<p>Understanding where data come from is foundational to inference. This section returns to sampling and distributions from that perspective — not just to describe them, but to ask what they reveal about the process that generated our observations.</p>
<p>A <strong>distribution</strong> specifies what numbers are likely to occur and how often. It sets the constraints on what we can expect to see when we take measurements. Distributions are abstract, but they can be visualized directly with histograms.</p>
<section id="uniform-distribution" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="uniform-distribution"><span class="header-section-number">5.2.1</span> Uniform distribution</h3>
<p>As a reminder from last chapter, <a href="#fig-5unifagain">Figure&nbsp;<span>5.1</span></a> shows that the shape of a uniform distribution is completely flat.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5unifagain" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5unifagain-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.1: Uniform distribution showing that the numbers from 1 to 10 have an equal probability of being sampled</figcaption>
</figure>
</div>
</div>
</div>
<p>The y-axis shows probability (0 to 1) and the x-axis shows the values 1 through 10. The flat horizontal line indicates that every value from 1 to 10 has an equal probability of occurring: 1/10 = 0.1. This is the defining property of a uniform distribution — no value is more likely than any other.</p>
<p>Think of the uniform distribution as a number-generating process. If it generates numbers repeatedly, it produces each value with equal frequency: roughly 10% 1s, 10% 2s, and so on. <a href="#tbl-5100rand">Table&nbsp;<span>5.1</span></a> shows 100 numbers sampled from this distribution.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-5100rand" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;5.1: 100 numbers randomly sampled from a uniform distribution.</caption>
<tbody>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>We used the uniform distribution to generate these numbers. Formally, this is called <strong>sampling</strong> from a <strong>distribution</strong>. Drawing a subset of observations from a larger process or population is sampling; if you could observe every possible value the process could produce, you would have the <strong>population</strong>. We will return to the distinction between samples and populations throughout the course.</p>
<p>Because we used the uniform distribution to create numbers, we already know where our numbers came from. However, we can still pretend for the moment that someone showed up at your door, showed you these numbers, and then you wondered where they came from. Can you tell just by looking at these numbers that they came from a uniform distribution? What would need to look at? Perhaps you would want to know if all of the numbers occur with roughly equal frequency, after all they should have right? That is, if each number had the same chance of occurring, we should see that each number occurs roughly the same number of times.</p>
<p>We already know what a histogram is, so we can put our sample of 100 numbers into a histogram and see what the counts look like. If all of the numbers from 1 to 10 occur with equal frequency, then each individual number should occur about 10 times. <a href="#fig-5histunif">Figure&nbsp;<span>5.2</span></a> shows the histogram:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5histunif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5histunif-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.2: Histogram of 100 numbers randomly sampled from the uniform distribution containing the integers from 1 to 10</figcaption>
</figure>
</div>
</div>
</div>
<p>As the histogram shows, not all numbers occurred exactly 10 times. The bars vary in height even though all values had equal probability. This is a direct illustration of <strong>sampling variability</strong>: random samples do not perfectly reproduce the distribution they came from. The discrepancy between what we observe and what the distribution predicts is called <strong>sampling error</strong>.</p>
</section>
<section id="not-all-samples-are-the-same-they-are-usually-quite-different" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="not-all-samples-are-the-same-they-are-usually-quite-different"><span class="header-section-number">5.2.2</span> Not all samples are the same, they are usually quite different</h3>
<p>Let’s look at sampling error more closely. We will sample 20 numbers from the uniform distribution. We should expect that each number between 1 and 10 occurs about two times each. As before, this expectation can be visualized in a histogram. To get a better sense of sampling error, let’s repeat the above process ten times. <a href="#fig-5manysamples">Figure&nbsp;<span>5.3</span></a> has 10 histograms, each showing what 10 different samples of twenty numbers looks like:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5manysamples" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5manysamples-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.3: Histograms for 10 different samples from the uniform distribution. Each sample contains 20 numbers. The histograms all look quite different. The differences between the samples are due to sampling error or random chance.</figcaption>
</figure>
</div>
</div>
</div>
<p>You might notice right away that none of the histograms are the same. Even though we are randomly taking 20 numbers from the very same uniform distribution, each sample of 20 numbers comes out different. This is sampling variability, or sampling error.</p>
<p><a href="#fig-5expectedUnif">Figure&nbsp;<span>5.4</span></a> shows an animated version of the process of repeatedly choosing 20 new random numbers and plotting a histogram. The horizontal line shows the flat-line shape of the uniform distribution. The line crosses the y-axis at 2; and, we expect that each number (from 1 to 10) should occur about 2 times each in a sample of 20. However, each sample bounces around quite a bit, due to random chance.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5expectedUnif" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/sampleUnifExpected-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.4: Animation of histograms for different samples of 20 from Uniform distribution (numbers 1 to 10). The black lines shows the expected number of times each number from 1 to 10 should occur. The fact that each number does not occur 2 times each illustrates the error associated with sampling</figcaption>
</figure>
</div>
</div>
</div>
<p>Small samples show high variability because random chance can produce very uneven counts even when every value is equally likely. This variability is sampling error, and it makes it harder to identify the true distribution from a single sample.</p>
</section>
<section id="large-samples-are-more-like-the-distribution-they-came-from" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="large-samples-are-more-like-the-distribution-they-came-from"><span class="header-section-number">5.2.3</span> Large samples are more like the distribution they came from</h3>
<p>Let’s refresh the question. Which of the two samples in <a href="#fig-5whichone">Figure&nbsp;<span>5.5</span></a> do you think came from a uniform distribution?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5whichone" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5whichone-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.5: Which of these two samples came from a uniform distribution?</figcaption>
</figure>
</div>
</div>
</div>
<p>Both samples came from the uniform distribution — yet neither histogram looks perfectly flat. This illustrates how sampling error can obscure the true distribution, especially at small sample sizes.</p>
<p>Can we improve things, and make it easier to see if a sample came from a uniform distribution? Yes, we can. All we need to do is increase the <strong>sample-size</strong>. We will often use the letter <code>n</code> to refer to sample-size. N is the number of observations in the sample.</p>
<p>So let’s increase the number of observations in each sample from 20 to 100. We will again create 10 samples (each with 100 observations), and make histograms for each of them. All of these samples will be drawn from the very same uniform distribution. This, means we should expect each number from 1 to 10 to occur about 10 times in each sample. The histograms are shown in <a href="#fig-5unifsamp100">Figure&nbsp;<span>5.6</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5unifsamp100" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5unifsamp100-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.6: Histograms for different samples from a uniform distribution. N = 100 for each sample.</figcaption>
</figure>
</div>
</div>
</div>
<p>Again, most of these histograms don’t look very flat, and all of the bars seem to be going up or down, and they are not exactly at 10 each. So, we are still dealing with sampling error. It’s a pain. It’s always there.</p>
<p>Let’s bump up the <span class="math inline">\(N\)</span> from 100 to 1000 observations per sample. Now we should expect every number to appear about 100 times each. What happens?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5unifsamp1000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5unifsamp1000-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.7: Histograms for different samples from a uniform distribution. N = 1000 for each sample.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-5unifsamp1000">Figure&nbsp;<span>5.7</span></a> shows the histograms are starting to flatten out. The bars are still not perfectly at 100, because there is still sampling error (there always will be). But, if you found a histogram that looked flat and knew that the sample contained many observations, you might be more confident that those numbers came from a uniform distribution.</p>
<p>Just for fun let’s make the samples really big. Say 100,000 observations per sample. Here, we should expect that each number occurs about 10,000 times each. What happens?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5sampunifALOT" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5sampunifALOT-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.8: Histograms for different samples from a uniform distribution. N = 100,000 for each sample.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-5sampunifALOT">Figure&nbsp;<span>5.8</span></a> shows that the histograms for each sample are starting to look the same. They all have 100,000 observations, and this gives chance enough opportunity to equally distribute the numbers, roughly making sure that they all occur very close to the same amount of times. As you can see, the bars are all very close to 10,000, which is where they should be if the sample came from a uniform distribution.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pro tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The pattern behind a sample will tend to stabilize as sample-size increases. Small samples will have all sorts of patterns because of sampling error (chance).</p>
</div>
</div>
<p>Before getting back to the topic of experiments that we started with, let’s ask two more questions. First, which of the two samples in <a href="#fig-5whichoneB">Figure&nbsp;<span>5.9</span></a> do you think came from a uniform distribution? FYI, each of these samples had 20 observations each.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5whichoneB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5whichoneB-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.9: Which of these samples came from a uniform distribution?</figcaption>
</figure>
</div>
</div>
</div>
<p>If you are not confident in the answer, this is because <strong>sampling error</strong> (randomness) is fuzzing with the histograms.</p>
<p>Here is the very same question, only this time we will take 1,000 observations for each sample. Which histogram in <a href="#fig-5whichoneC">Figure&nbsp;<span>5.10</span></a> do you think came from a uniform distribution, which one did not?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5whichoneC" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5whichoneC-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.10: Which of these samples came from a uniform distribution?</figcaption>
</figure>
</div>
</div>
</div>
<p>Now that we have increased N, we can see the pattern in each sample becomes more obvious. The histogram for sample 1 has bars near 100, not perfectly flat, but it resembles a uniform distribution. The histogram for sample 2 is not flat looking at all.</p>
<p>By comparing the two histograms, we have already performed a basic statistical inference — we inferred that sample 2 did not come from a uniform distribution. This is the same logic underlying the formal tests covered in later chapters: arrange the data to make the source distribution visible, then judge whether the observed pattern is consistent with a hypothesized one.</p>
<!--
## Playing with distributions

talk about a few different distribution. Embed shiny app

SHINY APP here

-->
</section>
</section>
<section id="is-there-a-difference" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="is-there-a-difference"><span class="header-section-number">5.3</span> Is there a difference?</h2>
<p>Let’s get back to experiments. In an experiment we want to know if an independent variable (our manipulation) causes a change in a dependent variable (measurement). If this occurs, then we will expect to see some differences in our measurement as a function of the manipulation.</p>
<p>Consider the light switch example:</p>
<hr>
<p><strong>Light Switch Experiment</strong>: You manipulate the switch up (condition 1 of independent variable), light goes on (measurement). You manipulate the switch down (condition 2 of independent variable), light goes off (another measurement). The measurement (light) changes (goes off and on) as a function of the manipulation (moving switch up or down).</p>
<p>You can see the change in measurement between the conditions, it is as obvious as night and day. So, when you conduct a manipulation, and can see the difference (change) in your measure, you can be pretty confident that your manipulation is causing the change.</p>
<blockquote class="blockquote">
<p>note: to be cautious we can say “something” about your manipulation is causing the change, it might not be what you think it is if your manipulation is very complicated and involves lots of moving parts.</p>
</blockquote>
<hr>
<section id="chance-can-produce-differences" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="chance-can-produce-differences"><span class="header-section-number">5.3.1</span> Chance can produce differences</h3>
<p>Random chance can produce apparent differences between groups even when no real difference exists. We have already seen this with sampling: two samples from the same distribution come out differently. The same principle applies when we compare group means. This is a fundamental problem for inference.</p>
<p>To make this concrete, consider a scenario where we expect to find no real difference. A researcher samples pH at 10 randomly selected sites from a stream network. All 10 sites are drawn from the same population — there is no treatment, no environmental gradient, no systematic difference between them. The sites are arbitrarily divided into two groups of 5 (Group A and Group B). Even though there is no real difference, we might still observe a difference in mean pH between the two groups simply because of sampling error.</p>
<p>Here is data from one run of this scenario:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">ph</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">7.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: right;">5.85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">7.88</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: right;">7.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">7.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">6.78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: right;">7.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">6.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: right;">6.88</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">7.48</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>This is a long-format table. Each row is one site. The first column shows the group assignment, and the second shows the pH reading. Did Group A have a higher mean pH than Group B?</p>
<p>It is easier to see the comparison in a bar graph (<a href="#fig-5gumballA">Figure&nbsp;<span>5.11</span></a>), which shows the mean pH for each group.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5gumballA" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5gumballA-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.11: Mean pH for Group A and Group B sampled randomly from the same stream population.</figcaption>
</figure>
</div>
</div>
</div>
<p>The bars are not the same height. Group A and Group B have different mean pH values. Does this mean there is a real environmental difference between the groups? No — both groups were drawn from the same population. The difference is an artifact of sampling error. This is the core inference problem: differences appear even when nothing real caused them. <strong>How can we tell whether an observed difference is real or just the result of chance?</strong></p>
</section>
<section id="differences-due-to-chance-can-be-simulated" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="differences-due-to-chance-can-be-simulated"><span class="header-section-number">5.3.2</span> Differences due to chance can be simulated</h3>
<p>Just as we showed that chance can produce spurious correlations with limited reach, we can characterize exactly what chance is capable of producing in a comparison of group means. Once we know what chance typically does — and what it cannot do — we have a basis for judging whether our observed difference falls within or outside its range.</p>
<p>The first step is to replicate the sampling scenario many times. <a href="#fig-5gumballsims">Figure&nbsp;<span>5.12</span></a> shows bar graphs of mean pH for Group A and Group B across 10 replications of the same experiment — all 10 sites sampled from the same population, split 5+5, and means computed.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5gumballsims" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5gumballsims-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.12: 10 simulated replications of sampling pH at 10 stream sites and splitting them arbitrarily into two groups of 5. Each replication gives a slightly different answer. Any difference between the bars is due to chance, not to a real environmental difference.</figcaption>
</figure>
</div>
</div>
</div>
<p>These 10 replications show that chance produces different mean differences each time. Sometimes Group A is higher, sometimes Group B is higher, sometimes the means are nearly equal. All of this variation arises from sampling error alone — there is no real difference in the population.</p>
</section>
</section>
<section id="chance-makes-some-differences-more-likely-than-others" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="chance-makes-some-differences-more-likely-than-others"><span class="header-section-number">5.4</span> Chance makes some differences more likely than others</h2>
<p>We have seen that chance can produce group mean differences. But we still need to characterize what chance usually does and what it rarely does. If we can establish the range of differences that chance produces, we can build a window: differences inside the window could plausibly have arisen by chance; differences outside the window could not.</p>
<p>We summarize each replication as a single <strong>difference score</strong>: mean pH for Group A minus mean pH for Group B. <a href="#fig-5gumballdiffs">Figure&nbsp;<span>5.13</span></a> shows those difference scores for the 10 replications above.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5gumballdiffs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5gumballdiffs-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.13: Difference in mean pH between Group A and Group B across 10 replications. The true difference is zero, but sampling error produces non-zero differences each time.</figcaption>
</figure>
</div>
</div>
</div>
<p>A bar at zero means the two groups had the same mean pH in that replication. Positive values indicate Group A was higher; negative values indicate Group B was higher. The signs of the differences would flip if we reversed the subtraction order.</p>
<p>The differences in these 10 replications mostly fall in a narrow range. To better characterize what chance can do, we run 100 replications. The results are shown in <a href="#fig-5manydiffs">Figure&nbsp;<span>5.14</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5manydiffs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5manydiffs-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.14: Difference in mean pH between Group A and Group B across 100 replications. There are many possible differences that chance can produce, but the y-axis shows the range is bounded.</figcaption>
</figure>
</div>
</div>
</div>
<p>The x-axis spans 100 experiments and is difficult to read, but the important information is on the y-axis. Many different difference sizes occur, but the range is bounded — very large differences (say, greater than 0.5 pH units in either direction) do not appear. This begins to define the window of what chance can produce.</p>
<p>To get a clearer picture, we now run 10,000 replications and plot the distribution of difference scores as a histogram. This gives a precise view of which differences happen often and which are extremely rare.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5histdiffgumball" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5histdiffgumball-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.15: Histogram of mean pH differences between Group A and Group B over 10,000 replications. All differences arise from chance alone. The most frequent difference is near zero; larger differences occur less often. Chance cannot produce everything.</figcaption>
</figure>
</div>
</div>
</div>
<p>This histogram is the <strong>chance window</strong> for this study design. It shows that chance most often produces a difference near zero — that is the tallest bar in the center. Larger differences in either direction occur less and less frequently. The distribution has a clear boundary: extreme differences are possible but very rare.</p>
<p>We can use this window to evaluate any observed difference. If a study found a mean pH difference of 0.1 between two groups, that falls well inside the chance window — differences of that size occur frequently by random sampling alone. If the study found a difference of 0.6, that would fall far outside the window; chance produced a difference that large 0 times out of 10,000. When an observed result almost never happens by chance, we have grounds to conclude that something other than chance produced it.</p>
</section>
<section id="simulation-based-inference" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="simulation-based-inference"><span class="header-section-number">5.5</span> Simulation-Based Inference</h2>
<p>We are going to be doing a lot of inference throughout the rest of this course. Pretty much all of it will come down to one question. Did chance produce the differences in my data? We will be talking about experiments mostly, and in experiments we want to know if our manipulation caused a difference in our measurement. But, we measure things that have natural variability, so every time we measure things we will always find a difference. We want to know if the difference we found (between our experimental conditions) could have been produced by chance. If chance is a very unlikely explanation of our observed difference, we will make the inference that chance did not produce the difference, and that something about our experimental manipulation did produce the difference. This is it (for this textbook).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Statistics is not only about determining whether chance could have produced a pattern in the observed data. The same tools we are talking about here can be generalized to ask whether any kind of distribution could have produced the differences. This allows comparisons between different models of the data, to see which one was the most likely, rather than just rejecting the unlikely ones (e.g., chance). But, we’ll leave those advanced topics for another textbook.</p>
</div>
</div>
<p>The simulation-based approach introduced here answers the same question as every formal test in later chapters: <strong>could chance alone have produced the observed difference?</strong> The advantage of starting here is transparency — every step is explicit and the logic is visible before any formulas are introduced.</p>
<section id="intuitive-methods" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="intuitive-methods"><span class="header-section-number">5.5.1</span> Intuitive methods</h3>
<p>The approach in this section uses only simple arithmetic operations that you already understand to build a tool for inference. Specifically, we will use:</p>
<ol type="1">
<li>Sampling numbers randomly from a distribution</li>
<li>Adding and subtracting</li>
<li>Division, to find the mean</li>
<li>Counting</li>
<li>Graphing and drawing lines</li>
<li>NO FORMULAS</li>
</ol>
</section>
<section id="part-1-frequency-based-intuition-about-occurrence" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="part-1-frequency-based-intuition-about-occurrence"><span class="header-section-number">5.5.2</span> Part 1: Frequency based intuition about occurrence</h3>
<p><strong>Question</strong>: How many times does something need to happen for it to happen a lot? Or, how many times does something need to happen for it to happen not very much, or even really not at all? Small enough for you to not worry about it at all happening to you?</p>
<p>Would you go outside every day if you thought that you would be hit by lightning 1 out of 10 times? At those odds, a person going out daily would expect to be struck more than 30 times per month. 1 in 10 is a high-risk threshold by any practical standard.</p>
<p>Would you go outside every day if you thought lightning would strike 1 out of every 100 days? At that rate, someone going out every day would expect roughly 3–4 strikes per year. Most people would sharply limit their outdoor exposure at 1-in-100 odds.</p>
<p>Would you go outside every day at 1-in-1000 odds? At that frequency, a person going outside daily would expect to be struck roughly once every 3 years. Risk accumulates meaningfully even at odds that initially seem small.</p>
<p>What about 1 in 10,000 days? That translates to roughly one strike every 27 years. At 1-in-10,000 odds, risk accumulates slowly — a person would expect to be struck roughly 36 times per year at 1-in-10 odds, but only once across a lifetime at 1-in-10,000 odds. The practical consequences of different probability thresholds are very different.</p>
<p>At 1 in 100,000 days — about 273 years — most people would not modify their behavior at all. The probability is so low as to be negligible for practical planning.</p>
<p>The point of considering these questions is to get a sense for yourself of what happens a lot, and what doesn’t happen a lot, and how you would make important decisions based on what happens a lot and what doesn’t.</p>
</section>
<section id="part-2-simulating-chance" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="part-2-simulating-chance"><span class="header-section-number">5.5.3</span> Part 2: Simulating chance</h3>
<p>This next part could happen a bunch of ways, so I’ll make some simplifying assumptions to keep things clear. We’ve already been introduced to simulating things, so we’ll do that again. Here is what we will do. Say we are an environmental scientist monitoring total suspended particulate concentrations (µg/m³) at air quality stations across a region. From prior monitoring work, we know that when we sample particulate levels across similar sites, our measurements tend to have a particular mean and standard deviation. Let’s say the mean is usually 100 µg/m³, and the standard deviation is usually 15 µg/m³. In this case, I don’t care about using these numbers as estimates of the population parameters, I’m just thinking about what my samples usually look like. What I want to know is how they behave when I sample them. I want to see what kind of samples happen a lot, and what kind of samples don’t happen a lot. Now, when we run studies to see whether something like a pollution source or land-use type changes particulate levels, we usually have a limited number of monitoring sites available. Let’s say we can instrument 20 sites in each of two treatment areas. Let’s keep the study simple, with two groups, so we will need 40 total sites.</p>
<p>I would like to learn something to help me with inference. One thing I would like to learn is what the sampling distribution of the sample mean looks like. This distribution tells me what kinds of mean values happen a lot, and what kinds don’t happen very often. But, I’m actually going to skip that bit. Because what I’m really interested in is what the <strong>sampling distribution of the difference between my sample means</strong> looks like. After all, I am going to run a study with 20 monitoring sites in one group and 20 in another. Then I am going to calculate the mean particulate concentration for group A and the mean for group B, and I’m going to look at the difference. I will probably find a difference, but my question is, did the environmental condition (e.g., proximity to an industrial source) cause this difference, or is this the kind of thing that happens a lot by chance? If I knew what chance can do, and how often it produces differences of particular sizes, I could look at the difference I observed, then look at what chance can do, and then I can make a decision! If my difference doesn’t happen a lot (we’ll get to how much not a lot is in a bit), then I might be willing to believe that the environmental condition caused a difference. If my difference happens all the time by chance alone, then I wouldn’t be inclined to think anything other than sampling error caused the difference.</p>
<p>So, here’s what we’ll do, even before running the study. We’ll do a simulation. We will sample numbers for group A and Group B, then compute the means for group A and group B, then we will find the difference in the means between group A and group B. But, we will do one very important thing. We will pretend that the two groups are actually the same — no real environmental difference between them. If we do this (do nothing, no manipulation that could cause a difference), then we know that <strong>only sampling error</strong> could cause any differences between the mean of group A and group B. We’ve eliminated all other causes, only chance is left. By doing this, we will be able to see exactly what chance can do. More importantly, we will see the kinds of differences that occur a lot, and the kinds that don’t occur a lot.</p>
<p>Before running the simulation, we need to define a threshold: how rare does a result need to be before we consider it unlikely to have occurred by chance? We will use 10,000 repetitions as our reference. An event that occurs 1 time out of 10,000 is considered extremely unlikely.</p>
<p>OK, now we have our number, we are going to simulate the possible mean differences between group A and group B that could arise by chance. We do this 10,000 times. This gives chance a lot of opportunity to show us what it does do, and what it does not do.</p>
<p>This is what I did: I sampled 20 numbers into group A (say, sites near an industrial source) and 20 into group B (background sites), but both groups are drawn from the <strong>same</strong> normal distribution — mean = 100 µg/m³, standard deviation = 15 µg/m³ — because we’re simulating the null scenario where there’s no real difference. Because the samples are coming from the same distribution, we expect that on average they will be similar (but we already know that samples differ from one another). Then, I compute the mean for each sample, and compute the difference between the means. I save the <strong>mean difference score</strong>, and end up with 10,000 of them. Then, I draw the histogram in <a href="#fig-5simdiff">Figure&nbsp;<span>5.16</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5simdiff" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5simdiff-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.16: Histogram of mean differences in particulate concentration (µg/m³) arising by chance when both groups are sampled from the same distribution.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Of course, we might recognize that chance could do a difference greater than 15. We just didn’t give it the opportunity. We only ran the simulation 10,000 times. If we ran it a million times, maybe a difference greater than 15 or even 20 would happen a couple times. If we ran it a bazillion gazillion times, maybe a difference greater than 30 would happen a couple times. If we go out to infinity, then chance might produce all sorts of bigger differences once in a while. But, we’ve already decided that 1/10,000 is not a lot. So things that happen 0 out of 10,000 times, like differences greater than 15, are considered to be extremely unlikely.</p>
</div>
</div>
<p>Now we can see what chance can do to the size of our mean difference. The x-axis shows the size of the mean difference. We took our samples from the sample distribution, so the difference between them should usually be 0, and that’s what we see in the histogram.</p>
<p>Pause for a second. Why should the mean differences usually be zero, wasn’t the population mean = 100, shouldn’t they be around 100? No.&nbsp;The mean of group A will tend to be around 100, and the mean of group B will tend be around 100. So, the difference score will tend to be 100-100 = 0. That is why we expect a mean difference of zero when the samples are drawn from the same population.</p>
<p>So, differences near zero happen the most, that’s good, that’s what we expect. Bigger or smaller differences happen increasingly less often. Differences greater than 15 or -15 never happen at all. For our purposes, it looks like chance only produces differences between -15 to 15.</p>
<p>OK, let’s ask a couple simple questions. What was the biggest negative number that occurred in the simulation? We’ll use R for this. All of the 10,000 difference scores are stored in a variable I made called <code>difference</code>. If we want to find the minimum value, we use the <code>min</code> function. Here’s the result.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(difference)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -16.60894</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>OK, so what was the biggest positive number that occurred? Let’s use the <code>max</code> function to find out. It finds the biggest (maximum) value in the variable. FYI, we’ve just computed the range, the minimum and maximum numbers in the data. Remember we learned that before. Anyway, here’s the max.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(difference)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 20.6813</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Both of these extreme values only occurred once. Those values were so rare we couldn’t even see them on the histogram, the bar was so small. Also, these biggest negative and positive numbers are pretty much the same size if you ignore their sign, which makes sense because the distribution looks roughly symmetrical.</p>
<p>So, what can we say about these two numbers for the min and max? We can say the min happens 1 times out of 10,000. We can say the max happens 1 times out of 10,000. Is that a lot of times? Not to me. It’s not a lot.</p>
<p>So, how often does a difference of 30 (much larger larger than the max) occur out of 10,000. We really can’t say, 30s didn’t occur in the simulation. Going with what we got, we say 0 out of 10,000. That’s never.</p>
<p>We’re about to move into part three, which involves drawing decision lines and talking about them. The really important part about part 3 is this. What would you say if you ran this experiment once, and found a mean difference of 30? I would say it happens 0 times of out 10,000 by chance. I would say chance did not produce my difference of 30. That’s what I would say. We’re going to expand upon this right now.</p>
</section>
<section id="part-3-judgment-and-decision-making" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="part-3-judgment-and-decision-making"><span class="header-section-number">5.5.4</span> Part 3: Judgment and Decision-making</h3>
<p>We now use the simulated distribution to make a decision about whether the observed difference is consistent with what chance alone could produce. This decision-making structure — compare your result to the distribution of results that chance generates, and judge where your result falls — is the basis for every formal hypothesis test covered in this course.</p>
<p>The simulation gives us a concrete foundation for that judgment. We can see which differences chance produced often, which it produced rarely, and which it never produced at all.</p>
<p>Let’s talk about some objective facts from our simulation of 10,000 things that we definitely know to be true. For example, we can draw some lines on the graph, and label some different regions. We’ll talk about two kinds of regions.</p>
<ol type="1">
<li>Region of chance. Chance did it. Chance could have done it</li>
<li>Region of not chance. Chance didn’t do it. Chance couldn’t have done it.</li>
</ol>
<p>The regions are defined by the minimum value and the maximum value. Chance never produced a smaller or bigger number. The region inside the range is what chance did do, and the the region outside the range on both sides is what chance never did. It looks like <a href="#fig-5simdecision">Figure&nbsp;<span>5.17</span></a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5simdecision" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5simdecision-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.17: Applying decision boundaries to the histogram of mean differences. The boundaries identify what differences chance did or did not produce in the simulation.</figcaption>
</figure>
</div>
</div>
</div>
<p>We have just drawn some lines, and shaded some regions, and made one plan we could use to make decisions. How would the decisions work. Consider a mean difference between groups A and B of 25. Where is 25 in the figure? It’s in the green part. The green region is labeled NOT CHANCE — chance never produced a difference of 25 in 10,000 simulations. If we found a difference of 25, we could confidently conclude that chance did not cause it, and have grounds to consider whether our experimental manipulation produced the effect.</p>
<p>A difference of +10 falls within the red region — the window of what chance did produce in the simulation. Differences inside that window could plausibly have arisen from sampling error alone. A result of +10 does not provide strong grounds for concluding that the manipulation caused the difference.</p>
<p>This is the core logic of statistical inference: compare your observed result to the distribution of results chance could produce. If the observed result falls outside that distribution, chance is an unlikely explanation.</p>
<p>A difference of +10 falls within the chance window and could plausibly be a result of random sampling. A difference of +25 falls outside the window; chance produced that value 0 times out of 10,000. In practice, we use this comparison to decide whether an observed difference warrants further investigation.</p>
<section id="grey-areas" class="level4" data-number="5.5.4.1">
<h4 data-number="5.5.4.1" class="anchored" data-anchor-id="grey-areas"><span class="header-section-number">5.5.4.1</span> Grey areas</h4>
<p>The clean division between “chance” and “not chance” breaks down near the edges of the distribution. We would prefer a simple yes/no answer about whether chance caused our difference, but in practice we have to acknowledge that some differences fall in ambiguous territory. <span class="quarto-unresolved-ref">?fig-5crumpuncertainty</span> illustrates where those grey areas are.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5simuncertainty" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5simuncertainty-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.18: The question marks refer to an area where you have some uncertainty. Differences inside the question mark region do not happen very often by chance. When you find differences of these sizes, should you reject the idea that chance caused your difference? You will always have some uncertainty associated with this decision because it is clear that chance could have caused the difference. But, chance usually does not produce differences of these sizes.</figcaption>
</figure>
</div>
</div>
</div>
<p>I made two grey areas, and they are reddish grey, because we are still in the chance window. There are question marks (?) in the grey areas. Why? The question marks reflect some uncertainty that we have about those particular differences. For example, if you found a difference that was in a grey area, say a 15. 15 is less than the maximum, which means chance did create differences of around 15. But, differences of 15 don’t happen very often.</p>
<p>What can you conclude or say about this 15 you found? Can you say without a doubt that chance did not produce the difference? Of course not, you know that chance could have. Still, it’s one of those things that doesn’t happen a lot. That makes chance an unlikely explanation. Instead of thinking that chance did it, you might be willing to take a risk and say that your experimental manipulation caused the difference. You’d be making a bet that it wasn’t chance…but, could be a safe bet, since you know the odds are in your favor.</p>
<p>The boundaries of the grey area reflect the researcher’s tolerance for uncertainty. More conservative thresholds reduce false positives; more permissive ones reduce false negatives. The formal hypothesis testing framework (covered in Chapter 6) provides a standardized approach to this trade-off.</p>
<p>Another thing to think about is your decision policy. What will you do, when your observed difference is in your grey area? Will you always make the same decision about the role of chance? Or, will you sometimes flip-flop depending on how you feel. Perhaps, you think that there shouldn’t be a strict policy, and that you should accept some level of uncertainty. The difference you found could be a real one, or it might not. There’s uncertainty, hard to avoid that.</p>
<p>So let’s illustrate one more kind of strategy for making decisions. We just talked about one that had some lines, and some regions. This makes it seem like a binary choice: we can either rule out, or not rule out the role of chance. Another perspective is that everything is a different shade of grey, like in <a href="#fig-5simshade">Figure&nbsp;<span>5.19</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5simshade" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5simshade-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.19: The shading of the blue bars indicates levels of confidence in whether a difference could have been produced by chance. Darker bars represent increased confidence that the difference was not produced by chance. Bars get darker as the mean difference increases in absolute value.</figcaption>
</figure>
</div>
</div>
</div>
<p>OK, so I made it shades of blue (because it was easier in R). Now we can see two decision plans at the same time. Notice that as the bars get shorter, they also get become a darker stronger blue. The color can be used as a guide for your confidence. That is, your confidence in the belief that your manipulation caused the difference rather than chance. If you found a difference near a really dark bar, those don’t happen often by chance, so you might be really confident that chance didn’t do it. If you find a difference near a slightly lighter blue bar, you might be slightly less confident. That is all. You run your experiment, you get your data, then you have some amount of confidence that it wasn’t produced by chance. This way of thinking is elaborated to very interesting degrees in the Bayesian world of statistics. We don’t wade too much into that, but mention it a little bit here and there. It’s worth knowing it’s out there.</p>
</section>
<section id="making-decisions-and-being-wrong" class="level4" data-number="5.5.4.2">
<h4 data-number="5.5.4.2" class="anchored" data-anchor-id="making-decisions-and-being-wrong"><span class="header-section-number">5.5.4.2</span> Making decisions and being wrong</h4>
<p>No matter how you plan to make decisions about your data, you will always be prone to making some mistakes. You might call one finding real, when in fact it was caused by chance. This is called a <strong>type I</strong> error, or a false positive. You might ignore one finding, calling it chance, when in fact it wasn’t chance (even though it was in the window). This is called a <strong>type II</strong> error, or a false negative.</p>
<p>How you make decisions can influence how often you make errors over time. If you are a researcher, you will run lots of experiments, and you will make some amount of mistakes over time. If you do something like the very strict method of only accepting results as real when they are in the “no chance” zone, then you won’t make many type I errors. Pretty much all of your result will be real. But, you’ll also make type II errors, because you will miss things real things that your decision criteria says are due to chance. The opposite also holds. If you are willing to be more liberal, and accept results in the grey as real, then you will make more type I errors, but you won’t make as many type II errors. Under the decision strategy of using these cutoff regions for decision-making there is a necessary trade-off. The Bayesian view get’s around this a little bit. Bayesians talk about updating their beliefs and confidence over time. In that view, all you ever have is some level of confidence about whether something is real, and by running more experiments you can increase or decrease your level of confidence. This, in some fashion, avoids some trade-off between type I and type II errors.</p>
<p>Regardless, there is another way to reduce type I and type II errors, and to increase your confidence in your results, even before you do the experiment. It’s called “knowing how to design a good experiment”.</p>
</section>
</section>
<section id="part-4-experiment-design" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="part-4-experiment-design"><span class="header-section-number">5.5.5</span> Part 4: Experiment Design</h3>
<p>Study design directly controls the sensitivity of the analysis. It is often possible — and important — to choose a design that is sensitive to the size of effect you care about detecting.</p>
<p>Two forces govern whether a study can detect a real effect: the size of the effect and the amount of noise in the data. The design choices you make — primarily sample size — determine how much noise obscures the signal.</p>
<p>Recall what happens to the sampling distribution of the mean as sample size increases: the distribution narrows. The same is true for the distribution of mean differences. As N increases, the range of differences that chance produces shrinks. At very large N, chance produces only very small differences. This means that with a large enough sample, even small real effects can be reliably distinguished from noise.</p>
<p>For example, we could run our experiment with 20 subjects in each group. Or, we could decide to invest more time and run 40 subjects in each group, or 80, or 150. When you are the experimenter, you get to decide the design. These decisions matter big time. Basically, the more subjects you have, the more sensitive your experiment. With bigger N, you will be able to reliably detect smaller mean differences, and be able to confidently conclude that chance did not produce those small effects.</p>
<p>Check out the histograms in <a href="#fig-5sampleDistNormal">Figure&nbsp;<span>5.20</span></a>. This is the same simulation as before, but with four different sample-sizes: 20, 40, 80, 160. We are doubling our sample-size across each simulation just to see what happens to the width of the chance window.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5sampleDistNormal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5sampleDistNormal-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.20: The range or width of the differences produced by chance shrinks as sample-size increases.</figcaption>
</figure>
</div>
</div>
</div>
<p>There you have it. The <strong>sampling distribution of the mean differences</strong> shrinks toward 0 as sample-size increases. This means if you run an experiment with a larger sample-size, you will be able to detect smaller mean differences, and be confident they aren’t due to chance. <a href="#tbl-5minmax">Table&nbsp;<span>5.2</span></a> contains the minimum and maximum values that chance produced across the four sample-sizes:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-5minmax" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;5.2: The smallest and largest mean differences produced by chance as a function of sample-size.</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">sample_size</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">smallest</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">largest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">20</td>
<td style="text-align: right;">-24.19486</td>
<td style="text-align: right;">21.89654</td>
</tr>
<tr class="even">
<td style="text-align: right;">40</td>
<td style="text-align: right;">-16.18592</td>
<td style="text-align: right;">15.69097</td>
</tr>
<tr class="odd">
<td style="text-align: right;">80</td>
<td style="text-align: right;">-10.11355</td>
<td style="text-align: right;">10.85447</td>
</tr>
<tr class="even">
<td style="text-align: right;">160</td>
<td style="text-align: right;">-11.25008</td>
<td style="text-align: right;">11.40671</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>The table shows the range of chance behavior is very wider for smaller N and narrower for larger N. Consider what this narrowing means for your study design. For example, one aspect of the design is the choice of sample size, N — in an environmental study, this might be the number of monitoring sites, field plots, or sampling events.</p>
<p>If it turns out your manipulation will cause a difference of +11, then what should you do? Run an experiment with N = 20 people? I hope not. If you did that, you could get a mean difference of +11 fairly often by chance. However, if you ran the experiment with 160 people, then you would definitely be able to say that +11 was not due to chance, it would be outside the range of what chance can do. You could even consider running the experiment with 80 subjects. A +11 there wouldn’t happen often by chance, and you’d be cost-effective, spending less time on the experiment.</p>
<p>The point is: <strong>the design of the experiment determines the sizes of the effects it can detect</strong>. If you want to detect a small effect. Make your sample size bigger. It’s really important to say this is not the only thing you can do. You can also make your cell-sizes bigger. For example, often times we take several measurements from a single subject. The more measurements you take (cell-size), the more stable your estimate of the subject’s mean. We discuss these issues more later. You can also make a stronger manipulation, when possible.</p>
</section>
<section id="part-5-i-have-the-power" class="level3" data-number="5.5.6">
<h3 data-number="5.5.6" class="anchored" data-anchor-id="part-5-i-have-the-power"><span class="header-section-number">5.5.6</span> Part 5: I have the power</h3>
<p><strong>Statistical power</strong> is the probability that a study will detect a real effect when one exists. A well-powered study is designed so that the sampling distribution of the test statistic — under the assumption that the effect is real — falls reliably outside the null distribution. The key driver of power is sample size: larger samples narrow the null distribution, making real effects easier to distinguish from chance.</p>
<p>We have already seen this principle in action. The number of observations in the study changes the sensitivity of the design: more observations means the distribution of chance differences shrinks, which makes it possible to detect smaller real effects.</p>
<p>Let’s take a look at one more plot. What we will do is simulate a measure of sensitivity across a whole bunch of sample sizes, from 10 to 300. We’ll do this in steps of 10. For each simulation, we’ll compute the mean differences as we have done. But, rather than showing the histogram, we’ll just compute the smallest value and the largest value. This is a pretty good measure of the outer reach of chance. Then we’ll plot those values as a function of sample size and see what we’ve got.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5simminmax" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5simminmax-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.21: A graph of the maximum and minimum mean differences produced by chance as a function of sample-size. The range narrows as sample-size increases showing that chance alone produces a smaller range of mean differences as sample-size increases.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-5simminmax">Figure&nbsp;<span>5.21</span></a> shows a reasonably precise window of sensitivity as a function of sample size. For each sample size, we can see the maximum difference that chance produced and the minimum difference. In those simulations, chance never produced bigger or smaller differences. So, each design is sensitive to any difference that is underneath the bottom line, or above the top line.</p>
<p>Here’s another way of putting it. Which of the sample sizes will be sensitive to a difference of +10 or -10. That is, if a difference of +10 or -10 was observed, then we could very confidently say that the difference was not due to chance, because according to these simulations, chance never produced differences that big. To help us see which ones are sensitive, <a href="#fig-5simredline">Figure&nbsp;<span>5.22</span></a> draws horizontal lines at -10 and +10.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5simredline" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5simredline-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.22: The red line represents the size of a mean difference that a researcher may be interested in detecting. All of the dots outside (above or below) the red line represent designs with small sample-sizes. When a difference of 10 occurs for these designs, we can rule out chance with confidence. The dots between the red lines represent designs with larger sample-sizes. These designs never produce differences as large as 10, so when those differences occur, we can be confident chance did not produce them.</figcaption>
</figure>
</div>
</div>
</div>
<p>Based on visual guesstimation, the designs with sample-size &gt;= 100 are all sensitive to real differences of 10. Designs with sample-size &gt; 100 all failed to produce extreme differences outside of the red lines by chance alone. If these designs were used, and if an effect of 10 or larger was observed, then we could be confident that chance alone did not produce the effect. Designing your experiment so that you know it is sensitive to the thing you are looking for is the big idea behind power.</p>
</section>
<section id="summary-of-simulation-based-inference" class="level3" data-number="5.5.7">
<h3 data-number="5.5.7" class="anchored" data-anchor-id="summary-of-simulation-based-inference"><span class="header-section-number">5.5.7</span> Summary of Simulation-Based Inference</h3>
<p>What did we learn from this simulation-based approach? We learned the basics of what we’ll be doing moving forward — and we did it all without any hard math or formulas. We sampled numbers, computed means, subtracted means between conditions, then repeated that process many times and counted up the mean differences and put them in a histogram. This showed us what chance can do in a study. Then, we discussed how to make decisions around these facts. And, we showed how we can control the role of chance just by changing things like sample size.</p>
</section>
</section>
<section id="the-randomization-test-permutation-test" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="the-randomization-test-permutation-test"><span class="header-section-number">5.6</span> The randomization test (permutation test)</h2>
<p>Welcome to the first official inferential statistic in this textbook. Up till now we have been building some intuitions for you. Next, we will get slightly more formal and show you how we can use random chance to tell us whether our experimental finding was likely due to chance or not. We do this with something called a randomization test. The ideas behind the randomization test are the very same ideas behind the rest of the inferential statistics that we will talk about in later chapters. And, surprise, we have already talked about all of the major ideas already. Now, we will just put the ideas together, and give them the name <strong>randomization test</strong>.</p>
<p>Here’s the big idea. When you run an experiment and collect some data you get to find out what happened that one time. But, because you ran the experiment only once, you don’t get to find out what <strong>could have happened</strong>. The randomization test is a way of finding out what <strong>could have happened</strong>. And, once you know that, you can compare <strong>what did happen</strong> in your experiment, with <strong>what could have happened</strong>.</p>
<section id="pretend-example-does-distance-from-a-highway-affect-no₂-levels" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="pretend-example-does-distance-from-a-highway-affect-no₂-levels"><span class="header-section-number">5.6.1</span> Pretend example: does distance from a highway affect NO₂ levels?</h3>
<p>Let’s say you are monitoring nitrogen dioxide (NO₂) concentrations at air quality sites near a major highway. You assign 20 monitoring sites to a “near” group (within 50 m of the highway) and 20 different sites to a “far” group (500 m or more from the highway). If highway traffic is a meaningful source of NO₂, then the near group should have higher concentrations on average than the far group.</p>
<p>Let’s say the data looked like this:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near_ppb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far_ppb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">55</td>
<td style="text-align: left;">33</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">55</td>
<td style="text-align: left;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">59</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">46</td>
<td style="text-align: left;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">57</td>
<td style="text-align: left;">26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">59</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">38</td>
<td style="text-align: left;">31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">38</td>
<td style="text-align: left;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: left;">62</td>
<td style="text-align: left;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: left;">46</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">38</td>
<td style="text-align: left;">31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">1032</td>
<td style="text-align: left;">473</td>
</tr>
<tr class="even">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">51.6</td>
<td style="text-align: left;">23.65</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>So, did the near-highway sites have higher NO₂ than the far sites? Look at the mean concentrations at the bottom of the table. The mean for near sites was 51.6 ppb, and the mean for far sites was 23.65 ppb. Just looking at the means, it looks like proximity to the highway matters!</p>
<p>“But wait — could this just be chance?” Even if this were real data, you might wonder: maybe the near sites just happened to be in a windier or more industrialized area, so their higher readings reflect those conditions rather than the highway itself. Or maybe the difference between the groups happened simply because of random sampling variation. We agree this is a legitimate concern. Let’s take a closer look. We already know how the data came out. What we want to know is how they <em>could have</em> come out — what are all the possibilities?</p>
<p>For example, the data would have come out a bit different if some of the sites from the near group had been placed in the far group, and vice versa. Think of all the ways you could have assigned the 40 sites to two groups — there are lots of ways. And, the means for each group would turn out differently depending on how the sites are assigned.</p>
<p>Practically speaking, it’s not possible to run the experiment every possible way, that would take too long. But, we can nevertheless estimate how all of those experiments might have turned out using simulation.</p>
<p>We take all 40 NO₂ readings from both groups and pool them together. Then we randomly assign 20 to a ‘near’ group and 20 to a ‘far’ group — as if the original assignment had been done differently. We compute the new group means and their difference. We repeat this process many times to build up a picture of what the difference could have been under random assignment.</p>
<section id="doing-the-randomization" class="level4" data-number="5.6.1.1">
<h4 data-number="5.6.1.1" class="anchored" data-anchor-id="doing-the-randomization"><span class="header-section-number">5.6.1.1</span> Doing the randomization</h4>
<p>Before we do that, let’s show how the randomization part works. We’ll use fewer numbers to make the process easier to look at. Here are the first 5 NO₂ readings from each group.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near_ppb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far_ppb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">55</td>
<td style="text-align: left;">33</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">278</td>
<td style="text-align: left;">119</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">55.6</td>
<td style="text-align: left;">23.8</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Things could have turned out differently if some of the near-highway sites had been placed in the far group instead, and vice versa. Here’s how we can do some random switching using R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>all_readings      <span class="ot">&lt;-</span> <span class="fu">c</span>(near[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>], far[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>randomize_scores  <span class="ot">&lt;-</span> <span class="fu">sample</span>(all_readings)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>new_near          <span class="ot">&lt;-</span> randomize_scores[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>new_far           <span class="ot">&lt;-</span> randomize_scores[<span class="dv">6</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(new_near)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 58 55 33 49 12</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(new_far)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 63 53 27 30 17</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have taken the first 5 readings from each group and put them all into a variable called <code>all_readings</code>. Then we use the <code>sample</code> function in R to shuffle the readings. Finally, we take the first 5 readings from the shuffled numbers and put them into <code>new_near</code>, and the last five into <code>new_far</code>.</p>
<p>If we do this a couple of times and put them in a table, we can indeed see that the means for each group would be different if the sites were shuffled around. Check it out:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near_ppb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far_ppb</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">near3</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">far3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">55</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">55</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">58</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">53</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">49</td>
<td style="text-align: left;">30</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">55</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">278</td>
<td style="text-align: left;">119</td>
<td style="text-align: left;">210</td>
<td style="text-align: left;">187</td>
<td style="text-align: left;">151</td>
<td style="text-align: left;">246</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">55.6</td>
<td style="text-align: left;">23.8</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;">37.4</td>
<td style="text-align: left;">30.2</td>
<td style="text-align: left;">49.2</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="simulating-the-mean-differences-across-the-different-randomizations" class="level4" data-number="5.6.1.2">
<h4 data-number="5.6.1.2" class="anchored" data-anchor-id="simulating-the-mean-differences-across-the-different-randomizations"><span class="header-section-number">5.6.1.2</span> Simulating the mean differences across the different randomizations</h4>
<p>In our pretend study we found that the mean NO₂ for near-highway sites was 51.6 ppb, and for far sites was 23.65 ppb. The mean difference (near − far) was 27.95 ppb. This is a pretty big difference. This is <strong>what did happen</strong>. But, <strong>what could have happened</strong>? If we tried out all the possible ways to assign 40 sites to two groups, what does the distribution of the possible mean differences look like? Let’s find out. This is what the randomization test is all about.</p>
<p>When we do our randomization test we will measure the mean difference in NO₂ between the near and far groups. Every time we randomize we will save the mean difference.</p>
<p>Let’s look at a short animation of what is happening in the randomization test. <a href="#fig-5randtest">Figure&nbsp;<span>5.23</span></a> shows data from a different fake study, but the principles are the same. We’ll return to the NO₂ example after the animation. The animation is showing three important things. First, the purple dots show the mean values in two groups (lower-exposure vs.&nbsp;higher-exposure sites). It looks like there is a difference, as 1 dot is lower than the other. We want to know if chance could produce a difference this big. At the beginning of the animation, the light green and red dots show the individual readings from each of 10 sites in each group (the purple dots are the means of these original readings). Now, during the randomizations, we randomly shuffle the original readings between the groups. You can see this happening throughout the animation, as the green and red dots appear in different random combinations. The moving yellow dots show you the new means for each group after the randomization. The differences between the yellow dots show you the range of differences that chance could produce.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5randtest" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/gifs/randomizationTest-1.gif" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.23: Animation of a randomization test. The purple dots represent the location of the original sample means in each condition. The yellow dots represent the means of each randomized sample. The blue and red dots show how the original scores are shuffled across each randomization.</figcaption>
</figure>
</div>
</div>
</div>
<p>We are engaging in some visual statistical inference. By looking at the range of motion of the yellow dots, we are watching what kind of differences chance can produce. In this animation, the purple dots, representing the original difference, are generally outside of the range of chance. The yellow dots don’t move past the purple dots, as a result chance is an unlikely explanation of the difference.</p>
<p>If the purple dots were inside the range of the yellow dots, then when would know that chance is capable of producing the difference we observed, and that it does so fairly often. As a result, we should not conclude the manipulation caused the difference, because it could have easily occurred by chance.</p>
<p>Let’s return to the NO₂ example. After we randomize our readings many times and compute the new means and mean differences, we will have loads of mean differences to look at, which we can plot in a histogram. The histogram gives a picture of <strong>what could have happened</strong>. Then, we can compare <strong>what did happen</strong> with <strong>what could have happened</strong>.</p>
<p>Here’s the histogram of the mean differences from the randomization test. For this simulation, we randomized the results from the original study 10,000 times. This is what could have happened. The blue line in <a href="#fig-5randhist">Figure&nbsp;<span>5.24</span></a> shows where the observed difference lies on the x-axis.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5randhist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5randhist-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.24: A histogram of simulated mean differences in NO₂ (ppb) for a randomization test. The blue vertical line marks the observed difference from our study.</figcaption>
</figure>
</div>
</div>
</div>
<p>What do you think? Could the difference represented by the blue line have been caused by chance? My answer is probably not. The histogram shows us the window of chance — the range of differences that random assignment alone can produce. The blue line is not inside that window. This means we can be pretty confident that the difference we observed was not due to chance alone, and is more consistent with a real environmental effect of highway proximity on NO₂.</p>
<p>We are looking at another window of chance. We are seeing a histogram of the kinds of mean differences that could have occurred in our study if we had randomly assigned our 40 sites to the near and far groups differently. As you can see, the mean differences range from negative to positive. The most frequent difference is 0. The distribution appears to be symmetrical about zero. Notice that as the differences get larger (in either direction), they become less frequent. The blue line shows us <strong>the observed difference</strong> from our study. Where is it? It’s way out to the right — well outside the histogram. In other words, when we look at <strong>what could have happened</strong> by chance, we see that <strong>what did happen</strong> doesn’t occur very often by chance alone.</p>
<p><strong>Important:</strong> When we speak of <strong>what could have happened</strong>, we are talking about what could have happened <strong>by chance</strong>. When we compare what did happen to what chance could have done, we can assess whether our result is likely due to chance or something real.</p>
<hr>
<p>OK, let’s pretend we got a much smaller mean difference when we first ran the study. We can draw new lines (blue and red) to represent smaller differences we might have found.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5randquestion" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-Foundation_Inference_files/figure-html/fig-5randquestion-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5.25: Would you expect a mean difference represented by the blue line to occur more or less often by chance compared to the mean difference represented by the red line?</figcaption>
</figure>
</div>
</div>
</div>
<p>Look at the blue line in <a href="#fig-5randquestion">Figure&nbsp;<span>5.25</span></a>. If you found a mean difference of 10 ppb, would you be convinced that this wasn’t caused by chance? As you can see, the blue line is inside the chance window — differences of +10 ppb do happen sometimes by chance. You might infer that the difference was probably not due to chance (it’s on the edge), but you’d be a little skeptical. How about the red line? The red line represents a difference of +5 ppb. If you found a difference of +5 here, would you be confident that it wasn’t caused by chance? No — the red line is well inside the chance window, and this kind of difference happens fairly often. You’d need more evidence before concluding that highway proximity was driving the difference.</p>
</section>
</section>
<section id="take-homes-so-far" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="take-homes-so-far"><span class="header-section-number">5.6.2</span> Take homes so far</h3>
<p>The simulation-based approach developed in this chapter illustrates the core logic of all the formal tests covered later in this course.</p>
<p>Inferential statistics is an attempt to solve the problem: <strong>where did my data come from?</strong> In the randomization test example, our question was: <strong>where did the differences between the means in my data come from?</strong> We know that the differences could be produced by chance alone. We simulated what chance can do using randomization. Then we plotted what chance can do using a histogram. Then, we used that picture to help us make an inference. Did our observed difference come from the chance distribution, or not? When the observed difference is clearly inside the chance distribution, then we can infer that our difference <strong>could have been produced by chance</strong>. When the observed difference is not clearly inside the chance distribution, then we can infer that our difference was <strong>probably not produced by chance</strong>.</p>
<p>These pictures are very, very helpful. If one of our goals is to summarize a bunch of complicated numbers and arrive at an inference, the pictures do a great job. We don’t even need a summary number — we just need to look at the picture and see if the observed difference is inside or outside of the chance window. As we move forward, the main thing we will do is formalize this process and talk more about “standard” inferential statistics. For example, rather than looking at a picture, we will create summary numbers. What if you wanted the probability that your difference could have been produced by chance? That could be a single number. If there was a 95% probability that chance could produce the difference you observed, you might not be very confident that your environmental condition was causing the difference. If there was only 1% probability that chance could produce your difference, you might be much more confident that <strong>chance did not</strong> produce it — and that your variable of interest (highway proximity, pollution source, land use type) actually matters. In order to get there, we will introduce some more foundational tools for statistical inference.</p>
</section>
</section>
<section id="videos" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="videos"><span class="header-section-number">5.7</span> Videos</h2>
<section id="null-and-alternate-hypotheses" class="level3" data-number="5.7.1">
<h3 data-number="5.7.1" class="anchored" data-anchor-id="null-and-alternate-hypotheses"><span class="header-section-number">5.7.1</span> Null and Alternate Hypotheses</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/gJ38qX0ihPc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</section>
<section id="types-of-errors" class="level3" data-number="5.7.2">
<h3 data-number="5.7.2" class="anchored" data-anchor-id="types-of-errors"><span class="header-section-number">5.7.2</span> Types of Errors</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/zhhDCFPzlkw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-SamplesPopulations.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-Hypothesis_Testing.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>