<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory Barnes">

<title>6&nbsp; t-tests – Statistics for Environmental Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-Nonparametric.html" rel="next">
<link href="./05-Hypothesis_Testing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="6&nbsp; t-tests – Statistics for Environmental Science">
<meta property="og:description" content="">
<meta property="og:image" content="06-ttests_files/figure-html/fig-6-z-vs-t-linear-log-1.png">
<meta property="og:site_name" content="Statistics for Environmental Science">
<meta property="og:image:alt" content="Two stacked panels showing the same three overlaid curves: the standard normal, t with 10 degrees of freedom, and t with 2 degrees of freedom. On the linear-scale top panel, all three curves look almost identical, bell-shaped and close together. On the log-scale bottom panel, the same three curves separate clearly in the tails, with the t distribution at 2 degrees of freedom sitting well above the other two far from the center, revealing much heavier tails than the linear panel suggested.">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-ttests.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for Environmental Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inference and Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Errors, Power, and Effect Size</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#intro" id="toc-intro" class="nav-link active" data-scroll-target="#intro"><span class="header-section-number">6.1</span> Intro</a></li>
  <li><a href="#from-z-to-t" id="toc-from-z-to-t" class="nav-link" data-scroll-target="#from-z-to-t"><span class="header-section-number">6.2</span> From <span class="math inline">\(z\)</span> to <span class="math inline">\(t\)</span></a>
  <ul class="collapse">
  <li><a href="#why-t-has-heavier-tails-than-z" id="toc-why-t-has-heavier-tails-than-z" class="nav-link" data-scroll-target="#why-t-has-heavier-tails-than-z"><span class="header-section-number">6.2.1</span> Why <span class="math inline">\(t\)</span> has heavier tails than <span class="math inline">\(z\)</span></a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom"><span class="header-section-number">6.2.2</span> Degrees of freedom</a></li>
  <li><a href="#critical-values" id="toc-critical-values" class="nav-link" data-scroll-target="#critical-values"><span class="header-section-number">6.2.3</span> Critical values</a></li>
  <li><a href="#t-when-h_0-is-true" id="toc-t-when-h_0-is-true" class="nav-link" data-scroll-target="#t-when-h_0-is-true"><span class="header-section-number">6.2.4</span> <span class="math inline">\(t\)</span> when <span class="math inline">\(H_0\)</span> is true</a></li>
  </ul></li>
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test"><span class="header-section-number">6.3</span> One-sample t-test</a>
  <ul class="collapse">
  <li><a href="#calculating-t-from-data" id="toc-calculating-t-from-data" class="nav-link" data-scroll-target="#calculating-t-from-data"><span class="header-section-number">6.3.1</span> Calculating t from data</a></li>
  <li><a href="#interpreting-t" id="toc-interpreting-t" class="nav-link" data-scroll-target="#interpreting-t"><span class="header-section-number">6.3.2</span> Interpreting <span class="math inline">\(t\)</span></a></li>
  <li><a href="#getting-the-p-values-for-t-values" id="toc-getting-the-p-values-for-t-values" class="nav-link" data-scroll-target="#getting-the-p-values-for-t-values"><span class="header-section-number">6.3.3</span> Getting the p-values for <span class="math inline">\(t\)</span>-values</a></li>
  <li><a href="#one-tailed-vs.-two-tailed-applied" id="toc-one-tailed-vs.-two-tailed-applied" class="nav-link" data-scroll-target="#one-tailed-vs.-two-tailed-applied"><span class="header-section-number">6.3.4</span> One-tailed vs.&nbsp;two-tailed, applied</a></li>
  <li><a href="#sec-6assumptions" id="toc-sec-6assumptions" class="nav-link" data-scroll-target="#sec-6assumptions"><span class="header-section-number">6.3.5</span> Assumptions, and what to do when they don’t hold</a></li>
  </ul></li>
  <li><a href="#paired-t-beforeafter-or-matched" id="toc-paired-t-beforeafter-or-matched" class="nav-link" data-scroll-target="#paired-t-beforeafter-or-matched"><span class="header-section-number">6.4</span> Paired t: before/after or matched</a>
  <ul class="collapse">
  <li><a href="#calculate-t" id="toc-calculate-t" class="nav-link" data-scroll-target="#calculate-t"><span class="header-section-number">6.4.1</span> Calculate t</a></li>
  <li><a href="#scaling-to-the-full-sample" id="toc-scaling-to-the-full-sample" class="nav-link" data-scroll-target="#scaling-to-the-full-sample"><span class="header-section-number">6.4.2</span> Scaling to the full sample</a></li>
  </ul></li>
  <li><a href="#two-independent-groups" id="toc-two-independent-groups" class="nav-link" data-scroll-target="#two-independent-groups"><span class="header-section-number">6.5</span> Two independent groups</a></li>
  <li><a href="#simulating-data-for-t-tests" id="toc-simulating-data-for-t-tests" class="nav-link" data-scroll-target="#simulating-data-for-t-tests"><span class="header-section-number">6.6</span> Simulating data for t-tests</a>
  <ul class="collapse">
  <li><a href="#simulating-a-one-sample-t-test" id="toc-simulating-a-one-sample-t-test" class="nav-link" data-scroll-target="#simulating-a-one-sample-t-test"><span class="header-section-number">6.6.1</span> Simulating a one-sample t-test</a></li>
  <li><a href="#simulating-paired-and-independent-samples-tests" id="toc-simulating-paired-and-independent-samples-tests" class="nav-link" data-scroll-target="#simulating-paired-and-independent-samples-tests"><span class="header-section-number">6.6.2</span> Simulating paired and independent-samples tests</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">6.7</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/06-ttests.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 2, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="intro" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="intro"><span class="header-section-number">6.1</span> Intro</h2>
<p>In the early 1900s, William Sealy Gosset worked as a brewer at Guinness, where quality control depended on testing ingredients such as barley and hops. Every test used up beer or ingredients, so Guinness could only test small samples. The statistics of the time relied on the normal (<span class="math inline">\(z\)</span>) distribution, which works when samples are large.</p>
<p>Gosset set out to measure how much extra uncertainty small samples add, and derived a new sampling distribution for it, now known as the <strong>Student’s <span class="math inline">\(t\)</span> distribution</strong>. Guinness restricted outside publication, so he published the 1908 paper under the pseudonym “Student” <span class="citation" data-cites="Student1908">(<a href="references.html#ref-Student1908" role="doc-biblioref">Student 1908</a>)</span>, which is why we still say Student’s <span class="math inline">\(t\)</span>-test. This chapter uses Gosset’s approach. We measure a signal, divide it by its standard error, and compare the resulting <span class="math inline">\(t\)</span> to the <span class="math inline">\(t\)</span> distribution for <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
<p><strong>Why this matters.</strong> We often compare a sample mean to a reference (drinking-water standard, historical average) or compare two conditions (before/after, site A vs site B). A <span class="math inline">\(t\)</span>-test asks whether the observed difference is larger than you would expect from sampling variation alone, given your <span class="math inline">\(n\)</span> and variability. Chapter 5 added two questions to every test: how large the effect is, and whether the design had the power to detect it. Both carry over to the <span class="math inline">\(t\)</span>-tests here.</p>
<p><strong>Three common <span class="math inline">\(t\)</span>-tests you will use.</strong></p>
<ol type="1">
<li><strong>One-sample <span class="math inline">\(t\)</span>-test.</strong> Compare a sample mean to a target (<span class="math inline">\(\mu_0\)</span>).</li>
<li><strong>Paired <span class="math inline">\(t\)</span>-test.</strong> Compare before/after (or matched) measurements on the same units by running a one-sample <span class="math inline">\(t\)</span>-test on the <em>differences</em>.</li>
<li><strong>Independent-samples <span class="math inline">\(t\)</span>-test (also called two-sample <span class="math inline">\(t\)</span>-test).</strong> Compare means from two groups measured on different units. The pooled version assumes the two groups have similar spread; Welch’s version <span class="citation" data-cites="Welch1947">(<a href="references.html#ref-Welch1947" role="doc-biblioref">Welch 1947</a>)</span> does not, and it is what R’s <code>t.test()</code> runs unless you set <code>var.equal = TRUE</code>.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Tip: What you will report">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip: What you will report
</div>
</div>
<div class="callout-body-container callout-body">
<p>Always report:</p>
<ul>
<li>the effect size (mean difference)</li>
<li>a 95% CI</li>
<li>the test statistic with its df</li>
<li>the <span class="math inline">\(p\)</span>-value</li>
</ul>
<p>Example: “Mean change was -0.42 units (95% CI [-0.73, -0.11]; <em>t</em>(11) = -2.92; <em>p</em> = 0.014).”</p>
</div>
</div>
</section>
<section id="from-z-to-t" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="from-z-to-t"><span class="header-section-number">6.2</span> From <span class="math inline">\(z\)</span> to <span class="math inline">\(t\)</span></h2>
<p>A test statistic is the effect you observed divided by an estimate of how much it could vary by chance:</p>
<p><span class="math display">\[\text{statistic}=\frac{\text{effect}}{\text{error}}\]</span></p>
<p>In Chapter 5 we used this with <span class="math inline">\(z\)</span> to test a sample mean against <span class="math inline">\(\mu_0\)</span>:</p>
<p><span class="math display">\[z = \frac{\bar{x}-\mu_0}{\sigma/\sqrt{n}}\]</span></p>
<p>The numerator is the effect, the distance between the sample mean and the value <span class="math inline">\(H_0\)</span> names. The denominator is the standard error, the standard deviation of the sampling distribution of the sample mean. The thing being tested is a sample mean, so the yardstick is how far sample means of size <span class="math inline">\(n\)</span> fall from <span class="math inline">\(\mu_0\)</span> by chance. Means vary less than individual observations do, by a factor of <span class="math inline">\(\sqrt{n}\)</span>, which is why the denominator is <span class="math inline">\(\sigma/\sqrt{n}\)</span> rather than <span class="math inline">\(\sigma\)</span>.</p>
<p><span class="math inline">\(z\)</span> needs the population standard deviation <span class="math inline">\(\sigma\)</span>, and real studies almost never know it. The <span class="math inline">\(t\)</span>-test estimates it with the sample standard deviation <span class="math inline">\(s\)</span>:</p>
<p><span class="math display">\[t = \frac{\bar{x}-\mu_0}{s/\sqrt{n}}\]</span></p>
<p><span class="math inline">\(t\)</span> still measures the distance from <span class="math inline">\(\mu_0\)</span> in standard errors. The difference is that <span class="math inline">\(s\)</span> is itself an estimate that changes from sample to sample, and the rest of this section shows what that does to the distribution of <span class="math inline">\(t\)</span>.</p>
<section id="why-t-has-heavier-tails-than-z" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="why-t-has-heavier-tails-than-z"><span class="header-section-number">6.2.1</span> Why <span class="math inline">\(t\)</span> has heavier tails than <span class="math inline">\(z\)</span></h3>
<p>Because <span class="math inline">\(s\)</span> varies from sample to sample, the <span class="math inline">\(t\)</span> distribution has heavier tails than the standard normal. As <span class="math inline">\(n\)</span> grows, <span class="math inline">\(s\)</span> stabilizes and <span class="math inline">\(t\)</span> converges to <span class="math inline">\(z\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6-z-vs-t-linear-log" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two stacked panels showing the same three overlaid curves: the standard normal, t with 10 degrees of freedom, and t with 2 degrees of freedom. On the linear-scale top panel, all three curves look almost identical, bell-shaped and close together. On the log-scale bottom panel, the same three curves separate clearly in the tails, with the t distribution at 2 degrees of freedom sitting well above the other two far from the center, revealing much heavier tails than the linear panel suggested.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6-z-vs-t-linear-log-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6-z-vs-t-linear-log-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Two stacked panels showing the same three overlaid curves: the standard normal, t with 10 degrees of freedom, and t with 2 degrees of freedom. On the linear-scale top panel, all three curves look almost identical, bell-shaped and close together. On the log-scale bottom panel, the same three curves separate clearly in the tails, with the t distribution at 2 degrees of freedom sitting well above the other two far from the center, revealing much heavier tails than the linear panel suggested.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6-z-vs-t-linear-log-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Normal (<span class="math inline">\(z\)</span>) vs <span class="math inline">\(t\)</span> distributions: on a linear scale (top), tail differences look small; on a log scale (bottom), the heavy tails of small-<span class="math inline">\(n\)</span> <span class="math inline">\(t\)</span> are clear.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Tip: When is $z$ appropriate?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip: When is <span class="math inline">\(z\)</span> appropriate?
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the population SD <span class="math inline">\(\sigma\)</span> is known <em>and</em> the sampling distribution of the sample mean is (approximately) normal, use <span class="math inline">\(z\)</span>. In practice, <span class="math inline">\(\sigma\)</span> is rarely known, so we use <span class="math inline">\(t\)</span> with <span class="math inline">\(s\)</span> and <span class="math inline">\(df=n-1\)</span>.</p>
</div>
</div>
</section>
<section id="degrees-of-freedom" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="degrees-of-freedom"><span class="header-section-number">6.2.2</span> Degrees of freedom</h3>
<p><a href="#fig-6-z-vs-t-linear-log" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> drew a different <span class="math inline">\(t\)</span> curve for each value of a number called the <strong>degrees of freedom</strong>, <span class="math inline">\(df\)</span>. It is also the number in parentheses whenever a <span class="math inline">\(t\)</span>-test is reported, as in <span class="math inline">\(t(9) = 1.94\)</span>.</p>
<p>For one-sample and paired <span class="math inline">\(t\)</span>-tests, <span class="math inline">\(df = n-1\)</span>. A sample of 10 has <span class="math inline">\(df=9\)</span>.</p>
<p>Degrees of freedom counts how many values are still free to vary once something has been estimated from the data. Consider three numbers with a mean of 2: pick the first two freely, say 51 and <span class="math inline">\(-3\)</span>, and the third number is no longer free. It has to be <span class="math inline">\(-42\)</span> for the mean to come out to 2. Two of the three numbers had freedom; the third didn’t. That’s <span class="math inline">\(df=n-1=2\)</span> for three numbers.</p>
<p>In a <span class="math inline">\(t\)</span>-test, the mean is the thing estimated, and the <span class="math inline">\(df\)</span> tells you how much information is left for estimating the spread, <span class="math inline">\(s\)</span>. With few degrees of freedom, <span class="math inline">\(s\)</span> can be well above or below <span class="math inline">\(\sigma\)</span>, so large <span class="math inline">\(t\)</span> values turn up more often and the <span class="math inline">\(t\)</span> curve has heavier tails. As <span class="math inline">\(df\)</span> grows, <span class="math inline">\(s\)</span> settles close to <span class="math inline">\(\sigma\)</span> and the <span class="math inline">\(t\)</span> curve approaches the normal. That is why each <span class="math inline">\(df\)</span> gets its own curve.</p>
<p>In a simulation with <span class="math inline">\(H_0\)</span> true, 7.8% of <span class="math inline">\(t\)</span> values from samples of 10 fall beyond <span class="math inline">\(\pm 2\)</span>, against 4.9% from samples of 101, close to the 5% a normal curve gives. Small samples produce more large <span class="math inline">\(t\)</span> values because <span class="math inline">\(s\)</span> is sometimes well below <span class="math inline">\(\sigma\)</span>, which shrinks the denominator. That is why a test with few degrees of freedom needs a larger cutoff (2.26 at <span class="math inline">\(df = 9\)</span>) to keep false alarms at 5%.</p>
</section>
<section id="critical-values" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="critical-values"><span class="header-section-number">6.2.3</span> Critical values</h3>
<p>For two-tailed tests at <span class="math inline">\(\alpha = 0.05\)</span>:</p>
<ul>
<li><span class="math inline">\(z\)</span> uses critical values <span class="math inline">\(\pm 1.96\)</span>.</li>
<li><span class="math inline">\(t\)</span> uses wider cutoffs for small samples: <span class="math inline">\(\pm 2.262\)</span> at <span class="math inline">\(df = 9\)</span>, <span class="math inline">\(\pm 2.086\)</span> at <span class="math inline">\(df = 20\)</span>, <span class="math inline">\(\pm 2.045\)</span> at <span class="math inline">\(df = 29\)</span>. They approach <span class="math inline">\(\pm 1.96\)</span> as <span class="math inline">\(n\)</span> increases.</li>
</ul>
<p><strong>Rule of thumb.</strong> Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(|t|\)</span> beyond about 2 is rare.</p>
</section>
<section id="t-when-h_0-is-true" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="t-when-h_0-is-true"><span class="header-section-number">6.2.4</span> <span class="math inline">\(t\)</span> when <span class="math inline">\(H_0\)</span> is true</h3>
<p><span class="math inline">\(t\)</span> can be positive or negative depending on direction. Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(t \sim t_{(df=n-1)}\)</span>.</p>
<p>To see how <span class="math inline">\(t\)</span> behaves when <span class="math inline">\(H_0\)</span> is true, we can simulate it. We set up a population whose mean really is <span class="math inline">\(\mu_0 = 0\)</span>, draw a sample of 10, and compute one <span class="math inline">\(t\)</span>. Then we repeat that 1,000 times.</p>
<p><strong>Before you look.</strong> Each bar in <a href="#fig-6t-sim" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> counts <span class="math inline">\(t\)</span> values from these samples. Decide roughly what share of them will fall beyond <span class="math inline">\(\pm 2.26\)</span>, the critical values for <span class="math inline">\(df = 9\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6t-sim" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of 1000 simulated t values on a density scale, tallest near zero and tapering symmetrically. A blue dot-dash t curve with 9 degrees of freedom follows the bars. Red vertical lines labeled lower crit equals -2.26 and upper crit equals 2.26 mark the critical values, and the few bars beyond them are shaded light red.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6t-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6t-sim-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Histogram of 1000 simulated t values on a density scale, tallest near zero and tapering symmetrically. A blue dot-dash t curve with 9 degrees of freedom follows the bars. Red vertical lines labeled lower crit equals -2.26 and upper crit equals 2.26 mark the critical values, and the few bars beyond them are shaded light red.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6t-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Histogram of 1,000 simulated <span class="math inline">\(t\)</span> values from samples of 10 drawn from a population whose mean equals <span class="math inline">\(\mu_0 = 0\)</span>. Bars beyond the critical values, ±2.26, are shaded red. The blue dot-dash curve is the <span class="math inline">\(t\)</span> distribution with 9 degrees of freedom.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Most of the 1,000 values fall between <span class="math inline">\(-2\)</span> and <span class="math inline">\(2\)</span>. About 4% fall beyond <span class="math inline">\(\pm 2.26\)</span>, close to the 5% the cutoff is built to allow. The blue curve is the <span class="math inline">\(t\)</span> distribution with 9 degrees of freedom, and the histogram follows it. Software uses that curve in place of a simulation to find how often chance alone produces a <span class="math inline">\(t\)</span> as large as ours.</p>
</section>
</section>
<section id="one-sample-t-test" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="one-sample-t-test"><span class="header-section-number">6.3</span> One-sample t-test</h2>
<p>Use a one-sample <span class="math inline">\(t\)</span> when you want to test whether a sample mean differs from a reference value (<span class="math inline">\(\mu_0\)</span>). It asks whether the observed difference is bigger than you’d expect from sampling variability, given <span class="math inline">\(n\)</span> and your sample SD <span class="math inline">\(s\)</span>.</p>
<p><span class="math display">\[t = \frac{\bar{x}-\mu_0}{s/\sqrt{n}}, \qquad df = n-1\]</span></p>
<p>After calculating <span class="math inline">\(t\)</span> from our data, we compare the observed <span class="math inline">\(t\)</span> to a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-1\)</span> degrees of freedom to get a <span class="math inline">\(p\)</span>-value and a decision at <span class="math inline">\(\alpha\)</span>.</p>
<section id="calculating-t-from-data" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="calculating-t-from-data"><span class="header-section-number">6.3.1</span> Calculating t from data</h3>
<p>Let’s calculate a one-sample <span class="math inline">\(t\)</span> statistic step by step using a short example. Ten students each took a 10-question true/false quiz (50% expected by chance). Their scores (percent correct) are:</p>
<p><strong>Scores:</strong> 50, 70, 60, 40, 80, 30, 90, 60, 70, 60</p>
<p>By hand, the standard error of the mean is the sample SD divided by the square root of <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[\text{SE} = \frac{s}{\sqrt{n}} = \frac{17.92}{\sqrt{10}} = 5.67\]</span></p>
<p>And <span class="math inline">\(t\)</span> is the difference between the sample mean (61) and the reference value (50, chance level), divided by that SE:</p>
<p><span class="math display">\[t = \frac{\bar{x}-\mu_0}{SE} = \frac{61-50}{5.67} = 1.94\]</span></p>
<p>We can confirm this with a single R command, <code>t.test(scores, mu = 50)</code>:</p>
<p><strong>Results:</strong> <span class="math inline">\(t(9)=1.94\)</span>, <span class="math inline">\(p=0.0842\)</span>; mean <span class="math inline">\(=61\)</span> (95% CI [48.18, 73.82]).</p>
<p><strong>Confidence interval.</strong> The 95% CI in that output is <span class="math inline">\(\bar{x} \pm t_{crit} \cdot SE\)</span>, with <span class="math inline">\(t_{crit}\)</span> taken from the <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-1\)</span> degrees of freedom. Here that is <span class="math inline">\(61 \pm 2.262(5.67)\)</span>, or [48.18, 73.82]. The interval contains 50, so the test does not reject <span class="math inline">\(H_0\)</span>. For a two-tailed test at <span class="math inline">\(\alpha\)</span>, the <span class="math inline">\(100(1-\alpha)\%\)</span> CI and the critical value always reach the same decision, the same equivalence Chapter 4 showed for <span class="math inline">\(z\)</span>.</p>
<p><strong>Interpretation.</strong> The mean (61%) is above chance (50%), but the difference is not statistically significant at <span class="math inline">\(\alpha=0.05\)</span>.</p>
<p><strong>Assumptions check.</strong> The 10 scores spread evenly around 60 with no outliers, so approximate normality is reasonable. <a href="#sec-6assumptions" class="quarto-xref"><span>Section 6.3.5</span></a> covers how to check this.</p>
</section>
<section id="interpreting-t" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="interpreting-t"><span class="header-section-number">6.3.2</span> Interpreting <span class="math inline">\(t\)</span></h3>
<p>Extreme sample means are unlikely if <span class="math inline">\(H_0\)</span> is true, which is why large <span class="math inline">\(|t|\)</span> values are rare. That is the basis of the decision rule for <span class="math inline">\(t\)</span>-tests: if your observed <span class="math inline">\(t\)</span> falls beyond the critical values, you reject <span class="math inline">\(H_0\)</span>.</p>
<p>We’re asking whether our <span class="math inline">\(t\)</span>-value could plausibly have come from the null distribution: the distribution of <span class="math inline">\(t\)</span>-values we’d see across many samples of size 10, if the true mean were exactly 50 (chance level). <a href="#fig-6tnull" class="quarto-xref">Figure&nbsp;<span>6.3</span></a> shows what that distribution looks like, at <span class="math inline">\(df=9\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6tnull" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A symmetric t-distribution curve with 9 degrees of freedom, centered at zero with a grey vertical line marking the center. Labels on the left and right halves each read 50 percent, showing the curve splits evenly into negative and positive t-values.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6tnull-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6tnull-1.png" class="img-fluid figure-img" style="width:75.0%" alt="A symmetric t-distribution curve with 9 degrees of freedom, centered at zero with a grey vertical line marking the center. Labels on the left and right halves each read 50 percent, showing the curve splits evenly into negative and positive t-values.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6tnull-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: The distribution of <span class="math inline">\(t\)</span>-values that chance alone produces when the population mean equals <span class="math inline">\(\mu_0\)</span> (<span class="math inline">\(df = 9\)</span>).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(t\)</span> is most likely to be near zero, because chance alone rarely produces a large difference. The distribution is symmetric, so half of all <span class="math inline">\(t\)</span>-values are at or above zero and half are at or below.</p>
<p>We can get more precise than a 50/50 split. <a href="#fig-6percentregions" class="quarto-xref">Figure&nbsp;<span>6.4</span></a> divides the same distribution into ten regions, each containing 10% of the distribution. Notice the regions get wider out in the tails: since most <span class="math inline">\(t\)</span>-values cluster near 0, it takes a wider interval out there to capture the same 10%.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6percentregions" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The same t-distribution curve with 9 degrees of freedom, divided by nine grey vertical lines into ten regions, each labeled 10 percent. The regions near the two outer edges are noticeably wider than the regions clustered near the center of the curve.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6percentregions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6percentregions-1.png" class="img-fluid figure-img" style="width:100.0%" alt="The same t-distribution curve with 9 degrees of freedom, divided by nine grey vertical lines into ten regions, each labeled 10 percent. The regions near the two outer edges are noticeably wider than the regions clustered near the center of the curve.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6percentregions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Splitting the t distribution up into regions each containing 10% of the <span class="math inline">\(t\)</span>-values. The width between the bars narrows as they approach the center of the distribution, where there are more <span class="math inline">\(t\)</span>-values.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For example:</p>
<ol type="1">
<li><span class="math inline">\(t \leq -1.38\)</span>: <span class="math inline">\(p = 10\%\)</span></li>
<li><span class="math inline">\(-1.38 \leq t \leq -0.88\)</span>: <span class="math inline">\(p = 10\%\)</span></li>
<li><span class="math inline">\(-0.88 \leq t \leq -0.54\)</span>: <span class="math inline">\(p = 10\%\)</span></li>
<li><span class="math inline">\(t \geq 1.38\)</span>: <span class="math inline">\(p = 10\%\)</span></li>
</ol>
<p>Each range captures the same 10% of the distribution, even though the ranges themselves are different widths.</p>
<p>Our quiz <span class="math inline">\(t\)</span> of 1.94 is beyond 1.38, so it falls in the top 10% of this distribution. Its exact <span class="math inline">\(p\)</span>-value comes from software, and the one-tailed section below uses it.</p>
</section>
<section id="getting-the-p-values-for-t-values" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="getting-the-p-values-for-t-values"><span class="header-section-number">6.3.3</span> Getting the p-values for <span class="math inline">\(t\)</span>-values</h3>
<p>Older textbooks printed <span class="math inline">\(p\)</span>-values for <span class="math inline">\(t\)</span> in a table at the back of the book. Today R, Excel, and <a href="http://www.socscistatistics.com/pvalues/tdistribution.aspx">online calculators</a> give them directly. You’ll practice this in lab, both with software and by simulation.</p>
<p>Software needs two things from you to compute a <span class="math inline">\(p\)</span>-value: the degrees of freedom, which you already have, and whether the test is one-tailed or two-tailed, which comes next.</p>
</section>
<section id="one-tailed-vs.-two-tailed-applied" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="one-tailed-vs.-two-tailed-applied"><span class="header-section-number">6.3.4</span> One-tailed vs.&nbsp;two-tailed, applied</h3>
<p>Chapters 4 and 5 covered when each is justified. For a <span class="math inline">\(t\)</span>-test, the choice changes the critical value, and therefore the <span class="math inline">\(p\)</span>-value, for the exact same data.</p>
<p>For our quiz-score example (<span class="math inline">\(df=9\)</span>), a one-tailed test only needs to clear 5% of the distribution on one side. A two-tailed test has to clear 2.5% on each side, which pushes the critical value farther out:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6critT" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A t-distribution curve with 9 degrees of freedom, with a single red vertical line at t equal to 1.83 labeled plus crit equals 1.83. The tail to the right of that line is shaded red and labeled 5 percent; everything to the left is unshaded. A green dotted line marks the observed t of 1.94, just inside the shaded tail.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6critT-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6critT-1.png" class="img-fluid figure-img" style="width:75.0%" alt="A t-distribution curve with 9 degrees of freedom, with a single red vertical line at t equal to 1.83 labeled plus crit equals 1.83. The tail to the right of that line is shaded red and labeled 5 percent; everything to the left is unshaded. A green dotted line marks the observed t of 1.94, just inside the shaded tail.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6critT-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.5: One-tailed critical value at df=9: t-values of 1.83 or greater occur 5% of the time.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6twotailedt" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A t-distribution curve with 9 degrees of freedom, with two red vertical lines labeled minus crit and plus crit at negative 2.26 and positive 2.26. The tails beyond each line are shaded red and labeled 2.5 percent, one on each side, leaving the large central region between them unshaded. A green dotted line marks the observed t of 1.94, just short of the right critical value.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6twotailedt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6twotailedt-1.png" class="img-fluid figure-img" style="width:75.0%" alt="A t-distribution curve with 9 degrees of freedom, with two red vertical lines labeled minus crit and plus crit at negative 2.26 and positive 2.26. The tails beyond each line are shaded red and labeled 2.5 percent, one on each side, leaving the large central region between them unshaded. A green dotted line marks the observed t of 1.94, just short of the right critical value.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6twotailedt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.6: Two-tailed critical values at df=9: t-values beyond ±2.26 occur 5% of the time total, 2.5% in each tail.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For our result, <span class="math inline">\(t(9) = 1.94\)</span>, the one-tailed <span class="math inline">\(p\)</span> is 0.042 and the two-tailed <span class="math inline">\(p\)</span> is 0.084, exactly double, because a two-tailed test counts the matching region in both tails. The choice changes the decision here. One-tailed, the result is significant at <span class="math inline">\(\alpha = 0.05\)</span>; two-tailed, it is not.</p>
</section>
<section id="sec-6assumptions" class="level3" data-number="6.3.5">
<h3 data-number="6.3.5" class="anchored" data-anchor-id="sec-6assumptions"><span class="header-section-number">6.3.5</span> Assumptions, and what to do when they don’t hold</h3>
<p>Every test in this book has assumptions. Assumptions are conditions that need to be roughly true for the math behind the test to be trustworthy. There are two different kinds of assumptions.</p>
<p><strong>The universal assumption.</strong> Every test in this book, including the nonparametric tests in Chapter 7, assumes your observations are independent (in paired designs, the pairs) and came from a sound study design (a fair sample, not one that systematically favors certain values). Because it applies everywhere, we won’t list it test by test from here on. When an exam or homework question asks you to “list the assumptions of this test,” it means the test-specific assumptions below.</p>
<p><strong>Test-specific assumptions.</strong> These come from how a particular test’s math works, and they differ test to test. For the one-sample and paired <span class="math inline">\(t\)</span>-tests, the specific assumption is approximate normality of the outcome itself (one-sample) or of the difference scores (paired). The <span class="math inline">\(t\)</span>-distribution we’ve been using to get <span class="math inline">\(p\)</span>-values is <em>derived</em> assuming the population is normal, which makes the sample mean normally distributed too. If your data are badly skewed and your sample is small, that assumption fails, and the <span class="math inline">\(p\)</span>-value may not be the true probability of a result this extreme under <span class="math inline">\(H_0\)</span>.</p>
<p><strong>How worried should you be?</strong> It depends on <span class="math inline">\(n\)</span>. With a large sample, the sampling distribution of the sample mean tends toward normal even when individual observations are skewed (the Central Limit Theorem), so the <span class="math inline">\(t\)</span>-test is fairly <strong>robust</strong> to non-normality once <span class="math inline">\(n\)</span> is reasonably large. Much environmental field data comes from small samples that are also skewed. Examples include a handful of expensive water samples, a short list of monitoring wells, or the five plots you had time to visit in a season. A <span class="math inline">\(t\)</span>-test’s answer becomes questionable when the sample is small and the data are also non-normal.</p>
<p><strong>What to do about it.</strong> First, look at your data. A histogram or a Q-Q plot will usually tell you whether “approximately normal” is a reasonable description or a stretch. You can also run a formal normality test, the <strong>Shapiro-Wilk test</strong> (<code>shapiro.test()</code> in R), which tests <span class="math inline">\(H_0\)</span>: the data came from a normal distribution. Treat it as one more piece of evidence, though, rather than a strict gate. With a small sample, exactly when a violation matters most, it has low power and will often say “no problem” even when there is one. If your data look far from normal and your sample is small, you can use a <strong>nonparametric test</strong> instead, which does not assume normality. You’ll meet these nonparametric alternatives in the next chapter, once we’ve covered all three <span class="math inline">\(t\)</span>-test forms below.</p>
</section>
</section>
<section id="paired-t-beforeafter-or-matched" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="paired-t-beforeafter-or-matched"><span class="header-section-number">6.4</span> Paired t: before/after or matched</h2>
<p>When the same units are measured twice (before/after, matched pairs), the question is whether they changed. The natural data unit is the <strong>within-unit difference</strong>.</p>
<p><strong>Design in this worked example.</strong> Ecologists measured soil moisture at 20 field plots before wetland restoration and again one year later, to see whether restoration increased moisture enough to support plant reestablishment and carbon sequestration. <a href="#fig-6paireddesign" class="quarto-xref">Figure&nbsp;<span>6.7</span></a> shows the design.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6paireddesign" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Study design schematic. IV: restoration, before versus after. Two dashed boxes labeled Before and After, each n = 20 plots, with a note that these are the same 20 plots measured on both occasions. DV: soil moisture, percent.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6paireddesign-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6paireddesign-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Study design schematic. IV: restoration, before versus after. Two dashed boxes labeled Before and After, each n = 20 plots, with a note that these are the same 20 plots measured on both occasions. DV: soil moisture, percent.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6paireddesign-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.7: A paired design. The dashed boxes and the note underneath mark the feature that defines it: there is one set of 20 plots, measured on two occasions, not two separate samples.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The dashed boxes mark what makes this design paired. In every design so far the boxes held <em>different</em> units, and the test compared one set against another. Here both boxes hold the same 20 plots, so each plot’s Before value can be subtracted from its own After value.</p>
<p><strong>Define differences and their meaning.</strong> Choose an order and stick to it:</p>
<ul>
<li><span class="math inline">\(d_i = \text{After}_i - \text{Before}_i\)</span></li>
<li><span class="math inline">\(d_i&gt;0\)</span>: plot had more soil moisture after restoration (increase)</li>
<li><span class="math inline">\(d_i&lt;0\)</span>: plot had less soil moisture after restoration (decrease)</li>
</ul>
<p>This subtraction cancels between-plot variability (some plots are naturally wetter than others) and focuses on within-plot change. Because it removes those plot-to-plot differences, the paired test’s standard error is smaller, so it has more power than an independent-samples test on the same data.</p>
<p><strong>Test on differences (paired <span class="math inline">\(t\)</span>).</strong> Compute one difference per plot, then run a one-sample <span class="math inline">\(t\)</span> against 0:</p>
<p><span class="math display">\[\bar d=\frac{1}{n}\sum_{i=1}^n d_i, \quad
s_d=\text{SD}(d_1,\ldots,d_n), \quad
t = \frac{\bar d - 0}{s_d/\sqrt{n}}, \quad df=n-1.\]</span></p>
<p>The sign of <span class="math inline">\(t\)</span> matches <span class="math inline">\(\bar d\)</span> and your difference direction.</p>
<p><strong>What to report.</strong> <span class="math inline">\(\bar d\)</span> (the mean change), a 95% CI, <span class="math inline">\(t(df)\)</span>, and <span class="math inline">\(p\)</span>. Optionally add a standardized effect size, <span class="math inline">\(\bar d / s_d\)</span>, the paired version of Cohen’s <span class="math inline">\(d\)</span>.</p>
<p><strong>R pointers (you’ll do this in lab).</strong></p>
<ul>
<li>Compute differences: <code>d &lt;- after - before</code></li>
<li>Paired <span class="math inline">\(t\)</span>: <code>t.test(d, mu = 0)</code> or <code>t.test(after, before, paired = TRUE)</code></li>
<li>CI for <span class="math inline">\(\bar d\)</span>: from the <code>t.test</code> output</li>
</ul>
<section id="calculate-t" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="calculate-t"><span class="header-section-number">6.4.1</span> Calculate t</h3>
<p>To calculate <span class="math inline">\(t\)</span> for a paired-samples <span class="math inline">\(t\)</span>-test, we use the one-sample <span class="math inline">\(t\)</span>-test formula from the previous section, applied to the difference scores instead of raw scores. The paired-samples <span class="math inline">\(t\)</span>-test is a one-sample <span class="math inline">\(t\)</span>-test on a single group of numbers, the differences.</p>
<p>Let’s find <span class="math inline">\(t\)</span> for the mean difference scores:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Plot</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Before</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">After</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Difference</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Deviation from mean difference</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Squared deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">0.2</td>
<td style="text-align: left;">0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">26</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">3.2</td>
<td style="text-align: left;">10.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">-5.8</td>
<td style="text-align: left;">33.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">102</td>
<td style="text-align: left;">116</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">46.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">20.4</td>
<td style="text-align: left;">23.2</td>
<td style="text-align: left;">2.8</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">9.36</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">sd</td>
<td style="text-align: left;">3.421</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">SE</td>
<td style="text-align: left;">1.53</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">t</td>
<td style="text-align: left;">1.83</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The five differences average 2.8 percentage points, with <span class="math inline">\(s_d = 3.42\)</span>, so <span class="math inline">\(SE = 3.42/\sqrt{5} = 1.53\)</span> and <span class="math inline">\(t = 2.8/1.53 = 1.83\)</span>.</p>
<p>If we did this test using R, we would obtain almost the same numbers (there is a little bit of rounding in the table).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Paired t-test on 5 restoration plots</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0.141</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean difference was <span class="math inline">\(+2.8\)</span> percentage points, so soil moisture increased on average. Getting a <span class="math inline">\(p\)</span>-value from this <span class="math inline">\(t\)</span>, and choosing one-tailed vs.&nbsp;two-tailed, works exactly like it did for the one-sample case (see the One-sample <span class="math inline">\(t\)</span>-test section above). Two-tailed, <span class="math inline">\(t(4) = 1.83\)</span>, <span class="math inline">\(p = 0.141\)</span>, which is not significant. With only five plots, a mean increase this large would not be unusual even if restoration had no effect on soil moisture.</p>
</section>
<section id="scaling-to-the-full-sample" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="scaling-to-the-full-sample"><span class="header-section-number">6.4.2</span> Scaling to the full sample</h3>
<p>The five plots above are a subset of the full restoration study, which measured all 20 paired plots.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Paired t-test on all 20 restoration plots</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">0.022</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>At <span class="math inline">\(n=20\)</span>, <span class="math inline">\(t(19) = 2.5\)</span>, <span class="math inline">\(p =0.022\)</span>: significant. The mean difference (1.9 percentage points) is smaller than the 5-plot subset’s 2.8. The larger <span class="math inline">\(t\)</span> comes from the standard error, which fell from 1.53 to 0.76 with four times as many plots. A mean increase of 1.9 points would be unlikely if restoration had no effect, so the extra plots gave more power to detect a real effect.</p>
</section>
</section>
<section id="two-independent-groups" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="two-independent-groups"><span class="header-section-number">6.5</span> Two independent groups</h2>
<p>The independent-samples <span class="math inline">\(t\)</span>-test is the third and last design in this chapter. The logic is the same as the one-sample and paired cases: a mean difference divided by an estimate of its variability. Only the research design is different.</p>
<p>Use an independent-samples <span class="math inline">\(t\)</span>-test for a <strong>between-subjects</strong> design: different people or units in each condition, each measured once. With two groups of 5, that’s 10 units in total, none of them paired. Without repeated measures on the same unit, there’s no meaningful way to subtract scores between conditions the way the paired <span class="math inline">\(t\)</span>-test does.</p>
<p>The numerator is the mean difference between groups, as in the other two tests. The denominator differs from the paired case, because now we need a single estimate of variability built from two separate samples instead of one.</p>
<p>A natural first guess is to average the two groups’ standard errors:</p>
<p><span class="math display">\[t = \frac{\bar{A}-\bar{B}}{\left(\dfrac{SE_A+SE_B}{2}\right)}\]</span></p>
<p>That average understates how much a difference between two means varies. The standard error of a difference between two independent means is <span class="math inline">\(\sqrt{SE_A^2 + SE_B^2}\)</span>, which is always larger than the average of the two SEs. Instead of averaging, the independent-samples <span class="math inline">\(t\)</span>-test pools the two groups’ variances, weighted by their degrees of freedom, into a single estimate for the denominator:</p>
<p><span class="math display">\[t = \frac{\bar{x}_A-\bar{x}_B}{s_p\sqrt{\dfrac{1}{n_A}+\dfrac{1}{n_B}}}\]</span></p>
<p>where the pooled standard deviation <span class="math inline">\(s_p\)</span> is (note <span class="math inline">\(s_A^2\)</span> and <span class="math inline">\(s_B^2\)</span> here are variances, not standard deviations):</p>
<p><span class="math display">\[s_p = \sqrt{\frac{(n_A-1)s_A^2 + (n_B-1)s_B^2}{n_A+n_B-2}}\]</span></p>
<p>The pooled test has <span class="math inline">\(df = n_A + n_B - 2\)</span>, one degree of freedom used for each group’s mean. With two groups of 5, that is <span class="math inline">\(df = 8\)</span>, the 8 in <span class="math inline">\(t(8)\)</span> below.</p>
<p>The pooled test adds two test-specific assumptions: the outcome is approximately normal within each group, and the two groups have similar variances. When the spreads clearly differ, use Welch’s version instead.</p>
<p>The example below follows that formula step by step in R, then checks it against <code>t.test()</code>. We print R’s raw console output here instead of a formatted table, because this is the block you will see in lab, and you can check the hand-computed <span class="math inline">\(t\)</span> against its <code>t =</code> value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="do">## By "hand" using R</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">9</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>n_a <span class="ot">&lt;-</span> <span class="fu">length</span>(a) <span class="co"># sample size for A</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>n_b <span class="ot">&lt;-</span> <span class="fu">length</span>(b) <span class="co"># sample size for B</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>mean_difference <span class="ot">&lt;-</span> <span class="fu">mean</span>(a)<span class="sc">-</span><span class="fu">mean</span>(b) <span class="co"># compute mean difference</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>variance_a <span class="ot">&lt;-</span> <span class="fu">var</span>(a) <span class="co"># compute variance for A</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>variance_b <span class="ot">&lt;-</span> <span class="fu">var</span>(b) <span class="co"># compute variance for B</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute top part and bottom part of sp formula</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>sp_numerator <span class="ot">&lt;-</span> (n_a <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> variance_a <span class="sc">+</span> (n_b <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> variance_b</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>sp_denominator <span class="ot">&lt;-</span> n_a <span class="sc">+</span> n_b <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sp_numerator<span class="sc">/</span>sp_denominator) <span class="co"># compute sp</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># compute t following the formula</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> mean_difference <span class="sc">/</span> (sp <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>n_a <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>n_b))</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>t <span class="co"># our hand-computed t</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -2.017991</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># the same test via R's built-in function: compare the "t = " value</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a,b, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Two Sample t-test</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; data:  a and b</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t = -2.018, df = 8, p-value = 0.0783</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; alternative hypothesis: true difference in means is not equal to 0</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  -5.5710785  0.3710785</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample estimates:</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; mean of x mean of y </span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       3.0       5.6</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Our hand-computed <span class="math inline">\(t\)</span> is <span class="math inline">\(-2.02\)</span>, and the <code>t = -2.018</code> line in R’s output matches it. R also reports <span class="math inline">\(df = 8\)</span>, <span class="math inline">\(p = 0.078\)</span>, and the 95% confidence interval for the difference.</p>
<p>Cohen’s <span class="math inline">\(d\)</span> for two independent groups divides the mean difference by the pooled standard deviation, <span class="math inline">\(d = (\bar{x}_A - \bar{x}_B)/s_p\)</span>. Here <span class="math inline">\(s_p = 2.04\)</span>, so <span class="math inline">\(d = -2.6/2.04 = -1.28\)</span>.</p>
<p><a href="#tbl-6three-tests" class="quarto-xref">Table&nbsp;<span>6.1</span></a> sets the three forms side by side. Each one divides an effect by its standard error. The design decides what counts as the effect and how its standard error is estimated.</p>
<div id="tbl-6three-tests" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-6three-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: The three <span class="math inline">\(t\)</span>-tests compared.
</figcaption>
<div aria-describedby="tbl-6three-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>One-sample</th>
<th>Paired</th>
<th>Independent-samples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Design</td>
<td>One sample against a reference value</td>
<td>The same units measured twice</td>
<td>Two separate groups</td>
</tr>
<tr class="even">
<td>Effect (numerator)</td>
<td><span class="math inline">\(\bar{x} - \mu_0\)</span></td>
<td><span class="math inline">\(\bar{d}\)</span></td>
<td><span class="math inline">\(\bar{x}_A - \bar{x}_B\)</span></td>
</tr>
<tr class="odd">
<td>Standard error (denominator)</td>
<td><span class="math inline">\(s/\sqrt{n}\)</span></td>
<td><span class="math inline">\(s_d/\sqrt{n}\)</span></td>
<td><span class="math inline">\(s_p\sqrt{1/n_A + 1/n_B}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(df\)</span></td>
<td><span class="math inline">\(n - 1\)</span></td>
<td><span class="math inline">\(n - 1\)</span> (<span class="math inline">\(n\)</span> = number of pairs)</td>
<td><span class="math inline">\(n_A + n_B - 2\)</span></td>
</tr>
<tr class="odd">
<td>R call</td>
<td><code>t.test(x, mu = 50)</code></td>
<td><code>t.test(after, before, paired = TRUE)</code></td>
<td><code>t.test(a, b, var.equal = TRUE)</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Results reporting: t-tests">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Results reporting: t-tests
</div>
</div>
<div class="callout-body-container callout-body">
<p>All three forms report the same four things: the direction in plain language, the effect size, the test statistic with its df, and <span class="math inline">\(p\)</span>. The three forms differ only in what counts as the effect.</p>
<p>One-sample, where the effect is the sample mean against the reference value:</p>
<blockquote class="blockquote">
<p>Mean quiz score was 61%, which did not differ significantly from the 50% expected by chance, <em>t</em>(9) = 1.94, <em>p</em> = 0.084, 95% CI [48.18, 73.82].</p>
</blockquote>
<p>Paired, where the effect is the mean <em>difference</em> score:</p>
<blockquote class="blockquote">
<p>Soil moisture increased by 1.90 percentage points after restoration, <em>t</em>(19) = 2.50, <em>p</em> = 0.022, 95% CI [0.31, 3.49].</p>
</blockquote>
<p>Independent-samples, where the effect is the difference between two group means:</p>
<blockquote class="blockquote">
<p>Group A scored lower than Group B, a mean difference of -2.6, <em>t</em>(8) = -2.02, <em>p</em> = 0.078, 95% CI [-5.57, 0.37].</p>
</blockquote>
<p>Note the paired write-up never mentions the before and after means separately. The difference score <em>is</em> the unit of analysis, so that single number plus its CI is the whole result.</p>
</div>
</div>
</section>
<section id="simulating-data-for-t-tests" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="simulating-data-for-t-tests"><span class="header-section-number">6.6</span> Simulating data for t-tests</h2>
<p>Earlier in this chapter we simulated <span class="math inline">\(t\)</span> under <span class="math inline">\(H_0\)</span> and saw its null distribution in <a href="#fig-6t-sim" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>. The same kind of simulation also gives a <span class="math inline">\(p\)</span>-value for each repetition, and those <span class="math inline">\(p\)</span>-values show what a test does when <span class="math inline">\(H_0\)</span> is true and when it is false.</p>
<p>Simulating under conditions you choose shows how sampling error affects results for a given sample size, expected difference, and amount of variation. Formal power analyses use the same method.</p>
<section id="simulating-a-one-sample-t-test" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="simulating-a-one-sample-t-test"><span class="header-section-number">6.6.1</span> Simulating a one-sample t-test</h3>
<p>A simulation has two steps.</p>
<ol type="1">
<li>Decide what the population looks like. Here each sample is 30 sites, with values drawn from a normal distribution with mean 50 and SD 25.</li>
<li>Draw one sample from that population, run the <span class="math inline">\(t\)</span>-test, and save the statistics you care about (<span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span>). Repeat 1,000 times and look at how they are distributed.</li>
</ol>
<p>Every test compares the sample mean to <span class="math inline">\(\mu_0 = 50\)</span>, which is also the true population mean, so <span class="math inline">\(H_0\)</span> is true in every repetition. <a href="#fig-6flatp" class="quarto-xref">Figure&nbsp;<span>6.8</span></a> shows the 1,000 <span class="math inline">\(p\)</span>-values it produces.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6flatp" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of 1000 simulated p-values from samples with no true effect, roughly flat across the full range from 0 to 1, with bars of similar height in every bin including the bin closest to zero.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6flatp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6flatp-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Histogram of 1000 simulated p-values from samples with no true effect, roughly flat across the full range from 0 to 1, with bars of similar height in every bin including the bin closest to zero.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6flatp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.8: The distribution of <span class="math inline">\(p\)</span>-values that are observed is flat under the null.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-values in <a href="#fig-6flatp" class="quarto-xref">Figure&nbsp;<span>6.8</span></a> are flat, as they should be when <span class="math inline">\(H_0\)</span> is true. This means you have the same chance of getting a <span class="math inline">\(t\)</span> with a p-value between 0 and 0.05 as you would of getting one between 0.90 and 0.95. Those ranges are both ranges of 5%, so they hold an equal share of the <span class="math inline">\(t\)</span> values by definition.</p>
<p>The first bar holds the 45 <span class="math inline">\(p\)</span>-values below 0.05. Each one is a test that rejected a true <span class="math inline">\(H_0\)</span>, a Type I error. Together they make up about 5% of the 1,000, which is the <span class="math inline">\(\alpha\)</span> we chose.</p>
</section>
<section id="simulating-paired-and-independent-samples-tests" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="simulating-paired-and-independent-samples-tests"><span class="header-section-number">6.6.2</span> Simulating paired and independent-samples tests</h3>
<p>The paired and independent-samples cases behave the same way, because they use the same <span class="math inline">\(t\)</span> calculation on different inputs. A paired test runs a one-sample <span class="math inline">\(t\)</span> on the difference scores; an independent-samples test swaps in the pooled standard error. Simulate either one under <span class="math inline">\(H_0\)</span> and you get the same two pictures: a <span class="math inline">\(t\)</span> distribution centered on zero, and a flat <span class="math inline">\(p\)</span> distribution.</p>
<p>Chapter 5 simulated 1,000 experiments with a real difference (two groups of 10, means 10 and 12.5, SD 5) and counted how often <span class="math inline">\(p &lt; 0.05\)</span> to estimate power. <a href="#fig-6simtrueps" class="quarto-xref">Figure&nbsp;<span>6.9</span></a> shows the 1,000 <span class="math inline">\(p\)</span>-values from the same setup.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-6simtrueps" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of 1000 simulated p-values from samples of size 10 with a real underlying difference. Unlike the flat null histogram, this one is right-skewed, with the tallest bars near zero and progressively shorter bars moving toward 1.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6simtrueps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-ttests_files/figure-html/fig-6simtrueps-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Histogram of 1000 simulated p-values from samples of size 10 with a real underlying difference. Unlike the flat null histogram, this one is right-skewed, with the tallest bars near zero and progressively shorter bars moving toward 1.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6simtrueps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.9: 1,000 simulated <span class="math inline">\(p\)</span>-values (<span class="math inline">\(n = 10\)</span> per group) when there is a true difference.
</figcaption>
</figure>
</div>
</div>
</div>
<p>With a real difference, the <span class="math inline">\(p\)</span>-values pile up near 0, while under <span class="math inline">\(H_0\)</span> in <a href="#fig-6flatp" class="quarto-xref">Figure&nbsp;<span>6.8</span></a> they spread evenly from 0 to 1. Here <span class="math inline">\(H_0\)</span> is false, so rejecting it is a correct decision, not a Type I error. The first bar holds the 187 experiments that rejected <span class="math inline">\(H_0\)</span>, and their share of the 1,000 is the design’s power. The other 813 missed a difference that was really there. Chapter 5 showed how a larger sample raises power.</p>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">6.7</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> The <span class="math inline">\(t\)</span>-test measures a signal against the noise around it. ANOVA, regression, and the rest of the course use the same logic.</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>Signal over noise.</strong> A difference is only impressive relative to the variability around it. Every <span class="math inline">\(t\)</span> statistic is a ratio: the effect you observed on top, an estimate of how much that effect could vary by chance on the bottom.</li>
<li><strong>Three forms, one idea.</strong> The one-sample, paired, and independent-samples <span class="math inline">\(t\)</span>-tests differ in how they compute the effect and its standard error, but all three ask whether an observed difference is large compared to its own standard error. The paired test is just the one-sample test applied to difference scores.</li>
<li><strong>Why <span class="math inline">\(t\)</span> and not <span class="math inline">\(z\)</span>.</strong> When the population SD <span class="math inline">\(\sigma\)</span> is unknown, we estimate it with <span class="math inline">\(s\)</span>, which adds uncertainty. The <span class="math inline">\(t\)</span> distribution accounts for that by being fatter in the tails than the normal, and it tightens toward the normal as degrees of freedom grow.</li>
<li><strong>Assumptions come in two kinds.</strong> <em>Independence and a sound study design</em> apply to every test in this book and are assumed from here on. The <em>test-specific</em> assumption is approximate normality: of the outcome (one-sample), of the difference scores (paired), or of each group (independent samples). The pooled independent-samples test also assumes similar variances.</li>
<li><strong>How worried to be depends on <span class="math inline">\(n\)</span>.</strong> Thanks to the Central Limit Theorem, <span class="math inline">\(t\)</span>-tests are fairly robust to non-normality once samples are reasonably large. <span class="math inline">\(t\)</span>-tests are least trustworthy when samples are small <em>and</em> skewed, which describes a lot of environmental field data. Plot your data first, and treat a Shapiro-Wilk result as evidence rather than a gate, since it has the least power with small samples, when a violation matters most.</li>
<li><strong>Choose your tails before you look.</strong> Default to two-tailed. Reserve one-tailed tests for cases where a difference in the opposite direction would lead to the same action as no difference, and decide before seeing the result.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Student1908" class="csl-entry" role="listitem">
Student, A. 1908. <span>“The Probable Error of a Mean.”</span> <em>Biometrika</em> 6: 1–2.
</div>
<div id="ref-Welch1947" class="csl-entry" role="listitem">
Welch, B. L. 1947. <span>“The Generalization of <span>‘<span>Student</span>’s’</span> Problem When Several Different Population Variances Are Involved.”</span> <em>Biometrika</em> 34: 28–35.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-Hypothesis_Testing.html" class="pagination-link" aria-label="Errors, Power, and Effect Size">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Errors, Power, and Effect Size</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-Nonparametric.html" class="pagination-link" aria-label="Nonparametric and Categorical Data">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Nonparametric and Categorical Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/06-ttests.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>