<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory Barnes">

<title>Answering questions with data - 7&nbsp; When Assumptions Fail: Nonparametric and Categorical Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-ANOVA.html" rel="next">
<link href="./06-ttests.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 7&nbsp; When Assumptions Fail: Nonparametric and Categorical Data">
<meta property="og:description" content="">
<meta property="og:image" content="07-Nonparametric_files/figure-html/fig-8wilcoxon-hist-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 7&nbsp; When Assumptions Fail: Nonparametric and Categorical Data">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-Nonparametric.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-MoreFactorialDesigns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#parametric-vs.-nonparametric-tests" id="toc-parametric-vs.-nonparametric-tests" class="nav-link active" data-scroll-target="#parametric-vs.-nonparametric-tests"><span class="header-section-number">7.1</span> Parametric vs.&nbsp;nonparametric tests</a></li>
  <li><a href="#nonparametric-alternative-to-one-sample-paired-t-test-the-wilcoxon-signed-rank-test" id="toc-nonparametric-alternative-to-one-sample-paired-t-test-the-wilcoxon-signed-rank-test" class="nav-link" data-scroll-target="#nonparametric-alternative-to-one-sample-paired-t-test-the-wilcoxon-signed-rank-test"><span class="header-section-number">7.2</span> Nonparametric alternative to one-sample &amp; paired t-test: the Wilcoxon signed-rank test</a></li>
  <li><a href="#nonparametric-alternative-to-the-independent-samples-t-test-the-mann-whitney-wilcoxon-test" id="toc-nonparametric-alternative-to-the-independent-samples-t-test-the-mann-whitney-wilcoxon-test" class="nav-link" data-scroll-target="#nonparametric-alternative-to-the-independent-samples-t-test-the-mann-whitney-wilcoxon-test"><span class="header-section-number">7.3</span> Nonparametric alternative to the independent-samples t-test: the Mann-Whitney-Wilcoxon test</a></li>
  <li><a href="#categorical-data-the-chi-square-tests" id="toc-categorical-data-the-chi-square-tests" class="nav-link" data-scroll-target="#categorical-data-the-chi-square-tests"><span class="header-section-number">7.4</span> Categorical data: the chi-square tests</a>
  <ul class="collapse">
  <li><a href="#chi-square-goodness-of-fit-does-one-categorical-variable-match-an-expected-pattern" id="toc-chi-square-goodness-of-fit-does-one-categorical-variable-match-an-expected-pattern" class="nav-link" data-scroll-target="#chi-square-goodness-of-fit-does-one-categorical-variable-match-an-expected-pattern"><span class="header-section-number">7.4.1</span> Chi-square goodness-of-fit: does one categorical variable match an expected pattern?</a></li>
  <li><a href="#chi-square-test-of-independence-are-two-categorical-variables-related" id="toc-chi-square-test-of-independence-are-two-categorical-variables-related" class="nav-link" data-scroll-target="#chi-square-test-of-independence-are-two-categorical-variables-related"><span class="header-section-number">7.4.2</span> Chi-square test of independence: are two categorical variables related?</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">7.5</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/07-Nonparametric.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 27, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="parametric-vs.-nonparametric-tests" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="parametric-vs.-nonparametric-tests"><span class="header-section-number">7.1</span> Parametric vs.&nbsp;nonparametric tests</h2>
<p>Chapter 6 covered three flavors of the <span class="math inline">\(t\)</span>-test (one-sample, paired, and independent-samples, also called two-sample). All three need continuous, roughly normal data; the independent-samples test additionally assumes similar variance across the two groups. This chapter covers what to do when those assumptions aren’t met. We’ll also cover what to do if your data aren’t continuous at all.</p>
<p>So far, we’ve been looking at <strong>parametric</strong> tests, without calling them that. A test is parametric when we can only know the sampling distribution of its test statistic, the shape we compare our result against to get a <span class="math inline">\(p\)</span>-value, because we assumed something specific about the shape of the <strong>population</strong> the data came from. For the <span class="math inline">\(t\)</span>-test, that assumption is normality: the <span class="math inline">\(t\)</span>-distribution isn’t the shape of your raw data, it’s the shape the <span class="math inline">\(t\)</span>-statistic takes across repeated samples, and we can only derive that shape because we assumed the population itself was normal (or leaned on the Central Limit Theorem to get there for a large enough sample). Nonparametric tests, as you’ll see below, still end up with a known distribution for their own test statistics; they just don’t need to assume anything about the parent population’s shape to get there.</p>
<p>When the distributional assumptions are met, parametric tests are generally the most powerful available. However, when distributional assumptions are not met, parametric tests can become <strong>unreliable</strong>, and it may be difficult to understand how they become unreliable without extensive simulations. The worse the departures from assumed distributions, the worse the errors that may result.</p>
<p>Nonparametric tests make no assumption about the shape of the population’s distribution. Nonparametric does <strong>not</strong> mean assumption-free. But they usually have assumptions that are easier to satisfy than those of parametric tests.</p>
<p>Many nonparametric tests are run on the ranks of the data (first, second, third … last), rather than on the raw data. For example, the median - it’s a statistic based on ranks. It represents the middle rank in a data set.</p>
<p>We’ll talk about two different kinds of tools today:</p>
<ul>
<li><p><strong>Nonparametric alternatives</strong> (to t-tests). Your outcome is still continuous, but it’s skewed, has outliers, or your sample is too small to trust normality. The <strong>Wilcoxon signed-rank test</strong> and <strong>Mann-Whitney-Wilcoxon test</strong> answer the same questions as the one-sample/paired and independent-samples <span class="math inline">\(t\)</span>-tests, respectively, without assuming normality.</p></li>
<li><p><strong>Categorical data.</strong> Your outcome isn’t a number at all: a site either has an invasive species or it doesn’t, a sample either exceeds a threshold or it doesn’t. None of the tests above apply here; you need the <strong>chi-square (<span class="math inline">\(\chi^2\)</span>) tests</strong>.</p></li>
</ul>
<p>We’ll state the assumptions explicitly for each test as we go through them.</p>
<p><strong>A practical bonus of rank-based tests: ordinal data.</strong> Because the Wilcoxon and Mann-Whitney-Wilcoxon tests only need a rank ordering, neither is limited to interval- or ratio-scale measurements the way a <span class="math inline">\(t\)</span>-test is. A <span class="math inline">\(t\)</span>-test needs a mean, which requires numbers where the <em>distance</em> between values means something. Plenty of environmental data doesn’t work that way: a water-quality rating (poor, fair, good, excellent), a disturbance-severity class, a Likert-style survey response. You can put those in order, but “the average disturbance class was 2.4” isn’t meaningful the way “the average pH was 6.8” is. These rank-based tests only need the ordering, which ordinal data already has, so they apply directly where a <span class="math inline">\(t\)</span>-test can’t.</p>
</section>
<section id="nonparametric-alternative-to-one-sample-paired-t-test-the-wilcoxon-signed-rank-test" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="nonparametric-alternative-to-one-sample-paired-t-test-the-wilcoxon-signed-rank-test"><span class="header-section-number">7.2</span> Nonparametric alternative to one-sample &amp; paired t-test: the Wilcoxon signed-rank test</h2>
<p>Chapter 6 built the paired <span class="math inline">\(t\)</span>-test around this same idea, wetland restoration and soil moisture, with a full 20-plot dataset. Let’s run a smaller version of that same design, and this time actually check whether we should trust the result before reporting it.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Soil moisture (%) before and after restoration, 12 plots</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Plot</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Before</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">After</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Step 1: run the paired <span class="math inline">\(t\)</span>-test, the way Chapter 6 taught it.</strong></p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Paired t-test: soil moisture before vs. after restoration</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2.583333</td>
<td style="text-align: right;">2.57</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">0.026</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><span class="math inline">\(t(11) = 2.57\)</span>, <span class="math inline">\(p = .026\)</span>. Significant! Restoration looks like it increased soil moisture.</p>
<p><strong>Step 2: wait, did we check assumptions first?</strong> Let’s look at the differences before trusting that <span class="math inline">\(p\)</span>-value.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-8wilcoxon-hist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-Nonparametric_files/figure-html/fig-8wilcoxon-hist-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.1: Change in soil moisture per plot. Three plots showed no change at all, and the positive changes stretch out much further than the negative ones: not the symmetric, bell-shaped pattern a paired t-test assumes.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Shapiro-Wilk normality test on the differences</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.85</td>
<td style="text-align: left;">0.039</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The Shapiro-Wilk test agrees with the picture: <span class="math inline">\(p=.039\)</span>, a real violation, not a hypothetical one. Three plots didn’t change at all, three dropped slightly, and the rest jumped up by quite a lot; that’s not symmetric, let alone normal. The <span class="math inline">\(t\)</span>-test’s “significant” result was built on an assumption the data don’t meet. Time for the <strong>Wilcoxon signed-rank test</strong>.</p>
<p><strong>The question:</strong> did soil moisture systematically change after restoration, or is any change we see just plot-to-plot noise?</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: no systematic shift; the differences are symmetric around a median of 0 (positive and negative ranks are balanced).</p></li>
<li><p><span class="math inline">\(H_A\)</span>: there is a systematic shift; the median difference is not 0.</p></li>
</ul>
<p><strong>How it works, conceptually.</strong> Instead of using the actual sizes of the differences, the test converts them to ranks: it ranks the <em>absolute</em> differences from smallest to largest, then checks whether the positive-signed ranks and negative-signed ranks are roughly balanced. Balanced ranks are the null case: it would mean a plot’s rank (how extreme its change was) has nothing to do with whether that change was an increase or a decrease. If soil moisture really increased at most plots, the larger ranks should belong mostly to positive differences instead. Because it works with ranks rather than raw values, one wildly extreme plot can’t dominate the result the way it could with a mean.</p>
<p><strong>Its assumption.</strong> The Wilcoxon signed-rank test does not require normality, but it assumes the differences come from a <strong>symmetric distribution around their median</strong>. That’s a milder assumption than normality (symmetric-but-not-normal distributions are common), but our histogram above is pushing it: the positive side stretches to 8, the negative side barely reaches -1. We’ll run the test anyway, since it’s still the better-justified choice here, and note the strain honestly when we interpret the result.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Wilcoxon signed-rank test on restoration soil-moisture differences</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic (V)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Tails</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">39</td>
<td style="text-align: left;">0.057</td>
<td style="text-align: left;">Wilcoxon signed rank test with continuity correction</td>
<td style="text-align: left;">two.sided</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>“Two.sided” in the Tails column just means we tested for a shift in either direction, the same one-vs-two-tailed distinction from Chapter 6.</p>
<p>R falls back to a normal approximation twice over here: once for the tied differences (two plots at <span class="math inline">\(+6\)</span>, three at <span class="math inline">\(-1\)</span>), and once because three plots showed <em>no</em> change at all. Zero differences can’t be ranked as positive or negative, so the Wilcoxon test quietly drops them and runs on the remaining 9 plots instead of all 12. That’s worth thinking about: the rank test isn’t just less sensitive to magnitude than the <span class="math inline">\(t\)</span>-test, it can end up with less data entirely.</p>
<p><strong>How <span class="math inline">\(V\)</span> is actually calculated.</strong> Drop the zero differences, take the absolute value of what’s left, rank those absolute values from smallest to largest (tied absolute values share the average of their ranks), then sum the ranks belonging to the <em>positive</em> differences. That sum is <span class="math inline">\(V\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Ranking the nonzero restoration differences to calculate V</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Abs. difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rank</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sign</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6.5</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6.5</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8.0</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="even">
<td style="text-align: right;">-1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: left;">+</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><span class="math inline">\(V\)</span> is the sum of the ranks where Sign is “+”: <span class="math inline">\(6.5+6.5+5+8+9+4 = 39\)</span>, matching the table R gave us above.</p>
<p><strong>How the reference distribution is actually built.</strong> Under <span class="math inline">\(H_0\)</span>, each plot’s rank has an independent 50/50 chance of ending up positive or negative, purely by chance. That gives you <span class="math inline">\(2^n\)</span> equally likely sign patterns for <span class="math inline">\(n\)</span> nonzero differences (here, <span class="math inline">\(n=9\)</span>, not 12, since the zeros already dropped out), and summing the positive ranks for every one of those patterns builds a discrete probability distribution, not just a raw count. It has a known mean and variance:</p>
<p><span class="math display">\[E[V] = \frac{n(n+1)}{4}, \qquad \text{Var}(V) = \frac{n(n+1)(2n+1)}{24}\]</span></p>
<p>Plugging in our <span class="math inline">\(n=9\)</span> nonzero plots:</p>
<p><span class="math display">\[E[V] = \frac{9 \times 10}{4} = 22.5, \qquad \text{Var}(V) = \frac{9 \times 10 \times 19}{24} = 71.25\]</span></p>
<p>That’s an SD of about 8.4. Our observed <span class="math inline">\(V=39\)</span> sits about 1.96 SDs above that expectation (<span class="math inline">\(\frac{39-22.5}{8.4} \approx 1.96\)</span>), which is where R’s <span class="math inline">\(p=.057\)</span> comes from: a normal approximation to this exact distribution (with a ties and zeros adjustment). For small, tie-free samples with no zeros, R can instead read the exact enumerated distribution directly.</p>
<p>Where do the critical values actually come from? The same place they always do in this book: we build the null distribution ourselves, by simulating 20,000 experiments where each of the 9 nonzero ranks independently gets a random <span class="math inline">\(+\)</span> or <span class="math inline">\(-\)</span> sign, exactly what <span class="math inline">\(H_0\)</span> says should happen, and adding up the positive ranks each time.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-8wilcoxon-null" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-Nonparametric_files/figure-html/fig-8wilcoxon-null-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.2: Simulated null distribution of the Wilcoxon signed-rank statistic V, built from 20,000 random sign-flips of the 9 nonzero ranked differences. Shaded regions mark the two-tailed 5% rejection region; our observed V = 39 lands right on the boundary.</figcaption>
</figure>
</div>
</div>
</div>
<p>Our observed <span class="math inline">\(V=39\)</span> isn’t just close to the critical value; it <em>is</em> the critical value, 39, the exact boundary where the two-tailed 5% rejection region begins. That’s why <span class="math inline">\(p=.057\)</span> sits so close to <span class="math inline">\(\alpha=.05\)</span> without crossing it. Not significant, but only barely.</p>
<p><strong>So far: <span class="math inline">\(t\)</span>-test <span class="math inline">\(p=.026\)</span> (significant), Wilcoxon <span class="math inline">\(p=.057\)</span> (not quite).</strong> Same 12 plots, two different verdicts, because the <span class="math inline">\(t\)</span>-test’s numerator and denominator both used the exact magnitudes the Wilcoxon test deliberately ignores.</p>
<p><strong>The sign test.</strong> There’s an even simpler nonparametric option, the <strong>sign test</strong>, which looks only at whether each difference is positive or negative. It discards the magnitude entirely and asks whether pluses outnumber minuses more than chance would suggest. It has essentially no distributional assumption beyond the universal one (independence of observations, from a sound study design; see Chapter 6), not even symmetry. That’s genuinely useful here: we already flagged the symmetry assumption as shaky for this data (the positive side stretching to 8, the negative side barely reaching -1), so the sign test sidesteps the one assumption the Wilcoxon test still needed. That robustness comes at a big cost in power, though, so it’s usually a last resort.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Sign test on restoration soil-moisture differences</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Plots increased</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Plots total</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">0.508</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Six of the 9 nonzero plots increased. <span class="math inline">\(p=.508\)</span>: nowhere close to significant.</p>
<p><strong>The full picture.</strong> <span class="math inline">\(t\)</span>-test: <span class="math inline">\(p=.026\)</span>, significant. Wilcoxon signed-rank: <span class="math inline">\(p=.057\)</span>, not quite. Sign test: <span class="math inline">\(p=.508\)</span>, not close. Same 12 plots, three tests, three different verdicts. Each test gives up a little more than the last one, the <span class="math inline">\(t\)</span>-test uses the full magnitude of every difference, Wilcoxon keeps the ranks but drops the zeros, and the sign test keeps only direction, and the weaker the information, the weaker the evidence.</p>
<p>That’s not an argument that nonparametric tests are worse. The <span class="math inline">\(t\)</span>-test’s answer looked strongest here specifically because it leaned hardest on the assumption that turned out not to hold. Check your assumptions before you report a <span class="math inline">\(p\)</span>-value, not after you’ve already seen one you like.</p>
</section>
<section id="nonparametric-alternative-to-the-independent-samples-t-test-the-mann-whitney-wilcoxon-test" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="nonparametric-alternative-to-the-independent-samples-t-test-the-mann-whitney-wilcoxon-test"><span class="header-section-number">7.3</span> Nonparametric alternative to the independent-samples t-test: the Mann-Whitney-Wilcoxon test</h2>
<p>Now let’s run through the same kind of example for the independent-samples case. Researchers surveyed <strong>plant species richness</strong> (the number of distinct plant species found) at 8 restored wetland plots and 8 unrestored reference plots, to see whether restoration increased plant diversity.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Plant species richness at restored and unrestored wetland plots</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Plot</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Restored</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Unrestored</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Step 1: run the <span class="math inline">\(t\)</span>-test, the way Chapter 6 taught it.</strong></p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Independent-samples t-test: restored vs. unrestored richness</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6.375</td>
<td style="text-align: right;">2.54</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">0.024</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><span class="math inline">\(t(14) = 2.54\)</span>, <span class="math inline">\(p = .024\)</span>. Significant! Restoration looks like it increased richness.</p>
<p><strong>Step 2: wait, did we check assumptions first?</strong> We didn’t, and Chapter 6 was explicit that you’re supposed to. Let’s actually look at the data before trusting that <span class="math inline">\(p\)</span>-value.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-8richness-boxplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-Nonparametric_files/figure-html/fig-8richness-boxplot-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.3: Plant species richness by group. The circled restored plot has an unusually high richness count, visibly pulling that group’s distribution away from a normal, bell-shaped one.</figcaption>
</figure>
</div>
</div>
</div>
<p>The circled plot has 34 species, nearly double any other plot in either group. We don’t just throw away outliers; maybe that plot sits in an unusually favorable microhabitat. Either way, it’s a real violation of the normality assumption, not a hypothetical one:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Shapiro-Wilk normality test, by group</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Restored</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: left;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unrestored</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: left;">0.015</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Both groups fail the Shapiro-Wilk test, the restored group badly (<span class="math inline">\(p=.002\)</span>), driven almost entirely by that one plot. The <span class="math inline">\(t\)</span>-test’s “significant” result was built on top of an assumption the data don’t actually meet. This is exactly the situation the <strong>Mann-Whitney-Wilcoxon test</strong> was built for.</p>
<p><strong>The question:</strong> did restoration increase plant species richness, or is the difference we see consistent with random plot-to-plot variation?</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: no difference in richness between restored and unrestored plots; ranks are well-mixed between the groups.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: richness tends to rank systematically higher in one group than the other.</p></li>
</ul>
<p><strong>How it works, conceptually.</strong> Pool all the observations from both groups together, rank them from smallest to largest, then compare the sum of ranks in Group A to the sum of ranks in Group B. If the groups truly don’t differ, ranks should be well mixed between them; if one group tends to have higher values, its ranks should be systematically higher too. Critically, that outlier plot still gets <em>a</em> rank, but only one rank, the highest one, no matter how far above the pack it sits. Its magnitude, which is what distorted the <span class="math inline">\(t\)</span>-test, can’t distort the Mann-Whitney-Wilcoxon test the same way.</p>
<p><strong>Its assumption.</strong> The Mann-Whitney-Wilcoxon test assumes both groups’ parent distributions have the <strong>same shape</strong>: it does <em>not</em> require normality, and the assumption is <strong>not</strong> “equal variance,” even though same-shape distributions happen to have equal variance as a side effect. If the two groups have differently-shaped distributions (say, one skewed and one symmetric), the test still runs, but interpreting a significant result purely as “the medians differ” becomes murkier, since it could be a difference in location, shape, or both. Our two groups are both right-skewed by roughly the same amount, so that’s a reasonable assumption here.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Mann-Whitney-Wilcoxon test: restored vs. unrestored richness</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic (U)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Tails</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">50</td>
<td style="text-align: left;">0.063</td>
<td style="text-align: left;">Wilcoxon rank sum test with continuity correction</td>
<td style="text-align: left;">two.sided</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>R falls back to the normal approximation again, because both groups share some tied richness values (two plots at 16, two at 11, and so on).</p>
<p><strong>How the reference distribution is actually built.</strong> Same idea as the Wilcoxon signed-rank case above, just built from group membership instead of signs. Under <span class="math inline">\(H_0\)</span>, both groups are draws from the same population, so once you pool and rank all <span class="math inline">\(N = n_A + n_B = 16\)</span> values, which ranks end up in the restored group is just a matter of chance: any of the <span class="math inline">\(\binom{16}{8}\)</span> ways of splitting those 16 ranks into two groups of 8 is equally likely. That’s a real, discrete probability distribution, and its mean and variance are known:</p>
<p><span class="math display">\[E[U] = \frac{n_A n_B}{2}, \qquad \text{Var}(U) = \frac{n_A n_B (n_A+n_B+1)}{12}\]</span></p>
<p>Plugging in our two groups of 8:</p>
<p><span class="math display">\[E[U] = \frac{8 \times 8}{2} = 32, \qquad \text{Var}(U) = \frac{8 \times 8 \times 17}{12} \approx 90.7\]</span></p>
<p>That’s an SD of about 9.5. Our observed <span class="math inline">\(U=50\)</span> sits about 1.9 SDs above that expectation (<span class="math inline">\(\frac{50-32}{9.5} \approx 1.9\)</span>), which is where R’s <span class="math inline">\(p=.063\)</span> comes from: a normal approximation to this exact distribution (with a small ties adjustment), same mechanism as the Wilcoxon case. For small samples without ties, R can instead read the exact permutation distribution directly, no approximation needed.</p>
<p>Same question as before: where do the critical values come from? We build them the same way, by simulation. Under <span class="math inline">\(H_0\)</span>, group membership is random with respect to rank, so we pool the richness values, then repeatedly shuffle which 8 ranks land in the restored group:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-8mww-null" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-Nonparametric_files/figure-html/fig-8mww-null-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.4: Simulated null distribution of the Mann-Whitney U statistic, built from 20,000 random reshuffles of group membership among the pooled, ranked richness values. Shaded regions mark the two-tailed 5% rejection region; our observed U = 50 falls just inside the boundary.</figcaption>
</figure>
</div>
</div>
</div>
<p>Our observed <span class="math inline">\(U=50\)</span> lands just inside the critical value of <span class="math inline">\(50.5\)</span>, matching R’s <span class="math inline">\(p=.063\)</span>: close to significant, but not quite.</p>
<p><strong>The full picture.</strong> The <span class="math inline">\(t\)</span>-test said <span class="math inline">\(p=.024\)</span>: significant, restoration works. The Mann-Whitney-Wilcoxon test on the exact same data says <span class="math inline">\(p=.063\)</span>: not significant at <span class="math inline">\(\alpha=.05\)</span>, right on the boundary. Same 16 plots, same question, two different answers. One outlier plot was doing a lot of the work behind that “significant” <span class="math inline">\(t\)</span>-test result, and that’s exactly the kind of influence the normality assumption is supposed to rule out. That’s not a reason to always prefer the nonparametric test; if the data really had been roughly normal, the <span class="math inline">\(t\)</span>-test’s extra power would have been the right tool. It’s why you check assumptions <em>before</em> reporting a <span class="math inline">\(p\)</span>-value, not after.</p>
</section>
<section id="categorical-data-the-chi-square-tests" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="categorical-data-the-chi-square-tests"><span class="header-section-number">7.4</span> Categorical data: the chi-square tests</h2>
<p>Every test so far (the <span class="math inline">\(t\)</span>-tests in Chapter 6, and the Wilcoxon and Mann-Whitney-Wilcoxon tests above) needs a <strong>continuous</strong> outcome variable. But a lot of environmental data isn’t continuous at all: a site either has an invasive species or it doesn’t; a stream sample either exceeds a safety threshold or it doesn’t; a plot falls into one land-cover category, not a number line. For <strong>categorical</strong> data, none of the tests above apply: you need a different tool entirely, the <strong>chi-square (<span class="math inline">\(\chi^2\)</span>) test</strong>.</p>
<p>Chapter 3 introduced the shape of the chi-square distribution: always non-negative, right-skewed, naturally one-tailed, with its exact shape depending on degrees of freedom. Here’s what that rejection region looks like in practice, using the goodness-of-fit example below (one of the two chi-square tests you’ll meet in this section; more on what “goodness-of-fit” means right before we run it), which has <span class="math inline">\(df = 3\)</span>. The critical value at <span class="math inline">\(\alpha = .05\)</span> is 7.81; any statistic beyond that point (the shaded region) occurs less than 5% of the time by chance.</p>
<p>If you’re wondering how a “nonparametric” test can still have its own named distribution, that’s worth clearing up. “Nonparametric” is an assumption about your <strong>data</strong>, not the test statistic: you don’t need to assume the data came from a specific family like the normal distribution. Every test still needs a known reference distribution for its <strong>test statistic</strong> to produce a <span class="math inline">\(p\)</span>-value; what differs is how that reference distribution gets built. The chi-square distribution here, like the Wilcoxon and Mann-Whitney-Wilcoxon distributions earlier in this chapter, is built without any assumption about the data’s shape: chi-square from squared deviations under <span class="math inline">\(H_0\)</span>, the rank tests from all possible rank arrangements. That’s what “distribution-free” actually means: the statistic’s distribution is known, but building it never required assuming anything about the data.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-8chisq-crit" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-Nonparametric_files/figure-html/fig-8chisq-crit-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.5: The chi-square distribution with df = 3. The shaded region marks the rejection region at alpha = .05 (critical value 7.81). Our goodness-of-fit statistic, X-squared = 5.4, falls short of it.</figcaption>
</figure>
</div>
</div>
</div>
<p>There are two versions of the chi-square test, depending on the question you’re asking.</p>
<section id="chi-square-goodness-of-fit-does-one-categorical-variable-match-an-expected-pattern" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="chi-square-goodness-of-fit-does-one-categorical-variable-match-an-expected-pattern"><span class="header-section-number">7.4.1</span> Chi-square goodness-of-fit: does one categorical variable match an expected pattern?</h3>
<p>The name comes straight from what the test does: it checks how well (“goodness”) your observed counts match (“fit”) a specific pattern you’d expect, whether that expectation comes from a historical baseline, a theory, or an assumption of “equally likely.” A small chi-square statistic means a good fit (observed counts close to expected); a large one means a poor fit (observed counts far from expected).</p>
<p>A state wildlife agency has historically found fish evenly distributed across four zones of a lake: 25% of fish in each zone. This year’s survey of 200 fish gives a different picture:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Observed fish counts by lake zone (n = 200)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Zone</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Observed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">52</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">49</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>The question:</strong> does this year’s distribution across zones differ from the historical 25%-each pattern, or is this the kind of unevenness you’d expect from random sampling alone?</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: fish are still distributed 25% per zone; the pattern matches the historical baseline.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: fish are not evenly distributed across zones; the pattern has changed.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Chi-square goodness-of-fit test</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic (χ²)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5.4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">0.145</td>
<td style="text-align: left;">Chi-squared test for given probabilities</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Assumption.</strong> The goodness-of-fit test doesn’t assume anything about the shape of your data (categories aren’t numbers, so there’s no shape to assume). It does have a practical requirement instead: <strong>expected counts should generally be 5 or more</strong> in each category. That “5” is a conventional rule of thumb, not something calculated from this data or compared to a critical value; it’s a check on whether the chi-square curve is a trustworthy approximation, done <em>before</em> the test itself runs. Here, expected count per zone is <span class="math inline">\(200 \times 0.25 = 50\)</span> (total fish times the 25%-per-zone expectation under <span class="math inline">\(H_0\)</span>), comfortably above that minimum. When expected counts are too small, the chi-square approximation breaks down and a different method (like Fisher’s exact test) is more appropriate.</p>
<p><strong>Where <span class="math inline">\(\chi^2\)</span> actually comes from.</strong> For each category, take the squared difference between observed and expected, scaled by expected: <span class="math inline">\(\chi^2 = \sum \frac{(O-E)^2}{E}\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Chi-square contribution by zone</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Zone</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Observed</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Expected</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Contribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">2.88</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">2.42</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0.02</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Summing the last column: <span class="math inline">\(2.88+2.42+0.08+0.02 = 5.4\)</span>, matching R’s statistic above. With <span class="math inline">\(df=3\)</span>, the critical value at <span class="math inline">\(\alpha=.05\)</span> is 7.81 (the same one marked on the distribution figure earlier in this chapter); our <span class="math inline">\(5.4\)</span> falls well short of it.</p>
<p><strong>Interpretation.</strong> <span class="math inline">\(\chi^2(3) = 5.4\)</span>, <span class="math inline">\(p = .145\)</span>: not significant. This year’s zone counts are consistent with the historical 25%-each pattern; the unevenness we see is within the range chance alone would produce.</p>
</section>
<section id="chi-square-test-of-independence-are-two-categorical-variables-related" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="chi-square-test-of-independence-are-two-categorical-variables-related"><span class="header-section-number">7.4.2</span> Chi-square test of independence: are two categorical variables related?</h3>
<p>Now suppose researchers classify 150 stream sites by <strong>land use</strong> (Forested, Agricultural, Urban) and whether each site’s <em>E. coli</em> level <strong>exceeds</strong> a recreational safety threshold:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Stream sites by land use and E. coli exceedance</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Forested</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agricultural</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">30</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>The question:</strong> is <em>E. coli</em> exceedance <strong>independent</strong> of land use, or are they related?</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: land use and exceedance are independent; knowing one tells you nothing about the other.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: land use and exceedance are related; they are not independent.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Chi-square test of independence</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic (χ²)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">21.84</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">Pearson's Chi-squared test</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Assumption.</strong> Same rule as goodness-of-fit: expected counts should generally be 5 or more in every cell of the table. Unlike the goodness-of-fit test, where expected counts came from a stated proportion (25% per zone), here they come from the table’s own row and column totals: the expected count for a cell is <span class="math inline">\(\frac{\text{row total} \times \text{column total}}{\text{grand total}}\)</span>, the count you’d see in that cell if land use and exceedance really were unrelated. For Forested/No, that’s <span class="math inline">\(\frac{50 \times 87}{150} = 29\)</span> (50 forested sites total, 87 sites total with no exceedance, 150 sites overall).</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Expected counts under H0 (independence)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Forested</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agricultural</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">21</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>All six expected counts are between 21 and 29, well above the 5-count minimum from the assumption check above; that’s a separate question from whether the test is significant, just whether the chi-square approximation is trustworthy here.</p>
<p><strong>Where <span class="math inline">\(\chi^2\)</span> actually comes from.</strong> Same formula as the goodness-of-fit test, applied cell by cell instead of category by category: <span class="math inline">\(\chi^2 = \sum \frac{(O-E)^2}{E}\)</span>, using the observed table and the expected table above.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Chi-square contribution by cell</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Forested</td>
<td style="text-align: right;">5.83</td>
<td style="text-align: right;">8.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agricultural</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Urban</td>
<td style="text-align: right;">2.79</td>
<td style="text-align: right;">3.86</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Summing all six cells: <span class="math inline">\(5.83+8.05+0.55+0.76+2.79+3.86 = 21.84\)</span>, matching R’s statistic above. With <span class="math inline">\(df=2\)</span>, the critical value at <span class="math inline">\(\alpha=.05\)</span> is 5.99; our <span class="math inline">\(21.84\)</span> is more than three times that, which is where <span class="math inline">\(p&lt;.001\)</span> comes from.</p>
<p><strong>Interpretation.</strong> <span class="math inline">\(\chi^2(2) = 21.84\)</span>, <span class="math inline">\(p &lt; .001\)</span>: significant. <em>E. coli</em> exceedance is not independent of land use: forested sites exceed the threshold far less often (8 of 50) than agricultural (25 of 50) or urban (30 of 50) sites. Note what this test does <em>not</em> tell you: it says the two variables are related, but, just like correlation, it doesn’t by itself establish that land use <em>causes</em> the exceedance.</p>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">7.5</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> Real environmental data often breaks the rules a <span class="math inline">\(t\)</span>-test needs: small samples, skewed distributions, or outcomes that are counts and categories rather than measurements. This chapter is the toolkit for those cases, and for recognizing when you are in one.</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>Rank-based tests trade power for weaker assumptions.</strong> The <strong>Wilcoxon signed-rank</strong> and <strong>Mann-Whitney-Wilcoxon</strong> tests ask the same questions as the paired and independent-samples <span class="math inline">\(t\)</span>-tests, but work from ranks instead of raw magnitudes. That buys a milder distributional assumption at the cost of some sensitivity.</li>
<li><strong>The trade-off is a spectrum.</strong> The <strong>sign test</strong> goes further still, using only the direction of each difference. On the same restoration data, the <span class="math inline">\(t\)</span>-test, Wilcoxon, and sign test gave progressively weaker verdicts, because each one throws away more information than the last.</li>
<li><strong>Nonparametric does not mean assumption-free.</strong> Wilcoxon assumes the differences are symmetric about their median. Mann-Whitney-Wilcoxon assumes the two distributions have the same <em>shape</em>, which is not the same as equal variance. State the assumption you are actually making.</li>
<li><strong>Check assumptions before you trust a <span class="math inline">\(p\)</span>-value, not after.</strong> Both worked examples in this chapter ran the parametric test first, then went back and found the violation. That order is deliberate, because it is the mistake most people actually make.</li>
<li><strong>Categorical data needs a different tool entirely.</strong> The <strong>chi-square tests</strong> handle counts: goodness-of-fit asks whether one variable’s counts match an expected pattern, and the test of independence asks whether two categorical variables are related.</li>
<li><strong>The testing logic never changes.</strong> State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_A\)</span>, compute a statistic, and ask how surprising that statistic would be if <span class="math inline">\(H_0\)</span> were true. Only the statistic and its reference distribution differ from test to test.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-ttests.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-ANOVA.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>