<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory Barnes">

<title>Answering questions with data - 7&nbsp; t-tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-ANOVA.html" rel="next">
<link href="./06-Hypothesis_Testing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 7&nbsp; t-tests">
<meta property="og:description" content="">
<meta property="og:image" content="07-ttests_files/figure-html/fig-7-z-vs-t-linear-log-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 7&nbsp; t-tests">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-ttests.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-tests</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ttests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-MixedANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Libraries (top)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Gifs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">GIFs</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#intro" id="toc-intro" class="nav-link active" data-scroll-target="#intro"><span class="header-section-number">7.1</span> Intro</a></li>
  <li><a href="#from-mean-sd-to-signal-over-noise" id="toc-from-mean-sd-to-signal-over-noise" class="nav-link" data-scroll-target="#from-mean-sd-to-signal-over-noise"><span class="header-section-number">7.2</span> From mean &amp; SD to “signal over noise”</a></li>
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test"><span class="header-section-number">7.3</span> One-sample t-test</a>
  <ul class="collapse">
  <li><a href="#comparing-z-and-t" id="toc-comparing-z-and-t" class="nav-link" data-scroll-target="#comparing-z-and-t"><span class="header-section-number">7.3.1</span> Comparing <span class="math inline">\(z\)</span> and <span class="math inline">\(t\)</span></a></li>
  <li><a href="#what-t-represents" id="toc-what-t-represents" class="nav-link" data-scroll-target="#what-t-represents"><span class="header-section-number">7.3.2</span> What t represents</a></li>
  <li><a href="#calculating-t-from-data" id="toc-calculating-t-from-data" class="nav-link" data-scroll-target="#calculating-t-from-data"><span class="header-section-number">7.3.3</span> Calculating t from data</a></li>
  <li><a href="#how-does-t-behave" id="toc-how-does-t-behave" class="nav-link" data-scroll-target="#how-does-t-behave"><span class="header-section-number">7.3.4</span> How does t behave?</a></li>
  </ul></li>
  <li><a href="#paired-t-beforeafter-or-matched" id="toc-paired-t-beforeafter-or-matched" class="nav-link" data-scroll-target="#paired-t-beforeafter-or-matched"><span class="header-section-number">7.4</span> Paired t: before/after or matched</a>
  <ul class="collapse">
  <li><a href="#calculate-t" id="toc-calculate-t" class="nav-link" data-scroll-target="#calculate-t"><span class="header-section-number">7.4.1</span> Calculate t</a></li>
  <li><a href="#interpreting-ts" id="toc-interpreting-ts" class="nav-link" data-scroll-target="#interpreting-ts"><span class="header-section-number">7.4.2</span> Interpreting <span class="math inline">\(t\)</span>s</a></li>
  <li><a href="#getting-the-p-values-for-t-values" id="toc-getting-the-p-values-for-t-values" class="nav-link" data-scroll-target="#getting-the-p-values-for-t-values"><span class="header-section-number">7.4.3</span> Getting the p-values for <span class="math inline">\(t\)</span>-values</a></li>
  <li><a href="#one-tailed-tests" id="toc-one-tailed-tests" class="nav-link" data-scroll-target="#one-tailed-tests"><span class="header-section-number">7.4.4</span> One-tailed tests</a></li>
  <li><a href="#two-tailed-tests" id="toc-two-tailed-tests" class="nav-link" data-scroll-target="#two-tailed-tests"><span class="header-section-number">7.4.5</span> Two-tailed tests</a></li>
  <li><a href="#one-or-two-tailed-which-one" id="toc-one-or-two-tailed-which-one" class="nav-link" data-scroll-target="#one-or-two-tailed-which-one"><span class="header-section-number">7.4.6</span> One or two tailed, which one?</a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom"><span class="header-section-number">7.4.7</span> Degrees of freedom</a></li>
  </ul></li>
  <li><a href="#the-paired-samples-t-test-strikes-back" id="toc-the-paired-samples-t-test-strikes-back" class="nav-link" data-scroll-target="#the-paired-samples-t-test-strikes-back"><span class="header-section-number">7.5</span> The paired samples t-test strikes back</a></li>
  <li><a href="#two-independent-groups" id="toc-two-independent-groups" class="nav-link" data-scroll-target="#two-independent-groups"><span class="header-section-number">7.6</span> Two independent groups</a></li>
  <li><a href="#simulating-data-for-t-tests" id="toc-simulating-data-for-t-tests" class="nav-link" data-scroll-target="#simulating-data-for-t-tests"><span class="header-section-number">7.7</span> Simulating data for t-tests</a>
  <ul class="collapse">
  <li><a href="#simulating-a-one-sample-t-test" id="toc-simulating-a-one-sample-t-test" class="nav-link" data-scroll-target="#simulating-a-one-sample-t-test"><span class="header-section-number">7.7.1</span> Simulating a one-sample t-test</a></li>
  <li><a href="#simulating-a-paired-samples-t-test" id="toc-simulating-a-paired-samples-t-test" class="nav-link" data-scroll-target="#simulating-a-paired-samples-t-test"><span class="header-section-number">7.7.2</span> Simulating a paired samples t-test</a></li>
  <li><a href="#simulating-an-independent-samples-t.test" id="toc-simulating-an-independent-samples-t.test" class="nav-link" data-scroll-target="#simulating-an-independent-samples-t.test"><span class="header-section-number">7.7.3</span> Simulating an independent samples t.test</a></li>
  </ul></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"><span class="header-section-number">7.8</span> Videos</a>
  <ul class="collapse">
  <li><a href="#one-or-two-tailed-tests" id="toc-one-or-two-tailed-tests" class="nav-link" data-scroll-target="#one-or-two-tailed-tests"><span class="header-section-number">7.8.1</span> One or Two tailed tests</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/07-ttests.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-tests</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 6, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="intro" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="intro"><span class="header-section-number">7.1</span> Intro</h2>
<p>In the early 1900s, William Sealy Gosset joined <strong>Guinness</strong>, then the world’s largest brewery. Guinness hired scientifically trained brewers and gave them latitude to pursue research that improved the product. As production scaled, quality control mattered: a pint should taste the same in Dublin as in Detroit. Until then, hop quality was judged mostly by appearance and smell, which was unreliable. Chemical assays could measure ingredients, but the core problem was statistical. Inference relied on the normal (Z) distribution, which works well when samples are large enough for a normal approximation. In practice, Guinness could not destroy large volumes of beer or ingredients just to test them.</p>
<p>Gosset set out to quantify the extra uncertainty introduced by <strong>small</strong> samples. How much wider is the error around an estimate when <span class="math inline">\(n=10\)</span> instead of <span class="math inline">\(n=1000\)</span>? He derived a new sampling distribution that accounts for small-sample variability, now known as the <strong>Student’s (t) distribution</strong>. Because Guinness restricted external publications, he published the 1908 paper under the pseudonym <strong>“Student”</strong> <span class="citation" data-cites="Student1908">(<a href="references.html#ref-Student1908" role="doc-biblioref">Student 1908</a>)</span>. That is why we still say <strong>Student’s</strong> <span class="math inline">\(t\)</span>-test. The core idea you will use today is the same: measure a signal, scale it by its standard error, and compare the resulting <span class="math inline">\(t\)</span> to the appropriate <span class="math inline">\(t\)</span> distribution for your <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
<p><strong>Why this matters.</strong> We often compare a sample mean to a reference (drinking-water standard, historical average) or compare two conditions (before/after, site A vs site B). A t-test asks whether the observed difference is larger than you would expect from sampling variation alone, given your <span class="math inline">\(n\)</span> and variability.</p>
<p><strong>Three common t-tests you will use.</strong></p>
<ol type="1">
<li><strong>One-sample t-test.</strong> Compare a sample mean to a target (<span class="math inline">\(\mu_0\)</span>).</li>
<li><strong>Paired t-test.</strong> Compare before/after (or matched) measurements on the same units by running a one-sample t on the <em>differences</em>.</li>
<li><strong>Independent-samples t-test (also called two-sample t-test)</strong> Compare means from two groups measured on different units. Use Welch’s test by default when variances differ.</li>
</ol>
<p><strong>What you will report.</strong></p>
<p>Always report:</p>
<ul>
<li>the effect size (mean difference)</li>
<li>a 95% CI, the test statistic with df</li>
<li>and the <span class="math inline">\(p\)</span>-value.</li>
</ul>
<p>Example: “Mean change was (-0.42) units (95% CI [-0.73,-0.11] ;t(11)=-2.92; p=0.014).”</p>
</section>
<section id="from-mean-sd-to-signal-over-noise" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="from-mean-sd-to-signal-over-noise"><span class="header-section-number">7.2</span> From mean &amp; SD to “signal over noise”</h2>
<p>A mean tells you where the center is; the SD tells you how spread out the data are. A mean of 50 could be very representative (if SD is tiny) or nearly meaningless (if SD is huge). You need both.</p>
<p>A simple way to combine them is a ratio:</p>
<p><span class="math display">\[
\frac{\text{mean}}{\text{SD}}
\]</span></p>
<ul>
<li><p>Big numerator, small denominator → big ratio (more confidence that the mean reflects the data).</p></li>
<li><p>Small numerator or big denominator → small ratio (less confidence).</p></li>
</ul>
<p>For instance, mean = 50 with SD = 1 gives 50; mean = 50 with SD = 100 gives 0.5. Same mean, very different stories.</p>
<p>This “signal over noise” pattern shows up everywhere in inference. In general,</p>
<p><span class="math display">\[
\text{statistic}=\frac{\text{effect}}{\text{error}}.
\]</span></p>
<p>For <span class="math inline">\(t\)</span>-tests, we won’t actually use SD in the denominator, we use the <strong>standard error</strong> <span class="math inline">\(SE\)</span>, which is the SD of the sample mean. But the logic is the same: measure a signal, scale it by its uncertainty, and see whether the resulting ratio is unusually large or small under the right <span class="math inline">\(t\)</span> distribution.</p>
<p><span class="math display">\[
t = \frac{\text{effect}}{\text{standard error}} = \frac{\bar{X} - \mu_0}{s / \sqrt{n}}
\]</span></p>
<p>We now turn that ratio into a test statistic for a <em>single mean</em>.</p>
</section>
<section id="one-sample-t-test" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="one-sample-t-test"><span class="header-section-number">7.3</span> One-sample t-test</h2>
<p>Use a one-sample <span class="math inline">\(t\)</span> when you want to test whether a sample mean differs from a reference value (<span class="math inline">\(\mu_0\)</span>). The question: is the observed difference bigger than you’d expect from sampling variability, given <span class="math inline">\(n\)</span> and your sample SD <span class="math inline">\(s\)</span>?</p>
<p><span class="math display">\[
t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}, \qquad df = n-1
\]</span></p>
<p>After calculating <span class="math inline">\(t\)</span> from our data, we compare the observed <span class="math inline">\(t\)</span> to a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-1\)</span> degrees of freedom to get a <span class="math inline">\(p\)</span>-value and a decision at <span class="math inline">\(\alpha\)</span>.</p>
<section id="comparing-z-and-t" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="comparing-z-and-t"><span class="header-section-number">7.3.1</span> Comparing <span class="math inline">\(z\)</span> and <span class="math inline">\(t\)</span></h3>
<p>When the population SD is known (or we have a large enough sample to assume convergence), the ratio is called <span class="math inline">\(z\)</span>; when it’s estimated from the data, it’s <span class="math inline">\(t\)</span>.”</p>
<p>Under a known population SD (<span class="math inline">\(\sigma\)</span>), the standardized mean uses the <span class="math inline">\(z\)</span> statistic: <span class="math display">\[
z = \frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}
\]</span></p>
<p>When <span class="math inline">\(\sigma\)</span> is <strong>unknown</strong> (the usual case), we estimate it with the sample SD (<span class="math inline">\(s\)</span>) and use the <span class="math inline">\(t\)</span> statistic: <span class="math display">\[
t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}, \qquad df = n-1
\]</span></p>
<p>Because <span class="math inline">\(s\)</span> varies from sample to sample, the <span class="math inline">\(t\)</span> distribution has <strong>heavier tails</strong> than the standard normal. As <span class="math inline">\(n\)</span> grows, <span class="math inline">\(s\)</span> stabilizes and <span class="math inline">\(t\)</span> <strong>converges</strong> to <span class="math inline">\(z\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7-z-vs-t-linear-log" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7-z-vs-t-linear-log-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.1: Normal (<span class="math inline">\(z\)</span>) vs <span class="math inline">\(t\)</span> distributions: on a linear scale (top), tail differences look small; on a log scale (bottom), the heavy tails of small-<span class="math inline">\(n\)</span> <span class="math inline">\(t\)</span> are clear.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>When is</strong> <span class="math inline">\(z\)</span> appropriate? If the population SD <span class="math inline">\(\sigma\)</span> is known <em>and</em> the sampling distribution of the mean is (approximately) normal, use <span class="math inline">\(z\)</span>. In practice, <span class="math inline">\(\sigma\)</span> is rarely known, so we use <span class="math inline">\(t\)</span> with <span class="math inline">\(s\)</span> and <span class="math inline">\(df=n-1\)</span>.</p>
</div>
</div>
<p><strong>Rule of thumb.</strong> For two-tailed tests at <span class="math inline">\(\alpha=0.05\)</span>:</p>
<ul>
<li><span class="math inline">\(z\)</span> uses critical values <span class="math inline">\(\pm 1.96\)</span>.</li>
<li><span class="math inline">\(t\)</span> is a bit wider for small <span class="math inline">\(n\)</span> (e.g., <span class="math inline">\(df=9 \Rightarrow \pm 2.262\)</span>; <span class="math inline">\(df=29 \Rightarrow \pm 2.045\)</span>), and approaches <span class="math inline">\(\pm 1.96\)</span> as <span class="math inline">\(n\)</span> increases.</li>
</ul>
</section>
<section id="what-t-represents" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="what-t-represents"><span class="header-section-number">7.3.2</span> What t represents</h3>
<p>Either way, the ratio asks the same question: how far is the mean from the reference in SE units?</p>
<p><span class="math inline">\(t\)</span> expresses how far a sample mean is from the hypothesized mean, in <strong>standard error units</strong> (signal over noise):</p>
<p><span class="math display">\[
t = \frac{\bar{X}-\mu_0}{s/\sqrt{n}}
\]</span></p>
<p><span class="math inline">\(t\)</span> can be positive or negative depending on direction. Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(t \sim t_{(df=n-1)}\)</span>.<br>
<strong>Rule of thumb:</strong> at <span class="math inline">\(\alpha=.05\)</span> two-tailed, <span class="math inline">\(|t|\gtrsim 2\)</span> is uncommon when <span class="math inline">\(df\approx 20\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Remember, <span class="math inline">\(s/\sqrt{n}\)</span> is the <strong>standard error (SE)</strong>—the standard deviation of the sampling distribution of the mean.</p>
</div>
</div>
<p>Let’s see how <span class="math inline">\(t\)</span> values behave when samples really come from the null hypothesis. Under the null hypothesis, <span class="math inline">\(t\)</span> follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(df = n-1\)</span>.<br>
Large <span class="math inline">\(|t|\)</span> values are rare; with <span class="math inline">\(df \approx 20\)</span>, <span class="math inline">\(|t| \gtrsim 2\)</span> is uncommon at <span class="math inline">\(\alpha = .05\)</span> (two-tailed).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7t-sim" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7t-sim-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.2: Histogram of 1,000 simulated <span class="math inline">\(t\)</span> values (<span class="math inline">\(n=10\)</span>) drawn from a population with <span class="math inline">\(\mu_0=0\)</span>. Most <span class="math inline">\(t\)</span>s cluster near 0; large positive or negative values are rare.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Takeaway:</strong> <span class="math inline">\(t\)</span> measures how far the sample mean is from the null expectation, scaled by its uncertainty. It behaves predictably under <span class="math inline">\(H_0\)</span>, allowing us to decide whether a difference is likely due to chance.</p>
</section>
<section id="calculating-t-from-data" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="calculating-t-from-data"><span class="header-section-number">7.3.3</span> Calculating t from data</h3>
<p>Let’s calculate a one-sample <span class="math inline">\(t\)</span> statistic step by step using a short example. Ten students each took a 5-question true/false quiz (50% expected by chance). Their scores (percent correct) are:</p>
<p><strong>Scores</strong>: (50, 70, 60, 40, 80, 30, 90, 60, 70, 60)</p>
<div class="cell">
<pre><code>#&gt; [1] 61
#&gt; [1] 17.91957
#&gt; [1] 5.666667
#&gt;        t 
#&gt; 1.941176
#&gt; df 
#&gt;  9
#&gt; [1] 0.08415031
#&gt; [1] 48.18111 73.81889
#&gt; attr(,"conf.level")
#&gt; [1] 0.95
#&gt; mean of x 
#&gt;        61</code></pre>
</div>
<p><strong>Results (R):</strong> <span class="math inline">\(t(9)=1.94\)</span>, <span class="math inline">\(p=0.0842\)</span>; mean <span class="math inline">\(=61\)</span> (95% CI(48.18,73.82)).</p>
<p><strong>Interpretation:</strong> The mean (61%) is above chance (50%), but not statistically significant at <span class="math inline">\(\alpha=.05\)</span>.</p>
<p><strong>Assumptions check:</strong> Independence of observations; approximate normality of the outcome (with <span class="math inline">\(n=10\)</span>, mild deviations are acceptable for a one-sample <span class="math inline">\(t\)</span>).</p>
<p>We can confirm this with a single R command:</p>
<p><code>t.test(scores, mu = 5</code></p>
<p>The standard error of the mean, is the standard deviation divided by the square root of <span class="math inline">\(n\)</span></p>
<p><span class="math inline">\(\text{SEM} = \frac{s}{\sqrt{n}} = \frac{17.92}{10} = 5.67\)</span></p>
<p><span class="math inline">\(t\)</span> is the difference between our sample mean (61), and our population mean (50, assuming chance), divided by the standard error of the mean.</p>
<p><span class="math inline">\(\text{t} = \frac{\bar{X}-u}{S_{\bar{X}}} = \frac{\bar{X}-u}{SEM} = \frac{61-50}{5.67} = 1.94\)</span></p>
<p><strong>Interpretation:</strong> The sample mean (61%) is higher than chance (50%), but the difference is not large enough to be statistically significant at <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><strong>Assumptions check:</strong> Observations are independent, and with <span class="math inline">\(n=10\)</span> the data are approximately normal—sufficient for a one-sample <span class="math inline">\(t\)</span> test.</p>
</section>
<section id="how-does-t-behave" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="how-does-t-behave"><span class="header-section-number">7.3.4</span> How does t behave?</h3>
<p>Under the null hypothesis (<span class="math inline">\(H_0\)</span> true), <span class="math inline">\(t\)</span> follows a <em>t</em> distribution with degrees of freedom <span class="math inline">\(df = n - 1\)</span>. Large <span class="math inline">\(|t|\)</span> values are rare—extreme sample means are unlikely if <span class="math inline">\(H_0\)</span> is true.</p>
<p>For moderate sample sizes (<span class="math inline">\(df \approx 20\)</span>), a simple rule of thumb is:</p>
<blockquote class="blockquote">
<p>In a two-tailed test at <span class="math inline">\(\alpha = .05\)</span>, <span class="math inline">\(|t| \gtrsim 2\)</span> is uncommon.</p>
</blockquote>
<p>This means values of <span class="math inline">\(t\)</span> beyond roughly <span class="math inline">\(-2\)</span> or <span class="math inline">\(+2\)</span> occur less than 5% of the time under the null. That’s the foundation of the decision rule for <span class="math inline">\(t\)</span> tests: if your observed <span class="math inline">\(t\)</span> lies in those rare tails, you reject <span class="math inline">\(H_0\)</span>.</p>
<p>Remember, if we obtained a single <span class="math inline">\(t\)</span> from one sample we collected, we could consult the chance window in <a href="#fig-7-t-rejection">Figure&nbsp;<span>7.3</span></a> below to find out whether the <span class="math inline">\(t\)</span> we obtained from the sample was likely or unlikely to occur by chance.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7-t-rejection" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7-t-rejection-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.3: Two-tailed rejection regions at <span class="math inline">\(\alpha=.05\)</span> for <span class="math inline">\(t_{(df=9)}\)</span>. Shaded tails mark unlikely values under <span class="math inline">\(H_0\)</span>.</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="paired-t-beforeafter-or-matched" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="paired-t-beforeafter-or-matched"><span class="header-section-number">7.4</span> Paired t: before/after or matched</h2>
<p>When the <strong>same units</strong> are measured twice (before/after, matched pairs), the question is whether they <strong>changed</strong>. The natural data unit is the <strong>within-unit difference</strong>.</p>
<p><strong>Design in this worked example.</strong> Ecologists measured <strong>soil moisture (%)</strong> at 20 paired field plots before and after wetland restoration. Each plot was measured twice — once during the dry season before restoration work began, and again one year later. We care whether restoration <strong>increased</strong> soil moisture, which would support plant reestablishment and carbon sequestration.</p>
<p><strong>Define differences and their meaning.</strong> Choose an order and stick to it:</p>
<ul>
<li><span class="math inline">\(d_i = \text{After}_i - \text{Before}_i\)</span></li>
<li><span class="math inline">\(d_i&gt;0\)</span>: plot had <strong>more</strong> soil moisture after restoration (increase)</li>
<li><span class="math inline">\(d_i&lt;0\)</span>: plot had <strong>less</strong> soil moisture after restoration (decrease)</li>
</ul>
<p>This subtraction <strong>cancels between-plot variability</strong> (some plots are naturally wetter than others) and focuses on <strong>within-plot change</strong>.</p>
<p><strong>Test on differences (paired (t)).</strong> Compute one difference per plot, then run a <strong>one-sample</strong> <span class="math inline">\(t\)</span> against 0:</p>
<p><span class="math display">\[
\bar d=\frac{1}{n}\sum_{i=1}^n d_i, \quad
s_d=\text{SD}(d_1,\ldots,d_n), \quad
t = \frac{\bar d - 0}{s_d/\sqrt{n}}, \quad df=n-1.
\]</span></p>
<p>The <strong>sign of (t)</strong> matches (d) and your difference direction.</p>
<p><strong>Mini walk-through (first 5 plots).</strong> Using five representative plots, suppose <span class="math inline">\(\bar d = 2.8\)</span> and <span class="math inline">\(s_d = 3.35\)</span>. Then <span class="math display">\[
t=\frac{2.8}{3.35/\sqrt{5}} \approx 1.87,\qquad df=4,
\]</span> which (two-tailed) is <strong>not</strong> significant. That’s expected with <span class="math inline">\(n=5\)</span>.</p>
<p><strong>Full sample effect.</strong> With all 20 plots, <span class="math inline">\(\bar d\)</span> is similar but <span class="math inline">\(s_d/\sqrt{n}\)</span> gets smaller, so <span class="math inline">\(t\)</span> increases and the result becomes significant. This is the payoff of pairing: more power from the same number of plots.</p>
<p><strong>What to report.</strong> (d) (the mean change), a 95% CI, (t(df)), and (p). Optionally add a standardized effect (Cohen’s (d=d/s_d)).</p>
<p><strong>R pointers (you’ll do this in lab).</strong></p>
<ul>
<li>Compute differences: <code>d &lt;- after - before</code></li>
<li>Paired <span class="math inline">\(t\)</span>: <code>t.test(d, mu = 0)</code> or <code>t.test(after, before, paired = TRUE)</code></li>
<li>CI for <span class="math inline">\(\bar d\)</span>: from the <code>t.test</code> output</li>
</ul>
<section id="calculate-t" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="calculate-t"><span class="header-section-number">7.4.1</span> Calculate t</h3>
<p>OK, so how do we calculate <span class="math inline">\(t\)</span> for a paired-samples <span class="math inline">\(t\)</span>-test? Surprise, we use the one-sample t-test formula that you already learned about! Specifically, we use the one-sample <span class="math inline">\(t\)</span>-test formula on the difference scores. We have one sample of difference scores (you can see they are in one column), so we can use the one-sample <span class="math inline">\(t\)</span>-test on the difference scores. Specifically, we are interested in comparing whether the mean of our difference scores came from a distribution with mean difference = 0. This is a special distribution we refer to as the <strong>null distribution</strong>. It is the distribution no differences. Of course, this <strong>null distribution</strong> can produce differences due to to sampling error, but those differences are not caused by any experimental manipulation, they caused by the random sampling process.</p>
<p>We calculate <span class="math inline">\(t\)</span> in a moment. Let’s now consider again why we want to calculate <span class="math inline">\(t\)</span>? Why don’t we just stick with the mean difference we already have?</p>
<p>Remember, the whole concept behind <span class="math inline">\(t\)</span>, is that it gives an indication of how confident we should be in our mean. Remember, <span class="math inline">\(t\)</span> involves a measure of the mean in the numerator, divided by a measure of variation (standard error of the sample mean) in the denominator. The resulting <span class="math inline">\(t\)</span> value is small when the mean difference is small, or when the variation is large. So small <span class="math inline">\(t\)</span>-values tell us that we shouldn’t be that confident in the estimate of our mean difference. Large <span class="math inline">\(t\)</span>-values occur when the mean difference is large and/or when the measure of variation is small. So, large <span class="math inline">\(t\)</span>-values tell us that we can be more confident in the estimate of our mean difference. Let’s find <span class="math inline">\(t\)</span> for the mean difference scores. We use the same formulas as we did last time:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">plot</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Before</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">After</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">differences</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff_from_mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Squared_differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">0.2</td>
<td style="text-align: left;">0.0400000000000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">26</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">3.2</td>
<td style="text-align: left;">10.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">-5.8</td>
<td style="text-align: left;">33.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">102</td>
<td style="text-align: left;">116</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">46.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">20.4</td>
<td style="text-align: left;">23.2</td>
<td style="text-align: left;">2.8</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">9.36</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">sd</td>
<td style="text-align: left;">3.421</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">SEM</td>
<td style="text-align: left;">1.53</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">t</td>
<td style="text-align: left;">1.83006535947712</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>If we did this test using R, we would obtain almost the same numbers (there is a little bit of rounding in the table).</p>
<div class="cell">
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  differences
#&gt; t = 1.8304, df = 4, p-value = 0.1412
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -1.447144  7.047144
#&gt; sample estimates:
#&gt; mean of x 
#&gt;       2.8</code></pre>
</div>
<p>Here is a quick write up of our t-test results, t(4) = 1.87, p = .135.</p>
<p>What does all of that tell us? There’s a few things we haven’t gotten into much yet. For example, the 4 represents degrees of freedom, which we discuss later. The important part, the <span class="math inline">\(t\)</span> value should start to be a little bit more meaningful. We got a modest t-value of 1.87. What can we tell from this value? First, it is positive, so we know the mean difference is positive — soil moisture increased after restoration on average. The sign of the <span class="math inline">\(t\)</span>-value is always the same as the sign of the mean difference (ours was +2.8 percentage points). We can also see that the p-value was .135. We’ve seen p-values before. This tells us our <span class="math inline">\(t\)</span> value or larger would occur about 13.5% of the time by chance alone… Actually it means more than this. And, to understand it, we need to talk about the concept of two-tailed and one-tailed tests.</p>
</section>
<section id="interpreting-ts" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="interpreting-ts"><span class="header-section-number">7.4.2</span> Interpreting <span class="math inline">\(t\)</span>s</h3>
<p>Remember what it is we are doing here. We are evaluating whether our sample data could have come from a particular kind of distribution. The null distribution of no differences. This is the distribution of <span class="math inline">\(t\)</span>-values that would occur for samples of size 5, with a mean difference of 0, and a standard error of the sample mean of .075 (this is the SEM that we calculated from our sample). We can see what this particular null-distribution looks like in <a href="#fig-7tnull">Figure&nbsp;<span>7.4</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7tnull" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7tnull-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.4: A distribution of <span class="math inline">\(t\)</span>-values that can occur by chance alone, when there is no difference between the sample and a population</figcaption>
</figure>
</div>
</div>
</div>
<p>The <span class="math inline">\(t\)</span>-distribution above shows us the kinds of values <span class="math inline">\(t\)</span> will will take by chance alone, when we measure the mean differences for pairs of 5 samples (like our current). <span class="math inline">\(t\)</span> is most likely to be zero, which is good, because we are looking at the distribution of no-differences, which should most often be 0! But, sometimes, due to sampling error, we can get <span class="math inline">\(t\)</span>s that are bigger than 0, either in the positive or negative direction. Notice the distribution is symmetrical, a <span class="math inline">\(t\)</span> from the null-distribution will be positive half of the time, and negative half of the time, that is what we would expect by chance.</p>
<p>So, what kind of information do we want know when we find a particular <span class="math inline">\(t\)</span> value from our sample? We want to know how likely the <span class="math inline">\(t\)</span> value like the one we found occurs just by chance. This is actually a subtly nuanced kind of question. For example, any particular <span class="math inline">\(t\)</span> value doesn’t have a specific probability of occurring. When we talk about probabilities, we are talking about ranges of probabilities. Let’s consider some probabilities. We will use the letter <span class="math inline">\(p\)</span>, to talk about the probabilities of particular <span class="math inline">\(t\)</span> values.</p>
<ol type="1">
<li><p>What is the probability that <span class="math inline">\(t\)</span> is zero or positive or negative? The answer is p=1, or 100%. We will always have a <span class="math inline">\(t\)</span> value that is zero or non-zero…Actually, if we can’t compute the t-value, for example when the standard deviation is undefined, I guess then we would have a non-number. But, assuming we can calculate <span class="math inline">\(t\)</span>, then it will always be 0 or positive or negative.</p></li>
<li><p>What is the probability of <span class="math inline">\(t\)</span> = 0 or greater than 0? The answer is p=.5, or 50%. 50% of <span class="math inline">\(t\)</span>-values are 0 or greater.</p></li>
<li><p>What is the of <span class="math inline">\(t\)</span> = 0 or smaller than 0? The answer is p=.5, or 50%. 50% of <span class="math inline">\(t\)</span>-values are 0 or smaller.</p></li>
</ol>
<p>We can answer all of those questions just by looking at our t-distribution, and dividing it into two equal regions, the left side (containing 50% of the <span class="math inline">\(t\)</span> values), and the right side containing 50% of the <span class="math inline">\(t\)</span>-values).</p>
<p>What if we wanted to take a more fine-grained approach, let’s say we were interested in regions of 10%. What kinds of <span class="math inline">\(t\)</span>s occur 10% of the time. We would apply lines like the following. Notice, the likelihood of bigger numbers (positive or negative) gets smaller, so we have to increase the width of the bars for each of the intervals between the bars to contain 10% of the <span class="math inline">\(t\)</span>-values, it looks like <a href="#fig-7percentregions">Figure&nbsp;<span>7.5</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7percentregions" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7percentregions-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.5: Splitting the t distribution up into regions each containing 10% of the <span class="math inline">\(t\)</span>-values. The width between the bars narrows as they approach the center of the distribution, where there are more <span class="math inline">\(t\)</span>-values.</figcaption>
</figure>
</div>
</div>
</div>
<p>Consider the probabilities (<span class="math inline">\(p\)</span>) of <span class="math inline">\(t\)</span> for the different ranges.</p>
<ol type="1">
<li><span class="math inline">\(t\)</span> &lt;= -1.5 (<span class="math inline">\(t\)</span> is less than or equal to -1.5), <span class="math inline">\(p\)</span> = 10%</li>
<li>-1.5 &gt;= <span class="math inline">\(t\)</span> &lt;= -0.9 (<span class="math inline">\(t\)</span> is equal to or between -1.5 and -.9), <span class="math inline">\(p\)</span> = 10%</li>
<li>-.9 &gt;= <span class="math inline">\(t\)</span> &lt;= -0.6 (<span class="math inline">\(t\)</span> is equal to or between -.9 and -.6), <span class="math inline">\(p\)</span> = 10%</li>
<li><span class="math inline">\(t\)</span> &gt;= 1.5 (<span class="math inline">\(t\)</span> is greater than or equal to 1.5), <span class="math inline">\(p\)</span> = 10%</li>
</ol>
<p>Notice, that the <span class="math inline">\(p\)</span>s are always 10%. <span class="math inline">\(t\)</span>s occur in these ranges with 10% probability.</p>
</section>
<section id="getting-the-p-values-for-t-values" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="getting-the-p-values-for-t-values"><span class="header-section-number">7.4.3</span> Getting the p-values for <span class="math inline">\(t\)</span>-values</h3>
<p>You might be wondering where I am getting some of these values from. For example, how do I know that 10% of <span class="math inline">\(t\)</span> values (for this null distribution) have a value of approximately 1.5 or greater than 1.5? The answer is I used R to tell me.</p>
<p>In most statistics textbooks the answer would be: there is a table at the back of the book where you can look these things up…This textbook has no such table. We could make one for you. And, we might do that. But, we didn’t do that yet…</p>
<p>So, where do these values come from, how can you figure out what they are? The complicated answer is that we are not going to explain the math behind finding these values because, 1) the authors (some of us) admittedly don’t know the math well enough to explain it, and 2) it would sidetrack us to much, 3) you will learn how to get these numbers in the lab with software, 4) you will learn how to get these numbers in lab without the math, just by doing a simulation, and 5) you can do it in R, or excel, or you can use an <a href="http://www.socscistatistics.com/pvalues/tdistribution.aspx">online calculator</a>.</p>
<p>This is all to say that you can find the <span class="math inline">\(t\)</span>s and their associated <span class="math inline">\(p\)</span>s using software. But, the software won’t tell you what these values mean. That’s we are doing here. You will also see that software wants to know a few more things from you, such as the degrees of freedom for the test, and whether the test is one-tailed or two tailed. We haven’t explained any of these things yet. That’s what we are going to do now. Note, we explain degrees of freedom last. First, we start with a one-tailed test.</p>
</section>
<section id="one-tailed-tests" class="level3" data-number="7.4.4">
<h3 data-number="7.4.4" class="anchored" data-anchor-id="one-tailed-tests"><span class="header-section-number">7.4.4</span> One-tailed tests</h3>
<p>A <strong>one-tailed test</strong> is sometimes also called a directional test. It is called a directional test, because a researcher might have a hypothesis in mind suggesting that the difference they observe in their means is going to have a particular direction, either a positive difference, or a negative difference.</p>
<p>Typically, a researcher would set an <strong>alpha criterion</strong>. The alpha criterion describes a line in the sand for the researcher. Often, the alpha criterion is set at <span class="math inline">\(p = .05\)</span>. What does this mean? <a href="#fig-7critT">Figure&nbsp;<span>7.6</span></a> shows the <span class="math inline">\(t\)</span>-distribution and the alpha criterion.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7critT" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7critT-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.6: The critical value of t for an alpha criterion of 0.05. 5% of all ts are at this value or larger</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure shows that <span class="math inline">\(t\)</span> values of +2.13 or greater occur 5% of the time. Because the t-distribution is symmetrical, we also know that <span class="math inline">\(t\)</span> values of -2.13 or smaller also occur 5% of the time. Both of these properties are true under the null distribution of no differences. This means, that when there really are no differences, a researcher can expect to find <span class="math inline">\(t\)</span> values of 2.13 or larger 5% of the time.</p>
<p>Let’s review and connect some of the terms:</p>
<ol type="1">
<li><p><strong>alpha criterion</strong>: the criterion set by the researcher to make decisions about whether they believe chance did or did not cause the difference. The alpha criterion here is set to <span class="math inline">\(p = .05\)</span>.</p></li>
<li><p><strong>Critical</strong> <span class="math inline">\(t\)</span>. The critical <span class="math inline">\(t\)</span> is the <span class="math inline">\(t\)</span>-value associated with the alpha-criterion. In this case for a one-tailed test, it is the <span class="math inline">\(t\)</span> value where 5% of all <span class="math inline">\(t\)</span>s are this number or greater. In our example, the critical <span class="math inline">\(t\)</span> is 2.13. 5% of all <span class="math inline">\(t\)</span> values (with degrees of freedom = 4) are +2.13, or greater than +2.13.</p></li>
<li><p><strong>Observed</strong> <span class="math inline">\(t\)</span>. The observed <span class="math inline">\(t\)</span> is the one that you calculated from your sample. In our restoration example with 5 plots, the observed <span class="math inline">\(t\)</span> was <span class="math inline">\(t\)</span>(4) = 1.87.</p></li>
<li><p><strong>p-value</strong>. The <span class="math inline">\(p\)</span>-value is the probability of obtaining the observed <span class="math inline">\(t\)</span> value or larger. Now, you could look back at our previous example, and find that the <span class="math inline">\(p\)</span>-value for <span class="math inline">\(t\)</span>(4) = 1.87, was <span class="math inline">\(p = .135\)</span>. HOWEVER, this p-value was not calculated for a one-directional test…(we talk about what .135 means in the next section).</p></li>
</ol>
<p><a href="#fig-7tonedirection">Figure&nbsp;<span>7.7</span></a> shows what the <span class="math inline">\(p\)</span>-value for <span class="math inline">\(t\)</span> (4) = .72 using a one-directional test would would look like:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7tonedirection" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7tonedirection-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.7: A case where the observed value of t is much less than the critical value for a one-directional t-test.</figcaption>
</figure>
</div>
</div>
</div>
<p>Let’s take this one step at a time. We have located the observed <span class="math inline">\(t\)</span> of .72 on the graph. We shaded the right region all grey. What we see is that the grey region represents .256 or 25.6% of all <span class="math inline">\(t\)</span> values. In other words, 25.6% of <span class="math inline">\(t\)</span> values are .72 or larger than .72. You could expect, by chance alone, to a find a <span class="math inline">\(t\)</span> value of .72 or larger, 25.6% of the time. That’s fairly often. We did find a <span class="math inline">\(t\)</span> value of .72. Now that you know this kind of <span class="math inline">\(t\)</span> value or larger occurs 25.6% of the time, would you be confident that the mean difference was not due to chance? Probably not, given that chance can produce this difference fairly often.</p>
<p>Following the “standard” decision making procedure, we would claim that our <span class="math inline">\(t\)</span> value was <strong>not statistically significant</strong>, because it was not large enough. If our observed value was larger than the critical <span class="math inline">\(t\)</span> (larger than 2.13), defined by our alpha criterion, then we would claim that our <span class="math inline">\(t\)</span> value was <strong>statistically significant</strong>. This would be equivalent to saying that we believe it is unlikely that the difference we observed was due to chance. In general, for any observed <span class="math inline">\(t\)</span> value, the associated <span class="math inline">\(p\)</span>-value tells you how likely a <span class="math inline">\(t\)</span> of the observed size or larger would be observed. The <span class="math inline">\(p\)</span>-value <strong>always</strong> refers to a <strong>range</strong> of <span class="math inline">\(t\)</span>-values, never to a single <span class="math inline">\(t\)</span>-value. Researchers use the alpha criterion of .05, as a matter of convenience and convention. There are other ways to interpret these values that do not rely on a strict (significant versus not) dichotomy.</p>
</section>
<section id="two-tailed-tests" class="level3" data-number="7.4.5">
<h3 data-number="7.4.5" class="anchored" data-anchor-id="two-tailed-tests"><span class="header-section-number">7.4.5</span> Two-tailed tests</h3>
<p>OK, so that was one-tailed tests… What are two tailed tests? The <span class="math inline">\(p\)</span>-value that we originally calculated from our paired-samples <span class="math inline">\(t\)</span>-test was for a 2-tailed test. Often, the default is that the <span class="math inline">\(p\)</span>-value is for a two-tailed test.</p>
<p>The two-tailed test, is asking a more general question about whether a difference is likely to have been produced by chance. The question is: what is probability of any difference. It is also called a <strong>non-directional</strong> test, because here we don’t care about the direction or sign of the difference (positive or negative), we just care if there is any kind of difference.</p>
<p>The same basic things as before are involved. We define an alpha criterion (<span class="math inline">\(\alpha = 0.05\)</span>). And, we say that any observed <span class="math inline">\(t\)</span> value that has a probability of <span class="math inline">\(p\)</span> &lt;.05 (<span class="math inline">\(p\)</span> is less than .05) will be called <strong>statistically significant</strong>, and ones that are more likely (<span class="math inline">\(p\)</span> &gt;.05, <span class="math inline">\(p\)</span> is greater than .05) will be called null-results, or not statistically significant. The only difference is how we draw the alpha range. Before it was on the right side of the <span class="math inline">\(t\)</span> distribution (we were conducting a one-sided test remember, so we were only interested in one side).</p>
<p><a href="#fig-7twotailedt">Figure&nbsp;<span>7.8</span></a> shows what the most extreme 5% of the <span class="math inline">\(t\)</span>-values are when we ignore their sign (whether they are positive or negative).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7twotailedt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7twotailedt-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.8: Critical values for a two-tailed test. Each line represents the location where 2.5% of all <span class="math inline">\(t\)</span>s are larger or smaller than critical value. The total for both tails is 5%</figcaption>
</figure>
</div>
</div>
</div>
<p>Here is what we are seeing. A distribution of no differences (the null, which is what we are looking at), will produce <span class="math inline">\(t\)</span>s that are 2.78 or greater 2.5% of the time, and <span class="math inline">\(t\)</span>s that are -2.78 or smaller 2.5% of the time. 2.5% + 2.5% is a total of 5% of the time. We could also say that <span class="math inline">\(t\)</span>s larger than +/- 2.78 occur 5% of the time.</p>
<p>As a result, the critical <span class="math inline">\(t\)</span> value is (+/-) 2.78 for a two-tailed test. As you can see, the two-tailed test is blind to the direction or sign of the difference. Because of this, the critical <span class="math inline">\(t\)</span> value is also higher for a two-tailed test, than for the one-tailed test that we did earlier. Hopefully, now you can see why it is called a two-tailed test. There are two tails of the distribution, one on the left and right, both shaded in green.</p>
</section>
<section id="one-or-two-tailed-which-one" class="level3" data-number="7.4.6">
<h3 data-number="7.4.6" class="anchored" data-anchor-id="one-or-two-tailed-which-one"><span class="header-section-number">7.4.6</span> One or two tailed, which one?</h3>
<p>Now that you know there are two kinds of tests, one-tailed, and two-tailed, which one should you use? There is some conventional wisdom on this, but also some debate. In the end, it is up to you to be able to justify your choice and why it is appropriate for you data. That is the real answer.</p>
<p>The conventional answer is that you use a one-tailed test when you have a theory or hypothesis that is making a directional prediction (the theory predicts that the difference will be positive, or negative). Similarly, use a two-tailed test when you are looking for any difference, and you don’t have a theory that makes a directional prediction (it just makes the prediction that there will be a difference, either positive or negative).</p>
<p>Also, people appear to choose one or two-tailed tests based on how risky they are as researchers. If you always ran one-tailed tests, your critical <span class="math inline">\(t\)</span> values for your set alpha criterion would always be smaller than the critical <span class="math inline">\(t\)</span>s for a two-tailed test. Over the long run, you would make more type I errors, because the criterion to detect an effect is a lower bar for one than two tailed tests.</p>
<blockquote class="blockquote">
<p>Remember type 1 errors occur when you reject the idea that chance could have caused your difference. You often never know when you make this error. It happens anytime that sampling error was the actual cause of the difference, but a researcher dismisses that possibility and concludes that their manipulation caused the difference.</p>
</blockquote>
<p>Similarly, if you always ran two-tailed tests, even when you had a directional prediction, you would make fewer type I errors over the long run, because the <span class="math inline">\(t\)</span> for a two-tailed test is higher than the <span class="math inline">\(t\)</span> for a one-tailed test. It seems quite common for researchers to use a more conservative two-tailed test, even when they are making a directional prediction based on theory. In practice, researchers tend to adopt a standard for reporting that is common in their field. Whether or not the practice is justifiable can sometimes be an open question. The important task for any researcher, or student learning statistics, is to be able to justify their choice of test.</p>
</section>
<section id="degrees-of-freedom" class="level3" data-number="7.4.7">
<h3 data-number="7.4.7" class="anchored" data-anchor-id="degrees-of-freedom"><span class="header-section-number">7.4.7</span> Degrees of freedom</h3>
<p>Before we finish up with paired-samples <span class="math inline">\(t\)</span>-tests, we should talk about degrees of freedom. Our sense is that students don’t really understand degrees of freedom very well. If you are reading this textbook, you are probably still wondering what is degrees of freedom, seeing as we haven’t really talked about it all.</p>
<p>For the <span class="math inline">\(t\)</span>-test, there is a formula for degrees of freedom. For the one-sample and paired sample <span class="math inline">\(t\)</span>-tests, the formula is:</p>
<p><span class="math inline">\(\text{Degrees of Freedom} = \text{df} = n-1\)</span>. Where n is the number of samples in the test.</p>
<p>In our paired <span class="math inline">\(t\)</span>-test example, there were 5 restoration plots. Therefore, degrees of freedom = 5-1 = 4.</p>
<p>OK, that’s a formula. Who cares about degrees of freedom, what does the number mean? And why do we report it when we report a <span class="math inline">\(t\)</span>-test… you’ve probably noticed the number in parentheses e.g., <span class="math inline">\(t\)</span>(4)=.72, the 4 is the <span class="math inline">\(df\)</span>, or degrees of freedom.</p>
<p>Degrees of freedom is both a concept, and a correction. The concept is that if you estimate a property of the numbers, and you use this estimate, you will be forcing some constraints on your numbers.</p>
<p>Consider the numbers: 1, 2, 3. The mean of these numbers is 2. Now, let’s say I told you that the mean of three numbers is 2. Then, how many of these three numbers have freedom? Funny question right. What we mean is, how many of the three numbers could be any number, or have the freedom to be any number.</p>
<p>The first two numbers could be any number. But, once those two numbers are set, the final number (the third number), MUST be a particular number that makes the mean 2. The first two numbers have freedom. The third number has no freedom.</p>
<p>To illustrate. Let’s freely pick two numbers: 51 and -3. I used my personal freedom to pick those two numbers. Now, if our three numbers are 51, -3, and x, and the mean of these three numbers is 2. There is only one solution, x has to be -42, otherwise the mean won’t be 2. This is one way to think about degrees of freedom. The degrees of freedom for these three numbers is n-1 = 3-1= 2, because 2 of the numbers can be free, but the last number has no freedom, it becomes fixed after the first two are decided.</p>
<p>Now, statisticians often apply degrees of freedom to their calculations, especially when a second calculation relies on an estimated value. For example, when we calculate the standard deviation of a sample, we first calculate the mean of the sample right! By estimating the mean, we are fixing an aspect of our sample, and so, our sample now has n-1 degrees of freedom when we calculate the standard deviation (remember for the sample standard deviation, we divide by n-1…there’s that n-1 again.)</p>
<section id="simulating-how-degrees-of-freedom-affects-the-t-distribution" class="level4" data-number="7.4.7.1">
<h4 data-number="7.4.7.1" class="anchored" data-anchor-id="simulating-how-degrees-of-freedom-affects-the-t-distribution"><span class="header-section-number">7.4.7.1</span> Simulating how degrees of freedom affects the <span class="math inline">\(t\)</span> distribution</h4>
<p>There are at least two ways to think the degrees of freedom for a <span class="math inline">\(t\)</span>-test. For example, if you want to use math to compute aspects of the <span class="math inline">\(t\)</span> distribution, then you need the degrees of freedom to plug in to the formula… If you want to see the formulas I’m talking about, scroll down on the <a href="https://en.wikipedia.org/wiki/Student%27s_t-distribution"><span class="math inline">\(t\)</span>-test wikipedia page</a> and look for the probability density or cumulative distribution functions…We think that is quite scary for most people, and one reason why degrees of freedom are not well-understood.</p>
<p>If we wanted to simulate the <span class="math inline">\(t\)</span> distribution we could more easily see what influence degrees of freedom has on the shape of the distribution. Remember, <span class="math inline">\(t\)</span> is a sample statistic, it is something we measure from the sample. So, we could simulate the process of measuring <span class="math inline">\(t\)</span> from many different samples, then plot the histogram of <span class="math inline">\(t\)</span> to show us the simulated <span class="math inline">\(t\)</span> distribution.</p>
<div class="cell" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-7dft" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7dft-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.9: The width of the t distribution shrinks as sample size and degrees of freedom (from 4 to 100) increases.</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-7dft">Figure&nbsp;<span>7.9</span></a> notice that the red distribution for <span class="math inline">\(df = 4\)</span>, is a little bit shorter, and a little bit wider than the bluey-green distribution for <span class="math inline">\(df = 100\)</span>. As degrees of freedom increase the <span class="math inline">\(t\)</span> distribution gets taller (in the middle), and narrower in the range. It get’s more peaky. Can you guess the reason for this? Remember, we are estimating a sample statistic, and degrees of freedom is really just a number that refers to the number of subjects (well minus one). And, we already know that as we increase <span class="math inline">\(n\)</span>, our sample statistics become better estimates (less variance) of the distributional parameters they are estimating. So, <span class="math inline">\(t\)</span> becomes a better estimate of it’s “true” value as sample size increase, resulting in a more narrow distribution of <span class="math inline">\(t\)</span>s.</p>
<p>There is a slightly different <span class="math inline">\(t\)</span> distribution for every degrees of freedom, and the critical regions associated with 5% of the extreme values are thus slightly different every time. This is why we report the degrees of freedom for each t-test, they define the distribution of <span class="math inline">\(t\)</span> values for the sample-size in question. Why do we use n-1 and not n? Well, we calculate <span class="math inline">\(t\)</span> using the sample standard deviation to estimate the standard error or the mean, that estimate uses n-1 in the denominator, so our <span class="math inline">\(t\)</span> distribution is built assuming n-1. That’s enough for degrees of freedom…</p>
</section>
</section>
</section>
<section id="the-paired-samples-t-test-strikes-back" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="the-paired-samples-t-test-strikes-back"><span class="header-section-number">7.5</span> The paired samples t-test strikes back</h2>
<p>Don’t worry, we’re not starting over — we’re just going to 1) remind you of the soil moisture restoration example, and 2) run the paired t-test on the full dataset of 20 plots and discuss what changes.</p>
<p>Remember, we were asking whether soil moisture (%) increased after wetland restoration. We showed you data from 5 plots and walked through the computations for the <span class="math inline">\(t\)</span>-test. As a reminder, it looked like this:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">plot</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Before</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">After</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">differences</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff_from_mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Squared_differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">0.2</td>
<td style="text-align: left;">0.0400000000000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">26</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">3.2</td>
<td style="text-align: left;">10.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">-5.8</td>
<td style="text-align: left;">33.64</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">102</td>
<td style="text-align: left;">116</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">46.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">20.4</td>
<td style="text-align: left;">23.2</td>
<td style="text-align: left;">2.8</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">9.36</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">sd</td>
<td style="text-align: left;">3.421</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">SEM</td>
<td style="text-align: left;">1.53</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">t</td>
<td style="text-align: left;">1.83006535947712</td>
</tr>
</tbody>
</table>


</div>
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  differences
#&gt; t = 1.8304, df = 4, p-value = 0.1412
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -1.447144  7.047144
#&gt; sample estimates:
#&gt; mean of x 
#&gt;       2.8</code></pre>
</div>
<p>Let’s write down the finding one more time: The mean difference was 2.8 percentage points, <span class="math inline">\(t\)</span>(4) = 1.87, <span class="math inline">\(p\)</span> = .135. We can also now confirm that the <span class="math inline">\(p\)</span>-value was from a two-tailed test. So, what does this all really mean?</p>
<p>We can say that a <span class="math inline">\(t\)</span> value with an absolute value of 1.87 or larger occurs 13.5% of the time by chance alone. More precisely, the null distribution of no differences will produce a <span class="math inline">\(t\)</span> value this large or larger 13.5% of the time. In other words, our five-plot sample is too small to rule out chance as an explanation for the observed increase.</p>
<p>Let’s now run the test using all 20 plots.</p>
<div class="cell">
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  differences_full
#&gt; t = 3.3943, df = 19, p-value = 0.003044
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  1.629317 6.870683
#&gt; sample estimates:
#&gt; mean of x 
#&gt;      4.25</code></pre>
</div>
<p>Now we get a very different answer. The degrees of freedom is 19, confirming <span class="math inline">\(n = 20\)</span> plots. We see a much smaller <span class="math inline">\(p\)</span>-value. This is also a two-tailed test. In other words, the null distribution of no differences will produce the observed <span class="math inline">\(t\)</span>-value very rarely. So, it is unlikely that the observed mean increase in soil moisture was due to chance alone. As a result, we can be reasonably confident that wetland restoration increased soil moisture at these sites — consistent with the ecological goal of restoring hydrological function.</p>
</section>
<section id="two-independent-groups" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="two-independent-groups"><span class="header-section-number">7.6</span> Two independent groups</h2>
<p>If you’ve been following the Star Wars references, we are on last movie (of the original trilogy)… the independent t-test. This is were basically the same story plays out as before, only slightly different.</p>
<p>Remember there are different <span class="math inline">\(t\)</span>-tests for different kinds of research designs. When your design is a <strong>between-subjects</strong> design, you use an <strong>independent samples t-test</strong>. Between-subjects design involve different people or subjects in each experimental condition. If there are two conditions, and 10 people in each, then there are 20 total people. And, there are no paired scores, because every single person is measured once, not twice, no repeated measures. Because there are no repeated measures we can’t look at the difference scores between conditions one and two. The scores are not paired in any meaningful way, to it doesn’t make sense to subtract them. So what do we do?</p>
<p>The logic of the independent samples t-test is the very same as the other <span class="math inline">\(t\)</span>-tests. We calculated the means for each group, then we find the difference. That goes into the numerator of the t formula. Then we get an estimate of the variation for the denominator. We divide the mean difference by the estimate of the variation, and we get <span class="math inline">\(t\)</span>. It’s the same as before.</p>
<p>The only wrinkle here is what goes into the denominator? How should we calculate the estimate of the variance? It would be nice if we could do something very straightforward like this, say for an experiment with two groups A and B:</p>
<p><span class="math inline">\(t = \frac{\bar{A}-\bar{B}}{(\frac{SEM_A+SEM_B}{2})}\)</span></p>
<p>In plain language, this is just:</p>
<ol type="1">
<li>Find the mean difference for the top part</li>
<li>Compute the SEM (standard error of the mean) for each group, and average them together to make a single estimate, pooling over both samples.</li>
</ol>
<p>This would be nice, but unfortunately, it turns out that finding the average of two standard errors of the mean is not the best way to do it. This would create a biased estimator of the variation for the hypothesized distribution of no differences. We won’t go into the math here, but instead of the above formula, we an use a different one that gives as an <strong>unbiased estimate of the pooled standard error of the sample mean</strong>. Our new and improved <span class="math inline">\(t\)</span> formula would look like this:</p>
<p><span class="math inline">\(t = \frac{\bar{X_A}-\bar{X_B}}{s_p * \sqrt{\frac{1}{n_A} + \frac{1}{n_B}}}\)</span></p>
<p>and, <span class="math inline">\(s_p\)</span>, which is the pooled sample standard deviation is defined as, note the $s$es in the formula are variances:</p>
<p><span class="math inline">\(s_p = \sqrt{\frac{(n_A-1)s_A^2 + (n_B-1)s^2_B}{n_A +n_B -2}}\)</span></p>
<p>Believe you me, that is so much more formula than I wanted to type out. Shall we do one independent <span class="math inline">\(t\)</span>-test example by hand, just to see the computations? Let’s do it…but in a slightly different way than you expect. I show the steps using R. I made some fake scores for groups A and B. Then, I followed all of the steps from the formula, but made R do each of the calculations. This shows you the needed steps by following the code. At the end, I print the <span class="math inline">\(t\)</span>-test values I computed “by hand”, and then the <span class="math inline">\(t\)</span>-test value that the R software outputs using the <span class="math inline">\(t\)</span>-test function. You should be able to get the same values for <span class="math inline">\(t\)</span>, if you were brave enough to compute <span class="math inline">\(t\)</span> by hand.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">## By "hand" using R r code</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">9</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>mean_difference <span class="ot">&lt;-</span> <span class="fu">mean</span>(a)<span class="sc">-</span><span class="fu">mean</span>(b) <span class="co"># compute mean difference</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>variance_a <span class="ot">&lt;-</span> <span class="fu">var</span>(a) <span class="co"># compute variance for A</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>variance_b <span class="ot">&lt;-</span> <span class="fu">var</span>(b) <span class="co"># compute variance for B</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute top part and bottom part of sp formula</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>sp_numerator <span class="ot">&lt;-</span> (<span class="dv">4</span><span class="sc">*</span>variance_a <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span> variance_b) </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>sp_denominator <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">+</span><span class="dv">5-2</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sp_numerator<span class="sc">/</span>sp_denominator) <span class="co"># compute sp</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># compute t following formulat</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> mean_difference <span class="sc">/</span> ( sp <span class="sc">*</span> <span class="fu">sqrt</span>( (<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>) <span class="sc">+</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>) ) )</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>t <span class="co"># print results</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -2.017991</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co"># using the R function t.test</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a,b, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Two Sample t-test</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; data:  a and b</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t = -2.018, df = 8, p-value = 0.0783</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; alternative hypothesis: true difference in means is not equal to 0</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  -5.5710785  0.3710785</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample estimates:</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; mean of x mean of y </span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       3.0       5.6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulating-data-for-t-tests" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="simulating-data-for-t-tests"><span class="header-section-number">7.7</span> Simulating data for t-tests</h2>
<p>An “advanced” topic for <span class="math inline">\(t\)</span>-tests is the idea of using R to conduct simulations for <span class="math inline">\(t\)</span>-tests.</p>
<p>If you recall, <span class="math inline">\(t\)</span> is a property of a sample. We calculate <span class="math inline">\(t\)</span> from our sample. The <span class="math inline">\(t\)</span> distribution is the hypothetical behavior of our sample. That is, if we had taken thousands upon thousands of samples, and calculated <span class="math inline">\(t\)</span> for each one, and then looked at the distribution of those <span class="math inline">\(t\)</span>’s, we would have the sampling distribution of <span class="math inline">\(t\)</span>!</p>
<p>It can be very useful to get in the habit of using R to simulate data under certain conditions, to see how your sample data, and things like <span class="math inline">\(t\)</span> behave. Why is this useful? It mainly prepares you with some intuitions about how sampling error (random chance) can influence your results, given specific parameters of your design, such as sample-size, the size of the mean difference you expect to find in your data, and the amount of variation you might find. These methods can be used formally to conduct power-analyses. Or more informally for data sense.</p>
<section id="simulating-a-one-sample-t-test" class="level3" data-number="7.7.1">
<h3 data-number="7.7.1" class="anchored" data-anchor-id="simulating-a-one-sample-t-test"><span class="header-section-number">7.7.1</span> Simulating a one-sample t-test</h3>
<p>Here are the steps you might follow to simulate data for a one sample <span class="math inline">\(t\)</span>-test.</p>
<ol type="1">
<li><p>Make some assumptions about what your sample (that you might be planning to collect) might look like. For example, you might be planning to collect 30 subjects worth of data. The scores of those data points might come from a normal distribution (mean = 50, sd = 10).</p></li>
<li><p>sample simulated numbers from the distribution, then conduct a <span class="math inline">\(t\)</span>-test on the simulated numbers. Save the statistics you want (such as <span class="math inline">\(t\)</span>s and <span class="math inline">\(p\)</span>s), and then see how things behave.</p></li>
</ol>
<p>Let’s do this a couple different times. First, let’s simulate samples with N = 30, taken from a normal (mean= 50, sd = 25). We’ll do a simulation with 1000 simulations. For each simulation, we will compare the sample mean with a population mean of 50. There should be no difference on average here. <a href="#fig-7nullt">Figure&nbsp;<span>7.10</span></a> is the null distribution that we are simulating.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7nullt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7nullt-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.10: The distribution of <span class="math inline">\(t\)</span>-values under the null. These are the <span class="math inline">\(t\)</span> values that are produced by chance alone.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7flatp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7flatp-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.11: The distribution of <span class="math inline">\(p\)</span>-values that are observed is flat under the null.</figcaption>
</figure>
</div>
</div>
</div>
<p>Neat. We see both a <span class="math inline">\(t\)</span> distribution, that looks like <span class="math inline">\(t\)</span> distribution as it should. And we see the <span class="math inline">\(p\)</span> distribution. This shows us how often we get <span class="math inline">\(t\)</span> values of particular sizes. You may find it interesting that the <span class="math inline">\(p\)</span>-distribution is flat under the null, which we are simulating here. This means that you have the same chances of a getting a <span class="math inline">\(t\)</span> with a p-value between 0 and 0.05, as you would for getting a <span class="math inline">\(t\)</span> with a p-value between .90 and .95. Those ranges are both ranges of 5%, so there are an equal amount of <span class="math inline">\(t\)</span> values in them by definition.</p>
<p>Here’s another way to do the same simulation in R, using the replicate function, instead a for loop:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simtsRep" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simtsRep-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.12: Simulating <span class="math inline">\(t\)</span>s in R.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simpsRep" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simpsRep-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.13: Simulating <span class="math inline">\(p\)</span>s in R.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="simulating-a-paired-samples-t-test" class="level3" data-number="7.7.2">
<h3 data-number="7.7.2" class="anchored" data-anchor-id="simulating-a-paired-samples-t-test"><span class="header-section-number">7.7.2</span> Simulating a paired samples t-test</h3>
<p>The code below is set up to sample 10 scores for condition A and B from the same normal distribution. The simulation is conducted 1000 times, and the <span class="math inline">\(t\)</span>s and <span class="math inline">\(p\)</span>s are saved and plotted for each.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simps1000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simps1000-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.14: 1000 simulated ts from the null distribution</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simts1000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simts1000-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.15: 1000 simulated ps from the null distribution</figcaption>
</figure>
</div>
</div>
</div>
<p>According to the simulation. When there are no differences between the conditions, and the samples are being pulled from the very same distribution, you get these two distributions for <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span>. These again show how the null distribution of no differences behaves.</p>
<p>For any of these simulations, if you rejected the null-hypothesis (that your difference was only due to chance), you would be making a type I error. If you set your alpha criteria to <span class="math inline">\(\alpha = .05\)</span>, we can ask how many type I errors were made in these 1000 simulations. The answer is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 48</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.048</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We happened to make 48. The expectation over the long run is 5% type I error rates (if your alpha is .05).</p>
<p>What happens if there actually is a difference in the simulated data, let’s set one condition to have a larger mean than the other:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">13</span>,<span class="dv">5</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simtruets" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simtruets-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.16: 1000 ts when there is a true difference</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simtrueps" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simtrueps-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.17: 1000 ps when there is a true difference</figcaption>
</figure>
</div>
</div>
</div>
<p>Now you can see that the <span class="math inline">\(p\)</span>-value distribution is skewed to the left. This is because when there is a true effect, you will get p-values that are less than .05 more often. Or, rather, you get larger <span class="math inline">\(t\)</span> values than you normally would if there were no differences.</p>
<p>In this case, we wouldn’t be making a type I error if we rejected the null when p was smaller than .05. How many times would we do that out of our 1000 experiments?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 244</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.244</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We happened to get 244 simulations where p was less than .05, that’s only 0.244 experiments. If you were the researcher, would you want to run an experiment that would be successful only 0.244 of the time? I wouldn’t. I would run a better experiment.</p>
<p>How would you run a better simulated experiment? Well, you could increase <span class="math inline">\(n\)</span>, the number of subjects in the experiment. Let’s increase <span class="math inline">\(n\)</span> from 10 to 100, and see what happens to the number of “significant” simulated experiments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>,<span class="dv">13</span>,<span class="dv">5</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simtsB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simtsB-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.18: 1000 ts for n =100, when there is a true effect</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<pre><code>#&gt; [1] 984
#&gt; [1] 0.984</code></pre>
<div class="cell-output-display">
<div id="fig-7simpsB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simpsB-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.19: 1000 ps for n =100, when there is a true effect</figcaption>
</figure>
</div>
</div>
</div>
<p>Cool, now almost all of the experiments show a <span class="math inline">\(p\)</span>-value of less than .05 (using a two-tailed test, that’s the default in R). See, you could use this simulation process to determine how many subjects you need to reliably find your effect.</p>
</section>
<section id="simulating-an-independent-samples-t.test" class="level3" data-number="7.7.3">
<h3 data-number="7.7.3" class="anchored" data-anchor-id="simulating-an-independent-samples-t.test"><span class="header-section-number">7.7.3</span> Simulating an independent samples t.test</h3>
<p>Just change the t.test function like so… this is for the null, assuming no difference between groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  group_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  group_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(group_A, group_B, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-7simtsC" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simtsC-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.20: 1000 ts for n =100, when there is a true effect</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<pre><code>#&gt; [1] 45
#&gt; [1] 0.045</code></pre>
<div class="cell-output-display">
<div id="fig-7simpsC" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="07-ttests_files/figure-html/fig-7simpsC-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.21: 1000 ps for n =100, when there is a true effect</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="videos" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="videos"><span class="header-section-number">7.8</span> Videos</h2>
<section id="one-or-two-tailed-tests" class="level3" data-number="7.8.1">
<h3 data-number="7.8.1" class="anchored" data-anchor-id="one-or-two-tailed-tests"><span class="header-section-number">7.8.1</span> One or Two tailed tests</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/PuoGsguuY30" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
<div id="ref-Student1908" class="csl-entry" role="listitem">
Student, A. 1908. <span>“The Probable Error of a Mean.”</span> <em>Biometrika</em> 6: 1–2.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-Hypothesis_Testing.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-ANOVA.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>