<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>Answering questions with data - 8&nbsp; ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-Regression.html" rel="next">
<link href="./07-Nonparametric.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 8&nbsp; ANOVA">
<meta property="og:description" content="">
<meta property="og:image" content="08-ANOVA_files/figure-html/fig-9multiplet-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 8&nbsp; ANOVA">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-ANOVA.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-MoreFactorialDesigns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#anova-is-analysis-of-variance" id="toc-anova-is-analysis-of-variance" class="nav-link active" data-scroll-target="#anova-is-analysis-of-variance"><span class="header-section-number">8.1</span> ANOVA is Analysis of Variance</a>
  <ul class="collapse">
  <li><a href="#why-not-just-run-multiple-t-tests" id="toc-why-not-just-run-multiple-t-tests" class="nav-link" data-scroll-target="#why-not-just-run-multiple-t-tests"><span class="header-section-number">8.1.1</span> Why not just run multiple t-tests?</a></li>
  </ul></li>
  <li><a href="#one-factor-anova" id="toc-one-factor-anova" class="nav-link" data-scroll-target="#one-factor-anova"><span class="header-section-number">8.2</span> One-factor ANOVA</a>
  <ul class="collapse">
  <li><a href="#computing-the-f-value" id="toc-computing-the-f-value" class="nav-link" data-scroll-target="#computing-the-f-value"><span class="header-section-number">8.2.1</span> Computing the <span class="math inline">\(F\)</span>-value</a></li>
  <li><a href="#ss-total" id="toc-ss-total" class="nav-link" data-scroll-target="#ss-total"><span class="header-section-number">8.2.2</span> SS Total</a></li>
  <li><a href="#ss-between" id="toc-ss-between" class="nav-link" data-scroll-target="#ss-between"><span class="header-section-number">8.2.3</span> SS Between</a></li>
  <li><a href="#ss-within" id="toc-ss-within" class="nav-link" data-scroll-target="#ss-within"><span class="header-section-number">8.2.4</span> SS Within</a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom"><span class="header-section-number">8.2.5</span> Degrees of freedom</a></li>
  <li><a href="#mean-squares" id="toc-mean-squares" class="nav-link" data-scroll-target="#mean-squares"><span class="header-section-number">8.2.6</span> Mean Squares</a></li>
  <li><a href="#calculate-f" id="toc-calculate-f" class="nav-link" data-scroll-target="#calculate-f"><span class="header-section-number">8.2.7</span> Calculate F</a></li>
  <li><a href="#the-anova-table" id="toc-the-anova-table" class="nav-link" data-scroll-target="#the-anova-table"><span class="header-section-number">8.2.8</span> The ANOVA table</a></li>
  </ul></li>
  <li><a href="#what-does-f-mean" id="toc-what-does-f-mean" class="nav-link" data-scroll-target="#what-does-f-mean"><span class="header-section-number">8.3</span> What does F mean?</a>
  <ul class="collapse">
  <li><a href="#making-decisions" id="toc-making-decisions" class="nav-link" data-scroll-target="#making-decisions"><span class="header-section-number">8.3.1</span> Making decisions</a></li>
  <li><a href="#f-and-the-means" id="toc-f-and-the-means" class="nav-link" data-scroll-target="#f-and-the-means"><span class="header-section-number">8.3.2</span> F and the means</a></li>
  </ul></li>
  <li><a href="#anova-on-real-data" id="toc-anova-on-real-data" class="nav-link" data-scroll-target="#anova-on-real-data"><span class="header-section-number">8.4</span> ANOVA on Real Data</a>
  <ul class="collapse">
  <li><a href="#salamander-abundance-across-forest-types" id="toc-salamander-abundance-across-forest-types" class="nav-link" data-scroll-target="#salamander-abundance-across-forest-types"><span class="header-section-number">8.4.1</span> Salamander abundance across forest types</a></li>
  <li><a href="#checking-anovas-assumptions" id="toc-checking-anovas-assumptions" class="nav-link" data-scroll-target="#checking-anovas-assumptions"><span class="header-section-number">8.4.2</span> Checking ANOVA’s assumptions</a></li>
  <li><a href="#post-hoc-comparisons-with-tukey-hsd" id="toc-post-hoc-comparisons-with-tukey-hsd" class="nav-link" data-scroll-target="#post-hoc-comparisons-with-tukey-hsd"><span class="header-section-number">8.4.3</span> Post-hoc comparisons with Tukey HSD</a></li>
  <li><a href="#nonparametric-alternative-the-kruskal-wallis-test" id="toc-nonparametric-alternative-the-kruskal-wallis-test" class="nav-link" data-scroll-target="#nonparametric-alternative-the-kruskal-wallis-test"><span class="header-section-number">8.4.4</span> Nonparametric alternative: the Kruskal-Wallis test</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">8.5</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/08-ANOVA.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 27, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>A fun bit of stats history <span class="citation" data-cites="salsburg2001lady">(<a href="#ref-salsburg2001lady" role="doc-biblioref">Salsburg 2001</a>)</span>. Sir Ronald Fisher invented the ANOVA, which we learn about in this section. He wanted to publish his new test in the journal Biometrika. The editor at the time was Karl Pearson (remember Pearson’s <span class="math inline">\(r\)</span> for correlation?). Pearson and Fisher were apparently not on good terms, they didn’t like each other. Pearson refused to publish Fisher’s new test. So, Fisher eventually published his work in the Journal of Agricultural Science. Funnily enough, the feud continued onto the next generation. Years after Fisher published his ANOVA, Karl Pearson’s son Egon Pearson, and Jersey Neyman revamped Fisher’s ideas, and re-cast them into what is commonly known as null vs.&nbsp;alternative hypothesis testing. Fisher didn’t like this very much.</p>
<p>We present the ANOVA in the Fisherian sense, and at the end describe the Neyman-Pearson approach that invokes the concept of null vs.&nbsp;alternative hypotheses.</p>
<section id="anova-is-analysis-of-variance" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="anova-is-analysis-of-variance"><span class="header-section-number">8.1</span> ANOVA is Analysis of Variance</h2>
<p>ANOVA stands for Analysis Of Variance. It tests whether differences among several group means are larger than we’d expect from chance alone.</p>
<p>With two groups, a <span class="math inline">\(t\)</span>-test already answers that question. ANOVA extends the same logic to <strong>three or more</strong> groups, which comes up constantly in environmental science: multiple sites, multiple treatments, multiple time periods.</p>
<section id="why-not-just-run-multiple-t-tests" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="why-not-just-run-multiple-t-tests"><span class="header-section-number">8.1.1</span> Why not just run multiple t-tests?</h3>
<p>Suppose we’re comparing three restoration treatments for vegetation cover: <strong>compost</strong>, <strong>mulch</strong>, and a bare-soil <strong>control</strong>. With three groups, there are three possible pairwise comparisons: compost vs.&nbsp;mulch, compost vs.&nbsp;control, and mulch vs.&nbsp;control.</p>
<p>We could run a separate <span class="math inline">\(t\)</span>-test for each. The problem is that every test carries its own 5% chance of a false positive, and those chances accumulate across tests. If we run <span class="math inline">\(m\)</span> independent tests at <span class="math inline">\(\alpha=.05\)</span>, the probability of at least one false positive across all of them is</p>
<p><span class="math display">\[
P(\text{at least one false positive}) = 1-(1-\alpha)^m.
\]</span></p>
<p>With three groups, that’s three tests and a familywise error rate of 14%, not 5%:</p>
<p><span class="math display">\[
1-(1-.05)^3 = .14.
\]</span></p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Number of groups (<span class="math inline">\(k\)</span>)</th>
<th>Pairwise tests (<span class="math inline">\(m\)</span>)</th>
<th>Familywise error rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>3</td>
<td><span class="math inline">\(1-.95^3=.14\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td>6</td>
<td><span class="math inline">\(1-.95^6=.26\)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td>10</td>
<td><span class="math inline">\(1-.95^{10}=.40\)</span></td>
</tr>
</tbody>
</table>
<p>Even with only five groups, there’s a 40% chance of turning up at least one “significant” difference somewhere purely by chance, even if every population mean is identical. <a href="#fig-9multiplet">Figure&nbsp;<span>8.1</span></a> shows this inflation directly: as the number of independent <span class="math inline">\(t\)</span>-tests grows, so does the chance that at least one is a false positive.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9multiplet" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-ANOVA_files/figure-html/fig-9multiplet-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;8.1: Familywise Type I error rate as the number of independent t-tests increases, at alpha = .05 per test.</figcaption>
</figure>
</div>
</div>
</div>
<p>ANOVA solves this by replacing many separate <span class="math inline">\(t\)</span>-tests with <strong>one</strong> test that controls the overall error rate. It asks a single question:</p>
<p><span class="math display">\[
H_0: \mu_1=\mu_2=\mu_3 \qquad H_a: \text{at least one mean differs}
\]</span></p>
<p>Just like the <span class="math inline">\(t\)</span>-test, different research designs call for different kinds of ANOVA: a one-factor (between-subjects) ANOVA when every unit is measured once, and a repeated-measures ANOVA when the same units are measured under multiple conditions. We start with the one-factor case.</p>
</section>
</section>
<section id="one-factor-anova" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="one-factor-anova"><span class="header-section-number">8.2</span> One-factor ANOVA</h2>
<p>The one-factor ANOVA (also called a between-subjects, independent-factor, or one-way ANOVA) is the simplest version of the test: one independent variable with two or more levels, and every unit measured once.</p>
<p>With exactly two groups, a <span class="math inline">\(t\)</span>-test and a one-factor ANOVA give the same answer: <span class="math inline">\(t^2=F\)</span>. Both compare the size of an effect to the amount of variation you’d expect from sampling error alone; the <span class="math inline">\(t\)</span>-test expresses that comparison as <span class="math inline">\(t\)</span>, and the ANOVA expresses the same underlying ratio as <span class="math inline">\(F\)</span> (named for Fisher, its inventor).</p>
<p><span class="math display">\[
F = \frac{\text{measure of effect}}{\text{measure of error}}
\]</span></p>
<p>The difference is that <span class="math inline">\(F\)</span> uses <strong>variances</strong> for both the numerator and the denominator, so <span class="math inline">\(F\)</span> is a ratio of two variances: the variance you can explain (differences between group means) over the variance you can’t (leftover noise within each group).</p>
<p><span class="math display">\[
F = \frac{\text{Can explain}}{\text{Can't explain}}
\]</span></p>
<p>When the two are about the same size, <span class="math inline">\(F\approx 1\)</span>: group differences are no bigger than ordinary sampling noise. When explained variance is much larger than unexplained variance, <span class="math inline">\(F\)</span> climbs well above 1, evidence that the groups really differ; when it’s smaller, <span class="math inline">\(F\)</span> drops below 1. An <span class="math inline">\(F\)</span> of 5, for example, means the groups explain five times more variance than they leave unexplained, a substantial effect; an <span class="math inline">\(F\)</span> of 0.6 means the opposite, mostly unexplained noise.</p>
<section id="computing-the-f-value" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="computing-the-f-value"><span class="header-section-number">8.2.1</span> Computing the <span class="math inline">\(F\)</span>-value</h3>
<p>ANOVA splits the total variation in the data into two sources: variation caused by group membership (the manipulation), and variation left over as sampling error. If we can measure those two parts separately, we can turn them into a ratio and get an <span class="math inline">\(F\)</span>-value.</p>
<p><span class="math display">\[
\text{Total variation} = \text{Variation between groups} + \text{Variation within groups}
\]</span></p>
<p>To make that precise we need an actual measure of variation. As in Chapter 1, that’s the <strong>sums of squares</strong>:</p>
<p><span class="math display">\[
SS_\text{Total} = SS_\text{Between} + SS_\text{Within}
\]</span></p>
</section>
<section id="ss-total" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="ss-total"><span class="header-section-number">8.2.2</span> SS Total</h3>
<p><span class="math inline">\(SS_\text{Total}\)</span> captures all of the variation in a dataset: the difference between each score and the grand mean, squared and summed.</p>
<p>Let’s imagine we had some data in three groups, A, B, and C. For example, we might have 3 scores in each group. The data could look like this:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">groups</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff_squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">169</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">C</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">302</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">33.5555555555556</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The data are in long format, so each row is a single score. The mean of all of the scores is the <strong>Grand Mean</strong>, calculated in the table as 7.</p>
<p>The <code>diff</code> column holds every score’s distance from the grand mean; <code>diff_squared</code> squares those distances. Squaring matters because the raw differences sum to zero (the mean is the balancing point of the data), so working with them directly wouldn’t tell us anything. Squaring turns every deviation positive and, as a side effect, weights larger deviations more heavily.</p>
<p>Adding up all of the squared deviations gives the sums of squares, which is where the name comes from. That’s the first piece of our answer:</p>
<p><span class="math display">\[
SS_\text{Total} = SS_\text{Between} + SS_\text{Within}, \qquad 302 = SS_\text{Between} + SS_\text{Within}.
\]</span></p>
<p>We only need to compute one of the two remaining pieces directly; the other follows by subtraction.</p>
</section>
<section id="ss-between" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="ss-between"><span class="header-section-number">8.2.3</span> SS Between</h3>
<p><span class="math inline">\(SS_\text{Total}\)</span> captured all of the variation in the data. <span class="math inline">\(SS_\text{Between}\)</span> isolates the piece of that variation caused by group membership: how far each group’s mean sits from the grand mean.</p>
<p>To find it, replace every score with its own group’s mean, then square and sum each group mean’s distance from the grand mean.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">groups</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">means</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff_squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">C</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">8</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Notice the new <code>means</code> column: the mean for group A was 11, so there are three 11s, one per observation in row A; groups B and C both average to 5, so the rest of the column is 5s.</p>
<p>Each score has been replaced by its own group’s mean. From the mean’s point of view, every score in the group looks identical: a mean has no memory of how far off it was from any individual data point, only that everything in the group is centered on it.</p>
<p>Finding the differences between each of those group-mean values and the grand mean, squaring them, and summing gives <span class="math inline">\(SS_\text{Between} = 72\)</span>: the amount of variation caused by differences between the group means, i.e., the variation we can explain by group membership.</p>
<p><span class="math inline">\(SS_\text{Between}\)</span> can never be larger than <span class="math inline">\(SS_\text{Total}\)</span>, and indeed 72 is smaller than 302.</p>
</section>
<section id="ss-within" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="ss-within"><span class="header-section-number">8.2.4</span> SS Within</h3>
<p>We already have <span class="math inline">\(SS_\text{Total} = 302\)</span> and <span class="math inline">\(SS_\text{Between} = 72\)</span>, so we can solve for <span class="math inline">\(SS_\text{Within}\)</span> by subtraction:</p>
<p><span class="math display">\[
SS_\text{Within} = SS_\text{Total} - SS_\text{Between} = 302 - 72 = 230.
\]</span></p>
<p>It’s worth calculating <span class="math inline">\(SS_\text{Within}\)</span> directly from the data too, both to see where it comes from and to double-check that the subtraction was right.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">groups</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">scores</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">means</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">diff_squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">-9</td>
<td style="text-align: left;">81</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">81</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">C</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-6</td>
<td style="text-align: left;">36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">230</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">25.5555555555556</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>This time, for each score we found the group mean first, then found the leftover error in that estimate: the <code>diff</code> column is the difference between each score and its own group mean, and <code>diff_squared</code> squares those differences. Summing them gives another sum of squares, <span class="math inline">\(SS_\text{Within}\)</span>: the deviations the group means can’t explain.</p>
</section>
<section id="degrees-of-freedom" class="level3" data-number="8.2.5">
<h3 data-number="8.2.5" class="anchored" data-anchor-id="degrees-of-freedom"><span class="header-section-number">8.2.5</span> Degrees of freedom</h3>
<p>Degrees of freedom work the same way here as for the <span class="math inline">\(t\)</span>-test: every time we estimate something from the data, we use up a degree of freedom.</p>
<p><span class="math inline">\(df_\text{Between} = \text{groups}-1\)</span>. With 3 groups, <span class="math inline">\(df_\text{Between}=3-1=2\)</span>: once we fix the grand mean, two of the three group means are free to be anything, but the third is determined by the other two.</p>
<p><span class="math inline">\(df_\text{Within} = \text{scores}-\text{groups}\)</span>. With 9 scores and 3 groups, <span class="math inline">\(df_\text{Within}=9-3=6\)</span>: estimating each of the 3 group means uses up 3 degrees of freedom, so only 6 of the 9 individual deviations are free to vary.</p>
</section>
<section id="mean-squares" class="level3" data-number="8.2.6">
<h3 data-number="8.2.6" class="anchored" data-anchor-id="mean-squares"><span class="header-section-number">8.2.6</span> Mean Squares</h3>
<p>We’re building toward <span class="math inline">\(F=\dfrac{\text{measure of effect}}{\text{measure of error}}\)</span>, and it’s tempting to just divide <span class="math inline">\(SS_\text{Between}\)</span> by <span class="math inline">\(SS_\text{Within}\)</span> directly. The trouble is that <span class="math inline">\(SS_\text{Within}\)</span> sums over all 9 individual scores while <span class="math inline">\(SS_\text{Between}\)</span> sums over only 3 group means, so <span class="math inline">\(SS_\text{Within}\)</span> is almost always the much larger number, and the raw ratio wouldn’t be interpretable the way <span class="math inline">\(t\)</span> or <span class="math inline">\(z\)</span> are.</p>
<p>The fix is to convert each sum of squares into an average, or <strong>mean square</strong>, by dividing by its degrees of freedom (rather than its raw count, since these are estimated quantities):</p>
<p><span class="math display">\[
MS_\text{Between} = \frac{SS_\text{Between}}{df_\text{Between}} = \frac{72}{2} = 36
\]</span></p>
<p><span class="math display">\[
MS_\text{Within} = \frac{SS_\text{Within}}{df_\text{Within}} = \frac{230}{6} = 38.33
\]</span></p>
<p>Both are variances: <span class="math inline">\(MS_\text{Between}\)</span> measures how much the group means vary, and <span class="math inline">\(MS_\text{Within}\)</span> measures how much individual scores vary around their own group’s mean.</p>
</section>
<section id="calculate-f" class="level3" data-number="8.2.7">
<h3 data-number="8.2.7" class="anchored" data-anchor-id="calculate-f"><span class="header-section-number">8.2.7</span> Calculate F</h3>
<p>With <span class="math inline">\(MS_\text{Between}\)</span> and <span class="math inline">\(MS_\text{Within}\)</span> in hand, <span class="math inline">\(F\)</span> is their ratio:</p>
<p><span class="math display">\[
F = \frac{MS_\text{Between}}{MS_\text{Within}} = \frac{36}{38.33} = 0.94
\]</span></p>
</section>
<section id="the-anova-table" class="level3" data-number="8.2.8">
<h3 data-number="8.2.8" class="anchored" data-anchor-id="the-anova-table"><span class="header-section-number">8.2.8</span> The ANOVA table</h3>
<p>All of these pieces, the <span class="math inline">\(df\)</span>s, <span class="math inline">\(SS\)</span>es, <span class="math inline">\(MS\)</span>es, and finally <span class="math inline">\(F\)</span>, are conveniently organized into an <strong>ANOVA table</strong>:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">groups</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">36.00000</td>
<td style="text-align: right;">0.9391304</td>
<td style="text-align: right;">0.4417359</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">230</td>
<td style="text-align: right;">38.33333</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>R labels the two rows <code>groups</code> (the between-groups row: what the means can explain) and <code>Residuals</code> (the within-groups row: what they can’t). Other software uses slightly different labels for the same two rows. The table doesn’t add new information beyond what we already computed; it just organizes it, with <span class="math inline">\(MS_\text{Between}\)</span> (36) divided by <span class="math inline">\(MS_\text{Within}\)</span> (38.33) giving the <span class="math inline">\(F\)</span>-value.</p>
</section>
</section>
<section id="what-does-f-mean" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="what-does-f-mean"><span class="header-section-number">8.3</span> What does F mean?</h2>
<p>Every number in the ANOVA table so far was computed directly from the data, except one: the <span class="math inline">\(p\)</span>-value. Its meaning is the same as for any other test we’ve covered: the probability of observing an <span class="math inline">\(F\)</span> this large or larger if the null hypothesis (no real group differences) were true.</p>
<p>Since <span class="math inline">\(F\)</span> is a sample statistic, we can find out how it behaves the same way we found out how <span class="math inline">\(t\)</span> behaves: simulate it many times under the null and look at the resulting distribution.</p>
<p>To build intuition for the F distribution, consider a simulated monitoring study with three site types (A, B, C). Each site type has 10 sampling plots, for 30 total. We measure species abundance at each plot. Critically, the <strong>null scenario</strong> applies: all 30 plots are drawn from the same distribution (mean = 100, SD = 10), so site type has no real effect on abundance. Any differences between group means arise from sampling error alone.</p>
<p>We run this simulation 10,000 times. Each time we compute F from the sample data. The histogram of those 10,000 F-values, shown in <a href="#fig-9fnull">Figure&nbsp;<span>8.2</span></a>, is the null distribution of F for this design.</p>
<div class="cell" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-9fnull" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-ANOVA_files/figure-html/fig-9fnull-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;8.2: A simulation of 10,000 experiments from a null distribution where there is no differences. The histogram shows 10,000 <span class="math inline">\(F\)</span>-values, one for each simulation. These are values that F can take in this situation. All of these <span class="math inline">\(F\)</span>-values were produced by random sampling error.</figcaption>
</figure>
</div>
</div>
</div>
<p>A couple of things are worth noting about this <span class="math inline">\(F\)</span> distribution. First, it never goes below 0: <span class="math inline">\(F\)</span> is a ratio of two variances, and variances can’t be negative, so neither can <span class="math inline">\(F\)</span>. Second, it isn’t normal or symmetric; it’s right-skewed, and its exact shape depends on the numerator and denominator degrees of freedom.</p>
<p>Most simulated <span class="math inline">\(F\)</span>-values here cluster below 1, which makes sense: all 30 plots were drawn from the same distribution, so on average the explained and unexplained variance should be about the same size. A smaller number of <span class="math inline">\(F\)</span>-values reach up toward 5, an <span class="math inline">\(F\)</span> that large would mean the groups explain five times more variance than they leave unexplained, which is a lot, and the histogram shows that values that large are rare. Every <span class="math inline">\(F\)</span> in this histogram was produced purely by random sampling error, since we built the simulation with no real group differences at all.</p>
<section id="making-decisions" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="making-decisions"><span class="header-section-number">8.3.1</span> Making decisions</h3>
<p>We can use this null distribution of <span class="math inline">\(F\)</span> to decide when a real experiment’s result is too large to be explained by chance:</p>
<ol type="1">
<li>Set an alpha criterion of <span class="math inline">\(p\)</span> = 0.05</li>
<li>Find the critical value of <span class="math inline">\(F\)</span> for our design’s numerator and denominator <span class="math inline">\(df\)</span>s.</li>
</ol>
<p><a href="#fig-9criticalF">Figure&nbsp;<span>8.3</span></a> marks that critical value on the histogram:</p>
<div class="cell" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-9criticalF" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-ANOVA_files/figure-html/fig-9criticalF-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;8.3: The critical value for <span class="math inline">\(F\)</span> where 5% of all <span class="math inline">\(F\)</span>-values lie beyond this point</figcaption>
</figure>
</div>
</div>
</div>
<p>Only 5% of <span class="math inline">\(F\)</span>-values from this null distribution are 3.35 or larger. That gives us a decision rule: if we ran the same design for real (30 plots, 10 per site type) and site type genuinely affected abundance, we could treat <span class="math inline">\(F\geq3.35\)</span> as evidence the differences aren’t just chance. An observed <span class="math inline">\(F\)</span> of 3.4, for instance, would occur less than 5% of the time under the null, so seeing it would give us reasonably good grounds to conclude that site type actually mattered.</p>
</section>
<section id="f-and-the-means" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="f-and-the-means"><span class="header-section-number">8.3.2</span> F and the means</h3>
<p>An <span class="math inline">\(F\)</span>-value and its <span class="math inline">\(p\)</span>-value don’t, by themselves, tell us what the group means actually were. If a study reports <span class="math inline">\(F(2,27)=6.0\)</span>, <span class="math inline">\(p=.001\)</span>, we know only that an <span class="math inline">\(F\)</span> this large would happen by chance about 0.1% of the time, strong evidence against the null. We still don’t know which means differed, or by how much, without looking at the group means directly (the ANOVA table itself doesn’t report them).</p>
<p>That said, a large <span class="math inline">\(F\)</span> with a small <span class="math inline">\(p\)</span>-value does tell us one thing for certain: the group means <strong>must</strong> differ somewhere. If they didn’t, the variance explained by group membership (the numerator of <span class="math inline">\(F\)</span>) wouldn’t be large enough to produce that result. We know a difference exists; identifying it requires a separate step.</p>
<section id="anova-is-an-omnibus-test" class="level4" data-number="8.3.2.1">
<h4 data-number="8.3.2.1" class="anchored" data-anchor-id="anova-is-an-omnibus-test"><span class="header-section-number">8.3.2.1</span> ANOVA is an omnibus test</h4>
<p>This is why ANOVA is called an <strong>omnibus test</strong>: omnibus meaning “comprising several items.” It answers one overall question that stands in for several pairwise ones at once.</p>
<p>With three groups A, B, and C, there are three possible pairwise differences: A vs.&nbsp;B, B vs.&nbsp;C, and A vs.&nbsp;C. We could test each with a separate <span class="math inline">\(t\)</span>-test, or ask the more general omnibus question with a single ANOVA:</p>
<p>Hypothesis of no differences anywhere: <span class="math inline">\(A=B=C\)</span></p>
<p>Any differences anywhere:</p>
<ol type="a">
<li><span class="math inline">\(A\neq B=C\)</span></li>
<li><span class="math inline">\(A=B\neq C\)</span></li>
<li><span class="math inline">\(A\neq C=B\)</span></li>
</ol>
<p>A small <span class="math inline">\(F\)</span> with a large <span class="math inline">\(p\)</span>-value means we don’t reject the hypothesis of no differences: we have no evidence the three group means differ, and whatever gaps exist could easily be chance. A large <span class="math inline">\(F\)</span> with a small <span class="math inline">\(p\)</span>-value (below our alpha criterion) means we reject that hypothesis and conclude at least one group mean differs from the others. That’s the omnibus test: it tells us <em>whether</em> the means differ, not yet <em>which</em> ones.</p>
</section>
<section id="looking-at-group-means-directly" class="level4" data-number="8.3.2.2">
<h4 data-number="8.3.2.2" class="anchored" data-anchor-id="looking-at-group-means-directly"><span class="header-section-number">8.3.2.2</span> Looking at group means directly</h4>
<p>The 10,000 simulated experiments above never once showed us the actual group means behind each <span class="math inline">\(F\)</span>-value. <a href="#fig-9manyDiffs">Figure&nbsp;<span>8.4</span></a> shows the group means (with standard-error bars) from 10 of those null simulations.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9manyDiffs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-ANOVA_files/figure-html/fig-9manyDiffs-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;8.4: Different patterns of group means under the null (all scores for each group sampled from the same distribution).</figcaption>
</figure>
</div>
</div>
</div>
<p>Each panel is one simulated experiment; the dots are the group means for site types A, B, and C, with error bars showing standard error. All 30 plots in every panel were drawn from the same distribution (mean = 100, sd = 10), so the group means are only ever different because of sampling error, not any real effect of site type.</p>
<p>In most panels, the error bars overlap heavily, visually suggesting no real difference. In a few, they overlap less, which would suggest a difference that isn’t actually there. Concluding a real effect from one of those panels would be a Type I error: we know there’s no true difference here because we built the simulation that way, but in a real study you don’t get to know that in advance.</p>
</section>
<section id="what-group-means-look-like-when-f-is-less-than-1" class="level4" data-number="8.3.2.3">
<h4 data-number="8.3.2.3" class="anchored" data-anchor-id="what-group-means-look-like-when-f-is-less-than-1"><span class="header-section-number">8.3.2.3</span> What group means look like when F is less than 1</h4>
<p><a href="#fig-9flessthanone">Figure&nbsp;<span>8.5</span></a> shows 10 simulated experiments, this time filtered to only the ones where <span class="math inline">\(F&lt;1\)</span>, the cases where we’d clearly fail to reject the null.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9flessthanone" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-ANOVA_files/figure-html/fig-9flessthanone-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;8.5: Different patterns of group means under the null (sampled from same distribution) when F is less than 1.</figcaption>
</figure>
</div>
</div>
</div>
<p>The panel numbers show which simulations actually produced <span class="math inline">\(F&lt;1\)</span>. The bars aren’t perfectly flat, but what matters is that within each panel, the error bars for all three means overlap heavily: our estimate of the mean is about the same across groups, and we wouldn’t be making a Type I error here.</p>
</section>
<section id="what-group-means-look-like-when-f-exceeds-the-critical-value" class="level4" data-number="8.3.2.4">
<h4 data-number="8.3.2.4" class="anchored" data-anchor-id="what-group-means-look-like-when-f-exceeds-the-critical-value"><span class="header-section-number">8.3.2.4</span> What group means look like when F exceeds the critical value</h4>
<p>Earlier we found a critical value of 3.35: only 5% of <span class="math inline">\(F\)</span>-values from this null distribution exceed it. <a href="#fig-9sigdiffs">Figure&nbsp;<span>8.6</span></a> shows 10 simulations filtered to exactly that rare case, <span class="math inline">\(F&gt;3.35\)</span>, even though every one of them is still drawn from the same null distribution with no real group differences. Rejecting the null whenever <span class="math inline">\(F\)</span> clears 3.35 is the right long-run decision rule, but every one of these particular simulations would be a Type I error if we did.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-9sigdiffs" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-ANOVA_files/figure-html/fig-9sigdiffs-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;8.6: Different patterns of group means under the null when F is above critical value (these are all type I Errors).</figcaption>
</figure>
</div>
</div>
</div>
<p>Every panel of <a href="#fig-9sigdiffs">Figure&nbsp;<span>8.6</span></a> now shows at least one group mean whose error bars don’t overlap with another’s: a visually convincing “real” difference. All ten are Type I errors. That’s the deceptive part: when this happens by chance, the data really does look like it shows a pattern, the <span class="math inline">\(F\)</span>-value really is large, and the <span class="math inline">\(p\)</span>-value really is small. A genuine Type I error looks exactly like a genuine effect, which is exactly why it’s easy to be convinced by one.</p>
</section>
</section>
</section>
<section id="anova-on-real-data" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="anova-on-real-data"><span class="header-section-number">8.4</span> ANOVA on Real Data</h2>
<p>We’ve covered the fundamentals of ANOVA: how to compute an <span class="math inline">\(F\)</span>-statistic from the data, and how to interpret it along with its <span class="math inline">\(p\)</span>-value. In practice, software handles these calculations for you, but understanding what the numbers mean is what lets you interpret them correctly. Computing at least one ANOVA by hand, as we just did, is worth the effort: it’s the fastest way to build real intuition for what the software is doing under the hood.</p>
<p>The following example applies the full ANOVA workflow, from descriptive summaries through the omnibus F test to post-hoc comparisons, to a real ecological dataset. This is the same dataset used in Lab 10.</p>
<section id="salamander-abundance-across-forest-types" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="salamander-abundance-across-forest-types"><span class="header-section-number">8.4.1</span> Salamander abundance across forest types</h3>
<p>Plethodontid salamanders are sensitive indicators of forest condition: they depend on moist microhabitats, abundant coarse woody debris, and stable soil temperatures, all features that decline with forest disturbance. A field ecologist surveys salamander abundance at 24 plots distributed across three forest types: <strong>old-growth</strong> (8 plots), <strong>secondary</strong> forest (8 plots), and <strong>managed plantation</strong> (8 plots). The research question is whether mean salamander abundance differs among forest types.</p>
<p>Let’s look at the data and findings. Note that you will work through these steps yourself in Lab 10.</p>
<div class="cell" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-9salamanderData" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-ANOVA_files/figure-html/fig-9salamanderData-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;8.7: Mean salamander abundance (individuals per plot) across three forest types. Points show individual plot counts; error bars show ±1 SE.</figcaption>
</figure>
</div>
</div>
</div>
<p>The bar graph shows a clear gradient: old-growth plots have the highest mean abundance, managed plantations the lowest, with secondary forest in between. The individual plot counts (dots) show considerable within-group variability, a reminder that even where a real difference exists, individual plots can vary substantially.</p>
<p>We now conduct the one-way ANOVA to test whether these differences are larger than expected by chance alone.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-9salamanderANOVA" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;8.1: One-way ANOVA table for salamander abundance by forest type.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">forest_type</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">312.5833</td>
<td style="text-align: right;">156.29167</td>
<td style="text-align: right;">14.60345</td>
<td style="text-align: right;">0.000106</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">224.7500</td>
<td style="text-align: right;">10.70238</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>We report the result as:</p>
<blockquote class="blockquote">
<p>There was a significant effect of forest type on salamander abundance, F(2, 21) = 14.60, MSE = 10.65, p &lt; 0.001.</p>
</blockquote>
<p>The F-value of 14.60 falls far into the tail of the null F distribution for df(2, 21): values this large arise by chance less than 0.1% of the time. We reject the null hypothesis that all three group means are equal.</p>
</section>
<section id="checking-anovas-assumptions" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="checking-anovas-assumptions"><span class="header-section-number">8.4.2</span> Checking ANOVA’s assumptions</h3>
<p>Before trusting this result and moving on to post-hoc comparisons, it’s worth pausing to check whether ANOVA’s assumptions actually hold. (Recall from Chapter 6 that independence is the universal assumption that applies to every test we cover and won’t be re-listed here; what follows are ANOVA’s <em>test-specific</em> assumptions.)</p>
<p>ANOVA has two: <strong>homogeneity of variance</strong> (the groups’ spread around their own means should be roughly comparable) and <strong>approximately normal residuals</strong> (the leftover variation after accounting for group membership should be roughly bell-shaped). Both matter for the same underlying reason: the F-test pools information across groups into single numbers (a common error variance, a reference F-distribution), and that pooling is only trustworthy if the groups are behaving similarly enough to be pooled.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Levene's test for homogeneity of variance</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic (F)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.52</td>
<td style="text-align: left;">0.599</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">21</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Shapiro-Wilk test on ANOVA residuals</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic (W)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.93</td>
<td style="text-align: left;">0.078</td>
<td style="text-align: left;">Shapiro-Wilk normality test</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Levene’s test gives <span class="math inline">\(F(2,21) = 0.52\)</span>, <span class="math inline">\(p = .60\)</span>: no evidence of unequal variance across forest types. The Shapiro-Wilk test on the model’s residuals gives <span class="math inline">\(W = 0.93\)</span>, <span class="math inline">\(p = .078\)</span>: no strong evidence against normality either. Both checks are consistent with the boxplot and dot plot we already looked at in <a href="#fig-9salamanderData">Figure&nbsp;<span>8.7</span></a>: similar spread across groups, no glaring outliers.</p>
<p><strong>A word of caution about formal assumption tests.</strong> It’s tempting to treat Levene’s test as a strict gate, where significant means “stop” and not significant means “proceed.” Resist that. These tests have an awkward property: with a small sample (exactly when a violated assumption matters most), they have low power and will often say “no problem” even when there is one; with a very large sample (where ANOVA is fairly robust to mild violations anyway), they have high power and will flag trivial differences as “significant.” A formal test is one piece of evidence, not the whole verdict, so look at the diagnostic plots too and use judgment. In practice, one-way ANOVA is moderately robust to mild departures from these assumptions, especially with balanced group sizes like we have here (8 plots per forest type). The situation to genuinely worry about is the combination of small, unbalanced samples with visibly skewed data or wildly different spreads, and that’s exactly when the nonparametric alternative below becomes the better choice.</p>
</section>
<section id="post-hoc-comparisons-with-tukey-hsd" class="level3" data-number="8.4.3">
<h3 data-number="8.4.3" class="anchored" data-anchor-id="post-hoc-comparisons-with-tukey-hsd"><span class="header-section-number">8.4.3</span> Post-hoc comparisons with Tukey HSD</h3>
<p>The omnibus F test tells us that at least one group mean differs, but not which pairs. To identify which forest types differ, we use <strong>Tukey’s Honestly Significant Difference (HSD)</strong> test. Tukey HSD controls the family-wise error rate across all pairwise comparisons, making it the appropriate choice after a significant ANOVA.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-9tukey" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;8.2: Tukey HSD post-hoc comparisons for salamander abundance by forest type.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">diff</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lwr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p adj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Secondary-Old-growth</td>
<td style="text-align: right;">-6.875</td>
<td style="text-align: right;">-10.998</td>
<td style="text-align: right;">-2.752</td>
<td style="text-align: right;">0.0011</td>
</tr>
<tr class="even">
<td style="text-align: left;">Managed-Old-growth</td>
<td style="text-align: right;">-8.250</td>
<td style="text-align: right;">-12.373</td>
<td style="text-align: right;">-4.127</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Managed-Secondary</td>
<td style="text-align: right;">-1.375</td>
<td style="text-align: right;">-5.498</td>
<td style="text-align: right;">2.748</td>
<td style="text-align: right;">0.6825</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>The Tukey results show:</p>
<ul>
<li><strong>Old-growth vs.&nbsp;Managed</strong>: mean difference = 8.25 individuals/plot, p = 0.0002. Old-growth plots support significantly higher salamander abundance than managed plantations.</li>
<li><strong>Old-growth vs.&nbsp;Secondary</strong>: mean difference = 6.88 individuals/plot, p = 0.0011. Old-growth plots also differ significantly from secondary forest.</li>
<li><strong>Secondary vs.&nbsp;Managed</strong>: mean difference = 1.38 individuals/plot, p = 0.68. Secondary forest and managed plantation plots are <strong>not</strong> significantly different from each other.</li>
</ul>
<p>The pattern is ecologically interpretable: old-growth forest supports the highest salamander abundance, consistent with its structural complexity and stable microclimate. Secondary forest and managed plantation are statistically indistinguishable, suggesting that the early stages of forest recovery may not yet restore the conditions salamanders require.</p>
</section>
<section id="nonparametric-alternative-the-kruskal-wallis-test" class="level3" data-number="8.4.4">
<h3 data-number="8.4.4" class="anchored" data-anchor-id="nonparametric-alternative-the-kruskal-wallis-test"><span class="header-section-number">8.4.4</span> Nonparametric alternative: the Kruskal-Wallis test</h3>
<p>Our assumption checks above came back clean, so the ANOVA result stands as-is. But suppose they hadn’t: visibly unequal spread across groups, or clearly skewed residuals, especially with small or unbalanced samples. The <strong>Kruskal-Wallis test</strong> is the nonparametric alternative to one-way ANOVA, in exactly the same relationship that the Mann-Whitney-Wilcoxon test has to the independent-samples <span class="math inline">\(t\)</span>-test (in fact, Kruskal-Wallis <em>is</em> the Mann-Whitney-Wilcoxon logic extended to more than two groups).</p>
<p><strong>How it works, conceptually.</strong> Rank every observation across all groups together, from smallest to largest, ignoring group membership. Then check whether the average rank differs more across groups than chance alone would produce. If forest type genuinely matters, one group’s observations should occupy systematically higher or lower ranks than the others.</p>
<p><strong>Its assumption.</strong> Kruskal-Wallis does not require normality. Like the Mann-Whitney-Wilcoxon test, it’s cleanest to interpret as a test of differences in <strong>location</strong> (median) when the groups’ distributions have similar shape; if the shapes differ a lot, a significant result tells you the groups differ somehow, but not cleanly whether that’s a difference in location, spread, or shape.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Kruskal-Wallis test on salamander abundance by forest type</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic (χ²)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">13.09</td>
<td style="text-align: left;">0.001</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Kruskal-Wallis rank sum test</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><span class="math inline">\(\chi^2(2) = 13.09\)</span>, <span class="math inline">\(p = .001\)</span>: significant, the same conclusion as the ANOVA (<span class="math inline">\(F(2,21)=14.60\)</span>, <span class="math inline">\(p&lt;.001\)</span>). That agreement is exactly what you’d hope for when the parametric assumptions were actually fine to begin with, as ours were here.</p>
<p><strong>Post-hoc comparisons.</strong> Just as a significant ANOVA needs Tukey HSD to identify <em>which</em> groups differ, a significant Kruskal-Wallis result needs its own follow-up: pairwise rank-sum tests (Mann-Whitney-Wilcoxon, applied to each pair) with a correction for running multiple comparisons.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Pairwise Mann-Whitney-Wilcoxon comparisons (Holm-adjusted)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group 1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Group 2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Secondary</td>
<td style="text-align: left;">Old-growth</td>
<td style="text-align: left;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">Managed</td>
<td style="text-align: left;">Old-growth</td>
<td style="text-align: left;">0.004</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Managed</td>
<td style="text-align: left;">Secondary</td>
<td style="text-align: left;">0.486</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The pattern matches Tukey HSD exactly: Old-growth differs significantly from both Secondary (<span class="math inline">\(p=.011\)</span>) and Managed (<span class="math inline">\(p=.004\)</span>), while Secondary and Managed do not differ from each other (<span class="math inline">\(p=.49\)</span>). Two different sets of assumptions, two different sets of machinery, same ecological story: that’s the point of having both tools available, not a coincidence to be suspicious of.</p>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">8.5</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> Comparing more than two groups with a stack of <span class="math inline">\(t\)</span>-tests inflates your false-positive rate fast. ANOVA solves that by asking one omnibus question first, and its variance-partitioning logic is the same idea that reappears in regression, factorial designs, and ANCOVA.</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>Why not just run more <span class="math inline">\(t\)</span>-tests.</strong> Each comparison carries its own chance of a false positive, and they accumulate: with <span class="math inline">\(m\)</span> comparisons the familywise error rate is <span class="math inline">\(1-(1-\alpha)^m\)</span>, which is already 14% for three groups.</li>
<li><strong>Partition the variation.</strong> Total variation splits into a piece explained by group membership (<span class="math inline">\(SS_\text{Between}\)</span>) and unexplained residual variation (<span class="math inline">\(SS_\text{Within}\)</span>). That split is the whole idea.</li>
<li><strong><span class="math inline">\(F\)</span> is a ratio of the two.</strong> After adjusting each sum of squares for its degrees of freedom, <span class="math inline">\(F = MS_\text{Between} / MS_\text{Within}\)</span>. A large <span class="math inline">\(F\)</span> means between-group differences are large relative to within-group noise.</li>
<li><strong>Two steps, always in order.</strong> First the omnibus test: do <em>any</em> group means differ? Only if that is significant do you run post-hoc comparisons (Tukey HSD) to find out <em>which</em> pairs differ.</li>
<li><strong>Check the assumptions.</strong> ANOVA needs approximately equal variances across groups (Levene’s test) and roughly normal residuals. Treat formal tests as evidence rather than a gate, since they have least power exactly when small samples make violations matter most.</li>
<li><strong>When assumptions fail.</strong> The <strong>Kruskal-Wallis</strong> test is the rank-based alternative, with <code>pairwise.wilcox.test()</code> as its post-hoc counterpart.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
<div id="ref-salsburg2001lady" class="csl-entry" role="listitem">
Salsburg, David. 2001. <em>The Lady Tasting Tea: <span>How</span> Statistics Revolutionized Science in the Twentieth Century</em>. <span>Macmillan</span>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-Nonparametric.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-Regression.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>