<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>Answering questions with data - 9&nbsp; Simple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-FactorialANOVA.html" rel="next">
<link href="./08-ANOVA.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 9&nbsp; Simple Linear Regression">
<meta property="og:description" content="">
<meta property="og:image" content="09-Regression_files/figure-html/fig-10regscatter-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 9&nbsp; Simple Linear Regression">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-Regression.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">When Assumptions Fail: Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#regression-basics" id="toc-regression-basics" class="nav-link active" data-scroll-target="#regression-basics"><span class="header-section-number">9.1</span> Regression Basics</a>
  <ul class="collapse">
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses"><span class="header-section-number">9.1.1</span> Hypotheses</a></li>
  </ul></li>
  <li><a href="#worked-regression-example-stream-temperature-and-dissolved-oxygen." id="toc-worked-regression-example-stream-temperature-and-dissolved-oxygen." class="nav-link" data-scroll-target="#worked-regression-example-stream-temperature-and-dissolved-oxygen."><span class="header-section-number">9.2</span> Worked regression example: stream temperature and dissolved oxygen.</a>
  <ul class="collapse">
  <li><a href="#the-regression-model" id="toc-the-regression-model" class="nav-link" data-scroll-target="#the-regression-model"><span class="header-section-number">9.2.1</span> The regression model</a></li>
  </ul></li>
  <li><a href="#testing-the-slope" id="toc-testing-the-slope" class="nav-link" data-scroll-target="#testing-the-slope"><span class="header-section-number">9.3</span> Testing the slope</a></li>
  <li><a href="#r-squared-variance-explained" id="toc-r-squared-variance-explained" class="nav-link" data-scroll-target="#r-squared-variance-explained"><span class="header-section-number">9.4</span> R-squared: variance explained</a></li>
  <li><a href="#consider-both-significance-and-effect-size" id="toc-consider-both-significance-and-effect-size" class="nav-link" data-scroll-target="#consider-both-significance-and-effect-size"><span class="header-section-number">9.5</span> Consider both significance and effect size</a></li>
  <li><a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions"><span class="header-section-number">9.6</span> Checking assumptions</a>
  <ul class="collapse">
  <li><a href="#sometimes-the-truth-isnt-a-line-at-all" id="toc-sometimes-the-truth-isnt-a-line-at-all" class="nav-link" data-scroll-target="#sometimes-the-truth-isnt-a-line-at-all"><span class="header-section-number">9.6.1</span> Sometimes the truth isn’t a line at all</a></li>
  <li><a href="#checking-normality" id="toc-checking-normality" class="nav-link" data-scroll-target="#checking-normality"><span class="header-section-number">9.6.2</span> Checking normality</a></li>
  </ul></li>
  <li><a href="#using-the-model-prediction" id="toc-using-the-model-prediction" class="nav-link" data-scroll-target="#using-the-model-prediction"><span class="header-section-number">9.7</span> Using the model: prediction</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">9.8</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/09-Regression.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 29, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<blockquote class="blockquote">
<p><em>Essentially, all models are wrong, but some are useful.</em></p>
<p>George E. P. Box</p>
</blockquote>
<p>Back in Chapter 2, we used the covariance between two variables to quantify the strength and direction of a relationship (<strong>Pearson’s <span class="math inline">\(r\)</span></strong>), and fit a best-fit line through a scatterplot, learning to compute its slope and intercept from the data. What we couldn’t yet do was ask the <strong>inference question</strong> every other test in this book has asked:</p>
<p><em>Could chance alone plausibly have produced our result?</em></p>
<p>Now that we’ve learned hypothesis testing, sampling distributions, and the logic of comparing an observed statistic to a null distribution, we can put the regression line through that same machinery to test whether a given <strong>slope</strong> is evidence of a real relationship.</p>
<section id="regression-basics" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="regression-basics"><span class="header-section-number">9.1</span> Regression Basics</h2>
<p>The equation for a linear regression will be familiar, and it’s one of the most heavily used equations in applied science:</p>
<p><span class="math inline">\(y = \beta_0 + \beta_1 x + \varepsilon\)</span></p>
<p><em>Slope term</em>: <span class="math inline">\(\beta_1\)</span></p>
<p><em>Intercept term</em>: <span class="math inline">\(\beta_0\)</span>.</p>
<p>A linear equation, fit to real data, is a statistical <strong>model</strong>. We never observe <span class="math inline">\(\beta_1\)</span> directly. So, we need one additional term for the <em>residual error</em>, <span class="math inline">\(\varepsilon\)</span>. This is the additional variability in the DV not explained by our model.</p>
<p><strong>Parameters and sample statistics</strong></p>
<p>Because it’s a <em>model</em>, our beta coefficients represent the <strong>population parameters</strong>, which you’ll recall come from the inferred, but never truly known, parent distribution.</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>What is it?</th>
<th>Do we know it?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta_0, \beta_1\)</span></td>
<td>True population intercept and slope</td>
<td>Almost never known for sure</td>
</tr>
<tr class="even">
<td><span class="math inline">\(b_0, b_1\)</span></td>
<td>Sample intercept and slope</td>
<td>Yes, calculated by fitting the line to our data</td>
</tr>
</tbody>
</table>
<p>What we generate by drawing the best-fit line through our data is a <em>sample slope</em>, usually written <span class="math inline">\(b_1\)</span>.</p>
<section id="hypotheses" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="hypotheses"><span class="header-section-number">9.1.1</span> Hypotheses</h3>
<p>Our null and alternate hypotheses are fairly straightforward:</p>
<ul>
<li><p><span class="math inline">\(H_0: \beta_1 = 0\)</span> (there is no linear relationship between the continuous IV and the continuous DV)</p></li>
<li><p><span class="math inline">\(H_A: \beta_1 \neq 0\)</span> (there is a linear relationship between the variables)</p></li>
</ul>
<p><strong>But how to test them formally?</strong></p>
<p>Recall the “signal over noise” pattern, which is the basis for inference.</p>
<p><span class="math display">\[
\text{statistic}=\frac{\text{effect}}{\text{error}}.
\]</span></p>
<p>Like any other statistic, <span class="math inline">\(b_1\)</span> varies from sample to sample. If we drew a new sample from the same population and fit a new line, we’d get a slightly different <span class="math inline">\(b_1\)</span>, just by chance. Simple linear regression asks whether the sample slope <span class="math inline">\(b_1\)</span> is large enough, relative to that sampling variability, to conclude that a real linear relationship exists in the population, rather than one produced by chance alone.</p>
<p>We’ve previously done <span class="math inline">\(t\)</span>-tests on means, but the test statistic can be generated for other values too, in this case, our sample slope:</p>
<p><span class="math display">\[
t = \frac{\text{effect}}{\text{standard error}} = \frac{b_1}{SE(b_1)}
\]</span></p>
<p>We need just one more thing to get our p-value, our degrees of freedom. In our simple linear regression, one degree of freedom is spent estimating the intercept, one for the slope:</p>
<p><span class="math inline">\(df = n - 2\)</span></p>
<p>Comparing our estimated slope to its standard error, we can now quantify the probability our <span class="math inline">\(b_1\)</span> estimate could have occured by chance alone under the null hypothesis.</p>
</section>
</section>
<section id="worked-regression-example-stream-temperature-and-dissolved-oxygen." class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="worked-regression-example-stream-temperature-and-dissolved-oxygen."><span class="header-section-number">9.2</span> Worked regression example: stream temperature and dissolved oxygen.</h2>
<p>Let’s work through an example. Warmer water holds less dissolved gas, so ecologists expect dissolved oxygen (DO) to decline as stream temperature rises. This matters for stream health: low DO can stress or kill fish and invertebrates. Suppose we sample 40 stream sites, measuring water temperature (°C) and dissolved oxygen (mg/L) at each.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10regscatter" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10regscatter-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;9.1: Stream temperature and dissolved oxygen at 40 sample sites, with the fitted regression line.</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatterplot in <a href="#fig-10regscatter">Figure&nbsp;<span>9.1</span></a> shows a clear downward trend. Just from the graph, we can guess a couple of things:</p>
<ul>
<li><p>Pearson’s <span class="math inline">\(r\)</span> should be negative, since DO falls as temperature rises</p></li>
<li><p>It should sit fairly close to <span class="math inline">\(-1\)</span> since the points hug the line with only modest scatter.</p></li>
</ul>
<p>Before now, we didn’t have a way to test whether an <span class="math inline">\(r\)</span> that size is more than chance would produce, only how to compute it. Regression adds that missing piece by writing that observed relationship as a model we can test.</p>
<section id="the-regression-model" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="the-regression-model"><span class="header-section-number">9.2.1</span> The regression model</h3>
<p>We model dissolved oxygen as a linear function of stream temperature, plus error:</p>
<p><span class="math display">\[DO = \beta_0 + \beta_1(\text{Temperature}) + \varepsilon\]</span></p>
<p><span class="math inline">\(\beta_0\)</span> is the population intercept, <span class="math inline">\(\beta_1\)</span> is the population slope, and <span class="math inline">\(\varepsilon\)</span> is the error, the part of DO that temperature alone doesn’t explain.</p>
<p>We don’t know <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>; we estimate them from the sample as <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>, using the same least-squares logic from Chapter 2 (the line that minimizes the sum of squared residuals).</p>
<p>In R, this is a single line of code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(DO <span class="sc">~</span> stream_temp, <span class="at">data =</span> stream_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This fitted line (<a href="#fig-10regresidviz">Figure&nbsp;<span>9.2</span></a>) is the best-fit line that minimizes the total squared distance between the data and the line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10regresidviz" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10regresidviz-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Scatter plot of dissolved oxygen against stream temperature with a fitted downward-sloping line. Open circles mark each point's predicted value on the line, and a red vertical segment connects each observed point to its prediction."></p>
<figcaption class="figure-caption">Figure&nbsp;9.2: Stream temperature and dissolved oxygen with the fitted line. Vertical red segments are residuals.</figcaption>
</figure>
</div>
</div>
</div>
<p>Here’s the table of model coefficients R gives us.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Coefficient table for DO ~ stream temperature</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">13.40</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">18.44</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: right;">11.93</td>
<td style="text-align: right;">14.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">stream_temp</td>
<td style="text-align: right;">-0.27</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">-6.72</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: right;">-0.35</td>
<td style="text-align: right;">-0.19</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>With the results of the regression, we can get an equation for the fitted line:</p>
<p><span class="math inline">\(\widehat{DO} = 13.4 - 0.27 \times \text{Temperature}\)</span>.</p>
<p>The hat over <span class="math inline">\(DO\)</span> marks it as a <em>predicted</em> value, what the model outputs for a given temperature, as distinct from an actually observed <span class="math inline">\(DO\)</span> measurement.</p>
<p>The “estimate” column in our regression model output for the intercept and the slope are <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>, not <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. Recall this line is our model’s estimate from this one sample, not the true population line, which we never actually observe.</p>
<p>The intercept (<span class="math inline">\(b_0 = 13.4\)</span>) is the model’s predicted DO at 0°C, technically part of the model but outside the range of temperatures we actually sampled (10 to 24°C), so we won’t lean on it for interpretation.</p>
<p>The slope (<span class="math inline">\(b_1 = -0.27\)</span>) is the part we care about most: for every 1°C increase in stream temperature, predicted dissolved oxygen drops by about 0.27 mg/L.</p>
</section>
</section>
<section id="testing-the-slope" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="testing-the-slope"><span class="header-section-number">9.3</span> Testing the slope</h2>
<p>The slope <span class="math inline">\(b_1\)</span> is a sample estimate. Recall the hypothesis test asks whether the population slope <span class="math inline">\(\beta_1\)</span> could plausibly be zero:</p>
<ul>
<li><p><span class="math inline">\(H_0: \beta_1 = 0\)</span> (no linear relationship between stream temperature and dissolved oxygen)</p></li>
<li><p><span class="math inline">\(H_A: \beta_1 \neq 0\)</span> (there is a linear relationship)</p></li>
</ul>
<p>This <span class="math inline">\(t\)</span>-test for the regression slope, unlike the tests in earlier chapters, doesn’t need a separate function call: <code>lm()</code> computes it automatically the moment you fit the model. You the get whole coefficient table, <code>Std. Error</code>, <span class="math inline">\(t\)</span>, and <span class="math inline">\(p\)</span>, all at once.</p>
<p>Recall the test statistic compares the estimated slope to its standard error, the <code>Std. Error</code> column already in the coefficient table above, which measures how much <span class="math inline">\(b_1\)</span> would bounce around from sample to sample if we repeated this study over and over:</p>
<p><span class="math display">\[t = \frac{b_1}{SE(b_1)} = \frac{-0.271}{0.04} = -6.72\]</span></p>
<p>with <span class="math inline">\(df = n - 2 = 38\)</span> (one degree of freedom spent estimating the intercept, one for the slope).</p>
<p><strong>Where the <span class="math inline">\(p\)</span>-value comes from.</strong> If temperature and DO were truly unrelated in the population, repeating this study many times would still produce a nonzero <span class="math inline">\(b_1\)</span> just by chance, and a <span class="math inline">\(t\)</span>-statistic that follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df = 38\)</span>. <a href="#fig-10regslopenull">Figure&nbsp;<span>9.3</span></a> shows that distribution, with the critical values marking the boundary of the most extreme 5% under <span class="math inline">\(H_0\)</span>, and our observed <span class="math inline">\(t\)</span> marked against it.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10regslopenull" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10regslopenull-1.png" class="img-fluid figure-img" style="width:75.0%" alt="A t-distribution centered at zero with 38 degrees of freedom. Both tails beyond the critical values around plus or minus 2.02 are shaded and labeled as the rejection region, with the middle labeled retain H0. A vertical red line marks the observed t of about negative 6.72, far to the left of the critical value, labeled directly on the plot."></p>
<figcaption class="figure-caption">Figure&nbsp;9.3: The null distribution of t for the slope test at df=38. Shaded tails are the rejection region at alpha=.05; the dashed line marks our observed t, far into the left tail.</figcaption>
</figure>
</div>
</div>
</div>
<p>Our observed <span class="math inline">\(t = -6.72\)</span> sits far past the critical values of about <span class="math inline">\(\pm 2.02\)</span>, well outside where 95% of <span class="math inline">\(t\)</span>-values would fall if temperature and DO were unrelated. The <span class="math inline">\(p\)</span>-value is just the probability of landing that far out (or farther) in either tail under <span class="math inline">\(H_0\)</span>: here, <span class="math inline">\(p &lt; .001\)</span>, meaning essentially never. This crosses the conventional <span class="math inline">\(\alpha = .05\)</span> threshold.</p>
<p>We <strong>reject</strong> <span class="math inline">\(H_0\)</span>: stream temperature <strong>is</strong> linearly related to dissolved oxygen.</p>
<p>The 95% confidence interval for the slope, also in the coefficient table above, runs from -0.353 to -0.189 mg/L per °C. Because this interval does not contain 0, it agrees with the hypothesis test, as it always will.</p>
</section>
<section id="r-squared-variance-explained" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="r-squared-variance-explained"><span class="header-section-number">9.4</span> R-squared: variance explained</h2>
<p>After fitting a linear regression model, you also need to determine how well the model fits the data. Does it do a good job of explaining changes in the dependent variable?</p>
<p><strong>R-squared</strong> is a goodness-of-fit measure for linear regression models. It tells us the percentage of the variance in the dependent variable that the independent variables explain collectively. R-squared measures the strength of the relationship between your model and the dependent variable on a convenient 0 – 100% scale.</p>
<p>Just as one-way ANOVA in the last chapter partitioned total variability into a between-groups piece and a within-groups piece, regression partitions the total variability in <span class="math inline">\(Y\)</span> into a piece explained by the line and a piece left over as residual error:</p>
<p><span class="math display">\[SS_{Total} = SS_{Regression} + SS_{Residual}\]</span></p>
<p><span class="math inline">\(R^2\)</span> is the proportion of that total variability the line accounts for:</p>
<p><span class="math display">\[R^2 = \frac{SS_{Regression}}{SS_{Total}}\]</span></p>
<p>For simple regression with one predictor, <span class="math inline">\(R^2\)</span> is literally Pearson’s <span class="math inline">\(r\)</span> from Chapter 2, squared: <span class="math inline">\((-0.737)^2 = 0.543\)</span>, matching the model’s <span class="math inline">\(R^2\)</span> below exactly.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Model fit for DO ~ stream temperature</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">R-squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">value</td>
<td style="text-align: right;">0.543</td>
<td style="text-align: right;">45.09</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">38</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The table also reports <span class="math inline">\(F\)</span>, <span class="math inline">\(df1\)</span>, and <span class="math inline">\(df2\)</span>. With one predictor, <span class="math inline">\(F\)</span> and <span class="math inline">\(t\)</span> test the exact same thing: <span class="math inline">\(F = t^2 = -6.72^2 = 45.09\)</span>, matching the table. ANOVA reports its omnibus test this same way, and <span class="math inline">\(F\)</span> is the form that generalizes once more than one predictor is involved, which comes up shortly.</p>
<p>Here <span class="math inline">\(R^2 = 0.54\)</span>: stream temperature accounts for about 54% of the variation we observed in dissolved oxygen across sites. The remaining variation comes from everything else the model doesn’t capture (discharge, shading, groundwater input, and so on), folded into <span class="math inline">\(\varepsilon\)</span>.</p>
<p><strong>Reporting the result.</strong> We report a regression result the same way as any other test: the slope, the test statistic, degrees of freedom, and <span class="math inline">\(p\)</span>, plus <span class="math inline">\(R^2\)</span> as the effect size.</p>
<blockquote class="blockquote">
<p>Dissolved oxygen declined significantly with stream temperature, <span class="math inline">\(b_1 = -0.27\)</span>, <span class="math inline">\(t(38) = -6.72\)</span>, <span class="math inline">\(p &lt; .001\)</span>, <span class="math inline">\(R^2 = 0.54\)</span>.</p>
</blockquote>
</section>
<section id="consider-both-significance-and-effect-size" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="consider-both-significance-and-effect-size"><span class="header-section-number">9.5</span> Consider both significance and effect size</h2>
<p>As with all our tests, our significance test isn’t the whole picture. In addition to testing our slope (is <span class="math inline">\(\beta_1\)</span> significantly different from 0?), we also consider <span class="math inline">\(R^2\)</span>, which is regression’s <strong>effect size</strong>.</p>
<p>The two don’t move together the way intuition suggests.</p>
<p>A <strong>very large sample</strong>, the kind common in remote sensing and other big-data environmental work, can make a trivial effect statistically significant: more observations shrink the standard error until almost any nonzero slope clears <span class="math inline">\(p&lt;.05\)</span>, no matter how little variance it explains.</p>
<p>A <strong>small sample</strong> tends to fail the opposite way, missing a real, sizeable effect because the standard error is too large for it to reach significance.</p>
<p><span class="math inline">\(R^2\)</span> is what tells you how much of the variation is actually being explained.</p>
<p>Neither <span class="math inline">\(p\)</span> alone nor <span class="math inline">\(R^2\)</span> alone tells the whole story, so we must report both.</p>
<p><a href="#fig-10regeffectpanels">Figure&nbsp;<span>9.4</span></a> shows all three combinations this can produce: a strong relationship with a non-significant slope (underpowered), a weak relationship with a significant slope (a large sample), and a relationship that is both strong and significant.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10regeffectpanels" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10regeffectpanels-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Three scatter plots with fitted lines. The left panel shows a steep, tight relationship with few points and a non-significant p-value. The middle panel shows a nearly flat, scattered relationship with many points and a significant p-value. The right panel shows a steep, tight relationship with many points and a significant p-value."></p>
<figcaption class="figure-caption">Figure&nbsp;9.4: R-squared and the slope’s p-value can disagree. Left: a strong relationship (high R-squared) that isn’t statistically significant. Middle: a weak relationship (low R-squared) that is significant anyway. Right: strong and significant together.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>How big is a “good” <span class="math inline">\(R^2\)</span>?</strong> It depends on the field. In studies of human behavior, where dozens of unmeasured factors shape any outcome, an <span class="math inline">\(R^2\)</span> of 0.20 is a genuinely strong result. Environmental systems tend toward more direct physical relationships, so 0.5-0.8 for a well-chosen single predictor isn’t unusual. An <span class="math inline">\(R^2\)</span> that looks <em>too</em> good, say 0.98, from one predictor in a noisy field system, is itself worth a second look: it’s more often a sign of a setup problem than something to celebrate.</p>
</div>
</div>
</section>
<section id="checking-assumptions" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="checking-assumptions"><span class="header-section-number">9.6</span> Checking assumptions</h2>
<p>Simple linear regression assumes:</p>
<ul>
<li><p><strong>Linearity</strong>: the true relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is a straight line.</p></li>
<li><p><strong>Constant variance (homoscedasticity)</strong>: the spread of residuals is roughly the same across the whole range of <span class="math inline">\(X\)</span>.</p></li>
<li><p><strong>Normality of residuals</strong>: the residuals are approximately normally distributed.</p></li>
</ul>
<section id="sometimes-the-truth-isnt-a-line-at-all" class="level3" data-number="9.6.1">
<h3 data-number="9.6.1" class="anchored" data-anchor-id="sometimes-the-truth-isnt-a-line-at-all"><span class="header-section-number">9.6.1</span> Sometimes the truth isn’t a line at all</h3>
<blockquote class="blockquote">
<p>You can do linear regression without thinking about whether the phenomenon you’re modeling is actually close to linear. But you shouldn’t.<br>
Jordan Ellenberg, <em>How Not to Be Wrong</em></p>
</blockquote>
<p>A straight line is not guaranteed to be the right shape for your data, and the two assumptions above have two different failure signatures on this one plot: a curve means linearity is violated, a funnel shape means constant variance is violated. The most useful diagnostic for catching either is a residuals-versus-fitted plot:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10regresid" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10regresid-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;9.5: Residuals versus fitted values for the stream temperature model. A random scatter around zero, with no funnel shape or curve, supports linearity and constant variance.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-10regresid">Figure&nbsp;<span>9.5</span></a>, for our stream temperature data, shows what we want to see: residuals scattered evenly above and below zero, with no curve (which would suggest the true relationship isn’t linear) and no funnel shape (which would suggest variance changes systematically across the range of <span class="math inline">\(X\)</span>).</p>
<p>Let’s try checking residuals for a different set of data, this time on avian influenza cases over time.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10outbreakfit" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10outbreakfit-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Scatter plot of new cases per day against day of outbreak, with a fitted straight regression line. Points curve gently above and below the line."></p>
<figcaption class="figure-caption">Figure&nbsp;9.6: New avian influenza cases per day, days 1-14 of an outbreak, with a fitted straight line.</figcaption>
</figure>
</div>
</div>
</div>
<p>A straight line fit to these 14 days gives <span class="math inline">\(R^2 = 0.81\)</span> and <span class="math inline">\(p &lt; .001\)</span>, which by the benchmark from a couple pages back looks like a solid, significant fit for a field system. Nothing about those numbers alone raises a flag.</p>
<p><strong>Check it properly.</strong> The residuals-versus-fitted plot tells a different story than the <span class="math inline">\(R^2\)</span> and slope test did.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10outbreakresid" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10outbreakresid-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Residuals plotted against fitted values. The residuals form a clear U-shaped curve: negative in the middle, positive at both low and high fitted values, rather than scattering randomly around zero."></p>
<figcaption class="figure-caption">Figure&nbsp;9.7: Residuals versus fitted values for the linear outbreak model. A clear U-shape, not random scatter, is the signature of a nonlinear relationship forced into a straight line.</figcaption>
</figure>
</div>
</div>
</div>
<p>That U-shape is unambiguous: the line underpredicts early and late in the outbreak and overpredicts in the middle, exactly what you’d see forcing a straight line through a curve.</p>
<p>If a residual plot curves rather than scattering randomly, that’s the model telling you a straight line is the wrong tool.</p>
<p>Fixes typically include:</p>
<ul>
<li>a different model (often adding a polynomial term)</li>
<li>a transformation, re-expressing a variable on a different scale so a straight line fits it (log-transforming a variable that grows multiplicatively, like the outbreak data below, is the most common case)</li>
<li>or a nonlinear model entirely, beyond what this course covers</li>
</ul>
</section>
<section id="checking-normality" class="level3" data-number="9.6.2">
<h3 data-number="9.6.2" class="anchored" data-anchor-id="checking-normality"><span class="header-section-number">9.6.2</span> Checking normality</h3>
<p>For normality, we check the residuals two ways: visually, with a <strong>Q-Q plot</strong>, and formally, with the <strong>Shapiro-Wilk test</strong>.</p>
<p>A Q-Q plot sorts the residuals and compares them to where a perfectly normal distribution would place values at the same percentiles. If the residuals are normal, the points fall close to the diagonal line; a systematic curve or S-shape means they don’t.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10regqq" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10regqq-1.png" class="img-fluid figure-img" style="width:75.0%" alt="A normal quantile-quantile plot of the residuals. The points fall close to the diagonal reference line, showing no strong departure from normality."></p>
<figcaption class="figure-caption">Figure&nbsp;9.8: Normal Q-Q plot of the stream temperature model’s residuals. Points close to the diagonal support normality.</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-10regqq">Figure&nbsp;<span>9.8</span></a> looks close to straight, consistent with normal residuals. Shapiro-Wilk asks the same question formally: <span class="math inline">\(H_0\)</span> is that the residuals come from a normal distribution, so a small <span class="math inline">\(p\)</span>-value is the evidence against normality.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Shapiro-Wilk test on the regression residuals</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Statistic</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">0.987</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The residuals don’t depart from normality here (<span class="math inline">\(p = 0.987\)</span>). As with any formal normality test, treat this as one piece of evidence alongside the Q-Q plot and residual plot, not a strict gate. Shapiro-Wilk has the least power to detect real departures exactly when the sample is small, which is exactly when the visual checks matter most.</p>
<p>Now apply the same two normality checks to the avian influenza model, the one we already know is badly nonlinear.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10outbreakqq" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10outbreakqq-1.png" class="img-fluid figure-img" style="width:75.0%" alt="A normal quantile-quantile plot of the residuals. The points fall close to the diagonal reference line, showing no strong departure from normality."></p>
<figcaption class="figure-caption">Figure&nbsp;9.9: Normal Q-Q plot of the outbreak model’s residuals. They fall close to the diagonal, so this diagnostic alone would not have flagged the problem.</figcaption>
</figure>
</div>
</div>
</div>
<p>The Q-Q plot looks close to straight, and Shapiro-Wilk agrees (<span class="math inline">\(p = 0.060\)</span>, not significant). Both checks pass on a model we already know is the wrong shape. That is because they check <strong>normality of the residuals</strong>, which is a different assumption than linearity, and a model can badly violate linearity while its residuals still look roughly normal.</p>
</section>
</section>
<section id="using-the-model-prediction" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="using-the-model-prediction"><span class="header-section-number">9.7</span> Using the model: prediction</h2>
<p>Once we’ve confirmed a real linear relationship, the fitted equation lets us predict DO at any stream temperature. Plugging temperature into the fitted line directly gives the prediction: at 20°C,</p>
<p><span class="math display">\[\widehat{DO} = b_0 + b_1(20) = 13.4 + (-0.27)(20) = 7.98\]</span></p>
<p>R gives the same number, along with a confidence interval:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Predicted dissolved oxygen at 20°C, with 95% confidence interval</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Stream temperature</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Predicted</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">20</td>
<td style="text-align: right;">7.98</td>
<td style="text-align: right;">7.59</td>
<td style="text-align: right;">8.37</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>At 20°C, the model predicts DO of 7.98 mg/L, with a 95% confidence interval from 7.59 to 8.37. Notice that 20°C falls inside our sampled range of 10 to 24°C, this is interpolation, and it’s what regression is good for. Predicting DO at, say, 35°C would be extrapolation: nothing in the data tells us the relationship stays linear (or even stays a relationship at all) beyond the range we actually observed, and the further outside that range, the less trustworthy the prediction. <a href="#fig-10regextrap">Figure&nbsp;<span>9.10</span></a> shows both zones on the same line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10regextrap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10regextrap-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Scatter plot of dissolved oxygen against stream temperature. A solid blue line covers the observed range from 10 to 24 degrees C, and a dashed red line extends the same fitted trend below and above that range."></p>
<figcaption class="figure-caption">Figure&nbsp;9.10: The fitted line within the observed temperature range (solid blue, interpolation) and extended beyond it in both directions (dashed red, extrapolation). Dotted grey lines mark the edges of the observed data, 10 to 24°C.</figcaption>
</figure>
</div>
</div>
</div>
<p>Regression is used for extrapolation all the time, and often reasonably: a well-understood physical process can justify projecting a line beyond the data you happened to collect. Extrapolating a straight line is only safe if the true relationship actually stays straight past the range you observed.</p>
<p>The problem is that a narrow window of data can’t tell you which kind of curve you’re actually on. <a href="#fig-10curveshapes">Figure&nbsp;<span>9.11</span></a> shows four very different relationships, exponential growth, a sigmoid, a hump-shaped curve, and a truly straight line, each with the same short observed window highlighted in blue. The fitted line (dashed red) extrapolated based on the observed data is also exactly the same for all 4 panels, it just looks different because the y-axis scales are different. Once you see the full curve (grey), you can see how badly linear extrapolation beyond the range of observed data would perform in each case.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10curveshapes" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10curveshapes-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Four panels: exponential, sigmoid, hump-shaped, and linear curves. In each, a short initial segment is highlighted in blue and looks nearly straight. A dashed red line extends that local trend across the full range. The full grey curve shows the true shape, which diverges sharply from the dashed line except in the linear panel, where the two coincide."></p>
<figcaption class="figure-caption">Figure&nbsp;9.11: Four different true relationships that all look locally linear over a short observed window (blue). A line fit to that window (dashed red) extrapolates identically well in each panel, but only the genuinely linear case stays correct once the full curve (grey) is revealed.</figcaption>
</figure>
</div>
</div>
</div>
<p>To make this a bit more concrete, suppose officials use the linear fitted line from our example above to project avian influenza cases at day 30, well past the 14 days observed.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10outbreakextrap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09-Regression_files/figure-html/fig-10outbreakextrap-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Line graph of cases against day of outbreak from day 1 to day 30. A solid blue line and observed points cover days 1 through 14. A dashed red line continues the same linear trend from day 14 to day 30, staying low. A dotted grey curve shows the true exponential trajectory, which rises steeply and dramatically outpaces the dashed line by day 30."></p>
<figcaption class="figure-caption">Figure&nbsp;9.12: The linear fit extended (dashed) past the observed range, against the true exponential trajectory (dotted grey). The straight line badly underestimates how large the outbreak actually becomes.</figcaption>
</figure>
</div>
</div>
</div>
<p>The linear model predicts about 530 cases on day 30. If the outbreak is exponential, the actual count is closer to 26,682, roughly 50 times higher.</p>
<p>Planning surveillance and containment staffing off the linear forecast would leave the response badly under-resourced for the outbreak that actually arrives. A straight line can look fine over a short early window and still be very wrong about where that window leads.</p>
<p>What this calls for is a different model, not more data or a better-fit line. Fitting curves and transformations is beyond what this course covers, but recognizing when you need one, by plotting the data and the residuals, is not.</p>
</section>
<section id="chapter-summary" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">9.8</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> Regression is where description becomes inference. Chapter 2 drew a best-fit line through a scatterplot; this chapter turns that line into something you can test, quantify, and make predictions from.</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>The slope is a hypothesis.</strong> <span class="math inline">\(H_0: \beta_1 = 0\)</span> says there is no linear relationship. Testing it uses a <span class="math inline">\(t\)</span>-test on the slope divided by its standard error, with <span class="math inline">\(df = n-2\)</span>, and it is mechanically identical to testing a correlation coefficient.</li>
<li><strong><span class="math inline">\(R^2\)</span> is the effect size.</strong> It partitions variance exactly as ANOVA does, reporting the proportion of variation in <span class="math inline">\(y\)</span> the line accounts for. A relationship can be real (<span class="math inline">\(p\)</span> small) and still explain very little, which is why you report both.</li>
<li><strong>Look at your data, then look at your residuals.</strong> The assumptions that must be met are linearity, constant variance, and roughly normal residuals. A residuals-versus-fitted plot catches violations a formal test can miss entirely, as the outbreak example showed.</li>
<li><strong>Predict inside your data; extrapolate beyond with caution.</strong> Interpolating within the observed range of <span class="math inline">\(x\)</span> is what regression is for. Extrapolating beyond it is sometimes justified, but only when you have good reason to believe the relationship stays the same shape past the range you observed.</li>
<li><strong>A good</strong> <span class="math inline">\(R^2\)</span> can still be the wrong model. The outbreak example fit a straight line to exponential growth and got <span class="math inline">\(R^2=0.82\)</span>, a residuals-versus-fitted plot that clearly curved, and an extrapolated forecast tens of thousands of cases short of reality. The residual plot catches this; a Q-Q plot, which checks a different assumption, does not.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08-ANOVA.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-FactorialANOVA.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>