<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>10&nbsp; Factorial ANOVA – Statistics for Environmental Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-ANCOVA.html" rel="next">
<link href="./09-Regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d3f7f8e73c8d287b30bcf59c2b563615.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="10&nbsp; Factorial ANOVA – Statistics for Environmental Science">
<meta property="og:description" content="">
<meta property="og:image" content="imgs/figures/fig-10designs-rendered.png">
<meta property="og:site_name" content="Statistics for Environmental Science">
<meta property="og:image:alt" content="A two-by-two grid. Columns are labeled Acidic and Neutral; rows are labeled Low Water and High Water. Each of the four cells is marked DV, indicating that the dependent variable is measured in every combination.">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-FactorialANOVA.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for Environmental Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Inference and Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Errors, Power, and Effect Size</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#factorial-basics" id="toc-factorial-basics" class="nav-link active" data-scroll-target="#factorial-basics"><span class="header-section-number">10.1</span> Factorial basics</a>
  <ul class="collapse">
  <li><a href="#x2-designs" id="toc-x2-designs" class="nav-link" data-scroll-target="#x2-designs"><span class="header-section-number">10.1.1</span> 2x2 Designs</a></li>
  <li><a href="#factorial-notation" id="toc-factorial-notation" class="nav-link" data-scroll-target="#factorial-notation"><span class="header-section-number">10.1.2</span> Factorial Notation</a></li>
  </ul></li>
  <li><a href="#pollution-flow-and-stream-life" id="toc-pollution-flow-and-stream-life" class="nav-link" data-scroll-target="#pollution-flow-and-stream-life"><span class="header-section-number">10.2</span> Pollution, flow, and stream life</a></li>
  <li><a href="#why-factorial-designs-matter" id="toc-why-factorial-designs-matter" class="nav-link" data-scroll-target="#why-factorial-designs-matter"><span class="header-section-number">10.3</span> Why factorial designs matter</a>
  <ul class="collapse">
  <li><a href="#main-effects-and-interactions" id="toc-main-effects-and-interactions" class="nav-link" data-scroll-target="#main-effects-and-interactions"><span class="header-section-number">10.3.1</span> Main effects and interactions</a></li>
  </ul></li>
  <li><a href="#what-a-2x2-actually-tests" id="toc-what-a-2x2-actually-tests" class="nav-link" data-scroll-target="#what-a-2x2-actually-tests"><span class="header-section-number">10.4</span> What a 2x2 actually tests</a>
  <ul class="collapse">
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses"><span class="header-section-number">10.4.1</span> Hypotheses</a></li>
  </ul></li>
  <li><a href="#what-the-anova-is-really-comparing" id="toc-what-the-anova-is-really-comparing" class="nav-link" data-scroll-target="#what-the-anova-is-really-comparing"><span class="header-section-number">10.5</span> What the ANOVA is really comparing</a></li>
  <li><a href="#computing-a-factorial-anova-by-hand" id="toc-computing-a-factorial-anova-by-hand" class="nav-link" data-scroll-target="#computing-a-factorial-anova-by-hand"><span class="header-section-number">10.6</span> Computing a factorial ANOVA by hand</a>
  <ul class="collapse">
  <li><a href="#ss-total" id="toc-ss-total" class="nav-link" data-scroll-target="#ss-total"><span class="header-section-number">10.6.1</span> SS Total</a></li>
  <li><a href="#ss-pollution" id="toc-ss-pollution" class="nav-link" data-scroll-target="#ss-pollution"><span class="header-section-number">10.6.2</span> SS Pollution</a></li>
  <li><a href="#ss-flow" id="toc-ss-flow" class="nav-link" data-scroll-target="#ss-flow"><span class="header-section-number">10.6.3</span> SS Flow</a></li>
  <li><a href="#ss-interaction" id="toc-ss-interaction" class="nav-link" data-scroll-target="#ss-interaction"><span class="header-section-number">10.6.4</span> SS Interaction</a></li>
  <li><a href="#ss-error" id="toc-ss-error" class="nav-link" data-scroll-target="#ss-error"><span class="header-section-number">10.6.5</span> SS Error</a></li>
  <li><a href="#check-your-work" id="toc-check-your-work" class="nav-link" data-scroll-target="#check-your-work"><span class="header-section-number">10.6.6</span> Check your work</a></li>
  <li><a href="#effect-size-in-a-factorial-design" id="toc-effect-size-in-a-factorial-design" class="nav-link" data-scroll-target="#effect-size-in-a-factorial-design"><span class="header-section-number">10.6.7</span> Effect size in a factorial design</a></li>
  </ul></li>
  <li><a href="#reading-patterns-in-a-2x2" id="toc-reading-patterns-in-a-2x2" class="nav-link" data-scroll-target="#reading-patterns-in-a-2x2"><span class="header-section-number">10.7</span> Reading patterns in a 2x2</a></li>
  <li><a href="#interpreting-main-effects-and-interactions" id="toc-interpreting-main-effects-and-interactions" class="nav-link" data-scroll-target="#interpreting-main-effects-and-interactions"><span class="header-section-number">10.8</span> Interpreting main effects and interactions</a>
  <ul class="collapse">
  <li><a href="#a-consistent-main-effect-and-an-interaction" id="toc-a-consistent-main-effect-and-an-interaction" class="nav-link" data-scroll-target="#a-consistent-main-effect-and-an-interaction"><span class="header-section-number">10.8.1</span> A consistent main effect and an interaction</a></li>
  <li><a href="#an-averaged-main-effect-thats-actually-driven-by-an-interaction" id="toc-an-averaged-main-effect-thats-actually-driven-by-an-interaction" class="nav-link" data-scroll-target="#an-averaged-main-effect-thats-actually-driven-by-an-interaction"><span class="header-section-number">10.8.2</span> An “averaged” main effect that’s actually driven by an interaction</a></li>
  </ul></li>
  <li><a href="#more-complicated-designs" id="toc-more-complicated-designs" class="nav-link" data-scroll-target="#more-complicated-designs"><span class="header-section-number">10.9</span> More complicated designs</a>
  <ul class="collapse">
  <li><a href="#x2-design" id="toc-x2-design" class="nav-link" data-scroll-target="#x2-design"><span class="header-section-number">10.9.1</span> 3x2 design</a></li>
  </ul></li>
  <li><a href="#designs-beyond-this-course" id="toc-designs-beyond-this-course" class="nav-link" data-scroll-target="#designs-beyond-this-course"><span class="header-section-number">10.10</span> Designs Beyond This Course</a>
  <ul class="collapse">
  <li><a href="#three-factor-designs" id="toc-three-factor-designs" class="nav-link" data-scroll-target="#three-factor-designs"><span class="header-section-number">10.10.1</span> 2×2×2 (Three-Factor) Designs</a></li>
  <li><a href="#mixed-designs" id="toc-mixed-designs" class="nav-link" data-scroll-target="#mixed-designs"><span class="header-section-number">10.10.2</span> Mixed Designs</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">10.11</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/10-FactorialANOVA.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">August 19, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<p>In science, outcomes rarely depend on just one thing. Climate, soil type, and water availability all act together to influence ecosystems in ways a single-factor design can’t capture. <em>Factorial designs</em> let us study several factors, and how they interact with each other, at once.</p>
<p>This chapter covers both halves of that. First, <strong>how to compute</strong> a factorial ANOVA, including a full by-hand walkthrough of the sums-of-squares arithmetic. Second, <strong>how to interpret</strong> the result. This can be tricky with multiple factors. When an <em>interaction</em> is present, it changes what every other number in your results table means.</p>
<section id="factorial-basics" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="factorial-basics"><span class="header-section-number">10.1</span> Factorial basics</h2>
<p>Imagine investigating the growth rate of a plant species, with independent variables like soil pH or water variability. Each added IV multiplies the number of conditions you can observe, and with it, the questions you can ask about how those factors work together. Consider the following example:</p>
<ol type="1">
<li><strong>1 IV (with two levels)</strong></li>
</ol>
<p><em>How does soil pH affect plant growth?</em></p>
<ul>
<li>Independent Variable: Soil pH (Acidic vs.&nbsp;Neutral)</li>
</ul>
<p>We have one IV (soil pH), with two levels (Acidic vs.&nbsp;Neutral). A <em>t-test</em> is appropriate here, since we are dealing with just two levels of our independent variable.</p>
<ol start="2" type="1">
<li><strong>1 IV (three levels):</strong></li>
</ol>
<p><em>How does varying water availability impact plant growth?</em></p>
<ul>
<li>Independent Variable: Water Availability (Low, Medium, High)</li>
</ul>
<p>Our single IV (water availability) has three levels (Low, Medium, High). You can’t run a t-test anymore. An ANOVA is appropriate here, given the variable has more than two levels.</p>
<ol start="3" type="1">
<li><strong>2 IVs: IV1 (two levels), IV2 (two levels)</strong></li>
</ol>
<p><em>How do soil pH and water availability together affect plant growth?</em></p>
<ul>
<li>IV1 (Soil pH: Acidic vs.&nbsp;Neutral);</li>
<li>IV2 (Water Availability: Low vs.&nbsp;High)</li>
</ul>
<p>Now we have two IVs, soil pH and water availability, each with two levels. This is called a <strong>factorial</strong> design, and it’s easier to see what that means visually than to define it in words first. Take a look at <a href="#fig-10designs" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>.</p>
<section id="x2-designs" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="x2-designs"><span class="header-section-number">10.1.1</span> 2x2 Designs</h3>
<p><a href="#fig-10designs" class="quarto-xref">Figure&nbsp;<span>10.1</span></a> lays out our soil pH and water availability example as a grid.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10designs" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A two-by-two grid. Columns are labeled Acidic and Neutral; rows are labeled Low Water and High Water. Each of the four cells is marked DV, indicating that the dependent variable is measured in every combination.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10designs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imgs/figures/fig-10designs-rendered.png" class="img-fluid figure-img" style="width:75.0%" alt="A two-by-two grid. Columns are labeled Acidic and Neutral; rows are labeled Low Water and High Water. Each of the four cells is marked DV, indicating that the dependent variable is measured in every combination.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10designs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: Structure of a 2x2 factorial design: soil pH crossed with water availability.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Each combination of soil type and water availability creates a unique environment for the plants, giving four distinct scenarios to measure growth rates: 2 IVs, each with 2 levels, for 2x2 = 4 conditions total. The notation directly tells you the number of conditions.</p>
</section>
<section id="factorial-notation" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="factorial-notation"><span class="header-section-number">10.1.2</span> Factorial Notation</h3>
<p>Anytime <strong>all of the levels</strong> of each IV in a design are fully crossed, so that they all occur for each level of every other IV, we can say the design is a <strong>fully factorial</strong> design.</p>
<p>The notation system indicates the structure of the factorial design. Each IV gets a number representing its levels. Here are a few examples:</p>
<ul>
<li><p>2x2: Two IVs, each with two levels (yields four unique conditions).</p></li>
<li><p>2x3: Two IVs, with the first having two levels and the second three, (yields six unique conditions).</p></li>
<li><p>3x2: Similar to the 2x3, but the first IV has three levels, and the second has two, also giving us six unique conditions.</p></li>
<li><p>4x4: Two IVs, each with four levels, resulting in sixteen conditions.</p></li>
</ul>
</section>
</section>
<section id="pollution-flow-and-stream-life" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="pollution-flow-and-stream-life"><span class="header-section-number">10.2</span> Pollution, flow, and stream life</h2>
<p>The rest of this chapter uses one example throughout, so it’s worth setting it up carefully before any arithmetic starts.</p>
<p><strong>The question.</strong> Streams are affected by pollution, but also by how fast the water moves. Fast-moving water flushes contaminants downstream and re-oxygenates the channel; slow water lets them sit. So pollution might do more damage in a sluggish stream than a fast one. But damage to what? We need to operationalize stream health.</p>
<p><strong>The dependent variable</strong> is <strong>macroinvertebrate species count</strong>: how many distinct kinds of aquatic insects, snails, worms, and crustaceans live in a stream. This is a standard measure of stream health. These animals sit in the middle of the food web, many are pollution-sensitive, and they can’t flee a degraded stream the way fish can. More species present means a healthier stream.</p>
<p><strong>The design.</strong> We run an experiment in artificial stream channels, each assigned one pollution condition and one flow rate. <a href="#fig-10design" class="quarto-xref">Figure&nbsp;<span>10.2</span></a> summarizes it.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10design" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Study design schematic. IV: pollution crossed with flow rate, both categorical. Two boxes for pollution and two for flow rate, joined by a multiplication sign, equalling a four-cell grid labelled NP times LF, NP times HF, P times LF and P times HF. DV: macroinvertebrate species count.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10design-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-10design-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Study design schematic. IV: pollution crossed with flow rate, both categorical. Two boxes for pollution and two for flow rate, joined by a multiplication sign, equalling a four-cell grid labelled NP times LF, NP times HF, P times LF and P times HF. DV: macroinvertebrate species count.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10design-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.2: A fully crossed factorial design, read as arithmetic: two pollution levels times two flow levels gives four conditions. Every combination is measured, which is what ‘fully crossed’ means.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Two IVs, two levels each, so you should already be able to name this design: it’s a 2x2. Reading the schematic left to right also shows why the notation works the way it does. Crossing two levels with two levels <em>is</em> the multiplication that gives four conditions, and “fully crossed” simply means no cell is left empty. <a href="#fig-10setup" class="quarto-xref">Figure&nbsp;<span>10.3</span></a> shows those same four conditions as a grid, with what gets measured in each.</p>
<p>That four-cell grid resembles the chi-square table from Chapter 7, and the difference between them is worth pinning down. There, the cells held <strong>counts</strong> of stream sites that already had a given land use and <em>E. coli</em> level; nobody put them there. Here, the cells are <strong>conditions we assign channels to</strong>, and within each one we then measure something else entirely, the species count. Same shape, opposite direction: one counts where units landed, the other measures an outcome where we placed them.</p>
<p><strong>Predictions.</strong> No pollution plus high flow should support the most species; pollution plus low flow should support the fewest. The other two combinations are the interesting ones, and a one-factor study could never distinguish them: does pollution matter only when flow is low, with fast water washing its effect away entirely? Or does pollution hurt a stream no matter how fast the water moves? That’s exactly what an interaction test in a factorial experiment can tell us.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10setup" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A two-by-two grid. Columns are labeled No Pollution and Pollution; rows are labeled Low Flow and High Flow. Each of the four cells notes five stream channels and is labelled with its pollution condition and flow rate.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10setup-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="imgs/figures/fig-10setup-rendered.png" class="img-fluid figure-img" style="width:90.0%" alt="A two-by-two grid. Columns are labeled No Pollution and Pollution; rows are labeled Low Flow and High Flow. Each of the four cells notes five stream channels and is labelled with its pollution condition and flow rate.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10setup-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.3: The 2x2 experimental design. Two pollution conditions crossed with two flow rates gives four stream-channel conditions. In every condition we count how many macroinvertebrate species are present, and each cell is labelled with its pollution condition and flow rate.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="why-factorial-designs-matter" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="why-factorial-designs-matter"><span class="header-section-number">10.3</span> Why factorial designs matter</h2>
<p>Factorial designs let us ask more nuanced questions than a single-factor study can. Suppose we ignored flow entirely and just compared polluted to unpolluted channels. That gives us a <strong>Pollution effect</strong>: the difference in species count between polluted and unpolluted water, shown in <a href="#fig-10biodiversityeffect" class="quarto-xref">Figure&nbsp;<span>10.4</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10biodiversityeffect" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10biodiversityeffect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-10biodiversityeffect-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10biodiversityeffect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.4: Macroinvertebrate species count under pollution vs.&nbsp;no pollution, ignoring flow.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A factorial design lets us ask the follow-up question a one-factor design can’t: does the Pollution effect itself depend on flow? With flow rate added as a second IV, there are four condition means instead of two, so we can compare the Pollution effect <em>within</em> each flow condition, shown in <a href="#fig-10flowB" class="quarto-xref">Figure&nbsp;<span>10.5</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10flowB" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10flowB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-10flowB-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10flowB-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.5: The Pollution effect (the gap between the two bars within a flow condition) is larger under low flow than high flow.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Under low flow, species count drops sharply with pollution (35 to 15, a difference of 20). Under high flow, the drop is much smaller (30 to 25, a difference of 5). The Pollution effect isn’t constant: it depends on flow rate, exactly as we suspected it might.</p>
<p>That’s the core payoff of a factorial design: it tells you what changes the size of an effect, not only whether the effect exists.</p>
<section id="main-effects-and-interactions" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="main-effects-and-interactions"><span class="header-section-number">10.3.1</span> Main effects and interactions</h3>
<p>Those two things, <strong>main effects</strong> and <strong>interactions</strong>, are what any factorial design gives you. How many of each depends on the number of IVs.</p>
<p>A <strong>main effect</strong> is the average difference associated with a single IV, one per IV. A 2x2 design has two IVs, so two main effects: one for Pollution and one for Flow. A 2x2x2 design has three main effects, one per IV; a 3x3x3 design also has three, since the number of main effects tracks the number of IVs, not their levels.</p>
<p>An <strong>interaction</strong> occurs when the effect of one IV depends on the level of another, which is exactly what <a href="#fig-10flowB" class="quarto-xref">Figure&nbsp;<span>10.5</span></a> shows: the size of the Pollution effect changed with Flow.</p>
<p>Equivalently, and this framing is worth holding onto because it’s what the arithmetic actually computes, an interaction is a <strong>difference between differences</strong>. The Pollution effect is a difference (polluted minus unpolluted). If that difference itself changes across Flow conditions, that’s an interaction.</p>
<p>The number of possible interactions scales with the number of IVs. A 2x2 design has exactly one interaction, the combined effect of the two IVs. A design with three IVs (A, B, C) has three two-way interactions (AB, AC, BC) and one three-way interaction (ABC).</p>
</section>
</section>
<section id="what-a-2x2-actually-tests" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="what-a-2x2-actually-tests"><span class="header-section-number">10.4</span> What a 2x2 actually tests</h2>
<p>Before computing anything, it’s worth being precise about what the three tests are, because a two-way ANOVA tests <strong>three effects</strong> and therefore has <strong>three null hypotheses</strong>:</p>
<ol type="1">
<li>a main effect of pollution,</li>
<li>a main effect of flow, and</li>
<li>a pollution × flow interaction.</li>
</ol>
<p>We can represent the four combinations of conditions and their mean species counts as:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Pollution</th>
<th>Flow</th>
<th>Mean species count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Pollution</td>
<td>Low Flow</td>
<td><span class="math inline">\(\mu_{\text{NoPoll,Low}}\)</span></td>
</tr>
<tr class="even">
<td>No Pollution</td>
<td>High Flow</td>
<td><span class="math inline">\(\mu_{\text{NoPoll,High}}\)</span></td>
</tr>
<tr class="odd">
<td>Pollution</td>
<td>Low Flow</td>
<td><span class="math inline">\(\mu_{\text{Poll,Low}}\)</span></td>
</tr>
<tr class="even">
<td>Pollution</td>
<td>High Flow</td>
<td><span class="math inline">\(\mu_{\text{Poll,High}}\)</span></td>
</tr>
</tbody>
</table>
<section id="hypotheses" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="hypotheses"><span class="header-section-number">10.4.1</span> Hypotheses</h3>
<p><strong>Main effect of pollution</strong></p>
<ul>
<li><strong>Null (</strong><span class="math inline">\(H_0\)</span>): There is no effect of pollution on mean species count.</li>
<li><strong>Alternative (</strong><span class="math inline">\(H_1\)</span>): Pollution affects mean species count.</li>
</ul>
<p><strong>Main effect of flow</strong></p>
<ul>
<li><strong>Null (</strong><span class="math inline">\(H_0\)</span>): There is no effect of flow rate on mean species count.</li>
<li><strong>Alternative (</strong><span class="math inline">\(H_1\)</span>): Flow rate affects mean species count.</li>
</ul>
<p><strong>Pollution × flow interaction</strong></p>
<ul>
<li><strong>Null (</strong><span class="math inline">\(H_0\)</span>): The effect of pollution is the same at both flow rates. <em>(In symbols:</em> <span class="math inline">\((\mu_{\text{NoPoll,Low}}-\mu_{\text{Poll,Low}})=(\mu_{\text{NoPoll,High}}-\mu_{\text{Poll,High}})\)</span>.)</li>
<li><strong>Alternative (</strong><span class="math inline">\(H_1\)</span>): The effect of pollution differs across flow rates.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Plain English:</strong> Under the interaction null, the gap between polluted and unpolluted channels is the same whether the water is moving fast or slow. If that gap changes, for example if pollution does far more damage under low flow, you’ve found an interaction.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled" title="Note: General form">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: General form
</div>
</div>
<div class="callout-body-container callout-body">
<p>You’ll sometimes see this written in abstract terms, with “Factor A” and “Factor B.” For example: <span class="math inline">\(H_0: (\mu_{A1,B1}-\mu_{A2,B1})=(\mu_{A1,B2}-\mu_{A2,B2})\)</span>. It’s the same logic: just replace A and B with your own variables.</p>
</div>
</div>
</section>
</section>
<section id="what-the-anova-is-really-comparing" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="what-the-anova-is-really-comparing"><span class="header-section-number">10.5</span> What the ANOVA is really comparing</h2>
<p>Recall from earlier: an interaction is a <strong>difference between differences</strong>. Here’s that idea with real numbers, using the four condition means directly, before we touch a single sum of squares.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Pollution effect, Low Flow</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pollution effect, High Flow</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference of differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">3.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Under low flow, the Pollution effect (no-pollution mean minus pollution mean) is 6. Under high flow, it’s 2.6. Those two numbers aren’t the same, so the Pollution effect isn’t constant across Flow conditions, which is exactly what an interaction means. The gap between them, 3.4, is a first, informal look at the interaction itself. Whether a gap that size is more than chance would produce is what the formal test below settles.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Warning: If your design were repeated measures instead">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Warning: If your design were repeated measures instead
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here each condition uses a different set of stream channels, a <strong>between-subjects</strong> design. Had the <em>same</em> channels been measured under all four conditions, this identical interaction test could be computed as a paired <span class="math inline">\(t\)</span>-test on difference scores, agreeing exactly with a repeated-measures ANOVA (<span class="math inline">\(t^2=F\)</span>).</p>
</div>
</div>
</section>
<section id="computing-a-factorial-anova-by-hand" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="computing-a-factorial-anova-by-hand"><span class="header-section-number">10.6</span> Computing a factorial ANOVA by hand</h2>
<p>In our <strong>between-subjects</strong> 2x2 design, different stream channels appear in each condition: 5 channels per condition, 20 channels total, no repeats. The logic is the same as the one-way ANOVA in the last chapter: partition the total variance into parts. For a 2x2 design, there’s now one more part, the interaction:</p>
<p><span class="math display">\[SS_\text{Total} = SS_\text{Effect IV1} + SS_\text{Effect IV2} + SS_\text{Effect IV1xIV2} + SS_\text{Error}\]</span></p>
<p>The tables below build up each piece the same way the one-way ANOVA chapter did: one row per channel, showing what that channel’s score gets replaced with, its distance from the grand mean, and that distance squared.</p>
<section id="ss-total" class="level3" data-number="10.6.1">
<h3 data-number="10.6.1" class="anchored" data-anchor-id="ss-total"><span class="header-section-number">10.6.1</span> SS Total</h3>
<p><span class="math inline">\(SS_\text{Total}\)</span> captures all of the variation in the data: the difference between each channel’s score and the grand mean, squared and summed. The table shows the first few channels and the last, since the pattern is the same all the way down.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Pollution</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Flow</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Species</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Diff</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Diff Squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">1.05</td>
<td style="text-align: left;">1.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">-0.95</td>
<td style="text-align: left;">0.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">2.05</td>
<td style="text-align: left;">4.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pollution</td>
<td style="text-align: left;">High Flow</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">3.05</td>
<td style="text-align: left;">9.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">179</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">242.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">8.95</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean of all 20 scores is the <strong>grand mean</strong>, 8.95. The <code>Diff</code> column holds every channel’s distance from it; <code>Diff Squared</code> squares those distances so they don’t cancel (the same reason we squared deviations for the one-way ANOVA). Summing the squared column gives <span class="math inline">\(SS_\text{Total} = 242.9\)</span>.</p>
</section>
<section id="ss-pollution" class="level3" data-number="10.6.2">
<h3 data-number="10.6.2" class="anchored" data-anchor-id="ss-pollution"><span class="header-section-number">10.6.2</span> SS Pollution</h3>
<p><span class="math inline">\(SS_\text{Pollution}\)</span> isolates the variation caused by pollution condition alone: replace every score with its own pollution-condition mean, then find that mean’s distance from the grand mean.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Pollution</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Flow</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Species</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Group Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Diff</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Diff Squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">11.1</td>
<td style="text-align: left;">2.15</td>
<td style="text-align: left;">4.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">11.1</td>
<td style="text-align: left;">2.15</td>
<td style="text-align: left;">4.62</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">11.1</td>
<td style="text-align: left;">2.15</td>
<td style="text-align: left;">4.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pollution</td>
<td style="text-align: left;">High Flow</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">6.8</td>
<td style="text-align: left;">-2.15</td>
<td style="text-align: left;">4.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">179</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">92.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Every no-pollution channel is replaced by the no-pollution mean, 11.1; every pollution channel by the pollution mean, 6.8. Squaring and summing those means’ distances from the grand mean gives <span class="math inline">\(SS_\text{Pollution} = 92.4\)</span>: the variation explained by pollution condition alone.</p>
</section>
<section id="ss-flow" class="level3" data-number="10.6.3">
<h3 data-number="10.6.3" class="anchored" data-anchor-id="ss-flow"><span class="header-section-number">10.6.3</span> SS Flow</h3>
<p><span class="math inline">\(SS_\text{Flow}\)</span> works the same way, grouping by flow rate instead of pollution condition.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Pollution</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Flow</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Species</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Group Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Diff</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Diff Squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">6.6</td>
<td style="text-align: left;">-2.35</td>
<td style="text-align: left;">5.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">6.6</td>
<td style="text-align: left;">-2.35</td>
<td style="text-align: left;">5.52</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">6.6</td>
<td style="text-align: left;">-2.35</td>
<td style="text-align: left;">5.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pollution</td>
<td style="text-align: left;">High Flow</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">11.3</td>
<td style="text-align: left;">2.35</td>
<td style="text-align: left;">5.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">179</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">110.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Every low-flow channel is replaced by 6.6; every high-flow channel by 11.3. This gives <span class="math inline">\(SS_\text{Flow} = 110.4\)</span>.</p>
</section>
<section id="ss-interaction" class="level3" data-number="10.6.4">
<h3 data-number="10.6.4" class="anchored" data-anchor-id="ss-interaction"><span class="header-section-number">10.6.4</span> SS Interaction</h3>
<p>The interaction is the one genuinely new piece a factorial ANOVA adds. It asks: do the four individual condition means behave differently than the two main effects alone would predict?</p>
<p>Take the Low Flow condition: its own mean was 6.6. If pollution’s effect were the same regardless of flow, both pollution subgroups within Low Flow should also average close to that. They don’t: the no-pollution/low-flow mean is 9.6, well above it, and the pollution/low-flow mean is 3.6, well below it. That gap, variance the two main effects can’t explain on their own, is what the interaction captures.</p>
<p>To compute it, replace each score with its own condition mean, then subtract that channel’s pollution-group mean and flow-group mean, and add back the grand mean once (to avoid subtracting it twice):</p>
<p><span class="math display">\[\bar{x}_\text{condition} - \bar{x}_\text{Pollution group} - \bar{x}_\text{Flow group} + \bar{x}_\text{Grand mean}\]</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Pollution</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Flow</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Species</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Condition Mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Diff</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Diff Squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">9.6</td>
<td style="text-align: left;">0.85</td>
<td style="text-align: left;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">9.6</td>
<td style="text-align: left;">0.85</td>
<td style="text-align: left;">0.72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No Pollution</td>
<td style="text-align: left;">Low Flow</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">9.6</td>
<td style="text-align: left;">0.85</td>
<td style="text-align: left;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
<td style="text-align: left;">...</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pollution</td>
<td style="text-align: left;">High Flow</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">0.85</td>
<td style="text-align: left;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">179</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">14.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Squaring and summing gives <span class="math inline">\(SS_\text{Interaction} = 14.4\)</span>.</p>
</section>
<section id="ss-error" class="level3" data-number="10.6.5">
<h3 data-number="10.6.5" class="anchored" data-anchor-id="ss-error"><span class="header-section-number">10.6.5</span> SS Error</h3>
<p>The last piece follows by subtraction, since every other term in the identity is already known:</p>
<p><span class="math display">\[SS_\text{Error} = SS_\text{Total} - SS_\text{Pollution} - SS_\text{Flow} - SS_\text{Interaction}\]</span></p>
<p><span class="math display">\[SS_\text{Error} = 242.95 - 92.45 - 110.45 - 14.45 = 25.6\]</span></p>
</section>
<section id="check-your-work" class="level3" data-number="10.6.6">
<h3 data-number="10.6.6" class="anchored" data-anchor-id="check-your-work"><span class="header-section-number">10.6.6</span> Check your work</h3>
<p>Converting each <span class="math inline">\(SS\)</span> to an <span class="math inline">\(F\)</span>-value works exactly as it did for the one-way ANOVA: divide by <span class="math inline">\(df\)</span> to get <span class="math inline">\(MS\)</span>, then take the ratio of each effect’s <span class="math inline">\(MS\)</span> to <span class="math inline">\(MS_\text{Error}\)</span>. Instead of repeating that by hand, the check that matters here is that these hand-calculated <span class="math inline">\(SS\)</span> values match what R computes directly.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pollution</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">92.45</td>
<td style="text-align: right;">92.45</td>
<td style="text-align: right;">57.78125</td>
<td style="text-align: right;">0.0000011</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flow</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">110.45</td>
<td style="text-align: right;">110.45</td>
<td style="text-align: right;">69.03125</td>
<td style="text-align: right;">0.0000003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pollution:Flow</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.45</td>
<td style="text-align: right;">14.45</td>
<td style="text-align: right;">9.03125</td>
<td style="text-align: right;">0.0083879</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">25.60</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The <code>Sum Sq</code> column matches the hand-calculated values above: 92.45 for Pollution, 110.45 for Flow, 14.45 for the interaction, 25.6 for Error. All three effects are significant here, including the interaction we previewed informally a moment ago: the Pollution effect really is different at the two flow rates, not just by chance.</p>
</section>
<section id="effect-size-in-a-factorial-design" class="level3" data-number="10.6.7">
<h3 data-number="10.6.7" class="anchored" data-anchor-id="effect-size-in-a-factorial-design"><span class="header-section-number">10.6.7</span> Effect size in a factorial design</h3>
<p>The one-way ANOVA in Chapter 8 had one effect and so needed one effect size, <span class="math inline">\(\eta^2 = SS_\text{Between}/SS_\text{Total}\)</span>. A 2x2 runs three tests, so it needs three effect sizes, and the sums of squares we just computed by hand are all the ingredients required.</p>
<p>The direct extension keeps <span class="math inline">\(SS_\text{Total}\)</span> in the denominator for every effect:</p>
<p><span class="math display">\[
\eta^2 = \frac{SS_\text{Effect}}{SS_\text{Total}}
\]</span></p>
<p>Each effect then reports its share of <em>all</em> the variation in the study, so the three values plus error’s share add to 1. That is easy to interpret, but it has an awkward property: adding a second factor to a study inflates <span class="math inline">\(SS_\text{Total}\)</span>, which shrinks the <span class="math inline">\(\eta^2\)</span> of a factor whose behavior did not change at all. The same effect looks smaller purely because you studied something else alongside it.</p>
<p><strong>Partial eta-squared</strong> avoids that by setting the other factors’ variation aside instead of counting it:</p>
<p><span class="math display">\[
\eta_p^2 = \frac{SS_\text{Effect}}{SS_\text{Effect} + SS_\text{Error}}
\]</span></p>
<p>The question it answers is narrower: of the variation this effect could plausibly account for, once the other factors are held out, how much does it account for? Because each effect gets its own denominator, partial values do not sum to 1 and are always at least as large as the corresponding <span class="math inline">\(\eta^2\)</span>.</p>
<p>This is also why the distinction never came up in Chapter 8. A one-way ANOVA has only one effect, so there are no other factors to set aside, and <span class="math inline">\(SS_\text{Effect} + SS_\text{Error}\)</span> <em>is</em> <span class="math inline">\(SS_\text{Total}\)</span>. The two formulas give the same number there. They only diverge once a design has more than one factor.</p>
<div class="cell">
<div id="tbl-10etasq" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-10etasq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.1: Eta-squared and partial eta-squared for each effect in the 2x2 design.
</figcaption>
<div aria-describedby="tbl-10etasq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Effect</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SS</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Eta-squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Partial eta-squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pollution</td>
<td style="text-align: right;">92.45</td>
<td style="text-align: right;">0.381</td>
<td style="text-align: right;">0.783</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flow</td>
<td style="text-align: right;">110.45</td>
<td style="text-align: right;">0.455</td>
<td style="text-align: right;">0.812</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pollution x Flow</td>
<td style="text-align: right;">14.45</td>
<td style="text-align: right;">0.059</td>
<td style="text-align: right;">0.361</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Flow accounts for the largest share of the total variation, pollution is close behind, and the interaction is much smaller at <span class="math inline">\(\eta^2 = 0.06\)</span>. That last number is worth sitting with. The interaction is significant, and it is also the smallest of the three effects, which is a common combination and not a contradiction: significance and magnitude answer different questions. The interaction is small in the sense that it accounts for little of the total variation, and consequential in the sense that it changes what the pollution main effect means.</p>
<p><strong>Which one to report.</strong> Most statistical software, including SPSS and R’s <code>effectsize</code> package, gives you partial <span class="math inline">\(\eta_p^2\)</span> by default, and it is the more common choice in published work. Either is defensible, but say which you used, because the two can differ substantially: pollution is <span class="math inline">\(\eta^2 = 0.38\)</span> but <span class="math inline">\(\eta_p^2 = 0.78\)</span> here. Reporting the larger number without labeling it overstates the effect. Never compare a partial value from one study against an unpartialed value from another.</p>
</section>
</section>
<section id="reading-patterns-in-a-2x2" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="reading-patterns-in-a-2x2"><span class="header-section-number">10.7</span> Reading patterns in a 2x2</h2>
<p>Having computed one ANOVA table by hand, we can stop doing arithmetic and start doing the part that actually determines whether you get the science right: reading the result.</p>
<p>In any 2x2 ANOVA, there are eight general outcome patterns, different combinations of main effects and interactions. You don’t need to memorize all eight, but you should learn to <strong>read them in a line plot</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Pattern</th>
<th style="text-align: center;">Main Effect: Pollution</th>
<th style="text-align: center;">Main Effect: Flow</th>
<th style="text-align: center;">Interaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
</tr>
</tbody>
</table>
<p>We’ll create bar and line graphs to illustrate these patterns. Bar graphs are great for seeing differences in means directly, while line graphs help us spot interactions. <a href="#fig-10bar22" class="quarto-xref">Figure&nbsp;<span>10.6</span></a> shows the possible patterns in bar graph form. These are abstract illustrations of every combination that can occur, so a few of them describe patterns you would not expect ecologically; the point is to recognize the shapes, not to defend each one.</p>
<p>Here’s what to look for:</p>
<ul>
<li><strong>Parallel lines</strong> → no interaction.</li>
<li><strong>Non-parallel or crossing lines</strong> → interaction likely.</li>
<li><strong>Vertical separation between group means</strong> → main effect.</li>
</ul>
<p>For example:</p>
<ul>
<li>If the <strong>no-pollution vs.&nbsp;pollution</strong> lines are consistently apart, there’s a main effect of pollution.</li>
<li>If the lines cross or diverge, the <strong>pollution effect changes across flow rates</strong>, showing an interaction.</li>
<li>If one line sits higher overall (say, high flow always supports more species), that’s a main effect of flow.</li>
</ul>
<p>The eight panels below are numbered to match the table above, so panel “Pattern 3” in the figure is row 3 in the table, and so on.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10bar22" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10bar22-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-10bar22-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10bar22-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.6: Eight example patterns of main effects and interactions in a pollution × flow design, numbered to match the pattern table above.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-10lines22" class="quarto-xref">Figure&nbsp;<span>10.7</span></a> shows the same patterns in line graph form:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10lines22" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10lines22-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-10lines22-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10lines22-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.7: Line graphs showing eight possible outcomes for a pollution × flow design.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In the line graphs, interactions are easiest to see:</p>
<ul>
<li><strong>Parallel lines</strong> mean no interaction (the pollution effect is the same at both flow rates).</li>
<li><strong>Crossing lines</strong> mean an interaction (the pollution effect differs by flow).</li>
<li><strong>Vertical shifts</strong> between the two lines reflect a main effect of flow.</li>
</ul>
<p><strong>Order of interpretation.</strong> When we conduct a two-way ANOVA, we always begin by testing the <strong>interaction</strong> term.</p>
<ul>
<li><p>If the null hypothesis of <em>no interaction</em> is <strong>rejected</strong>, we <strong>do not</strong> interpret the main effects in isolation, because they are not consistent across conditions. Instead, we focus on the simple effects that describe how one factor behaves at each level of the other. Report simple effects (A at each level of B, or vice versa) rather than standalone main effects.</p></li>
<li><p>If the interaction is <strong>not significant</strong>, we then examine the two main effects separately, interpreting each as an overall difference averaged across the other factor.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="Tip: Which factor goes on the x-axis?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Tip: Which factor goes on the x-axis?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The statistics are identical either way, since the same condition means get plotted regardless. Two rules of thumb make the picture easier to read. Put the factor with more levels on the x-axis, since one long line is easier to follow than several short, crowded ones. And put whichever factor is your main scientific interest there too, since readers compare points along an axis more naturally than separate colored lines.</p>
</div>
</div>
</section>
<section id="interpreting-main-effects-and-interactions" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="interpreting-main-effects-and-interactions"><span class="header-section-number">10.8</span> Interpreting main effects and interactions</h2>
<p>It’s convenient to think of a main effect as one manipulation’s consistent influence. An interaction complicates that picture: it means the effect of one IV depends on another, so by definition, some main effect isn’t behaving consistently across conditions.</p>
<p><strong>Why interactions matter.</strong> In our stream example, pollution reduces species count most under low flow and less under high flow. The pollution effect is not constant across flow rates, so the average “main effect” of pollution can mislead if read without context.</p>
<p><strong>How to read it.</strong></p>
<ul>
<li>Look for non-parallel or crossing lines. That signals that simple effects differ across levels of the other factor.</li>
<li>Report the pattern using simple effects: e.g., “Pollution reduced species count sharply under low flow, and only slightly under high flow.”</li>
<li>If you must report a main effect, qualify it: “There was a main effect of pollution, but it varied by flow rate.”</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="Results reporting: factorial ANOVA">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Results reporting: factorial ANOVA
</div>
</div>
<div class="callout-body-container callout-body">
<p>Lead with the interaction, then give the simple effects, then report the main effects only with their qualification attached. Every effect gets its own effect size, labeled so the reader knows whether it is partialed.</p>
<blockquote class="blockquote">
<p>The effect of pollution on macroinvertebrate species count depended on flow rate, <em>F</em>(1, 16) = 9.03, <em>p</em> = .008, <span class="math inline">\(\eta_p^2 = 0.36\)</span>. Under low flow, polluted channels supported 6.0 fewer species than unpolluted ones (3.6 vs.&nbsp;9.6); under high flow that gap narrowed to 2.6 species (10.0 vs.&nbsp;12.6). Both main effects were also significant, pollution <em>F</em>(1, 16) = 57.78, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = 0.78\)</span>, and flow <em>F</em>(1, 16) = 69.03, <em>p</em> &lt; .001, <span class="math inline">\(\eta_p^2 = 0.81\)</span>, but each should be read in light of the interaction: pollution costs a stream far more species when the water is moving slowly.</p>
</blockquote>
</div>
</div>
<p>Here are two generalized examples to help you make sense of these issues:</p>
<section id="a-consistent-main-effect-and-an-interaction" class="level3" data-number="10.8.1">
<h3 data-number="10.8.1" class="anchored" data-anchor-id="a-consistent-main-effect-and-an-interaction"><span class="header-section-number">10.8.1</span> A consistent main effect and an interaction</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10mainint" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10mainint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-10mainint-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10mainint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.8: Pollution shows a general (main) effect, but the size of that effect differs by flow rate (interaction).
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-10mainint" class="quarto-xref">Figure&nbsp;<span>10.8</span></a> shows both a main effect and an interaction. Unpolluted channels sit above polluted ones at both flow rates, that’s the main effect. But the size of that gap is larger under low flow (12 vs.&nbsp;5) than under high flow (14 vs.&nbsp;11), so there’s an interaction too.</p>
<p>There was a main effect of pollution, qualified by a Pollution × Flow interaction: the size of the pollution effect changed with flow rate, larger under low flow and smaller under high flow. That qualification doesn’t mean the main effect isn’t real. Pollution is associated with lower species counts fairly consistently; flow changes how much lower, not the direction.</p>
</section>
<section id="an-averaged-main-effect-thats-actually-driven-by-an-interaction" class="level3" data-number="10.8.2">
<h3 data-number="10.8.2" class="anchored" data-anchor-id="an-averaged-main-effect-thats-actually-driven-by-an-interaction"><span class="header-section-number">10.8.2</span> An “averaged” main effect that’s actually driven by an interaction</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-10mainintInc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10mainintInc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-10mainintInc-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10mainintInc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.9: An apparent main effect of pollution arises from averaging over an interaction.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-10mainintInc" class="quarto-xref">Figure&nbsp;<span>10.9</span></a> shows a starker 2x2 pattern: a large difference between polluted and unpolluted channels under low flow, and no difference at all under high flow, an interaction visible at a glance.</p>
<p>Yet an ANOVA run on this data can still report a significant main effect of pollution. Averaged across flow rates, unpolluted channels give <span class="math inline">\((10+5)/2=7.5\)</span> species and polluted channels give <span class="math inline">\(5\)</span>, a main-effect difference of 2.5. That number is real, but it doesn’t describe what pollution actually does: it removes 5 species under low flow and none under high flow, not 2.5 everywhere. The “main effect” here is an artifact of averaging over a strong interaction, not a description of anything pollution is doing in general.</p>
<p>There was a main effect of pollution, but it was entirely qualified by a Pollution × Flow interaction: the pollution effect was large under low flow and effectively zero under high flow. In a case like this, it’s fair to doubt whether pollution has a <em>general</em> effect on species count at all. It may only do damage under specific conditions, in combination with other factors, rather than on its own.</p>
</section>
</section>
<section id="more-complicated-designs" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="more-complicated-designs"><span class="header-section-number">10.9</span> More complicated designs</h2>
<p>Up until now we have focused on the simplest case for factorial designs, the 2x2 design, with two IVs, each with 2 levels. It is worth spending some time looking at a few more complicated designs and how to interpret them.</p>
<section id="x2-design" class="level3" data-number="10.9.1">
<h3 data-number="10.9.1" class="anchored" data-anchor-id="x2-design"><span class="header-section-number">10.9.1</span> 3x2 design</h3>
<p>This design works exactly like the 2x2 you already know, it just adds one more level to one factor. The test structure is the same (two main effects and one interaction). What changes is how easy it is to interpret the interaction.</p>
<p>Let’s expand our stream example. Suppose we examine macroinvertebrate species count (DV) under two pollution conditions (no pollution vs.&nbsp;pollution) across <strong>three flow rates</strong> (low, medium, high).</p>
<ul>
<li>The <strong>main effect of pollution</strong> tests whether, on average, polluted and unpolluted channels differ in species count across all flow rates.</li>
<li>The <strong>main effect of flow</strong> tests whether mean species count differs among flow rates.</li>
<li>The <strong>interaction</strong> tests whether the pollution effect (unpolluted − polluted) changes with flow rate.</li>
</ul>
<p>In a 2x2 design, you can easily spot interactions by looking for non-parallel lines. In a 3x2, it’s still the same idea; but with three points per line, patterns get trickier to read. The statistical test is identical, but interpretation requires more care.</p>
<p>You have three hypotheses in a 3x2 factorial design:</p>
<p><strong>H₁: Main effect of Flow</strong></p>
<ul>
<li><strong>Null (</strong><span class="math inline">\(H_{0,1}\)</span>): <span class="math inline">\(\mu_{\text{Low}} = \mu_{\text{Medium}} = \mu_{\text{High}}\)</span></li>
<li><strong>Alternative (</strong><span class="math inline">\(H_{a,1}\)</span>): At least one flow rate mean differs from the others.</li>
</ul>
<p><strong>H₂: Main effect of Pollution</strong></p>
<ul>
<li><strong>Null (</strong><span class="math inline">\(H_{0,2}\)</span>): <span class="math inline">\(\mu_{\text{NoPoll}} = \mu_{\text{Poll}}\)</span></li>
<li><strong>Alternative (</strong><span class="math inline">\(H_{a,2}\)</span>): Mean species count differs between polluted and unpolluted channels.</li>
</ul>
<p><strong>H₃: Pollution × Flow interaction</strong></p>
<ul>
<li><strong>Null (</strong><span class="math inline">\(H_{0,3}\)</span>): The pollution effect is the same across all flow rates. <span class="math inline">\([ (\mu_{\text{NoPoll,Low}}-\mu_{\text{Poll,Low}}) = (\mu_{\text{NoPoll,Med}}-\mu_{\text{Poll,Med}}) = (\mu_{\text{NoPoll,High}}-\mu_{\text{Poll,High}}) ]\)</span></li>
<li><strong>Alternative (</strong><span class="math inline">\(H_{a,3}\)</span>): The pollution effect differs across flow rates (i.e., at least one difference of differences is not equal).</li>
</ul>
<p>Remember, this is far better than running two separate single factor ANOVAs that contrast pollution effects at each flow rate, because you have more statistical power (higher degrees of freedom) for the tests of interest, and you get a formal test of the interaction between factors which is often scientifically interesting.</p>
<p>We might expect data like shown in <a href="#fig-1023design" class="quarto-xref">Figure&nbsp;<span>10.10</span></a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1023design" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1023design-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-1023design-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1023design-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.10: Example means for a 3x2 factorial design in environmental science
</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure shows some pretend means in all conditions. Let’s talk about the main effects and interaction.</p>
<ol type="1">
<li><p><strong>Main Effect of Pollution</strong>: The main effect of pollution is evident. Averaged across flow rates, unpolluted channels support higher species counts (10 vs.&nbsp;7.3). The “No Pollution” line sits above the “Pollution” line at low and medium flow, and the two coincide at high flow.</p></li>
<li><p><strong>Main Effect of Flow</strong>: There is a main effect of flow as well. Averaged over pollution condition, species counts are lowest at low flow (8) and higher at medium and high flow (9 each).</p></li>
<li><p><strong>Interaction Between Pollution and Flow</strong>: Is there an interaction? Yes. Remember, an interaction occurs when the effect of one IV depends on the levels of another. The pollution gap is 6 species at low flow, 2 at medium, and 0 at high. So the size of the pollution effect changes with flow rate, which is also why the pollution main effect above describes no single flow condition well. You would have to conduct an inferential test on the interaction term to see if these differences were likely or unlikely to be due to sampling error.</p></li>
</ol>
<p>If there was no interaction and no main effect of flow, we would see something like the pattern in <a href="#fig-1023one" class="quarto-xref">Figure&nbsp;<span>10.11</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1023one" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1023one-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-1023one-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1023one-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.11: Example means for a 3x2 design with only one main effect
</figcaption>
</figure>
</div>
</div>
</div>
<p>What would you say about the interaction if you saw the pattern in <a href="#fig-1023int" class="quarto-xref">Figure&nbsp;<span>10.12</span></a>?</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1023int" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1023int-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-FactorialANOVA_files/figure-html/fig-1023int-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1023int-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.12: Example means for a 3x2 design showing a different interaction pattern
</figcaption>
</figure>
</div>
</div>
</div>
<p>The correct answer is that there is evidence in the means for an interaction. Remember, we are measuring the pollution effect three times, once at each flow rate. The pollution effect is the same at low and medium flow, but it is much smaller at high flow. The size of the pollution effect depends on the level of the flow IV, so here again there is an interaction.</p>
</section>
</section>
<section id="designs-beyond-this-course" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="designs-beyond-this-course"><span class="header-section-number">10.10</span> Designs Beyond This Course</h2>
<p>Once you understand the 2x2 logic, everything else in factorial ANOVA builds from the same foundation. But complexity grows quickly, both in the number of effects and in how hard they are to interpret.</p>
<section id="three-factor-designs" class="level3" data-number="10.10.1">
<h3 data-number="10.10.1" class="anchored" data-anchor-id="three-factor-designs"><span class="header-section-number">10.10.1</span> 2×2×2 (Three-Factor) Designs</h3>
<p>A 2×2×2 design includes <strong>three independent variables</strong>, each with two levels. That creates:</p>
<ul>
<li>three <strong>main effects</strong> (one per variable)</li>
<li>three <strong>two-way interactions</strong> (A×B, A×C, B×C)</li>
<li>one <strong>three-way interaction</strong> (A×B×C)</li>
</ul>
<p>You can think of it as two 2×2 plots side-by-side; one for each level of the third variable.</p>
<p>A <strong>three-way interaction</strong> means that one of the two-way interactions changes across the third variable. For example, the pollution × flow interaction might look different in summer than in winter.</p>
<p>That’s all you really need to know: interactions can themselves interact. The math is identical in structure, but the number of effects grows fast, and the graphs become difficult to interpret. In applied research, most studies stop at <strong>two factors</strong> unless there’s a strong reason to add more.</p>
</section>
<section id="mixed-designs" class="level3" data-number="10.10.2">
<h3 data-number="10.10.2" class="anchored" data-anchor-id="mixed-designs"><span class="header-section-number">10.10.2</span> Mixed Designs</h3>
<p>Sometimes one factor is <strong>between-subjects</strong> (e.g., different sites or treatments) and another is <strong>within-subjects</strong> (e.g., repeated measures over time). This is called a <strong>mixed design</strong>.</p>
<p>The interpretation of main effects and interactions is the same, but the error terms used in the F-tests differ, and the data structure must account for repeated measures. These models are important in longitudinal and environmental time-series studies, but they’re beyond our current scope.</p>
<p><strong>Takeaway:</strong> Factorial ANOVA can handle almost any experimental structure, but interpretability drops as factors multiply. Start simple: use only the number of factors needed to answer your scientific question clearly.</p>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="10.11">
<h2 data-number="10.11" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">10.11</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> Single-factor designs can tell you whether something has an effect. Factorial designs tell you what <em>changes</em> that effect, which is usually the more interesting scientific question, and often the more realistic one for environmental systems where drivers act together. Getting the numbers is only half the job. An interaction changes what every other term in the table means, so interpretation has to be part of the analysis rather than a step you tack on afterward.</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>Fully crossed means every combination.</strong> A factorial design pairs every level of each IV with every level of the others. The notation says the structure: 2×2 is four conditions, 3×2 is six.</li>
<li><strong>A 2×2 tests three things.</strong> One main effect per factor, plus their interaction. That means three null hypotheses, and you should be able to state all three in plain language before running anything.</li>
<li><strong>An interaction is a difference between differences.</strong> It asks whether the effect of one factor changes across levels of another. That framing is what the arithmetic is actually computing, and you can compute it directly with a paired <span class="math inline">\(t\)</span>-test on difference scores.</li>
<li><strong>The partition extends the one-way logic.</strong> <span class="math inline">\(SS_\text{Total}\)</span> now splits into each main effect, the interaction, and error. Working one table through by hand shows that the interaction term is the only genuinely new piece.</li>
<li><strong>Three tests, three effect sizes.</strong> <span class="math inline">\(\eta^2\)</span> divides each effect’s <span class="math inline">\(SS\)</span> by <span class="math inline">\(SS_\text{Total}\)</span>; partial <span class="math inline">\(\eta_p^2\)</span> divides it by that effect plus error. Partial values are always larger and do not sum to 1, so label which one you are reporting. A significant effect can still be a small one, which is exactly the case for this chapter’s interaction.</li>
<li><strong>Read the interaction first.</strong> If it’s significant, do not interpret the main effects on their own, because they are not consistent across conditions. Report simple effects instead: what factor A does at each level of B. Only when the interaction is not significant do the main effects stand on their own.</li>
<li><strong>Learn to read the picture.</strong> In a line plot, parallel lines mean no interaction, crossing or diverging lines mean an interaction, and vertical separation between lines means a main effect. There are eight possible patterns in a 2×2, and recognizing them by eye is faster than parsing the table.</li>
<li><strong>An averaged main effect can be an artifact.</strong> A factor that matters a lot in one condition and not at all in another will still produce a “significant main effect” once you average across conditions. That number is real arithmetic, but it describes something that never happens in either condition.</li>
<li><strong>Bigger designs, same tests, harder reading.</strong> A 3×2 has the same three tests as a 2×2, but three points per line are harder to read than two. Beyond that, a three-factor design brings three main effects, three two-way interactions, and a three-way interaction, and interpretability falls off fast. Use only as many factors as your question actually needs.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./09-Regression.html" class="pagination-link" aria-label="Simple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11-ANCOVA.html" class="pagination-link" aria-label="Analysis of Covariance (ANCOVA)">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/10-FactorialANOVA.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>