<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>Answering questions with data - 11&nbsp; Analysis of Covariance (ANCOVA)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-FactorialANOVA.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 11&nbsp; Analysis of Covariance (ANCOVA)">
<meta property="og:description" content="">
<meta property="og:image" content="11-ANCOVA_files/figure-html/fig-11onevstwo-1.png">
<meta property="og:site-name" content="Answering questions with data">
<meta name="twitter:title" content="Answering questions with data - 11&nbsp; Analysis of Covariance (ANCOVA)">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11-ANCOVA.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Data_Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measuring and Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Nonparametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Nonparametric and Categorical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-ANCOVA.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#terminology" id="toc-terminology" class="nav-link active" data-scroll-target="#terminology"><span class="header-section-number">11.1</span> Terminology</a></li>
  <li><a href="#what-ancova-is" id="toc-what-ancova-is" class="nav-link" data-scroll-target="#what-ancova-is"><span class="header-section-number">11.2</span> What ANCOVA Is</a>
  <ul class="collapse">
  <li><a href="#indicator-dummy-variables-and-how-they-work" id="toc-indicator-dummy-variables-and-how-they-work" class="nav-link" data-scroll-target="#indicator-dummy-variables-and-how-they-work"><span class="header-section-number">11.2.1</span> Indicator (dummy) variables and how they work</a></li>
  <li><a href="#the-null-hypothesis-in-ancova" id="toc-the-null-hypothesis-in-ancova" class="nav-link" data-scroll-target="#the-null-hypothesis-in-ancova"><span class="header-section-number">11.2.2</span> The Null Hypothesis in ANCOVA</a></li>
  <li><a href="#one-more-piece-of-vocabulary-the-omnibus-test" id="toc-one-more-piece-of-vocabulary-the-omnibus-test" class="nav-link" data-scroll-target="#one-more-piece-of-vocabulary-the-omnibus-test"><span class="header-section-number">11.2.3</span> One More Piece of Vocabulary: the Omnibus Test</a></li>
  <li><a href="#checking-ancovas-assumptions" id="toc-checking-ancovas-assumptions" class="nav-link" data-scroll-target="#checking-ancovas-assumptions"><span class="header-section-number">11.2.4</span> Checking ANCOVA’s assumptions</a></li>
  </ul></li>
  <li><a href="#full-ancova-example" id="toc-full-ancova-example" class="nav-link" data-scroll-target="#full-ancova-example"><span class="header-section-number">11.3</span> Full ANCOVA Example</a>
  <ul class="collapse">
  <li><a href="#question" id="toc-question" class="nav-link" data-scroll-target="#question"><span class="header-section-number">11.3.1</span> Question</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model"><span class="header-section-number">11.3.2</span> Model</a></li>
  <li><a href="#null-and-alternative-hypotheses-in-our-example-ancova" id="toc-null-and-alternative-hypotheses-in-our-example-ancova" class="nav-link" data-scroll-target="#null-and-alternative-hypotheses-in-our-example-ancova"><span class="header-section-number">11.3.3</span> Null and Alternative Hypotheses in our example ANCOVA</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">11.3.4</span> Analysis</a></li>
  <li><a href="#results-of-the-ancova-model" id="toc-results-of-the-ancova-model" class="nav-link" data-scroll-target="#results-of-the-ancova-model"><span class="header-section-number">11.3.5</span> Results of the ANCOVA Model</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">11.4</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/malloryb/statistics_E538/edit/master/11-ANCOVA.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">August 4, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>We’ve now covered both regression and ANOVA. This chapter merges them:</p>
<p><span class="math display">\[\text{Regression} + \text{ANOVA} = \text{ANCOVA}\]</span></p>
<p>The last chapter compared macroinvertebrate species count across two discrete Pollution categories, present or absent, and two Flow categories, low or high. But suppose you actually measured each channel’s pollution concentration instead of just labeling it present or absent.</p>
<ul>
<li><p>Does Flow’s effect on species count still depend on pollution once pollution is treated as the continuous measurement it really is, rather than binned into two groups? <em>(covariate: pollution concentration; factor: flow rate)</em></p></li>
<li><p>Does exposure to PFAS correlate with lifetime cancer incidence uniformly across low- and high-income American populations? <em>(covariate: PFAS exposure; factor: income level)</em></p></li>
</ul>
<p>Each question pairs a continuous relationship, a continuous variable’s effect on the outcome, with a categorical grouping. That pairing, one continuous variable and one categorical factor, is what makes a design an ANCOVA rather than a plain regression or a plain ANOVA.</p>
<p>The first question is really a complaint about the last chapter. “Pollution: present or absent” is a real simplification of something that’s actually continuous, a concentration in parts per billion, measured on a gradient, not a light switch. Sorting continuous measurements into “high” and “low” buckets throws away exactly the information a covariate needs: how much more polluted, not just whether. Whenever you have the real numbers, ANCOVA (or, if there’s no categorical factor left at all, plain regression) is almost always the better tool than forcing them into groups first.</p>
<p>ANCOVA is a linear model built directly on regression’s own equation. A simple linear model is</p>
<p><span class="math display">\[y = \beta_0 + \beta_1 x + \varepsilon\]</span></p>
<p>Here <span class="math inline">\(\beta_0\)</span> is the intercept, <span class="math inline">\(\beta_1\)</span> is the slope, and <span class="math inline">\(\varepsilon\)</span> is the error: one intercept, one slope, one line.</p>
<p>ANCOVA adds a categorical factor to that equation, and the whole chapter comes down to one question: does every group follow that same line, or does each group need its own slope and intercept?</p>
<p>We answer it in two steps: first test whether groups have different <strong>slopes</strong>, then, only if slopes are parallel, test whether groups differ in <strong>adjusted means</strong>.</p>
<section id="terminology" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="terminology"><span class="header-section-number">11.1</span> Terminology</h2>
<p><strong>Covariate:</strong> a continuous variable that changes alongside the response and helps explain part of its variation. In environmental studies, common covariates include temperature, rainfall, soil moisture, or pollution concentration: factors that may influence the outcome but aren’t the main treatment of interest. Including one lets us <strong>adjust for its influence</strong>, giving a clearer test of the categorical effect once that continuous background variation is accounted for.</p>
<p>The categorical predictor itself, in every example this chapter uses, is what’s called a <strong>fixed factor</strong>: specific, intentional levels chosen by the researcher (urban vs.&nbsp;rural, shaded vs.&nbsp;open canopy), not a random sample of possible groups. That distinction matters more once you’re building mixed-effects models, which is beyond where this course goes. A random factor, by contrast, would be something like the specific counties your streams happen to sit in: you aren’t interested in those ten counties for their own sake, they stand in for a larger population of possible counties, and you’d want your conclusions to generalize beyond just the ones you sampled.</p>
</section>
<section id="what-ancova-is" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="what-ancova-is"><span class="header-section-number">11.2</span> What ANCOVA Is</h2>
<p>ANCOVA helps us answer: does a <em>relationship</em> hold up across groups? That framing fits environmental work particularly well, because you usually can’t experimentally strip out a covariate like temperature, rainfall, or season anyway. Often you wouldn’t want to. It may be the reason you designed the study in the first place. In the examples in this chapter, the covariate is what we care about and the interaction is the result we’re testing for.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Warning: The other way you'll see ANCOVA">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning: The other way you’ll see ANCOVA
</div>
</div>
<div class="callout-body-container callout-body">
<p>Elsewhere the covariate is a <strong>nuisance</strong> instead: something you control for so a group comparison comes out fairer, with an interaction being a box you check and hope stays empty.</p>
<p>A classic version from psychology compares anxiety scores across two therapy groups after treatment, controlling for pre-treatment scores.</p>
<p>Same test, same math. The only difference is which term you came to interpret, so decide that before you fit anything.</p>
</div>
</div>
<p>For ANCOVA, you need:</p>
<ol type="1">
<li>A continuous dependent variable (the main effect you’re studying)</li>
<li>At least one continuous independent variable (covariate)</li>
<li>At least one categorical independent variable (which can be either a fixed or random factor)</li>
</ol>
<section id="indicator-dummy-variables-and-how-they-work" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="indicator-dummy-variables-and-how-they-work"><span class="header-section-number">11.2.1</span> Indicator (dummy) variables and how they work</h3>
<p>Before we can read real coefficients off an ANCOVA table, it helps to see exactly how one equation can represent two different groups at once.</p>
<p>Categorical predictors get into a linear model by being coded as <strong>indicator variables</strong>. For a factor with <span class="math inline">\(k\)</span> groups you include <span class="math inline">\(k-1\)</span> indicators; the omitted group becomes the <strong>reference</strong>, and every coefficient is interpreted relative to it. With two groups, one indicator does the whole job:</p>
<p><span class="math display">\[x_c = \begin{cases} 0 &amp; \text{group 1 (the reference group)} \\ 1 &amp; \text{group 2} \end{cases}\]</span></p>
<p>In R, <code>lm(y ~ x + Group)</code> creates these indicators for you automatically.</p>
<p><strong>Indicator variables in action.</strong> When an indicator variable is turned on (set to 1), it activates the terms multiplied by that variable. Depending on where the indicator appears in the model, that can change the intercept, the slope, or both.</p>
<p>Consider two predictors: a continuous variable <span class="math inline">\(x_l\)</span> and an indicator <span class="math inline">\(x_c\)</span> (0 or 1). The numbers below are arbitrary, chosen to make the arithmetic clean; the worked example later in this chapter plugs in real coefficients for air pollution and area type. Use this model:</p>
<p><span class="math display">\[y = 2x_l + 1(x_l x_c) - 7x_c + 3\]</span></p>
<p><strong>When</strong> <span class="math inline">\(x_c = 0\)</span> (indicator off), only the baseline terms are active:</p>
<p><span class="math display">\[y = 2x_l + 3 \qquad \text{slope} = 2, \ \text{intercept} = 3\]</span></p>
<p><strong>When</strong> <span class="math inline">\(x_c = 1\)</span> (indicator on), the new terms activate:</p>
<p><span class="math display">\[y = (2x_l + 3) + (1x_l - 7) = 3x_l - 4 \qquad \text{slope} = 3, \ \text{intercept} = -4\]</span></p>
<p>Turning on the indicator adds <strong>+1 to the slope</strong> and <strong>−7 to the intercept</strong>. One equation, two different lines, with the indicator deciding which one applies.</p>
<p>This is how linear models represent different groups: the indicator (<span class="math inline">\(x_c\)</span>) and its interaction with <span class="math inline">\(x_l\)</span> let a single equation shift the intercept and the slope for each group. ANCOVA uses exactly this logic to test, in order, whether the <strong>slopes differ</strong> between groups (the <span class="math inline">\(x_l x_c\)</span> term) and, if they don’t, whether the <strong>adjusted means</strong> differ (the <span class="math inline">\(x_c\)</span> term).</p>
<p><strong>Naming the pieces.</strong> Write that same equation in the general form and each coefficient now has a job:</p>
<p><span class="math display">\[y = \underbrace{\beta_0}_{\text{reference intercept}} + \underbrace{\beta_1 x_l}_{\text{reference slope}} + \underbrace{\beta_2 x_c}_{\text{intercept shift}} + \underbrace{\beta_3 x_l x_c}_{\text{slope shift}} + \varepsilon\]</span></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> describe the line for the <strong>reference group</strong> (<span class="math inline">\(x_c=0\)</span>).</li>
<li><span class="math inline">\(\beta_2\)</span> is how much the <strong>intercept</strong> moves for the other group.</li>
<li><span class="math inline">\(\beta_3\)</span> is how much the <strong>slope</strong> changes for the other group. This is the interaction term.</li>
</ul>
<p>If we only include <span class="math inline">\(\beta_2\)</span> and leave out <span class="math inline">\(\beta_3\)</span>, we get a restricted version: the intercept can shift but the slope cannot, so the two lines are forced to be <strong>parallel</strong>. That is the parallel-lines model, and it is the one we fall back to when the slope difference turns out not to be significant.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note: Why this matters">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note: Why this matters
</div>
</div>
<div class="callout-body-container callout-body">
<p>Every coefficient you will read out of an ANCOVA table is one of these four. Without the indicator, <span class="math inline">\(\beta_2\)</span> and <span class="math inline">\(\beta_3\)</span> are just numbers R hands you. With it, <span class="math inline">\(\beta_3\)</span> has a plain-language meaning you can check against a graph: it is the amount by which one group’s line tilts away from the other’s.</p>
</div>
</div>
</section>
<section id="the-null-hypothesis-in-ancova" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="the-null-hypothesis-in-ancova"><span class="header-section-number">11.2.2</span> The Null Hypothesis in ANCOVA</h3>
<p><strong>Model.</strong> For one covariate (<span class="math inline">\(x\)</span>) and a two-level group indicator <span class="math inline">\(x_c\in\{0,1\}\)</span>,</p>
<p><span class="math inline">\(y=\beta_0+\beta_1 x+\beta_2 x_c+\beta_3(x\times x_c)+\varepsilon .\)</span></p>
<p><a href="#fig-11onevstwo">Figure&nbsp;<span>11.1</span></a> shows the three possibilities this model can produce, and it’s worth keeping this picture in mind for the two steps below.</p>
<div class="cell" data-fig.asp="0.45">
<div class="cell-output-display">
<div id="fig-11onevstwo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="11-ANCOVA_files/figure-html/fig-11onevstwo-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Three scatter plots, each with two colored groups of points. In the first, a single line runs through both groups. In the second, two parallel lines sit at different heights. In the third, two lines with visibly different slopes diverge from left to right."></p>
<figcaption class="figure-caption">Figure&nbsp;11.1: The question ANCOVA answers. Left: one line describes both groups. Middle: the groups need different intercepts but share a slope, so the lines are parallel. Right: the groups need different slopes, so the lines are not parallel and the gap between them depends on where you look.</figcaption>
</figure>
</div>
</div>
</div>
<p>ANCOVA works right to left across that figure: first it asks whether the rightmost panel is what we have (do the slopes differ?), and only if the answer is no does it ask whether we have the middle panel or the leftmost (do the intercepts differ?).</p>
<p><strong>Step 1: Are slopes equal across groups?</strong> This tests whether the covariate effect is the same in each group.</p>
<ul>
<li>Null: <span class="math inline">\(H_{0,\text{int}}:\beta_3=0\)</span> (parallel lines, same slope)</li>
<li>Alternative: <span class="math inline">\(H_{A,\text{int}}:\beta_3\neq 0\)</span> (non-parallel lines, different slopes)</li>
</ul>
<p><strong>Interpretation if rejected.</strong> Report the two fitted lines and describe how the slope differs by group. Do not test adjusted means, because the idea of a single adjusted mean per group assumes parallel slopes.</p>
<p><strong>Step 2: Are adjusted means equal?</strong> <em>(only if Step 1 retained parallel slopes)</em> Fit the model without the interaction,</p>
<p><span class="math inline">\(y=\beta_0+\beta_1 x+\beta_2 x_c+\varepsilon .\)</span></p>
<ul>
<li>Null: <span class="math inline">\(H_{0,\text{group}}:\beta_2=0\)</span> (no difference in adjusted means)</li>
<li>Alternative: <span class="math inline">\(H_{A,\text{group}}:\beta_2\neq 0\)</span></li>
</ul>
<p><strong>What the parameters mean.</strong></p>
<ul>
<li><span class="math inline">\(\beta_1\)</span>: common slope of <span class="math inline">\(y\)</span> on <span class="math inline">\(x\)</span> when slopes are parallel.</li>
<li><span class="math inline">\(\beta_2\)</span>: difference in group means <strong>after</strong> adjusting for <span class="math inline">\(x\)</span> (tested only when <span class="math inline">\(\beta_3=0\)</span>).</li>
<li><span class="math inline">\(\beta_3\)</span>: difference in slopes between groups.</li>
</ul>
<p><strong>Intercepts and centering.</strong> Intercepts are evaluated at <span class="math inline">\(x=0\)</span>. Compare intercepts only if you center the covariate, for example <span class="math inline">\(\tilde x=x-\bar x\)</span>, so that the intercepts represent group means at the average covariate value.</p>
<p><strong>What to report.</strong></p>
<ul>
<li>If <span class="math inline">\(x\times x_c\)</span> is significant: “The effect of <span class="math inline">\(x\)</span> differs by group,” then provide the two line equations and a figure with separate fitted lines.</li>
<li>If <span class="math inline">\(x\times x_c\)</span> is not significant: report the common slope <span class="math inline">\(\beta_1\)</span> and the adjusted group difference <span class="math inline">\(\beta_2\)</span>, with a figure showing parallel lines.</li>
</ul>
<p><strong>Common pitfalls.</strong></p>
<ul>
<li>Interpreting main effects when the interaction is significant.</li>
<li>Comparing raw intercepts when <span class="math inline">\(x\)</span> is not centered.</li>
<li>Treating adjusted means as meaningful when slopes are not parallel.</li>
</ul>
</section>
<section id="one-more-piece-of-vocabulary-the-omnibus-test" class="level3" data-number="11.2.3">
<h3 data-number="11.2.3" class="anchored" data-anchor-id="one-more-piece-of-vocabulary-the-omnibus-test"><span class="header-section-number">11.2.3</span> One More Piece of Vocabulary: the Omnibus Test</h3>
<p>R’s ANCOVA output is built around an <strong>omnibus F-test</strong>: a single test of whether there’s any difference in adjusted group means once the covariate is accounted for. It’s the same idea as a significant one-way ANOVA telling you <em>some</em> group differs without saying which, and it’s exactly why we still decompose it into the interaction-then-adjusted-means steps above rather than stopping at one <span class="math inline">\(p\)</span>-value.</p>
<p>As always, statistical significance doesn’t guarantee ecological or practical importance. Interpret a rejected null in light of the study’s design, measurement precision, and the actual size of the effect, not just its <span class="math inline">\(p\)</span>-value.</p>
</section>
<section id="checking-ancovas-assumptions" class="level3" data-number="11.2.4">
<h3 data-number="11.2.4" class="anchored" data-anchor-id="checking-ancovas-assumptions"><span class="header-section-number">11.2.4</span> Checking ANCOVA’s assumptions</h3>
<p>Most of these are ones ANOVA already needed; two are new because a covariate has entered the model.</p>
<ul>
<li><p>Independent observations <em>(same as ANOVA)</em></p></li>
<li><p>Approximately normal residuals and similar variances across groups <em>(same as ANOVA)</em></p></li>
<li><p>Linearity within each group: the covariate-response relationship is a straight line <em>(new, about the covariate)</em></p></li>
<li><p>Homogeneity of slopes: the groups share that same line, unless the interaction test says otherwise <em>(new, and this is the one the interaction test above directly checks, rather than a condition you verify beforehand)</em></p></li>
<li><p>The covariate is measured with minimal error and isn’t itself affected by the treatment <em>(new, and more consequential here than in an ordinary regression: measurement error in the covariate leaves genuine covariate-driven differences between groups only partially adjusted for, which can look like a treatment effect that isn’t really there)</em></p></li>
</ul>
</section>
</section>
<section id="full-ancova-example" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="full-ancova-example"><span class="header-section-number">11.3</span> Full ANCOVA Example</h2>
<section id="question" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="question"><span class="header-section-number">11.3.1</span> Question</h3>
<p>Imagine we’re environmental scientists studying the impact of <strong>air pollution</strong> (a continuous variable) on <strong>bird species density</strong> (our dependent variable).</p>
<p>We want to know whether this relationship differs between <strong>urban</strong> and <strong>rural</strong> areas (our categorical variable).</p>
<p>Specifically, we want to know: Does the effect of air pollution on bird density differ between <strong>urban</strong> and <strong>rural</strong> areas?</p>
<p>We might expect that air pollution will have a stronger negative effect in urban areas than in rural areas: urban habitat is already fragmented and offers birds fewer clean patches to retreat to, so added pollution has less of a buffer to work against than it would in a rural area with more intact habitat nearby.</p>
</section>
<section id="model" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="model"><span class="header-section-number">11.3.2</span> Model</h3>
<p>We’ll fit an ANCOVA model to test whether location type influences bird density <strong>after accounting for</strong> air pollution.</p>
<p>The categorical variable (urban vs.&nbsp;rural) is represented as a dummy variable, and air pollution enters as a covariate.</p>
<ul>
<li><strong>Dataset Overview:</strong> 200 observations of bird density across urban and rural sites, each with a measured level of air pollution.</li>
</ul>
</section>
<section id="null-and-alternative-hypotheses-in-our-example-ancova" class="level3" data-number="11.3.3">
<h3 data-number="11.3.3" class="anchored" data-anchor-id="null-and-alternative-hypotheses-in-our-example-ancova"><span class="header-section-number">11.3.3</span> Null and Alternative Hypotheses in our example ANCOVA</h3>
<p>First, we state our hypotheses:</p>
<ol start="0" type="1">
<li><p><strong>Omnibus (adjusted means) hypothesis</strong> After adjusting for air pollution, do urban and rural sites differ in mean bird density?</p>
<p><span class="math inline">\(H_{0}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p><span class="math inline">\(H_{A}: \mu_{\text{Urban, adj}} \neq \mu_{\text{Rural, adj}}\)</span></p>
<p>Here, <span class="math inline">\(\mu_{\text{Urban, adj}}\)</span> and <span class="math inline">\(\mu_{\text{Rural, adj}}\)</span> are the <em>adjusted</em> group means once the covariate (air pollution) is accounted for.</p></li>
<li><p><strong>Slope (interaction) hypothesis</strong></p>
<p>Does air pollution affect bird density in the same way across urban and rural sites?</p>
<p><span class="math inline">\(H_{0,1}: \beta_{\text{interaction}} = 0\)</span></p>
<p><span class="math inline">\(H_{A,1}: \beta_{\text{interaction}} \neq 0\)</span></p>
<p>A significant interaction means the slopes differ, and air pollution’s relationship with bird density depends on area type.</p></li>
<li><p><strong>Intercept (baseline difference) hypothesis</strong></p>
<p>If slopes are parallel (interaction not significant), do the adjusted means differ?</p>
<p><span class="math inline">\(H_{0,2}: \beta_{0,\text{Urban}} = \beta_{0,\text{Rural}}\)</span></p>
<p><span class="math inline">\(H_{A,2}: \beta_{0,\text{Urban}} \neq \beta_{0,\text{Rural}}\)</span></p>
<p>Rejecting <span class="math inline">\(H_{0,2}\)</span> indicates an inherent group difference in bird density that is independent of pollution.</p></li>
</ol>
</section>
<section id="analysis" class="level3" data-number="11.3.4">
<h3 data-number="11.3.4" class="anchored" data-anchor-id="analysis"><span class="header-section-number">11.3.4</span> Analysis</h3>
<p>Before we look at the model results, it’s always good practice to <strong>look at the data first</strong>.</p>
<p>Let’s start with the response variable, <strong>bird density</strong>, in <a href="#fig-11birddensity">Figure&nbsp;<span>11.2</span></a>. This gives us a quick visual sense of whether urban and rural areas differ in their average values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(AreaType, BirdDensity)) <span class="sc">+</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Area Type"</span>, <span class="at">y =</span> <span class="st">"Bird Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-11birddensity" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="11-ANCOVA_files/figure-html/fig-11birddensity-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Boxplot of bird density for rural and urban area types. The rural box is centered higher than the urban box, with overlapping ranges."></p>
<figcaption class="figure-caption">Figure&nbsp;11.2: Bird density by area type. Rural sites sit higher than urban ones.</figcaption>
</figure>
</div>
</div>
</div>
<p>At first glance, bird density appears <strong>higher in rural areas</strong> than in urban ones, consistent with what we might expect ecologically.</p>
<p>Next, check the <strong>covariate</strong>, air pollution. If the covariate differs sharply between groups, ANCOVA will “adjust” for that difference. If it doesn’t, group comparisons will look more like a simple ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(AreaType, AirPollution)) <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Area Type"</span>, <span class="at">y =</span> <span class="st">"Air Pollution"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-11airpollution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="11-ANCOVA_files/figure-html/fig-11airpollution-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Boxplot of air pollution for rural and urban area types. The two boxes overlap substantially with similar centers."></p>
<figcaption class="figure-caption">Figure&nbsp;11.3: Air pollution by area type. The two groups look broadly similar, so there is no large covariate imbalance for the model to adjust away.</figcaption>
</figure>
</div>
</div>
</div>
<p>Air pollution looks fairly similar between urban and rural sites, with no obvious systematic difference. This isn’t diagnostic, but it helps us <strong>anticipate what the model might show</strong>: we may find that group differences in bird density aren’t explained by air pollution alone.</p>
</section>
<section id="results-of-the-ancova-model" class="level3" data-number="11.3.5">
<h3 data-number="11.3.5" class="anchored" data-anchor-id="results-of-the-ancova-model"><span class="header-section-number">11.3.5</span> Results of the ANCOVA Model</h3>
<p>Now that we’ve explored the data visually, we can test our hypotheses formally using ANCOVA.</p>
<p><strong>Step 1: Fit the ANCOVA model</strong>.</p>
<p>Notice this is the same <code>aov()</code> call we’ve been using for one-way and factorial ANOVA all along. R doesn’t need a special “ANCOVA function”: once <code>AirPollution</code> is numeric instead of a factor, <code>aov()</code> handles the continuous covariate automatically.</p>
<p><code>ancova &lt;- aov(BirdDensity ~ AirPollution * AreaType, data = data)</code></p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>ANCOVA Table</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">meansq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AirPollution</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2183.89</td>
<td style="text-align: right;">2183.89</td>
<td style="text-align: right;">88.57</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AreaType</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6450.54</td>
<td style="text-align: right;">6450.54</td>
<td style="text-align: right;">261.60</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AirPollution:AreaType</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">269.14</td>
<td style="text-align: right;">269.14</td>
<td style="text-align: right;">10.91</td>
<td style="text-align: right;">0.0011</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">4833.03</td>
<td style="text-align: right;">24.66</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Step 2: Interpret each term in light of the hypotheses</strong></p>
<p><strong>0. Omnibus (adjusted means)</strong> :</p>
<p><span class="math inline">\(H_{0}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p>The overall ANCOVA test examines whether adjusted means differ between groups after accounting for the covariate.</p>
<p>Because we included an interaction term, this omnibus test is <strong>decomposed</strong> into two parts:</p>
<ul>
<li><p>the <strong>interaction</strong> (slope difference), and</p></li>
<li><p>the <strong>main effects</strong> (covariate and group).</p></li>
</ul>
<p>The ANCOVA table above has no row labeled “omnibus,” and no single <span class="math inline">\(p\)</span>-value that answers this test on its own. So we interpret the omnibus test through the interaction and main-effect rows that are actually in the table, not as a separate line item.</p>
<p><strong>1. Interaction (slope difference)</strong>:</p>
<p><span class="math inline">\(H_{0,1}: \beta_{\text{interaction}} = 0\)</span></p>
<p>The interaction between air pollution and area type is <strong>significant</strong> (<span class="math inline">\(p = .001\)</span>).</p>
<p>Reject <span class="math inline">\(H_{0,1}\)</span> → our slopes are not parallel. Air pollution’s relationship with bird density depends on area type.</p>
<p><strong>2. Covariate (main effect of Air Pollution)</strong></p>
<p>Although not a formal ANCOVA hypothesis, this term tests whether air pollution predicts bird density <em>on average</em>, across both groups.</p>
<p>It is <strong>significant</strong> (<span class="math inline">\(p &lt; .001\)</span>): bird density falls as pollution rises.</p>
<p><strong>3. Group (main effect of Area Type)</strong>: <span class="math inline">\(H_{0,2}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p>Area type is <strong>significant</strong> (<span class="math inline">\(p &lt; .001\)</span>), suggesting lower average bird density in urban areas.</p>
<p>However, because the interaction is significant, this group difference changes with air pollution level, so it should be interpreted conditionally, not as a single overall difference.</p>
<p>Reject <span class="math inline">\(H_{0,2}\)</span> with caution.</p>
<p><strong>Step 3: Examine regression coefficients</strong></p>
<p>We can also fit the same model using <code>lm()</code> to view the <strong>regression coefficients</strong> directly.</p>
<p>This shows how each term contributes to predicting bird density and corresponds to the hypothesis tests we just discussed.</p>
<p><code>ancova_lm &lt;- lm(BirdDensity ~ AirPollution * AreaType, data = data)</code></p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Linear Model Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">41.784</td>
<td style="text-align: right;">1.310</td>
<td style="text-align: right;">31.90</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution</td>
<td style="text-align: right;">-0.069</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">-5.07</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AreaTypeUrban</td>
<td style="text-align: right;">-5.909</td>
<td style="text-align: right;">1.802</td>
<td style="text-align: right;">-3.28</td>
<td style="text-align: right;">0.0012</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution:AreaTypeUrban</td>
<td style="text-align: right;">-0.064</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">-3.30</td>
<td style="text-align: right;">0.0011</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>R automatically converts the categorical <code>AreaType</code> variable into a 0/1 indicator behind the scenes, exactly the <span class="math inline">\(x_c\)</span> switch from the detour earlier in this chapter. It picks one level (here, “Rural,” alphabetically first) as the <strong>reference</strong>, and every coefficient involving <code>AreaType</code> is interpreted relative to that reference. That’s why you see a coefficient called <code>AreaTypeUrban</code> but no separate <code>AreaTypeRural</code> term.</p>
<p>These coefficients give the <em>direction</em> and <em>magnitude</em> of each effect:</p>
<ul>
<li><strong>(Intercept):</strong> estimated mean bird density for rural sites (the reference group) when air pollution is zero.</li>
<li><strong>AirPollution:</strong> slope of the relationship between pollution and bird density in rural sites.</li>
<li><strong>AreaTypeUrban:</strong> difference in intercept between urban and rural areas.</li>
<li><strong>AirPollution:AreaTypeUrban:</strong> difference in slope between urban and rural areas (the interaction).</li>
</ul>
<p><strong>Step 4: Visualize the interaction</strong></p>
<p>As always, plotting helps confirm what the model tells us.</p>
<p>A scatter plot with fitted regression lines (<a href="#fig-11ancovalines">Figure&nbsp;<span>11.4</span></a>) lets us see how air pollution relates to bird density for each area type.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-11ancovalines" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="11-ANCOVA_files/figure-html/fig-11ancovalines-1.png" class="img-fluid figure-img" style="width:75.0%" alt="Scatter plot of bird density against air pollution, colored by area type, with separate straight fitted lines for rural and urban sites. Both slope downward, and the urban line is noticeably steeper, so the two lines diverge as pollution increases."></p>
<figcaption class="figure-caption">Figure&nbsp;11.4: Bird density against air pollution, with a separate fitted line for each area type. Both lines slope down, but the urban line falls about twice as steeply, which is what the interaction term tests.</figcaption>
</figure>
</div>
</div>
</div>
<p>Here, the slopes differ by area type, illustrating the <strong>significant interaction</strong> we detected statistically. Both lines slope downward, so pollution is associated with fewer birds in both settings, but the urban line drops roughly twice as fast. The two lines start close together at low pollution and pull apart as pollution rises, which is exactly what a slope difference looks like.</p>
<p>You’ll also notice real scatter around each line, which makes sense: our overall <span class="math inline">\(R^2\)</span> is <strong>0.65</strong>.</p>
<p>Remember, <span class="math inline">\(R^2\)</span> represents the <strong>proportion of variance in bird density explained by the model</strong>.</p>
<p>So about <strong>65% of the variation</strong> in bird density is explained by air pollution, area type, and their interaction.</p>
<p>The remaining 35% reflects other factors, measurement noise, or natural ecological variability not captured by this simple model. That is a strong fit by the standards of field data, and it is strong here partly because this is a synthetic dataset built to illustrate the method. Real environmental data are usually messier.</p>
<p><strong>Step 5: Centering the covariate</strong></p>
<p>Interpreting intercepts at <span class="math inline">\(x = 0\)</span> can be misleading when “zero pollution” isn’t meaningful.</p>
<p>By centering the covariate (subtracting its mean), we make the intercept represent <strong>average bird density at mean air pollution</strong> instead.</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Centered ANCOVA Model Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">35.828</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution_c</td>
<td style="text-align: right;">-0.069</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AreaTypeUrban</td>
<td style="text-align: right;">-11.385</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution_c:AreaTypeUrban</td>
<td style="text-align: right;">-0.064</td>
<td style="text-align: right;">0.0011</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>This re-centering doesn’t change the slopes or <span class="math inline">\(p\)</span>-values. It just shifts the intercepts, making them easier to interpret.</p>
<p><strong>Interpreting the Centered Model</strong></p>
<p>Notice that the coefficients for <code>AirPollution_c</code> (–0.069) and <code>AirPollution_c:AreaTypeUrban</code> (–0.064) are <strong>identical</strong> to the slopes we estimated before centering.</p>
<p>Only the <strong>intercept</strong> and the <strong>AreaTypeUrban</strong> (group difference) term have changed. They are now interpreted at the <em>mean pollution level</em> (about 86 units) instead of pollution = 0.</p>
<ul>
<li><p><strong>Intercept (35.8):</strong> Predicted bird density for <strong>rural sites</strong> at <em>average air pollution</em>.</p></li>
<li><p><strong>AreaTypeUrban (–11.4):</strong> Urban sites have, on average, <strong>about 11 fewer birds</strong> than rural sites <em>at the same mean pollution level</em>.</p></li>
<li><p><strong>AirPollution_c (–0.069):</strong> Slope for rural sites: bird density falls by about 0.07 birds for each additional unit of pollution.</p></li>
<li><p><strong>Interaction (–0.064):</strong> Difference in slopes between groups. The urban slope = <span class="math inline">\(-0.069 + (-0.064) \approx\)</span> <strong>–0.13</strong>, roughly twice as steep a decline as in rural sites.</p></li>
</ul>
<p>Note how much the group difference changed when we centered: –5.9 before, –11.4 after. That is not a contradiction. Uncentered, the term compares groups at pollution = 0, a value we never actually observed. Centered, it compares them at average pollution, which is a real place in the data. When slopes differ, “the group difference” is not one number; it depends on where along the covariate you look.</p>
<p><strong>Step 6: Summarize and Interpret</strong></p>
<p>The significant interaction shows that <strong>air pollution’s effect on bird density depends on area type</strong>: bird density declines with pollution in both settings, but the decline is about twice as steep in urban sites.</p>
<p>Because the interaction is significant, we focus on these <strong>different slopes</strong>, not on adjusted mean differences.</p>
<p>If the interaction had <strong>not</strong> been significant, we would instead drop the interaction term and interpret the <strong>parallel slopes model</strong>, comparing adjusted means between groups.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Important: Results reporting">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important: Results reporting
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p>Results from the ANCOVA indicated that air pollution’s effect on bird density depended on area type, <em>F</em>(1, 196) = 10.91, <em>p</em> = .001. Bird density declined with increasing pollution in both settings, but the decline was roughly twice as steep at urban sites (slope -0.13) as at rural ones (slope -0.07). These findings suggest that <strong>urbanization intensifies the pollution-bird density relationship</strong> and may point toward the need for area-specific conservation strategies.</p>
</blockquote>
</div>
</div>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">11.4</span> Chapter Summary</h2>
<p><strong>Why it matters.</strong> Environmental relationships rarely play out identically everywhere. ANCOVA is the tool for a specific, recurring question: does a continuous relationship, like pollution’s effect on some outcome, hold the same way across different groups, or change from one group to the next?</p>
<p><strong>Core ideas</strong></p>
<ul>
<li><strong>ANCOVA is regression plus a categorical factor.</strong> It takes the familiar <span class="math inline">\(y=\beta_0+\beta_1 x+\varepsilon\)</span> line and lets a categorical grouping shift the intercept, the slope, or both, using the same indicator-variable machinery that underlies every linear model in this book.</li>
<li><strong>Check the interaction first.</strong> Before anything else, test whether the groups’ slopes differ (<span class="math inline">\(H_0:\beta_3=0\)</span>). That answer decides how everything else gets interpreted.</li>
<li><strong>A significant interaction means report the two lines, not one number.</strong> If slopes differ, describe how the relationship changes by group instead of collapsing to a single adjusted-mean comparison, which assumes parallel lines that don’t actually hold here.</li>
<li><strong>If slopes are parallel, compare adjusted means.</strong> Drop the interaction term and test whether the groups’ intercepts differ once the covariate is accounted for.</li>
<li><strong>Center the covariate when the intercept should mean something.</strong> Left uncentered, the intercept describes the groups at covariate = 0, a value the data may never actually contain.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./10-FactorialANOVA.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>