<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mallory L. Barnes">

<title>12&nbsp; Analysis of Covariance (ANCOVA) – Answering questions with data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./13-Thinking.html" rel="next">
<link href="./11-MixedANOVA.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="12&nbsp; Analysis of Covariance (ANCOVA) – Answering questions with data">
<meta property="og:description" content="">
<meta property="og:image" content="12-ANCOVA_files/figure-html/unnamed-chunk-3-1.png">
<meta property="og:site_name" content="Answering questions with data">
<meta name="twitter:title" content="12&nbsp; Analysis of Covariance (ANCOVA) – Answering questions with data">
<meta name="twitter:description" content="A free textbook teaching introductory statistics for environmental science graduate students, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta name="twitter:image" content="imgs/TextbookCover.png">
<meta name="twitter:site" content="@mallory_barnes">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-ANCOVA.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Libraries (top)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malloryb/statistics_E538" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Hypothesis_Testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-RMANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-MixedANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-ANCOVA.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Libraries (top)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Thinking about answering questions with data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-Gifs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">GIFs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#linear-models-lms" id="toc-linear-models-lms" class="nav-link active" data-scroll-target="#linear-models-lms"><span class="header-section-number">12.1</span> Linear Models (LMs)</a>
  <ul class="collapse">
  <li><a href="#model-statements" id="toc-model-statements" class="nav-link" data-scroll-target="#model-statements"><span class="header-section-number">12.1.1</span> Model Statements:</a></li>
  <li><a href="#flexibility-and-applicability-of-lms" id="toc-flexibility-and-applicability-of-lms" class="nav-link" data-scroll-target="#flexibility-and-applicability-of-lms"><span class="header-section-number">12.1.2</span> Flexibility and Applicability of LMs</a></li>
  <li><a href="#understanding-anova-as-a-linear-model" id="toc-understanding-anova-as-a-linear-model" class="nav-link" data-scroll-target="#understanding-anova-as-a-linear-model"><span class="header-section-number">12.1.3</span> Understanding ANOVA as a linear model:</a></li>
  </ul></li>
  <li><a href="#moving-beyond-regression-and-anova-to-ancova" id="toc-moving-beyond-regression-and-anova-to-ancova" class="nav-link" data-scroll-target="#moving-beyond-regression-and-anova-to-ancova"><span class="header-section-number">12.2</span> Moving Beyond Regression and ANOVA to ANCOVA</a>
  <ul class="collapse">
  <li><a href="#conceptual-background-for-ancova" id="toc-conceptual-background-for-ancova" class="nav-link" data-scroll-target="#conceptual-background-for-ancova"><span class="header-section-number">12.2.1</span> Conceptual Background for ANCOVA</a></li>
  </ul></li>
  <li><a href="#dummy-indicator-variables-and-how-they-work" id="toc-dummy-indicator-variables-and-how-they-work" class="nav-link" data-scroll-target="#dummy-indicator-variables-and-how-they-work"><span class="header-section-number">12.3</span> Dummy (Indicator) Variables and How They Work</a>
  <ul class="collapse">
  <li><a href="#indicator-variables-in-action" id="toc-indicator-variables-in-action" class="nav-link" data-scroll-target="#indicator-variables-in-action"><span class="header-section-number">12.3.1</span> Indicator Variables in Action</a></li>
  <li><a href="#interaction-term-in-linear-models" id="toc-interaction-term-in-linear-models" class="nav-link" data-scroll-target="#interaction-term-in-linear-models"><span class="header-section-number">12.3.2</span> Interaction Term in Linear Models</a></li>
  <li><a href="#five-versions-of-the-linear-model" id="toc-five-versions-of-the-linear-model" class="nav-link" data-scroll-target="#five-versions-of-the-linear-model"><span class="header-section-number">12.3.3</span> Five Versions of the Linear Model</a></li>
  <li><a href="#terminology-in-lms" id="toc-terminology-in-lms" class="nav-link" data-scroll-target="#terminology-in-lms"><span class="header-section-number">12.3.4</span> Terminology in LMs</a></li>
  </ul></li>
  <li><a href="#what-ancova-is" id="toc-what-ancova-is" class="nav-link" data-scroll-target="#what-ancova-is"><span class="header-section-number">12.4</span> What ANCOVA Is</a>
  <ul class="collapse">
  <li><a href="#the-null-hypothesis-in-ancova" id="toc-the-null-hypothesis-in-ancova" class="nav-link" data-scroll-target="#the-null-hypothesis-in-ancova"><span class="header-section-number">12.4.1</span> The Null Hypothesis in ANCOVA</a></li>
  <li><a href="#conducting-the-test" id="toc-conducting-the-test" class="nav-link" data-scroll-target="#conducting-the-test"><span class="header-section-number">12.4.2</span> Conducting the Test</a></li>
  </ul></li>
  <li><a href="#full-ancova-example" id="toc-full-ancova-example" class="nav-link" data-scroll-target="#full-ancova-example"><span class="header-section-number">12.5</span> Full ANCOVA Example</a>
  <ul class="collapse">
  <li><a href="#question" id="toc-question" class="nav-link" data-scroll-target="#question"><span class="header-section-number">12.5.1</span> Question</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model"><span class="header-section-number">12.5.2</span> Model</a></li>
  <li><a href="#why-were-running-the-ancova" id="toc-why-were-running-the-ancova" class="nav-link" data-scroll-target="#why-were-running-the-ancova"><span class="header-section-number">12.5.3</span> Why We’re Running the ANCOVA</a></li>
  <li><a href="#null-and-alternative-hypotheses-in-our-example-ancova" id="toc-null-and-alternative-hypotheses-in-our-example-ancova" class="nav-link" data-scroll-target="#null-and-alternative-hypotheses-in-our-example-ancova"><span class="header-section-number">12.5.4</span> Null and Alternative Hypotheses in our example ANCOVA</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">12.5.5</span> Analysis</a></li>
  <li><a href="#results-of-the-ancova-model" id="toc-results-of-the-ancova-model" class="nav-link" data-scroll-target="#results-of-the-ancova-model"><span class="header-section-number">12.5.6</span> Results of the ANCOVA Model</a></li>
  </ul></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">12.6</span> Chapter Summary</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/12-ANCOVA.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Analysis of Covariance (ANCOVA)</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mallory L. Barnes </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 14, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<p><strong>ANCOVA</strong> uses the same linear model ideas from regression, with one continuous covariate and one categorical factor. We first test whether groups have different <strong>slopes</strong> with respect to the covariate, then, only if slopes are parallel, we test whether groups differ in <strong>adjusted means</strong>.</p>
<section id="linear-models-lms" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="linear-models-lms"><span class="header-section-number">12.1</span> Linear Models (LMs)</h2>
<p>Linear Models are a class of models that encompass various types of statistical analyses, including ANOVA, and regression. They’re flexible enough to handle different types of data and relationships. These assume the response variable is <strong>continuous and normally distributed</strong>. They include <em>t-tests, ANOVA, regression,</em> and <em>ANCOVA</em> as special cases.</p>
<p>A genera <strong>linear model</strong> is the common framework that includes ANOVA, regression, and ANCOVA. Each uses the same residual-based logic: a continuous response <span class="math inline">\(Y\)</span> is modeled as a combination of one or more predictors plus error. We’ve seen a few different cases so far:</p>
<ul>
<li><strong>No Groups and No Relationships (H0):</strong>
<ul>
<li>This scenario often emerges when our ANOVA or regression analysis yields non-significant results.</li>
<li><strong>What We Report:</strong> The grand mean and overall variance or standard deviation. Alternatively, we can use a confidence interval to encapsulate this information.</li>
</ul></li>
<li><strong>Two or More Categories with Significantly Different Means (t-test, ANOVA):</strong>
<ul>
<li>Here, we delve into data where group means are distinct and significant.</li>
<li><strong>What We Report:</strong> Group means. In classical ANOVA, we might report a common variance or standard deviation, or opt for group-specific measures (potentially through confidence intervals), ensuring to note that variances are not significantly different. With Welch’s t-test, we focus on group-specific variance or standard deviation.</li>
</ul></li>
<li><strong>Two Continuous Variables with a Significant Linear or Monotonic Relationship (Regression):</strong>
<ul>
<li>This model applies when there’s a significant linear relationship between two continuous variables.</li>
<li><strong>What We Report:</strong> The equation of the regression line, along with its confidence limits. We can also select specific x-values and provide confidence intervals for the predicted y-values at those points.</li>
</ul></li>
</ul>
<section id="model-statements" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="model-statements"><span class="header-section-number">12.1.1</span> Model Statements:</h3>
<ul>
<li><strong>No Groups/Relationships:</strong> <span class="math inline">\(y \sim N(\mu, \sigma^2)\)</span></li>
<li><strong>Categories with Different Means:</strong> <span class="math inline">\(y_{i,j} = \mu + \tau_i + \epsilon\)</span> (t-test allows for unequal variance: <span class="math inline">\(y_{i,j} = \mu + \tau_i + \epsilon_i\)</span>)</li>
<li><strong>Linear Relationship:</strong> <span class="math inline">\(y = \beta_0 + \beta_1x + \epsilon\)</span></li>
</ul>
<p>Linear models handle continuous <span class="math inline">\(y\)</span>; for counts or non-Gaussian <span class="math inline">\(y\)</span>, we use generalized linear models (not covered here).</p>
</section>
<section id="flexibility-and-applicability-of-lms" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="flexibility-and-applicability-of-lms"><span class="header-section-number">12.1.2</span> Flexibility and Applicability of LMs</h3>
<p>LMs enable us to model more complex relationships beyond the basic categorical X with continuous Y (as in t-tests and ANOVA) or continuous X with continuous Y (as in regression). They can handle diverse data types and model relationships that aren’t strictly linear, making them crucial for studying environmental systems.</p>
<p>So far, in our exploration of parametric tests, we have primarily focused on two types of relationships:</p>
<ul>
<li><strong>A categorical X and a continuous Y:</strong> This includes tests like the t-test and ANOVA.</li>
<li><strong>A continuous X and a continuous Y:</strong> This is typically analyzed using linear regression.</li>
</ul>
</section>
<section id="understanding-anova-as-a-linear-model" class="level3" data-number="12.1.3">
<h3 data-number="12.1.3" class="anchored" data-anchor-id="understanding-anova-as-a-linear-model"><span class="header-section-number">12.1.3</span> Understanding ANOVA as a linear model:</h3>
<p>ANOVA, or Analysis of Variance, is traditionally viewed as a technique to compare means across multiple groups. However, at its core, ANOVA is a linear model. It’s a special case where the predictors are categorical, not continuous. This distinction is important but subtle.</p>
<p>Example: Imagine a researcher is exploring the effects of metal contamination on the species richness of sessile marine invertebrates. They’re particularly interested in the impact of copper and the orientation of the substrate on which these organisms live. To investigate this, they conduct a factorial experiment, measuring species richness across different levels of copper enrichment (None, Low, High) and substrate orientation (Vertical, Horizontal). This setup allows us to not only consider each factor separately but also examine their potential interaction.</p>
<p>The ANOVA framework provides three null hypotheses to test:</p>
<ol type="1">
<li><p>There are no differences in species richness across the copper levels.</p></li>
<li><p>There are no differences in species richness between substrate orientations.</p></li>
<li><p>There is no interaction effect between copper levels and substrate orientation.</p></li>
</ol>
<p>These hypotheses can be represented in a linear model as follows:</p>
<p><span class="math inline">\(y_{ijk} = \beta_0 + \beta_{Copper_i} + \beta_{Orientation_j} + \beta_{Copper \times Orientation_{ij}} + \varepsilon_{ijk}\)</span></p>
<p>Here, <span class="math inline">\(\beta_0\)</span> is the grand mean (intercept), <span class="math inline">\(\beta_{Copper_i}\)</span> and <span class="math inline">\(\beta_{Orientation_j}\)</span> are the main effects of the copper levels and orientation, respectively, and <span class="math inline">\(\beta_{Copper \times Orientation_{ij}}\)</span> represents the interaction between these factors. The <span class="math inline">\(\varepsilon_{ijk}\)</span> term captures the residual variance, or the random deviation of each observation from the model prediction. The significance of each beta coefficient is tested to determine if it makes a meaningful contribution to the model.</p>
<p>When conducting an ANOVA, we’re essentially fitting a linear model with categorical predictors. These predictors are represented by beta coefficients in our model, which show the unique contribution of each factor (like copper levels or substrate orientation) to the outcome variable (such as species richness). The critical question we ask is whether each beta coefficient is significant—does it make a meaningful difference to our model?</p>
<p>We test each term with an <span class="math inline">\(F\)</span>-test. The F-statistic is a ratio that compares the amount of variance explained by a particular factor to the variance not explained by the model (within-group variance or error). A higher F-statistic indicates that the factor explains a significant portion of the variability in the outcome variable, while a lower F-statistic suggests that the factor does not contribute much to our understanding of the outcome variable.</p>
<p><span class="math inline">\(F = \frac{MS_{Treatment}}{MS_{Error}}\)</span>.</p>
<p>In an ANOVA with two factors, we calculate the F-statistic for each factor and their interaction. Significance is tested with <span class="math inline">\(F\)</span>; interpretation focuses on planned factors and interactions. If <span class="math inline">\(F\)</span> is significant, we keep the beta coefficient in our model. If not, we may consider omitting it for a simpler model.</p>
<p>It turns out that ANOVAs are just a type of linear model in which the predictor variable is categorical. In practice, we can perform ANOVA using the <code>lm()</code> function in R, treating the categorical predictors as factors. This allows us to use the familiar beta notation and interpret ANOVA as a linear regression model with categorical predictors.</p>
</section>
</section>
<section id="moving-beyond-regression-and-anova-to-ancova" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="moving-beyond-regression-and-anova-to-ancova"><span class="header-section-number">12.2</span> Moving Beyond Regression and ANOVA to ANCOVA</h2>
<p>As we’ve explored statistical modeling, we’ve understood the power of both regression and ANOVA. Now, let’s merge them. ANCOVA allows us to examine relationships across different categories.</p>
<p>Consider these questions that may arise in environmental research:</p>
<ul>
<li><p>Are dbh (Diameter at Breast Height) and height related similarly for tulip poplars and oaks?</p></li>
<li><p>Are biomass and BTUs (British Thermal Units) related similarly for corn stover and Miscanthus?</p></li>
<li><p>Does the exposure to PFAS correlate with the lifetime incidence of cancer uniformly across low- and high-income American populations?</p></li>
</ul>
<p>This specific subsection of general linear models is known as <strong>Analysis of Covariance – ANCOVA</strong>. ANCOVA is a linear model with one continuous covariate and one categorical factor; it tests group differences <strong>after</strong> adjusting for the covariate and, first, whether slopes differ across groups.</p>
<hr>
<section id="conceptual-background-for-ancova" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="conceptual-background-for-ancova"><span class="header-section-number">12.2.1</span> Conceptual Background for ANCOVA</h3>
<p>At its core, ANCOVA checks whether groups share the same line or whether each group needs its own slope and intercept. To represent those group-specific lines within a single linear model, we use indicator (dummy) variables. Indicators allow the model to “turn on” shifts in intercept or slope for each group, which is exactly the machinery ANCOVA relies on.</p>
</section>
</section>
<section id="dummy-indicator-variables-and-how-they-work" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="dummy-indicator-variables-and-how-they-work"><span class="header-section-number">12.3</span> Dummy (Indicator) Variables and How They Work</h2>
<p>Categorical predictors can be included in a linear model by coding them as <strong>indicator variables</strong>.</p>
<p>For a factor with <span class="math inline">\(k\)</span> groups, include <span class="math inline">\(k-1\)</span> indicators; the omitted group is the <strong>reference</strong>, and coefficients are interpreted relative to it.</p>
<p><strong>Example:</strong> modeling <strong>algal biomass</strong> across three nutrient treatments—Control, Low N, and High N.</p>
<p>Use two indicators, <code>LowN</code> and <code>HighN</code>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Treatment</th>
<th style="text-align: right;">LowN</th>
<th style="text-align: right;">HighN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>Low N</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>High N</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
<p>The model is <span class="math inline">\(y=\beta_0+\beta_1,\text{LowN}+\beta_2,\text{HighN}+\varepsilon\)</span>, where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the mean for the Control group (reference),</li>
<li><span class="math inline">\(\beta_1\)</span> is Low N minus Control,</li>
<li><span class="math inline">\(\beta_2\)</span> is High N minus Control.</li>
</ul>
<p>In R, <code>lm(y ~ Treatment)</code> creates these indicators automatically.</p>
<section id="indicator-variables-in-action" class="level3" data-number="12.3.1">
<h3 data-number="12.3.1" class="anchored" data-anchor-id="indicator-variables-in-action"><span class="header-section-number">12.3.1</span> Indicator Variables in Action</h3>
<p>When an indicator variable is turned on (set to 1), it activates the terms multiplied by that variable. This can change the intercept, the slope, or both, depending on where the indicator appears in the model.</p>
<p>Consider two predictors: a continuous variable <span class="math inline">\(x_l\)</span> and an indicator <span class="math inline">\(x_c\)</span> (0 or 1). Use this model:</p>
<p><span class="math inline">\(y = 2x_l + 1(x_l x_c) - 7x_c + 3\)</span></p>
<p><strong>When <span class="math inline">\(x_c = 0\)</span></strong> (indicator off), only baseline terms are active: <span class="math inline">\(y = 2x_l + 3\)</span> Slope = 2, intercept = 3.</p>
<p><strong>When <span class="math inline">\(x_c = 1\)</span></strong> (indicator on), new terms activate: <span class="math inline">\(y = (2x_l + 3) + (1x_l - 7) = 3x_l - 4\)</span> Slope = 3, intercept = −4.</p>
<p>Turning on the indicator adds <strong>+1 to the slope</strong> and <strong>–7 to the intercept</strong>.</p>
<p>This is how linear models represent different groups: the indicator (<span class="math inline">\(x_c\)</span>) and its interaction with <span class="math inline">\(x_l\)</span> let the equation shift the intercept and slope for each group.</p>
<p>Later, ANCOVA will use this same logic to formally test:</p>
<ul>
<li>whether the <strong>slopes differ</strong> between groups (the <span class="math inline">\(x_lx_c\)</span> term), and</li>
<li>if not, whether the <strong>adjusted means</strong> differ (the <span class="math inline">\(x_c\)</span> term).</li>
</ul>
<section id="visualizing-the-effect" class="level4" data-number="12.3.1.1">
<h4 data-number="12.3.1.1" class="anchored" data-anchor-id="visualizing-the-effect"><span class="header-section-number">12.3.1.1</span> Visualizing the Effect</h4>
<p>The R plots below demonstrate the change in the regression line when the indicator variable is toggled between being active (<code>xc = 1</code>) and inactive (<code>xc = 0</code>).</p>
<p><strong>When <code>xc</code> = 0:</strong></p>
<p><em>Equation Simplified:</em> <code>y = 2xl + 3</code></p>
<p><strong>When <code>xc</code> = 1:</strong></p>
<p><em>Equation Modified:</em> <code>y = (2xl + 3) + (1xl - 7)</code></p>
<p>The left plot shows the line when the indicator is <strong>off</strong> (<span class="math inline">\(x_c = 0\)</span>). The categorical variable has no influence here, so we see only the baseline slope and intercept.</p>
<p>The right plot shows the line when the indicator is <strong>on</strong> (<span class="math inline">\(x_c = 1\)</span>). The extra terms activate, and the categorical variable now changes both the slope and intercept, producing a different line for the second group.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="12-ANCOVA_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key idea:</strong> to change only intercepts, include <span class="math inline">\(x_c\)</span>; to change slopes, include <span class="math inline">\(x_l x_c\)</span>; to change both, include both. The corresponding parameters in a general model <span class="math inline">\(y=\beta_0+\beta_1 x_l+\beta_2 x_c+\beta_3(x_l x_c)+\varepsilon\)</span> are <span class="math inline">\(\beta_2\)</span> (intercept shift) and <span class="math inline">\(\beta_3\)</span> (slope difference).</p>
</section>
</section>
<section id="interaction-term-in-linear-models" class="level3" data-number="12.3.2">
<h3 data-number="12.3.2" class="anchored" data-anchor-id="interaction-term-in-linear-models"><span class="header-section-number">12.3.2</span> Interaction Term in Linear Models</h3>
<p><strong>Interaction terms</strong> tell us whether the relationship between one predictor and the response changes across levels of another predictor.</p>
<p>In other words: does the slope of <span class="math inline">\(x_l\)</span> depend on <span class="math inline">\(x_c\)</span>?”</p>
<p><strong>Model Equation Explained:</strong></p>
<p>Let’s break down a typical equation:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1x_l + \beta_2x_c + \beta_3x_lx_c + \epsilon
\]</span></p>
<p>the term <span class="math inline">\(x_l x_c\)</span> is the <strong>interaction</strong>, and <span class="math inline">\(\beta_3\)</span> is its coefficient.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 81%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y\)</span></td>
<td>response variable (e.g., plant growth)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_0\)</span></td>
<td>intercept: expected value when <span class="math inline">\(x_l\)</span> and <span class="math inline">\(x_c\)</span> are zero</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_1 x_l\)</span></td>
<td>effect of the continuous predictor (main effect of <span class="math inline">\(x_l\)</span>)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_2 x_c\)</span></td>
<td>effect of the categorical predictor (main effect of <span class="math inline">\(x_c\)</span>)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_3 x_l x_c\)</span></td>
<td><strong>interaction:</strong> how the slope of <span class="math inline">\(x_l\)</span> changes across categories of <span class="math inline">\(x_c\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\varepsilon\)</span></td>
<td>residual variation not explained by the model</td>
</tr>
</tbody>
</table>
<p>If <span class="math inline">\(\beta_3\)</span> is significant, the slope of <span class="math inline">\(x_l\)</span> differs across groups.</p>
<p>If <span class="math inline">\(\beta_3\)</span> is not significant, the relationship between <span class="math inline">\(x_l\)</span> and <span class="math inline">\(y\)</span> is consistent across groups, and the lines are parallel.</p>
</section>
<section id="five-versions-of-the-linear-model" class="level3" data-number="12.3.3">
<h3 data-number="12.3.3" class="anchored" data-anchor-id="five-versions-of-the-linear-model"><span class="header-section-number">12.3.3</span> Five Versions of the Linear Model</h3>
<p>This is our most complex version of the linear model so far. Remember what we just learned in case #1, and how each simpler version (#2–5) nests within it.</p>
<ol type="1">
<li><p><strong>Full model with interaction (<span class="math inline">\(\beta_0, \beta_1, \beta_2, \beta_3\)</span>)</strong></p>
<ul>
<li><p>When both the categorical (<span class="math inline">\(x_c\)</span>) and continuous (<span class="math inline">\(x_l\)</span>) predictors are included, and the interaction term (<span class="math inline">\(\beta_3\)</span>) is significant, the model produces <strong>different slopes and intercepts</strong> for each group.</p></li>
<li><p>Equations:</p>
<ul>
<li>For <span class="math inline">\(x_c = 0\)</span>: <span class="math inline">\(y = \beta_0 + \beta_1x_l\)</span></li>
<li>For <span class="math inline">\(x_c = 1\)</span>: <span class="math inline">\(y = (\beta_0 + \beta_2) + (\beta_1 + \beta_3)x_l\)</span></li>
</ul></li>
</ul></li>
<li><p><strong>Model without interaction (<span class="math inline">\(\beta_0, \beta_1, \beta_2\)</span>)</strong></p>
<ul>
<li><p>If both predictors are significant but the interaction is not, the model simplifies to <strong>parallel lines</strong>—the slope of <span class="math inline">\(x_l\)</span> is the same across categories of <span class="math inline">\(x_c\)</span>, but intercepts differ.</p></li>
<li><p>Equations:</p>
<ul>
<li>For <span class="math inline">\(x_c = 0\)</span>: <span class="math inline">\(y = \beta_0 + \beta_1x_l\)</span></li>
<li>For <span class="math inline">\(x_c = 1\)</span>: <span class="math inline">\(y = (\beta_0 + \beta_2) + \beta_1x_l\)</span></li>
</ul></li>
</ul></li>
<li><p><strong>Simple linear regression (<span class="math inline">\(\beta_0, \beta_1\)</span>)</strong></p>
<ul>
<li>If only the continuous variable (<span class="math inline">\(x_l\)</span>) matters, the model reduces to a single regression line.</li>
<li>Equation: <span class="math inline">\(y = \beta_0 + \beta_1x_l\)</span></li>
</ul></li>
<li><p><strong>Two different means (t-test equivalent) (<span class="math inline">\(\beta_0, \beta_2\)</span>)</strong></p>
<ul>
<li><p>If only the categorical variable (<span class="math inline">\(x_c\)</span>) matters, the model compares two means—just like a t-test.</p></li>
<li><p>Equations:</p>
<ul>
<li>For <span class="math inline">\(x_c = 0\)</span>: <span class="math inline">\(y = \beta_0\)</span></li>
<li>For <span class="math inline">\(x_c = 1\)</span>: <span class="math inline">\(y = \beta_0 + \beta_2\)</span></li>
</ul></li>
</ul></li>
<li><p><strong>Single mean (one-sample model) (<span class="math inline">\(\beta_0\)</span>)</strong></p>
<ul>
<li>If neither variable contributes, the model collapses to a single overall mean.</li>
<li>Equation: <span class="math inline">\(y = \beta_0\)</span></li>
</ul></li>
</ol>
</section>
<section id="terminology-in-lms" class="level3" data-number="12.3.4">
<h3 data-number="12.3.4" class="anchored" data-anchor-id="terminology-in-lms"><span class="header-section-number">12.3.4</span> Terminology in LMs</h3>
<p>Here are some key terms:</p>
<ul>
<li><p><strong>Fixed Factor:</strong> This refers to a categorical variable with specific, predefined categories. For example, if you’re studying the effect of different seasons (spring, summer, autumn, winter) on plant growth, ‘season’ is a fixed factor because it represents specific, distinct categories of interest.</p></li>
<li><p><strong>Random Factor:</strong> This is a categorical variable where the categories represent a random sample from a larger population. For instance, if you’re examining the output quality from different machines in a factory, and these machines are randomly selected from a larger set, then ‘machine’ is a random factor.</p></li>
<li><p><strong>Covariate:</strong> This is your continuous variable that varies along with the dependent variable (Y). In environmental studies, this could be something like temperature, rainfall, or pollution levels, which you suspect might influence your outcome of interest (like species distribution or plant growth).</p></li>
</ul>
<hr>
</section>
</section>
<section id="what-ancova-is" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="what-ancova-is"><span class="header-section-number">12.4</span> What ANCOVA Is</h2>
<p><strong>Analysis of Covariance (ANCOVA)</strong> extends ANOVA by adding a continuous predictor. It fits a linear model with both a categorical factor and a covariate, allowing us to compare groups <strong>and</strong> account for how the response changes with the continuous variable.</p>
<p>The covariate may or may not be the main factor of interest. Sometimes we adjust for it, and sometimes we want to see whether its relationship with the response differs across groups.</p>
<p>For ANCOVA, you need:</p>
<ol type="1">
<li>A continuous dependent variable (the main effect you’re studying)</li>
<li>At least one continuous independent variable (covariate)</li>
<li>At least one categorical independent variable (which can be either a fixed or random factor)</li>
</ol>
<section id="the-null-hypothesis-in-ancova" class="level3" data-number="12.4.1">
<h3 data-number="12.4.1" class="anchored" data-anchor-id="the-null-hypothesis-in-ancova"><span class="header-section-number">12.4.1</span> The Null Hypothesis in ANCOVA</h3>
<p><strong>Why this matters.</strong> ANCOVA asks two questions in order. First, do groups have the <strong>same slope</strong> for the covariate–response relation. Only if slopes are the same do we ask whether groups differ in <strong>adjusted means</strong> after controlling for the covariate.</p>
<p><strong>Model.</strong> For one covariate (x) and a two-level group indicator <span class="math inline">\(g\in{0,1}\)</span>,</p>
<p><span class="math inline">\(y=\beta_0+\beta_1 x+\beta_2 g+\beta_3(x\times g)+\varepsilon .\)</span></p>
<p><strong>Step 1: Slopes equal across groups?</strong> This tests whether the covariate effect is the same in each group.</p>
<ul>
<li>Null: <span class="math inline">\(H_{0,\text{int}}:\beta_3=0\)</span> (parallel lines, same slope)</li>
<li>Alternative: <span class="math inline">\(H_{A,\text{int}}:\beta_3\neq 0\)</span> (non-parallel lines, different slopes)</li>
</ul>
<p><strong>Interpretation if rejected.</strong> Report the two fitted lines and describe how the slope differs by group. Do not test adjusted means, because the idea of a single adjusted mean per group assumes parallel slopes.</p>
<p><strong>Step 2: Adjusted means equal?</strong> <em>(only if Step 1 retained parallel slopes)</em> Fit the model without the interaction,</p>
<p><span class="math inline">\(y=\beta_0+\beta_1 x+\beta_2 g+\varepsilon .\)</span></p>
<ul>
<li>Null: <span class="math inline">\(H_{0,\text{group}}:\beta_2=0\)</span> (no difference in adjusted means)</li>
<li>Alternative: <span class="math inline">\(H_{A,\text{group}}:\beta_2\neq 0\)</span></li>
</ul>
<p><strong>What the parameters mean.</strong></p>
<ul>
<li><span class="math inline">\(\beta_1\)</span>: common slope of <span class="math inline">\(y\)</span> on <span class="math inline">\(x\)</span> when slopes are parallel.</li>
<li><span class="math inline">\(\beta_2\)</span>: difference in group means <strong>after</strong> adjusting for <span class="math inline">\(x\)</span> (tested only when <span class="math inline">\(\beta_3=0\)</span>).</li>
<li><span class="math inline">\(\beta_3\)</span>: difference in slopes between groups.</li>
</ul>
<p><strong>Intercepts and centering.</strong> Intercepts are evaluated at <span class="math inline">\(x=0\)</span>. Compare intercepts only if you center the covariate, for example <span class="math inline">\(\tilde x=x-\bar x\)</span>, so that the intercepts represent group means at the average covariate value.</p>
<p><strong>What to report.</strong></p>
<ul>
<li>If <span class="math inline">\(x\times g\)</span> is significant: “The effect of <span class="math inline">\(x\)</span> differs by group,” then provide the two line equations and a figure with separate fitted lines.</li>
<li>If <span class="math inline">\(x\times g\)</span> is not significant: report the common slope <span class="math inline">\(\beta_1\)</span> and the adjusted group difference <span class="math inline">\(\beta_2\)</span>, with a figure showing parallel lines.</li>
</ul>
<p><strong>Common pitfalls.</strong></p>
<ul>
<li>Interpreting main effects when the interaction is significant.</li>
<li>Comparing raw intercepts when <span class="math inline">\(x\)</span> is not centered.</li>
<li>Treating adjusted means as meaningful when slopes are not parallel.</li>
</ul>
</section>
<section id="conducting-the-test" class="level3" data-number="12.4.2">
<h3 data-number="12.4.2" class="anchored" data-anchor-id="conducting-the-test"><span class="header-section-number">12.4.2</span> Conducting the Test</h3>
<p>When we run an ANCOVA, the output includes an <strong>omnibus F-test</strong>—a single test of whether there are any differences in the adjusted group means after accounting for the covariate.</p>
<p>If this test is <strong>significant</strong>, we reject the overall null hypothesis that all adjusted means are equal.</p>
<p><strong>What happens next:</strong> A significant omnibus test tells us that at least one group differs, but it doesn’t tell us <em>which</em> groups differ or <em>why</em>.</p>
<p>To interpret the result, we must <strong>decompose the omnibus effect</strong> into its components:</p>
<ol type="1">
<li><p><strong>Interaction (slope difference):</strong> Are the slopes of the covariate–response relationship the same across groups?</p></li>
<li><p><strong>Adjusted means (intercept difference):</strong> If the slopes are equal, do the groups still differ in their adjusted means?</p></li>
</ol>
<p>This two-step logic—testing slope equality first, then adjusted means—is central to ANCOVA and parallels how we follow a significant ANOVA with post-hoc comparisons.</p>
<p><strong>Interpreting the Findings:</strong></p>
<p>Rejecting the omnibus null indicates that the categorical factor affects the dependent variable <em>after controlling for the covariate</em>.</p>
<p>However, as always, statistical significance does not guarantee ecological or practical importance. The results should be interpreted in light of the study’s design, measurement precision, and the size of the observed effects.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>ANCOVA ASSUMPTIONS</strong></p>
<ul>
<li>Linearity within each group (covariate–response relation is linear).</li>
<li><strong>Homogeneity of slopes</strong> (test via interaction).</li>
<li>Independent observations.</li>
<li>Approximately normal residuals and similar variances across groups.</li>
<li>Covariate measured without substantial error and not affected by treatment</li>
</ul>
</div>
</div>
</section>
</section>
<section id="full-ancova-example" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="full-ancova-example"><span class="header-section-number">12.5</span> Full ANCOVA Example</h2>
<section id="question" class="level3" data-number="12.5.1">
<h3 data-number="12.5.1" class="anchored" data-anchor-id="question"><span class="header-section-number">12.5.1</span> Question</h3>
<p>Imagine we’re environmental scientists studying the impact of <strong>air pollution</strong> (a continuous variable) on <strong>bird species density</strong> (our dependent variable).</p>
<p>We want to know whether this relationship differs between <strong>urban</strong> and <strong>rural</strong> areas (our categorical variable).</p>
<p>For this purpose, we’ve created a synthetic dataset to model the scenario.</p>
</section>
<section id="model" class="level3" data-number="12.5.2">
<h3 data-number="12.5.2" class="anchored" data-anchor-id="model"><span class="header-section-number">12.5.2</span> Model</h3>
<p>We’ll fit an ANCOVA model to test whether location type influences bird density <strong>after accounting for</strong> air pollution.</p>
<p>The categorical variable (urban vs.&nbsp;rural) is represented as a dummy variable, and air pollution enters as a covariate.</p>
<ul>
<li><strong>Dataset Overview:</strong> 200 observations of bird density across urban and rural sites, each with a measured level of air pollution.</li>
</ul>
</section>
<section id="why-were-running-the-ancova" class="level3" data-number="12.5.3">
<h3 data-number="12.5.3" class="anchored" data-anchor-id="why-were-running-the-ancova"><span class="header-section-number">12.5.3</span> Why We’re Running the ANCOVA</h3>
<ul>
<li><p><strong>Research Question:</strong> Does the effect of air pollution on bird density differ between urban and rural areas?</p></li>
<li><p><strong>Expectation:</strong> Air pollution will have a stronger negative effect in urban areas than in rural areas.</p></li>
</ul>
</section>
<section id="null-and-alternative-hypotheses-in-our-example-ancova" class="level3" data-number="12.5.4">
<h3 data-number="12.5.4" class="anchored" data-anchor-id="null-and-alternative-hypotheses-in-our-example-ancova"><span class="header-section-number">12.5.4</span> Null and Alternative Hypotheses in our example ANCOVA</h3>
<ol start="0" type="1">
<li><p><strong>Omnibus (adjusted means) hypothesis</strong> After adjusting for air pollution, do urban and rural sites differ in mean bird density?</p>
<p><span class="math inline">\(H_{0}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p><span class="math inline">\(H_{A}: \mu_{\text{Urban, adj}}  \neq \mu_{\text{Rural, adj}}\)</span></p>
<p>Here, <span class="math inline">\(\mu_{\text{Urban, adj}}\)</span> and <span class="math inline">\(\mu_{\text{Rural, adj}}\)</span> are the <em>adjusted</em> group means once the covariate (air pollution) is accounted for.</p></li>
<li><p><strong>Slope (interaction) hypothesis</strong></p>
<p>Does air pollution affect bird density in the same way across urban and rural sites?</p>
<p><span class="math inline">\(H_{0,1}: \beta_{\text{interaction}} = 0\)</span></p>
<p><span class="math inline">\(H_{A,1}: \beta_{\text{interaction}} \neq 0\)</span></p>
<p>A significant interaction means the slopes differ, and air pollution’s relationship with bird density depends on area type.</p></li>
<li><p><strong>Intercept (baseline difference) hypothesis</strong></p>
<p>If slopes are parallel (interaction not significant), do the adjusted means differ?</p>
<p><span class="math inline">\(H_{0,2}: \beta_{0,\text{Urban}} = \beta_{0,\text{Rural}}\)</span></p>
<p><span class="math inline">\(H_{A,2}: \beta_{0,\text{Urban}} \neq \beta_{0,\text{Rural}}\)</span></p>
<p>Rejecting <span class="math inline">\(H_{0,2}\)</span> indicates an inherent group difference in bird density that is independent of pollution.</p></li>
</ol>
</section>
<section id="analysis" class="level3" data-number="12.5.5">
<h3 data-number="12.5.5" class="anchored" data-anchor-id="analysis"><span class="header-section-number">12.5.5</span> Analysis</h3>
<p>Before we look at the model results, it’s always good practice to <strong>look at the data first</strong>.</p>
<p>Visual inspection helps us check for broad patterns and see whether the model output later “makes sense.”</p>
<p>Let’s start with the response variable—<strong>bird density</strong>. This will give us a quick visual sense of whether urban and rural areas differ in their average values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot for bird density by area type</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(AreaType, BirdDensity)) <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>(<span class="at">base_size=</span><span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bird Density by Area Type"</span>, <span class="at">x =</span> <span class="st">"Area Type"</span>, <span class="at">y =</span> <span class="st">"Bird Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="12-ANCOVA_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>At first glance, bird density appears <strong>higher in rural areas</strong> than in urban ones, consistent with what we might expect ecologically.</p>
<p>Next, check the <strong>covariate</strong>, air pollution.</p>
<p>If the covariate differs sharply between groups, ANCOVA will “adjust” for that difference.</p>
<p>If it doesn’t, group comparisons will look more like a simple ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(AreaType, AirPollution)) <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>(<span class="at">base_size=</span><span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Air Pollution by Area Type"</span>, <span class="at">x =</span> <span class="st">"Area Type"</span>, <span class="at">y =</span> <span class="st">"Air Pollution"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="12-ANCOVA_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>Air pollution looks fairly similar between urban and rural sites—there’s no obvious systematic difference.</p>
<p>This isn’t diagnostic, but it helps us <strong>anticipate what the model might show</strong>: we may find that group differences in bird density aren’t explained by pollution alone.</p>
</section>
<section id="results-of-the-ancova-model" class="level3" data-number="12.5.6">
<h3 data-number="12.5.6" class="anchored" data-anchor-id="results-of-the-ancova-model"><span class="header-section-number">12.5.6</span> Results of the ANCOVA Model</h3>
<p>Now that we’ve explored the data visually, we can test our hypotheses formally using ANCOVA.</p>
<p><strong>Step 1: Fit the ANCOVA model</strong>.</p>
<p><code>ancova &lt;- aov(BirdDensity ~ AirPollution * AreaType, data = data)</code></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>ANCOVA Table</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sumsq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">meansq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AirPollution</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.7690</td>
</tr>
<tr class="even">
<td style="text-align: left;">AreaType</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1687.99</td>
<td style="text-align: right;">1687.99</td>
<td style="text-align: right;">24.79</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AirPollution:AreaType</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">291.26</td>
<td style="text-align: right;">291.26</td>
<td style="text-align: right;">4.28</td>
<td style="text-align: right;">0.0399</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">13347.09</td>
<td style="text-align: right;">68.10</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Step 2: Interpret each term in light of the hypotheses</strong></p>
<p><strong>0. Omnibus (adjusted means)</strong> :</p>
<p><span class="math inline">\(H_{0}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p>The overall ANCOVA test examines whether adjusted means differ between groups after accounting for the covariate.</p>
<p>Because we included an interaction term, this omnibus test is <strong>decomposed</strong> into two parts:</p>
<ul>
<li><p>the <strong>interaction</strong> (slope difference), and</p></li>
<li><p>the <strong>main effects</strong> (covariate and group).</p></li>
</ul>
<p>So we interpret the omnibus test through these individual terms rather than as a separate <span class="math inline">\(p\)</span>-value.</p>
<p><strong>1. Interaction (slope difference)</strong>:</p>
<p><span class="math inline">\(H_{0,1}: \beta_{\text{interaction}} = 0\)</span></p>
<p>The interaction between air pollution and area type is <strong>significant</strong> (<span class="math inline">\(p = 0.0399\)</span>).</p>
<p>Reject <span class="math inline">\(H_{0,1}\)</span> → our slopes are not parallel. Air pollution’s relationship with bird density depends on area type.</p>
<p><strong>2. Covariate (main effect of Air Pollution)</strong></p>
<p>Although not a formal ANCOVA hypothesis, this term tests whether air pollution predicts bird density <em>on average</em>, across both groups.</p>
<p>It is <strong>not significant</strong> (<span class="math inline">\(p = 0.7690\)</span>), so air pollution alone does not explain much variation.</p>
<p><strong>3. Group (main effect of Area Type)</strong> – <span class="math inline">\(H_{0,2}: \mu_{\text{Urban, adj}} = \mu_{\text{Rural, adj}}\)</span></p>
<p>Area type is <strong>significant</strong> (<span class="math inline">\(p &lt; 0.001\)</span>), suggesting lower average bird density in urban areas.</p>
<p>However, because the interaction is significant, this group difference changes with air pollution level, so it should be interpreted conditionally, not as a single overall difference.</p>
<p>Reject <span class="math inline">\(H_{0,2}\)</span> with caution.</p>
<p><strong>Step 3: Examine regression coefficients</strong></p>
<p>We can also fit the same model using <code>lm()</code> to view the <strong>regression coefficients</strong> directly.</p>
<p>This shows how each term contributes to predicting bird density and corresponds to the hypothesis tests we just discussed.</p>
<p><code>ancova_lm &lt;- lm(BirdDensity ~ AirPollution * AreaType, data = data)</code></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Linear Model Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">31.546</td>
<td style="text-align: right;">2.286</td>
<td style="text-align: right;">13.80</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution</td>
<td style="text-align: right;">-0.043</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">-1.75</td>
<td style="text-align: right;">0.0816</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AreaTypeUrban</td>
<td style="text-align: right;">-11.577</td>
<td style="text-align: right;">3.022</td>
<td style="text-align: right;">-3.83</td>
<td style="text-align: right;">0.0002</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution:AreaTypeUrban</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">2.07</td>
<td style="text-align: right;">0.0399</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>These coefficients give the <em>direction</em> and <em>magnitude</em> of each effect:</p>
<ul>
<li><strong>(Intercept):</strong> estimated mean bird density for rural sites (the reference group) when air pollution is zero.</li>
<li><strong>AirPollution:</strong> slope of the relationship between pollution and bird density in rural sites.</li>
<li><strong>AreaTypeUrban:</strong> difference in intercept between urban and rural areas.</li>
<li><strong>AirPollution:AreaTypeUrban:</strong> difference in slope between urban and rural areas (the interaction).</li>
</ul>
<p><strong>Step 4: Visualize the interaction</strong></p>
<p>As always, plotting helps confirm what the model tells us.</p>
<p>A scatter plot with fitted regression lines lets us see how air pollution relates to bird density for each area type.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="12-ANCOVA_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>Here, the slopes differ by area type, illustrating the <strong>significant interaction</strong> we detected statistically.</p>
<p>You’ll also notice quite a bit of scatter around each line, which makes sense—our overall <span class="math inline">\(R^2\)</span> is only <strong>0.116</strong>.</p>
<p>Remember, <span class="math inline">\(R^2\)</span> represents the <strong>proportion of variance in bird density explained by the model</strong>.</p>
<p>So, about <strong>12% of the variation</strong> in bird density is explained by air pollution, area type, and their interaction.</p>
<p>The remaining 88% reflects other factors, measurement noise, or natural ecological variability not captured by this simple model.</p>
<p><strong>Step 5: Centering the covariate</strong></p>
<p>Interpreting intercepts at <span class="math inline">\(x = 0\)</span> can be misleading when “zero pollution” isn’t meaningful.</p>
<p>By centering the covariate (subtracting its mean), we make the intercept represent <strong>average bird density at mean air pollution</strong> instead.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Centered ANCOVA Model Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">27.814</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution_c</td>
<td style="text-align: right;">-0.043</td>
<td style="text-align: right;">0.0816</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AreaTypeUrban</td>
<td style="text-align: right;">-5.810</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AirPollution_c:AreaTypeUrban</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.0399</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This re-centering doesn’t change the slopes or <span class="math inline">\(p\)</span>-values—it just shifts the intercepts, making them easier to interpret.</p>
<p><strong>Interpreting the Centered Model</strong></p>
<p>Centering does <strong>not</strong> change the slopes or their <span class="math inline">\(p\)</span>-values.</p>
<p>Notice that the coefficients for <code>AirPollution_c</code> (–0.04) and <code>AirPollution_c:AreaTypeUrban</code> (+0.07) are <strong>identical</strong> to the slopes we estimated before centering.</p>
<p>Only the <strong>intercept</strong> and the <strong>AreaTypeUrban</strong> (group difference) term have changed — they are now interpreted at the <em>mean pollution level</em> instead of pollution = 0.</p>
<ul>
<li><p><strong>Intercept (27.8):</strong> Predicted bird density for <strong>rural sites</strong> at <em>average air pollution</em>.</p></li>
<li><p><strong>AreaTypeUrban (–5.8):</strong> Urban sites have, on average, <strong>about 6 fewer birds</strong> than rural sites <em>at the same mean pollution level</em>.</p></li>
<li><p><strong>AirPollution_c (–0.04):</strong> Slope for rural sites — bird density decreases slightly as pollution increases.</p></li>
<li><p><strong>Interaction (+0.07):</strong> Difference in slopes between groups. The urban slope = –0.04 + 0.07 ≈ <strong>+0.03</strong>, meaning bird density increases slightly with pollution in urban areas.</p></li>
</ul>
<p><strong>Step 6: Summarize and Interpret</strong></p>
<p>The significant interaction shows that <strong>air pollution’s effect on bird density depends on area type</strong>: in rural sites, bird density decreases slightly as pollution rises, while in urban sites, it increases slightly.</p>
<p>Because the interaction is significant, we focus on these <strong>different slopes</strong>, not on adjusted mean differences.</p>
<p>If the interaction had <strong>not</strong> been significant, we would instead drop the interaction term and interpret the <strong>parallel slopes model</strong>, comparing adjusted means between groups.</p>
<p>Our results sentences might look something like this:</p>
<p>Results from the ANCOVA indicated that air pollution’s effect on bird density depended on area type, <em>F</em>(1, 196) = 4.28, <em>p</em> = .0399. Bird density declined with increasing pollution in rural sites but showed a slight increase in urban sites. These findings suggest that <strong>urbanization modifies the pollution–bird density relationship</strong> and may point toward the need for area-specific conservation strategies.</p>
<p><strong>Key takeaways</strong></p>
<ol type="1">
<li>Always <strong>check for interaction first</strong></li>
<li>If interaction is <strong>significant</strong>, interpret slope differences.</li>
<li>If not, <strong>fit the reduced model</strong> (no interaction) and compare adjusted means.</li>
<li>Center covariates when the intercept needs to represent a meaningful point.</li>
</ol>
</section>
</section>
<section id="chapter-summary" class="level2" data-number="12.6">
<h2 data-number="12.6" class="anchored" data-anchor-id="chapter-summary"><span class="header-section-number">12.6</span> Chapter Summary</h2>
<p>In this chapter, we introduced <strong>ANCOVA</strong> as an extension of ANOVA that includes continuous covariates. We began by framing ANOVA within the linear modeling framework, showing how ANCOVA builds on it by combining categorical and continuous predictors. Using examples such as bird density across urban and rural environments, we developed and tested null and alternative hypotheses step by step. The main advantage of ANCOVA is its ability to adjust for continuous variables, allowing clearer interpretation of group effects.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-mallory_barnes" class="csl-entry" role="listitem">
Barnes, Mallory L. 2023. <em>Statistics for Environmental Science</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./11-MixedANOVA.html" class="pagination-link" aria-label="More On Factorial Designs">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./13-Thinking.html" class="pagination-link" aria-label="Thinking about answering questions with data">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Thinking about answering questions with data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/malloryb/statistics_E538/edit/master/12-ANCOVA.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>